### ISSUE TITLE
Rapberry Pi - Raspbian - Help

### ISSUE THREAD

**Issue by hestuppfodarn** [InstaPy/InstaPy#1010]
Hi Guys,

I'm currently trying to get the script working on my RPI3.

I've followed the instructions but cannot get it to work. 
PyCharm is the program I'm using to create a virtualenv and use it as projects interpreter.

Using Rasbpian, have latest Selenium and Geckodriver.

What happens? The script starts and then Firefox opens but then immediately closes.
 
The following error message occurs:

```
/home/pi/venvpia/bin/python "/home/pi/Projects/Leif/InstaPy-master-SQGD/Campaign – SQGD.py"
Traceback (most recent call last):
  File "/home/pi/Projects/Leif/InstaPy-master-SQGD/Campaign – SQGD.py", line 63, in <module>
    session = InstaPy(username=insta_username, password=insta_password, use_firefox=True, page_delay=25, nogui=False)
  File "/home/pi/Projects/Leif/InstaPy-master-SQGD/instapy/instapy.py", line 126, in _init_
    self.set_selenium_local_session()
  File "/home/pi/Projects/Leif/InstaPy-master-SQGD/instapy/instapy.py", line 150, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/home/pi/venvpia/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 80, in _init_
    self.binary, timeout)
  File "/home/pi/venvpia/local/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in _init_
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/home/pi/venvpia/local/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/home/pi/venvpia/local/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpMQhqrg If you specified a log_file in the FirefoxBinary constructor, check it for details.


Process finished with exit code 1

```

Anyone else had this problem or could advise me? Thanks

**Comment by bartosjiri** [comment]
I have the same problem. Try running the script like 10 times in the row, it usually starts working eventually. 

However, a proper solution is indeed needed.

**Comment by gedankenstrom** [comment]
run: 
sudo xvfb-run python3.5 yourconfig.py
