### ISSUE TITLE
Can i run this on pythonanywhre ??

### ISSUE THREAD

**Issue by Tokyysek** [InstaPy/InstaPy#1011]
Hello i want set up this bot on pythonanywhere it is free cloud server with two consoles free

**Comment by converge** [comment]
sounds good, tell us if you need some help

**Comment by Tokyysek** [comment]
@converge i have a problem i succesfully install it on cloud but i dont really know how to run that

**Comment by converge** [comment]
maybe it helps: https://www.youtube.com/watch?v=2Ci-hXU1IEY

**Comment by Tokyysek** [comment]
this is diferent to this https://ctrlv.cz/wJ5i
i have acces to files

**Comment by Tokyysek** [comment]
How can i setup that

**Comment by Tokyysek** [comment]
https://ctrlv.cz/onZu
i tryed to install selenium

**Comment by RomeoJuliett** [comment]
@Tokyysek try running the sudo command.

sudo install "whatever you want"

I run docker containers at work and they can be really weird when using certain commands. I have never run this script on Pythonanywhere though.

**Comment by daaanny90** [comment]
I resume this issue because I have some problem with that.
First of all, you can run it on Pythonanywhere, you have to clone the project in the home folder with the bash console, than set the bot to use firefox (on pythonanywhere you can use selenioum, but only firefox is supported).
It's almost like a normal installation.
My problem is this:
`INFO - Session started - 2017-12-08 11:43:43
Traceback (most recent call last):
  File "quickstart.py", line 9, in <module>
    session.login()
  File "/home/danny90/InstaPy/instapy/instapy.py", line 220, in login
    self.switch_language):
  File "/home/danny90/InstaPy/instapy/login_util.py", line 25, in login_user
    "//article/div/div/p/a[text()='Log in']")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: {"method":"xpath","selector":"//article/div/div/p/a[text()='Log in']"
}
Stacktrace:
    at FirefoxDriver.findElementInternal_ (file:///tmp/tmpLYSoRH/extensions/fxdriver@googlecode.com/components/driver-component.js:10770)
    at fxdriver.Timer.setTimeout/<.notify (file:///tmp/tmpLYSoRH/extensions/fxdriver@googlecode.com/components/driver-component.js:625)`

Somebody knows how to go over it?

**Comment by daaanny90** [comment]
I did some test to reproduce the exception. It look like the problem is not pythonanywhere but firefox. Pythonanywhere uses Firefox 17, I installed it on my computer and tried to run it, but when it comes the moment to load the page https://www.instagram.com the page doesn't load, it stays empty, and after few seconds Instapy gives this exception 

`selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: {"method":"xpath","selector":"//article/div/div/p/a[text()='Log in']" }`

Of course, there is no "Log in" at all!

<img width="989" alt="schermata 2017-12-09 alle 10 40 19" src="https://user-images.githubusercontent.com/24957034/33794488-6adeab90-dccd-11e7-8ef6-590101371bf3.png">

It could be a compatibility problem with Firefox 17?

**Comment by daaanny90** [comment]
Another update, I tried to load the page without style and I saw this 
<img width="990" alt="schermata 2017-12-10 alle 15 00 36" src="https://user-images.githubusercontent.com/24957034/33805769-4b611752-ddbe-11e7-887c-1c138115479f.png">
The key is to go over it with firefox 17 and then it will possible to run Instapy on pythonanywhere.
Somebody knows how?
[I posted also a question on stackoverflow ](https://stackoverflow.com/questions/47739636/how-to-load-instagram-on-firefox-17-through-selenium-on-pythonanywhere?sfb=2)

**Comment by daaanny90** [comment]
@converge @timgrossmann sorry for the tag but it could be important and useful to somebody. Pythonanywhere gives the chance to run Instapy on a server for free, not bad. But right know is impossible.

**Comment by converge** [comment]
hey guys, InstaPy is open source, softwares like this coasts $100/month, paying 5% of the software coast in a decent server is a nice idea. Don't understand me wrong, but Digital Ocean offers $5 vps, check it out:
https://www.digitalocean.com/pricing/#droplet

**Comment by arthurecommerce** [comment]
@daaanny90 Any updates?

**Comment by ianmonat** [comment]
Hi - I'm trying to run Instapy on pythonanywhere as well. Is the verdict still that it is impossible?

Here's the error message I got. I'm kind of a noob and not great at diagnosing errors so if someone can help, that would be great:

```
(instapy) 06:12 ~/instapy (master)$ /home/ianmonat/.virtualenvs/instapy/bin/python /home/ianmonat/instapy/quickstart.py
ERROR [2018-06-06 06:13:39] [caliweedjobs]  Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.4.0-1060-aws x86_64)
Traceback (most recent call last):
  File "/home/ianmonat/instapy/instapy/instapy.py", line 276, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/ianmonat/.virtualenvs/instapy/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/ianmonat/.virtualenvs/instapy/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ianmonat/.virtualenvs/instapy/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ianmonat/.virtualenvs/instapy/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/home/ianmonat/.virtualenvs/instapy/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.4.0-1060-aws x86_64)
Traceback (most recent call last):
  File "/home/ianmonat/instapy/instapy/instapy.py", line 276, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/ianmonat/.virtualenvs/instapy/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/ianmonat/.virtualenvs/instapy/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ianmonat/.virtualenvs/instapy/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ianmonat/.virtualenvs/instapy/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/home/ianmonat/.virtualenvs/instapy/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.4.0-1060-aws x86_64)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ianmonat/instapy/quickstart.py", line 23, in <module>
    multi_logs=True)
  File "/home/ianmonat/instapy/instapy/instapy.py", line 170, in __init__
    self.set_selenium_local_session()
  File "/home/ianmonat/instapy/instapy/instapy.py", line 280, in set_selenium_local_session
```

**Comment by daaanny90** [comment]
My experience is that is unfortunately impossible. As they still use Firefox 17.

A free solution could be AWS, they give the chance to use it for free with some limits (but they are quite large). Better than Pythonanywhere, more customizable and without this kind of problems. And free.
