### ISSUE TITLE
Element is not clickable at point (188, 530)

### ISSUE THREAD

**Issue by HONGAA** [InstaPy/InstaPy#1027]
Recently started getting this error. Instapy, selenium and chromedriver are up to date.

```
Traceback (most recent call last):
  File "quickstart.py", line 19, in <module>
    session.set_dont_unfollow_active_users(enabled=True, posts=3)
  File "C:\Users\Kenny\Desktop\Instapy\instapy\instapy.py", line 1470, in set_dont_unfollow_active_users
    self.logger)
  File "C:\Users\Kenny\Desktop\Instapy\instapy\util.py", line 122, in get_active_users
    "(//div[contains(@class, '_si7dy')])[1]").click()
  File "C:\Users\Kenny\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.
py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kenny\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.
py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kenny\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.p
y", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kenny\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandle
r.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element is not clickable at point (188, 530)
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.14393 x86_6
4)
```

**Comment by converge** [comment]
hey mate, youre chrome driver is outdated, could you update it and try again ? also update InstaPy to latest version.

**Comment by HONGAA** [comment]
thanks - I'm trying to download the newest version of chromedriver from https://chromedriver.storage.googleapis.com but when i run the exe file, it says "only local connections are allowed." Is there another way to update chromedriver?

**Comment by converge** [comment]
check it out: https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by HONGAA** [comment]
Yep- I'm trying to download the latest chromedriver from here but I get this:

```
Starting ChromeDriver 2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f) on port 9515
Only local connections are allowed.
```

Sorry.. do you know how to get around this?

**Comment by converge** [comment]
this is a warning, everything is fine. Got it to work ?

**Comment by HONGAA** [comment]
No, unfortunately not yet..

**Comment by converge** [comment]
Do you have slack ? check out slack channel at REAME, I can help you.
