### ISSUE TITLE
Selenium Chrome Driver Trouble

### ISSUE THREAD

**Issue by mehdi691** [InstaPy/InstaPy#1028]
Hi, 

My script use to work nicely and now I have a trouble which came from nowhere...
## Current Behavior

Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password)
  File "/Users/Mehdi/Desktop/InstaPy/instapy/instapy.py", line 128, in __init__
    self.set_selenium_local_session()
  File "/Users/Mehdi/Desktop/InstaPy/instapy/instapy.py", line 187, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 102, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service ./assets/chromedriver

## Possible Solution (optional)

I dowloaded geckodriver (Firefox), I put in the path /usr/local/bin. I modifier quick start.py by adding use_firefox=True. I still have the same error...
I

**Comment by edison12a** [comment]
Hello, In the issue title, you say "Selenium Chrome Driver Trouble" definitely talking about chrome but in your trouble-shooting steps you are actually trouble shooting Firefox; "I dowloaded geckodriver (Firefox)". Those are two different browsers please.

I suspect your issue is one that results from auto-updates. Selenium behaviour is sometimes messy for latest browser updates.

Suggested Solution: Have you tried rolling back your chrome version to the version that ran smoothly and see ?
