### ISSUE TITLE
quickstart.py not executing 

### ISSUE THREAD

**Issue by drcyber975** [InstaPy/InstaPy#1038]
I have the same problem as before even after taking your advice of using the quickstart.py as a template. this is my script: 
```python
from instapy import InstaPy

insta_username = 'username'
insta_password = 'password'

# if you want to run this script on a server, 
# simply add nogui=True to the InstaPy() constructor
session = InstaPy(username=insta_username, password=insta_password)
session.login()

# set up all the settings
session.set_upper_follower_count(limit=1000)
session.set_do_comment(True, percentage=0)
session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
session.set_dont_include(['friend1', 'friend2', 'friend3'])
session.set_dont_like(['pizza', 'girl'])

session.follow_user_followers(['kimkardashian', 'selenagomez', 'natgeo'], amount=37, randomize=False, sleep_delay=60)

# do the actual liking
session.like_by_tags(['natgeo', 'world'], amount=100)

# end the bot session
session.end()
```
2
this is the error message i receive from using the command "python quickstart.py"

```bash
python quickstart.py
python: can't open file 'quickstart.py': [Errno 2] No such file or directory
lubuntu@lubuntu:~$ cd
lubuntu@lubuntu:~$ cd InstaPy
lubuntu@lubuntu:~/InstaPy$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password)
  File "/home/lubuntu/InstaPy/instapy/instapy.py", line 126, in __init__
    self.set_selenium_local_session()
  File "/home/lubuntu/InstaPy/instapy/instapy.py", line 177, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 151, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 240, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to write automation extension zip
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.8.0-56-generic x86_64)
```
 
sorry to be a pain i really want this to work and cant understand what i am doing wrong i am following the codes so precisely.

**Comment by Naramsim** [comment]
Please, remove the comments above, they render in Markdown.

Give us more information, if you use the template quickstart, why don't you use the issue template?

**Comment by drcyber975** [comment]
okay so the comments you used above the code such as #do the actual liking. i should remove the comments from the code?

**Comment by drcyber975** [comment]
just now i used the exact same template as quickstart.py all i added was my username and password and it wasnt working :/

**Comment by converge** [comment]
@drcyber975 , what's your chrome version (not chrome driver) ?

**Comment by converge** [comment]
no return, closing..
