### ISSUE TITLE
not starting anymore

### ISSUE THREAD

**Issue by wizarduk** [InstaPy/InstaPy#1042]
is there a issue as all my accounts have stopped working

/root/InstaPy && python3.4

when i try to run it just goes blank now ?

**Comment by wizarduk** [comment]
This is the error 

File "/root/InstaPy/instapy/instapy.py", line 186, in login
    self.switch_language):
  File "/root/InstaPy/instapy/login_util.py", line 18, in login_user
    "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav[@class='_luodr']/ul[@class='_g8wl6']/li[@class='_538w0'][10]/span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=62.0.3202.75)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 2.6.32-042stab125.3 x86_64)

**Comment by wizarduk** [comment]
any idea anyone ?

**Comment by hestuppfodarn** [comment]
You have the lastest chromdriver? 
What version of Selenium do you have?

**Comment by wizarduk** [comment]
This is working on another VPS so im clueless to the issue with the same drivers

**Comment by wizarduk** [comment]
INFO - Session started - 2017-12-06 15:28:12
Traceback (most recent call last):
  File "quickstart.py", line 9, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 219, in login
    self.switch_language):
  File "/root/InstaPy/instapy/login_util.py", line 9, in login_user
    browser.get('https://www.instagram.com')
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_respon            se
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 2.6.32-042stab125            .3 x86_64)

**Comment by wizarduk** [comment]
I havent a clue why its not working i have tried everything and reinstalled everything and its still not woking any ideas ?

**Comment by converge** [comment]
@wizarduk maybe a firewall is blocking your connection to instagram. try to get instagram ips and ping it or do some call using curl

**Comment by kidz55** [comment]
same here ! same problem ! any up on this subject @wizarduk ?

**Comment by wizarduk** [comment]
Works fine end

**Comment by converge** [comment]
[fixed](https://github.com/timgrossmann/InstaPy/pull/1328)
