### ISSUE TITLE
Instapy crashing

### ISSUE THREAD

**Issue by ediooo** [InstaPy/InstaPy#1055]
Hi,
Any idea why instapy always crashes with this message over here?

Thanks a ton for any hints what might be wrong (maybe with my configuration?)

Traceback (most recent call last):
  File "instapy_sw.py", line 5, in <module>
    from instapy import InstaPy
  File "/Users/dk/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/Users/dk/InstaPy/instapy/instapy.py", line 15, in <module>
    from .clarifai_util import check_image
  File "/Users/dk/InstaPy/instapy/clarifai_util.py", line 3, in <module>
    from clarifai import rest
  File "build/bdist.macosx-10.6-x86_64/egg/clarifai/rest/__init__.py", line 3, in <module>
  File "build/bdist.macosx-10.6-x86_64/egg/clarifai/rest/client.py", line 19, in <module>
  File "/Users/dk/miniconda2/lib/python2.7/site-packages/configparser-3.5.0-py2.7.egg/configparser.py", line 12, in <module>
    from backports.configparser import (
ImportError: No module named configparser

**Comment by timgrossmann** [comment]
@ediooo Please refer to other issues before opening a new one.

If there is any error that says `No module named xxxxxx` then please, please simply do:

```bash
pip install xxxxxx

# in your case
pip install configparser
```

it might also make sense to google the error before opening a new issue here:
https://techglimpse.com/fix-no-module-named-import-error/
