### ISSUE TITLE
CRITICAL - Wrong login data! & follow_given_user_followers not working

### ISSUE THREAD

**Issue by hijak** [InstaPy/InstaPy#1061]
## Expected Behavior
able to login and run the script. The creds are 100% correct
## Current Behavior
fails
```
Selenium is up - executing command
INFO - Session started - 2017-12-08 09:34:38
CRITICAL - Wrong login data!
WARNING - There are 0 people to follow
ERROR - following_link error list index out of range
Traceback (most recent call last):
  File "docker_quickstart.py", line 30, in <module>
    bot.follow_user_followers(['USER1', 'USER2', 'USER3'], amount=10)
  File "/code/instapy/instapy.py", line 1173, in follow_user_followers
    self.logger)
  File "/code/instapy/unfollow_util.py", line 724, in follow_given_user_followers
    allfollowing,
UnboundLocalError: local variable 'allfollowing' referenced before assignment
```
## InstaPy configuration
```
from instapy import InstaPy

# Write your automation here
# Stuck ? Look at the github page or the examples in the examples folder

insta_username = 'MYUSERNAME'
insta_password = 'MYPASSWORD'

dont_like = ['food', 'ETC']
ignore_words = ['pizza', 'love']
friend_list = ['BLAH1, 'BLAH2' ]

bot = InstaPy(username=insta_username, password=insta_password, selenium_local_session=False)
bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub')
bot.login()
bot.set_upper_follower_count(limit=5000)
bot.set_do_comment(False)
bot.set_dont_include(friend_list)
bot.set_dont_like(dont_like)
bot.set_ignore_if_contains(ignore_words)
bot.set_dont_unfollow_active_users(enabled=False, posts=2)
bot.set_ignore_users(['THATUSER'])
bot.set_do_follow(enabled=True, percentage=10, times=1)
bot.like_by_tags(['TAGS'], amount=200)
bot.follow_user_followers(['USER1', 'USER2', 'USER3'], amount=10)
bot.unfollow_users(amount=10, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 )
bot.end()
```

**Comment by hijak** [comment]
Hi

I have fixed incorrect login data. when viewed via VNC it seemed to be stuck on the page of one of my follow_user_followers users
