### ISSUE TITLE
Logging in and then breaking: No such element

### ISSUE THREAD

**Issue by wendyhouserules** [InstaPy/InstaPy#1065]
Current behaviour:
Logs in
Lands on feed
Looks at profile
Back to feed
Stops

Has the xpath changed on one of the elements? 
I'm getting this error:

(env) iMac:instapy user$ python3 quickstart.py
Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    session.login()
  File "....../InstaPy/instapy/instapy.py", line 186, in login
    self.switch_language):
  File "....../InstaPy/instapy/login_util.py", line 18, in login_user
    "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
  File "....../env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "....../env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 855, in find_element
    'value': value})['value']
  File "....../env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "....../env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav[@class='_luodr']/ul[@class='_g8wl6']/li[@class='_538w0'][10]/span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.11.6 x86_64)

**Comment by Klyado** [comment]
Same here :(

**Comment by rfargetton** [comment]
This issue has been sorted out here
#1279

**Comment by converge** [comment]
[fixed](https://github.com/timgrossmann/InstaPy/pull/1328)
