### ISSUE TITLE
Unable to login on Windows after filling up username

### ISSUE THREAD

**Issue by Cineda** [InstaPy/InstaPy#1086]
I have been trying to solve this issue for days but I can't seem to figure out what's wrong. I uninstalled every python version I have as well as reinstalled InstaPy, but the error still persist. 

Whenever I run the script, Chrome would open and then InstaPy would fill up the username. Then it stops there and gives me this error on power-shell.

Any idea what I could do to solve this?

Many thanks to those that are behind this amazing project BTW!

```
[PS C:\Users\username\Downloads\InstaPy> py.exe .\instaScript.py

DevTools listening on ws://127.0.0.1:12381/devtools/browser/15ee9f48-c419-4bf6-b0ba-2668b38e0f6b
INFO - Session started - 2017-12-12 19:07:39
CRITICAL - Sorry, Record Activity is not working on Windows. We're working to fix this soon!
Traceback (most recent call last):
  File ".\instaScript.py", line 7, in <module>
    session.login()
  File "C:\Users\username\Downloads\InstaPy\instapy\instapy.py", line 219, in login
    self.switch_language):
  File "C:\Users\username\Downloads\InstaPy\instapy\login_util.py", line 39, in login_user
    "//input[@name='password']")
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 886, in find_elements
    'value': value})['value'] or []
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: missing or invalid 'entry.level'
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.16299 x86_64)

PS C:\Users\username\Downloads\InstaPy> [13748:12376:1212/190938.373:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[13748:12376:1212/190938.373:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[13748:12376:1212/190938.374:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED](url)
```

**Comment by Cineda** [comment]
Did another clean install this time, somehow its working again. 
Thanks anyway!!
