### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by mlwrose** [InstaPy/InstaPy#1107]
Hi there please help.

Struggling with my installation on my Raspberry Pi

After all my Pip installs and Google driver errors fixed, im getting this error now.

OSError: [Errno 8] Exec format error

please advise? thanks

**Comment by gitpatrickhub** [comment]
@mlwrose have you tried switching to firefox? What version of debian are you using?

**Comment by mlwrose** [comment]
Hi Patrick,

im using linux raspberrypi 4.9.59-v7+

i havent tried firefox yet.

But i just installed it. but im still getting the same error message when i run quickstart.py

see below for error:

Traceback (most recent call last):
  File "quick_m.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password)
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 128, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 187, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by gitpatrickhub** [comment]
@mlwrose the Raspberry Pi how to doc is out of date, but essentially it's these steps;

```
git clone https://github.com/timgrossmann/InstaPy.git
cd InstaPy
sudo pip install . 
```
Use the below site to figure out what version of firefox you need (copy commands);
http://mozilla.debian.net/

then get the latest geckodriver

New releases can be found in https://github.com/mozilla/geckodriver/releases
```
wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-arm7hf.tar.gz
tar -xvzf geckodriver-v*
chmod +x geckodriver
sudo cp geckodriver /usr/local/bin/
```
Then modify your quickstart.py file with 

```
session = InstaPy(username=insta_username, password=insta_password, use_firefox=True)
```

**Comment by mlwrose** [comment]
thanks Patrick,

Im definitely making progress and the code is executing.

but im running into this now error now "connection refused"?

Traceback (most recent call last):
  File "quick_m.py", line 10, in <module>
    session = InstaPy(username=insta_username, password=insta_password, use_firefox=True)
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 128, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 152, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

**Comment by mlwrose** [comment]
also the new firefox window launches, but stays blank?

**Comment by gitpatrickhub** [comment]
Any details in the geckodriver.log ?

the web browser will load as normal when it's working correctly.

**Comment by mlwrose** [comment]
Hi Patrick, 
im a bit unsure about what you mean?
how do i access the geckodriver.log? 
sorry im a beginner at this.
regards,
Matthew

**Comment by mlwrose** [comment]
when i ran 
geckodriver.log 

in the terminal it said bash: geckodriver.log command not found

**Comment by gitpatrickhub** [comment]
The log file should be in the same directory as python, but if you can't locate it. There's no harm in trying this;
```
sudo pip install pyvirtualdisplay
```

If it wasn't installed already that was likely your problem.

**Comment by mlwrose** [comment]
ok i have successfully installed pyvirtualdisplay 

but its still the same error and launch blank screen.

Traceback (most recent call last):
File "quick_m.py", line 10, in 
session = InstaPy(username=insta_username, password=insta_password, use_firefox=True)
File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 128, in init
self.set_selenium_local_session()
File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 152, in set_selenium_local_session
self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 158, in init
keep_alive=True)
File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in init
self.start_session(desired_capabilities, browser_profile)
File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
response = self.execute(Command.NEW_SESSION, parameters)
File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
self.error_handler.check_response(response)
File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

**Comment by gitpatrickhub** [comment]
What version of firefox, selenium and geckodriver do you have?

For reference, I am running with the following;

Python 3.5
Selenium 2.53.6
Firefox-esr 52.3.0
Geckodriver  0.19.0

**Comment by mlwrose** [comment]
FIREFOX ESR 52.5.2 (32-bit)

SELENIUM
DATA
    __version__ = '3.8.0'

VERSION
    3.8.0

geckodriver 0.19.1

**Comment by gitpatrickhub** [comment]
I'm not an expert, but I would try downgrading your selenium version to 2.53.6

```
sudo pip uninstall selenium
sudo pip install selenium==2.53.6
```

**Comment by mlwrose** [comment]
Thanks for trying Patrick. i will keep you updated when i get it solved.

:)

**Comment by gitpatrickhub** [comment]
One last thought, when you execute the script from the command line are you using sudo? i.e.,
```
sudo python quickstart.py 
```

**Comment by mlwrose** [comment]
hmmm, ok when i run that i get a new error.
'Import error: no module names clarifai.rest'
but when i pip install clarifai.rest
i get
collecting clarifai.rest
Could not find version that satisfies version.
no matching distribution found

**Comment by gitpatrickhub** [comment]
```
pip install git+git://github.com/Clarifai/clarifai-python.git
```
or just comment out the line in the instapy.py file that says import from clarifai

**Comment by mlwrose** [comment]
ok i commented out the clarifai import and it executed, but then gave me this error.

Traceback (most recent call last):
  File "quick_m.py", line 10, in <module>
    session = InstaPy(username=insta_username, password=insta_password, use_firefox=True)
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 130, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 154, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpjbWk7R If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by gitpatrickhub** [comment]
Sorry man, I haven't seen this one before. I'd verify the geckodriver is in the correct directory;
/usr/local/bin/

Other than that, I'm out of ideas.

**Comment by mlwrose** [comment]
Finally working Patrick! thank you so much for all your help yesterday. I am not sure what happened by plugged in the pi this morning and tried sudo command again and it worked. Its running very slowly but its running! thanks bro.

**Comment by BorysVrublevskyi** [comment]
I got same issue when i downloaded manually chromedriver from site. But it was 64bit and my Orange Pi Zero is ARMv71 (32bit). So I just installed it (apt install chromedriver) and copied to assets folder. And it's got ALIVE!!1

**Comment by mwargan** [comment]
@BorysVrublevskyi could you clarify what you did? I'm running into a chromedriver issue on the Pi Zero, on 3B+ it works fine...

**Comment by tE3m** [comment]
Do you know which ARM your Pi Zero is? Or do you know the exact model?

**Comment by mwargan** [comment]
@TarekJ03 
```
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 9000c1
```

**Comment by tE3m** [comment]
https://github.com/timgrossmann/InstaPy/issues/4033#issuecomment-466491400
Here's someone who made it work with a v6l:wink:

**Comment by mwargan** [comment]
@TarekJ03 thanks so much! Will give it a go now and report back - funny how we need almost half a gig package to get one file out of it :D

**Comment by playnet-team** [comment]
you need to change the default workspace which is set to /root/InstaPy 

> from instapy import set_workspace
> set_workspace(path='/home/pi/InstaPy')
