### ISSUE TITLE
 TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by TR0X** [InstaPy/InstaPy#1108]
I've chcked the output of InstaPy and found an error message in there: 
```
WARNING - Post Randomly Skipped...

Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file instapy.py, line 1314
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file instapy.py, line 1314
```

**Comment by converge** [comment]
hey @TR0X , what's your config (quickstart.py) ?

**Comment by TR0X** [comment]
Attached:

```
insta_username = '**************'
insta_password = '**************'
session = InstaPy(username=insta_username, password=insta_password, use_firefox=True, nogui=True)
session.login()
session.set_do_comment(True, percentage = 25)
session.set_comments(['Beautiful ! :)', 'Pretty! :D', 'Great photo'])
session.like_by_locations(['262309028/austria', '63134088/vienna-austria', '213933962/zermatt-switzerland'], amount=50)
session.follow_user_followers(['sonyalpha', 'kai.boet', 'menschfotograf'], amount=10, randomize=True)
session.unfollow_users(amount=10, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO')
session.set_user_interact(amount=3, randomize=True, percentage=50, media='Photo')
session.set_do_like(enabled=True, percentage=75)
session.set_comments(["Great!", "Nice one!"])
session.set_do_comment(enabled=True, percentage=10)
session.interact_user_followers(['thorstenovergaard', 'sonyalpha', 'menschfotograf', 'kai.boet', 'stephanwiesner', 'brahmino', 'macenzo', 'janske'], amount=60, random=True)
session.like_by_tags(['streetphotography', 'travelgram', 'macro', 'bokeh', 'architecture', 'photography', 'sunset', 'mountains', 'colors'], amount=55, media='Photo')
session.like_by_feed(amount=100, randomize=True, interact=True)
```

**Comment by converge** [comment]
is that the full stack trace (error message) ? Can't find where InstaPy raised it

**Comment by TR0X** [comment]
Hi! It seems so:

```
WARNING - Post Randomly Skipped...

INFO - Total of links feched for analysis: 1
INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file instapy.py, line 1314
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file instapy.py, line 1314
INFO - Total of links feched for analysis: 1
INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file instapy.py, line 1314
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file instapy.py, line 1314
INFO - Total of links feched for analysis: 1
INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARNING - Post Randomly Skipped...

INFO - Total of links feched for analysis: 1
INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARNING - Post Randomly Skipped...

```

I took a look in at the line 1314 in instapy.py:
```
self.logger.info('This link has already '
                                         'been visited:\n', link, '\n')

```

My Python skills are not the best, but imho it is not allowed to insert two strings in one logger message... (?)

**Comment by christian0101** [comment]
Try this

https://github.com/timgrossmann/InstaPy/pull/1346
