### ISSUE TITLE
Message: connection refused

### ISSUE THREAD

**Issue by mlwrose** [InstaPy/InstaPy#1109]
Hi guys,

im trying to install / setup instapy on my raspberry pi. i can get the code to execute. but it only launches my firefox browser blank. and then gives me this error in the terminal. please help!

`Traceback (most recent call last):
  File "quick_m.py", line 10, in <module>
    session = InstaPy(username=insta_username, password=insta_password, use_firefox=True)
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 128, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 152, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused`

im using 
FIREFOX ESR 52.5.2 (32-bit)

SELENIUM
DATA
    __version__ = '3.8.0'

VERSION
    3.8.0

geckodriver 0.19.1

**Comment by converge** [comment]
can you ping instagram.com ?

**Comment by mlwrose** [comment]
HI there,

yes i think so.

I did ping -c 4 instagram.com

it came back with.
```
pi@raspberrypi:~ $ ping -c 4 instagram.com
PING instagram.com (52.207.16.21) 56(84) bytes of data.
64 bytes from ec2-52-207-16-21.compute-1.amazonaws.com (52.207.16.21): icmp_seq=1 ttl=239 time=266 ms
64 bytes from ec2-52-207-16-21.compute-1.amazonaws.com (52.207.16.21): icmp_seq=2 ttl=239 time=289 ms
64 bytes from ec2-52-207-16-21.compute-1.amazonaws.com (52.207.16.21): icmp_seq=3 ttl=239 time=263 ms
64 bytes from ec2-52-207-16-21.compute-1.amazonaws.com (52.207.16.21): icmp_seq=4 ttl=239 time=266 ms

--- instagram.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3002ms
rtt min/avg/max/mdev = 263.959/271.481/289.610/10.506 ms
```

**Comment by mlwrose** [comment]
Hi Joao, its somehow working. not sure what changed but the sudo command seemed to get it working. Thanks to you and especially Patrick
