### ISSUE TITLE
CRITICAL - Sorry, Record Activity is not working on Windows

### ISSUE THREAD

**Issue by GeekYasser** [InstaPy/InstaPy#1130]
CRITICAL - Sorry, Record Activity is not working on Windows. We're working to fi                                                                                                                x this soon!
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>

**Comment by sngmrrsy** [comment]
facing the same issue as well, any fix?

**Comment by Ashuqwe** [comment]
Error: INFO - Session started - 2017-12-25 17:39:22
 CRITICAL - Sorry, Record Activity is not working on Windows. We're working to fix this soon!
 INFO - Logged in successfully!
 Traceback (most recent call last):
 File "quickstart.py", line 11, in <module>
 session.set_user_interact(amount=40, random=False, percentage=20)
 TypeError: set_user_interact() got an unexpected keyword argument 'random'
 Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x0470B7D0>>
 Traceback (most recent call last):
 File "C:\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 163, in __del__
 File "C:\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 139, in stop
 File "C:\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
 ImportError: sys.meta_path is None, Python is likely shutting down



This is the error
 message i get while running

**Comment by converge** [comment]
@Ashuqwe 
change from
```
session.set_user_interact(amount=40, random=False, percentage=20)
```
to
```
session.set_user_interact(amount=40, randomize=False, percentage=20)
```

**Comment by converge** [comment]
#1136

**Comment by sngmrrsy** [comment]
PS D:\Downloads\InstaPy-master> python quickstart.py

DevTools listening on ws://127.0.0.1:12252/devtools/browser/91297e45-e11d-455a-9d4d-34a13ea44e6f
INFO - Session started - 2017-12-26 07:09:27
WARNING - Sorry, Record Activity is not working on Windows. We're working to fix this soon!
Cookie file not found, creating cookie...
CRITICAL - Wrong login data!
INFO - Session ended - 2017-12-26 07:09:42
INFO - --------------------

Still getting error after the update

**Comment by sngmrrsy** [comment]
For anyone else still facing the same problem, manually login to instagram after the id and pw has been entered will fix the issue.

**Comment by dothebernny** [comment]
INFO - Session started - 2017-12-26 03:08:48
WARNING - Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO - Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 9, in <module>
    session.login()
  File "D:\Programing\InstaPy-master\InstaPy-master\instapy\instapy.py", line 234, in login
    log_follower_num(self.browser, self.username)
  File "D:\Programing\InstaPy-master\InstaPy-master\instapy\print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "C:\Users\berna\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "C:\Users\berna\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\berna\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.15063 x86_64)

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x041964B0>>
Traceback (most recent call last):
  File "C:\Users\berna\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 163, in __del__
  File "C:\Users\berna\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 139, in stop
  File "C:\Users\berna\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by converge** [comment]
hey @dothebernny , this is not related to this issue, could you move it to https://github.com/timgrossmann/InstaPy/issues/1128 ?
