### ISSUE TITLE
Fails on ubuntu 14.04 server

### ISSUE THREAD

**Issue by imewish** [InstaPy/InstaPy#1141]
OS: Ubuntu 14.04
INPUT
```
from instapy import InstaPy

insta_username = ''
insta_password = ''

# if you want to run this script on a server,
# simply add nogui=True to the InstaPy() constructor
session = InstaPy(username='xxxxx', password='xxxxx', nogui=True)
session.login()

# set up all the settings
session.set_upper_follower_count(limit=1000)
session.set_do_comment(True, percentage=70)
session.set_comments(['Amazing!!!', 'Cool!!', 'This could be a canvas!'])
#session.set_do_follow(enabled=True, percentage=5, times=2)
#session.unfollow_users(amount=10, onlyInstapyFollowed = True )

# do the actual liking
session.like_by_tags(['mobilephotography'], amount=300)

# end the bot session
session.end()


````

OUTPUT
```
INFO - Session started - 2017-12-26 16:03:48
Traceback (most recent call last):
  File "gdaily.py", line 9, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 227, in login
    self.bypass_suspicious_attempt):
  File "/root/InstaPy/instapy/login_util.py", line 99, in login_user
    browser.get('https://www.google.com')
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 433, in _request
    resp = self._conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 408, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

```
Works fine on my Macbook though.

**Comment by converge** [comment]
did you set you login/passwd ?

**Comment by imewish** [comment]
Obviously Yes. It used to work earlier. @converge

**Comment by douwevandermeij** [comment]
I have the same error every now and then (on Debian), it's something with the "remote server". Checkout this answer on StackOverflow https://stackoverflow.com/a/8734798/1747266.

The "remote server" in this case is the internal Selenium webdriver. In my case this url is called: http://127.0.0.1:60794/session/--random-md5-sum--/execute upon `browser.execute_script("window.scrollTo(0, document.body.scrollHeight);")` and it fails sometimes, not sure why.

**Comment by Tjorriemorrie** [comment]
@imewish that's a known issue on ubuntu. You have to update your chromedriver.

**Comment by imewish** [comment]
OK. I'm now running on Ubuntu 16.04. Works fine.
