### ISSUE TITLE
Error: set_user_interact() got an unexpected keyword argument 'random'

### ISSUE THREAD

**Issue by RowenB83** [InstaPy/InstaPy#1153]
After meticulously following the setup instructions for Windows 10 I get this error in the instaPy GUI:

Error: INFO - Session started - 2017-12-28 22:25:49
 WARNING - Sorry, Record Activity is not working on Windows. We're working to fix this soon!
 INFO - Logged in successfully!
 Traceback (most recent call last):
 File "quickstart.py", line 7, in <module>
 session.set_user_interact(amount=40, random=False, percentage=50)
 TypeError: set_user_interact() got an unexpected keyword argument 'random'
 Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x04079290>>
 Traceback (most recent call last):
 File "C:\Users\thete\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 163, in __del__
 File "C:\Users\thete\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 139, in stop
 File "C:\Users\thete\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
 ImportError: sys.meta_path is None, Python is likely shutting down
InstaPy ended

It reads Record Activity is not working on Win. Does that mean we cannot run it on Windows?

Thanks for your help

**Comment by gitpatrickhub** [comment]
I don't use the GUI, but 'random' was changed to 'randomize' in one of the latest updates.
