### ISSUE TITLE
Trying to set up InstaPy - what am I missing?

### ISSUE THREAD

**Issue by itsmejamie** [InstaPy/InstaPy#1158]
I've tried to set up InstaPy but I'm getting the following error. What does it mean?

Last login: Fri Dec 29 14:13:49 on ttys000
Jamies-MBP:~ jamie$ cd Instapy
Jamies-MBP:Instapy jamie$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password)
  File "/Users/jamie/InstaPy/instapy/instapy.py", line 128, in __init__
    self.set_selenium_local_session()
  File "/Users/jamie/InstaPy/instapy/instapy.py", line 187, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Jamies-MBP:Instapy jamiefraser$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password)
  File "/Users/jamie/InstaPy/instapy/instapy.py", line 128, in __init__
    self.set_selenium_local_session()
  File "/Users/jamie/InstaPy/instapy/instapy.py", line 187, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by gitpatrickhub** [comment]
1) verify the chromedriver is in your assets folder
2) have you tried running using sudo python quickstart.py ?

**Comment by itsmejamie** [comment]
1. Yes, the chromedriver is in my assets folder
2. Yes, I've tried running using sudo python quickstart.py and get the same results.

**Comment by beranPro** [comment]
@itsmejamie 
is the chromedriver unzipped ?
do you have the correct version for your chrome?

**Comment by itsmejamie** [comment]
@beranPro 

Yes chrome driver is unzipped
I'm using the latest version of chrome - Version 63.0.3239.108

**Comment by beranPro** [comment]
please post your quickstart.py and stripe the credentials out

**Comment by julzKB** [comment]
@itsmejamie any resolution on this issue ?
