### ISSUE TITLE
NameError: name 'session' is not defined *Noob*

### ISSUE THREAD

**Issue by robo558999** [InstaPy/InstaPy#1161]
## Possible Solution (optional)

I'm getting this error. I'll attach my quickstart.py 

# python3.6 quickstart.py

Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    headless_browser=False)
  File "/root/Desktop/InstaPy-master/instapy/instapy.py", line 135, in __init__
    self.set_selenium_local_session()
  File "/root/Desktop/InstaPy-master/instapy/instapy.py", line 194, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.10.267518,platform=Linux 4.13.0-kali1-amd64 x86_64)

During handling of the above exception, another exception occurred:

****Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.end()
NameError: name 'session' is not defined**

![screenshot from 2017-12-29 13-53-56](https://user-images.githubusercontent.com/34945389/34445108-c2168608-ec9f-11e7-9f5a-bd2e6dd3ab6f.png)

**

**Comment by robo558999** [comment]
![screenshot from 2017-12-29 13-55-32](https://user-images.githubusercontent.com/34945389/34445158-09ff3104-eca0-11e7-9d86-ef1cbf332a1e.png)

**Comment by converge** [comment]
hey @robo558999 , do you have chrome installed ?

**Comment by robo558999** [comment]
The browser, or?

**Comment by converge** [comment]
the browser

**Comment by robo558999** [comment]
That I do not have lol. Is that all I need?

**Comment by converge** [comment]
it's :)
