### ISSUE TITLE
NameError: name 'session' is not defined *Chrome Installed*

### ISSUE THREAD

**Issue by robo558999** [InstaPy/InstaPy#1163]
Had issue before, installed chrome. Now quickstart.py pauses on a blinking cursor for a good moment, and the wifi indicator starts blinking then it throws up. 

```
root@kali:~/Desktop/InstaPy-master# python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    headless_browser=False)
  File "/root/Desktop/InstaPy-master/instapy/instapy.py", line 135, in __init__
    self.set_selenium_local_session()
  File "/root/Desktop/InstaPy-master/instapy/instapy.py", line 194, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.10.267518,platform=Linux 4.13.0-kali1-amd64 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
![screenshot from 2017-12-29 16-58-22](https://user-images.githubusercontent.com/34945389/34448292-f6473674-ecb9-11e7-8a70-8b75a3219c97.png)
![screenshot from 2017-12-29 16-58-55](https://user-images.githubusercontent.com/34945389/34448295-f8b92980-ecb9-11e7-853d-48177ab7e8d2.png)


    session.end()
NameError: name 'session' is not defined

```

**Comment by robo558999** [comment]
![screenshot from 2017-12-29 16-58-22](https://user-images.githubusercontent.com/34945389/34448316-2176e68c-ecba-11e7-9b4d-5813211a0d8a.png)
![Uploading Screenshot from 2017-12-29 16-58-55.png…]()

**Comment by robo558999** [comment]
![screenshot from 2017-12-29 16-58-55](https://user-images.githubusercontent.com/34945389/34448407-ffc06de6-ecba-11e7-9041-929a5e0d25ac.png)

**Comment by converge** [comment]
```sudo killall chrome xvfb Xvfb```

**Comment by robo558999** [comment]
That puts out 

```
root@kali:~/Desktop/InstaPy-master# sudo killall chrome xvfb Xvfb
chrome: no process found
xvfb: no process found
```

**Comment by converge** [comment]
did you try to run instapy again ?

**Comment by robo558999** [comment]
I did, and it looks the same 


```
# python3.6 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    headless_browser=True, nogui=True)
  File "/root/Desktop/InstaPy-master/instapy/instapy.py", line 135, in __init__
    self.set_selenium_local_session()
  File "/root/Desktop/InstaPy-master/instapy/instapy.py", line 194, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.10.267518,platform=Linux 4.13.0-kali1-amd64 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.end()
NameError: name 'session' is not defined
```

**Comment by converge** [comment]
is chrome installed ?

**Comment by robo558999** [comment]
It is

On Dec 30, 2017 8:03 PM, "João Paulo Vanzuita" <notifications@github.com>
wrote:

is chrome installed ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/timgrossmann/InstaPy/issues/1163#issuecomment-354578623>,
or mute the thread

**Comment by robo558999** [comment]
I also get the same output running as non-root user with sudo access

**Comment by grakercub** [comment]
im having a similar problem... when i put in python quickstart.py i get:

Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.end()
NameError: name 'session' is not defined
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x100df8790>> ignored

**Comment by robo558999** [comment]
I ran everything under Ubuntu Desktop and it works like a charm. Kali not
so much

**Comment by vaporstatic** [comment]
I've got the same/similar problem on Windows 7 64 Pro. It was working fine up until a few days ago for some reason.

C:\Users\USER\Documents\GitHub\InstaPy>py quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    headless_browser=False)
  File "C:\Users\USER\Documents\GitHub\InstaPy\instapy\instapy.py", line
87, in __init__
    self.follow_restrict = load_follow_restriction()
  File "C:\Users\USER\Documents\GitHub\InstaPy\instapy\unfollow_util.py",
 line 789, in load_follow_restriction
    return json.load(followResFile)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\json\__i
nit__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\json\__i
nit__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\json\dec
oder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\json\dec
oder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.end()
NameError: name 'session' is not defined

**Comment by ptkdev** [comment]
Problem is with pip package: https://pypi.python.org/simple/session/ (error 404)
Run `$ pip install -vvv session` 

![pip session](https://image.ibb.co/bOuRxG/Screenshot_from_2018_01_08_02_10_52.png)

**Comment by SimoneRaimondiCominesi** [comment]
@robo558999  I have the same error.
I'm using raspberry pi3 with raspbian and Firefox.

**Comment by robo558999** [comment]
Use the latest files there's a new selenium version.

 I ran my same setup on Ubuntu server(with headless set for server) and
desktop and had no issues. Not too sure what my issue was on kali. I
suggest switching the os platform to Ubuntu or Ubuntu server

**Comment by vaporstatic** [comment]
I fixed my issue by backing up my quickstart.py, nuking the Instapy folder, and having GitHub re-clone everything. I then downloaded the latest chromedriver, threw the exe into the assets folder, and it worked.

**Comment by luigifaticoso** [comment]
If you are running chrome try to remove the version of python you have installed using this  guide https://stackoverflow.com/questions/3819449/how-to-uninstall-python-2-7-on-a-mac-os-x-10-6-4
and use the default python. It worked to a friend of mine that had the same issue

**Comment by sebmer-com** [comment]
you probally had a typo

**Comment by robo558999** [comment]
What can one do to keep the session from ending? Is there a command to loop
back to the scripts first set actions/settings

**Comment by wemakefuture** [comment]
Update: 
today I freshly installed a raspi and it worked but when i repeat the 

`sudo xvfb-run python2.7 quickstart.py`

it crashed with 

`xvfb-run: error: Xvfb failed to start`

so i rebooted and ran again `sudo xvfb-run python2.7 quickstart.py` which worked quite well. But perma reboot after instapysession is no option. So i kept searching google [https://github.com/travis-ci/travis-ci/issues/4387](url)

well what solved it was putting `-a` in between.
[](https://github.com/Shippable/support/issues/2848)

so now full command on raspi what i am running in crontab is:
  `cd Projects/InstaPy/ && sudo xvfb-run -a  python2.7 quickstart.py`
Worked for me
