### ISSUE TITLE
ImportError: No module named 'jsonschema'

### ISSUE THREAD

**Issue by WHATTHEHECKIGOTTADO** [InstaPy/InstaPy#1174]
I did s it instructs and well--
h e l p ?

C:\Users\sir. Aaron Burr\InstaPy>python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\sir. Aaron Burr\InstaPy\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\Users\sir. Aaron Burr\InstaPy\instapy\instapy.py", line 18, in <module>
    from .clarifai_util import check_image
  File "C:\Users\sir. Aaron Burr\InstaPy\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Image as ClImage
  File "C:\Users\sir. Aaron Burr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\clarifai-2.0.31-py3.5.egg\clarifai\rest\__init__.py", line 3, in <module>
  File "C:\Users\sir. Aaron Burr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\clarifai-2.0.31-py3.5.egg\clarifai\rest\client.py", line 22, in <module>
ImportError: No module named 'jsonschema'

**Comment by Oyetomi** [comment]
pip install jsonschema
