### ISSUE TITLE
Chrome works, Firefox not

### ISSUE THREAD

**Issue by beranPro** [InstaPy/InstaPy#1184]
## Expected Behavior
Runs with Firefox
## Current Behavior
Firefox starts but then the script fails
```
mr-snuggles:~/Dokumente/Instagram/InstaPy$ python quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 39, in <module>
    session.end()
NameError: name 'session' is not defined
```
## InstaPy configuration
```python
from instapy import InstaPy

insta_username = 'user'
insta_password = 'pass'

# set headless_browser=True if you want to run InstaPy on a server
try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      use_firefox=True)
    session.login()

    # settings

    session.set_lower_follower_count(limit = 10)
    session.set_upper_follower_count(limit=25000)


# This is used to perform likes on your own feeds
# amount=100  specifies how many total likes you want to perform
# randomize=True randomly skips posts to be liked on your feed
# unfollow=True unfollows the author of a post which was considered
# inappropriate interact=True visits the author's profile page of a
# certain post and likes a given number of his pictures, then returns to feed
    #session.like_by_feed(amount=100, randomize=True, unfollow=False, interact=False)

#    session.set_do_comment(True, percentage=10)
#    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
#    session.set_dont_include(['friend1', 'friend2', 'friend3'])
#    session.set_dont_like(['pizza', 'girl'])
    session.set_do_like(enabled=True, percentage=100)
    session.interact_by_users(['someAccountToLike'], amount=200, randomize=True, media='Photo')

    # actions
 #   session.like_by_tags(['natgeo'], amount=1)

finally:
    # end the bot session
    session.end()
```
## Hostsystem
Ubuntu 17.10  x64

**Comment by RoyBkker** [comment]
Same problem here

**Comment by elenamahartana** [comment]
Same problem. If I run the included firefox example, it also does not work. (Ubuntu 16.04)

~/Desktop/InstaPy-master/examples$ python firefoxExample.py 
  File "firefoxExample.py", line 29
    .end()
    ^
IndentationError: unexpected indent
