### ISSUE TITLE
Unknown Error: Button Not Clickable at Point (589,9)

### ISSUE THREAD

**Issue by lairdep23** [InstaPy/InstaPy#1202]
```
File "/home/ubuntu/InstaPy/instapy/instapy.py", line 725, in like_by_tags
    self.logger)
  File "/home/ubuntu/InstaPy/instapy/unfollow_util.py", line 341, in follow_user
    follow_button.click()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button class="_qv64e _iokts _4tgw8 _njrw0">...</button> is not clickable at point (589, 9). Other element would receive the click: <div class="_5rnaq _cyf06">...</div>
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.4.0-1041-aws x86_64)
```
Will work for a few minutes perfectly then crash after liking and commenting on an image, giving this error message. 

Chromedriver and Instapy should be up to date as this one was created yesterday. (Running on a virtual machine - AWS Ubuntu Linux)

**Comment by mkraffa** [comment]
same problem here, running on digital ocean linux machine.

runs for a while then "like_by_tags" crashes when it tries to click "follow"

`Traceback (most recent call last):
  File "/root/instapy/instabot.py", line 14, in <module>
    session.like_by_tags(['#dogs', '#cats', '#cute', '#randomstuff'], amount=4)
  File "/root/instapy/instapy/instapy.py", line 725, in like_by_tags
    self.logger)
  File "/root/instapy/instapy/unfollow_util.py", line 341, in follow_user
    follow_button.click()
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button class="_qv64e _iokts _4tgw8 _njrw0">...</button> is not clickable at point (591, 9). Other element would receive the click: <div class="_5rnaq _cyf06">...</div>
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.4.0-104-generic x86_64)`

**Comment by mkraffa** [comment]
I think I've managed to fix this by adding `headless_browser=True`


`session = InstaPy(username='', password='', bypass_suspicious_attempt=False, nogui=True, headless_browser=True)
`
