### ISSUE TITLE
Unknown error: Cannot read property 'entry_data' of undefined

### ISSUE THREAD

**Issue by datteba** [InstaPy/InstaPy#1215]
File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 487, in execute_script
    'args': converted_args})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.15063 x86_64)

**Comment by dcurletti** [comment]
Worked fine the first few days i used it, then i started getting the same error myself.

**Comment by MrBeardedGuy** [comment]
Same here it seems that selenium has issues with the headless browser. 

```
Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    session.login()
  File "/Users/UserOS/InstaPy/instapy/instapy.py", line 271, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "/Users/UserOS/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: headless chrome=64.0.3282.186)
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.3 x86_64)
```

**Comment by MrBeardedGuy** [comment]
https://github.com/timgrossmann/InstaPy/issues/1434 Seems to be solving the problem.... Specifically suggests to modify `log_follower_num()` in `print_logwriter.py` file

from
```
followed_by = browser.execute_script(
   "return window._sharedData.""entry_data.ProfilePage[0]."
   "user.followed_by.count")
```

to 
```
from selenium.common.exceptions import WebDriverException   #import this at top of the file

try:
    followed_by = browser.execute_script(
        "return window._sharedData.""entry_data.ProfilePage[0]."
        "user.followed_by.count")
except WebDriverException:   #handle the possible `entry_data` error
    try:
        browser.execute_script("location.reload()")
        followed_by = browser.execute_script(
            "return window._sharedData.""entry_data.ProfilePage[0]."
            "user.followed_by.count")
    except WebDriverException:
        followed_by = None
```
