### ISSUE TITLE
</button> is not clickable at point (584, 9)

### ISSUE THREAD

**Issue by imewish** [InstaPy/InstaPy#1216]
OS: Ubuntu 14.04 digital ocean server.

it rails randomly with following error messages.

```
Traceback (most recent call last):
  File "cap.py", line 19, in <module>
    session.like_by_tags(['mobilephotography'], amount=200)
  File "/root/InstaPy/instapy/instapy.py", line 725, in like_by_tags
    self.logger)
  File "/root/InstaPy/instapy/unfollow_util.py", line 341, in follow_user
    follow_button.click()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button class="_qv64e _iokts _4tgw8 _njrw0">...</button> is not clickable at point (584, 9). Other element would receive the click: <div class="_5rnaq _cyf06">...</div>
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.4.0-103-generic x86_64)

```

**Comment by imewish** [comment]
I have verified this on a fresh instance of Ubuntu 14.04. Same error. Any update on this ?
