### ISSUE TITLE
Element is not clickable at point (381, 340). Other element would receive the click: <div class="_eyflt">...</div>

### ISSUE THREAD

**Issue by antonrifco** [InstaPy/InstaPy#1217]
## Expected Behavior
Script running fine while executing session.like_by_tags

## Current Behavior
Got following error while running recently, it was previously working fine. 

Traceback (most recent call last):
  File "quickstart.py", line 27, in <module>
    session.like_by_tags(['muajakarta', 'makeupartistjakarta', 'muabandung', 'muabali', 'indonesiamakeupartist', 'muapekanbaru', 'inspirasimakeupwedding', 'muamedan', 'divaindonesia', 'sigersunda', 'muasurabaya', 'rezaazrumakeup', 'muasolo', 'muaindonesia', 'thebridestory', 'muasemarang', 'bridestory', 'pengantintraditional', 'pengantin', 'riastangerang', 'makeupwisuda', 'makeupwisudajakarta', 'muapamulang', 'riastangerang', 'nikah', 'makeupgraduationjakarta', 'makeuplamaran'], amount=30)
  File "/opt/bitnami/apps/instabot/InstaPy/instapy/instapy.py", line 640, in like_by_tags
    skip_top_posts)
  File "/opt/bitnami/apps/instabot/InstaPy/instapy/like_util.py", line 207, in get_links_for_tag
    load_button.click()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <a href="/explore/tags/muajakarta/?max_id=1689337455628996406" class="_1cr2e _epyes">...</a> is not clickable at point (381, 340). Other element would receive the click: <div class="_eyflt">...</div>
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 3.13.0-119-generic x86_64)

## InstaPy configuration
session.login()

    # settings
    session.set_do_follow(enabled=True, percentage=30, times=2)
    session.set_upper_follower_count(limit=2500)
    session.set_lower_follower_count(limit = 3)
    session.set_do_comment(True, percentage=30)
    session.set_do_like(True, percentage=40)
    
    # actions
    session.like_by_tags(['muajakarta', 'makeupartistjakarta', 'muabandung', 'muabali', 'indonesiamakeupartist', 'muapekanbaru', 'inspirasimakeupwedding', 'muamedan', 'divaindonesia', 'sigersunda', 'muasurabaya', 'rezaazrumakeup', 'muasolo', 'muaindonesia', 'thebridestory', 'muasemarang', 'bridestory', 'pengantintraditional', 'pengantin', 'riastangerang', 'makeupwisuda', 'makeupwisudajakarta', 'muapamulang', 'riastangerang', 'nikah', 'makeupgraduationjakarta', 'makeuplamaran'], amount=30)
    session.unfollow_users(amount=20, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=30 )

**Comment by blesson3** [comment]
See [my comment](https://github.com/timgrossmann/InstaPy/pull/47#issuecomment-357359125) on this PR: https://github.com/timgrossmann/InstaPy/pull/47 for a potential workaround/fix.

Let me know if this change helps out.

**Comment by timgrossmann** [comment]
@antonrifco Could you pull and try again, please?
Sorry for the problem, I should've fixed it now

**Comment by antonrifco** [comment]
hi @timgrossmann , I just pulled the latest code, and tried to rerun the code.
It still got the same error, but now on different line

any idea?

```
Traceback (most recent call last):
  File "quickstart.py", line 26, in <module>
    session.like_by_tags(['muajakarta', 'makeupartistjakarta', 'muabandung', 'muabali', 'indonesiamakeupartist', 'muapekanbaru', 'inspirasimakeupwedding', 'muamedan', 'divaindonesia', 'sigersunda', 'muasurabaya', 'rezaazrumakeup', 'muasolo', 'muaindonesia', 'thebridestory', 'muasemarang', 'bridestory', 'pengantintraditional', 'pengantin', 'riastangerang', 'makeupwisuda', 'makeupwisudajakarta', 'muapamulang', 'riastangerang', 'nikah', 'makeupgraduationjakarta', 'makeuplamaran'], amount=30)
  File "/opt/bitnami/apps/instabot/InstaPy/instapy/instapy.py", line 640, in like_by_tags
    skip_top_posts)
  File "/opt/bitnami/apps/instabot/InstaPy/instapy/like_util.py", line 207, in get_links_for_tag
    load_button.click()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <a href="/explore/tags/muajakarta/?max_id=1691174418158395062" class="_1cr2e _epyes">...</a> is not clickable at point (391, 464). Other element would receive the click: <div class="_eyflt">...</div>
  (Session info: headless chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 3.13.0-119-generic x86_64)

```

**Comment by CharlesCCC** [comment]
I got the similar error on the new version, but it seems working fine with the older version.

**Comment by RoyBkker** [comment]
I got the same error with using smart hashtags. Have pulled the latest versions.

`Using smart hashtags
Traceback (most recent call last):
  File "quickstart.py", line 33, in <module>
    session.like_by_tags(amount=20, use_smart_hashtags=True)
  File "D:\Projecten\InstaBot\InstaPy\instapy\instapy.py", line 725, in like_by_                                                                                                                                  tags
    self.logger)
  File "D:\Projecten\InstaBot\InstaPy\instapy\unfollow_util.py", line 341, in fo                                                                                                                                  llow_user
    follow_button.click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py",                                                                                                                                   line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py",                                                                                                                                   line 461, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", l                                                                                                                                  ine 236, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py"                                                                                                                                  , line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <                                                                                                                                  button class="_qv64e _iokts _4tgw8 _njrw0">...</button> is not clickable at poin                                                                                                                                  t (233, 8). Other element would receive the click: <div class="_catib">...</div>
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87a                                                                                                                                  f1),platform=Windows NT 6.1.7601 SP1 x86_64)`

**Comment by timgrossmann** [comment]
@RoyBkker @CharlesCCC @antonrifco @blesson3 @converge 
Can someone please try to fix this?

**Comment by RoyBkker** [comment]
Update:
Still have the error.. Running with smart hashtags and headless browser = true.. Really don't know how this is possible. 

`Using smart hashtags
Traceback (most recent call last):
  File "quickstart.py", line 32, in <module>
    session.like_by_tags(amount=25, use_smart_hashtags=True)
  File "D:\Projecten\InstaBot\InstaPy\instapy\instapy.py", line 725, in like_by_tags
    self.logger)
  File "D:\Projecten\InstaBot\InstaPy\instapy\unfollow_util.py", line 341, in follow_user
    follow_button.click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button class="_qv64e _iokts _4tgw8 _njrw0">...</button> is not clickable at point (196, 9). Other element would receive the click: <div class="_catib">...</div>
  (Session info: headless chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 6.1.7601 SP1 x86_64)
`

In my case it was my own fault.. When I ran it with headLess Browser =False, i resized the browser a couple of times.. So that's why selenium couldn't find the buttons etc.. 
I ran it now a couple of times without touching or resizing the browser and with headLessBrowser = True, and no failures anymore.

**Comment by blesson3** [comment]
@antonrifco checkout from this PR (https://github.com/timgrossmann/InstaPy/pull/1248) and let me know if it fixes your issue
