### ISSUE TITLE
Mac installation issues -Chromedriver- -Process-

### ISSUE THREAD

**Issue by quintendewilde** [InstaPy/InstaPy#1225]
I get following error whilst running python3 quickstart.py.
I brew installed chromedriver so the path should be set automatically.

```

Quintens-MBP:Instapy quintendewilde$ python3 quickstart.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './assets/chromedriver': './assets/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    headless_browser=False)
  File "/Users/quintendewilde/Documents/InstaPy/instapy/instapy.py", line 135, in __init__
    self.set_selenium_local_session()
  File "/Users/quintendewilde/Documents/InstaPy/instapy/instapy.py", line 194, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.end()
NameError: name 'session' is not defined
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x107a42a58>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 163, in __del__
    self.stop()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 135, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'
Quintens-MBP:Instapy quintendewilde$ brew install chromedriver
Warning: chromedriver 2.35 is already installed
Quintens-MBP:Instapy quintendewilde$ brew doctor
Your system is ready to brew.
```

**Comment by converge** [comment]
https://github.com/timgrossmann/InstaPy#basic-installation

**Comment by LoopForYou** [comment]
You need to put chromedriver in the assets folder.

Download Chrome Driver here: https://sites.google.com/a/chromium.org/chromedriver/downloads

Put it in InstaPy->assets

**Comment by quintendewilde** [comment]
Works, this can be closed.
