### ISSUE TITLE
unable to get followers and following information   'after'

### ISSUE THREAD

**Issue by leegabriel** [InstaPy/InstaPy#1230]
## Expected Behavior
Successfully unfollow users who are not following account, after running chromedriver in a separate terminal and running ```$ python quickstart.py```.

## Current Behavior
Not showing any HTML in the browser, just showing some JSON, and exiting prematurely in the terminal with the following: 
```
INFO - Session started - 2018-01-12 22:37:42
INFO - Logged in successfully!
INFO - Number of people followed automatically remaining: 77
unable to get followers and following information 
 'after'
INFO - --> Total people unfollowed : 0 
INFO - Session ended - 2018-01-12 22:38:10
INFO - --------------------


Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7f741e78e908>>
Traceback (most recent call last):
  File "/home/gabriel/anaconda3/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 163, in __del__
  File "/home/gabriel/anaconda3/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 139, in stop
  File "/home/gabriel/anaconda3/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down
```

## InstaPy configuration
quickstart.py:
```
from instapy import InstaPy

insta_username = 'asdf'
insta_password = 'asdf
# set headless_browser=True if you want to run InstaPy on a server
try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False)
    session.login()

    # unfollow people who are not following
    session.unfollow_users(amount=1, onlyInstapyFollowed=False, onlyNotFollowMe=True, sleep_delay=60)

   
finally:
    # end the bot session
    session.end()
```
Platform is Ubuntu 16.04 64-bit.

**Comment by leegabriel** [comment]
For anyone with the same problem, I was able to fix the issue by setting ```headless_browser=True``` in the InstaPy constructor.
