### ISSUE TITLE
Problems On  Ubuntu Server

### ISSUE THREAD

**Issue by tylergit2** [InstaPy/InstaPy#1233]
## Expected Behavior
I've been running InstaPy on a Ubuntu server on Digital Ocean with no problems. My scripts stopped running suddenly, and now I'm getting this error. Any suggestions? 
## Current Behavior

root@ubuntu-512mb-sfo2-01:~/InstaPy# python3 quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    headless_browser=True)
  File "/root/InstaPy/instapy/instapy.py", line 135, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 194, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created exception
from tab crashed
  (Session info: headless chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.4.0-109-generic x86_64)

**Comment by tylergit2** [comment]
I must've messed something up in the installation when I was adding twitter automation to the server. I just needed to reinstall Instapy on a fresh Ubuntu droplet and all is well.
