### ISSUE TITLE
Schedule - Not More than One Task (Firefox, Raspberry Pi)

### ISSUE THREAD

**Issue by alexsmedile** [InstaPy/InstaPy#1235]
Hi,
I wrote a simple InstaPy Bot and run it on my Raspberry Pi 3. It worked very good.
Now I want to automate it. So I wrote that:
```
from instapy import InstaPy
from random import randint
import schedule
import time
import pickle #cookies login

related_tag = [#mytags]
```
I've defined some functions like that:
```
bot = InstaPy(username=insta_username, password=insta_password, use_firefox=True, page_delay=.5)

def cookie_login():
    bot.browser.get("https://www.instagram.com")
    for cookie in pickle.load(open("instacookies.pkl", "rb")):
        bot.browser.add_cookie(cookie) # i found a guide on that

def _like_related_tag_(x,y):
    # login
    cookie_login()
    bot.set_sleep_reduce(95)
    bot.set_dont_include(friend_list)
    # generic comment
    bot.set_comments(pic_comment, media='Photo')
    bot.set_comments(vid_comment, media='Video')
    bot.set_do_comment(enabled=True, percentage=(randint(60,80)))
    # like
    bot.like_by_tags(related_tag, amount=(randint(x,y)))
    bot.end()
```
And I've scheduled that way:
```
schedule.every().day.at("10:00").do(like_related_tag, x=1, y=2)
schedule.every().day.at("11:00").do(like_related_tag, x=2, y=4)
schedule.every().day.at("12:00").do(like_related_tag, x=8, y=16)

while True:
    schedule.run_pending()
    time.sleep(1)
```

**Without the Schedule Module everything works fine.** I've tested it.
Even the first job from my schedule works fine. But once the first session is completed my code does not want to go on.

**ERROR:**
```
Traceback (most recent call last):
  File "AntidoteBot_v1.0.py", line 291, in <module>
    schedule.run_pending()
  File "/home/pi/.local/lib/python2.7/site-packages/schedule/__init__.py", line 493, in run_pending
    default_scheduler.run_pending()
  File "/home/pi/.local/lib/python2.7/site-packages/schedule/__init__.py", line 78, in run_pending
    self._run_job(job)
  File "/home/pi/.local/lib/python2.7/site-packages/schedule/__init__.py", line 131, in _run_job
    ret = job.run()
  File "/home/pi/.local/lib/python2.7/site-packages/schedule/__init__.py", line 411, in run
    ret = self.job_func()
  File "AntidoteBot_v1.0.py", line 153, in like_smart_tag
    cookie_login()
  File "AntidoteBot_v1.0.py", line 94, in cookie_login
    bot.browser.get("https://www.instagram.com")
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 432, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
```

I've tried to add to my functions this piece of code at the end but it didn't work:
`return schedule.CancelJob`

How can I fix it? I think it's something to do with Selenium but I don't really know what to do now...

**Comment by andreescocard** [comment]
Create a bash script and run on cron will solve your problem

**Comment by alexsmedile** [comment]
@andreescocard Thank you!

I set it up like that:
Main file: `AntidoteBot_v2.py`
and specific functions recall files `like_music_tag.py` `like_photo_tag.py` and so on... 

Functions recall files example:
```
#!/usr/bin/env python
import os
import time
from AntidoteBot_v2 import *
# RUN:
start_time = time.strftime("%d %b %Y %H:%M:%S", time.gmtime())
print(os.path.realpath(__file__),' started at '+ start_time)
like_music_tag(2,4)
```
And I added `0 0 * * * /usr/bin/python /home/pi/Projects/InstaPy/like_music_tag.py` to my crontab.

But I encounter the following error:
```
Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/like_music_tag.py", line 4, in <module>
    from AntidoteBot_v2 import *
  File "/home/pi/Projects/InstaPy/AntidoteBot_v2.py", line 250, in <module>
    bot = InstaPy(username=insta_username, password=insta_password, use_firefox=True, page_delay=.5)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 83, in __init__
    self.follow_restrict = load_follow_restriction()
  File "/home/pi/Projects/InstaPy/instapy/unfollow_util.py", line 789, in load_follow_restriction
    with open('./logs/followRestriction.json') as followResFile:
IOError: [Errno 2] No such file or directory: './logs/followRestriction.json'
```

Running the python file normally works fine. So I don't really know what's wrong now.

**Comment by ishandutta2007** [comment]
To prevent duplicate/ parallel job runs I have created a bash script like this:

run_instapy.sh
```

#!/bin/bash

TEMPLATE_NAME="target_followers_of_similar_accounts_and_influencers.py"
if ps aux | grep $TEMPLATE_NAME | awk '{ print $11 }' | grep python
then
   echo $TEMPLATE_NAME" Already Running"
else
   echo "Starting "$TEMPLATE_NAME
   /Users/ishandutta2007/.pyenv/shims/python `dirname "$0"`/quickstart_templates/$TEMPLATE_NAME -u myusename -p mypwd --nogui --headless-browser --disable_image_load --multi_logs
fi

```

And then in crontab 

`
*/10 * * * * bash /Users/ishandutta2007/Documents/Projects/InstaPy/run_instapy.sh
`
 
@uluQulu @timgrossmann Is there already a built-in way to prevent parallel jobs runs that I might be missing?

**Comment by ishandutta2007** [comment]
@uluQulu @timgrossmann If there aren't can I push `run_once_instapy.sh` ?

**Comment by uluQulu** [comment]
wow @ishandutta2007 
You have nicely used the newly introduced CLI args 🥳
```erlang
python $TEMPLATE_NAME -u myusename -p mypwd --nogui --headless-browser --disable_image_load --multi_logs
```
Just a note,
**nogui** parameter is not supported and will not be supported ever I think, so you should not use the `--nogui` flag.
**multilogs** parameter is also not supported but it is in plan to also serve that functionality somehow.

Meanwhile, you can still parse any of the parameters that is not formally supported and use as you like.

##### Why you used those unsupported params and did not get an any error?
It's cos I wrote _argparsing_ to be fully flexible and users can pass their custom args WHILST passing unparsed args makes no harm (_no worries_) xD

You should read the extensive documentation about it if you like.

Short note, `python your_quickstart.py -h` will give you all of the supported flags.

----

About your script,
There currently is no any functionality as you've suggested.
Although, I am not good at scripting, your idea is neat and useful.
You should PR it added to the **scripts** folder with a usage example.

I am sure there are many ppl who would like that functionality.

----

Cheers 😁
---
