### ISSUE TITLE
Unfollow utility throwing an error

### ISSUE THREAD

**Issue by Namaslayer** [InstaPy/InstaPy#1271]
## Expected Behavior
unfollow 200 users, not InstaPy followed, running from Crontab twice daily

## Current Behavior
Logins correctly, crashes before unfollow starts. Shows the error below everytime.

2018-01-23 19:11:01 - INFO - Session started - 2018-01-23 19:11:01
2018-01-23 19:11:05 - INFO - Logged in successfully!
2018-01-23 19:11:24 - INFO - Number of people followed automatically remaining: 2
2018-01-23 19:11:26 - ERROR - following_link error Message: unknown error: Element <li class="_bnq48">...</li> is not clickable at point (572, 30). Other element would receive the click: <div class="_qlijk">...</div>
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.4.0-109-generic x86_64)

Traceback (most recent call last):
  File "unfollow.py", line 9, in <module>
    session.unfollow_users(amount=200, onlyInstapyFollowed = False, sleep_delay=3600 )
  File "/igb/InstaPy/instapy/instapy.py", line 1315, in unfollow_users
    self.logger)
  File "/igb/InstaPy/instapy/unfollow_util.py", line 271, in unfollow
    "//div[text()='Following']/following-sibling::div")
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Following']/following-sibling::div"}
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.4.0-109-generic x86_64)

root@rheumarelief:/igb/InstaPy# 

## InstaPy configuration
from instapy import InstaPy

session = InstaPy(username='user', password='pass', nogui=True)
session.login()

session.set_dont_unfollow_active_users(enabled=True, posts=5)
session.unfollow_users(amount=200, onlyInstapyFollowed = False, sleep_delay=3600 )

session.end()

**Comment by jermainee** [comment]
Duplicate of #1263
