### ISSUE TITLE
NameError: name 'session' is not defined

### ISSUE THREAD

**Issue by Eisblume77** [InstaPy/InstaPy#1274]
Here is the error code:

pi@raspberrypi:~/Projects/InstaPy $ sudo python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 11, in <module>
    multi_logs=True)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 134, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 219, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

I downloaded the chromedriver and extrakt to /asset - Folder.

**Comment by jermainee** [comment]
Chrome installed?

**Comment by luigifaticoso** [comment]
rpi2?

**Comment by Eisblume77** [comment]
I installed Raspbian (Noobs) on a RPi3. Chromium is installed and i downloaded 32bit chromedriver and unzipped in /asset Folder. 
Do i have to install Chrome instead of Chromium? Which Version of Chrome should i install then ??

**Comment by converge** [comment]
duplicated
#1249 #1222
