### ISSUE TITLE
Random error that kills service

### ISSUE THREAD

**Issue by liamthynne** [InstaPy/InstaPy#1284]
Error: Traceback (most recent call last):
  File "quickstart.py", line 35, in <module>
    ['handpoked'], amount=10, media='Photo')
  File "/Users/liam/InstaPy/instapy/instapy.py", line 725, in like_by_tags
    self.logger)
  File "/Users/liam/InstaPy/instapy/unfollow_util.py", line 341, in follow_user
    follow_button.click()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button class="_qv64e _iokts _4tgw8 _njrw0">...</button> is not clickable at point (221, 23). Other element would receive the click: <div class="_catib">...</div>
  (Session info: headless chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.2 x86_64)

I likes between 8-1500 photos and then does this.

**Comment by jermainee** [comment]
Duplicate of #1263
