### ISSUE TITLE
I can't install pyvirtualdisplay

### ISSUE THREAD

**Issue by kremenovic** [InstaPy/InstaPy#1288]
Hi, I am trying all night to install this thing and nothing can help me... 

pip install pyvirtualdisplay
Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: EasyProcess in /usr/local/lib/python3.5/dist-packages (from pyvirtualdisplay)

Can you help me to fix this? 
Thanks :)

**Comment by converge** [comment]
pip3 install pyvirtualdisplay

**Comment by kremenovic** [comment]
pip3 install pyvirtualdisplay
Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: EasyProcess in /usr/local/lib/python3.5/dist-packages (from pyvirtualdisplay)
-------------
pip --version
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)
-------------
python --version
Python 2.7.12
-------------

**Comment by kremenovic** [comment]
Okay, pip2 fixed this problem... Now when I want to login, it says:

stefan@stefan-HP-ProBook-430-G2:~/InstaPy$ python quickstart.py
2018-01-26 21:18:21 - INFO - Session started - 2018-01-26 21:18:21
Cookie file not found, creating cookie...
2018-01-26 21:18:56 - INFO - Session ended - 2018-01-26 21:18:56
2018-01-26 21:18:56 - INFO - --------------------


Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session.login()
  File "/home/stefan/InstaPy/instapy/instapy.py", line 253, in login
    self.bypass_suspicious_attempt):
  File "/home/stefan/InstaPy/instapy/login_util.py", line 115, in login_user
    "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
  File "/home/stefan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 385, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/stefan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 955, in find_element
    'value': value})['value']
  File "/home/stefan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/home/stefan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav[@class='_luodr']/ul[@class='_g8wl6']/li[@class='_538w0'][10]/span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=64.0.3282.119)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.13.0-32-generic x86_64)

**Comment by kremenovic** [comment]
Fixed:

https://github.com/timgrossmann/InstaPy/pull/1280

**Comment by luigifaticoso** [comment]
Close the issues?

**Comment by kremenovic** [comment]
Everything works fine right now :)

**Comment by luigifaticoso** [comment]
Can you please close the issue so we keep the issues list clean? thanks!
