### ISSUE TITLE
IndentationError: expected an indented block

### ISSUE THREAD

**Issue by RoyBkker** [InstaPy/InstaPy#1291]
## Expected Behavior
Should run the script. 

## Current Behavior
Giving error right away. Already did a new git clone and fresh install, but didn't help...
Commented the .clarifai_util import check_image in instapy.py. Furthermore didn't change any settings..

`D:\Projecten\InstaBot\InstaPy>start.bat

D:\Projecten\InstaBot\InstaPy>set PYTHONIOENCODING=UTF-8

D:\Projecten\InstaBot\InstaPy>py quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "D:\Projecten\InstaBot\InstaPy\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "D:\Projecten\InstaBot\InstaPy\instapy\instapy.py", line 20
    from .comment_util import comment_image
       ^
IndentationError: expected an indented block

D:\Projecten\InstaBot\InstaPy>`

## Possible Solution (optional)
Really don't know. 

## InstaPy configuration

**quickstart.py** 

`from instapy import InstaPy
import os
session = InstaPy(username='###', password='###')
session.login()
session.unfollow_users(amount=200)
session.set_upper_follower_count(limit = 800)
session.set_lower_follower_count(limit = 10)
session.like_by_tags(['ronaldo', ' messi', ' robben', ' soccer'], amount=50)

session.end()`

**Comment by ganeshkrishnan1** [comment]
seems to be an encoding issue. what OS?

**Comment by RoyBkker** [comment]
@ganeshkrishnan1. On Windows.

I now commented the if statement : 
 
```
# if os.name != 'nt':
#     from .clarifai_util import check_image
```

But now i get the following error. It could not login.. Bypass suspicious login will also not help login.. 


$ py quickstart.py
```
2018-01-27 11:56:05 - INFO - Session started - 2018-01-27 11:56:05
2018-01-27 11:56:05 - WARNING - Sorry, Record Activity is not working on Windows. We're working to fix this soon!
2018-01-27 11:56:38 - INFO - Session ended - 2018-01-27 11:56:38
2018-01-27 11:56:38 - INFO - --------------------


Cookie file not found, creating cookie...
Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session.login()
  File "D:\Projecten\InstaBot\InstaPy\instapy\instapy.py", line 253, in login
    self.bypass_suspicious_attempt):
  File "D:\Projecten\InstaBot\InstaPy\instapy\login_util.py", line 115, in login_user
    "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
  File "C:\Users\robakker\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 385, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\robakker\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 955, in find_element
    'value': value})['value']
  File "C:\Users\robakker\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\robakker\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav[@class='_luodr']/ul[@class='_g8wl6']/li[@class='_538w0'][10]/span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=64.0.3282.119)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 6.1.7601 SP1 x86_64)
```

**Comment by ganeshkrishnan1** [comment]
Look at the previous issues. There is a instagram change with login page. In instapy.py you need to set the 

self.switch_language = False

**Comment by RoyBkker** [comment]
@ganeshkrishnan1. 
Wow, you made my day. Thanks for the help!
