### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException

### ISSUE THREAD

**Issue by matteoFeduzi** [InstaPy/InstaPy#1299]
## Expected Behavior
How can i solve this error?

## Current Behavior

Traceback (most recent call last):
  File "quickstart.py", line 12, in <module>
    session.login()
  File "/Users/FeduziMatteo/Desktop/InstaPy-master/instapy/instapy.py", line 253, in login
    self.bypass_suspicious_attempt):
  File "/Users/FeduziMatteo/Desktop/InstaPy-master/instapy/login_util.py", line 115, in login_user
    "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav[@class='_luodr']/ul[@class='_g8wl6']/li[@class='_538w0'][10]/span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.1 x86_64)

## InstaPy configuration

from instapy import InstaPy

insta_username = 'Username'
insta_password = 'Password'

# set headless_browser=True if you want to run InstaPy on a server
try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      multi_logs=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit=2500)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['natgeo'], amount=1)

finally:
    # end the bot session
    session.end()

**Comment by harrydet** [comment]
Open instapy.py and change self.switch_langauge = True to False.

**Comment by clevebounce** [comment]
After changing self.switch_langauge = True to False, I couldn't logging although the same login info is valid and can be used to login manually.

2018-01-29 02:46:34 - INFO - Session started - 2018-01-29 02:46:34
Cookie file not found, creating cookie...
2018-01-29 02:46:48 - CRITICAL - Wrong login data!
2018-01-29 02:49:03 - WARNING - There are 0 people to follow
2018-01-29 02:49:28 - ERROR - following_link error list index out of range
2018-01-29 02:49:28 - INFO - Session ended - 2018-01-29 02:49:28
2018-01-29 02:49:28 - INFO - --------------------

**Comment by luigifaticoso** [comment]
don't use the email, use the username that could be an issue

**Comment by clevebounce** [comment]
@luigifaticoso I have all the while been using my username... nothing changed for my own setting

**Comment by clevebounce** [comment]
clearing cookies and cache seem to have solved the problem, thanks everyone

**Comment by converge** [comment]
[fixed](https://github.com/timgrossmann/InstaPy/pull/1328)
