### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by gphilips** [InstaPy/InstaPy#130]
There is a problem with the unicode character "horizontal ellipsis".
It says:

> UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 119: ordinal not in range(128)

**Comment by timgrossmann** [comment]
Please use the search function fist...

Duplicate of #45

**Comment by hojabbr** [comment]
Just add these lines to `quickstart.py` and `instapy.py`:

```
# -*- coding: UTF-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

**Comment by colindbx** [comment]
Hi! 
So first thing, I am not familiar at all with coding whatsoever, so pardon me if this seems stupid. I've tried the above fixes but I get this error when running "pip install ." Can someone help ? I need a step by step for dummies :) Thanks!

"Exception:
Traceback (most recent call last):
  File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 5: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 5: invalid continuation byte"

**Comment by BenedictLang** [comment]
Same for me.. tried setting encoding in console.
(Im on Win11 Powershell, Python 3.10.4, InstaPy  0.6.16)

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f525' in position 1875: character maps to <undefined>
Call stack:
  File "D:\Software\InstagramBot.py", line 21, in <module>
    session.follow_by_tags(["my_tags"], amount = 20)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 4919, in follow_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\like_util.py", line 618, in check_link
    logger.info("post_page: {}".format(post_page))
```
