### ISSUE TITLE
No such element. Unable to locate element: {"method":"xpath" ,"selector":"//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav[@class='_luodr']/ul[@class='_g8wl6']/li[@class='_ 538w0'][10]/span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option[text()='English']"}

### ISSUE THREAD

**Issue by amartiniuc** [InstaPy/InstaPy#1304]
Stack trace:

Traceback (most recent call last):
  File ".\q2.py", line 12, in <module>
    session.login()
  File "C:\py\InstaPy\instapy\instapy.py", line 253, in login
    self.bypass_suspicious_attempt):
  File "C:\py\InstaPy\instapy\login_util.py", line 115, in login_user
    "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
  File "C:\Users\andrei\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.
py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\andrei\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.
py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\andrei\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.
py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\andrei\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandl
er.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath"
,"selector":"//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav[@class='_luodr']/ul[@class='_g8wl6']/li[@class='_
538w0'][10]/span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.16299 x86_6
4)

**Comment by RoyBkker** [comment]
Set self.switch_language to  False in instapy.py

**Comment by amartiniuc** [comment]
Thanks

**Comment by clevebounce** [comment]
After setting self.switch_language to False in instapy.py

I couldn't logging at all although the same login info is valid when logging in manually

2018-01-29 02:46:34 - INFO - Session started - 2018-01-29 02:46:34
Cookie file not found, creating cookie...
2018-01-29 02:46:48 - CRITICAL - Wrong login data!
2018-01-29 02:49:03 - WARNING - There are 0 people to follow
2018-01-29 02:49:28 - ERROR - following_link error list index out of range
2018-01-29 02:49:28 - INFO - Session ended - 2018-01-29 02:49:28
2018-01-29 02:49:28 - INFO - --------------------

**Comment by estebancortero** [comment]
Switching self.switch_language to False solved it for me. Try deleting the cookie and try again, double checking the login info.

**Comment by clevebounce** [comment]
@estebancortero clearing cookies and cache seem to have solved the problem, thank you

**Comment by converge** [comment]
[fixed](https://github.com/timgrossmann/InstaPy/pull/1328)
