### ISSUE TITLE
quickstart.py command prompt errors

### ISSUE THREAD

**Issue by alex30020** [InstaPy/InstaPy#1315]
My chromedrive.exe is in the /assets

C:\Users\Alexis>python "C:\Users\Alexis\Desktop\InstaPy\quickstart.py"
Traceback (most recent call last):
  File "C:\Users\Alexis\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Users\Alexis\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Alexis\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alexis\Desktop\InstaPy\quickstart.py", line 10, in <module>
    headless_browser=True)
  File "C:\Users\Alexis\Desktop\InstaPy\instapy\instapy.py", line 134, in __init__
    self.set_selenium_local_session()
  File "C:\Users\Alexis\Desktop\InstaPy\instapy\instapy.py", line 222, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\Alexis\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in __init__
    self.service.start()
  File "C:\Users\Alexis\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alexis\Desktop\InstaPy\quickstart.py", line 25, in <module>
    session.end()
NameError: name 'session' is not defined
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x00000178518F3748>>
Traceback (most recent call last):
  File "C:\Users\Alexis\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 163, in __del__
    self.stop()
  File "C:\Users\Alexis\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 135, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'

**Comment by converge** [comment]
do you have chrome browser installed ?

**Comment by alex30020** [comment]
Yes ...

**Comment by converge** [comment]
is chromedriver in assets folder?

**Comment by alex30020** [comment]
yes, i wrote that in the beginning of the post!😊

**Comment by converge** [comment]
sorry.
Are you using Selenium last version ? pip install selenium -U

**Comment by alex30020** [comment]
I will try to delete everything - and start from scratch . See how it works then 👍 .
But thank you !
