### ISSUE TITLE
Script not starting ?

### ISSUE THREAD

**Issue by wizarduk** [InstaPy/InstaPy#1321]
This has started to happen on x 6 accounts ?

I have tried to do a few things but nothing is working anyone know a fix ?

INFO - Session started - 2018-01-31 08:30:16
Traceback (most recent call last):
  File "trpy", line 9, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 208, in login
    self.switch_language):
  File "/root/InstaPy/instapy/login_util.py", line 18, in login_user
    "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriv                     er.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriv                     er.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriv                     er.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorha                     ndler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Una                     ble to locate element: {"method":"xpath","selector":"//footer[@class='_s5vm9']/d                     iv[@class='_g7lf5 _9z659']/nav[@class='_luodr']/ul[@class='_g8wl6']/li[@class='_                     538w0'][10]/span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option[text()='                     English']"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cc                     e4),platform=Linux 2.6.32-042stab126.2 x86_64)

**Comment by uluQulu** [comment]
What is your OS language?

**Comment by wizarduk** [comment]
@uluQulu i done this 
also, you can do this by toggling it inside InstaPy class

it still doesnt work ?

**Comment by uluQulu** [comment]
you might try commenting out

**Comment by wizarduk** [comment]
@uluQulu what does that mean ?

**Comment by acekreations** [comment]
I seem to be having the same problem. I could be wrong, but it seems as though Instagram is redirecting to the create account page after InstaPy tries to go to the login page. Could this be the issue?

**Comment by converge** [comment]
[fixed](https://github.com/timgrossmann/InstaPy/pull/1328)
