### ISSUE TITLE
Error on my server with selenium and logging

### ISSUE THREAD

**Issue by 0-hero** [InstaPy/InstaPy#1335]
## Expected Behavior
Login and start the script.

## Current Behavior
Works sometimes on my mac but doesn't work on my server

Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 263, in login
    log_follower_num(self.browser, self.username, self.logfolder)
  File "/root/InstaPy/instapy/print_log_writer.py", line 8, in log_follower_num
    browser.get('https://www.instagram.com/' + username)
  File "/usr/local/lib/python3.6/dist-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/dist-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=64.0.3282.119)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.13.0-31-generic x86_64)

## InstaPy configuration

from instapy import InstaPy

insta_username = ''
insta_password = ''

try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False)
    session.login()

    session.like_by_tags(['love','instagood','tbt','picoftheday','follow4follow'], amount=100)
    session.set_do_comment(enabled=True, percentage=25)
    session.set_comments(['Awesome', 'Really Cool', 'Good One','Awesome Pic'])
    session.set_do_follow(enabled=True, percentage=40)
    session.follow_user_followers([''], amount=100, random=True, sleep_delay=60)

finally:
    # end the bot session
    session.end()

**Comment by IKDH** [comment]
I have got this error this morning : 

```
File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 323, in get
   self.execute(Command.GET, {'url': url})
 File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
   self.error_handler.check_response(response)
 File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
   raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
 (Session info: headless chrome=63.0.3239.108)
 (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.9.0-4-amd64 x86_64)
```
I was running 3 scripts on OVH that shut down at approximately the same time.

**Comment by IKDH** [comment]
ramprasadc which server are you using ? I would like to know if this problem come from my server (OVH) or if it doesn't.

**Comment by 0-hero** [comment]
I'm using a digitalocean droplet @Idrisskh

**Comment by alextousss** [comment]
I'm having the same issue on my Ubuntu PC. I run the script using headless and nogui arguments

**Comment by kushpvo** [comment]
I'm having the same error on my Raspberry Pi 3 B+ . Running the script with nogui argument.
