### ISSUE TITLE
cannot read property owner

### ISSUE THREAD

**Issue by sugionodjojo** [InstaPy/InstaPy#134]
this is the comment 

root@ubuntu-1gb-sgp1-01:/InstaPy# python3.5 quickstart.py
Logged in successfully!
Tag [1/5]
--> **************
[1/100]
Traceback (most recent call last):
  File "quickstart.py", line 23, in <module>
    .like_by_tags(['*****************'], amount=100) \
  File "/InstaPy/instapy/instapy.py", line 235, in like_by_tags
    self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)
  File "/InstaPy/instapy/like_util.py", line 59, in check_link
    user_name = browser.execute_script("return window._sharedData.entry_data.PostPage[0].media.owner.username")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'owner' of undefined
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-72-generic x86_64)

anyone experience that too?

i tried to upload old version of quickstart.py , like-util.py ( which works before) , but still got the same comment.

maybe need to upgrade chromedriver or anything?

**Comment by sakowicz** [comment]
https://github.com/timgrossmann/InstaPy/issues/131

**Comment by pekapa** [comment]
I'm closing this as this is the same as #131 
A quick fix can be found at #132 but we are working on bigger improvements to avoid this kind of problems in the future.
