### ISSUE TITLE
error "Cookie file not found..."

### ISSUE THREAD

**Issue by Jenuan** [InstaPy/InstaPy#1341]
I keep getting this error
Cookie file not found, creating cookie...
Traceback (most recent call last):
  File "C:\Users\jenua\OneDrive\Documents\InstaPy\VisualFollow.py", line 15, in <module>
    session.login()
  File "C:\Users\jenua\OneDrive\Documents\InstaPy\instapy\instapy.py", line 227, in login
    self.bypass_suspicious_attempt):
  File "C:\Users\jenua\OneDrive\Documents\InstaPy\instapy\login_util.py", line 114, in login_user
    "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
  File "C:\Users\jenua\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 368, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\jenua\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 858, in find_element
    'value': value})['value']
  File "C:\Users\jenua\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jenua\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav[@class='_luodr']/ul[@class='_g8wl6']/li[@class='_538w0'][10]/span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.15063 x86_64)

**Comment by uluQulu** [comment]
@Jenuan [this](https://github.com/timgrossmann/InstaPy/pull/1328/files) may help

**Comment by Jenuan** [comment]
@uluQulu is it because im not running chrome in english?? i dont get it, i can run instapy with no problem with one account but not the other one. 
i use the same code for both accounts.

**Comment by uluQulu** [comment]
@Jenuan 
I am not sure about the problem, did it help any?

**Comment by Jenuan** [comment]
@uluQulu yeah man, thx! I had rewritten the code u sent me in the first reply wrong.
