### ISSUE TITLE
Insta Py crashed

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#135]
My error message:
```
C:\Users\Daniel\Downloads\InstaPy-master\InstaPy-master>python quickstart.py
Logged in successfully!
Tag [1/2]
--> b'design'
[1/57]
Traceback (most recent call last):
  File "quickstart.py", line 23, in <module>
    .like_by_tags(['design', '#wallpaper'], amount=200) \
  File "C:\Users\Daniel\Downloads\InstaPy-master\InstaPy-master\instapy\instapy.py", line 235, in like_by_tags
    self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)
  File "C:\Users\Daniel\Downloads\InstaPy-master\InstaPy-master\instapy\like_util.py", line 59, in check_link
    user_name = browser.execute_script("return window._sharedData.entry_data.PostPage[0].media.owner.username")
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'owner' of undefined
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.15063 x86_64)
 
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x035CC6B0>>
Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 163, in __del__
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 139, in stop
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down
```

Why does it crash after InstaPy searched for the images of the hashtag? @timgrossmann

**Comment by sugionodjojo** [comment]
--> b'design'

this part with new git clone, eventhough replace quickstart.py with old one, still got "b" in front of tag.

**Comment by ghost** [comment]
Sry, belongs to another issue: #131
