### ISSUE TITLE
unknown error: Cannot read property 'owner' of undefined

### ISSUE THREAD

**Issue by dincerkurnaz** [InstaPy/InstaPy#136]
[1/93]
Traceback (most recent call last):
  File "quickstart.py", line 23, in <module>
    .like_by_tags(['dog', '#cat'], amount=100) \
  File "/Users/dincer/InstaPy/instapy/instapy.py", line 235, in like_by_tags
    self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)
  File "/Users/dincer/InstaPy/instapy/like_util.py", line 59, in check_link
    user_name = browser.execute_script("return window._sharedData.entry_data.PostPage[0].media.owner.username")
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'owner' of undefined
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.4 x86_64)

**Comment by pekapa** [comment]
Same as #131 
Please have a look over there, we are working on some big changes but, for now, #132 should fix it.
