### ISSUE TITLE
Exception AttributeError

### ISSUE THREAD

**Issue by supm3n** [InstaPy/InstaPy#1361]
I need help fixing this problem
![aaaa](https://user-images.githubusercontent.com/36124577/35824359-e7ca6b54-0ab2-11e8-9bef-e33db1530458.PNG)

**Comment by craigricker** [comment]
Ensure that you followed all setup directions, including the important step below:

> Download chromedriver for your system from [here](https://sites.google.com/a/chromium.org/chromedriver/downloads). Extract the .zip file and put it in /assets folder.

**Comment by StromboliKQ** [comment]
im getting this error 

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "docker_quickstart.py", line 18, in worker
    bot.login()
  File "/code/instapy/instapy.py", line 264, in login
    self.bypass_suspicious_attempt):
  File "/code/instapy/login_util.py", line 94, in login_user
    browser.get('https://www.instagram.com')
AttributeError: 'NoneType' object has no attribute 'get'`
