### ISSUE TITLE
Issue running quickstart.py related to chromedriver?

### ISSUE THREAD

**Issue by em773** [InstaPy/InstaPy#1387]
I just finished setting up a Raspberry Pi with InstaPy.  I followed the README.  I'm having trouble running quickstart.py.

Any thoughts on this?  My traceback and quickstart.py are below. Thanks in advance!

```
pi@raspberrypi:~/Projects/InstaPy $ 
pi@raspberrypi:~/Projects/InstaPy $ sudo python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    multi_logs=True)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 142, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 230, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service ./assets/chromedriver unexpectedly exited. Status code was: -4


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.end()
NameError: name 'session' is not defined
pi@raspberrypi:~/Projects/InstaPy $ 
```

```
from instapy import InstaPy

insta_username = 'x'
insta_password = 'x'

# set headless_browser=True if you want to run InstaPy on a server
try:
    # set these if you're locating the library in the /usr/lib/pythonX.X/ directory
    # Settings.database_location = '/path/to/instapy.db'
    # Settings.browser_location = '/path/to/chromedriver'
    
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      multi_logs=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit=2500)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['natgeo'], amount=1)

finally:
    # end the bot session
    session.end()
```

**Comment by sandes** [comment]
nogui=True parameter is necessary in InstaPy

**Comment by em773** [comment]
Thanks for the suggestion. I tried adding the nogui=True parameter to the InstaPy() constructor. I see the same issue.

**Comment by riccardorighettiphoto** [comment]
same issue here... running on a CentOS 7.x VPS with Python3.6.4
