### ISSUE TITLE
How to fix this issue during 'pip install .'

### ISSUE THREAD

**Issue by vladislav-vasilenko** [InstaPy/InstaPy#1397]
pip install .

## Current Behavior
During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python3.6/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 559, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/selenium-3.7.0.dist-info/DESCRIPTION.rst'
```

**Comment by txaiwieser** [comment]
Same, had done a clean install of my macOS

**Comment by eschick** [comment]
Same here

**Comment by ghost** [comment]
Checkout this guide for MacOS

https://github.com/vijetahingorani/InstaPy-wiki/blob/master/Mac-OSX-%20Setup.md
