### ISSUE TITLE
scroll on chromedriver is now stopping today

### ISSUE THREAD

**Issue by Webmatthieu** [InstaPy/InstaPy#1401]
## Expected Behavior
Scroll in following users worked yesterday and today, no
## Current Behavior
Scroll is stopping at the beginning of the list 
## InstaPy configuration
On windows 10

```
C:\InstaPy\InstaPy-master>set PYTHONIOENCODING=UTF-8

C:\InstaPy\InstaPy-master>py quickstart.py

DevTools listening on ws://127.0.0.1:12306/devtools/browser/330896b8-5c4a-45d6-9
77b-f57d5ee2afa3
[7460:7916:0210/172521.929:ERROR:mf_helpers.cc(14)] Error in dxva_video_decode_a
ccelerator_win.cc on line 542
INFO [lepetitcordon]  Session started - 2018-02-10 17:25:22
WARNING [lepetitcordon]  Sorry, Record Activity is not working on Windows. We're
 working to fix this soon!
[2052:1348:0210/172526.657:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
[2052:1348:0210/172526.665:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
INFO [lepetitcordon]  Logged in successfully!
INFO [lepetitcordon]  Number of people followed automatically remaining: 420
[2052:1348:0210/172531.471:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
[2052:1348:0210/172531.474:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session.unfollow_users(amount=30)
  File "C:\InstaPy\InstaPy-master\instapy\instapy.py", line 1339, in unfollow_us
ers
    self.logfolder)
  File "C:\InstaPy\InstaPy-master\instapy\unfollow_util.py", line 277, in unfoll
ow
    scroll_bottom(browser, dialog, allfollowing)
  File "C:\InstaPy\InstaPy-master\instapy\util.py", line 186, in scroll_bottom
    "arguments[0].scrollTop = arguments[0].scrollHeight", element)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python36\lib\site-pac
kages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python36\lib\site-pac
kages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python36\lib\site-pac
kages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call func
tion result missing 'value'
  (Session info: chrome=65.0.3325.51)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87a
f1),platform=Windows NT 6.3.9600 x86_64)

[2052:1348:0210/172933.267:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
```

**Comment by Webmatthieu** [comment]
file quickstart.py
```
from instapy import InstaPy
import os
session = InstaPy(username='lepetitcordon', password='xxxxxxxx')
session.login()
session.set_do_comment(enabled=True, percentage=60)
session.set_comments([u'Canonnn 😍', u'❤️', u'👍👍👍', u'😍😍😍', u'Waouh ❤️', u'Canon ❤✌😍', 'Magnifique photo', u'Belle photo 😶', u'Top 😍', u'Jadore!!! 💕', u'💕❤💕', u'Sublime❤', u'Superbe 😍', 'superbe photo !!', u'CANON 😍😍' ])
session.set_do_follow(enabled=True, percentage=20, times=1)
session.unfollow_users(amount=30)
session.follow_user_followers(['lepetitlunetier', 'lesboomeuses', 'terrafemina', 'femme_actuelle' ], randomize=True, sleep_delay=60)
session.like_by_tags(['#frenchgirl', '#frenchblogger'], amount=50, media='Photo')
session.end()
```

**Comment by keusta** [comment]
@Webmatthieu Dont paste your login/password (you got a nice fish pic now ;)
and [try this fix](https://github.com/timgrossmann/InstaPy/issues/1365#issuecomment-363586896)

**Comment by Webmatthieu** [comment]
Holyu crap !! I was so tired....
HAHA thanks ! Nice fish pic !
