### ISSUE TITLE
Element is not currently interactable and may not be manipulated

### ISSUE THREAD

**Issue by Freddorick** [InstaPy/InstaPy#1409]
I don't fully understand what causes the error. The log claims that the image pool of a user is not large enough, although it actually is.

## Expected Behavior
When commenting images using like_by_tag I in conjunction with set_user_interact I occasionally run into this issue. 

## Current Behavior
The script terminates. 

**The log output is:**

INFO [instaaccount]  -------------
INFO [instaaccount]  --> Given amount not fullfilled, image pool reached its end

INFO [instaaccount]  Liked: 5
INFO [instaaccount]  Already Liked: 1
INFO [instaaccount]  Inappropriate: 1
INFO [instaaccount]  Commented: 2
INFO [instaaccount]  Session ended - 2018-02-11 09:07:56
INFO [instaaccount]  --------------------

**Traceback:**
```

Traceback (most recent call last):
  File "/Users/xxx/InstaPy/tag_follow.py", line 214, in <module>
    session.like_by_tags(['tag1', 'tag2'], amount=27, interact = True)
  File "/Users/xxx/InstaPy/instapy/instapy.py", line 913, in like_by_tags
    self.logfolder)
  File "/Users/xxx/InstaPy/instapy/comment_util.py", line 46, in comment_image
    comment_input[0].clear()
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 87, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidElementStateException: Message: invalid element state: Element is not currently interactable and may not be manipulated
  (Session info: chrome=64.0.3282.140)
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.3 x86_64)
```

## Possible Solution
An exception handler would fix it quickly. This fixed it for me:

```

def comment_image(browser, username, comments, blacklist, logger, logfolder):
    """Checks if it should comment on the image"""
    missing_comment_elem_warning = ('--> Warning: Comment Action Likely Failed:'
                                    ' Probably InvalidElementStateException')
    rand_comment = (choice(comments).format(username))
    rand_comment = emoji.demojize(rand_comment)
    rand_comment = emoji.emojize(rand_comment, use_aliases=True)

    open_comment_section(browser)
    comment_input = get_comment_input(browser)
    try:
        if len(comment_input) > 0:
            comment_input[0].clear()
            comment_input = get_comment_input(browser)

            browser.execute_script(
                "arguments[0].value = '" + rand_comment + " ';", comment_input[0])
            # An extra space is added here and then deleted.
            # This forces the input box to update the reactJS core
            comment_input[0].send_keys("\b")
            comment_input = get_comment_input(browser)
            comment_input[0].submit()
            update_activity('comments')
            if blacklist['enabled'] is True:
                action = 'commented'
                add_user_to_blacklist(
                    browser, username, blacklist['campaign'], action, logger, logfolder
                )
        else:
            logger.warning('--> Warning: Comment Action Likely Failed:'
                           ' Comment Element not found')

        logger.info("--> Commented: {}".format(rand_comment.encode('utf-8')))
        sleep(2)
        
    except WebDriverException:
        print(missing_comment_elem_warning)

    return 1
```

## Instapy Setup

```
    session.set_user_interact(amount=7, randomize=False, percentage=100, media='Photo')
    session.set_upper_follower_count(limit=5000)
    session.set_lower_follower_count(limit = 100)
    session.set_do_comment(True, percentage=50)
    session.set_do_follow(enabled=True, percentage=40)
    session.set_dont_like(['food'])
    session.set_comments(comments_list)
    
    session.like_by_tags(['tag1', 'tag2'], amount=27, interact = True)
```

**Comment by bunducafe** [comment]
I have the same error, but where to put that exception handler?

**Comment by dbknv** [comment]
I also have the same error. To fix it I just replace 
`comment_input[0].clear() -> #comment_input[0].clear()`

**Element is not currently interactable and may not be manipulated** is well known problem with clear() function. 

or it could be replaced by
```
 comment_input[0].sendKeys(Keys.CONTROL + "a");
 comment_input[0].sendKeys(Keys.DELETE);
```
