### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Lazydrippa** [InstaPy/InstaPy#1434]
Every time I attempt to run InstaPy I'm faced with this error message, any ideas how to fix this?

`Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    session.login()
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 271, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "/home/ubuntu/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: chrome=64.0.3282.167)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.4.0-1050-aws x86_64)`

**Comment by agcty** [comment]
I get a similar error, it looks like this: Traceback (most recent call last):
  File "instabot.py", line 34, in <module>
    session.like_by_tags(['#fashion', '#traveler', '#like4like'], amount=50)
  File "/Users/agcty/code/python/InstaPy/instapy/instapy.py", line 843, in like_by_tags
    self.logger)
  File "/Users/agcty/code/python/InstaPy/instapy/like_util.py", line 488, in check_link
    "return window._sharedData.entry_data."
  File "/Users/agcty/code/python/InstaPy/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "/Users/agcty/code/python/InstaPy/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Users/agcty/code/python/InstaPy/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: chrome=64.0.3282.167)
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.3 x86_64)

**Comment by agcty** [comment]
I get a similar error, it looks like this:

Traceback (most recent call last):
  File "instabot.py", line 34, in <module>
    session.like_by_tags(['#tag1', '#tag2', '#tag3'], amount=50)
  File "/Users/agcty/code/python/InstaPy/instapy/instapy.py", line 843, in like_by_tags
    self.logger)
  File "/Users/agcty/code/python/InstaPy/instapy/like_util.py", line 488, in check_link
    "return window._sharedData.entry_data."
  File "/Users/agcty/code/python/InstaPy/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "/Users/agcty/code/python/InstaPy/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Users/agcty/code/python/InstaPy/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: chrome=64.0.3282.167)
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.3 x86_64)

**Comment by uluQulu** [comment]
Hi guys, have a look at #1338 
it's a common temporary outage error
```
WebDriverException: Message: unknown error: Cannot read property~
```
the solution to handle the error is also common
but specifically, @Lazydrippa you would modify `log_follower_num()` in `print_logwriter.py` file
```python
followed_by = browser.execute_script(
   "return window._sharedData.""entry_data.ProfilePage[0]."
   "user.followed_by.count")
```
will be
```python
from selenium.common.exceptions import WebDriverException   #import this at top of the file

try:
    followed_by = browser.execute_script(
        "return window._sharedData.""entry_data.ProfilePage[0]."
        "user.followed_by.count")
except WebDriverException:   #handle the possible `entry_data` error
    try:
        browser.execute_script("location.reload()")
        followed_by = browser.execute_script(
            "return window._sharedData.""entry_data.ProfilePage[0]."
            "user.followed_by.count")
    except WebDriverException:
        followed_by = None
```
As for @agcty 
I think, [this](https://github.com/timgrossmann/InstaPy/issues/1338#issuecomment-363608708) will help

If you encounter any kind of this error, handle it similarly..

**Comment by Lazydrippa** [comment]
I've resolved the issue by downloading a completely fresh copy of Instapy and removing the old one, this seemed to resolve the issue for me.

**Comment by kevXZY** [comment]
@uluQulu Would you care to share the customized print_logwriter.py ? Thanks :)

**Comment by uluQulu** [comment]
@neomh my `print_log_writer.py` file has other modifications, too
share your file, I will help and I think you are having the similar error as in above

**Comment by kevXZY** [comment]
@uluQulu Here's my file: https://pastebin.com/Pfay7Xjn . I'm also getting " unknown error: Cannot read property '0' of undefined".

**Comment by uluQulu** [comment]
here is the [gist](https://gist.github.com/uluQulu/d85ba08f849f360bdbcfbe067e48c731) @neomh

**Comment by kevXZY** [comment]
@uluQulu error gone but i can see this now 
--> Warning: Comment Button Not Found: May cause issues with browser windows of smaller widths
WARNING [kevpref]  --> Warning: Comment Action Likely Failed: Comment Element not found

**Comment by uluQulu** [comment]
Well, it's another issue, use `click_element()` function to click
