### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ceriusss** [InstaPy/InstaPy#1438]
## 

Traceback (most recent call last):
  File "D:\pro\instagram fol\InstaPy-master3\quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "D:\pro\instagram fol\InstaPy-master3\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "D:\pro\instagram fol\InstaPy-master3\instapy\instapy.py", line 11, in <module>
    from pyvirtualdisplay import Display
  File "D:\pro\instagram fol\InstaPy-master3\pyvirtualdisplay\__init__.py", line 3, in <module>
    from pyvirtualdisplay.display import Display
  File "D:\pro\instagram fol\InstaPy-master3\pyvirtualdisplay\display.py", line 1, in <module>
    from pyvirtualdisplay.abstractdisplay import AbstractDisplay
  File "D:\pro\instagram fol\InstaPy-master3\pyvirtualdisplay\abstractdisplay.py", line 1, in <module>
    from easyprocess import EasyProcess
  File "D:\pro\instagram fol\InstaPy-master3\easyprocess\__init__.py", line 227
    except OSError, oserror:
                  ^
SyntaxError: invalid syntax
>>>

**Comment by ivanyschen** [comment]
@ceriusss `except OSError, oserror:` is not used anymore in Python3. Instead, the correct syntax would be `except OSError as oserror:`

**Comment by ceriusss** [comment]
@ujhuyz0110 thank you
