### ISSUE TITLE
problem to use this library :( - Please help!

### ISSUE THREAD

**Issue by mehrab-wj** [InstaPy/InstaPy#1440]
hi guys 
i tried to use this library and i think i install all of required packages.
i write this codes : 
```
from instapy import InstaPy
#print 'starting follow server ...'

insta_username = 'mbin1379'
insta_password = '13791379'

# if you want to run this script on a server,
# simply add nogui=True to the InstaPy() constructor
session = InstaPy(username=insta_username, password=insta_password,nogui=True)
session.login()

accs = ['mehrawb_pv','marketeman']
session.follow_by_list(accs, times=1)

# end the bot session
session.end()
```
but i got this errors : 

```
Traceback (most recent call last):
  File "follow.py", line 11, in <module>
    session = InstaPy(username=insta_username, password=insta_password,nogui=True)
  File "/home/mehrab/Desktop/InstaPy/instapy/instapy.py", line 142, in __init__
    self.set_selenium_local_session()
  File "/home/mehrab/Desktop/InstaPy/instapy/instapy.py", line 230, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/mehrab/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/mehrab/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/mehrab/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/home/mehrab/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/mehrab/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.13.0-32-generic x86_64)

```

please help me to slove this problem ❤️

**Comment by hm8941** [comment]
"unknown error: cannot find Chrome binary"   

Have you installed chrome?

Also, did you install the chrome driver into the assets folder?

**Comment by hm8941** [comment]
Also, you posted your ID and Password, edit that out.   I almost gave you an interesting profile picture.

**Comment by mehrab-wj** [comment]
@hm8941 no problem bro
its not my instagram account .
also this is chromedriver in my assets folder:
![image](https://user-images.githubusercontent.com/13809573/36343007-89870b8e-141b-11e8-9f61-b67725df684c.png)

**Comment by mehrab-wj** [comment]
guys please help :cry:

**Comment by mehrab-wj** [comment]
go up :(
i really need to use this library !!!
