### ISSUE TITLE
load button not found, working with current images! help!

### ISSUE THREAD

**Issue by saunlani** [InstaPy/InstaPy#1477]
## Current Behavior

WARNING [username]  Load button not found, working with current images!
Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.end()
  File "/root/InstaPy/instapy/instapy.py", line 1748, in end
    self.browser.delete_all_cookies()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 759, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: no such session
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.4.0-104-generic x86_64)

**Comment by saunlani** [comment]
This is a ubuntu install on a digital ocean server
