### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by vernak2539** [InstaPy/InstaPy#148]
python 3.6 (also with 2.7)

quickstart.py looks like this

```python
dont_like = ['thing0']
ignore_words = ['thing1']
friend_list = ['tester']

InstaPy(username="XXX", password="XXX")\
  .login()\
  .set_upper_follower_count(limit=2000) \
  .set_do_comment(True, percentage=20) \
  .set_comments(['Nice shot!', 'Sooo cool', 'Amazing!']) \
  .set_dont_include(friend_list) \
  .set_dont_like(dont_like) \
  .set_ignore_if_contains(ignore_words) \
  .like_by_tags(['travelphotography'], amount=20) \
  .end()
```

getting the following error
```
[10/20]
Image from: b'shortcutofmylife'
Number of Followers: 280
Link: b'https://www.instagram.com/p/BTCxMUOAUjR/?tagged=travelphotography'
Description: b'#streetart #taupo \xf0\x9f\x8f\xa2\n\n#ethnic #tag #travelling #newzealand #oceania \xf0\x9f\x8c\x8f #instatravel #travelgram #trip #travelphotography #nofilter #iphone7 \xf0\x9f\x93\xb7'
Traceback (most recent call last):
  File "quickstart.py", line 29, in <module>
    .like_by_tags(['travelphotography'], amount=20) \
  File "/Users/vernacchia/Coding/InstaPy/instapy/instapy.py", line 271, in like_by_tags
    self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)
TypeError: 'NoneType' object is not iterable
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x102281d30>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 163, in __del__
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 139, in stop
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by pekapa** [comment]
Same as #147,
Should be fixed now, please update and let us know if it persists (closing this for now)
