### ISSUE TITLE
"Owner" not specified?

### ISSUE THREAD

**Issue by amilios** [InstaPy/InstaPy#149]
I keep getting the following exception:
```

Traceback (most recent call last):
  File "server.py", line 41, in <module>
    session.like_by_tags(tags, amount=AMOUNT)
  File "/root/InstaPy/instapy/instapy.py", line 208, in like_by_tags
    self.ignore_if_contains, self.username)
  File "/root/InstaPy/instapy/like_util.py", line 56, in check_link
    user_name = browser.execute_script("return window._sharedData.entry_data.PostPage[0].media.owner.username")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'owner' of undefined
  (Session info: chrome=57.0.2987.98)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-72-generic x86_64)
```

What could be the cause?

**Comment by komad1na** [comment]
Maybe you should try with Python 3.5 instead of 2.7 

Similar errors #134 and #131

**Comment by blesson3** [comment]
@amilios Have you updated to the latest commit? There was a PR #132 earlier that fixed my issue which looked exactly like yours.
I am currently using python `2.7.13` and that PR fixed my issue.

**Comment by eduardocalazansjr** [comment]
This is not version related.
For some users it won't work. Wait for a fix
