### ISSUE TITLE
[SOLVED] NameError: name 'session' is not defined - Line 30

### ISSUE THREAD

**Issue by stainless33** [InstaPy/InstaPy#1502]
When attempting to run quickstart.py

```
Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    multi_logs=True)
  File "/root/InstaPy/instapy/instapy.py", line 142, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 230, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.4.0-112-generic x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.end()
NameError: name 'session' is not defined
```
**Running:**
Ubuntu 16.04.3
Python Version 3.5

Chrome web driver is in InstaPy/assets but Chrome seems to fail to start

**UPDATE:** Adding `nogui=True` to quickstart.py resolved my issue

**Comment by info3g** [comment]
I am getting this after run the 
python quickstart.py  command


Traceback (most recent call last):
  File "quickstart.py", line 29, in <module>
    session.end()
NameError: name 'session' is not defined
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7f21cd4b5750>> ignored

**Comment by info3g** [comment]
could you please let me know the  issue..!
