### ISSUE TITLE
Import Error: No module named requests

### ISSUE THREAD

**Issue by rohan11103** [InstaPy/InstaPy#1512]
## Current Behavior
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/Rohan/Documents/Instapy/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/Users/Rohan/Documents/Instapy/InstaPy/instapy/instapy.py", line 16, in <module>
    import requests
ImportError: No module named requests
Nick-Connors-Mac:Instapy Rohan$

**Comment by rohan11103** [comment]
I resolved this by using
sudo pip install emoji

sudo pip install requests
