### ISSUE TITLE
[Crash] WebDriverException. Unknown error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by MrBeardedGuy** [InstaPy/InstaPy#1520]
## Expected Behavior
The script should complete it's course without crashing 😉

## Current Behavior
It happened various times in the last 7 days quite randomly. Sometimes the script crashes after running few times ` session.like_by_tags` or `session.follow_user_following` but always returns this error. 

```
INFO [2018-02-28 18:20:56] [HIDDEN VALUE 😉]  Image from: marbook
Process Process-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "quickstart.py", line 67, in worker
    session.like_by_tags(amount=random.randint(3,8), use_smart_hashtags=True, interact=True)
  File "/Users/HIDDEN VALUE 😉/InstaPy/instapy/instapy.py", line 872, in like_by_tags
    self.user_interact_media)
  File "/Users/HIDDEN VALUE 😉/InstaPy/instapy/instapy.py", line 1041, in like_by_users
    self.logger)
  File "/Users/HIDDEN VALUE 😉/InstaPy/instapy/like_util.py", line 488, in check_link
    "return window._sharedData.entry_data."
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: headless chrome=64.0.3282.186)
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.3 x86_64)
```

## InstaPy configuration
```
import random 
from instapy import InstaPy
import os
import schedule
import multiprocessing
import datetime
import time

global users, psw, followersToFollow, smartTags, followLocation

# Trying with just 1 user now
users = ['username1']
psw = ['pass1']

#followersToFollow = [['acc1Relatedtousers1', 'acc2Relatedtousers1'], ['acc1Relatedtousers2']]
# followLocation = ['', '224442573/salton-sea/']

followersToFollow = [['User1', 'User2','User3']]
smartTags = [['Tag1', 'Tag2', 'Tag3']]


def worker(sel):
    
    startTime = datetime.datetime.now().strftime("%H:%M:%S")
    
    #TO_DO Date subtraction
    print("~~~~~~~ - Started as",users[sel],"at",startTime)
    session = InstaPy(username=users[sel], password=psw[sel], headless_browser=True)
    session.login()

    ####### INCREASE SPEED ######
    # session.set_sleep_reduce(5)    # BREAKS THE UNFOLLOW FUNCTION NOT SURE WHY... 


    ######## SETTINGS ########
    session.set_dont_unfollow_active_users(enabled=True, posts=20)
    session.set_user_interact(amount=random.randint(3,8), randomize=True, percentage=70, media='Photo')
    session.set_upper_follower_count(limit = 64875)
    session.set_lower_follower_count(limit = 388)
    session.set_do_comment(enabled=True, percentage=20)
    session.set_smart_hashtags(smartTags[sel], limit=random.randint(2,4), sort='random', log_tags=True)
    session.set_comments([
        u'Amazing! :two_hearts:', 
        u'Loooovely :sparkling_heart:', 
        u'Killin it!! :two_hearts: :two_hearts: :scream:', 
        u':sparkling_heart::sparkling_heart::sparkling_heart:', 
        u'Loooove it :sparkling_heart:', 
        u'Niiiice :sparkling_heart:', 
        u'Nice shot! @{} :sparkling_heart:'
        u':heart_eyes:'
        ], media='Photo')
    

    ######## ACTIONS ########
    

    session.like_by_feed(amount=random.randint(5,11), randomize=True, unfollow=True)
    print("~~~~~~~ -",users[sel],"finished liking by feed at",datetime.datetime.now().strftime("%H:%M:%S"))

    session.unfollow_users(amount=random.randint(19,32), onlyInstapyFollowed=True, onlyInstapyMethod = 'FIFO', sleep_delay=(random.randint(44,111)))
    print("~~~~~~~ -",users[sel],"finished unfollowing at",datetime.datetime.now().strftime("%H:%M:%S"))
      
    if followersToFollow[sel]:
         session.follow_user_following(followersToFollow[sel], amount=random.randint(23,42), randomize=True, interact=True, sleep_delay=(random.randint(90,111)))
         print("~~~~~~~ -",users[sel],"finished following followers at", datetime.datetime.now().strftime("%H:%M:%S")) 
    
    if smartTags[sel]:
        session.like_by_tags(amount=random.randint(3,8), use_smart_hashtags=True, interact=True)
        print("~~~~~~~ -",users[sel],"finished smartTags at",datetime.datetime.now().strftime("%H:%M:%S"))
   

    ######## END SESSION ########

    print("~~~~~~~ -",users[sel]," finished run that started at ",startTime)
    session.end()

if __name__ == '__main__':        
    print("~~~~~~~ -","Starting at",datetime.datetime.now().strftime("%H:%M:%S"))
    jobs = []
    for i in range(len(users)):
        p = multiprocessing.Process(target=worker, args=(i,))
        jobs.append(p)
        p.start()
        time.sleep(66);#no delay cause some instances of chrome to give errors and stop
```

**Comment by mingdc** [comment]
> Error: INFO [2018-03-02 03:45:08] [USERNAME] Session started - 2018-03-02 03:45:08
WARNING [2018-03-02 03:45:08] [USERNAME] Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO [2018-03-02 03:45:40] [USERNAME] Logged in successfully!
Traceback (most recent call last):
File "quickstart.py", line 5, in 
session.login()
File "E:\USER\Desktop\InstaPy-master\instapy\instapy.py", line 271, in login
self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
File "E:\USER\Desktop\InstaPy-master\instapy\print_log_writer.py", line 11, in log_follower_num
"return window._sharedData.""entry_data.ProfilePage[0]."
File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script
'args': converted_args})['value']
File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
self.error_handler.check_response(response)
File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
(Session info: chrome=64.0.3282.186)
(Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 6.1.7601 SP1 x86_64)

I also have a very similar issue, tried to resolve everything I could myself but I can't figure out this :(

**Comment by liamcloss** [comment]
More of the same following login
```
Traceback (most recent call last):
  File "quickstart.py", line 19, in job
    session.login()
  File "/home/control/InstaPy/instapy/instapy.py", line 271, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "/home/control/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/usr/local/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: headless chrome=64.0.3282.186)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.14.17-x86_64-linode99 x86_64)
```

**Comment by liamcloss** [comment]
#1434 
Seemed to fix this, though I also had to comment out session.set_dont_unfollow_active_users() due to an issue with the logfile not being declared.

**Comment by MrBeardedGuy** [comment]
Confirmed. Few days of light testing and https://github.com/timgrossmann/InstaPy/issues/1434 seems to have solved the problem! 

This issue can be closed I guess!
