### ISSUE TITLE
Exception when runing quickstart.py on latest python

### ISSUE THREAD

**Issue by igisho** [InstaPy/InstaPy#1530]
## Current Behavior
Traceback (most recent call last):
  File "./quickstart-fff.py", line 57, in <module>
    amount=20)
  File "/Users/fff/InstaPy/instapy/instapy.py", line 914, in like_by_tags
    self.logfolder)
  File "/Users/fff/InstaPy/instapy/comment_util.py", line 66, in comment_image
    logger.info("--> Commented: {}".format(rand_comment.encode('utf-8')))
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-1: surrogates not allowed
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x10fac2160>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/service.py", line 163, in __del__
  File "/usr/local/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/service.py", line 139, in stop
  File "/usr/local/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down

## InstaPy configuration
Latest InstaPy
Latest python
Latest macosx
Latest chromedriver

**Comment by MrBeardedGuy** [comment]
Are you using any emoji or non utf-8 character in your comments? 
https://github.com/timgrossmann/InstaPy#emoji-support
