### ISSUE TITLE
unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by jnmcfly** [InstaPy/InstaPy#155]
Hey Guys,

after **pip install .** and downloading and exctracting the chromedriver (for win32, took the path in the *.ps1 file) this happen to me:

```
 E:\InstaPy>python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    InstaPy()\
  File "E:\InstaPy\instapy\instapy.py", line 35, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "E:\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "E:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "E:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "E:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "E:\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.10240 x86_64)

```
My chromedriver is located in .\assets\chromedriver

any ideas?

**Comment by GaryYiu** [comment]
Did you remove the hashtag in these two lines of code in InstaPy/instapy/instapy.py ?
#self.display = Display(visible=0, size=(800, 600))
#self.display.start()

**Comment by jnmcfly** [comment]
@GaryYiu nope, everything original, should I?

**Comment by GaryYiu** [comment]
@jnmcfly Yes you have to remove those two hashtags otherwise Chrome cannot start.

**Comment by jnmcfly** [comment]
@GaryYiu Now I got this:

```
E:\InstaPy>python quickstart.py
Traceback (most recent call last):
  File "E:\Python36-32\lib\site-packages\easyprocess\__init__.py", line 225, in start
    env=self.env,
  File "E:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "E:\Python36-32\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python36-32\lib\site-packages\easyprocess\__init__.py", line 178, in check_installed
    self.call()
  File "E:\Python36-32\lib\site-packages\easyprocess\__init__.py", line 194, in call
    self.start().wait(timeout=timeout)
  File "E:\Python36-32\lib\site-packages\easyprocess\__init__.py", line 230, in start
    raise EasyProcessError(self, 'start error')
easyprocess.EasyProcessError: start error <EasyProcess cmd_param=['Xvfb', '-help'] cmd=['Xvfb', '-help'] oserror=[WinError 2] Das System kann die angegebene Datei nicht finden return_code=None stdout="None" stderr="None" timeout_happened=False>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    InstaPy()\
  File "E:\InstaPy\instapy\instapy.py", line 28, in __init__
    self.display = Display(visible=0, size=(800, 600))
  File "E:\Python36-32\lib\site-packages\pyvirtualdisplay\display.py", line 34, in __init__
    self._obj = self.display_class(
  File "E:\Python36-32\lib\site-packages\pyvirtualdisplay\display.py", line 52, in display_class
    cls.check_installed()
  File "E:\Python36-32\lib\site-packages\pyvirtualdisplay\xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "E:\Python36-32\lib\site-packages\easyprocess\__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[WinError 2] Das System kann die angegebene Datei nicht finden
Program install error!
```

**Comment by eduardocalazansjr** [comment]
You have to **COMMENT** the display lines, since you're using windows.
Check if your Chrome installation is fine, if it's not installed on temp or user folder.

Also, you could add `chrome_options.setBinary("/path/to/your/chrome/binary") ` on the instapy.py file.

**Comment by jnmcfly** [comment]
Ha! The binary thing got me! I only worked with a portable version of chrome. Installed the full and everything works! Thank you!
