### ISSUE TITLE
Error installation Raspberry pi

### ISSUE THREAD

**Issue by devmaxime** [InstaPy/InstaPy#1556]
Hello,

I'm running on a Raspberry pi 3 with the standart installation. Nothing fancy.

I have clone and unzip InstaPy and I have copied chromedriver in asset.

When I'm trying to execute the installation command, everything seems to work fine, but at the end I got an exception.

Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 214, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 204, in clobber
    os.makedirs(destdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/selenium'

So if i'm trying to run the quickstart script, that is what I get.

pi@raspberrypi:~/Instapy/InstaPy $ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/home/pi/Instapy/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/home/pi/Instapy/InstaPy/instapy/instapy.py", line 11, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay

What is missing on my installation ? Maybe something about python ?

Thanks a lot for your help.

**Comment by imbarismustafa** [comment]
I used to get the same mistake.
then realised that step 13-15 are optional.
do step 12 and go to the next part for chrome and after that do the finishing up part. 
It worked for me. I recommend you to restart everything fresh.

**Comment by timojaask** [comment]
I've got the same issue, and still can't figure out how to solve it. Also, I can't understand what steps is @imbarismustafa talking about. There are literally three steps in the installation instructions:
1. git clone https://github.com/timgrossmann/InstaPy.git
2. cd InstaPy
3. pip install .

The error comes on the third step. Any ideas?

And I'm running macOS High Sierra.

**Comment by imbarismustafa** [comment]
nope. check out this https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md

git clone https://github.com/timgrossmann/InstaPy.git
cd InstaPy
sudo pip install .
sudo pip install future
sudo apt-get install xvfb
sudo pip install pyvirtualdisplay
sudo reboot (may not be required, but no harm)
