### ISSUE TITLE
Error Followed by shutdown

### ISSUE THREAD

**Issue by boldestfortune** [InstaPy/InstaPy#1565]
Hey guys. Getting some issues I thought I would run by you. I have removed my username & folder info for this post. Essentially it starts out fine, but I noticed the :Error: is new. Once it gets to the first tag, the bot shuts down. Is this based on a new update from instagram? maybe my internet? I'm using the latest set of files from a few days ago.
Thanks.

Using smart hashtags
INFO [2018-03-08 02:07:48] [User]  Tag [1/29]
INFO [2018-03-08 02:07:48] [User]  --> b'andywarhol'
[11196:1360:0308/020749.464:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
WARNING [2018-03-08 02:08:19] []  Load button not found, working with current images!
Traceback (most recent call last):
  File "love3.py", line 25, in <module>
    session.like_by_tags(amount=7, use_smart_hashtags=True, interact=True)
  File "C:\Users\User\Desktop\Instapy\instapy\instapy.py", line 824, in like_by_tags
    skip_top_posts)
  File "C:\Users\User\Desktop\Instapy\instapy\like_util.py", line 212, in get_links_for_tag
    body_elem.send_keys(Keys.HOME)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\webelement.py", line 320, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': keys_to_typing(value)})
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=65.0.3325.146)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x000001A289D01240>>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 163, in __del__
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 139, in stop
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by redeux** [comment]
I'm having the same issue.

**Comment by sionking** [comment]
hi you have old chromedriver and new chrome no match !

**Comment by boldestfortune** [comment]
Thanks @sionking. Figured it out & got it running. Still getting this error though "[10784:12988:0308/205849.844:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED"

Should I be concerned?

**Comment by randysinnott** [comment]
The issue is able to be resolved by updating the version of chromedriver in the assets/ folder to the newest chromedriver from google.

**Comment by GitNees** [comment]
No go for me, updated to latest 2.36 and got Chrome 65, keeps giving that error since today.

**Comment by Tjorriemorrie** [comment]
Paste the new stacktrace

**Comment by randysinnott** [comment]
Make sure you updated the chromedriver in assets/ and not just the one on
your system.  I made that mistake at first as well.

-R

**Comment by RafNadler** [comment]
Hi guys,

I'm having the same issue here. Latest Chromedriver 2.37 in Assets folder, Chrome 65 and exact same error. Any idea how to fix this ?

**Comment by Tjorriemorrie** [comment]
@Rafoo1381 please pull the latest master and paste the whole stacktrace please

**Comment by RafNadler** [comment]
@Tjorriemorrie I did reinstall everything with the latest master, same issue:
The only action I try to run is like_by_feed

I tried follow_user_followers, that works good. set_user_interact gives the same result as the like_by_feed

DevTools listening on ws://127.0.0.1:12263/devtools/browser/63484a6c-0426-42b6-9cd4-447c756f950d
INFO [2018-03-23 18:03:52] [xxx]  Session started - 2018-03-23 18:03:52
WARNING [2018-03-23 18:03:52] [xxxx]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
[12092:14344:0323/180356.558:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
INFO [2018-03-23 18:04:23] [xxx]  Logged in successfully!
[12092:14344:0323/180423.544:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
INFO [2018-03-23 18:04:26] [xxx]  Session ended - 2018-03-23 18:04:26
INFO [2018-03-23 18:04:26] [xxxx]  --------------------

**Comment by Tjorriemorrie** [comment]
That's an error in [chrome](https://chromium.googlesource.com/chromium/chromium/+/HEAD/chrome/browser/extensions/api/web_request/upload_data_presenter.cc). There's nothing instapy can do about it. What version of chrome are you running, and which platform are you on, windows?

**Comment by RafNadler** [comment]
Running Chrome 65 chromedrive 2.37 (tried 2.36 and does the same thing) on Windows 10.

**Comment by 201504242** [comment]
Hi, I have the same issue as @Rafoo1381 , What can I do?
Version 65.0.3325.181 (Official Build) (64-bit)
chromedrive 2.37
Windows 10

**Comment by shauryauppal** [comment]
I am also facing the same issue updating chrome driver didnot help me.
