### ISSUE TITLE
Running setup.py install for Pillow ... error

### ISSUE THREAD

**Issue by colindbx** [InstaPy/InstaPy#1585]
Hi!
So first thing, I am not familiar at all with coding whatsoever, so pardon me if this seems stupid. I've tried the fixes mentionned about Unicode on the forum but I still get this error when running "pip install ." Can someone help ? I need a step by step for dummies :) I'm on Windows 10, using chrome latest version. Thanks!

"Exception:
Traceback (most recent call last):
File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat_init_.py", line 73, in console_to_str
return s.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 5: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
status = self.run(options, args)
File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
prefix=options.prefix_path,
File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
**kwargs
File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
spinner=spinner,
File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils_init_.py", line 676, in call_subprocess
line = console_to_str(proc.stdout.readline())
File "c:\users\pc coline\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat_init_.py", line 75, in console_to_str
return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 5: invalid continuation byte"

**Comment by jdarias3** [comment]
I have the same error. @colindbx, did you fix it?

**Comment by jdarias3** [comment]
I just fixed the problem using the following command:
$ sudo apt-get install python-dev

**Comment by ChrisvanChip** [comment]
> I just fixed the problem using the following command:
> $ sudo apt-get install python-dev

How would you solve it for Windows?
