### ISSUE TITLE
Bug in #interact_user_followers

### ISSUE THREAD

**Issue by max-si-m** [InstaPy/InstaPy#1586]
## Current Behavior

```
Traceback (most recent call last):
  File "cheap_oc.py", line 22, in <module>
    .interact_user_followers(['<some_user>'], amount=900, randomize=True) \
  File "/Users/max-si-m/projects/InstaPy/instapy/instapy.py", line 1322, in interact_user_followers
    self.logger)
  File "/Users/max-si-m/projects/InstaPy/instapy/unfollow_util.py", line 635, in get_given_user_followers
    scroll_bottom(browser, dialog, allfollowing)
  File "/Users/max-si-m/projects/InstaPy/instapy/util.py", line 216, in scroll_bottom
    "arguments[0].scrollTop = arguments[0].scrollHeight", element)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=65.0.3325.146)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.1 x86_64)
```

## InstaPy configuration

```
# coding: utf-8

from instapy import InstaPy

insta_username = 'xxxxxx'
insta_password = 'xxxxxx'

with open('stop_words.txt') as f:
    content = f.readlines()
stop_words = [x.strip() for x in content]

InstaPy(insta_username, insta_password) \
  .login() \
  .set_ignore_if_contains(stop_words) \
  .set_dont_like(stop_words) \
  .set_dont_include(stop_words) \
  .set_upper_follower_count(limit = 1300) \
  .set_user_interact(amount=2, randomize=True, percentage=50, media='Photo') \
  .set_do_comment(enabled=True, percentage=50) \
  .set_do_like(enabled=False, percentage=70) \
  .interact_user_followers(['<some_user>'], amount=900, randomize=True) \
  .end()
```

**Comment by michaloslav** [comment]
same thing here, I started getting this error after running a software update on Ubuntu (I don't know what software got updated or how to reverse it, I just got an update notification and I clicked update; if anyone knows how to reverse a software update, I'd love to know)

**Comment by Tjorriemorrie** [comment]
What is your driver version? 
`chromedriver --version`

**Comment by Tjorriemorrie** [comment]
[Already fixed](https://chromium.googlesource.com/chromium/src/+/45c0029def3706a9b37b9fc5b0e83386749a10c1) 
Update your chromedriver - you are using 2.33 and 2.36 is latest.

**Comment by max-si-m** [comment]
@Tjorriemorrie thanks, It was fixed 🎉
