### ISSUE TITLE
NameError: name 'session' is not defined

### ISSUE THREAD

**Issue by jufelka** [InstaPy/InstaPy#1587]
Hello. I've tried to install InstaPy on Debian but after start got this error:

Traceback (most recent call last):
  File "start.py", line 19, in <module>
    multi_logs=True)
  File "/home/Admin/InstaPy/instapy/instapy.py", line 142, in __init__
    self.set_selenium_local_session()
  File "/home/Admin/InstaPy/instapy/instapy.py", line 230, in set_selenium_local                                                                             _session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriv                                                                             er.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service                                                                             .py", line 86, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service                                                                             .py", line 99, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service ./assets/chromed                                                                             river unexpectedly exited. Status code was: 127

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 34, in <module>
    session.end()
NameError: name 'session' is not defined

**Comment by Tjorriemorrie** [comment]
Make sure you have the correct chromedriver for your system. Otherwise also try with firefox (can set `use_firefox=True` on `Instapy`)

**Comment by jufelka** [comment]
Just made rebuild system and now all is ok

**Comment by jeffreylm** [comment]
Having the same issue, could you explain how the problem was solved?

**Comment by Tjorriemorrie** [comment]
@jeffreylm please paste the stacktrace
