### ISSUE TITLE
UnboundLocalError: local variable 'allfollowing' referenced before assignment

### ISSUE THREAD

**Issue by ignacio87** [InstaPy/InstaPy#1597]
hello guys i start to use instapy 3 weeks ago, at the beginning it looks well, but now it stops after 10 or 15 minutes. i use a mac, i provided with update the chrome driver and erase the cookie but remains the same:
WARNING [ignacio.24fit]  policortez -> Less users to follow than requested.
and
UnboundLocalError: local variable 'allfollowing' referenced before assignment

[quickstart.py.zip](https://github.com/timgrossmann/InstaPy/files/1803063/quickstart.py.zip)

## Current Behavior
INFO [ignacio.24fit]  --> Total people unfollowed : 28 
WARNING [ignacio.24fit]  policortez -> Less users to follow than requested.
ERROR [ignacio.24fit]  follow loop error sample larger than population
WARNING [ignacio.24fit]  gimnasiosevenlife -> Less users to follow than requested.
ERROR [ignacio.24fit]  follow loop error sample larger than population
WARNING [ignacio.24fit]  There are 0 people to follow
ERROR [ignacio.24fit]  following_link error list index out of range
INFO [ignacio.24fit]  Session ended - 2018-03-11 23:20:51
INFO [ignacio.24fit]  --------------------

Traceback (most recent call last):
  File "quickstart.py", line 60, in <module>
    randomize=True)
  File "/Users/marcelacortes/Downloads/InstaPy-master/instapy/instapy.py", line 1409, in follow_user_followers
    self.follow_times)
  File "/Users/marcelacortes/Downloads/InstaPy-master/instapy/unfollow_util.py", line 753, in follow_given_user_followers
    allfollowing,
UnboundLocalError: local variable 'allfollowing' referenced before assignment

# all the lists have more than 2k followers (policortez have 14k)

**Comment by jlntrt** [comment]
Hi there,

with the current version (commit hash ec4cbf2), this error still occurs.
By calling `session.follow_user_following(follower_von_acc_folgen, amount=2, randomize=False)
`, InstaPy breaks with 
```bash
ERROR [2018-04-21 10:59:18] [<project>]  following_link error list index out of range
Traceback (most recent call last):
  File "project.py", line 119, in <module>
    session.follow_user_following(follower_von_acc_folgen, amount=2, randomize=False)
  File "/home/<user>/InstaPy/instapy/instapy.py", line 1553, in follow_user_following
    self.follow_times)
  File "/home/<user>/InstaPy/instapy/unfollow_util.py", line 865, in follow_given_user_following
    allfollowing,
UnboundLocalError: local variable 'allfollowing' referenced before assignment
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7fd387c7f278>>
Traceback (most recent call last):
  File "/home/<user>/InstaPy/instapy/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 163, in __del__
  File "/home/<user>/InstaPy/instapy/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 139, in stop
  File "/home/<user>/InstaPy/instapy/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down
```
Chromium uses version 65.0.3325.181
