### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by brunocechet** [InstaPy/InstaPy#16]
```python3 newunder.py             
Traceback (most recent call last):
  File "newunder.py", line 8, in <module>
    session = InstaPy(username='', password='')
  File "/home/brunocechet/git-projects/InstaPy/instapy/instapy.py", line 33, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error```

I can't figure out :/

**Comment by brunocechet** [comment]
Solved updating assets/chromedriver to the correct version and platform :)
