### ISSUE TITLE
Instagram Changed their webpage API Not able to get `followed_by` anymore 

### ISSUE THREAD

**Issue by CharlesCCC** [InstaPy/InstaPy#1609]
## Expected Behavior
running without issue
## Current Behavior
Crash
## Possible Solution (optional)
need find the place that have this piece of code:
```
browser.execute_script(
            "return window._sharedData.""entry_data.ProfilePage[0]."
            "user.followed_by.count")
```
and change it to
```
browser.execute_script(
            "return window._sharedData.""entry_data.ProfilePage[0]."
            "graphql.user.edge_followed_by.count")
```

and update it accordingly.

**Comment by luigifaticoso** [comment]
Same problem

**Comment by andersjohansenn** [comment]
Same here

**Comment by CharlesCCC** [comment]
PR created https://github.com/timgrossmann/InstaPy/pull/1610/files
@timgrossmann please merge in ASAP.

@luigifaticoso and @andersjohansenn  feel free to manually change those two files on your own if not merged in time.

**Comment by 1337lucas** [comment]
Same here :(

**Comment by Subway19** [comment]
Same issue. It was working two hours ago. Now it throws an error.

![error](https://user-images.githubusercontent.com/14835320/37363213-586812fe-271d-11e8-8d46-789070b0c37c.JPG)

**Comment by martinkuna** [comment]
Same issue raspberry pi using chrome driver

@timgrossmann see PR https://github.com/timgrossmann/InstaPy/pull/1610/files

**Comment by keusta** [comment]
thx @CharlesCCC for the quick fix 👍

**Comment by wemakefuture** [comment]
@CharlesCCC works thank you <3 !

**Comment by balakedev** [comment]
Thanks @CharlesCCC

**Comment by 1337lucas** [comment]
Thank you @CharlesCCC :D <3

**Comment by sionking** [comment]
Thank,
Also need to fix this: ( this is after change)
```
            user_data = json.loads(pre)['graphql']['user'][
        except BaseException as e:
            logger.warning("unable to get user information\n", str(e))

        graphql_endpoint = 'https://www.instagram.com/graphql/query/'
        graphql_followers = (
            graphql_endpoint + '?query_id=17851374694183129')
        graphql_following = (
            graphql_endpoint + '?query_id=17874545323001329')

        all_followers = []
        all_following = []
        unfollow_list = []

        variables = {}
        variables['id'] = user_data'id']
```

**Comment by gi4riv** [comment]
Thanks @CharlesCCC way to go!

**Comment by gomorizsolt** [comment]
thanks @CharlesCCC!

**Comment by furk4no** [comment]
I made the change but the error still comes up?

**Comment by CharlesCCC** [comment]
@furk4no Please provide more detail. This issue has been addressed, I will close this.

**Comment by furk4no** [comment]
This is the error I'm getting:

```
Traceback (most recent call last):
  File "quickstart.py", line 23, in <module>
    session.like_by_tags(['siir'], amount=30)
  File "/home/anonymous/InstaPy/instapy/instapy.py", line 850, in like_by_tags
    self.logger)
  File "/home/anonymous/InstaPy/instapy/like_util.py", line 488, in check_link
    "return window._sharedData.entry_data."
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=65.0.3325.162)
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.13.0-36-generic x86_64)
```
Solved.. the change in likeutils was missing..

**Comment by corncobb** [comment]
@CharlesCCC Works perfectly now, thank you!

**Comment by corncobb** [comment]
Just kidding... now I am receiving issues with "interact_by_users" and many others. Here's the errors...
`Traceback (most recent call last):
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python36-32\InstaPy-master\working bot o copy.py", line 44, in <module>
    session.interact_by_users(usernames, amount=1, randomize=False)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python36-32\InstaPy-master\instapy\instapy.py", line 1182, in interact_by_users
    self.logger)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python36-32\InstaPy-master\instapy\like_util.py", line 488, in check_link
    "return window._sharedData.entry_data."
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 6.1.7601 SP1 x86_64)`
