### ISSUE TITLE
Stopped working all of a sudden.

### ISSUE THREAD

**Issue by wesleytrying** [InstaPy/InstaPy#1611]
I haven't used my InstaPy in a couple days, but when I was using it was working perfectly. It was liking between 270 and 320 photos. However, when I tried starting it up today, it would only log in then close down. It wouldn't give any warning as to why it would stop, just stopped. I have the trace callback of what happened. I am just getting started with this so any help would be appreciated. Here's my traceback. 

## **Traceback**

Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    session.login()
  File "C:\Users\The King\Documents\GitHub\InstaPy\instapy\instapy.py", line 271, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\Users\The King\Documents\GitHub\InstaPy\instapy\print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "C:\Users\The King\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "C:\Users\The King\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\The King\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)

I'm confused as to what this line means "selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined". I can also upload the code itself if that will help.

Thanks for helping!

**Comment by CharlesCCC** [comment]
duplicated, read this before you post new issue. #1609

**Comment by martinkuna** [comment]
@timgrossmann close issue please
