### ISSUE TITLE
Issue regarding the possible update of instagram web

### ISSUE THREAD

**Issue by gabriansa** [InstaPy/InstaPy#1613]
Hello! I've changed the files in the folder instapy in order to make the bot work on the new instagram web. So far its working perfectly, I just got an error that I think can be correlated to this new update. Here it is!

```
Traceback (most recent call last):
  File "quickstart.py", line 31, in <module>
    session.like_by_tags(amount=15, use_smart_hashtags=True)
  File "/Users/gabriele/Desktop/InstaPy1/instapy/instapy.py", line 850, in like_by_tags
    self.logger)
  File "/Users/gabriele/Desktop/InstaPy1/instapy/like_util.py", line 488, in check_link
    "return window._sharedData.entry_data."
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: headless chrome=64.0.3282.186)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.13.2 x86_64)
```

**Comment by GabrieleCalarota** [comment]
Same here but here's the message 

`WARNING:instapy.instapy:Load button not found, working with current images!
...TRACEBACK...
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'`

**Comment by windgan** [comment]
As a hotfix try to change display resolution in _instapy/instapy.py_
```
if nogui:
    self.display = Display(visible=0, size=(800, 600))
    self.display.start()
```
E.x. change it to (1920 x 1080)

Also, download the latest chromedriver (2.36)

**Comment by GabrieleCalarota** [comment]
I'm running nogui = False

**Comment by balakedev** [comment]
Getting very similar error:

`INFO [2018-03-14 08:37:59] [####]  Logged in successfully!
Traceback (most recent call last):
  File "C:\InstaPy-master - ####\InstaPy\ST01.py", line 9, in <module>
    session.login()
  File "C:\InstaPy-master - ####\InstaPy\instapy\instapy.py", line 277, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\InstaPy-master - ####\InstaPy\instapy\print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "C:\Users\####\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 491, in execute_script
    'args': converted_args})['value']
  File "C:\Users\####\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Users\#####\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)
`

**Comment by GabrieleCalarota** [comment]
for that you shoud see 
Duplicate of #1610

**Comment by texmex44** [comment]
@blakemmw Same here since Today (work perfectly normaly) and thanks @GabrieleCalarota for the fix

**Comment by burtongfx** [comment]
I am running InstaPy on a raspberri pi with Firefox. These fixes resolved the issue for me:

https://github.com/timgrossmann/InstaPy/commit/bace3172a9d4fbe6e54217f563622e2fdc46a525

**Comment by GabrieleCalarota** [comment]
I fixed downloading latest chrome driver and deleting all the file named chrome driver in assets

**Comment by burtongfx** [comment]
In my case I am running through Firefox on a raspberry pi. That fix wont apply

**Comment by Klyado** [comment]
Hi, 

I have the same problem here. 
I've deleted all the files in /assets
I ran these commandes to install the latest chrome driver : 

wget "https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip"
unzip chromedriver_linux64
mv chromedriver InstaPy/assets/chromedriver
chmod +x InstaPy/assets/chromedriver
chmod 755 InstaPy/assets/chromedriver
cd InstaPy
pip install .

But problem is still present.
Do you have any ideas ?
