### ISSUE TITLE
Chrome Web Driver SEND KEYS

### ISSUE THREAD

**Issue by GabrieleCalarota** [InstaPy/InstaPy#1614]
I'm getting this issue since the last 2 hours:

Any Guesses?

`2018-03-13 22:49:49 - WARNING - Load button not found, working with current images!
WARNING:instapy.instapy:Load button not found, working with current images!
Traceback (most recent call last):
  File "quickstart.py", line 50, in <module>
    session.like_by_tags(tag_list, amount=50, media='Photo')
  File "E:\Manutenzione_PC_Portable\InstaPy-master\instapy\instapy.py", line 676, in like_by_tags
    skip_top_posts)
  File "E:\Manutenzione_PC_Portable\InstaPy-master\instapy\like_util.py", line 212, in get_links_for_tag
    body_elem.send_keys(Keys.HOME)
  File "C:\Users\Gabriele\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Users\Gabriele\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Gabriele\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Gabriele\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=65.0.3325.162)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)`

**Comment by GabrieleCalarota** [comment]
Updated Chrome driver and deleted chromedriver files in assets worked out
