### ISSUE TITLE
Cannot read property 'followed_by' 

### ISSUE THREAD

**Issue by gi4riv** [InstaPy/InstaPy#1615]
Hello guys. I get this error after some days of working properly activity:

++++
Traceback (most recent call last):
  File "dothejob_02.py", line 18, in <module>
    session.login()

  File "/Users/user/Desktop/InstaPy/instapy/instapy.py", line 271, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)

  File "/Users/user/Desktop/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."

  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 627, in execute_script
    'args': converted_args})['value']

  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)

  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: **Cannot read property 'followed_by' of undefined**

  (Session info: headless chrome=64.0.3282.186)
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.10.5 x86_64)
+++

Any idea? Could be a change in the IG webviewer?
Thanks a bunch!

**Comment by gi4riv** [comment]
Sorry! I saw now the issue #1609

**Comment by CharlesCCC** [comment]
this should have been fixed by PR #1616 
Try manually change your own code before this get merged.

**Comment by benjamin-ollier** [comment]
I have the same

**Comment by thePsguy** [comment]
+1

**Comment by thePsguy** [comment]
@benji0812 @gianpieroriva, doing a `git pull` or re downloading the source will fix the issue.

**Comment by CharlesCCC** [comment]
please follow @thePsguy 's instruciton.
