### ISSUE TITLE
Hi this my Error

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#1622]
Traceback (most recent call last):
  File "start.py", line 11, in <module>
    session.login()
  File "/Users/Retina/Desktop/Instapy/instapy/instapy.py", line 234, in login
    log_follower_num(self.browser, self.username)
  File "/Users/Retina/Desktop/Instapy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.13.3 x86_64)

MacBook-Pro-de-Mac:instapy Retina$

**Comment by windgan** [comment]
Fixed in #1610 
Please, update your local repo from master.

**Comment by johnvfitness** [comment]
thx bro

**Comment by johnvfitness** [comment]
Traceback (most recent call last):
  File "start.py", line 15, in <module>
    session.login()
  File "/Users/Retina/Desktop/InstaPy/instapy/instapy.py", line 277, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "/Users/Retina/Desktop/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: headless chrome=64.0.3282.186)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.13.3 x86_64)

MacBook-Pro-de-Mac:instapy Retina$

**Comment by johnvfitness** [comment]
it's Good thx bro for help ;)

**Comment by CharlesCCC** [comment]
issue fixed by PR #1610 please close this issue @johnvfitness

**Comment by imbarismustafa** [comment]
i am new so i will ask the question. how can i update all files for raspberry pi?
