### ISSUE TITLE
Cannot run instapy on a screen on my Linux Server

### ISSUE THREAD

**Issue by furk4no** [InstaPy/InstaPy#1627]
## Expected Behavior
To run quickstart.py on a linux screen over DigitalOcean.. Ubuntu 16.04.4 LTS 

## Current Behavior
Throws the error:

```
Traceback (most recent call last):
  File "./quickstart.py", line 30, in <module>
    session.end()
NameError: name 'session' is not defined
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7fe67c1abe10>> ignored
```

## InstaPy configuration
It's running if I'm running it normally. On a screen it behaves strange..

**Comment by Tjorriemorrie** [comment]
The chromedriver cannot find the chrome binary.
Fix should be to be able to set chrome binary in Settings and use that if set during selenium init

**Comment by furk4no** [comment]
Uhm, I'm pretty new to Python and Selenium. May you explain it for a dummy please?

**Comment by furk4no** [comment]
I have got a question about running instapy on a DigitalOcean Droplet.. Should I run with the option headless_browser or nogui? I see both everywhere but not really sure which one to use. I'm using nogui right now..

**Comment by furk4no** [comment]
I've got a new error;

```

Traceback (most recent call last):
  File "/root/InstaPy/quickstart.py", line 37, in <module>
    session.end()
NameError: name 'session' is not defined
Exception AttributeError: "'Service' object has no attribute 'process'" in <boun                                                                                         d method Service.__del__ of <selenium.webdriver.chrome.service.Service object at                                                                                          0x7fb796b553d0>> ignored
root@ubuntu-s-1vcpu-1gb-fra1-01:~# python ~/InstaPy/quickstart.py
Traceback (most recent call last):
  File "/root/InstaPy/quickstart.py", line 37, in <module>
    session.end()
NameError: name 'session' is not defined
Exception AttributeError: "'Service' object has no attribute 'process'" in <boun                                                                                         d method Service.__del__ of <selenium.webdriver.chrome.service.Service object at                                                                                          0x7f3411367510>> ignored
```

**Comment by SPQRBrutus** [comment]
@furk4no attach yout quickstart.py

**Comment by furk4no** [comment]
```
from instapy import InstaPy
# -*- coding: UTF-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

insta_username = 'soezlerkrali'
insta_password = 'furk4n123'

# set headless_browser=True if you want to run InstaPy on a server
try:
    # set these if you're locating the library in the /usr/lib/pythonX.X/ directory
    # Settings.database_location = './db/instapy.db'
    # Settings.browser_location = './assets/chromedriver'

    session = InstaPy(username=insta_username,
                      password=insta_password,
                      nogui=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit = 6000)
    session.set_lower_follower_count(limit = 100)
    session.set_do_comment(True, percentage=10)
    session.set_comments([u'Cok guzel! :fire:', u'Dogru!! :fire:', u'Harika! :fire:'])

    # actions
    session.like_by_tags(['siir'], amount=30)
    session.like_by_tags(['ask'], amount=40)
    session.like_by_tags(['bebek'], amount=40)
    session.like_by_tags(['sevgi'], amount=40)
    session.like_by_tags(['kitapsevgisi'], amount=40)
    session.follow_user_followers(['gecesensiir'], amount=120, randomize=False, interact=True, sleep_delay=120)
    session.unfollow_users(amount=10, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 )
finally:
    # end the bot session
    session.end()

```

**Comment by SPQRBrutus** [comment]
Can you please remove your password from this post before someone steals it ?

**Comment by furk4no** [comment]
Oh thank you.. I didn't notice it. Now here it is..
```
from instapy import InstaPy
# -*- coding: UTF-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

insta_username = 'asdasdaasd'
insta_password = 'asdasd'

    # set headless_browser=True if you want to run InstaPy on a server
try:
    # set these if you're locating the library in the /usr/lib/pythonX.X/ directory
    # Settings.database_location = './db/instapy.db'
    # Settings.browser_location = './assets/chromedriver'

    session = InstaPy(username=insta_username,
                      password=insta_password,
                      nogui=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit = 6000)
    session.set_lower_follower_count(limit = 100)
    session.set_do_comment(True, percentage=10)
    session.set_comments([u'Cok guzel! :fire:', u'Dogru!! :fire:', u'Harika! :fire:'])

    # actions
    session.like_by_tags(['siir'], amount=30)
    session.like_by_tags(['ask'], amount=40)
    session.like_by_tags(['bebek'], amount=40)
    session.like_by_tags(['sevgi'], amount=40)
    session.like_by_tags(['kitapsevgisi'], amount=40)
    session.follow_user_followers(['gecesensiir'], amount=120, randomize=False, interact=True, sleep_delay=120)
    session.unfollow_users(amount=10, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 )
finally:
    # end the bot session
    session.end()

```

**Comment by SPQRBrutus** [comment]
Try this:

```python
from instapy import InstaPy
# -*- coding: UTF-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

insta_username = 'asdasdaasd'
insta_password = 'asdasd'

    # set headless_browser=True if you want to run InstaPy on a server
try:
    # set these if you're locating the library in the /usr/lib/pythonX.X/ directory
    # Settings.database_location = './db/instapy.db'
    # Settings.browser_location = './assets/chromedriver'

    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit = 6000)
    session.set_lower_follower_count(limit = 100)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['Cok guzel! :fire:', 'Dogru!! :fire:', 'Harika! :fire:'])

    # actions
    session.like_by_tags(['siir'], amount=30)
    session.like_by_tags(['ask', 'bebek', 'sevgi', 'kitapsevgisi'], amount=40)
    session.follow_user_followers(['gecesensiir'], amount=120, randomize=False, interact=True, sleep_delay=120)
    session.unfollow_users(amount=10, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 )
finally:
    # end the bot session
    session.end()
```

**Comment by furk4no** [comment]
I get this: 

`Traceback (most recent call last):
  File "/root/InstaPy/quickstart.py", line 37, in <module>
    session.end()
NameError: name 'session' is not defined
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7fa17be07450>> ignored
`

I have been getting this error a couple of times but a bit later I was able to run my quickstart again. 
I don't really know why.. Right now the errors start showing up again.

It doesn't really run reliable..

**Comment by furk4no** [comment]
I set up my server like on this link:

[https://medium.com/@mcnamee/using-open-source-software-to-build-your-instagram-followers-205f908cf657](url)

I have the feeling that the usage of **/usr/bin/screen** has something to do with this issue, even if I'm currently trying to run quickstart.py on the **normal console**..

It has been running since a half day every 4 hours.. After I tried to execute my script manually it started to give the error above 

If it doesn't work reliable I'm going to remove my droplet and do everything from scratch....

**Comment by furk4no** [comment]
Change made: I removed the UTF-8 charset lines from instapy.py and quickstart.py. 
Now this error is showing up:

```
root@pypy:~# python3.5 ~/InstaPy/quickstart.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: './assets/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/InstaPy/quickstart.py", line 15, in <module>
    headless_browser=True)
  File "/root/InstaPy/instapy/instapy.py", line 144, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 235, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/InstaPy/quickstart.py", line 34, in <module>
    session.end()
NameError: name 'session' is not defined
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7fea12f97e10>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 163, in __del__
    self.stop()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 135, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'

 
```
**The way I run my instapy:** 

Like on the medium.com tutorial,
I added a **bash script execution** to the **crontab** that executes **quickstart.py with python3.5** in a **screen** every 4 hours. It did work for 3 times until I tried to start quickstart manually..

The reason I use 'python3.5' is that the server has only version 2.7 python and I didn't want to remove it..

**Comment by furk4no** [comment]
I would really appreciate any help for this problem.. 
If someone is running his own linux server (ubuntu prefered) I'd like to know some information:

Python version?
Chrome driver version?
Chromium installed? (why?)
Xvfb installed? (why?)
Using nogui on a server? (why?)
Using headless_browser on a server (why?)
Using the newest version of python? (if no, why not?)

**Comment by furk4no** [comment]
I found the problem.. my script works reliable.. im executing the command `python3.5 ~/InstaPy/quickstart.py` but InstaPy does only start when I execute this in the **InstaPy** folder....

Why the heck???

###I‘m closing this issue.. thanks for trying to help everyone.. 
I’d still appreciate some answers to my questions..
