### ISSUE TITLE
InstaPy session error

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1629]
## Current Behavior
Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.end()
NameError: name 'session' is not defined

## InstaPy configuration
On a DO Droplet
Have chromedriver in /assets
usernames / password set 

Thank you for the assistance

**Comment by furk4no** [comment]
Hello,
I also started using InstaPy on a DO Droplet.
The default python version is 2.7 on the linux servers just install version 3 if you did not.


`sudo apt-get -y install unzip python3-pip python3-dev build-essential libssl-dev libffi-dev xvfb
`

and after that.. do the setup with the newest version you'll get installed (currently python3.5)
`
python3.5 setup.py install`

and also only run your quickstart.py like:

`python3.5 ~/InstaPy/quickstart.py`

I hope this solves the problem..

**Comment by ghost** [comment]
@furk4no - Added the above

Now getting the error:

Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.end()
NameError: name 'session' is not defined
root@booktrib-instapy:/var/www/html/InstaPy# python3.5 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    multi_logs=True)
  File "/var/www/html/InstaPy/instapy/instapy.py", line 144, in __init__
    self.set_selenium_local_session()
  File "/var/www/html/InstaPy/instapy/instapy.py", line 235, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/common/service.py", line 86, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/common/service.py", line 99, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /var/www/html/InstaPy/assets/chromedriver unexpectedly exited. Status code was: 127


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.end()
NameError: name 'session' is not defined

**Comment by furk4no** [comment]
Well try to change your session to
```
 session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=True)
```
are you sure to have the newest version of the chrome browser? (2.36)
**IF not.. it would be better to completely remove the old files you've downloaded etc. before you download the newer version, to be sure it is the right one.**

and have you done all of the steps right here?:
[https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md](url)

**Comment by ghost** [comment]
@furk4no Tried that - I even just restored the entire server to its base LAMP install and used the above guide - but still getting the error.

Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    multi_logs=True)
  File "/var/www/html/InstaPy/instapy/instapy.py", line 145, in __init__
    self.set_selenium_local_session()
  File "/var/www/html/InstaPy/instapy/instapy.py", line 236, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 86, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 99, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service ./assets/chromedriver unexpectedly exited. Status code was: 127


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.end()
NameError: name 'session' is not defined

**Comment by Tjorriemorrie** [comment]
Do you mind trying `pip install -U selenium` and see if that works.

**Comment by ghost** [comment]
@Tjorriemorrie yes - Requirement already up-to-date: selenium in /usr/local/lib/python3.5/dist-packages

**Comment by Tjorriemorrie** [comment]
Do you mind trying [this update](https://github.com/timgrossmann/InstaPy/issues/1245#issuecomment-358872721)

**Comment by furk4no** [comment]
I had this error again yesterday after I applied the changes with Python 3.5 as I told you.
It's still giving an error sometimes, but I could run my python script multiple times on crontab since it started working again. 
Now I tried installing the chromium-browser as **Tjorriemorrie** recommended.. 

Hope this is a permanent fix.

**Comment by bendwebs** [comment]
@furk4no - had even tried to remove then re-install selenium - going to hire someone to install - I'll post any fixes found for this issue once its installed.

**Comment by ghost** [comment]
Thank you for your help @furk4no and @Tjorriemorrie 

I uninstalled selenium and then re-installed then looked at the chromedriver wanting to verify its permissions and file name.

I removed it (the chromedriver) via SFTP, redownloading it, and then re-uploaded. 

Then ran:

$ python3.5 quickstart.py 

and it started to work

-Closing this issue
