### ISSUE TITLE
Please help !

### ISSUE THREAD

**Issue by granddaddysmoke** [InstaPy/InstaPy#1633]
WARNING [2018-03-15 05:07:19] [user]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO [2018-03-15 05:07:24] [user]  Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 9, in <module>
    session.login()
  File "C:\Users\user\Desktop\InstaPy-master\instapy\instapy.py", line 271, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\Users\user\Desktop\InstaPy-master\instapy\print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x0568F990>>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 163, in __del__
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 139, in stop
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by alessiomatt1** [comment]
I have just post the same  #1634 , if I have to delete it tell me

**Comment by alessiomtt** [comment]
#1565 

EDIT:
Same error, not working for me

**Comment by alessiomtt** [comment]
Please @granddaddysmoke change the title in:
**"ImportError: sys.meta_path is None, Python is likely shutting down"**

**Comment by Tjorriemorrie** [comment]
That should be fixed, did you pull the latest master?
