### ISSUE TITLE
ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by alessiomtt** [InstaPy/InstaPy#1634]
INFO [xxxxxx]  Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    session.login()
  File "C:\Users\INSTAGRAM NONTOCCARE\Desktop\InstaPy-master\instapy\instapy.py", line 271, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\Users\INSTAGRAM NONTOCCARE\Desktop\InstaPy-master\instapy\print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "C:\Users\INSTAGRAM NONTOCCARE\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "C:\Users\INSTAGRAM NONTOCCARE\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\INSTAGRAM NONTOCCARE\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: headless chrome=64.0.3282.186)
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.16299 x86_64)

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x0662AF90>>
Traceback (most recent call last):
  File "C:\Users\INSTAGRAM NONTOCCARE\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 163, in __del__
  File "C:\Users\INSTAGRAM NONTOCCARE\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 139, in stop
  File "C:\Users\INSTAGRAM NONTOCCARE\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down

Really don't know what to do...

**Comment by Tjorriemorrie** [comment]
That has been fixed, pull the latest from master.
