### ISSUE TITLE
Hi this my error

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#1640]
Traceback (most recent call last):
  File "start.py", line 47, in <module>
    session.like_by_tags(['musculation','teamshape','getfit','fit','fitnessmodel','fitspo','crossfit','muscu','shooting','fitfrenchies'], amount=10)
  File "/Users/Retina/Desktop/InstaPy/instapy/instapy.py", line 850, in like_by_tags
    self.logger)
  File "/Users/Retina/Desktop/InstaPy/instapy/like_util.py", line 538, in check_link
    'Inappropriate! ~ contains \'{}\' in \'{}\''.format(iffy, quashed))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 13: ordinal not in range(128)

**Comment by Tjorriemorrie** [comment]
Yeah that should be encoded.

**Comment by johnvfitness** [comment]
Traceback (most recent call last):
  File "start.py", line 43, in <module>
    session.like_by_tags(['musculation','teamshape','getfit','strong','ifbb','fitspo','crossfit','instagood','lille','training'], amount=10)
  File "/Users/Retina/Desktop/InstaPy/instapy/instapy.py", line 850, in like_by_tags
    self.logger)
  File "/Users/Retina/Desktop/InstaPy/instapy/like_util.py", line 421, in check_link
    "return window._sharedData.entry_data.PostPage")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: chrome=65.0.3325.162)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.13.3 x86_64)

MacBook-Pro-de-Mac:instapy Retina$

**Comment by johnvfitness** [comment]
thx bro :)
