### ISSUE TITLE
Session ended

### ISSUE THREAD

**Issue by jufelka** [InstaPy/InstaPy#1643]
From yesterday the script doesn't work. Here is log file:

INFO [...]  Session started - 2018-03-15 15:00:03
INFO [...]  Logged in successfully!
INFO [...]  Session ended - 2018-03-15 15:00:13
INFO [...]  --------------------

INFO [...]  Session started - 2018-03-15 18:00:03
INFO [...]  Logged in successfully!
INFO [...]  Session ended - 2018-03-15 18:00:06
INFO [...]  --------------------

**Comment by CharlesCCC** [comment]
Please provide more details.

**Comment by dperconti** [comment]
I'm seeing this too, followed by this error:

```Traceback (most recent call last):
  File "quickstart.py", line 26, in <module>
    session.like_by_tags(['natgeo'], amount=1)
  File "/Users/donato/Documents/dev/personal/instagram/InstaPy/instapy/instapy.py", line 831, in like_by_tags
    skip_top_posts)
  File "/Documents/dev//instagram/InstaPy/instapy/like_util.py", line 200, in get_links_for_tag
    body_elem.send_keys(Keys.END)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 349, in send_keys
    'value': keys_to_typing(value)})
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=65.0.3325.162)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.2 x86_64)```

**Comment by CharlesCCC** [comment]
please check this #1365

**Comment by julesbou** [comment]
Since a few days, the script runs for exactly one day (24 hours), and then in the console I see:

```
Session ended - 2018-03-29 17:57:07
```

The script is still running, but no more liking, following, etc

It just seems that Instagram has ended my session.

Is there a way to reinitialize Instagram's session, why not try a fresh login for example?

**Comment by jufelka** [comment]
Just try to update script

**Comment by julesbou** [comment]
Apparently I found out it was because all the liking/following was done. So InstaPy just ended the session.

**Comment by Robcis** [comment]
@julesbou how do you make it so that the liking/following is never done?
