### ISSUE TITLE
get_given_user_followers return error

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#1645]
I am getting this error when trying this specific user "Bxxar_xxxcial".
```
Traceback (most recent call last):
  File ".../scheduleInstaPy.py", line 71, in job
    amountUserFollowers=5, randomize=True)
  File "...xxx\instapy\instapy.py", line 1798, in iblabla
    self.logger)
  File "...xxx\instapy\unfollow_util.py", line 739, in get_given_user_followers
    click_element(browser, following_link[0]) # following_link.send_keys("\n")
IndexError: list index out of range
```

Will investigate!
SCK

**Comment by sionking** [comment]
Hi the issue is since the name is not lower case.
Should we catch this or cast to lower ?
