### ISSUE TITLE
unable to start the session

### ISSUE THREAD

**Issue by Moein-9** [InstaPy/InstaPy#1646]
Hi Friends, i am having this issue at the moment, will appreciate any help that anyone can give me.  If you guys need more info, please ask and i will share it

Thank you. 

## Current Behavior
```
WARNING [2018-03-15 12:55:35] [charmoptical]  Load button not found, working with current images!
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    session.like_by_tags(['yeg'], amount=50)
  File "C:\Users\Moein_tablet\Documents\GitHub\InstaPy\instapy\instapy.py", line 831, in like_by_tags
    skip_top_posts)
  File "C:\Users\Moein_tablet\Documents\GitHub\InstaPy\instapy\like_util.py", line 212, in get_links_for_tag
    body_elem.send_keys(Keys.HOME)
  File "C:\Users\Moein_tablet\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Users\Moein_tablet\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Moein_tablet\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Moein_tablet\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=65.0.3325.162)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)
```

## InstaPy configuration

```
from instapy import InstaPy

session = InstaPy(username='', password='')

session.login()

session.like_by_tags(['yeg'], amount=50, media=None)

session.end()

```

**Comment by dperconti** [comment]
I'm having the same issue as well:

```
 File "quickstart.py", line 26, in <module>
    session.like_by_tags(['natgeo'], amount=1)
  File "/Users/donato/Documents/dev/personal/instagram/InstaPy/instapy/instapy.py", line 831, in like_by_tags
    skip_top_posts)
  File "/Documents/dev//instagram/InstaPy/instapy/like_util.py", line 200, in get_links_for_tag
    body_elem.send_keys(Keys.END)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 349, in send_keys
    'value': keys_to_typing(value)})
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=65.0.3325.162)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.2 x86_64)```
```

**Comment by Moein-9** [comment]
Can someone please help, any guidance would be highly appreciated! 

Thank you!

**Comment by Moein-9** [comment]
I think I fixed it if anyone is wondering how i did it. 

I did a fresh download for instapy, and next step was I tested it with quickstart, it worked, but I had the common problem that everyone is having, "the 27 likes only"  after that I referred myself to  [1365](https://github.com/timgrossmann/InstaPy/issues/1365#issuecomment-366526517)  lookup for uluQulu comments ( if you are reading this, thank you for all your help! ) 

If you are lazy, i have attached my instapy code and like_utill code as well. 

attached are my code for [ like_utill ](https://gist.github.com/Moein-9/e1f98fdec4c38c23878e9d8f8aaffdd4)

and [instapy](https://gist.github.com/Moein-9/e1f98fdec4c38c23878e9d8f8aaffdd4)

I take no responsibility if it didn't work out for you, but I thought to share what worked for me.

**Comment by pigipi** [comment]
I have also the same problem since 2 weeks, and I didn't find a way to fix it. If anyone has a solution (even after a git pull), please share it to us...

**Comment by Tjorriemorrie** [comment]
You can update your chromedriver.

**Comment by pigipi** [comment]
ooh thank you, I didn't try this option. I'll try this.

**Comment by pigipi** [comment]
Alright, we must update the chromedriver. If it can help, how to update it, I copy/paste the sentence from Instapy tutorial:

_Download chromedriver for your system from [here](https://sites.google.com/a/chromium.org/chromedriver/downloads). Extract the .zip file and put it in /assets folder._

Many thanks Tjorriemorrie for the suggestion!
