### ISSUE TITLE
Webdriver issue ?

### ISSUE THREAD

**Issue by Croneee** [InstaPy/InstaPy#1647]
Hi!
When i start Instapy, after a login successfull I get this error message:

macbookBmo:InstaPy BMOPRO$ python3 quickstart.py
Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 9, in <module>
    session.login()
  File "/Users/BMOPRO/InstaPy/instapy/instapy.py", line 202, in login
    log_follower_num(self.browser, self.username)
  File "/Users/BMOPRO/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/Applications/anaconda3/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Applications/anaconda3/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Applications/anaconda3/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.12.6 x86_64)

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x103500588>>
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/service.py", line 163, in __del__
  File "/Applications/anaconda3/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/service.py", line 139, in stop
  File "/Applications/anaconda3/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down

I just download, unzip and put in the asset folder the chromedrivers v2.36.
Before i had the v2.34 but nothing change..

I run Instapy on a Macbook pro 
with python3.6 
and i use chrome

Thanks for helping !!!

**Comment by FranklinClinton** [comment]
Got the same problem. Looks like instagram changed something. A few days ago it was working fine.

**Comment by alessiomtt** [comment]
Same error

**Comment by DemOnJR** [comment]
The same error for me!!

**Comment by corncobb** [comment]
Same

**Comment by asoomar** [comment]
Yeah I ended up getting the same thing! It's really frustrating. Anyone know what could be the issue?

**Comment by corncobb** [comment]
@asoomar I just fixed the issue. It works completely fine now. Uninstall Instapy and download the new one and install it and get the latest version of chrome driver and put it in the assets folder.

**Comment by Croneee** [comment]
@corncobb ok thank, i'll try imediatly

**Comment by corncobb** [comment]
@Croneee let me know how it goes

**Comment by asoomar** [comment]
@corncobb I got passed that, but now when trying to comment on the most recent photo for each username, it works for a couple, then I get the following error. The bot comments on about 2-3 usernames I have selected, but just turns off after, and I get this error for some reason

`Traceback (most recent call last):
  File "quickstart.py", line 76, in <module>
    session.interact_by_users(Usernames, amount=1, randomize=False, media='Photo')
  File "/Users/alisoomar/InstaPy-master/instapy/instapy.py", line 1267, in interact_by_users
    self.logfolder)
  File "/Users/alisoomar/InstaPy-master/instapy/comment_util.py", line 50, in comment_image
    "arguments[0].value = '" + rand_comment + " ';", comment_input[0])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: Unexpected identifier
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.13.4 x86_64)`

**Comment by Croneee** [comment]
@corncobb It work fine for me ! Thx.
I had an old version of quickstart.py with some keyword doesn't work like "random" now it's "randomize" etc...

**Comment by bichig** [comment]
@corncobb Do you have any tutorials to do it? I know it's basic but for beginners like me I can find it complicated. Thank you very much for your help!

**Comment by asoomar** [comment]
I ended up finding the issue and fixing it myself! In comment_util.py, under comment_image,
`"arguments[0].value = '" + rand_comment + " ';", comment_input[0])`
needed to be changed to 
`'arguments[0].value = "' + rand_comment + ' ";', comment_input[0])`

This is because if you edit your comments to have ' (apostrophe), for some reason it would give the error I described in my previous comment, but now it works fine.

**Comment by corncobb** [comment]
@bichig A tutorial to install instapy? If that's what you are asking then I do not have a tutorial but I can make a YouTube video that can show you how.

**Comment by corncobb** [comment]
@asoomar Interesting... Glad you figured it out!

**Comment by Croneee** [comment]
@bichig For instalation move your instapy folder to trash and follow the steps at https://github.com/timgrossmann/InstaPy#basic-installation

**Comment by corncobb** [comment]
@bichig I do not have a tutorial but I can make one! Can you give me until tomorrow night and I can have a full video showing you how to get it installed and working?

**Comment by bichig** [comment]
@Croneee  I just have to delete the InstaPy folder from my computer and replace it with the new one? If so, I can do it ... I am a basic user but not so much hahaha


@corncobb  If you can do a tutorial it is always welcome!

Thanks to all for the help!

**Comment by corncobb** [comment]
@bichig It's more complicated than just replacing the folder. You have to go into pip and install it and download the chrome driver and put it in the assets folder and if you want to run code with instapy it has to be in the instapy folder. Lol it can be irritating. Just curious... what is your operating system and do you have Selenium installed for python?

**Comment by bichig** [comment]
@corncobb I have it running for 5 months, and I have it run through PyCharm Community Edition 2017.
To make it work I open the Chromedriver, then the PyCharm and there I go to the Quickstart.py folder and I give it to the "Run Quickstart".


That's how it always worked for me!

**Comment by corncobb** [comment]
@bichig Interesting... I've never used PyCharm. Unfortunately I cannot help you in that sense... The video that I will make will show you how I learned and maybe it will provide insight to how you can get it to work with PyCharm.

**Comment by bichig** [comment]
Thank you very much, I will talk to my friend who helped me install it in PyCharm and if I can solve it I will share the answer!

Also, thank you very much for your time! @corncobb

**Comment by corncobb** [comment]
@bichig You are very welcome :) I will have a video up tomorrow for you and for those who want to know how to install Instapy :)

**Comment by bichig** [comment]
I installed the new version and the problems continue, so I went back to the previous version.

with the PyCharm it is very simple, only the folder is replaced.
Now I have to see how I solve the problem!

Logged in successfully!
Traceback (most recent call last):
  File "C:/Users/Gustavo/Desktop/InstaPy/InstaPy/quickstart.py", line 9, in <module>
    session.login()
  File "C:\Users\Gustavo\Desktop\InstaPy\InstaPy\instapy\instapy.py", line 193, in login
    log_follower_num(self.browser, self.username)
  File "C:\Users\Gustavo\Desktop\InstaPy\InstaPy\instapy\print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "C:\Users\Gustavo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Gustavo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Gustavo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=65.0.3325.162)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.16299 x86_64)

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x04E9E870>>
Traceback (most recent call last):
  File "C:\Users\Gustavo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 163, in __del__
  File "C:\Users\Gustavo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 139, in stop
  File "C:\Users\Gustavo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down

Process finished with exit code 1

**Comment by FranklinClinton** [comment]
Remove instapy directory, download the newest files from github and execute it. If it only likes 27 Pictures, then use https://github.com/timgrossmann/InstaPy/issues/1365#issuecomment-366526517. Worked for me.

**Comment by sandes** [comment]
Yes..
There is a problem with the 2.36
I did not have any problem with Google chrome 62 and chromedriver 2.34

 [chrome 62]( https://www.slimjet.com/chrome/download-chrome.php?file=lnx%2Fchrome64_62.0.3202.75.deb)

**Comment by corncobb** [comment]
@bichig I made the tutorial video here on how to fully install Instapy in case you still wanted to see it: https://youtu.be/bwAiuBtXxTU

**Comment by bichig** [comment]
Thanks for the tutorial, but I installed the new version and did not manage to make it work, moreover, not even log in with the new version.

I went back to the old version and still with the same mistake ... I do not know what to do anymore!
