### ISSUE TITLE
(Multiprocess) interact_user_followers crash (StaleElementReferenceException)

### ISSUE THREAD

**Issue by texmex44** [InstaPy/InstaPy#1651]
I have this error on "interact_user_followers" :
```bash
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "quickstart.py", line 38, in worker
    session.interact_user_followers(instaMentors[selection][random.randint(0, len(instaMentors[selection]) -1 )], amount=40, randomize=True)
  File "/home/pi/bot/InstaPy/instapy/instapy.py", line 1359, in interact_user_followers
    self.user_interact_media)
  File "/home/pi/bot/InstaPy/instapy/instapy.py", line 1004, in like_by_users
    media)
  File "/home/pi/bot/InstaPy/instapy/like_util.py", line 394, in get_links_for_username
    if link_elem.text in media]
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 68, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.33 (undefined),platform=Linux 4.9.59-v7+ armv7l)

```

Here is my multi process script :

```python
# !/usr/bin/env python
# -*- coding: utf-8 -*-
import random
from instapy import InstaPy, Settings
import os
import multiprocessing
import datetime
import time
import sys

instaUser = ['user1', 'user2']
instaPass = ['pass1', 'pass2']
instaMentors = [['user1Friend1', 'user1Friend2'],['user2Friend1', 'user2Friend2']]
instaComments = [[u':heart:', u':heart::heart:', u':heart::heart::heart:', u'Nice :+1:', u':+1:', u':ok_hand:',
                  u':+1::ok_hand:', u':star::star::star:', u':clap::clap:'],
                 [u':heart:', u':heart::heart:', u':heart::heart::heart:', u'Super :+1:', u':+1:', u':ok_hand:',
                  u':+1::ok_hand:', u':star::star::star:', u':clap::clap:']]


def worker(selection):
    print("MULTI - Started as", instaUser[selection], "at", datetime.datetime.now().strftime("%H:%M:%S"))
    Settings.browser_location = './assets/chromedriver'
    session = InstaPy(username=instaUser[selection], password=instaPass[selection], headless_browser=False,
                      multi_logs=True)
    session.login()

    session.set_user_interact(amount=5, randomize=True, percentage=100, media='Photo')
    session.set_comments(instaComments[selection])
    session.set_upper_follower_count(limit=500)
    session.set_dont_include(instaMentors[selection])
    session.set_do_comment(True, percentage=50)
    session.set_do_like(True, percentage=70)
    session.set_do_follow(True, percentage=100)

    if len(sys.argv) > 1:
        print(
        "MULTI -", instaUser[selection], "started unfollowing at", datetime.datetime.now().strftime("%H:%M:%S"))
        session.unfollow_users(amount=420, onlyInstapyFollowed=True, onlyInstapyMethod='FIFO',
                               onlyNotFollowMe=True, sleep_delay=(random.randint(44, 111)))
        print("MULTI -", instaUser[selection], "finished unfollowing at",
              datetime.datetime.now().strftime("%H:%M:%S"))

    if instaMentors[selection] and len(sys.argv) == 1:
        print(
        "MULTI -", instaUser[selection], "started following at", datetime.datetime.now().strftime("%H:%M:%S"))
        session.interact_user_followers(
            instaMentors[selection][random.randint(0, len(instaMentors[selection]) - 1)], amount=40,
            randomize=True)
        print("MULTI -", instaUser[selection], "finished following followers at",
              datetime.datetime.now().strftime("%H:%M:%S"))

    session.end()
    print("MULTI -", instaUser[selection], "finished run at", datetime.datetime.now().strftime("%H:%M:%S"))


if __name__ == '__main__':
    print("MULTI -", "Starting at", datetime.datetime.now().strftime("%H:%M:%S"))
    jobs = []
    for i in range(len(instaUser)):
        p = multiprocessing.Process(target=worker, args=(i,))
        jobs.append(p)
        p.start()
        # p.join()
        time.sleep(66);  # no delay cause some instances of chrome to give errors and stop
```

I think it's multiprocess / interact_user_followers bug because when i process one account by one (by adding "p.join()") it's work without any problem.

This script run on Raspberry pi 3.

**Comment by imbarismustafa** [comment]
Hello. I think i have similar problem but i coundnt understand what was the real issue and how we can get it fixed.

My error looks very similar to yours and I am using raspberry pi 3 too.

`File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 68, in text
return self._execute(Command.GET_ELEMENT_TEXT)['value']
File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
return self._parent.execute(command, params)
File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
self.error_handler.check_response(response)
File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
(Session info: chrome=63.0.3239.84)
(Driver info: chromedriver=2.33 (undefined),platform=Linux 4.14.34-v7+ armv7l)`

As far as i could understand you managed to solve the issue? If possible can you explain. Thank you.

**Comment by mrrobotsca** [comment]
Me too I got this issue today
