### ISSUE TITLE
AttributeError: 'Service' object has no attribute 'process'

### ISSUE THREAD

**Issue by sallarrabiei** [InstaPy/InstaPy#1653]
I faced with this result; would you please help me on this issue.  

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './assets/chromedriver': './assets/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    multi_logs=True)
  File "/Users/mohammadrabiei/InstaPy/instapy/instapy.py", line 145, in __init__
    self.set_selenium_local_session()
  File "/Users/mohammadrabiei/InstaPy/instapy/instapy.py", line 236, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.end()
NameError: name 'session' is not defined
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x11269bc50>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/service.py", line 163, in __del__
    self.stop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/service.py", line 135, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'

**Comment by furk4no** [comment]
do `cd InstaPy` before you do `python ~/InstaPy/quickstart.py`

**Comment by sallarrabiei** [comment]
Thank you Furk4no, Again I faced the same error.

**Comment by MrJamsn** [comment]
Hi all,

i am facing a similar error:

`pi@raspberrypi:~/instabot/InstaPy_chrome $ python3 quickstart.py Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/pi/instabot/InstaPy_chrome/instapy/instapy.py", line 190, in __init__
    self.set_selenium_local_session()
  File "/home/pi/instabot/InstaPy_chrome/instapy/instapy.py", line 297, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 61, in __init__
    self.service.start()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 62, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x752fcef0>> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 151, in __del__
    self.stop()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 123, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'
`


Generally I am a bit confused as in the Readme is written, that chrome only works in 64bit mode. My Raspbi3B+ is 64 bit, but there is no Rasbian 64 bit image, so my systems runs on 32 bit. But it seems that people are using raspberry for it.
With Firefox it runs, but i want to run it headless which is not possible with Firefox so far.

Please help me :)

**Comment by MrJamsn** [comment]
finally made it!!
i reversed the tutorial https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md
`sudo apt-get remove PACKAGE` `sudo apt autoremove`

When everything was clear, including chromium, wolfram (wolfram-engine) and libreoffcie(libreoffice*), i follwed the last point of the tutorial:

Installation with raspbian stretch lite (v4.14)
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install chromium-browser python-pip git
git clone https://github.com/timgrossmann/InstaPy.git instapy
in the instapy folder: pip install .
in the assets folder: wget https://github.com/electron/electron/releases/download/v3.0.0-beta.5/chromedriver-v3.0.0-beta.5-linux-armv7l.zip
also in the assets folder: unzip chromedriver-v3.0.0-beta.5-linux-armv7l.zip
🎉

AND IT WORKS!! Thanks Tim for your grat work
