### ISSUE TITLE
Unknown error: Cannot re ad property 'followed_by' of undefined

### ISSUE THREAD

**Issue by Abedessamad** [InstaPy/InstaPy#1660]
It was working very well until two days now... it stop in the profile account give this message:

**DevTools listening on ws://127.0.0.1:12010/devtools/browser/10f534b3-88c0-4c9e-8
104-43e65f79af97
[4312:916:0316/135426.950:ERROR:mf_helpers.cc(14)] Error in dxva_video_decode_ac
celerator_win.cc on line 542**
[**1960:1968:0316/135441.180:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
Traceback (most recent call last):
  File "C:\Users\Abedessamad\Desktop\Desktop\InstaPy-master\quickstartF.py", lin
e 9, in <module>**
    **session.login()
  File "C:\Users\Abedessamad\Desktop\Desktop\InstaPy-master\instapy\instapy.py",
 line 202, in login
    log_follower_num(self.browser, self.username)
  File "C:\Users\Abedessamad\Desktop\Desktop\InstaPy-master\instapy\print_log_wr
iter.py", line 11, in log_follower_num**
    **"return window._sharedData.""entry_data.ProfilePage[0]."
  File "C:\Users\Abedessamad\AppData\Local\Programs\Python\Python36-32\lib\site-
packages\selenium\webdriver\remote\webdriver.py", line 627, in execute**_**script
    'args': converted_args})['value']**
  **File "C:\Users\Abedessamad\AppData\Local\Programs\Python\Python36-32\lib\site-
packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Abedessamad\AppData\Local\Programs\Python\Python36-32\lib\site-
packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response**

    **raise exception_class(message, screen, stacktrace)**
**selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot re
ad property 'followed_by' of undefined**
  **(Session info: chrome=65.0.3325.162)**
  **(Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e
73),platform=Windows NT 6.3.9600 x86_64)**

**Comment by tanmald** [comment]
I'm also getting a similar one.

Traceback (most recent call last):
  File "likebytags2.py", line 24, in <module>
    session.like_by_tags(['tags'], amount=3, interact=True)
  File "/Users/xxx/InstaPy/instapy/instapy.py", line 879, in like_by_tags
    self.user_interact_media)
  File "/Users/xxx/InstaPy/instapy/instapy.py", line 1049, in like_by_users
    self.logger)
  File "/Users/xxx/InstaPy/instapy/like_util.py", line 421, in check_link
    "return window._sharedData.entry_data.PostPage")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
**selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined**
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.13.2 x86_64)

**Comment by FranklinClinton** [comment]
Remove instapy directory, download the newest files from github and execute it. If it only likes 27 Pictures, then use https://github.com/timgrossmann/InstaPy/issues/1365#issuecomment-366526517. Worked for me.
