### ISSUE TITLE
Chrome webdriver error

### ISSUE THREAD

**Issue by DemOnJR** [InstaPy/InstaPy#1665]
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
  File "/root/InstaPy/instapy/instapy.py", line 145, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 236, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: session not created exception
from tab crashed
  (Session info: headless chrome=65.0.3325.162)
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 2.6.32-042stab125.5 x86_64)

**Comment by DemOnJR** [comment]
SOLVED
