### ISSUE TITLE
[SOLVED] Chrome webdriver error (ubuntu 14.04 server 64 bit)

### ISSUE THREAD

**Issue by DemOnJR** [InstaPy/InstaPy#1667]
root@host2:~/InstaPy# python3.5 test.py
INFO [2018-03-17 02:29:49] [test]  Session started - 2018-03-17 02:29:49
INFO [2018-03-17 02:30:21] [test]  Logged in successfully!
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    session.unfollow_users(amount=800, onlyNotFollowMe=False, sleep_delay=300)
  File "/root/InstaPy/instapy/instapy.py", line 1527, in unfollow_users
    self.logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 340, in unfollow
    if person and hasattr(person, 'text') and person.text:
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 68, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=65.0.3325.162)
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 2.6.32-042stab125.5 x86_64)

**Comment by sionking** [comment]
Happens now and then.
Need to merge the PR that restart the chrome and webdriver on crashes.

**Comment by DemOnJR** [comment]
@sionking solved.
## **_Ubuntu server 14.04 64bit_**
## **_python 3.4 ( 3.5 / 2.7 get crash chromedriver ) and pip3_**
`apt-get update`
`apt-get -y install unzip python3-pip python3-dev build-essential libssl-dev libffi-dev xvfb`
`pip3 install --upgrade pip`

`cd ~`
`wget "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"`
`sudo dpkg -i google-chrome-stable_current_amd64.deb`
`sudo apt-get install -y -f`
`sudo rm google-chrome-stable_current_amd64.deb`

`git clone https://github.com/timgrossmann/InstaPy.git`

## **_chromedriver 2.37_**
`wget "https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip"`
`unzip chromedriver_linux64`
`mv chromedriver InstaPy/assets/chromedriver`
`chmod +x InstaPy/assets/chromedriver`
`chmod 755 InstaPy/assets/chromedriver`

`cd InstaPy`

`pip install .`
`pip3 install .`
`pip3 install --upgrade pip`

## **_Start the script with:_**
`python3 yourfile.py`

**Comment by DemOnJR** [comment]
@

**Comment by sionking** [comment]
So is it python version to blame ?
I am working on windows with 3.6.3 should I switch to 3.4 ?

**Comment by DemOnJR** [comment]
for me yes.

**Comment by arminorlik** [comment]
@DemOnJR do you have any advice how to install python3.4 instead 3.5 or 2.7 (both are actually installed on my ubuntu 16.04)?

**Comment by DemOnJR** [comment]
sudo apt-get update
sudo apt-get install python3.4

**Comment by imbarismustafa** [comment]
how can i solve this issue for raspberry pi 3?

**Comment by DemOnJR** [comment]
what is it "raspberry" ?

**Comment by imbarismustafa** [comment]
yeah its raspberry pi 3 running raspberrian os. @DemOnJR

**Comment by DemOnJR** [comment]
I did not use that system I do not know sorry

**Comment by wizarduk** [comment]
still doesnt work this bot is usless now

**Comment by DemOnJR** [comment]
@wizarduk the bot is working! :)

**Comment by jakeseaton** [comment]
I just power cycled my droplet and it works again
