### ISSUE TITLE
Error when i run the gui

### ISSUE THREAD

**Issue by nodope7** [InstaPy/InstaPy#1677]
Error: INFO [2018-03-18 03:58:10] [nodope7] Session started - 2018-03-18 03:58:10
 WARNING [2018-03-18 03:58:10] [nodope7] Sorry, Record Activity is not working on Windows. We're working to fix this soon!
 INFO [2018-03-18 03:58:55] [nodope7] Logged in successfully!
 Traceback (most recent call last):
 File "quickstart.py", line 5, in <module>
 session.login()
 File "C:\Users\Dell\Downloads\InstaPy-master\InstaPy-master\instapy\instapy.py", line 277, in login
 self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
 File "C:\Users\Dell\Downloads\InstaPy-master\InstaPy-master\instapy\print_log_writer.py", line 11, in log_follower_num
 "return window._sharedData.""entry_data.ProfilePage[0]."
 File "C:\Users\Dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script
 'args': converted_args})['value']
 File "C:\Users\Dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
 self.error_handler.check_response(response)
 File "C:\Users\Dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
 (Session info: chrome=64.0.3282.186)
 (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.10586 x86_64)

**Comment by tadejs** [comment]
Same here, this has been happening for a few days now, and not just when running the GUI. I guess they changed their attribute names again.

**Comment by tadejs** [comment]
Also, seems the same thing as #1647

**Comment by Tjorriemorrie** [comment]
Can you try again by pulling latest master please

**Comment by tadejs** [comment]
Ah yes, I see it's been fixed recently. Works for me.
