### ISSUE TITLE
Do not working on Windows 10

### ISSUE THREAD

**Issue by BoneS38** [InstaPy/InstaPy#1687]
## Expected Behavior
Start working 
## Current Behavior
Give an error message
## Possible Solution (optional)

Cookie file not found, creating cookie...

Error: INFO [2018-03-19 16:29:02] [williansalceda] Session started - 2018-03-19 16:29:02
 WARNING [2018-03-19 16:29:02] [williansalceda] Sorry, Record Activity is not working on Windows. We're working to fix this soon!
 Traceback (most recent call last):
 File "quickstart.py", line 5, in <module>
 session.login()
 File "C:\Users\BoneS\Desktop\InstaPy-master\instapy\instapy.py", line 264, in login
 self.bypass_suspicious_attempt):
 File "C:\Users\BoneS\Desktop\InstaPy-master\instapy\login_util.py", line 133, in login_user
 "//select[@class='_fsoey']/option[text()='English']").click()
 File "C:\Users\BoneS\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
 self._execute(Command.CLICK_ELEMENT)
 File "C:\Users\BoneS\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
 return self._parent.execute(command, params)
 File "C:\Users\BoneS\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
 self.error_handler.check_response(response)
 File "C:\Users\BoneS\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
 (Session info: chrome=65.0.3325.162)
 (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)

**Comment by Tjorriemorrie** [comment]
@BoneS38 update your chromedriver

**Comment by david-vendel** [comment]
Is there a way how to automatically keep updating Chromedriver? If I want this script to be running for 2 years without touching it, for example.

**Comment by Tjorriemorrie** [comment]
@justdvl That's an implementation. You have to write such a script yourself. It shouldn't be that hard though. But it's not a feasible solution anyway as IG will change over time and break the current library, meaning you'll have to regularly update the code anyway.
