### ISSUE TITLE
Traceback (most recent call last):   File "quickstart.py", line 1, in <module>     from instapy import InstaPy   File "C:\Users\Telo\Documents\GitHub\InstaPy\instapy\__init__.py", line 2, in <module>     from .instapy import InstaPy   File "C:\Users\Telo\Documents\GitHub\InstaPy\instapy\instapy.py", line 21     from .settings import Settings        ^ IndentationError: expected an indented block

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1694]
## Expected Behavior
WORK PERFECTLY
## Current Behavior
CRASHING FROM THE FIRST LINE SAYING
```
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\Telo\Documents\GitHub\InstaPy\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "C:\Users\Telo\Documents\GitHub\InstaPy\instapy\instapy.py", line 21
    from .settings import Settings
       ^
IndentationError: expected an indented block
```
## Possible Solution (optional)
IF I KNEW I WOULDN'T BE ASKING FOR HELP
## InstaPy configuration
HERE'S HOW MY QUICKSTART,PY LOOKS LIKE;

```
from instapy import InstaPy

insta_username = ''
insta_password = ''

# set headless_browser=True if you want to run InstaPy on a server
try:
    # set these if you're locating the library in the /usr/lib/pythonX.X/ directory
    # Settings.database_location = '/path/to/instapy.db'
    # Settings.browser_location = '/path/to/chromedriver'

    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      multi_logs=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit=2500)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['natgeo'], amount=1)

finally:
    # end the bot `session`
    session.end()

from instapy import InstaPy

insta_username = ''
insta_password = ''

# set headless_browser=True if you want to run InstaPy on a server
try:
    # set these if you're locating the library in the /usr/lib/pythonX.X/ directory
    # Settings.database_location = '/path/to/instapy.db'
    # Settings.browser_location = '/path/to/chromedriver'

    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      multi_logs=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit=2500)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['natgeo'], amount=1)

finally:
    # end the bot session
    session.end()
```

=============================================================
IVE SET EVERYTHING UP PERFECTLY, PLEASE HELP

**Comment by Tjorriemorrie** [comment]
You seem to have an error: there is an indentation [around here](https://github.com/timgrossmann/InstaPy/blob/cf789726ae65a11e666031760444a0074b3144ff/instapy/instapy.py#L30)

**Comment by wassim1995** [comment]
I have the same problem
