### ISSUE TITLE
Error with the last update

### ISSUE THREAD

**Issue by animetrk** [InstaPy/InstaPy#1703]
## Expected Behavior
It was working without a problem, then I updated with the latest update.

## Current Behavior
It gives the following error when I write "python quickstart.py":

> Traceback (most recent call last):
>   File "quickstart.py", line 3, in <module>
>     from instapy import InstaPy
>   File "C:\Users\USER\Documents\bot1\instapy\__init__.py", line 2, in <module>
>     from .instapy import InstaPy
>   File "C:\Users\USER\Documents\bot1\instapy\instapy.py", line 19, in <module>
>     from .clarifai_util import check_image
>   File "C:\Users\USER\Documents\bot1\instapy\clarifai_util.py", line 3, in <module>
>     from clarifai.rest import ClarifaiApp, Image as ClImage
>   File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\clarifai-2.0.32-py3.6.egg\clarifai\rest\__init__.py", line 3, in <module>
>   File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\clarifai-2.0.32-py3.6.egg\clarifai\rest\client.py", line 21, in <module>
> ModuleNotFoundError: No module named 'past'

Note: I'm not using clarifai

## InstaPy configuration
(Just like it works before)

```
import traceback

from instapy import InstaPy

insta_username = 'username'
insta_password = 'password'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=False)

try:
    session.login()

    # settings
    session.set_lower_follower_count(limit = 30)
    session.set_do_comment(False, percentage=1)
    session.set_comments(['comments'], media='Photo')
    session.set_dont_include(['users'])
    session.set_dont_like(['sex'])
    session.set_dont_unfollow_active_users(enabled=True, posts=5)
    session.set_user_interact(amount=2, randomize=False, percentage=100, media='Photo')
    session.set_ignore_users(['haters'])

    # actions
    session.unfollow_users(amount=100, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=150, unfollow_after=72*60*60)
    session.like_by_feed(amount=40, randomize=False, unfollow=False, interact=False)    
    session.follow_user_followers(['someone'], amount=30, sleep_delay=120, randomize=False, interact=True)
    session.like_by_feed(amount=20, randomize=False, unfollow=False, interact=False)
    session.follow_user_followers(['someone2'], amount=30, sleep_delay=120, randomize=False, interact=True)
    session.like_by_feed(amount=30, randomize=False, unfollow=False, interact=False)
    session.follow_user_followers(['someone3'], amount=30, sleep_delay=120, randomize=False, interact=True)
    session.like_by_feed(amount=40, randomize=False, unfollow=False, interact=False)

except Exception as exc:
    # full stacktrace when raising Github issue
    traceback.print_exc(exc)

finally:
    # end the bot session
    session.end()
```

**Comment by animetrk** [comment]
I solved it by searching on internet. They say 
`pip install future` 
will fix it but when I tried it I get an error. So I tried other things,
`pip install --upgrade future`
and it upgraded it. And the "No module named 'Past' error dissappeared.

Now instapy works normally. Closing the issue...
