### ISSUE TITLE
I get this Error

### ISSUE THREAD

**Issue by Affenjimbo** [InstaPy/InstaPy#1709]
## Expected Behavior

should be working ^^ 

## Current Behavior

I get this message when I run quickstart.py:

========== RESTART: C:\Users\Max\InstaPy-master\quickstart_2018.py ==========
Traceback (most recent call last):
  File "C:\Users\Max\InstaPy-master\quickstart_2018.py", line 3, in <module>
    from instapy import InstaPy
  File "C:\Users\Max\InstaPy-master\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "C:\Users\Max\InstaPy-master\instapy\instapy.py", line 19, in <module>
    from .clarifai_util import check_image
  File "C:\Users\Max\InstaPy-master\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Image as ClImage
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\site-packages\clarifai-2.0.32-py3.6.egg\clarifai\rest\__init__.py", line 3, in <module>
    from .client import ApiClient, ApiError, UserError, TokenError
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\site-packages\clarifai-2.0.32-py3.6.egg\clarifai\rest\client.py", line 22, in <module>
    from jsonschema import validate
ModuleNotFoundError: No module named 'jsonschema'
>>> 

I just downloaded the latest version of Instapy and Chromedrive. Does anyone have an Idea what I am doing wrong?

Thanks a lot!

**Comment by CharlesCCC** [comment]
make sure you have followed the **instruction** and run the installation before you start.
