### ISSUE TITLE
InstaPy instance has no attribute "headless_browser"

### ISSUE THREAD

**Issue by Sigurros492** [InstaPy/InstaPy#1713]
## InstaPy configuration
I have it running on Raspbian on a Raspberry pi. I had it running fine on Mac OS with the headless_browser. I have the latest chromedriver in the assests folder.  I have headless_browser set to true in quickstart.py and instapy.py

Traceback (most recent call last):
  File "quickstart.py", line 19, in <module>
    multi_logs=True)
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 148, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 224, in set_selenium_local_session
    if self.headless_browser:
AttributeError: InstaPy instance has no attribute 'headless_browser'

**Comment by Sigurros492** [comment]
I fixed it myself, along with several other errors.
