### ISSUE TITLE
After Latest PR, Receiving a JSONDecodeError

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1728]
Traceback (most recent call last):
  File ".\quickstart.py", line 18, in <module>
    multi_logs=True)
  File "C:\Users\****\Documents\GitHub\InstaPy2\instapy\instapy.py", line 116, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "C:\Users\****\Documents\GitHub\InstaPy2\instapy\unfollow_util.py", line 881, in load_follow_restriction
    return json.load(followResFile)
  File "C:\Users\****\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\****\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\****\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\****\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 77785 (char 77784)

**Comment by ghost** [comment]
Did 2 things to fix this:
1. Turn off multilogs
2. Insert newest chromedriver

**Comment by Tjorriemorrie** [comment]
Mutlilogs worked because there is a bad character in `followRestriction.json` and it fails to load, therefore switching to another directory, and new file, it worked again. You can also just delete that file in your user's directory, or search it for the username that has an unusual character and delete that line.
