### ISSUE TITLE
New Update Not Working

### ISSUE THREAD

**Issue by omidedipidizi** [InstaPy/InstaPy#1730]
## Current Behavior

Traceback (most recent call last):

  File "new.py", line 11, in job
    session=InstaPy(username=insta_username,password=insta_password,headless_browser=False,multi_logs=False)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 152, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 256, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x76962150>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/common/service.py", line 163, in __del__
    self.stop()
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/common/service.py", line 135, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'
^CTraceback (most recent call last):
  File "new.py", line 42, in <module>
    time.sleep(1)
KeyboardInterrupt

## InstaPy configuration

InstaPy from last commit
ChromeDriver 2.36

<img width="720" alt="screen shot 2018-03-23 at 10 20 22 pm" src="https://user-images.githubusercontent.com/25254194/37859538-7b7f7478-2eeb-11e8-9ece-851e449e389a.png">

**Comment by callahanryang** [comment]
**New Update Causes This for Me as well:**

C:\Users\Ryan\Downloads\InstaPy-master>set PYTHONIOENCODING=UTF-8

C:\Users\Ryan\Downloads\InstaPy-master>py quickstart.py

DevTools listening on ws://127.0.0.1:12993/devtools/browser/132793f2-9646-4f86-96ec-0b0c171526e2
2018-03-24 15:38:12 - INFO - Session started - 2018-03-24 15:38:12
2018-03-24 15:38:12 - WARNING - Sorry, Record Activity is not working on Windows. We're working to fix this soon!
[1692:2956:0324/153814.987:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
[7204:8600:0324/153815.039:ERROR:gles2_cmd_decoder.cc(18268)] [.DisplayCompositor-000001879D6933D0]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[7204:8600:0324/153815.039:ERROR:gles2_cmd_decoder.cc(10094)] [.DisplayCompositor-000001879D6933D0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
2018-03-24 15:38:15 - INFO - Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    session.login()
  File "C:\Users\Ryan\Downloads\InstaPy-master\instapy\instapy.py", line 260, in login
    log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\Users\Ryan\Downloads\InstaPy-master\instapy\print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "C:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "C:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.16299 x86_64)

**Comment by balakedev** [comment]
Im getting this

```
Traceback (most recent call last):
  File "C:\Users\Blake Waldron\Desktop\InstaPy-master\InstaPy\ST01.py", line 81, in <module>
    session.like_by_tags(amount=25, use_smart_hashtags=True)
  File "C:\Users\Blake Waldron\Desktop\InstaPy-master\InstaPy\instapy\instapy.py", line 831, in like_by_tags
    skip_top_posts)
  File "C:\Users\Blake Waldron\Desktop\InstaPy-master\InstaPy\instapy\like_util.py", line 223, in get_links_for_tag
    "window.scrollTo(0, document.body.scrollHeight);")
  File "C:\Users\Blake Waldron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 491, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Blake Waldron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Blake Waldron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)
```

**Comment by riccardorighettiphoto** [comment]
Same here... latest commits have totally messed up!

**Comment by Tjorriemorrie** [comment]
All three issues here are different :p

@blakemmw that error is a bug in chromedriver, you can update to the latest, 2.36 you are on 2.34.

@callahanryang that was fixed in #1616. Make sure you have the latest code. You can check you have the fix by running `git log | grep e1bd0b8`

@omidedipidizi  that is an error of chromedriver not being able to work with chrome. Not sure, but it could maybe happen that certain versions of chromedriver only work with certain versions of chrome.

**Comment by d7laungani** [comment]
@omidedipidizi Did you ever get this issue fixed?

**Comment by omidedipidizi** [comment]
non still same issue
