### ISSUE TITLE
Hi This my error after update

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#1735]
Traceback (most recent call last):
  File "startstef.py", line 35, in <module>
    session.like_by_tags(['musculation','teamshape','getfit','fit','fitnessmodel','fitspo','crossfit','muscu','shooting','fitfrenchies'], amount=10)
  File "/Users/Retina/Desktop/Instapy/instapy/instapy.py", line 987, in like_by_tags
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 39: ordinal not in range(128)

**Comment by johnvfitness** [comment]
I found good ;)
