### ISSUE TITLE
"database is locked"

### ISSUE THREAD

**Issue by denisemenov** [InstaPy/InstaPy#1744]
I do not know why, but I always have such a mistake.
I tried to run only 1 script on the server, but still have this error.
This error can appear both at the beginning of the script execution (example below), and after a few hours.
I did not find any patterns in the appearance of this error.

## Current Behavior

```
INFO [2018-03-25 12:29:04] [username]  Session started - 2018-03-25 12:29:04
INFO [2018-03-25 12:29:22] [username]  Logged in successfully!
INFO [2018-03-25 12:29:24] [username]  Tag [1/11]
INFO [2018-03-25 12:29:24] [username]  --> hashtag
...
bla-bla-bla
...
INFO [2018-03-25 12:30:30] [username]  Session ended - 2018-03-25 12:30:30
INFO [2018-03-25 12:30:30] [username]  --------------------


Traceback (most recent call last):
  File "tags_ds.py", line 30, in <module>
    interact=True)
  File "/root/InstaPy/instapy/instapy.py", line 871, in like_by_tags
    skip_top_posts)
  File "/root/InstaPy/instapy/like_util.py", line 178, in get_links_for_tag
    update_activity()
  File "/root/InstaPy/instapy/util.py", line 55, in update_activity
    cur.execute("SELECT * FROM statistics WHERE created == date('now')")
sqlite3.OperationalError: database is locked
```
## InstaPy configuration
```
from instapy import InstaPy

insta_username = ''
insta_password = ''

try:
    session = InstaPy(username=insta_username,
                    password=insta_password,
                    headless_browser=True,
                    nogui=True,
                    multi_logs=True)
    session.login()

    # settings
    
    session.set_sleep_reduce(20)
    session.set_upper_follower_count(limit=1814)
    session.set_lower_follower_count(limit=54)
    session.set_user_interact(amount=6,
                              randomize=True,
                              percentage=60,
                              media='Photo')
    session.set_dont_like(['hashtags'])
    session.set_ignore_users(['username'])

    # actions
    session.like_by_tags(['hashtags'],
                         amount=133,
                         skip_top_posts=True,
                         interact=True)
    session.like_by_locations(['123456789'],
                              amount=133,
                              skip_top_posts=True,
                              interact=True)

finally:
    session.end()

```

**Comment by sionking** [comment]
seems like permission error

**Comment by denisemenov** [comment]
I think that permission error appears immediately, and not after several hours of script job.

**Comment by denisemenov** [comment]
Still have this error. :(
