### ISSUE TITLE
Message: unknown error: Cannot read property 'entry_data' of undefined

### ISSUE THREAD

**Issue by Doom666** [InstaPy/InstaPy#1745]
`Traceback (most recent call last):
  File "dexterforestbot.py", line 74, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 493, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 78, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 131, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 411, in run
    ret = self.job_func()
  File "dexterforestbot.py", line 49, in job
    session.like_by_tags(keywords, amount=liknum, interact=False)
  File "/root/2ndInstaPy/instapy/instapy.py", line 874, in like_by_tags
    self.logger)
  File "/root/2ndInstaPy/instapy/like_util.py", line 415, in check_link
    "return window._sharedData.entry_data.PostPage")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.4.0-116-generic x86_64)`

I actually don't know what the error is about...
could someone help me understand what went wrong ?
it seems liek it just happened for no apparent reason, just as it was working.

**Comment by aleducode** [comment]
same problem

**Comment by FreakyBoy** [comment]
my problem was that Instagram ban for no reason my IP.. 
new IP -> working

**Comment by stevenharris-dev** [comment]
Check out [this comment](https://github.com/timgrossmann/InstaPy/issues/1338#issuecomment-363067955) on issue #1338 - it fixed the problem for me. You have to modify `like_util.py`
