### ISSUE TITLE
Pulled, needed to upgrade chromium driver - getting this error

### ISSUE THREAD

**Issue by balakedev** [InstaPy/InstaPy#1749]
```

DevTools listening on ws://127.0.0.1:12998/devtools/browser/dba53729-ac45-4d3b-9f7f-a32ff3b882ae
Traceback (most recent call last):
  File "C:\Users\######\Desktop\InstaPy-master\InstaPy\ST01.py", line 5, in <module>
    session = InstaPy(username='######', password='########')
  File "C:\Users\####\Desktop\InstaPy-master\InstaPy\instapy\instapy.py", line 152, in __init__
    self.set_selenium_local_session()
  File "C:\Users\######\Desktop\InstaPy-master\InstaPy\instapy\instapy.py", line 267, in set_selenium_local_session
    float(matches.groups()[0]), Settings.chromedriver_min_version))
instapy.instapy.InstaPyError: chromedriver 2.34 is not supported, expects 2.36+


```

2.36 is in the assets folder. really confused

**Comment by blakemmw** [comment]
So who hacked my account?

**Comment by Tjorriemorrie** [comment]
2.34 is your current chromedriver version, as it is read from the session. If you don't come right, it is a setting, you can change it to 2.34 in the Settings file.

**Comment by balakedev** [comment]
@Tjorriemorrie Downloaded 2.36. Receiving the same error. 

When I set chromedriver_min_version to 2.3 I get another error:

`Traceback (most recent call last):
  File "C:\Users\####\Desktop\InstaPy-master\InstaPy\ST01.py", line 9, in <module>
    session.login()
  File "C:\Users\####\Desktop\InstaPy-master\InstaPy\instapy\instapy.py", line 302, in login
    self.bypass_suspicious_attempt):
  File "C:\Users\####\Desktop\InstaPy-master\InstaPy\instapy\login_util.py", line 132, in login_user
    "//select[@class='_fsoey']/option[text()='English']").click()
  File "C:\Users\####\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\####\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\####\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Users\####\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)
`
