### ISSUE TITLE
Issues after latest commits and chromedriver update to 2.37

### ISSUE THREAD

**Issue by riccardorighettiphoto** [InstaPy/InstaPy#1757]
Hello, after having pulled last commits, my InstaPy installation on laptop (Windows 10) is totally messed.
This is the error I get: 
```
Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    session.login()
  File "------\instapy.py", line 309, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "-------\print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "--------\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "-------AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "----------\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.15063 x86)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 35, in <module>
    traceback.print_exc(exc)
  File "------------\AppData\Local\Programs\Python\Python36-32\lib\traceback.py", line 159, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "---------\AppData\Local\Programs\Python\Python36-32\lib\traceback.py", line 100, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "-----------\AppData\Local\Programs\Python\Python36-32\lib\traceback.py", line 497, in __init__
    capture_locals=capture_locals)
  File "--------\AppData\Local\Programs\Python\Python36-32\lib\traceback.py", line 332, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'WebDriverException' and 'int'
```
I guess is something of incompatibility issues, could you help me?
Thank you.

**Comment by furk4no** [comment]
Downgrade your chromebrowser to 2.36 and try running again..

**Comment by balakedev** [comment]
@furk4no , hey I tried downloading the 2.36 from the suggested link. Yet when I put the file in assets cmd still says it’s running 2.34. Do you know what’s going wrong with this?

**Comment by oculairmedia** [comment]
@blakemmw did you remove .exe from the chrome driver file name?
