### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by RealMakAttak** [InstaPy/InstaPy#1759]
Traceback (most recent call last):
  File "quickstart.py", line 18, in <module>
    multi_logs=True)
  File "C:\Users\Antony\Documents\InstaPy_no_mods_26.03.18\InstaPy-master\instapy\instapy.py", line 152, in __init__
    self.set_selenium_local_session()
  File "C:\Users\Antony\Documents\InstaPy_no_mods_26.03.18\InstaPy-master\instapy\instapy.py", line 256, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\Antony\Anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in __init__
    self.service.start()
  File "C:\Users\Antony\Anaconda3\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Users\Antony\Anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Antony\Anaconda3\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

I have tried everything to solve this, does anyone know what it is?

**Comment by indiegamefiend** [comment]
same issue

**Comment by RealMakAttak** [comment]
I have tried running it off of 32 bit and 64 bit Python3 installs but same thing
