### ISSUE TITLE
NameError: name 'session' is not defined

### ISSUE THREAD

**Issue by 0x526f6d656f** [InstaPy/InstaPy#1763]
`Traceback (most recent call last):
  File "C:\Users\User\Documents\InstaPy\unfollow_start.py", line 15, in <module>
    multi_logs=True)
  File "C:\Users\User\Documents\InstaPy\instapy\instapy.py", line 116, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "C:\Users\User\Documents\InstaPy\instapy\unfollow_util.py", line 893, in load_follow_restriction
    return json.load(followResFile)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 8205 (char 8204)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Documents\InstaPy\unfollow_start.py", line 35, in <module>
    session.end()
NameError: name 'session' is not defined`

Have this happening with two accounts of mine

**Comment by denisemenov** [comment]
Show us the config

**Comment by Tjorriemorrie** [comment]
also make sure to update to latest. that session not defined has been fixed.
