### ISSUE TITLE
Cannot read property 'entry_data' of undefined

### ISSUE THREAD

**Issue by gabriansa** [InstaPy/InstaPy#1775]
Hello! 
I get this error sometimes, anyone who knows how to fix it?

```
Traceback (most recent call last):
  File "quickstart.py", line 31, in <module>
    session.like_by_tags(amount=15, use_smart_hashtags=True)
  File "/Users/*****/Desktop/InstaPy1/instapy/instapy.py", line 850, in like_by_tags
    self.logger)
  File "/Users/*****/Desktop/InstaPy1/instapy/like_util.py", line 488, in check_link
    "return window._sharedData.entry_data."
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.13.2 x86_64)
```

**Comment by riccardorighettiphoto** [comment]
same here

**Comment by skaeslin** [comment]
Same here. Instapy runs on a raspberry pi 3 in my case.

**Comment by GitNees** [comment]
Seems insta changed something. Its broken.

**Comment by CharlesCCC** [comment]
I have encountered the same issue. :(

**Comment by gruvismalt** [comment]
Same here, raspberry pi 3...

**Comment by uluQulu** [comment]
Hey guys, there is a [workaround](https://github.com/timgrossmann/InstaPy/issues/1338#issuecomment-377718322) for it in #1338
