### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by Mehran** [InstaPy/InstaPy#1784]
it work well till yesterday but today i got this error .

**Comment by thankmelater23** [comment]
Getting the same thing

**Comment by Essbuisness** [comment]
@uluQulu same problem here
worked fine a few hours ago now gives me


C:\Users\USER>"C:\Users\USER\Desktop\Insta Bot\InstaPy-master\InstaPy-master\quickstart.py"
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\Insta Bot\InstaPy-master\InstaPy-master\quickstart.py", line 22, in <module>
    multi_logs=True)
  File "C:\Users\USER\Desktop\Insta Bot\InstaPy-master\InstaPy-master\instapy\instapy.py", line 122, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "C:\Users\USER\Desktop\Insta Bot\InstaPy-master\InstaPy-master\instapy\unfollow_util.py", line 849, in load_follow_restriction
    return json.load(followResFile)
  File "C:\Python27\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by uluQulu** [comment]
Hi guys
@Essbuisness, have a read https://github.com/timgrossmann/InstaPy/pull/2086#issuecomment-394117784 to find a solution.
