### ISSUE TITLE
Raspberry initial setup / first run

### ISSUE THREAD

**Issue by timmoh** [InstaPy/InstaPy#1813]
installed clean raspberry following every step in the documentation.
but if I start the script

## Current Behavior
ERROR [2018-04-06 23:46:32] [None]  Message: Service /home/pi/InstaPy/assets/chromedriver unexpectedly exited. Status code was: -4
Traceback (most recent call last):
  File "/home/pi/InstaPy/instapy/instapy.py", line 256, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 86, in start
    self.assert_process_still_running()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 99, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /home/pi/InstaPy/assets/chromedriver unexpectedly exited. Status code was: -4

Traceback (most recent call last):
  File "/home/pi/InstaPy/instapy/instapy.py", line 256, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 86, in start
    self.assert_process_still_running()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 99, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /home/pi/InstaPy/assets/chromedriver unexpectedly exited. Status code was: -4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/pi/InstaPy/instapy/instapy.py", line 152, in __init__
    self.set_selenium_local_session()
  File "/home/pi/InstaPy/instapy/instapy.py", line 260, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/InstaPy/assets/chromedriver

## InstaPy configuration
normal quickstart without any changes... (except user&pw)

Also tested: nogui=True & headless_browser=True

**Comment by d7laungani** [comment]
I have the same issue as well. Any solutions?

**Comment by mikestan** [comment]
These are chromium-browser and dep issues. Follow the installation and then the Raspberry Pi setup: https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md

FWIW, I also had to insert my own step 13.5: sudo apt-get install libjpeg62

Lastly, I had to edit ~/InstaPy/instapy/settings.py and change the chromium version back to 2.33 because nothing newer is currently available.

**Comment by timmoh** [comment]
same issue again
