### ISSUE TITLE
Error DigitalOceans

### ISSUE THREAD

**Issue by Jenderz** [InstaPy/InstaPy#1823]
## Expected Behavior

```
root@JAN:/opt/InstaPy# sudo nano quickstart.py
root@JAN:/opt/InstaPy# python quickstart.py
ERROR [2018-04-10 00:45:33] [jenderz]  Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.13.0-37-generic x86_64)
Traceback (most recent call last):
  File "/opt/InstaPy/instapy/instapy.py", line 256, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.13.0-37-generic x86_64)

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/opt/InstaPy/instapy/instapy.py", line 152, in __init__
    self.set_selenium_local_session()
  File "/opt/InstaPy/instapy/instapy.py", line 260, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /opt/InstaPy/assets/chromedriver

```

## InstaPy configuration

Help me!

**Comment by ceribbo** [comment]
I'm having a really similar issue and get understand which is the problem

**Comment by lormayna** [comment]
I have the same error using chromedriver 2.37 inside a virtualenv.

**Comment by vollerempfang** [comment]
same on 2.40
