### ISSUE TITLE
My quickstart.py crashing everytime

### ISSUE THREAD

**Issue by bhuiyanmobasshir94** [InstaPy/InstaPy#1838]
## Expected Behavior
My instapy is not working as expecting for liking posts for tags and sometimes for commenting
![image](https://user-images.githubusercontent.com/31741188/38696262-7eee434e-3eb0-11e8-8a78-852fbd568896.png)

## Current Behavior
It's crashing all the time

**Comment by bhuiyanmobasshir94** [comment]
please give me the solution I am using all the things updated but it's saying all the time

**Comment by bhuiyanmobasshir94** [comment]
Traceback (most recent call last):
  File "index.py", line 11, in <module>
    .like_by_tags(['mindset', 'coaching', 'behappy', 'giessen', 'marburg','lich', 'leben', 'sinndeslebens'], amount=35)\
  File "C:\Users\mobas\Desktop\instagram_bot\Final Work Station\InstaPy\instapy\instapy.py", line 890, in like_by_tags
    self.logger)
  File "C:\Users\mobas\Desktop\instagram_bot\Final Work Station\InstaPy\instapy\like_util.py", line 564, in check_link
    '" in "'.join([iffy, quashed]))
TypeError: sequence item 1: expected str instance, bytes found
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x05747F50>>
Traceback (most recent call last):
  File "C:\Users\mobas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 163, in __del__
  File "C:\Users\mobas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 139, in stop
  File "C:\Users\mobas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down
** Same problem to every function
TypeError: sequence item 1: expected str instance, bytes found **

**Comment by ShiftingKill** [comment]
I suggest just taking quickstart.py and start file out and re cloning. Also make sure you have Github desktop as well as the Github Desktop repository downloaded (I have 2 folders under GitHub on my PC, one for InstaPy and one for Github Desktop so you can clone without failures or missed files).

**Comment by bhuiyanmobasshir94** [comment]
Traceback (most recent call last):
  File "quickstart.py", line 35, in <module>
    session.like_by_tags(['medical'], amount=50)
  File "C:\Users\mobas\Desktop\instagram_bot\Final Work Station\InstaPy\instapy\instapy.py", line 890, in like_by_tags
    self.logger)
  File "C:\Users\mobas\Desktop\instagram_bot\Final Work Station\InstaPy\instapy\like_util.py", line 564, in check_link
    '" in "'.join([iffy, quashed]))
TypeError: sequence item 1: expected str instance, bytes found

**Comment by bhuiyanmobasshir94** [comment]
@ShiftingKill can you describe more I am noob here. Thanks. BTW I am running the quickstart.py from this repo.
