### ISSUE TITLE
Can't set webdriver (raise error)

### ISSUE THREAD

**Issue by ceribbo** [InstaPy/InstaPy#1839]
I can't understand why but InstaPy is crashing causing this error raised on line 256 which is `self.browser = webdriver.Chrome(chromedriver_location,
                                                desired_capabilities=capabilities,
                                                chrome_options=chrome_options)`
how can i solve it?
## Current Behavior
`(Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.13.0-1012-azure x86_64) 
selenium.common.exceptions.WebDriverException: Message: chrome not reachable 
raise exception_class(message, screen, stacktrace) 
File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response 
self.error_handler.check_response(response) 
File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute 
response = self.execute(Command.NEW_SESSION, parameters) 
File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session 
self.start_session(desired_capabilities, browser_profile) 
File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__ 
desired_capabilities=desired_capabilities) 
File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__ 
chrome_options=chrome_options) 
File "/home/instapy/Desktop/InstaPy/instapy/instapy.py", line 256, in set_selenium_local_session 
Traceback (most recent call last): 
(Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.13.0-1012-azure x86_64) 
ERROR [2018-04-12 21:55:58] [user] Message: chrome not reachable `
## InstaPy configuration
classic on a configuration a virtual machine with linux

**Comment by timgrossmann** [comment]
@ceribbo Have you downloaded the chromedriver and put it in the `assets` folder?

Have you updated the chrome driver in the last time?

**Comment by ceribbo** [comment]
@timgrossmann nope it is a problem that happens randomly, It happens after some sessions, running it non stop. is it possible it is related to selenium?

**Comment by ceribbo** [comment]
is it possible that if it crashes and the session is not yet closed the error is raised in selenium?
