### ISSUE TITLE
help With raspberrypi and Instapy

### ISSUE THREAD

**Issue by Sewi13** [InstaPy/InstaPy#1847]
root@raspberrypi:/home/pi/InstaPy# python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/pi/InstaPy/instapy/instapy.py", line 157, in __init__
    self.set_selenium_local_session()
  File "/home/pi/InstaPy/instapy/instapy.py", line 261, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

i got this error message when i try to start the quickstart.py. 
Can someone please help me, i want to run the bot on a raspberry pi 3

**Comment by athena15** [comment]
+1
