### ISSUE TITLE
Raspberry Pi, Exec format error

### ISSUE THREAD

**Issue by gabriansa** [InstaPy/InstaPy#1852]
Hello!
i have been trying to run my quickstart.py file on the raspberry pi3. I followed all the steps given here on the website, but unfortunately i am getting some errors. I am using chromium as browser.
Here is the error i get

```
pi@raspberrypi:~/Projects/InstaPy $ sudo xvfb-run python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    headless_browser=False)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 157, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 261, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

```

**Comment by BorysVrublevskyi** [comment]
I got same issue when i downloaded manually chromedriver from site. But it was 64bit and my Orange Pi Zero is ARMv71 (32bit). So I just installed it (apt install chromedriver) and copied from /usr/bin/chromedriver to InstaPy/assets folder. And it's got ALIVE!!1
