### ISSUE TITLE
Trackback Error

### ISSUE THREAD

**Issue by kddww8** [InstaPy/InstaPy#1867]
## Expected Behavior
after pyton quickstart.py, error code:
## Current Behavior
Traceback (most recent call last):
  File "quickstart.py", line 7, in <module>
    from instapy import InstaPy
  File "/root/instapy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/root/instapy/instapy/instapy.py", line 22, in <module>
    from .clarifai_util import check_image
  File "/root/instapy/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Image as ClImage
  File "build/bdist.linux-x86_64/egg/clarifai/rest/__init__.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/clarifai/rest/client.py", line 16, in <module>
ImportError: No module named enum

## InstaPy configuration
Django Ubuntu Server

**Comment by ardacebi** [comment]
I'm having the exact same issue here.
@timgrossmann

**Comment by TurboProgramming** [comment]
@timgrossmann
