### ISSUE TITLE
Selenium crashes under Docker

### ISSUE THREAD

**Issue by funkypenguin** [InstaPy/InstaPy#1882]
Hey folks,

I'm running InstaPy under Docker Swarm, with latest Selenium image as of 16 days ago. I'm getting intermittent crashes which seem to be related to Selenium, and seem to be triggered triggered when trying to interact with followers of accounts with large _amounts_ of followers.

## Expected Behavior

InstaPy works consistently

## Current Behavior

InstaPy crashes randomly, with messages like below, implicating Selenium:

```
instapy_web.1.q4vqyno7tmd2@docker    | Traceback (most recent call last):
instapy_web.1.q4vqyno7tmd2@docker    |   File "docker_quickstart.py", line 33, in <module>
instapy_web.1.q4vqyno7tmd2@docker    |     bot.login()
instapy_web.1.q4vqyno7tmd2@docker    |   File "/code/instapy/instapy.py", line 314, in login
instapy_web.1.q4vqyno7tmd2@docker    |     self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
instapy_web.1.q4vqyno7tmd2@docker    |   File "/code/instapy/print_log_writer.py", line 8, in log_follower_num
instapy_web.1.q4vqyno7tmd2@docker    |     browser.get('https://www.instagram.com/' + username)
instapy_web.1.q4vqyno7tmd2@docker    |   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 324, in get
instapy_web.1.q4vqyno7tmd2@docker    |     self.execute(Command.GET, {'url': url})
instapy_web.1.q4vqyno7tmd2@docker    |   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
instapy_web.1.q4vqyno7tmd2@docker    |     self.error_handler.check_response(response)
instapy_web.1.q4vqyno7tmd2@docker    |   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
instapy_web.1.q4vqyno7tmd2@docker    |     raise exception_class(message, screen, stacktrace)
instapy_web.1.q4vqyno7tmd2@docker    | selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
instapy_web.1.q4vqyno7tmd2@docker    | from unknown error: cannot determine loading status
instapy_web.1.q4vqyno7tmd2@docker    | from tab crashed
instapy_web.1.q4vqyno7tmd2@docker    |   (Session info: chrome=65.0.3325.181)
instapy_web.1.q4vqyno7tmd2@docker    |   (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 3.10.0-693.21.1.el7.x86_64 x86_64)
```

## InstaPy configuration

My config looks like this:

```
bot = InstaPy(username=insta_username, password=insta_password, selenium_local_session=False)
bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub')
bot.login()

# Ignore users as defined by ignore_usernames and friends
bot.set_ignore_users(ignore_usernames)
bot.set_ignore_users(friend_list)

# For now, don't comment, just like and follow
bot.set_do_comment(False)

# Yes, enable following of 100% of users, once
bot.set_do_follow(enabled=True, percentage=100, times=1)

# Yes, like (although interacting kinda does this already)
bot.set_do_like(enabled=True, percentage=100)

# Ignore the plebs with < 100 followers
bot.set_lower_follower_count(limit = 100)

# When we interact, do 2 likes to 100% of the interactees, but only on photos
bot.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')

# Now interact with followers of the "follow_followers_of" list. 2 interactions each
bot.interact_user_followers(follow_followers_of, amount=2, randomize=False)
```

**Comment by funkypenguin** [comment]
Here's a similar crash I just noted:

````
instapy_web.1.s8o3w5x0ljfv@docker    | WARNING [2018-04-19 09:14:28] [<my username>]  whoompthayeritis -> Less users to follow than requested. == 0
instapy_web.1.qn4i5czk8f55@docker    |   File "docker_quickstart.py", line 33, in <module>
instapy_web.1.x9e5yz9v188o@docker    | Traceback (most recent call last):
instapy_web.1.x9e5yz9v188o@docker    |   File "docker_quickstart.py", line 33, in <module>
instapy_web.1.s224b4rqmhpq@docker    | Traceback (most recent call last):
instapy_web.1.qn4i5czk8f55@docker    |     bot.login()
instapy_web.1.qn4i5czk8f55@docker    |   File "/code/instapy/instapy.py", line 307, in login
instapy_web.1.x9e5yz9v188o@docker    |     bot.login()
instapy_web.1.s224b4rqmhpq@docker    |   File "docker_quickstart.py", line 33, in <module>
instapy_web.1.s224b4rqmhpq@docker    |     bot.login()
instapy_web.1.qn4i5czk8f55@docker    |     self.bypass_suspicious_attempt):
instapy_web.1.x9e5yz9v188o@docker    |   File "/code/instapy/instapy.py", line 307, in login
instapy_web.1.x9e5yz9v188o@docker    |     self.bypass_suspicious_attempt):
instapy_web.1.s224b4rqmhpq@docker    |   File "/code/instapy/instapy.py", line 307, in login
instapy_web.1.qn4i5czk8f55@docker    |   File "/code/instapy/login_util.py", line 116, in login_user
instapy_web.1.qn4i5czk8f55@docker    |     "//*[contains(text(), 'Log in')]")
instapy_web.1.x9e5yz9v188o@docker    |   File "/code/instapy/login_util.py", line 97, in login_user
instapy_web.1.s224b4rqmhpq@docker    |     self.bypass_suspicious_attempt):
instapy_web.1.s224b4rqmhpq@docker    |   File "/code/instapy/login_util.py", line 112, in login_user
instapy_web.1.qn4i5czk8f55@docker    |   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 401, in find_elements_by_xpath
instapy_web.1.x9e5yz9v188o@docker    |     browser.get('https://www.instagram.com')
instapy_web.1.x9e5yz9v188o@docker    |   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 324, in get
instapy_web.1.s224b4rqmhpq@docker    |     browser.get('https://www.instagram.com')
instapy_web.1.qn4i5czk8f55@docker    |     return self.find_elements(by=By.XPATH, value=xpath)
instapy_web.1.qn4i5czk8f55@docker    |   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 983, in find_elements
instapy_web.1.x9e5yz9v188o@docker    |     self.execute(Command.GET, {'url': url})
instapy_web.1.s224b4rqmhpq@docker    |   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 324, in get
instapy_web.1.s224b4rqmhpq@docker    |     self.execute(Command.GET, {'url': url})
instapy_web.1.qn4i5czk8f55@docker    |     'value': value})['value'] or []
instapy_web.1.x9e5yz9v188o@docker    |   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
instapy_web.1.x9e5yz9v188o@docker    |     self.error_handler.check_response(response)
instapy_web.1.s224b4rqmhpq@docker    |   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
instapy_web.1.qn4i5czk8f55@docker    |   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
instapy_web.1.qn4i5czk8f55@docker    |     self.error_handler.check_response(response)
instapy_web.1.x9e5yz9v188o@docker    |   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
instapy_web.1.s224b4rqmhpq@docker    |     self.error_handler.check_response(response)
instapy_web.1.s224b4rqmhpq@docker    |   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
instapy_web.1.qn4i5czk8f55@docker    |   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
instapy_web.1.x9e5yz9v188o@docker    |     raise exception_class(message, screen, stacktrace)
instapy_web.1.x9e5yz9v188o@docker    | selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
instapy_web.1.s224b4rqmhpq@docker    |     raise exception_class(message, screen, stacktrace)
instapy_web.1.qn4i5czk8f55@docker    |     raise exception_class(message, screen, stacktrace)
instapy_web.1.qn4i5czk8f55@docker    | selenium.common.exceptions.WebDriverException: Message: chrome not reachable
instapy_web.1.x9e5yz9v188o@docker    | from tab crashed
instapy_web.1.s224b4rqmhpq@docker    | selenium.common.exceptions.WebDriverException: Message: no such session
instapy_web.1.s224b4rqmhpq@docker    |   (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 3.10.0-693.21.1.el7.x86_64 x86_64)
instapy_web.1.qn4i5czk8f55@docker    |   (Session info: chrome=65.0.3325.181)
instapy_web.1.x9e5yz9v188o@docker    |   (Session info: chrome=65.0.3325.181)
instapy_web.1.x9e5yz9v188o@docker    |   (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 3.10.0-693.21.1.el7.x86_64 x86_64)
instapy_web.1.s224b4rqmhpq@docker    |
instapy_web.1.qn4i5czk8f55@docker    |   (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 3.10.0-693.21.1.el7.x86_64 x86_64)
instapy_web.1.qn4i5czk8f55@docker    |
instapy_web.1.x9e5yz9v188o@docker    |
````

**Comment by jakeseaton** [comment]
I just power cycled my droplet and it works again
