### ISSUE TITLE
Chromedrivers issues.

### ISSUE THREAD

**Issue by mdrzn** [InstaPy/InstaPy#1906]
## Need help getting it to work

So, I'm on a VM running Debian GNU/Linux 7.11 (wheezy). 
I updated it to Jessie 8.0 to make sure I'm not on an old OS.
I'm following both the written How_To and the YT video for Digital Ocean.
I git the repo, modify the quickstart, download the chromedrivers, put 'em in the asset folder unzipped.

When I go launch quickstart.py:

```
InstaPy/assets/chromedriver unexpectedly exited. Status code was: 127
Traceback (most recent call last):
  File "/root/InstaPy/InstaPy/instapy/instapy.py", line 265, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 86, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 99, in assert_process_still_running
    % (self.path, return_code)
WebDriverException: Message: Service /root/InstaPy/InstaPy/assets/chromedriver unexpectedly exited. Status code was: 127

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/root/InstaPy/InstaPy/instapy/instapy.py", line 161, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/InstaPy/instapy/instapy.py", line 269, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /root/InstaPy/InstaPy/assets/chromedriver
```

also while installing I've seen these red errors:
```
python-keystoneclient 0.10.1 requires Babel>=1.3, which is not installed.
python-keystoneclient 0.10.1 requires iso8601>=0.1.9, which is not installed.
python-keystoneclient 0.10.1 requires lxml>=2.3, which is not installed.
python-keystoneclient 0.10.1 requires netaddr>=0.7.6, which is not installed.
python-keystoneclient 0.10.1 requires oslo.config>=1.2.1, which is not installed.
python-keystoneclient 0.10.1 requires pbr!=0.7,<1.0,>=0.6, which is not installed.
python-keystoneclient 0.10.1 requires stevedore>=0.14, which is not installed.
python-keystoneclient 0.10.1 has requirement PrettyTable<0.8,>=0.7, but you'll have prettytable 0.6.1 which is incompatible.
```

Does my LANG has to be set to en_US? It would break another script I have which need the system LANG to be set to it_IT.

I then tried to follow the guide, doing:
```
wget "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
 dpkg -i google-chrome-stable_current_amd64.deb
```
but I get all the dependence errors. I'm not even sure which tutorial should I follow by now.

**Comment by ghost** [comment]
make sure the chromedriver is executable with chmod is what i think 

`chmod +x db/chromedriver`
`chmod +x assets/chromedriver`
`chmod 755 assets/chromedriver`

**Comment by Syslog777** [comment]
You need to install google-chrome-stable. Are you running this on a server? Also, are you using 'python quickstart.py' or 'python3 quickstart.py'? Are you using virtualvenv?

**Comment by cyberpz** [comment]
Install google-chrome-stable, worked for me! 
```
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
```
