### ISSUE TITLE
Hi this my problems after update 

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#1942]
Traceback (most recent call last):
  File "john.py", line 25, in <module>
    session.login()
  File "/Users/jonathanverdier/Desktop/InstaPy/instapy/instapy.py", line 310, in login
    self.bypass_suspicious_attempt):
  File "/Users/jonathanverdier/Desktop/InstaPy/instapy/login_util.py", line 107, in login_user
    .format(logfolder,username), 'rb')):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 886, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3

**Comment by ellaprogrammer** [comment]
how did you fix this? @johnvfitness
