### ISSUE TITLE
Hi This my problem after update

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#1943]
Traceback (most recent call last):
  File "john.py", line 25, in <module>
    session.login()
  File "/Users/jonathanverdier/Desktop/InstaPy/instapy/instapy.py", line 317, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "/Users/jonathanverdier/Desktop/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage."
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'user' of undefined
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.13.4 x86_64)

**Comment by luigifaticoso** [comment]
Same here!

**Comment by eyupaltindal** [comment]
I have same too. I think it is a general bug because of Instagram's frontend changes.

**Comment by Nocturnal-2** [comment]
I am facing the same issue.

**Comment by johnvfitness** [comment]
last update its work its good ;)

**Comment by luigifaticoso** [comment]
still facing the same issue

**Comment by ghost** [comment]
also facing the same issue
