### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by patricmutwiri** [InstaPy/InstaPy#1944]
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'user' of undefined

**Comment by alatraxx** [comment]
I have the same issue

**Comment by redsector72** [comment]
They have updated the code for "fixing" something that is not for everyone.
If you have updated the code and it is no more working, do:
git reset --hard bc9f795ad48614b6688a50a830bb0c2fc6639942 and it will work again.
If you have not updated the code, then update with:
git pull

**Comment by alatraxx** [comment]
I've done a hard reset but nothing has changed.
`Traceback (most recent call last):
  File "C:\Users\Moris\Documents\GitHub\InstaPy\quickstart.py", line 39, in <module>
    session.unfollow_users(amount=200, onlyNotFollowMe=True, sleep_delay=600)
  File "C:\Users\Moris\Documents\GitHub\InstaPy\instapy\instapy.py", line 1640, in unfollow_users
    self.logfolder)
  File "C:\Users\Moris\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 202, in unfollow
    "return window._sharedData.entry_data.ProfilePage."
  File "C:\Users\Moris\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Moris\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Moris\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'user' of undefined
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.16299 x86_64)`

**Comment by luigifaticoso** [comment]
same problem also with last version

```
Traceback (most recent call last):
  File "cali.py", line 36, in <module>
    session.unfollow_users(amount=20, onlyNotFollowMe=True)
  File "/Users/luigicali/Proejcts/InstaPy/instapy/instapy.py", line 1640, in unfollow_users
    self.logfolder)
  File "/Users/luigicali/Proejcts/InstaPy/instapy/unfollow_util.py", line 202, in unfollow
    "return window._sharedData.entry_data.ProfilePage."
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'user' of undefined
  (Session info: headless chrome=66.0.3359.139)
  (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.13.4 x86_64)
```

**Comment by ghost** [comment]
same problem on my end

> File "/Users/piratze/Dropbox/InstaPy/instapy/instapy.py", line 1640, in unfollow_users
    self.logfolder)
  File "/Users/piratze/Dropbox/InstaPy/instapy/unfollow_util.py", line 202, in unfollow
    "return window._sharedData.entry_data.ProfilePage."
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'user' of undefined
  (Session info: chrome=67.0.3396.30)
  (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.13.5 x86_64)
