### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by 201504242** [InstaPy/InstaPy#1948]
It is running on a server:
* Ubuntu 14.04.5 LTS
* Python 2.7.6

but now I get an error and it does not work what could it be?

## Current Behavior

INFO [2018-05-02 17:12:06] [********]  Session started - 2018-05-02 17:12:06
INFO [2018-05-02 17:12:35] [********]  Logged in successfully!
^CTraceback (most recent call last):
  File "quickstart.py", line 64, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 493, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 78, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 131, in _run_job
    ret = job.run()
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 411, in run
    ret = self.job_func()
  File "quickstart.py", line 54, in unfollow
    session.end() 
  File "/home/pablo6a/InstaPy/instapy/instapy.py", line 1861, in end
    self.browser.delete_all_cookies()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 856, in delete_all_coo
kies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execut
e
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 489, in _reque
st
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1045, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python2.7/httplib.py", line 906, in putrequest
    raise CannotSendRequest()
httplib.CannotSendRequest

## InstaPy configuration

`session = InstaPy(username=use, password=pas,headless_browser=True)`
`        try:`
`                session.login()`
`                session.unfollow_users(amount=320, sleep_delay=500, unfollow_after=120*60*60)`
`        except Exception as exc:`
`           # if changes to IG layout, upload the file to help us locate the change`
`                if isinstance(exc, NoSuchElementException):`
`                        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-H%M%S')))`
`                        with open(file_path, 'wb') as fp:`
`                                fp.write(session.browser.page_source.encode('utf8'))`
`                print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(`
`                '*' * 70, file_path))`
`    # full stacktrace when raising Github issue`
`                raise`
`        finally:`
`                session.end() `

**Comment by uluQulu** [comment]
hi @201504242,
You seem to be an experienced pythonner;
Your quickstart script says something,
```powershell
session.unfollow_users(amount=320, sleep_delay=500, unfollow_after=120*60*60)
```
seems incomplete.
This is the `unfollow_users` method with formal arguments inside IstaPy class:
```powershell
unfollow_users(self,
                amount=10,
                 onlyInstapyFollowed=False,
                  onlyInstapyMethod='FIFO',
                   sleep_delay=600,
                    onlyNotFollowMe=False,
                     unfollow_after=None)
```
You should declare which unfollow method you want to use: `onlyInstapyFollowed` or `onlyNotFollowMe`?
Basically, if you want to use `unfollow_after` parameter, use `onlyInstapyFollowed` method, cos for now, it is supported only for that.
So, correct version should be:
```powershell
session.unfollow_users(amount=320, onlyInstapyFollowed=True, onlyInstapyMethod='FIFO', sleep_delay=500, unfollow_after=120*60*60)
```
> Choose 'FIFO' or 'LIFO' (_reversed user list_) as you wish (_see README_)

**Comment by 201504242** [comment]
Hi @uluQulu 
I only replaced the code that you gave me and it worked perfect, thanks
`session.unfollow_users(`
                            `              amount=320,` 
`onlyInstapyFollowed=True,` 
`onlyInstapyMethod='FIFO',`
 `sleep_delay=500,` 
 `unfollow_after=120*60*60)`
