### ISSUE TITLE
Unable to unfollow users

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1949]
## Expected Behavior
Ability to unfollow users
## Current Behavior
Program terminates
## InstaPy configuration

In my quickstart config, I have this function to unfollow people:

`    session.unfollow_users(amount=1000, onlyInstapyFollowed=False, onlyNotFollowMe=True, onlyInstapyMethod='FIFO',
                           sleep_delay=60, unfollow_after=48*60*60)`

Here is the error received:
Traceback (most recent call last):
  File "quickstart.py", line 51, in <module>
    sleep_delay=60, unfollow_after=48*60*60)
  File "/Users/aaa/Dropbox/InstaPy2/instapy/instapy.py", line 1640, in unfollow_users
    self.logfolder)
  File "/Users/aaa/Dropbox/InstaPy2/instapy/unfollow_util.py", line 202, in unfollow
    "return window._sharedData.entry_data.ProfilePage."
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'user' of undefined
  (Session info: chrome=67.0.3396.30)
  (Driver info: chromedriver=2.38.551581 (2c9c29527ada10af4745ab26dd000ebb6d5e055e),platform=Mac OS X 10.13.5 x86_64)

**Comment by uluQulu** [comment]
hi Mohammed,
_it seems you've pulled latest commits and page structure is still unstable_
But for your particular issue,
**replace**
```powershell
"return window._sharedData.entry_data.ProfilePage."
```
**with**
```powershell
"return window._sharedData.entry_data.ProfilePage[0]."   ##added [0]
```
For more information, you can revert all the removed `[0]` instances back after #1940 (_or simply `git revert` #1940 commit_), but page structure can be switched back any time, so follow the latest commits and #1936

**Comment by ghost** [comment]
Fixed by https://github.com/timgrossmann/InstaPy/pull/1954
