### ISSUE TITLE
not working TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by lamepost** [InstaPy/InstaPy#1951]
## Current Behavior
```
Traceback (most recent call last):
  File "index.py", line 17, in <module>
    session.like_by_tags(['puppy'], amount=100)
  File "/home/ale/InstaPy/instapy/instapy.py", line 957, in like_by_tags
    self.logger)
  File "/home/ale/InstaPy/instapy/like_util.py", line 461, in check_link
    media = post_page['media']
TypeError: list indices must be integers, not str
```

**Comment by ceribbo** [comment]
Same error here

**Comment by lamepost** [comment]
thx it work now after i clone https://github.com/joanroig/InstaPy
