### ISSUE TITLE
Problems, can't find a solution, that doesn't have it fixed allready, yet it is still happening

### ISSUE THREAD

**Issue by Emilbackhausen** [InstaPy/InstaPy#1953]
Traceback (most recent call last):
  File "quickstart.py", line 41, in <module>
    session.like_by_tags(['Landscapelovers'], amount=100)
  File "C:\Users\Emil Backhausen\Documents\InstaPy\instapy\instapy.py", line 957, in like_by_tags
    self.logger)
  File "C:\Users\Emil Backhausen\Documents\InstaPy\instapy\like_util.py", line 461, in check_link
    media = post_page['media']
TypeError: list indices must be integers or slices, not str

**Comment by uluQulu** [comment]
Hey @Emilbackhausen,
_the page structure has been unstable last days_
Hopefully there will soon a stable fix written.
For now, try using **with** and **without** [0] indexing for finding the live solution for yourself, just find the affected lines from this [sheet](https://github.com/timgrossmann/InstaPy/pull/1940/files)
