### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ' '

### ISSUE THREAD

**Issue by leon-h-a** [InstaPy/InstaPy#1957]
Traceback (most recent call last):
  File "quickstart.py", line 37, in <module>
    session.like_by_tags(['natgeo'], amount=1)
  File "/home/pi/InstaPy/instapy/instapy.py", line 985, in like_by_tags
    skip_top_posts)
  File "/home/pi/InstaPy/instapy/like_util.py", line 196, in get_links_for_tag
    "//span[contains(@class, '_fd86t')]").text)
  File "/home/pi/InstaPy/instapy/util.py", line 342, in format_number
    return int(formatted_num)
**ValueError: invalid literal for int() with base 10: ' '**

Do you understand what's going on here?

**Comment by uluQulu** [comment]
hi @Naponoel,
have a read https://github.com/timgrossmann/InstaPy/issues/1924#issuecomment-385247307 for solution

**Comment by leon-h-a** [comment]
@uluQulu 
Works! thanks! 🥇
