### ISSUE TITLE
load_follow_restriction

### ISSUE THREAD

**Issue by smhjamalii** [InstaPy/InstaPy#1978]
## Expected Behavior
python3.6 quickstart.py
## Current Behavior
Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    multi_logs=True)
  File "/home/InstaPy/instapy/instapy.py", line 119, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "/home/InstaPy/instapy/unfollow_util.py", line 893, in load_follow_restriction
    return json.load(followResFile)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 82 (char 81)

## InstaPy configuration
just as basic configuration plus this 

    session.set_do_follow(enabled=True, percentage=100, times=1)
    session.set_dont_unfollow_active_users(enabled=False, posts=2)
    session.like_by_feed(amount=100, randomize=True, unfollow=True, interact=True)

**Comment by uluQulu** [comment]
hi @smhjamali,
Have a read this https://github.com/timgrossmann/InstaPy/issues/1732#issuecomment-383390727, it would help.

**Comment by smhjamalii** [comment]
resolved by removing logs folder
