### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by iransales** [InstaPy/InstaPy#2018]
HELP! I was running the boot normally. But after I rebooted the computer appears this error.

C:\Users\iran\Desktop\InstaPy-master\InstaPy-master>python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "C:\Users\iran\Desktop\InstaPy-master\InstaPy-master\instapy\instapy.py", line 121, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "C:\Users\iran\Desktop\InstaPy-master\InstaPy-master\instapy\unfollow_util.py", line 895, in load_follow_restriction
    return json.load(followResFile)
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 8208 (char 8207)

**Comment by uluQulu** [comment]
Hi!
Have a read https://github.com/timgrossmann/InstaPy/issues/1732#issuecomment-383390727 to solve it.

**Comment by Dankartpage** [comment]
I have the same error, I'll check the post above
