### ISSUE TITLE
Raspberry Pi 3 with Kali Linux Issue

### ISSUE THREAD

**Issue by Mehran** [InstaPy/InstaPy#2020]
## Expected Behavior
Script not run
## Current Behavior
```
python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password, nogui=True)
  File "/root/InstaPy/instapy/instapy.py", line 170, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 276, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
```
## InstaPy configuration

from instapy import InstaPy

insta_username = 'xxxxx'
insta_password = 'xxxxx'

session = InstaPy(username=insta_username, password=insta_password)
session.login()

session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)

session.set_do_comment(True, percentage=10)
session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
session.set_dont_include(['friend1', 'friend2', 'friend3'])
session.set_dont_like(['pizza', 'girl'])

session.like_by_tags(['natgeo', 'world'], amount=100)

session.end()

**Comment by Mehran** [comment]
but with firefox its okey
