### ISSUE TITLE
Someone Help

### ISSUE THREAD

**Issue by iransales** [InstaPy/InstaPy#2022]
I have this error when I try to run

DevTools listening on ws://127.0.0.1:12458/devtools/browser/f2000fed-48ab-43fe-8c4e-19fe58904686
INFO [2018-05-14 23:59:23] [projetando3d]  Session started - 2018-05-14 23:59:23
WARNING [2018-05-14 23:59:23] [projetando3d]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO [2018-05-14 23:59:55] [projetando3d]  Logged in successfully!
[14772:8660:0514/235958.160:ERROR:broker_win.cc(57)] Error reading broker pipe: O pipe foi finalizado. (0x6D)
INFO [2018-05-15 00:00:01] [projetando3d]  Session ended - 2018-05-15 00:00:01
INFO [2018-05-15 00:00:01] [projetando3d]  --------------------

Traceback (most recent call last):
  File "C:\Users\iran\Desktop\InstaPy-master - Copia\InstaPy-master\quickstart.py", line 27, in <module>
    session.follow_commenters(['renderexpress'], amount=100, daysold=365, max_pic = 100, sleep_delay=600, interact=False)
TypeError: follow_commenters() got an unexpected keyword argument 'sleep_delay'

**Comment by uluQulu** [comment]
Use latest files where `sleep_delay` and `interact` parameters are added to the `follow_commenters` feature.

**Comment by iransales** [comment]
now I have this erro

Microsoft Windows [versão 10.0.16299.431]
(c) 2017 Microsoft Corporation. Todos os direitos reservados.

C:\Users\iran>virtualenv venv
'virtualenv' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\Users\iran>cd C:\Users\iran\Desktop\InstaPy-master\InstaPy-master

C:\Users\iran\Desktop\InstaPy-master\InstaPy-master>python quickstart.py
ERROR [2018-05-15 13:31:24] [projetando3d]  Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Traceback (most recent call last):
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\iran\Desktop\InstaPy-master\InstaPy-master\instapy\instapy.py", line 276, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in __init__
    self.service.start()
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Traceback (most recent call last):
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\iran\Desktop\InstaPy-master\InstaPy-master\instapy\instapy.py", line 276, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in __init__
    self.service.start()
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "C:\Users\iran\Desktop\InstaPy-master\InstaPy-master\instapy\instapy.py", line 170, in __init__
    self.set_selenium_local_session()
  File "C:\Users\iran\Desktop\InstaPy-master\InstaPy-master\instapy\instapy.py", line 280, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at C:\Users\iran\Desktop\InstaPy-master\InstaPy-master\assets\chromedriver
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x05FEB690>>
Traceback (most recent call last):
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 163, in __del__
    self.stop()
  File "C:\Users\iran\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 135, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'

C:\Users\iran\Desktop\InstaPy-master\InstaPy-master>

**Comment by uluQulu** [comment]
Make sure chromedriver executable- `chromedriver.exe` is in **assets** folder

**Comment by iransales** [comment]
is not. What should I do?

**Comment by uluQulu** [comment]
Download chromedriver by clicking this [link](https://chromedriver.storage.googleapis.com/2.38/chromedriver_win32.zip) and extract the executable `.exe` file and put into **assets** folder
_see README- Installation section for more instructions_

**Comment by iransales** [comment]
now this:

Microsoft Windows [versão 10.0.16299.431]
(c) 2017 Microsoft Corporation. Todos os direitos reservados.

C:\Users\iran>cd
C:\Users\iran

C:\Users\iran>cd C:\Users\iran\Desktop\InstaPy-master\InstaPy-master

C:\Users\iran\Desktop\InstaPy-master\InstaPy-master>python quickstart - Copia.py
python: can't open file 'quickstart': [Errno 2] No such file or directory

C:\Users\iran\Desktop\InstaPy-master\InstaPy-master>

**Comment by uluQulu** [comment]
It is a typical Windows command prompt issue.
Your quickstart file has `2` whitespaces in its name which must be escaped (_with **double quotes**_) and when you run without escaping,
```powershell
python quickstart - Copia.py
```
it gets only the first `quickstart` part and skips ` - Copia.py` part which is what misbehaving.

**To solve** it, `run`
```powershell
python "quickstart - Copia.py"
```
**or**
```powershell
python quickstart" - "Copia.py
```
**or** even
```powershell
python quickstart" "-" "Copia.py
```
_But better is to just type,_
```powershell
python quickstart
```
_and then press `Tab` key until it brings the correct file, "quickstart - Copia.py" and then hit Enter._

**Comment by iransales** [comment]
another error :/

Microsoft Windows [versão 10.0.16299.431]
(c) 2017 Microsoft Corporation. Todos os direitos reservados.

C:\Users\iran>cd
C:\Users\iran

C:\Users\iran>cd C:\Users\iran\Desktop\InstaPy-master\InstaPy-master

C:\Users\iran\Desktop\InstaPy-master\InstaPy-master>python iransales.py
  File "iransales.py", line 30
    session.set_do_like(enabled=True, percentage=70)
          ^
SyntaxError: invalid syntax

C:\Users\iran\Desktop\InstaPy-master\InstaPy-master>

**Comment by uluQulu** [comment]
Zip and attach **that** quickstart file.  
I will look (_don't forget to remove personal credentials_).

**Comment by iransales** [comment]
[iransales.zip](https://github.com/timgrossmann/InstaPy/files/2019729/iransales.zip)

**Comment by uluQulu** [comment]
In python indentation is crucial,
```python
##some code
try:
    session.login()



##settings
session.set_do_like(enabled=True, percentage=70)

session.set_do_comment(enabled=True, percentage=10)
session.set_comments(comments=['cool', 'dope'], media='Photo')

session.set_user_interact(amount=10, percentage=100, randomize=False, media='Photo')

##actions
session.follow_commenters(['user1'], amount=10, daysold=10, max_pic=7, sleep_delay=60, interact=True)



except Exception as exc:
```

Correct the indentation of lines between `try` and `except`
##some other code
```python
##some code
try:
    session.login()



    ##settings
    session.set_do_like(enabled=True, percentage=70)

    session.set_do_comment(enabled=True, percentage=10)
    session.set_comments(comments=['cool', 'dope'], media='Photo')

    session.set_user_interact(amount=10, percentage=100, randomize=False, media='Photo')

    ##actions
    session.follow_commenters(['user1'], amount=10, daysold=10, max_pic=7, sleep_delay=60, interact=True)



except Exception as exc:
##some other code
```

**Comment by iransales** [comment]
thank you!! It's working now, but I still have not understood the reason for the error. You are great

**Comment by iransales** [comment]
Now this

DevTools listening on ws://127.0.0.1:12733/devtools/browser/c51a4ffb-82a1-4a6d-ba0c-064e9f4474fa
INFO [2018-05-19 16:17:00] [projetando3d]  Session started - 2018-05-19 16:17:00
WARNING [2018-05-19 16:17:00] [projetando3d]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
[13472:1364:0519/161706.553:ERROR:shader_disk_cache.cc(238)] Failed to create shader cache entry: -2
INFO [2018-05-19 16:17:38] [projetando3d]  Logged in successfully!
INFO [2018-05-19 16:17:40] [projetando3d]  Starting to follow commenters..
INFO [2018-05-19 16:17:40] [projetando3d]  Following commenters of 'renderexpress' from pictures in last 10 days...
Scrapping wall..

Error: Couldn't get user profile. Moving on..
INFO [2018-05-19 16:18:06] [projetando3d]  Noone commented, noone to follow.

INFO [2018-05-19 16:18:07] [projetando3d]  Finished following commenters!

[10488:12588:0519/161809.102:ERROR:broker_win.cc(57)] Error reading broker pipe: O pipe foi finalizado. (0x6D)
INFO [2018-05-19 16:18:12] [projetando3d]  Session ended - 2018-05-19 16:18:12
INFO [2018-05-19 16:18:12] [projetando3d]  --------------------
