### ISSUE TITLE
Chromedriver not in PATH

### ISSUE THREAD

**Issue by thiswayalice** [InstaPy/InstaPy#2023]
Hi, when I try to run it I get this error. Chromedriver is in the assets file though, so I don't get it.

```
ERROR [2018-05-15 14:06:36] [xf]  Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Traceback (most recent call last):
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg\instapy\instapy.py", line 276, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in __init__
    self.service.start()
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Traceback (most recent call last):
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg\instapy\instapy.py", line 276, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in __init__
    self.service.start()
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 5, in <module>
    session = InstaPy(username='someusername', password='somepassword')
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg\instapy\instapy.py", line 170, in __init__
    self.set_selenium_local_session()
  File "C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg\instapy\instapy.py", line 280, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg\assets\chromedriver
```

Maybe it has something to do with this issue regarding versions of the requirements 

```
Requirement already satisfied: selenium in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 1)) (3.5.0)
Requirement already satisfied: clarifai in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages\clarifai-2.0.32-py3.6.egg (from -r requirements.txt (line 2)) (2.0.32)
Requirement already satisfied: pyvirtualdisplay in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 3)) (0.2.1)
Requirement already satisfied: emoji in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages\emoji-0.4.5-py3.6.egg (from -r requirements.txt (line 4)) (0.4.5)
Requirement already satisfied: GitPython in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 5)) (2.1.9)
Requirement already satisfied: future==0.15.2 in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from clarifai->-r requirements.txt (line 2)) (0.15.2)
Requirement already satisfied: requests==2.13.0 in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from clarifai->-r requirements.txt (line 2)) (2.13.0)
Requirement already satisfied: configparser==3.5.0 in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from clarifai->-r requirements.txt (line 2)) (3.5.0)
Requirement already satisfied: jsonschema==2.5.1 in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from clarifai->-r requirements.txt (line 2)) (2.5.1)
Requirement already satisfied: enum34==1.1.6 in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from clarifai->-r requirements.txt (line 2)) (1.1.6)
Collecting Pillow==2.9.0 (from clarifai->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/62/7d/a6decd77e926197621ca13f63e4f37333a462e1be18a8b5928b692f7ae24/Pillow-2.9.0.tar.gz
Requirement already satisfied: EasyProcess in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from pyvirtualdisplay->-r requirements.txt (line 3)) (0.2.3)
Requirement already satisfied: gitdb2>=2.0.0 in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from GitPython->-r requirements.txt (line 5)) (2.0.3)
Requirement already satisfied: smmap2>=2.0.0 in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from gitdb2>=2.0.0->GitPython->-r requirements.txt (line 5)) (2.0.3)
Building wheels for collected packages: Pillow
  Running setup.py bdist_wheel for Pillow ... error
  Complete output from command c:\users\alexandre\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\pip-install-d5515kx0\\Pillow\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\ALEXAN~1\AppData\Local\Temp\pip-wheel-rnd0sezt --python-tag cp36:
  Single threaded build, not installing mp_compile: 4 processes
[...]
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

  ----------------------------------------
  Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
instagram-py 0.0.1 has requirement selenium==2.53.6, but you'll have selenium 3.5.0 which is incompatible.
Installing collected packages: Pillow
  Found existing installation: pillow 5.1.0
    Uninstalling pillow-5.1.0:
      Successfully uninstalled pillow-5.1.0
  Running setup.py install for Pillow ... error
    Complete output from command c:\users\alexandre\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\pip-install-d5515kx0\\Pillow\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ALEXAN~1\AppData\Local\Temp\pip-record-f9rx5qky\install-record.txt --single-version-externally-managed --compile:
    Single threaded build, not installing mp_compile: 4 processes
[...]
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
  Rolling back uninstall of pillow
Command "c:\users\alexandre\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\pip-install-d5515kx0\\Pillow\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ALEXAN~1\AppData\Local\Temp\pip-record-f9rx5qky\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ALEXAN~1\AppData\Local\Temp\pip-install-d5515kx0\Pillow\
```

Any help ?

**Comment by uluQulu** [comment]
Wow, @thiswayalice, lots of log information! 🎋 
Is _chromedriver_ `unzip`ped in the **assets** folder?

**Comment by thiswayalice** [comment]
Yes of course.
I've also run the windows in the scripts file afterward to make sure. Still not working

**Comment by uluQulu** [comment]
@thiswayalice, change your password and never share it in public!
It is weird, but if `chromedriver.exe` executable is in **assets** folder, it should not give that error.
_but if you provide more details on how you did do installation, I can guess a few ways_

**Comment by thiswayalice** [comment]
I simply followed every steps from this [page ](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Windows.md) except the 4. Edit the instapy.py file., couldn't find how to do it.

_Edited my original post, too many logs indeed. Password changed._

**Comment by uluQulu** [comment]
@thiswayalice,
That set of instructions is conflicting with each other.
Now I would recommend you to remove old Instapy folder and start again with the best methods!
_if you want to continue, remove your previous InstaPy folder AND install Github Desktop, then tell me_

**Comment by thiswayalice** [comment]
So I've removed everything and reinstalled it with the simple setup.
But when I run windows.ps1 I get some errors. Chromedriver do get installed though, but still not in path.

```
InstaPy Windows Setup
Installing Selenium
Requirement already satisfied: selenium in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (3.5.0)
instagram-py 0.0.1 has requirement selenium==2.53.6, but you'll have selenium 3.5.0 which is incompatible.
clarifai 2.0.32 has requirement Pillow==2.9.0, but you'll have pillow 5.1.0 which is incompatible.
Requirement already satisfied: pyvirtualdisplay in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (0.2.1)
Requirement already satisfied: EasyProcess in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from pyvirtualdisplay) (0.2.3)
instagram-py 0.0.1 has requirement selenium==2.53.6, but you'll have selenium 3.5.0 which is incompatible.
clarifai 2.0.32 has requirement Pillow==2.9.0, but you'll have pillow 5.1.0 which is incompatible.
C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\python.exe: can't open file 'get-pip.py': [Errno 2] No such file or directory

Installing GUI Tool
Exception lors de l'appel de «DownloadFile» avec «2» argument(s): «La demande a été abandonnée: Impossible de créer un canal sécurisé SSL/TLS.»
Au caractère C:\Users\Alexandre\Documents\GitHub\InstaPy\scripts\windows.ps1:10 : 1
 $webclient.DownloadFile(//github.com/Nemixalone/GUI-tool-for-I ...
 CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
 FullyQualifiedErrorId : WebException

mv : Impossible de trouver le chemin d'accès «C:\Users\Alexandre\Documents\GitHub\InstaPy\scripts\InstaPy-GUI.exe»,
car il n'existe pas Au caractère C:\Users\Alexandre\Documents\GitHub\InstaPy\scripts\windows.ps1:11 : 1
 mv "$pwd\InstaPy-GUI.exe" "$pwd\..\InstaPy-GUI.exe"
 CategoryInfo          : ObjectNotFound: (C:\Users\Alexan...InstaPy-GUI.exe:String) [Move-Item], ItemNotFoundException
  FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand


Downloading Chrome Driver...
Chrome Driver download completed.

Unzipping Chrome Driver...
Unzipping completed.

Removing unneeded files...
Removal completed.

running install
running bdist_egg
running egg_info
creating instagram_py.egg-info
writing instagram_py.egg-info\PKG-INFO
writing dependency_links to instagram_py.egg-info\dependency_links.txt
writing requirements to instagram_py.egg-info\requires.txt
writing top-level names to instagram_py.egg-info\top_level.txt
writing manifest file 'instagram_py.egg-info\SOURCES.txt'
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
reading manifest file 'instagram_py.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'instagram_py.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
creating build
creating build\lib
creating build\lib\instapy
copying instapy\clarifai_util.py -> build\lib\instapy
copying instapy\commenters_util.py -> build\lib\instapy
copying instapy\comment_util.py -> build\lib\instapy
copying instapy\feed_util.py -> build\lib\instapy
copying instapy\instapy.py -> build\lib\instapy
copying instapy\like_util.py -> build\lib\instapy
copying instapy\login_util.py -> build\lib\instapy
copying instapy\print_log_writer.py -> build\lib\instapy
copying instapy\settings.py -> build\lib\instapy
copying instapy\time_util.py -> build\lib\instapy
copying instapy\unfollow_util.py -> build\lib\instapy
copying instapy\util.py -> build\lib\instapy
copying instapy\__init__.py -> build\lib\instapy
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
creating build\bdist.win32
creating build\bdist.win32\egg
creating build\bdist.win32\egg\instapy
copying build\lib\instapy\clarifai_util.py -> build\bdist.win32\egg\instapy
copying build\lib\instapy\commenters_util.py -> build\bdist.win32\egg\instapy
copying build\lib\instapy\comment_util.py -> build\bdist.win32\egg\instapy
copying build\lib\instapy\feed_util.py -> build\bdist.win32\egg\instapy
copying build\lib\instapy\instapy.py -> build\bdist.win32\egg\instapy
copying build\lib\instapy\like_util.py -> build\bdist.win32\egg\instapy
copying build\lib\instapy\login_util.py -> build\bdist.win32\egg\instapy
copying build\lib\instapy\print_log_writer.py -> build\bdist.win32\egg\instapy
copying build\lib\instapy\settings.py -> build\bdist.win32\egg\instapy
copying build\lib\instapy\time_util.py -> build\bdist.win32\egg\instapy
copying build\lib\instapy\unfollow_util.py -> build\bdist.win32\egg\instapy
copying build\lib\instapy\util.py -> build\bdist.win32\egg\instapy
copying build\lib\instapy\__init__.py -> build\bdist.win32\egg\instapy
byte-compiling build\bdist.win32\egg\instapy\clarifai_util.py to clarifai_util.cpython-36.pyc
byte-compiling build\bdist.win32\egg\instapy\commenters_util.py to commenters_util.cpython-36.pyc
byte-compiling build\bdist.win32\egg\instapy\comment_util.py to comment_util.cpython-36.pyc
byte-compiling build\bdist.win32\egg\instapy\feed_util.py to feed_util.cpython-36.pyc
byte-compiling build\bdist.win32\egg\instapy\instapy.py to instapy.cpython-36.pyc
byte-compiling build\bdist.win32\egg\instapy\like_util.py to like_util.cpython-36.pyc
byte-compiling build\bdist.win32\egg\instapy\login_util.py to login_util.cpython-36.pyc
byte-compiling build\bdist.win32\egg\instapy\print_log_writer.py to print_log_writer.cpython-36.pyc
byte-compiling build\bdist.win32\egg\instapy\settings.py to settings.cpython-36.pyc
byte-compiling build\bdist.win32\egg\instapy\time_util.py to time_util.cpython-36.pyc
byte-compiling build\bdist.win32\egg\instapy\unfollow_util.py to unfollow_util.cpython-36.pyc
byte-compiling build\bdist.win32\egg\instapy\util.py to util.cpython-36.pyc
byte-compiling build\bdist.win32\egg\instapy\__init__.py to __init__.cpython-36.pyc
creating build\bdist.win32\egg\EGG-INFO
copying instagram_py.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying instagram_py.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying instagram_py.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying instagram_py.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying instagram_py.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
instapy.__pycache__.settings.cpython-36: module references __file__
creating dist
creating 'dist\instagram_py-0.0.1-py3.6.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing instagram_py-0.0.1-py3.6.egg
removing 'c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg' (and everything under it)
creating c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg
Extracting instagram_py-0.0.1-py3.6.egg to c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages
instagram-py 0.0.1 is already the active version in easy-install.pth

Installed c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg
Processing dependencies for instagram-py==0.0.1
Searching for Pillow==2.9.0
Reading https://pypi.python.org/simple/Pillow/
C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\setuptools\pep425tags.py:89: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\setuptools\pep425tags.py:93: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
Downloading https://files.pythonhosted.org/packages/62/7d/a6decd77e926197621ca13f63e4f37333a462e1be18a8b5928b692f7ae24/Pillow-2.9.0.tar.gz#sha256=0f179d7e75e7c83b6341b9595ca1f394de7081484a9e352ad66d553a1c3daa29
Best match: Pillow 2.9.0
Processing Pillow-2.9.0.tar.gz
Writing C:\Users\ALEXAN~1\AppData\Local\Temp\easy_install-c04eyy35\Pillow-2.9.0\setup.cfg
Running Pillow-2.9.0\setup.py -q bdist_egg --dist-dir C:\Users\ALEXAN~1\AppData\Local\Temp\easy_install-c04eyy35\Pillow-2.9.0\egg-dist-tmp-ugjut5z6
Single threaded build, not installing mp_compile: 4 processes
error: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
Setup is completed.
````

**Comment by uluQulu** [comment]
I will repeat again, @thiswayalice 😅,
That set of instructions is conflicting with each other.
Now I would recommend you to remove old Instapy folder and start again with the best methods!
_if you want to continue, remove your previous InstaPy folder AND install Github Desktop, then tell me_

Note: make sure you have done step `0`, `1` and `2` in that page AND don't touch other steps (_remove whatever you have downloaded those other steps_)

**Comment by thiswayalice** [comment]
Ah sorry I guess my brain cells also got conflicted.
Previous folder removed and Github installed, and these steps are done.

**Comment by uluQulu** [comment]
Super @thiswayalice,
1. Open up https://github.com/timgrossmann/InstaPy/ in your web browser and click on `Clone or download` button
2. Choose `Open in Desktop` to clone it into your GitHub Desktop app
3. After cloning it, take a good cup of tea and give some feedback to me :P
>By using GitHub Desktop app, you will have the best open-source experience and it will help you pull new updates with ease!

_Also, if you would like, install Atom text editor (_written by Github_) which is one of the best editors to work with Git and GitHub that you shall use_

**Comment by thiswayalice** [comment]
It seems like a good interface I reckon, but how is this helping with my
issue ?

**Comment by uluQulu** [comment]
Well @thiswayalice,
Barely looking at this,
```erlang
instapy.instapy.InstaPyError: ensure chromedriver is installed at C:\Users\Alexandre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg\assets\chromedriver
```
you have had an installation issue.

Anyways, I was just trying to help you with a good method I used.
Good luck!
