### ISSUE TITLE
unfollow issue

### ISSUE THREAD

**Issue by Mehran** [InstaPy/InstaPy#2026]
## Current Behavior
```
ERROR [2018-05-15 15:21:56] [xxxxx]  following_link error list index out of range
Traceback (most recent call last):
  File "/root/InstaPy/quickstart.py", line 43, in <module>
    session.unfollow_users(amount=15, onlyInstapyFollowed =False, onlyInstapyMethod = 'FIFO', sleep_delay=60)
  File "/root/InstaPy/instapy/instapy.py", line 1840, in unfollow_users
    self.logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 327, in unfollow
    "//div[text()='Following']/following-sibling::div")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 385, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 955, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Following']/following-sibling::div"}
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.4.0-124-generic x86_64)

INFO [2018-05-15 15:22:23] [xxxxxx]  Session ended - 2018-05-15 15:22:23
INFO [2018-05-15 15:22:23] [xxxxxx]  --------------------
```
## InstaPy configuration
  
    session.unfollow_users(amount=15, onlyInstapyFollowed =False, onlyInstapyMethod = 'FIFO', sleep_delay=60)

**Comment by fgisslen** [comment]
Same error

**Comment by gitpatrickhub** [comment]
Same issue as #1977

**Comment by ghost** [comment]
I have the same issue. I updated chromedriver and it didn't fix it. I think they changed the element for the following list.

**Comment by uluQulu** [comment]
Hi @bretie,
Please see https://github.com/timgrossmann/InstaPy/issues/2031#issuecomment-389608594 for solution.
