### ISSUE TITLE
Instapy crashes on set_dont_unfollow_active_users 

### ISSUE THREAD

**Issue by koenvdlist** [InstaPy/InstaPy#2039]
## Expected Behavior
Instapy counts active users correctly and does not unfollow them. 

## Current Behavior

DevTools listening on ws://127.0.0.1:12982/devtools/browser/29c8703b-7b69-4d56-8e11-e26aba37944d
INFO [2018-05-17 17:48:37] [koekoeksklokonline.nl]  Session started - 2018-05-17 17:48:37
WARNING [2018-05-17 17:48:37] [koekoeksklokonline.nl]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO [2018-05-17 17:49:33] [koekoeksklokonline.nl]  Logged in successfully!
INFO [2018-05-17 17:49:47] [koekoeksklokonline.nl]  Getting active users who liked the latest 5 posts:
  ~collecting the usernames from posts with the boundary of 500

INFO [2018-05-17 17:49:54] [koekoeksklokonline.nl]  Session ended - 2018-05-17 17:49:54
INFO [2018-05-17 17:49:54] [koekoeksklokonline.nl]  --------------------

Traceback (most recent call last):
  File "C:\Users\User\OneDrive\Koekoeksklok\Instagram\automation\InstaPy-master\InstaPy-master\quickstart.py", line 30, in <module>
    session.set_dont_unfollow_active_users(enabled=True, posts=5)
  File "C:\Users\User\OneDrive\Koekoeksklok\Instagram\automation\InstaPy-master\InstaPy-master\instapy\instapy.py", line 2072, in set_dont_unfollow_active_users
    self.logger)
  File "C:\Users\User\OneDrive\Koekoeksklok\Instagram\automation\InstaPy-master\InstaPy-master\instapy\util.py", line 130, in get_active_users
    "//a[contains(@class, '_nzn1h')]/span").text)
  File "C:\Users\User\OneDrive\Koekoeksklok\Instagram\automation\InstaPy-master\InstaPy-master\instapy\util.py", line 342, in format_number
    return int(formatted_num)
ValueError: invalid literal for int() with base 10: ''

## Possible Solution (optional)
Might be related to #1924, as  ValueError is the same. However, the error exists due to   session.set_dont_unfollow_active_users instead of like_by_tags.

**Comment by uluQulu** [comment]
hi @koenvdlist,
#2042 should solve this.
