### ISSUE TITLE
Was able to run InstaPy old version, reinstalled and cant get to work again

### ISSUE THREAD

**Issue by Amber-Williams** [InstaPy/InstaPy#2040]
## Expected Behavior
Typed cd InstaPy then python quickstart.py to run program as usual and it wouldn't run. I redownloaded InstaPy from the GitHub repository then changed my quickstart.py to match the old version. Seems as though it can't find selenium? 

Error message from terminal is below.

Thanks!

## Current Behavior

ERROR [2018-05-17 12:23:37] [amberbombcom]  Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Traceback (most recent call last):
  File "/Users/margee/InstaPy/instapy/instapy.py", line 276, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/Users/margee/InstaPy/instapy/instapy.py", line 170, in __init__
    self.set_selenium_local_session()
  File "/Users/margee/InstaPy/instapy/instapy.py", line 280, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /Users/margee/InstaPy/assets/chromedriver
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x10a5c9bd0>> ignored
Neriums-Mac-mini:InstaPy margee$ ERROR [2018-05-17 12:23:37] [amberbombcom]  Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Traceback (most recent call last):
  File "/Users/margee/InstaPy/instapy/instapy.py", line 276, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/Users/margee/InstaPy/instapy/instapy.py", line 170, in __init__
    self.set_selenium_local_session()
  File "/Users/margee/InstaPy/instapy/instapy.py", line 280, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /Users/margee/InstaPy/assets/chromedriver
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x10a5c9bd0>> ignored
Neriums-Mac-mini:InstaPy margee$ 

## Possible Solution (optional)
uninstall selenium and reinstall maybe. Not sure where its located though.

**Comment by Amber-Williams** [comment]
Just needed to install new version of chromedriver and place in assets
