### ISSUE TITLE
No such Element: Unable to locate element

### ISSUE THREAD

**Issue by agcty** [InstaPy/InstaPy#2044]
I got the following error:

Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Following']/following-sibling::div"}
  (Session info: headless chrome=63.0.3239.84)
  (Driver info: chromedriver=2.33 (undefined),platform=Linux 4.14.34-v7+ armv7l)

If needed I can supply my config

**Comment by agcty** [comment]
Here's a more verbose log 
```
ERROR [2018-05-17 10:37:47] [user]  following_link error list index out of range
Traceback (most recent call last):
  File "quickstart.py", line 33, in <module>
    session.unfollow_users(amount=20)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 1835, in unfollow_users
    self.logfolder)
  File "/home/pi/Projects/InstaPy/instapy/unfollow_util.py", line 327, in unfollow
    "//div[text()='Following']/following-sibling::div")
  File "/home/pi/Projects/InstaPy/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/pi/Projects/InstaPy/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/home/pi/Projects/InstaPy/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/pi/Projects/InstaPy/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Following']/following-sibling::div"}
  (Session info: headless chrome=63.0.3239.84)
  (Driver info: chromedriver=2.33 (undefined),platform=Linux 4.14.34-v7+ armv7l)
```

**Comment by uluQulu** [comment]
Hi @agcty,
Please see #2042 to solve your issue.
