### ISSUE TITLE
function like_by_tags

### ISSUE THREAD

**Issue by ThomasViennet-zz** [InstaPy/InstaPy#2047]
Hi
I need your help.

The function like_by_tags doesn't work with me.
I have this traceback `
Traceback (most recent call last):
  File "quickstart.py", line 70, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 493, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 78, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 131, in _run_job
    ret = job.run()
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 411, in run
    ret = self.job_func()
  File "quickstart.py", line 40, in job
    session.like_by_tags(['miaoubox', 'world'], amount=10, interact=True)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 1082, in like_by_tags
    skip_top_posts)
  File "/home/pi/Projects/InstaPy/instapy/like_util.py", line 197, in get_links_for_tag
    "//span[contains(@class, '_fd86t')]").text)
  File "/home/pi/Projects/InstaPy/instapy/util.py", line 342, in format_number
    return int(formatted_num)
ValueError: invalid literal for int() with base 10: ''`

and it's my quickstart : 
`
session.login()

        # settings
        session.set_relationship_bounds(enabled=False,)
        session.set_user_interact(amount=4, randomize=True, percentage=100)
        session.set_do_follow(enabled=True, percentage=100, times=5)
        session.set_do_like(enabled=True, percentage=100)
        session.set_do_comment(True, percentage=25)
        session.set_comments(['Je suis fan @{} !', 'Magnifique', 'Superbe', 'Top !', 'Ton compte instagram est vraiment top @{} !'])

        # actions
        session.interact_user_followers(['natgeo'], amount=10, randomize=False)
        session.like_by_tags(['natgeo', 'world'], amount=10, interact=True)
        session.unfollow_users(amount=20, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=600, unfollow_after=2*24*60*60)`

Thank for your help.

**Comment by uluQulu** [comment]
hi @ThomasViennet,
Please see #2042, it should solve your problem.

**Comment by ThomasViennet-zz** [comment]
Sorry I don't understand what I need to do to solves this problem.
Can you explain me please ?

**Comment by uluQulu** [comment]
@ThomasViennet,
Sure, you can apply the easy modification in https://github.com/timgrossmann/InstaPy/issues/1924#issuecomment-385247307 for temporary workaround until #2042 gets merged.

**Comment by ThomasViennet-zz** [comment]
thanks it work !
