### ISSUE TITLE
errno 13 permission denied

### ISSUE THREAD

**Issue by aku6640** [InstaPy/InstaPy#2048]
## Current Behavior
Traceback (most recent call last):
  File "custom.py", line 25, in <module>
    multi_logs=True)
  File "/home/pi/InstaPy/instapy/instapy.py", line 165, in __init__
    self.logger = self.get_instapy_logger(show_logs)
  File "/home/pi/InstaPy/instapy/instapy.py", line 187, in get_instapy_logger
    file_handler = logging.FileHandler('{}general.log'.format(self.logfolder))
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/home/pi/InstaPy/logs/username/general.log'

I am getting this error, maybe someone could help out?

**Comment by uluQulu** [comment]
@aku6640,
Does your user accaunt have `read`/`write` privilege to that `logs` _folder_ and particularly `general.log` file in it?

**Comment by aku6640** [comment]
Hi uluQulu! 

i have done chmod -R 777 InstaPy on the InstaPy directory, that should be enough?

**Comment by uluQulu** [comment]
@aku6640,
_I am not really familiar with Linux commands but Internet has lots of information on it to find easily_
It was just a suggestion, I am not very sure about that issue but also try to rename `general.log` to sth different, e.g., `general_old.log`

**Comment by aku6640** [comment]
I've changed the name to general_old.log but when i run python.custom.py it gives the same error: 

Traceback (most recent call last):
  File "custom.py", line 25, in <module>
    multi_logs=True)
  File "/home/pi/InstaPy/instapy/instapy.py", line 165, in __init__
    self.logger = self.get_instapy_logger(show_logs)
  File "/home/pi/InstaPy/instapy/instapy.py", line 187, in get_instapy_logger
    file_handler = logging.FileHandler('{}general.log'.format(self.logfolder))
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/home/pi/InstaPy/logs/user/general.log'

**Comment by aku6640** [comment]
sudo python fixed the issue thanks again uluQ! Hope that it keeps working now and not stops after a while.

**Comment by uluQulu** [comment]
Is clear now @aku6640,
I think you can write a new alias for it to ease of typing
```erlang
alias py="sudo python"
```
in your `.profile ` (_for **ksh**, **bash**_) or `.login` (_for **csh**_) file
