### ISSUE TITLE
Running error suddenly occurring, no previous issue with script

### ISSUE THREAD

**Issue by Dankartpage** [InstaPy/InstaPy#2073]
Script has been working perfectly fine for weeks until now, here's the traceback.

$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "C:\users\username\instapy\instapy\instapy.py", line 119, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "C:\users\username\instapy\instapy\unfollow_util.py", line 822, in load_f                                         ollow_restriction
    return json.load(followResFile)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36-32\lib\json\__i                                         nit__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36-32\lib\json\__i                                         nit__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36-32\lib\json\dec                                         oder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36-32\lib\json\dec                                         oder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

(edit: tried to update the files by doing git pull before posting this issue)

**Comment by Dankartpage** [comment]
Found solution:

"It possibly happened after you've forcibly ended some session where it corruptly dumped data to JSON file,
for solution, either find that corrupt element in followRestriction.json file and fix it or just reset that file (keep only this in there: {})

note that followRestriction.json file keeps records to be used with follow_times parameter"

Solved by deleting followrestiction.json file (attempting to git pull to replace it, but don't think this made any difference) and starting up the script again, works fine now. thanks alot to @uluQulu
