### ISSUE TITLE
Like_by_tags, too few images, no such element

### ISSUE THREAD

**Issue by kenstowe** [InstaPy/InstaPy#2087]
Started today when I try to like_by_tags I get the error message that there are too few images. All tags have over 50000 images and I am only asking for 3 images. Issue is consistent and every tag fails. 

I tested with multiple instagram accounts, two different computers, two internet connections, and a fresh install of instapy. The issue continues.  

Error message:
```
INFO [2018-05-23 21:44:25] [sliceofstacy]  Session started - 2018-05-23 21:44:25
INFO [2018-05-23 21:44:57] [sliceofstacy]  Logged in successfully!
INFO [2018-05-23 21:44:59] [sliceofstacy]  Tag [1/6]
INFO [2018-05-23 21:44:59] [sliceofstacy]  --> b'stylecollective'
INFO [2018-05-23 21:45:28] [sliceofstacy]  Too few images, skipping this tag
INFO [2018-05-23 21:45:28] [sliceofstacy]  Tag [2/6]
INFO [2018-05-23 21:45:28] [sliceofstacy]  --> b'beautifulmatters'
INFO [2018-05-23 21:45:58] [sliceofstacy]  Too few images, skipping this tag
...
```

My like_by_tags code config:

```
session.like_by_tags(tags, amount=3, skip_top_posts=True)
```

Traceback:

```
Traceback (most recent call last):
  File "Tags.py", line 67, in <module>
    session.like_by_tags(tags, amount=3, skip_top_posts=True, interact=True)
  File "/home/ke/.virtualenvs/insta/InstaPy/instapy/instapy.py", line 1133, in like_by_tags
    skip_top_posts)
  File "/home/ke/.virtualenvs/insta/InstaPy/instapy/like_util.py", line 196, in get_links_for_tag
    top_elements = browser.find_element_by_xpath('//main/article/div[1]')
  File "/home/ke/.virtualenvs/insta/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/ke/.virtualenvs/insta/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/home/ke/.virtualenvs/insta/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/ke/.virtualenvs/insta/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//main/article/div[1]"}
  (Session info: headless chrome=66.0.3359.181)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 3.10.0-862.el7.x86_64 x86_64)
```

**Comment by forgottensword** [comment]
Same problem here .... No tags are working .... Any Solution

**Comment by amauryleproux** [comment]
@TruthLore and @forgottensword did you find any solutions? I've got the same issue right now :/

**Comment by forgottensword** [comment]
@amauryleproux after I cleared the cookies and everything it just worked fine.

**Comment by valentincognito** [comment]
@forgottensword Sounds like a good idea, but I am afraid I couldn't yet find a way to clear the cookies on a raspberry PI.

**Comment by kenstowe** [comment]
I'm not sure what caused the problem. After a few days the issue stopped. I did not clear the cookies but if the issue reoccurs I will test.

**Comment by valentincognito** [comment]
The latest version of the repo fixes the issue !

**Comment by tunidev** [comment]
same here when using  Authentication proxy
