### ISSUE TITLE
Could not determine if xxxx has followers

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2089]
Hi,
I have run into a problem:
ERROR [2018-05-23 17:57:16] [xxxxx]  Could not determine if xxxx has followers

Traceback (most recent call last):
  File "quickstart.py", line 81, in <module>
    session.follow_user_followers(['user1', 'user2'], amount=7, randomize=False, interact=True)
  File "/home/usr/InstaPy/instapy/instapy.py", line 1907, in follow_user_followers
    self.logfolder)
ValueError: not enough values to unpack (expected 2, got 0)

Anyone know how to fix this?

**Comment by timojaask** [comment]
I have the same problem, running the latest version, in a docker container.

**Comment by Raziel15** [comment]
Same issue

**Comment by uluQulu** [comment]
Hi guys
Is that issue persistent?


##### UPDATE
Find the solution in the PR of #2086, particularly, in this commit 27926468677655ba994ca52150601ab9a9fb64fc

**Comment by Raziel15** [comment]
It worked but now I get this error :

```
[0527/025814.736:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:12486/devtools/browser/45579119-f091-4fad-859c-2436244a3202
INFO [2018-05-27 02:58:16] [x]  Session started - 2018-05-27 02:58:16
Cookie file not found, creating cookie...
CRITICAL [2018-05-27 02:58:51] [x]  Wrong login data!
INFO [2018-05-27 02:58:53] [x]  User 'x' [1/4]
ERROR [2018-05-27 02:59:44] [x]  `followers_link` error list index out of range
INFO [2018-05-27 02:59:44] [x]  User 'x' [2/4]
ERROR [2018-05-27 03:00:35] [x]  `followers_link` error list index out of range
INFO [2018-05-27 03:00:35] [x]  User 'x' [3/4]
ERROR [2018-05-27 03:01:26] [x]  `followers_link` error list index out of range
INFO [2018-05-27 03:01:26] [x]  User 'x' [4/4]
ERROR [2018-05-27 03:02:17] [x]  `followers_link` error list index out of range
INFO [2018-05-27 03:02:17] [x]  --> Followed total of 0 people

WARNING [2018-05-27 03:02:43] [x]  There are 0 people to unfollow
ERROR [2018-05-27 03:03:08] [x]  following_link error list index out of range
Traceback (most recent call last):
  File "essai.py", line 127, in <module>
    amount=1050)  # unfollows 10 of the accounts your following -> instagram will only unfollow 10 before you'll be 'blocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg\instapy\instapy.py", line 2047, in unfollow_users
    self.logfolder)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg\instapy\unfollow_util.py", line 327, in unfollow
    "//div[text()='Following']/following-sibling::div")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 387, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 957, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Following']/following-sibling::div"}
  (Session info: headless chrome=66.0.3359.181)
  (Driver info: chromedriver=2.36.540470 (e522d04694c7ebea4ba8821272dbef4f9b818c91),platform=Windows NT 10.0.14393 x86_64)
```

**Comment by uluQulu** [comment]
@Raziel15 
That issue was solved in the last merged commits, do you have them?

**Comment by Raziel15** [comment]
Updated, thanks
