### ISSUE TITLE
Group of error messages

### ISSUE THREAD

**Issue by Cal12345** [InstaPy/InstaPy#2095]
Hello, I'm getting this error when I attempt to run instapy on the GUI. I'm using Windows 10. I'm a newb so any help would be great. 

"Cookie file not found, creating cookie...

Error: INFO [2018-05-24 10:37:33] [_username_] Session started - 2018-05-24 10:37:33
 WARNING [2018-05-24 10:37:33] [_username_] Sorry, Record Activity is not working on Windows. We're working to fix this soon!
 Traceback (most recent call last):
 File "quickstart.py", line 5, in <module>
 session.login()
 File "C:\Users\WINDOWS\Desktop\InstaPy-master\instapy\instapy.py", line 322, in login
 self.bypass_suspicious_attempt):
 File "C:\Users\WINDOWS\Desktop\InstaPy-master\instapy\login_util.py", line 136, in login_user
 "//select[@class='_fsoey']/option[text()='English']").click()
 File "C:\Users\WINDOWS\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
 self._execute(Command.CLICK_ELEMENT)
 File "C:\Users\WINDOWS\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
 return self._parent.execute(command, params)
 File "C:\Users\WINDOWS\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 314, in execute
 self.error_handler.check_response(response)
 File "C:\Users\WINDOWS\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
 (Session info: chrome=66.0.3359.181)
 (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)"

**Comment by uluQulu** [comment]
Hey @Cal12345 
Looks like your **chromedriver** is old, consider upgrading it to some newer version and see if it works
>_Also have a good read https://github.com/timgrossmann/InstaPy/issues/2043#issuecomment-390332578 for more useful information_

Cheers
