### ISSUE TITLE
is it just me? 'json.decoder.JSONDecodeError: Extra data: line 1 column 45524'

### ISSUE THREAD

**Issue by luigifaticoso** [InstaPy/InstaPy#2110]
## Current Behavior

```
Traceback (most recent call last):
  File "cali.py", line 17, in <module>
    multi_logs=True)
  File "/Users/luigicali/Proejcts/InstaPy/instapy/instapy.py", line 119, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "/Users/luigicali/Proejcts/InstaPy/instapy/unfollow_util.py", line 822, in load_follow_restriction
    return json.load(followResFile)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 45524 (char 45523)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cali.py", line 124, in <module>
    session.end()
NameError: name 'session' is not defined
```

**Comment by luigifaticoso** [comment]
Deleted the folder, re-cloned the project fixed it
