### ISSUE TITLE
Unfollowing Error

### ISSUE THREAD

**Issue by timokueck** [InstaPy/InstaPy#2111]
Im getting this error:

`Traceback (most recent call last):
  File "script.py", line 37, in <module>
    session.unfollow_users(amount=100, sleep_delay=600, unfollow_after=48*60*60)
  File "/home/InstaPy/instapy/instapy.py", line 2102, in unfollow_users
    self.logfolder)
  File "/home/InstaPy/instapy/unfollow_util.py", line 329, in unfollow
    "//div[text()='Following']/following-sibling::div")
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Following']/following-sibling::div"}
  (Session info: headless chrome=66.0.3359.139)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.13.0-36-generic x86_64)`

**Comment by Raziel15** [comment]
Same issue

**Comment by xme1226** [comment]
Same issue
```
**********************************************************************
If raising an issue, please also upload the file located at:
/var/folders/s9/zzc03f7d055_4ds3c_33z4jw0000gp/T/20180531-181435.html
**********************************************************************
```
here is the file
[20180531-180403.html.zip](https://github.com/timgrossmann/InstaPy/files/2057621/20180531-180403.html.zip)

**Comment by timokueck** [comment]
@timgrossmann
