### ISSUE TITLE
Timeout problems

### ISSUE THREAD

**Issue by marudon** [InstaPy/InstaPy#214]
Often I have problems with early termination of the script because of timeouts in the webdriver.
Does anybody know what the reason could be and how to fix it?

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    session.like_by_tags(['collection'], amount=100)
  File "..\InstaPy-master\instapy\instapy.py", line 274, in like_by_tags
    self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)
  File "..\InstaPy-master\instapy\like_util.py", line 154, in check_link
    browser.get(userlink)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 261, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\**selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout**
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by timgrossmann** [comment]
@marudon Are you running it on a server or local machine?

**Comment by marudon** [comment]
Local maschine

Also in case of this terminations I will get no summary of what the script has done.
That is not nice after a long run .. is there a chance to catch the exceptions?

**Comment by timgrossmann** [comment]
@marudon Wait,  `platform=Windows NT 6.1.7601 SP1 x86_64)` ?!

How much RAM? 
You need at least 1GB RAM...

**Comment by marudon** [comment]
Windows 7, 16GB RAM.. Do you think it s a Problem of resources? I had open many applications, maybe the RAM was temporarily less

Von meinem iPhone gesendet

**Comment by marudon** [comment]
Here annother exception .. nearly every script run I get one ..
I'm running on Win7 .. I don't why is logged "platform=Windows NT"  ??

----------------------------------
Image from: b'doublecross925'
Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    session.like_by_tags(['fashionart'], amount=100)
 ...instapy\like_util.py", line 156, in check_link
    num_followers = browser.execute_script("return window._sharedData.entry_data.ProfilePage[0].user.followed_by.count")
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 484, in execute_script
    'args': converted_args})['value']
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by timgrossmann** [comment]
@marudon Well, that's a different error, at least.
`Cannot read property 'entry_data' of undefined` are you on a business account?
Do you have the latest version of InstaPy? `git pull`

**Comment by kushpvo** [comment]
I'm getting this error frequently.

`[82/191]
Traceback (most recent call last):
  File "quickstart.py", line 28, in <module>
    session.like_by_tags(['#nyc', 'miami', 'chicago', 'losangeles'], amount=randint(minTag, maxTag))
  File "/root/InstaPy/instapy/instapy.py", line 430, in like_by_tags
    self.like_by_followers_lower_limit)
  File "/root/InstaPy/instapy/like_util.py", line 176, in check_link
    browser.get(link)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-83-generic x86_64)
`
