### ISSUE TITLE
Selenium exception 

### ISSUE THREAD

**Issue by wutzi15** [InstaPy/InstaPy#2142]
I'm on commit 709f27f72a5410ae8efc4345875140218e1d0264. 

A previously working config now crashes with the following output: 

    INFO [2018-06-01 11:05:40] [benediktbergenthal]  Session started - 2018-06-01 11:05:40
    INFO [2018-06-01 11:06:09] [benediktbergenthal]  Logged in successfully!
    Traceback (most recent call last):
      File "quickstart.py", line 28, in <module>
        session.set_dont_unfollow_active_users(enabled=True, posts=5)
      File "/home/benedikt/src/InstaPy/instapy/instapy.py", line 2357, in set_dont_unfollow_active_users
    self.logger)
      File "/home/benedikt/src/InstaPy/instapy/util.py", line 202, in get_active_users
        "//span[contains(@class,'_t98z6')]//span").text)
      File "/home/benedikt/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py",     line 293, in find_element_by_xpath
        return self.find_element(by=By.XPATH, value=xpath)
      File "/home/benedikt/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py",     line 752, in find_element
        'value': value})['value']
      File "/home/benedikt/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
        self.error_handler.check_response(response)
      File "/home/benedikt/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
        raise exception_class(message, screen, stacktrace)
    selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(@class,'_t98z6')]//span"}
      (Session info: chrome=66.0.3359.181)
      (Driver info: chromedriver=2.39.562737     (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.15.0-22-generic x86_64)

**Comment by sionking** [comment]
update to latest

**Comment by wutzi15** [comment]
Correct me if im wrong, but as far as I can see/pull 709f27f72a5410ae8efc4345875140218e1d0264 is the latest commit (right now) and produces this error
