### ISSUE TITLE
Sudden death

### ISSUE THREAD

**Issue by Doom666** [InstaPy/InstaPy#2143]
![screenshot_20180601-114223_codeanywhere](https://user-images.githubusercontent.com/8590333/40834754-f5de38bc-6591-11e8-9317-0766cce4b6b9.jpg)
This began to happen 2 days ago,  I did absolutely no changes whatsoever... I'm quite lost here guys
As a side note, before the crash after " reading settings" it hangs for like 10 minutes before crashing...

**Comment by sionking** [comment]
update to latest

**Comment by Doom666** [comment]
Oh, of course, I will!

**Comment by succulentia** [comment]
I have just completed the update.  Using it on windows, here is da problem:

`Traceback (most recent call last):
  File "C:\Users\siber\Desktop\InstaPy\quickstart.py", line 5, in <module>
    session.login()
  File "C:\Users\siber\Desktop\InstaPy\instapy\instapy.py", line 322, in login
    self.bypass_suspicious_attempt):
  File "C:\Users\siber\Desktop\InstaPy\instapy\login_util.py", line 136, in login_user
    "//select[@class='_fsoey']/option[text()='English']").click()
  File "C:\Users\siber\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 385, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\siber\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 955, in find_element
    'value': value})['value']
  File "C:\Users\siber\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\siber\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.17134 x86_64)`

**Comment by joanroig** [comment]
@succulentia @Doom666 this solves your issue: https://github.com/timgrossmann/InstaPy/pull/2146
