### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by Erasio38** [InstaPy/InstaPy#2144]
Hi there please help me.

the error message is the following :
"Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    multi_logs=True)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 170, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 276, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error"

please advise? thanks

**Comment by converge** [comment]
hey, this should help: https://github.com/timgrossmann/InstaPy/search?q=OSError%3A+%5BErrno+8%5D+Exec+format+error%22&type=Issues

**Comment by Erasio38** [comment]
I can not do it even using the other topic

**Comment by gustafsom** [comment]
I have the same problem

**Comment by playnet-team** [comment]
you need to change the default workspace which is set to /root/InstaPy 

> from instapy import set_workspace
> set_workspace(path='/home/pi/InstaPy')

**Comment by dimat** [comment]
I've got the same problem. When I run the bot from the shell, it works well, so gecko and firefox are compatible

However, I get this error, when I try to run the bot as a cron job.

Any ideas what could be different in these two environments?

**Comment by mnike000** [comment]
Did you ever figure this out @dimat ? I'm having the same issue. Thanks for any help!
