### ISSUE TITLE
Hi team, i've been using instapy for more than 1 week and today i had this huge error :D

### ISSUE THREAD

**Issue by DelaaReda** [InstaPy/InstaPy#2156]
## Expected Behavior
 File "quickstart.py", line 23, in <module>
    multi_logs=True)
  File "/Users/macbookair/Desktop/InstaPy-master/instapy/instapy.py", line 116, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "/Users/macbookair/Desktop/InstaPy-master/instapy/unfollow_util.py", line 893, in load_follow_restriction
    return json.load(followResFile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
macbooks-MacBook-Air:InstaPy-master Reda$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 23, in <module>
    multi_logs=True)
  File "/Users/macbookair/Desktop/InstaPy-master/instapy/instapy.py", line 116, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "/Users/macbookair/Desktop/InstaPy-master/instapy/unfollow_util.py", line 893, in load_follow_restriction
    return json.load(followResFile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

## InstaPy configuration
python 2.7 on mac os Sierra 10.12.6

Thanks for help if possible...

**Comment by testingNodejs** [comment]
I dowloaded the recent version and i had another error:
