### ISSUE TITLE
I can not login to instagram account 

### ISSUE THREAD

**Issue by imanbahmani** [InstaPy/InstaPy#2163]
this is my error 
please help me!

I have last version of brach of master and today download them and update chrome driver and google chrome browser but see this problem

Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.login()
  File "/home/deeplearning/Pictures/InstaPy-master (2)/instapy/instapy.py", line 322, in login
    self.bypass_suspicious_attempt):
  File "/home/deeplearning/Pictures/InstaPy-master (2)/instapy/login_util.py", line 136, in login_user
    "//select[@class='_fsoey']/option[text()='English']").click()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 385, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 955, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=67.0.3396.62)
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.13.0-39-generic x86_64)

**Comment by dgolosov** [comment]
https://github.com/timgrossmann/InstaPy/pull/2146/files
