### ISSUE TITLE
issue with get_active_users - _t98z6 changed.

### ISSUE THREAD

**Issue by chadrenshaw** [InstaPy/InstaPy#2166]
Does anyone know the new value?

Traceback (most recent call last):
  File "./quickstart-unfollow.py", line 61, in <module>
    session.set_dont_unfollow_active_users(enabled=True, posts=40)
  File "/root/InstaPy/instapy/instapy.py", line 2357, in set_dont_unfollow_active_users
    self.logger)
  File "/root/InstaPy/instapy/util.py", line 202, in get_active_users
    "//span[contains(@class,'_t98z6')]//span").text)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(@class,'_t98z6')]//span"}
  (Session info: headless chrome=66.0.3359.139)
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.14.0-kali3-amd64 x86_64)

**Comment by uluQulu** [comment]
@chadrenshaw 
_See #2136 or #2131 to find solution._

**Comment by chadrenshaw** [comment]
thanks @uluQulu - all good now.
