### ISSUE TITLE
New VPS，first time setup，just dont know why， any help？

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2170]
root@vultr:~/InstaPy# python ./quickstart.py 
INFO [2018-06-04 02:40:54] [***]  Session started - 2018-06-04 02:40:54
Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20180604-024124.html
**********************************************************************
INFO [2018-06-04 02:41:25] [*****]  Session ended - 2018-06-04 02:41:25
INFO [2018-06-04 02:41:25] [*****]  --------------------

Traceback (most recent call last):
  File "./quickstart.py", line 27, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 322, in login
    self.bypass_suspicious_attempt):
  File "/root/InstaPy/instapy/login_util.py", line 136, in login_user
    "//select[@class='_fsoey']/option[text()='English']").click()
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='_fsoey']/option[text()='English']"}
  (Session info: headless chrome=67.0.3396.62)
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.9.0-5-amd64 x86_64)

everthing is same as before，but in new vps ，it doesnt work，where should i check？

**Comment by ghost** [comment]
this vps is in tokyo

**Comment by ghost** [comment]
download latest master.zip
if still not working....
checkout issue #2157

**Comment by ghost** [comment]
it works! thank u
