### ISSUE TITLE
Cookie file not found, creating cookie...

### ISSUE THREAD

**Issue by mutant-77** [InstaPy/InstaPy#2171]
Any Idea whats going on here?

error:
```
Cookie file not found, creating cookie...
Traceback (most recent call last):
  File "/Users/user/Downloads/InstaPy/quickstart.py", line 15, in <module>
    session.login()
  File "/Users/user/Downloads/InstaPy/instapy/instapy.py", line 322, in login
    self.bypass_suspicious_attempt):
  File "/Users/user/Downloads/InstaPy/instapy/login_util.py", line 136, in login_user
    "//select[@class='_fsoey']/option[text()='English']").click()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-3.12.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 387, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-3.12.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 957, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-3.12.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-3.12.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=67.0.3396.62)
  (Driver info: chromedriver=2.39.562713 (dd642283e958a93ebf6891600db055f1f1b4f3b2),platform=Mac OS X 10.13.3 x86_64)

```

**Comment by kiankji** [comment]
Go into the folder instapy and open the file login_util.py. Scroll down to the line 136 and replace it with 
`"//select[@class='hztqj']/option[text()='English']").click()`

**Comment by neversleeps** [comment]
Also do this [https://github.com/timgrossmann/InstaPy/issues/2133#issuecomment-394098747](url).

And add 2 instead of 1 to the sleep

**Comment by wesleytrying** [comment]
@neversleeps the link you gave doesn't link to anything. It just sends to a 404 link.

@kiankji I also tried installing that line of text over the one there and it didn't seem to work.

**Comment by astritshuli** [comment]
Same error here help please !!

Cookie file not found, creating cookie...
Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.login()
  File "C:\Users\GridComputers\InstaPy\instapy\instapy.py", line 347, in login
    self.bypass_suspicious_attempt):
  File "C:\Users\GridComputers\InstaPy\instapy\login_util.py", line 136, in login_user
    "//select[@class='hztqj']/option[text()='English']").click()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.17134 x86_64)

**Comment by sandy1812** [comment]
> Same error here help please !!
> 
> Cookie file not found, creating cookie...
> Traceback (most recent call last):
> File "quickstart.py", line 25, in 
> session.login()
> File "C:\Users\GridComputers\InstaPy\instapy\instapy.py", line 347, in login
> self.bypass_suspicious_attempt):
> File "C:\Users\GridComputers\InstaPy\instapy\login_util.py", line 136, in login_user
> "//select[@Class='hztqj']/option[text()='English']").click()
> File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
> self._execute(Command.CLICK_ELEMENT)
> File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
> return self._parent.execute(command, params)
> File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
> self.error_handler.check_response(response)
> File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
> (Session info: chrome=67.0.3396.99)
> (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.17134 x86_64)

Same issue

**Comment by soldiersebas** [comment]
Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20181006-040237.html

tengo este problema, ya revise el login_util y esta bien, lo estoy ejecutando de manera local alguna ayuda?
