### ISSUE TITLE
Finally got past a bunch of problems, but one still remains

### ISSUE THREAD

**Issue by neversleeps** [InstaPy/InstaPy#2172]
Richards-MacBook-Air:InstaPy Richard$ python3 quickstart.py
INFO [2018-06-03 22:41:15] [richard.nait]  Session started - 2018-06-03 22:41:15
Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/var/folders/cm/_4dg7j9d67g8td35b9vw77340000gn/T/20180603-224153.html
**********************************************************************
INFO [2018-06-03 22:41:53] [richard.nait]  Session ended - 2018-06-03 22:41:53
INFO [2018-06-03 22:41:53] [richard.nait]  --------------------

Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.login()
  File "/Users/Richard/Documents/InstaPy/instapy/instapy.py", line 322, in login
    self.bypass_suspicious_attempt):
  File "/Users/Richard/Documents/InstaPy/instapy/login_util.py", line 136, in login_user
    "//select[@class='_fsoey']/option[text()='English']").click()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 387, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 957, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=67.0.3396.62)
  (Driver info: chromedriver=2.39.562713 (dd642283e958a93ebf6891600db055f1f1b4f3b2),platform=Mac OS X 10.13.2 x86_64)

Not sure what is going on, it just opens chrome.

Please all help is appreciated.

**Comment by neversleeps** [comment]
Also when I attempt the GUI, it shows "Error: ImportError: No module named selenium"

**Comment by uluQulu** [comment]
@neversleeps 
See #2133

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)
