### ISSUE TITLE
Problem running selenium driver, was working previously

### ISSUE THREAD

**Issue by highmountainwoody** [InstaPy/InstaPy#2173]
## Current Behavior
INFO [2018-06-04 08:25:51] [userjoe]  Session started - 2018-06-04 08:25:51
Cookie file not found, creating cookie...
Traceback (most recent call last):
  File "quickstart.py", line 12, in <module>
    session.login()
  File "/home/mike/instapy/instapy/instapy.py", line 322, in login
    self.bypass_suspicious_attempt):
  File "/home/mike/instapy/instapy/login_util.py", line 136, in login_user
    "//select[@class='_fsoey']/option[text()='English']").click()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.9.0-6-amd64 x86_64)

**Comment by highmountainwoody** [comment]
Sorry, fixed by finding #2133
