### ISSUE TITLE
Fastest Way to unfollow everyone?

### ISSUE THREAD

**Issue by timokueck** [InstaPy/InstaPy#2191]
I would like to know whats the fastest way to unfollow everyone with instapy without getting soft banned?

Im following 6k+

**Comment by akyzer** [comment]
just go -400/600 every day.
should be ok

**Comment by akyzer** [comment]
but you cant unfollow for the moment :))))

**Comment by timokueck** [comment]
@akyzer 

Im getting since 2 weeks this error:
`Traceback (most recent call last):
  File "script.py", line 37, in <module>
    session.unfollow_users(amount=200, onlyInstapyFollowed = False, onlyInstapyMethod = 'FIFO', sleep_delay=600, unfollow_after=48*60*60)
  File "/home/InstaPy/instapy/instapy.py", line 2126, in unfollow_users
    self.logfolder)
  File "/home/InstaPy/instapy/unfollow_util.py", line 348, in unfollow
    "//div[text()='Following']/following-sibling::div")
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Following']/following-sibling::div"}
  (Session info: headless chrome=66.0.3359.139)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.13.0-36-generic x86_64)`

**Comment by akyzer** [comment]
just check other issue and dont create new one!
You need to pull to the latest version #2171

**Comment by timokueck** [comment]
One question I have is can I unfollow 600 at once or should I wait like one hour each 100 followers

**Comment by timokueck** [comment]
And unfollowing is still not working even after cloning the latest version of instapy
