### ISSUE TITLE
 Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by juisex** [InstaPy/InstaPy#2194]
I've runned the InstaPy and the same script before (last week) I was using a VMWare ubuntu virtual machine, since then I've started some studies and decided to install Ubuntu as my main OS.

Today after install all the program and dependencies, I've got this error, that already appeared for me and I've solucionated with Geckodriver, but now Geckodriver and Chromedriver doesn't work.  

Heres all the error:
Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.15.0-22-generic x86_64)
Traceback (most recent call last):
  File "/home/organic/Downloads/InstaPy-master/instapy/instapy.py", line 285, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.15.0-22-generic x86_64)

Traceback (most recent call last):
  File "/home/organic/Downloads/InstaPy-master/instapy/instapy.py", line 285, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.15.0-22-generic x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Liketest23.py", line 2, in <module>
    session = InstaPy(username='pedroghion', password='macaco14', headless_browser=True)
  File "/home/organic/Downloads/InstaPy-master/instapy/instapy.py", line 174, in __init__
    self.set_selenium_local_session()
  File "/home/organic/Downloads/InstaPy-master/instapy/instapy.py", line 289, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/organic/Downloads/InstaPy-master/assets/chromedriver

Maybe if I change some executable or the own chromedriver to another program I can solve this?

Befor I didn't need to start the script as a "sudo -s" but since I'm using the ubuntu as a main OS i need to do this command, I don't know if this affects the script runs, but I'm telling you.

I've Already tryed to change the Chromedriver in Assets to a folder or directly to the executable, both solutions goes to the same error.

I'm using Instapy in Headless browser mode.

**Comment by juisex** [comment]
Looks like all this problem started after the python Conda installation.

**Comment by Doom666** [comment]
have you ad nogui= True?
in your session settings?

**Comment by Fannolo** [comment]
Have you tried to set in the "quickstart.py" file from `headless_browser=False` to `headless_browser=False`
