### ISSUE TITLE
Created New User - Startup Error

### ISSUE THREAD

**Issue by dbmathis** [InstaPy/InstaPy#2198]
I copied a working instapy dir and tested the copied dir and Instapy works fine. Within the new dir I renamed quickstart.py to lulu.py and then changed the login name and pass to a new user and ran lulu.py and got the following error. What else do I need to do to run Instapy for this new user?

```
INFO [2018-06-07 10:25:31] [x]  Session started - 2018-06-07 10:25:31
Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/var/folders/qx/jz4kqlr5273bw5l63cxjjjl00000gn/T/20180607-102602.html
**********************************************************************
INFO [2018-06-07 10:26:02] [x]  Session ended - 2018-06-07 10:26:02
INFO [2018-06-07 10:26:02] [x]  --------------------


Traceback (most recent call last):
  File "./lulu.py", line 26, in <module>
    session.login()
  File "/Users/x/InstaPyLulu/instapy/instapy.py", line 322, in login
    self.bypass_suspicious_attempt):
  File "/Users/x/InstaPyLulu/instapy/login_util.py", line 136, in login_user
    "//select[@class='_fsoey']/option[text()='English']").click()
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=67.0.3396.79)
  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.13.4 x86_64)

```

**Comment by dbmathis** [comment]
I just started over from scratch on the new user and it works. Still curious how to copy an existing dir and change the user for it.
