### ISSUE TITLE
A lot of issues with raspberry pi

### ISSUE THREAD

**Issue by Liturgikus** [InstaPy/InstaPy#2199]
Hey guys!
After spending literally hours in front of my screen trying to setup the bot on my raspberry pi, I think I'm now ready to open my own issue. I've already tried to follow step by step different tutorials, via Chromium, or Firefox. But I'm pretty sure I can't find any working tutorial...
I always face a new issue (the most preponderant is when I get this error while installing pip : You must give at least one requirement to install).
Is there a proper working tutorial?
I'm not running this headless, got a raspberry pi 3B+ on a new raspbian stretch

**Comment by ljacobo** [comment]
Hi Liturgikus,

Did you follow the instructions step by step? My lab is currently in a Raspberry Pi 3 using Firefox-esr and is working perfect.. This is an update of the instructions. https://github.com/timgrossmann/InstaPy/issues/1253

**Comment by wemakefuture** [comment]
Well @Liturgikus is right its not working properly. i use a old version of April 3rd 2018 and it is still starting the script and logging on. But it runs into errors later cause IG changed a lot. 

So i updated to new version and i get this error:

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=False)
  File "/home/pi/100618/InstaPy/instapy/instapy.py", line 174, in __init__
    self.set_selenium_local_session()
  File "/home/pi/100618/InstaPy/instapy/instapy.py", line 285, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

(i run this (-a) is better then without for crontab)
`sudo xvfb-run -a python2.7 `

**Comment by FinMonkee** [comment]
I'm also having issues following the rpi tutorial; 

`pi@raspberrypi:~/Projects/InstaPy $ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)

  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 189, in __init__
    self.set_selenium_local_session()

  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 296, in set_selenium_local_session
    chrome_options=chrome_options)

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)

  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)

  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception

OSError: [Errno 8] Exec format error
`

edited: formatting.

**Comment by imbarismustafa** [comment]
use the GUI version of raspian
and dont forget to change the min version to 2.33
and make sure you have the chromium driver in assets folder
and also i think you need to change In login_util.py change _fsoey to hztqj
thats what i did and its working fine
but you need full raspian os

**Comment by wemakefuture** [comment]
@imbarismustafa 

dont forget to change the min version to 2.33
Thanks man. Sometimes i should carefully read things. Sorry.

**Comment by wemakefuture** [comment]
@timgrossmann solved
