### ISSUE TITLE
Chromedriver won't run in Windows

### ISSUE THREAD

**Issue by aamirc** [InstaPy/InstaPy#22]
As the Chromedriver that comes with this package is for linux - this won't run if you are trying to run it on windows. I replaced the chrome driver in the assets with the windows version - extracted of course.

https://chromedriver.storage.googleapis.com/2.29/chromedriver_win32.zip

**Comment by timgrossmann** [comment]
Yes thank you for pointing it out, I'll add it to the readme!
You have to use the chrome driver that fits your system.

**Comment by rahulkapoor90** [comment]
@aamirc how did you run this in windows?

I am getting this error even after replacing the file in assets.

```
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\rahul\Desktop\InstaPy\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\Users\rahul\Desktop\InstaPy\instapy\instapy.py", line 11, in <module>
    from .clarifai_util import check_image
  File "C:\Users\rahul\Desktop\InstaPy\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.client import ClarifaiApi
  File "C:\Users\rahul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\clarifai-2.0.20-py3.6.egg\clarifai\client\__init__.py", line 5, in <module>
  File "C:\Users\rahul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\clarifai-2.0.20-py3.6.egg\clarifai\client\client.py", line 4, in <module>
ModuleNotFoundError: No module named 'past'
```

**Comment by aamirc** [comment]
@rahulkapoor90

All I did to get it to work was to install all the dependencies via pip
install and replaced the chromedriver file in the assets folder with the
windows version.

Worked fine after I did this.

To install Clarifai I had to open command prompt as Administrator.

**Comment by timgrossmann** [comment]
@aamirc Perfect, thanks  for sharing your experience, this will help a lot of other people having the same problems!
