### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2212]
## Current Behavior

Currently application crashes when using follow_likers on yourself:

```
Traceback (most recent call last):
  File "/Users/piratze/Documents/GitHub/InstaPy/instapy/util.py", line 481, in get_relationship_counts
    followers_count = format_number(browser.find_element_by_xpath("//a[contains"
  File "/Users/piratze/Documents/GitHub/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 387, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/piratze/Documents/GitHub/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 957, in find_element
    'value': value})['value']
  File "/Users/piratze/Documents/GitHub/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/Users/piratze/Documents/GitHub/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href,'followers')]/span"}
  (Session info: chrome=68.0.3440.17)
  (Driver info: chromedriver=2.39.562713 (dd642283e958a93ebf6891600db055f1f1b4f3b2),platform=Mac OS X 10.13.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/piratze/Documents/GitHub/InstaPy/instapy/util.py", line 486, in get_relationship_counts
    "return window._sharedData.entry_data."
  File "/Users/piratze/Documents/GitHub/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 629, in execute_script
    'args': converted_args})['value']
  File "/Users/piratze/Documents/GitHub/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/Users/piratze/Documents/GitHub/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: chrome=68.0.3440.17)
  (Driver info: chromedriver=2.39.562713 (dd642283e958a93ebf6891600db055f1f1b4f3b2),platform=Mac OS X 10.13.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/piratze/Documents/GitHub/InstaPy/instapy/util.py", line 492, in get_relationship_counts
    "return window._sharedData.entry_data."
  File "/Users/piratze/Documents/GitHub/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 629, in execute_script
    'args': converted_args})['value']
  File "/Users/piratze/Documents/GitHub/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/Users/piratze/Documents/GitHub/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: chrome=68.0.3440.17)
  (Driver info: chromedriver=2.39.562713 (dd642283e958a93ebf6891600db055f1f1b4f3b2),platform=Mac OS X 10.13.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/piratze/Documents/GitHub/InstaPy/quickstart.py", line 76, in <module>
    session.follow_likers([a], photos_grab_amount=10, follow_likers_per_photo=10, randomize=True)
  File "/Users/piratze/Documents/GitHub/InstaPy/instapy/instapy.py", line 618, in follow_likers
    followed = self.follow_by_list(liker, self.follow_times, sleep_delay, interact)
  File "/Users/piratze/Documents/GitHub/InstaPy/instapy/instapy.py", line 667, in follow_by_list
    self.logger)
  File "/Users/piratze/Documents/GitHub/InstaPy/instapy/util.py", line 73, in validate_username
    followers_count, following_count = get_relationship_counts(browser, username, logger)
  File "/Users/piratze/Documents/GitHub/InstaPy/instapy/util.py", line 497, in get_relationship_counts
    "//span[contains(@class,'g47SY')]")[1].text))
IndexError: list index out of range

Process finished with exit code 1
```

## InstaPy configuration

using below:

`session.follow_likers([a], photos_grab_amount=10, follow_likers_per_photo=10, randomize=True)`

**Comment by sohumsanu** [comment]
I am getting the same error as well and am not sure what to do.

**Comment by spikeyhair** [comment]
It gave error randomly

**Comment by Floflokiki** [comment]
On **util.py** file, replace:
```
followers_count = format_number((browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")[1].text))
```
With:
```
topCount_elements = browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")
if topCount_elements:
    followers_count = format_number(topCount_elements[1].text)
else:
    logger.error("Failed to get followers count of '{}'  ~empty list".format(username))
    followers_count = None
```
And, replace:
```
following_count = format_number(browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")[2].text)
```
With:
```
topCount_elements = browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")
if topCount_elements:
    following_count = format_number(topCount_elements[2].text)
else:
    logger.error("Failed to get following count of '{}'  ~empty list".format(username))
    following_count = None
```

On **unfollow_util.py** file, replace :
```
allfollowers = format_number((browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")[1].text))
```
With:
```
topCount_elements = browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")
if topCount_elements:
    allfollowers = format_number(topCount_elements[1].text)
else:
    logger.error("Error occured during getting the followers count of '{}'  ~empty list".format(username))
    allfollowers = None
```
And replace:
```
allfollowing = format_number((browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")[2].text))
```
With:
```
topCount_elements = browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")
if topCount_elements:
    allfollowing = format_number(topCount_elements[2].text)
else:
    logger.error("Error occured during getting the following count of '{}'  ~empty list".format(username))
    allfollowing = None
```

Hope it helps!
Based on @uluQulu proposal!
