### ISSUE TITLE
One account works but another doesn't.  WHY????

### ISSUE THREAD

**Issue by thankmelater23** [InstaPy/InstaPy#2213]
## Expected Behavior
Wont run quickstart.py file with one account, but not with other.  I've been running Instapy on the account a few months.  Not sure if it got blocked or something.

## Current Behavior
<pr>Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/Users/AndreVillanueva_Com/Dropbox/Bots/InstaPy/instapy/instapy.py", line 122, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "/Users/AndreVillanueva_Com/Dropbox/Bots/InstaPy/instapy/unfollow_util.py", line 849, in load_follow_restriction
    return json.load(followResFile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded</pr>

**Comment by CharlesCCC** [comment]
whoever the user you are using must have a corrupsted `followedrestriction.json` file @uluQulu is working on a fix to prevent this happening in the future.

**Comment by thankmelater23** [comment]
Ok so what do I have to do? Wait till it’s fixed?

**Comment by CharlesCCC** [comment]
wait or delete the existing corrupsted json file from that user's folder. but this will cause some user get follow/unfollowed again (you decision if you would like do that or not)

**Comment by thankmelater23** [comment]
Ok I think I’ll do that! Thanks!

**Comment by uluQulu** [comment]
Hey guys
@thankmelater23 Have a read https://github.com/timgrossmann/InstaPy/pull/2086#issuecomment-394117784 to fix that file without purging it completely.
@CharlesCCC I think I can write that DB after finishing with current feature set.

**Comment by thankmelater23** [comment]
Will do! Thanks!
