### ISSUE TITLE
 DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by epokheio** [InstaPy/InstaPy#2214]
Hello everyone, 

After running python quickstart.py on AWS/Ubuntu for the first time I got the following error message:

```
Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 3.13.0-74-generic x86_64)
Traceback (most recent call last):
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 285, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 3.13.0-74-generic x86_64)
```

**Comment by rayl8w** [comment]
Try changing "Headless browser=True" inside the quickstart.py

**Comment by ghost** [comment]
@epokheio how did you fix?

**Comment by DanielDK100** [comment]
Getting the same exception here - anyone found a solution to this?

**Update**: This seems to be working for me; add the following option parameters:
```python
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
```
The above solution is only tested on a **bare installation of Selenium** (not in any way related to _this_ repository since I only found this thread by Googling the error message that I received) - so you'll probably have to figure out where to place the above options accordingly in InstaPy for it to work.

Here's all of my Python code for further reference in case anyone should need it:
```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--headless')
options.add_argument('--disable-gpu')

driver = webdriver.Chrome(executable_path='/usr/local/bin/chromedriver', chrome_options=options)
driver.get('https://github.com/')
print driver.title
driver.quit()
```
**Notice**: Remember to change the `executable_path` parameter to the correct directory that your own chrome driver is located in.

**Comment by apsk-code** [comment]
I was stuck for more than a week for this issue...Thanks a lot...
