### ISSUE TITLE
Error reading broker pipe

### ISSUE THREAD

**Issue by maexsim** [InstaPy/InstaPy#2219]
DevTools listening on ws://127.0.0.1:50304/devtools/browser/d1c49a51-8e5a-41a9-ac44-30385ae6d00c
INFO [2018-06-11 22:45:06] [mylogin]  Session started - 2018-06-11 22:45:06
WARNING [2018-06-11 22:45:06] [mylogin]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO [2018-06-11 22:45:36] [mylogin]  Logged in successfully!
INFO [2018-06-11 22:45:39] [mylogin]  User 'avrora_mua' [1/1]
**********************************************************************
If raising an issue, please also upload the file located at:
C:\Users\2BA0~1\AppData\Local\Temp\20180611-224610.html
**********************************************************************
[9304:10168:0611/224610.674:ERROR:broker_win.cc(57)] Error reading broker pipe: ╩рэры с√ы чръЁ√Є. (0x6D)
INFO [2018-06-11 22:46:14] [mylogin]  Session ended - 2018-06-11 22:46:14
INFO [2018-06-11 22:46:14] [mylogin]  --------------------

Traceback (most recent call last):
  File "C:\Users\Максим\Documents\GitHub\InstaPy\quickstart.py", line 42, in <module>
    session.follow_user_followers(['avrora_mua'], amount=2500, randomize=False)
  File "C:\Users\Максим\Documents\GitHub\InstaPy\instapy\instapy.py", line 1925, in follow_user_followers
    self.logfolder)
  File "C:\Users\Максим\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 766, in get_given_user_followers
    logger, logfolder)
  File "C:\Users\Максим\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 540, in get_users_through_dialog
    "//div[text()='Followers' or text()='Following']/following-sibling::div")
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 387, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 957, in find_element
    'value': value})['value']
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/following-sibling::div"}
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.16299 x86_64)

**Comment by gitpatrickhub** [comment]
Web version of Instagram appears to be broken.  I see the same behavior using InstaPy (raspberry pi on firefox) and manual operation (macbook chrome). If you login on your computer and attempt the same function, i.e., click on the user's followers, it doesn't open the Followers component, it is reloading the user's account page. Need Instagram to fix their page.
