### ISSUE TITLE
automatic crash when unfollow begins

### ISSUE THREAD

**Issue by Doom666** [InstaPy/InstaPy#2223]
## Expected Behavior
easily unfollow following settings
## Current Behavior
as soon as unfollowing begans, there is a traceback : here is the full session 

> ubuntu@ip-172-31-28-175:~/InstaPy$ python3 mshUNFBot.py
> =========================================
> ==============M************n UNFOLLOWER =========================================
> 
> INFO [2018-06-12 09:37:02] [**************]  Session started - 2018-06-12 09:37:02
> INFO [2018-06-12 09:37:31] [**************]  Logged in successfully!
> INFO [2018-06-12 09:37:33] [**************]  Getting active users who liked the latest 5 posts:
>   ~collecting the usernames from posts with the boundary of 500
> 
> INFO [2018-06-12 09:37:51] [**************]  Post 1  |  Likers: found 95, catched 95
> INFO [2018-06-12 09:38:12] [**************]  Post 2  |  Likers: found 87, catched 87
> INFO [2018-06-12 09:38:29] [**************]  Post 3  |  Likers: found 37, catched 37
> INFO [2018-06-12 09:38:44] [**************]  Post 4  |  Likers: found 45, catched 45
> INFO [2018-06-12 09:39:00] [**************]  Post 5  |  Likers: found 52, catched 52
> INFO [2018-06-12 09:39:03] [**************]  Gathered total of 212 unique active followers from the latest 5 posts in 1 minutes and 30 seconds
> ================================= UNFOLLOW START =========================================
> INFO [2018-06-12 09:39:03] [**************]  --> unfollow_users, amount: 10
> **********************************************************************
> If raising an issue, please also upload the file located at:
> /tmp/20180612-093935.html
> **********************************************************************
> INFO [2018-06-12 09:39:35] [**************]  Session ended - 2018-06-12 09:39:35
> INFO [2018-06-12 09:39:35] [**************]  --------------------
> 
> 
> Traceback (most recent call last):
>   File "UNFBot.py", line 47, in <module>
>     session.unfollow_users(amount=10, onlyInstapyFollowed = False, onlyInstapyMethod = 'FIFO', sleep_delay=600, unfollow_after=48*60*60)
>   File "/home/ubuntu/InstaPy/instapy/instapy.py", line 2126, in unfollow_users
>     self.logfolder)
>   File "/home/ubuntu/InstaPy/instapy/unfollow_util.py", line 348, in unfollow
>     "//div[text()='Following']/following-sibling::div")
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
>     return self.find_element(by=By.XPATH, value=xpath)
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
>     'value': value})['value']
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
>     self.error_handler.check_response(response)
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Following']/following-sibling::div"}
>   (Session info: headless chrome=67.0.3396.79)
>   (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.4.0-1060-aws x86_64)

## Possible Solution (optional)

Changing something from my script:
    session.set_dont_unfollow_active_users(enabled=True, posts=5)
   
    print('==== UNFOLLOW START =======================================')
    session.unfollow_users(amount=500, onlyInstapyFollowed = False, onlyInstapyMethod = 'FIFO', sleep_delay=600, unfollow_after=48*60*60)

**Comment by Doom666** [comment]
I SEE THAT THIS IS AN INSTAGRAM ERROR
you can access to the following/ unfollowing lists in the desktop version
