### ISSUE TITLE
Errno 11004 in Urllib2

### ISSUE THREAD

**Issue by Dalrabadi** [InstaPy/InstaPy#2246]
## Expected Behavior
This code execute without issues?
## Current Behavior
I get this error:
`urllib2.URLError: <urlopen error [Errno 11004] getaddrinfo failed> `
when the code hits this line:
`bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub') `

Error Log:
`C:\Python27\python.exe C:/Users/dalrabad/Downloads/InstaPy-master_44/InstaPy-master/docker_quickstart.py
Traceback (most recent call last):
  File "C:/Users/dalrabad/Downloads/InstaPy-master_44/InstaPy-master/docker_quickstart.py", line 18, in <module>
    bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub')
  File "C:\Users\dalrabad\Downloads\InstaPy-master_44\InstaPy-master\instapy\instapy.py", line 314, in set_selenium_remote_session
    desired_capabilities=DesiredCapabilities.CHROME)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 408, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 478, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 11004] getaddrinfo failed>`
## Possible Solution (optional)
I heard it has to do with proxies I know nothing about that. If that is the solution can someone walk me through how to add one/remove one/add to system variables? Please? Thank you Thank you

**Comment by NooriP** [comment]
Hi @Dalrabadi did you find any solution, i am having the same issue.
