### ISSUE TITLE
stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by Areahints** [InstaPy/InstaPy#2261]
I keep getting this error! after updating both instapy and chromedriver

```root@areahints:~/InstaPy# python areahintsng.py
INFO [2018-06-18 03:08:06] [areahintsng]  Session started - 2018-06-18 03:08:06
Cookie file not found, creating cookie...
INFO [2018-06-18 03:08:59] [areahintsng]  Session ended - 2018-06-18 03:08:59
INFO [2018-06-18 03:08:59] [areahintsng]  --------------------


Traceback (most recent call last):
  File "areahintsng.py", line 25, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 328, in login
    self.bypass_suspicious_attempt):
  File "/root/InstaPy/instapy/login_util.py", line 152, in login_user
    click().send_keys(username).perform()
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/action_chains.py", line 74, in perform
    action()
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/action_chains.py", line 225, in <lambda>
    Command.MOVE_TO, {'element': to_element.id}))
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=66.0.3359.181)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.4.0-127-generic x86_64)```

**Comment by Nisthar** [comment]
Getting the same error. Any fixes?

**Comment by Areahints** [comment]
Hello a @Nisthar I fixed by deleting the folder of the account in ~/InstaPy/logs. I also wrote a script that deletes the folder everyday and I've not had this problem anymore.
