### ISSUE TITLE
Error reading broker pipe (0x6D)

### ISSUE THREAD

**Issue by jat-x** [InstaPy/InstaPy#2276]
Hi everyone, I have this error when I try to run

INFO [2018-06-19 20:17:10] [useraccount]  Location [7/13]
INFO [2018-06-19 20:17:10] [useraccount]  --> b'1300584339959340'
[12020:7688:0619/201711.507:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
WARNING [2018-06-19 20:17:39] [useraccount]  **Too few images, skipping this location**
**********************************************************************
If raising an issue, please also upload the file located at:
C:\Users\User\AppData\Local\Temp\20180619-201739.html
**********************************************************************
[3228:8652:0619/201740.734:ERROR:broker_win.cc(57)] **Error reading broker pipe: ╩рэры с√ы чръЁ√Є. (0x6D)**
INFO [2018-06-19 20:17:46] [useraccount]  Session ended - 2018-06-19 20:17:46
INFO [2018-06-19 20:17:46] [useraccount]  --------------------

Traceback (most recent call last):
  File "C:\Users\User\Desktop\InstaPy-master-useraccount\1_useraccount-like.py", line 59, in <module>
    amount=12, skip_top_posts=True)
  File "C:\Users\User\Desktop\InstaPy-master-useraccount\instapy\instapy.py", line 796, in like_by_locations
    skip_top_posts)
  File "C:\Users\User\Desktop\InstaPy-master-useraccount\instapy\like_util.py", line 77, in get_links_for_location
    top_elements = browser.find_element_by_xpath('//main/article/div[1]')
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 385, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 955, in find_element
    'value': value})['value']
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//main/article/div[1]"}
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36.540470 (e522d04694c7ebea4ba8821272dbef4f9b818c91),platform=Windows NT 10.0.14393 x86_64)

**Comment by jat-x** [comment]
In the list of the function "like_by_locations" was a bad location id.
link: https://www.instagram.com/explore/locations/1300584339959340/
I just delete it and my code start working.
