### ISSUE TITLE
Error from Digital Ocean Docker

### ISSUE THREAD

**Issue by ericxor61a0c0d** [InstaPy/InstaPy#230]
Not too familiar with docker but I ran into this issue, tried the possible solution (uncommenting) and didn't work!

`
Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    InstaPy(username="***********",password="*******")\
  File "/InstaPy/instapy/instapy.py", line 37, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chro                                                                                                             me_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriv                                                                                                             er.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriv                                                                                                             er.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriv                                                                                                             er.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriv                                                                                                             er.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorha                                                                                                             ndler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome fa                                                                                                             iled to start: exited abnormally
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822c                                                                                                             c5),platform=Linux 4.4.0-71-generic x86_64)
`

**Comment by timgrossmann** [comment]
@ericchenmelt How much does your Droplet have?

**Comment by ericxor61a0c0d** [comment]
512 mb ram, I got the cheapest $5 a month one

**Comment by tibor** [comment]
You have to use a version with at least 1GB RAM, more would be better.

**Comment by ericxor61a0c0d** [comment]
Upgraded, still didn't work!

**Comment by timgrossmann** [comment]
@ericchenmelt You should start posting the error with every comment.
We can't read your mind...

Please post what error is thrown.

**Comment by pekapa** [comment]
@ericchenmelt 
Have you tried adding `nogui=True` to your InstaPy constructor?

**Comment by calebfornari** [comment]
@ericchenmelt When running with Docker you need a bit more than 1 GB memory. It works for me on a 2 GB server (AWS T2.Small), but was failing with this exact same error on a 1 GB DO droplet.
