### ISSUE TITLE
Hi Guys This my error 

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#2305]
Traceback (most recent call last):
  File "start.py", line 46, in <module>
    session.follow_user_followers(['tiboinshape','jujufitcats','justinegallice','stanimal9','antonao','carolineclnfit', 'fitbyclem','chloe_fit_','mmjhottie','__bigwill__'], amount=10, randomize=True, interact=True, sleep_delay=30)
  File "/Users/jonathanverdier/Desktop/Alpha/instapy/instapy.py", line 2055, in follow_user_followers
    self.logger)
  File "/Users/jonathanverdier/Desktop/Alpha/instapy/util.py", line 77, in validate_username
    followers_count, following_count = get_relationship_counts(browser, username, logger)
  File "/Users/jonathanverdier/Desktop/Alpha/instapy/util.py", line 513, in get_relationship_counts
    "//span[contains(@class,'g47SY')]")[1].text))
IndexError: list index out of range

**Comment by johnvfitness** [comment]
@uluQulu

**Comment by paul40322** [comment]
why is this closed?
