### ISSUE TITLE
Chromedriver error 'session'

### ISSUE THREAD

**Issue by quintendewilde** [InstaPy/InstaPy#2332]
```
python baenkovigori.py
ERROR [2018-06-29 13:29:00] [baenkov.igori]  Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Traceback (most recent call last):
  File "/home/toyama/InstaPy/instapy/instapy.py", line 297, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/toyama/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/home/toyama/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Traceback (most recent call last):
  File "baenkovigori.py", line 75, in <module>
    schedule.run_pending()
  File "/home/toyama/.local/lib/python2.7/site-packages/schedule/__init__.py", line 493, in run_pending
    default_scheduler.run_pending()
  File "/home/toyama/.local/lib/python2.7/site-packages/schedule/__init__.py", line 78, in run_pending
    self._run_job(job)
  File "/home/toyama/.local/lib/python2.7/site-packages/schedule/__init__.py", line 131, in _run_job
    ret = job.run()
  File "/home/toyama/.local/lib/python2.7/site-packages/schedule/__init__.py", line 411, in run
    ret = self.job_func()
  File "baenkovigori.py", line 64, in job
    session.end()
UnboundLocalError: local variable 'session' referenced before assignment
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7f1fcd2e8dd0>> ignored

In installed a fresh pull from master, and only copied the 'accounts'.py files in to place togheter with an unix version of chrome driver. It worked on my Imac. But with my unix I get this error from above.. 
Any help?

```

**Comment by the-unknown** [comment]
have you tried chmod 777 on "chromedriver"?

**Comment by CamiloB** [comment]
Hi did you fixed this?
