### ISSUE TITLE
ChromeDriver error after new pull

### ISSUE THREAD

**Issue by MrDebashis** [InstaPy/InstaPy#2369]
## Expected Behavior
It should work fine with latest code as chromedriver is well in place with chmod 777
## Current Behavior
Showing Chromedriver Error

ERROR [2018-07-04 13:42:42] [_youianddiy_]  Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.0-6-amd64 x86_64)
Traceback (most recent call last):
  File "/home/debas/InstaPy/instapy/instapy.py", line 297, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.0-6-amd64 x86_64)

Traceback (most recent call last):
  File "/home/debas/InstaPy/instapy/instapy.py", line 297, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.0-6-amd64 x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/debas/InstaPy/quickstart.py", line 21, in <module>
    nogui=True)
  File "/home/debas/InstaPy/instapy/instapy.py", line 190, in __init__
    self.set_selenium_local_session()
  File "/home/debas/InstaPy/instapy/instapy.py", line 301, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/debas/InstaPy/assets/chromedriver

**Comment by ghost** [comment]
please update the progect again.

**Comment by rabrez** [comment]
the same problem

**Comment by ghost** [comment]
please uncomment:

`chrome_options.add_argument('--no-sandbox')`

in your instapy.py

**Comment by MrDebashis** [comment]
please uncomment:

chrome_options.add_argument('--no-sandbox')

in your instapy.py

---this works

**Comment by ghost** [comment]
i'm glad you solve your problem, close the issue thanks.

**Comment by MrDebashis** [comment]
please uncomment:

chrome_options.add_argument('--no-sandbox')

in your instapy.py

---this works

**Comment by rabrez** [comment]
wheeeeyyyyyy... thanks a lot. perfect
