### ISSUE TITLE
Cant run the quickstart

### ISSUE THREAD

**Issue by yaca8** [InstaPy/InstaPy#2377]
Script was working fine until this morning, when I try to run the module I just get following traceback:

Traceback (most recent call last):
  File "C:\Users\xxx\Documents\GitHub\InstaPy\quickstart -ver follow by tags.py", line 22, in <module>
    multi_logs=True)
  File "C:\Users\xxx\Documents\GitHub\InstaPy\instapy\instapy.py", line 132, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "C:\Users\xxx\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 965, in load_follow_restriction
    return json.load(followResFile)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> 

Any idea what could have happened or how I can fix it? 
Thanks!

**Comment by marcomokastyle** [comment]
@yaca8 check the file "followRestriction.json" in your log folder, may be corrupted. If you have lost the content, is a little bit annoying but it can be restored from followedPool.csv maybe with a little bit of patience, regex and replace.

**Comment by yaca8** [comment]
@marcomokastyle  You were right, "followRestriction.json" has been corrupted, I've restored it from followedPool.csv as you advised and its working again. Thanks a lot!
