### ISSUE TITLE
chromedriver issue

### ISSUE THREAD

**Issue by S1mplyCompl3x** [InstaPy/InstaPy#2379]
## Expected Behavior
The script to start correctly and run through

## Current Behavior
The script throws the following error the second it is ran:

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.30 (7accc8730b0f99b5e7c0702ea89d1fa7c17bfe33),platform=Linux 4.14.50-v7+ armv7l)

Traceback (most recent call last):
  File "run.py", line 49, in <module>
    headless_browser=False)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 190, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 301, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/Projects/InstaPy/assets/chromedriver

## Possible Solution (optional)
Find correct chromedriver or chromium

## InstaPy configuration
    session.set_relationship_bounds(enabled=True,
				  delimit_by_numbers=True,
				   max_followers=4000)
    session.set_do_follow(enabled=True, percentage=30)
    session.like_by_tags(['xxx' ], amount=numLikes)

**Comment by LoudSoftware** [comment]
~~To add to that, I updated my chromedriver to 2.40.565383 and chrome to 67.0.3396.99 and I get the following stack trace:~~


~~ERROR [2018-07-05 13:07:14] [loudsoftware]  Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.4.0-122-generic x86_64)
Traceback (most recent call last):
  File "/home/nic/InstaPy/instapy/instapy.py", line 297, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.4.0-122-generic x86_64)~

Edit: Some log files were owned by root, causing me to have to run the script as root. Turns out if you set those log files to your user, and run without root, it works like a charm 😄

**Comment by wizel10** [comment]
@LoudSoftware not sure I follow your comment. You mean running the script as root shall work?

**Comment by LoudSoftware** [comment]
On the contrary @wizel10 running it as default user with the latest chrome and chromedriver versions works.

**Comment by Areahints** [comment]
Hello I'm having a similar problem

```Traceback (most recent call last):
  File "/root/InstaPy/instapy/util.py", line 430, in click_element
    element.click()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.4.0-130-generic x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "thetalent.py", line 40, in <module>
    session.follow_user_followers(['donjazzy', 'teknoofficial', '2niteflavour'], amount=25, randomize=False, sleep_delay=60)
  File "/root/InstaPy/instapy/instapy.py", line 2068, in follow_user_followers
    followed = self.follow_by_list(person, self.follow_times, sleep_delay, interact)
  File "/root/InstaPy/instapy/instapy.py", line 714, in follow_by_list
    element.click()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.4.0-130-generic x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "thetalent.py", line 40, in <module>
    session.follow_user_followers(['donjazzy', 'teknoofficial', '2niteflavour'], amount=25, randomize=False, sleep_delay=60)
  File "/root/InstaPy/instapy/instapy.py", line 2068, in follow_user_followers
    followed = self.follow_by_list(person, self.follow_times, sleep_delay, interact)
  File "/root/InstaPy/instapy/instapy.py", line 714, in follow_by_list
    self.logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 576, in follow_given_user
    click_element(browser, follow_button) # unfollow_button.send_keys("\n")
  File "/root/InstaPy/instapy/util.py", line 437, in click_element
    browser.execute_script("document.getElementsByClassName('" +  element.get_attribute("class") + "')[0].scrollIntoView({ inline: 'center' });")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 143, in get_attribute
    resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: no such session
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.4.0-130-generic x86_64)```

**Comment by Areahints** [comment]
from what I'm seeing, the culprit is chrome and it seems to be using far more resources than necessary 

> https://github.com/elgalu/docker-selenium/issues/20

> https://github.com/timgrossmann/InstaPy/issues/729

> https://github.com/SeleniumHQ/docker-selenium/issues/589

There are 3 alternatives I've seen so far

- Clear cookies and logs (all files except followRestriction.json)
- Set the default size of /dev/shm 
- Use Firefox instead

I'm going to clear cookies and update if it works!

**Comment by mhluska** [comment]
@Areahints did you end up solving this?
