### ISSUE TITLE
Having problems on Raspberry Pi3

### ISSUE THREAD

**Issue by lsaguiar** [InstaPy/InstaPy#238]
Dear All,

I follow the last installation packages and versions for InstaPy for my new Raspeberry PI, first I got a lot of erros but now just a few that I would like to share with you all to try InstaPy run on my micro computer.
That is what's show up on my terminal after I run InstaPy:

Traceback (most recent call last):
  File "index.py", line 1, in <module>
    from instapy import InstaPy
  File "/var/www/instapy/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/var/www/instapy/InstaPy/instapy/instapy.py", line 10, in <module>
    from .clarifai_util import check_image
  File "/var/www/instapy/InstaPy/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.client import ClarifaiApi
  File "build/bdist.linux-armv7l/egg/clarifai/client/__init__.py", line 5, in <module>
  File "build/bdist.linux-armv7l/egg/clarifai/client/client.py", line 4, in <module>
ImportError: No module named past.builtins

Any help?

Have a great day.
Best regards,
Leandro

**Comment by TheRealJAG** [comment]
How are you running this on the pi? I sorta got frustrated after not being able to install the chrome driver.

**Comment by lsaguiar** [comment]
I did follow the research on Google and   I had   install the chromedrive using sudo pip install and works. Now I'm  getting the messages of  my first post.

**Comment by TheRealJAG** [comment]
Can you tell me what the command was? As far as I know it's not compatible with the pi3.

**Comment by lsaguiar** [comment]
Sudo pip install  did  the job. I'm using raspberian distro.

**Comment by TheRealJAG** [comment]
Ok, I can reproduce. What version of python are you running? I'm getting the same error using Python 2.7.9

**Comment by lsaguiar** [comment]
I  had   up  to date  all  for  the last  version, 3.4  I  think.

**Comment by TheRealJAG** [comment]
What does python -V output? Your default python might be using 2.6

**Comment by TheRealJAG** [comment]
When I run 
 `sudo python3 quickstart.py`

I get the following error
`
Traceback (most recent call last):
  File "quickstart.py", line 24, in <module>
    .end()
  File "/home/pi/InstaPy/instapy/instapy.py", line 37, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x769e7610>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/common/service.py", line 163, in __del__
    self.stop()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/common/service.py", line 135, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'
`

**Comment by lsaguiar** [comment]
Python version 2.7.9 as yours

**Comment by TheRealJAG** [comment]
@lsaguiar try running sudo python3 quickstart.py and see what error you get.

**Comment by lsaguiar** [comment]
I had create index.py, and when I run that do those erros on my first post. Sorry I can't help you, let's wait help from here.

**Comment by TheRealJAG** [comment]
@lsaguiar You're getting those first errors cause you're not using the latest version of python.

**Comment by lsaguiar** [comment]
I update everything and I still get Python 2.7.9, any trick command?

**Comment by TheRealJAG** [comment]
@lsaguiar run and see what error you get.
`sudo python3 FILE.py`

**Comment by lsaguiar** [comment]
Trying with Python 3, I got these errors.

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "index.py", line 17, in <module>
    .end()
  File "/var/www/instapy/InstaPy/instapy/instapy.py", line 37, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/common/service.py", line 86, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by lsaguiar** [comment]
@TheRealJAG using your command I got this error:

python3: can't open file 'FILE.py': [Errno 2] No such file or directory

**Comment by TheRealJAG** [comment]
@lsaguiar Change FILE.py to whatever script you're testing.

**Comment by converge** [comment]
I changed instapy/instapy.py line 37
self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
to
self.browser = webdriver.Firefox()

worked fine in my linux server.

**Comment by ghost** [comment]
@converge I changed code to on line 37 to self.browser = webdriver.Firefox()

However, the code isn't executing on my raspberrypi out terminal. 

Using instapy/ Python3.6 scriptname.py  

It logs the session as started. However, it doesn't launch firefox. (I installed via terminal - sudo apt-get install python-pip iceweasel xvfb)

Any help would be appreciated.
