### ISSUE TITLE
Unfollow active unfollowers | KeyError: '07'

### ISSUE THREAD

**Issue by Nuzzo235** [InstaPy/InstaPy#2385]
## Current Behavior

Unfollow active unfollowers not working

Traceback (most recent call last):
  File "C:\Users\xxx\Documents\GitHub\InstaPy\quickstart.py", line 74, in <module>
    all_unfollowers, active_unfollowers = session.pick_unfollowers(username="xxx.yyy", compare_by="latest", live_match=True, store_locally=True, print_out=True)
  File "C:\Users\xxx\Documents\GitHub\InstaPy\instapy\instapy.py", line 2646, in pick_unfollowers
    self.logfolder)
  File "C:\Users\xxx\Documents\GitHub\InstaPy\instapy\relationship_tools.py", line 445, in get_unfollowers
    logfolder)
  File "C:\Users\xxx\Documents\GitHub\InstaPy\instapy\relationship_tools.py", line 868, in load_followers_data
    existing_days = list(day for day, entry in structured_entries["years"][entry_year]["months"][entry_month]["days"].items())
KeyError: '07'

## InstaPy configuration

```
all_unfollowers, active_unfollowers = session.pick_unfollowers(username="xxx.yyy", compare_by="latest", live_match=True, store_locally=True, print_out=True)

session.unfollow_users(amount=len(active_unfollowers), customList=(True, active_unfollowers, "all"), style="RANDOM", unfollow_after=None, sleep_delay=600)
```
Cheers

**Comment by Nuzzo235** [comment]
The problem was a corrupt JSON fIle in the log-folder. Works like a charm again.
