### ISSUE TITLE
Can't run the script , and i'm not familiar with python. Anyone know what's going on here ? 

### ISSUE THREAD

**Issue by sandrobridge** [InstaPy/InstaPy#2405]
Session started - 2018-07-10 16:45:17
Cookie file not found, creating cookie...
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    session.login()
  File "C:\Users\sandr\Desktop\InstaPy-master\instapy\instapy.py", line 328, in login
    self.bypass_suspicious_attempt):
  File "C:\Users\sandr\Desktop\InstaPy-master\instapy\login_util.py", line 136, in login_user
    "//select[@class='hztqj']/option[text()='English']").click()
  File "D:\Python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "D:\Python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "D:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "D:\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.17134 x86_64)

**Comment by Nuzzo235** [comment]
@sandrobridge Upgrading the chromedriver in /assets folder to a newer version should work as a first option. (https://sites.google.com/a/chromium.org/chromedriver/downloads)

**Comment by maraoz** [comment]
I'm having the same issue with the latest chromedriver :(
