### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by waseem312** [InstaPy/InstaPy#2407]
I am getting this error that module _sqlite not found and sqlite is already installed.

Traceback (most recent call last):
  File "quickstart.py", line 7, in <module>
    from instapy import InstaPy
  File "/var/www/html/kingstagram/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/var/www/html/kingstagram/InstaPy/instapy/instapy.py", line 22, in <module>
    from .comment_util import comment_image
  File "/var/www/html/kingstagram/InstaPy/instapy/comment_util.py", line 5, in <module>
    from .util import update_activity
  File "/var/www/html/kingstagram/InstaPy/instapy/util.py", line 7, in <module>
    import sqlite3
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)

**Comment by abendy** [comment]
I'm receiving this error (checked out the repository and installed today). I've tried several different python versions in a virtual env.
