### ISSUE TITLE
Chromedrive error

### ISSUE THREAD

**Issue by khaleefaalhammadi** [InstaPy/InstaPy#2424]
Dear Programmer,

I'm getting the below error always

InstaPy Process
Error: ERROR [2018-07-14 20:26:39] [Shj_ad_2020] Message: unknown error: cannot find Chrome binary
 (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.3 x86_64)
 Traceback (most recent call last):
 File "C:\Instabot\5\InstaPy-master\instapy\instapy.py", line 297, in set_selenium_local_session
 chrome_options=chrome_options)
 File "C:\Users\Um Khaled\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium-2.53.6-py3.7.egg\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
 desired_capabilities=desired_capabilities)
 File "C:\Users\Um Khaled\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium-2.53.6-py3.7.egg\selenium\webdriver\remote\webdriver.py", line 90, in __init__
 self.start_session(desired_capabilities, browser_profile)
 File "C:\Users\Um Khaled\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium-2.53.6-py3.7.egg\selenium\webdriver\remote\webdriver.py", line 177, in start_session
 response = self.execute(Command.NEW_SESSION, capabilities)
 File "C:\Users\Um Khaled\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium-2.53.6-py3.7.egg\selenium\webdriver\remote\webdriver.py", line 236, in execute
 self.error_handler.check_response(response)
 File "C:\Users\Um Khaled\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium-2.53.6-py3.7.egg\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
 (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.3 x86_64)
 
 Traceback (most recent call last):
 File "C:\Instabot\5\InstaPy-master\instapy\instapy.py", line 297, in set_selenium_local_session
 chrome_options=chrome_options)
 File "C:\Users\Um Khaled\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium-2.53.6-py3.7.egg\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
 desired_capabilities=desired_capabilities)
 File "C:\Users\Um Khaled\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium-2.53.6-py3.7.egg\selenium\webdriver\remote\webdriver.py", line 90, in __init__
 self.start_session(desired_capabilities, browser_profile)
 File "C:\Users\Um Khaled\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium-2.53.6-py3.7.egg\selenium\webdriver\remote\webdriver.py", line 177, in start_session
 response = self.execute(Command.NEW_SESSION, capabilities)
 File "C:\Users\Um Khaled\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium-2.53.6-py3.7.egg\selenium\webdriver\remote\webdriver.py", line 236, in execute
 self.error_handler.check_response(response)
 File "C:\Users\Um Khaled\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium-2.53.6-py3.7.egg\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
 (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.3 x86_64)
 
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
 File "quickstart.py", line 3, in <module>
 session = InstaPy(username='Shj_ad_2020', password='A123456a')
 File "C:\Instabot\5\InstaPy-master\instapy\instapy.py", line 190, in __init__
 self.set_selenium_local_session()
 File "C:\Instabot\5\InstaPy-master\instapy\instapy.py", line 301, in set_selenium_local_session
 Settings.chromedriver_location))
 instapy.instapy.InstaPyError: ensure chromedriver is installed at C:\Instabot\5\InstaPy-master\assets\chromedriver
InstaPy ended Stop

**Comment by brocool** [comment]
that may seem stupid to do, but delete everything, like backup all your files and then re-install your windows version or whatever you have... that's what i did because i was desperate.
