### ISSUE TITLE
Cant seem to get past initial login page 

### ISSUE THREAD

**Issue by Tuscanae** [InstaPy/InstaPy#2425]
#########################
Cookie file not found, creating cookie...

Error: INFO [2018-07-14 19:45:19] [mattspics_] Session started - 2018-07-14 19:45:19
 WARNING [2018-07-14 19:45:19] [mattspics_] Sorry, Record Activity is not working on Windows. We're working to fix this soon!
 Traceback (most recent call last):
 File "quickstart.py", line 5, in <module>
 session.login()
 File "C:\Users\Small\Desktop\InstaPy-master\instapy\instapy.py", line 322, in login
 self.bypass_suspicious_attempt):
 File "C:\Users\Small\Desktop\InstaPy-master\instapy\login_util.py", line 136, in login_user
 "//select[@class='_fsoey']/option[text()='English']").click()
 File "D:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 387, in find_element_by_xpath
 return self.find_element(by=By.XPATH, value=xpath)
 File "D:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 957, in find_element
 'value': value})['value']
 File "D:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 314, in execute
 self.error_handler.check_response(response)
 File "D:\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='_fsoey']/option[text()='English']"}
 (Session info: chrome=67.0.3396.99)
 (Driver info: chromedriver=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9),platform=Windows NT 10.0.16299 x86_64)
#########################

This appears after launching the Insta.py GUI program, the login information is correct and the program proceeds to open instagram however only to the very initial screen but does not log in, after 10 seconds this error message is produced. The same happens when I try to use the quickstart.py file 

I'm pretty new so apologies if its an obvious error on my part

**Comment by Running-VincentW** [comment]
Seems like I've got the same issue recently
The latest InstaPy dependencies seems to have fixed the problem, try downloading the latest version.

**Comment by Running-VincentW** [comment]
Okay found a solution. This is caused by a malfunction in changing the Instagram web page to English. Use the following instead.
instapy/login_util.py:131
`browser.find_element_by_xpath(
          "//*[@id='react-root']/section/footer/div/nav/ul/li[11]/span/select/option[6]").click()`

**Comment by astritshuli** [comment]
[8616:3932:0717/232444.801:ERROR:shader_disk_cache.cc(237)] Failed to create shader cache entry: -2
Cookie file not found, creating cookie...

Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.login()
  File "C:\Users\GridComputers\InstaPy\instapy\instapy.py", line 347, in login
    self.bypass_suspicious_attempt):
  File "C:\Users\GridComputers\InstaPy\instapy\login_util.py", line 136, in login_user
    "//select[@class='hztqj']/option[text()='English']").click()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.17134 x86_64)

PS C:\Users\GridComputers\InstaPy>
