### ISSUE TITLE
Bot stopped working after a few minutes

### ISSUE THREAD

**Issue by Stewler** [InstaPy/InstaPy#2433]
## Expected Behavior
Bot to work 24/7
## Current Behavior
Bot is working for 20 minutes then receiving the following error:
```
TypeError: unfollow_users() got an unexpected keyword argument 'onlyInstapyFollowed'
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x000001B72DFA7208>>
Traceback (most recent call last):
  File "C:\Users\dvlav\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 163, in __del__
  File "C:\Users\dvlav\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 139, in stop
  File "C:\Users\dvlav\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down
```
## InstaPy configuration
```
from instapy import InstaPy

session = InstaPy(username='XXX', password='XXX')

session.login()

zx = True
while zx==True:   # it will repeat actions forever, cos `zx` is equal to the value of `True`, above
    session.set_do_follow(enabled=True, percentage=30, times=1)
    
    session.like_by_tags(['summertime', 'tb', 'throwback', 'holidays', 'relax', 'лето', 'water', 'ocean', 'gorgeous', 'perfect', 'eyes', 'color', 'lovely', 'nice', 'picture', 'portrait', 'greece'], amount=10, media='Photo')
    session.like_by_locations(['213087839/sochi-russia/','219151927/heraklion-greece','212893191/cancun-quintana-roo/','214179276/minsk-belarus/','264915885/israel/','213041503/tel-aviv-israel'], amount=15, media=None)

    session.follow_user_followers(['doyoutravel', 'jayalvarrez'], amount=5, sleep_delay=60, randomize=True, interact=False)
    session.follow_by_list(['doyoutravel', 'jayalvarrez', 'cristiano'], times=5)
    session.unfollow_users(amount=100, onlyInstapyFollowed=True, sleep_delay=1, unfollow_after=3030, onlyInstapyMethod = 'FIFO', onlyNotFollowMe=True)
   

session.end()

```

**Comment by Stewler** [comment]
Anyone?

**Comment by Luisjanz** [comment]
Same Problem!!!!
