### ISSUE TITLE
 File "quickstart.py", line 7, in <module>     from instapy import InstaPy

### ISSUE THREAD

**Issue by astritshuli** [InstaPy/InstaPy#2446]
I followed every step on how to windows and 
I have this error when i run python quickstart.py on powershell . 
---
Traceback (most recent call last):
  File "quickstart.py", line 7, in <module>
    from instapy import InstaPy
  File "C:\Users\GridComputers\InstaPy\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "C:\Users\GridComputers\InstaPy\instapy\instapy.py", line 19, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by waseem-brinsi** [comment]
I have the same problem  @timgrossmann help
