### ISSUE TITLE
Error first launch on windows 10

### ISSUE THREAD

**Issue by marcspartacus** [InstaPy/InstaPy#2451]
## Expected Behavior
I trying to launch an example of the bot as it is available in the files :)
## Current Behavior
PS C:\Users\Marco> & python c:/Users/Marco/Downloads/instabot.py-master/test1bot.py
18.07.2018_09:09 Instabot v1.2.0 started at 18.07.2018 09:09:

18.07.2018_09:09 Trying to login as 1_astuce_insta_par_jour...

Traceback (most recent call last):
  File "c:/Users/Marco/Downloads/instabot.py-master/test1bot.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "c:\Users\Marco\Downloads\instabot.py-master\src\instabot.py", line 232, in __init__
    self.login()
  File "c:\Users\Marco\Downloads\instabot.py-master\src\instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\Marco\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Marco\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
PS C:\Users\Marco>

## Possible Solution (optional)
I think i'm just missing something simple... thanks a lot for your help with you guys i'll throw away follow liker ahah 

## InstaPy configuration
windows 10 64bit

**Comment by DavidMolinari** [comment]
This is InstaPy and not Instabot :>
