### ISSUE TITLE
NEW/Again: App fails to start after last pull 19.07

### ISSUE THREAD

**Issue by michaelBielang** [InstaPy/InstaPy#2474]
Hi,

like recently, what was fixed with the help of some nice guys, I get now again exceptions after I have executed a new pull right now. I actually expected this issue to be fixed but it doesn't look like.

So what to do this time please? (Don't suggest chrom-driver, this is not the Issue ;))

```
ERROR [2018-07-19 18:31:29] [i_am_a_user]  Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.15.0-24-generic x86_64)
Traceback (most recent call last):
  File "/home/usern/venv/bin/InstaPy/instapy/instapy.py", line 296, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.15.0-24-generic x86_64)

Traceback (most recent call last):
  File "/home/usern/venv/bin/InstaPy/instapy/instapy.py", line 296, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.15.0-24-generic x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    multi_logs=True)
  File "/home/usern/venv/bin/InstaPy/instapy/instapy.py", line 189, in __init__
    self.set_selenium_local_session()
  File "/home/usern/venv/bin/InstaPy/instapy/instapy.py", line 300, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/usern/venv/bin/InstaPy/assets/chromedriver

```

This, in instapy.py fix still does help me, but I think, this should be in the master as well?

```
def set_selenium_local_session(self):
    """Starts local session for a selenium server.
    Default case scenario."""
    if self.aborting:
        return self

    if self.use_firefox:
        if self.browser_profile_path is not None:
            firefox_profile = webdriver.FirefoxProfile(
                self.browser_profile_path)
        else:
            firefox_profile = webdriver.FirefoxProfile()

        # permissions.default.image = 2: Disable images load,
        # this setting can improve pageload & save bandwidth
        firefox_profile.set_preference('permissions.default.image', 2)

        if self.proxy_address and int(self.proxy_port) > 0:
            firefox_profile.set_preference('network.proxy.type', 1)
            firefox_profile.set_preference('network.proxy.http',
                                           self.proxy_address)
            firefox_profile.set_preference('network.proxy.http_port',
                                           self.proxy_port)
            firefox_profile.set_preference('network.proxy.ssl',
                                           self.proxy_address)
            firefox_profile.set_preference('network.proxy.ssl_port',
                                           self.proxy_port)

        self.browser = webdriver.Firefox(firefox_profile=firefox_profile)

    else:
        chromedriver_location = Settings.chromedriver_location
        chrome_options = Options()
        #chrome_options.add_argument("--disable-infobars")
        chrome_options.add_argument("--mute-audio")
        chrome_options.add_argument('--dns-prefetch-disable')
        #chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument('--lang=en-US')
        chrome_options.add_argument('--disable-setuid-sandbox')

        # this option implements Chrome Headless, a new (late 2017)
        # GUI-less browser. chromedriver 2.9 and above required
        if self.headless_browser:
            chrome_options.add_argument('--headless')
            # Replaces browser User Agent from "HeadlessChrome".
            user_agent = "Chrome"
            chrome_options.add_argument('user-agent={user_agent}'
                                        .format(user_agent=user_agent))
        capabilities = DesiredCapabilities.CHROME
        # Proxy for chrome
        if self.proxy_address and int(self.proxy_port) > 0:
            prox = Proxy()
            proxy = ":".join([self.proxy_address, self.proxy_port])
            prox.proxy_type = ProxyType.MANUAL
            prox.http_proxy = proxy
            prox.socks_proxy = proxy
            prox.ssl_proxy = proxy
            prox.add_to_capabilities(capabilities)

        # add proxy extension
        if self.proxy_chrome_extension and not self.headless_browser:
            chrome_options.add_extension(self.proxy_chrome_extension)

        if self.browser_profile_path is not None:
            chrome_options.add_argument('user-data-dir={}'.format(self.browser_profile_path))

        chrome_prefs = {
            'intl.accept_languages': 'en-US'
        }
        chrome_options.add_experimental_option('prefs', chrome_prefs)


        chrome_options.add_argument('--headless')
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument('--disable-dev-shm-usage')

        try:

            self.browser = webdriver.Chrome(chromedriver_location,chrome_options=chrome_options)

            # self.browser = webdriver.Chrome(chromedriver_location,
            #                                 desired_capabilities=capabilities,
            #                                 chrome_options=chrome_options)
        except selenium.common.exceptions.WebDriverException as exc:
            self.logger.exception(exc)
            raise InstaPyError('ensure chromedriver is installed at {}'.format(
                Settings.chromedriver_location))

        # prevent: Message: unknown error: call function result missing 'value'
        matches = re.match(r'^(\d+\.\d+)',
                           self.browser.capabilities['chrome']['chromedriverVersion'])
        if float(matches.groups()[0]) < Settings.chromedriver_min_version:
            raise InstaPyError('chromedriver {} is not supported, expects {}+'.format(
                float(matches.groups()[0]), Settings.chromedriver_min_version))

    self.browser.implicitly_wait(self.page_delay)

    message = "Session started!"
    highlight_print(self.username, message, "initialization", "info", self.logger)
    print('')

    return self
```

**Comment by narchiii** [comment]
I'm getting the same error

**Comment by michaelBielang** [comment]
I have just made a clean installation, with a clean os. And this also has this issue. So the master is actually really buggy right now 🔢

**Comment by PJUllrich** [comment]
And make sure that you actually have chrome installed
You can install it on Debian like explained [here](https://github.com/timgrossmann/InstaPy/issues/2179#issuecomment-397460795)
