### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by rosnick** [InstaPy/InstaPy#2489]
Hello, I'm a newbie so I  know that it's gonna be a stupid error. 
I'm trying to run the example.py with some delete of some function but I had this error on the console:
Mac-mini-di-Rosario:~ rosario$ cd desktop
Mac-mini-di-Rosario:desktop rosario$ cd instapy-master
Mac-mini-di-Rosario:instapy-master rosario$ cd instapy
Mac-mini-di-Rosario:instapy rosario$ python example1.py
Traceback (most recent call last):
  File "example1.py", line 3, in <module>
    from instapy import InstaPy
  File "/Users/rosario/Desktop/InstaPy-master/instapy/instapy.py", line 21, in <module>
    from .clarifai_util import check_image
ValueError: Attempted relative import in non-package
Mac-mini-di-Rosario:instapy rosario$ 

Can someone help? Thanks

**Comment by rosnick** [comment]
up
