### ISSUE TITLE
OS X Crontab error 

### ISSUE THREAD

**Issue by 99willy99** [InstaPy/InstaPy#251]
Hi, I'm setting up a cron job to run the script but I get this error

```
Traceback (most recent call last):
  File "/Users/xxxxx/xxxxx/instapy/quickstart.py", line 16, in <module>
    InstaPy(username="xxxxx", password="xxxxx") \
  File "/Users/xxxxx/Projects/instapy/instapy/instapy.py", line 37, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH.
```
I tried to include `PATH=/Users/xxxxx/Projects/instapy/assets` at the beginning of my crontab but it didn't work. Any idea?

**Comment by tibor** [comment]
Try `cd` to your InstaPy folder first and call your script from there.

Something like:
`0 0 * * * cd /home/InstaPy && python QuickStart.py`
should work as mentioned in #205

**Comment by converge** [comment]
@tibor is there a way to log the cron output with multiple cron commands ?

**Comment by tibor** [comment]
Hi,

you can log the cron output like so:
`0 0 * * * cd /home/InstaPy && python QuickStart.py >> /home/InstaPy/log.txt 2>&1`
