### ISSUE TITLE
session.follow_user_followers error 

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#2522]
Traceback (most recent call last):
  File "start.py", line 47, in <module>
    session.follow_user_followers(['tiboinshape','jujufitcats','justinegallice','stanimal9','antonao','carolineclnfit', 'fitbyclem','chloe_fit_','mmjhottie','__bigwill__'], amount=10, randomize=True, interact=True, sleep_delay=260)
  File "/Users/jonathanverdier/Desktop/Valentin/instapy/instapy.py", line 2040, in follow_user_followers
    self.logfolder)
  File "/Users/jonathanverdier/Desktop/Valentin/instapy/unfollow_util.py", line 867, in get_given_user_followers
    simulation, channel, logger, logfolder)
  File "/Users/jonathanverdier/Desktop/Valentin/instapy/unfollow_util.py", line 678, in get_users_through_dialog
    if quick_username[0] not in simulated_list:
IndexError: list index out of range

**Comment by Yaxit** [comment]
How did you solve, mate?

**Comment by johnvfitness** [comment]
Yes mate Thx

**Comment by Yaxit** [comment]
How? :)
comment as-tu résolu?

**Comment by johnvfitness** [comment]
Moi c’était simplement un problème de mauvaise connexion au final

**Comment by sunnygill** [comment]
can you please post the solution for it in English :-)

**Comment by Yaxit** [comment]
Thought to be a network issue. I confirm the issue disappeared by itself.
