### ISSUE TITLE
where is the problem???

### ISSUE THREAD

**Issue by mcallist3r** [InstaPy/InstaPy#2525]
Hi, im trying to use this, this is my error message..

24.07.2018_19:53 Trying to login as xxx...

Traceback (most recent call last):
  File "C:\Users\xxx\Documents\GitHub\instabot.py\example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\xxx\Documents\GitHub\instabot.py\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\xxx\Documents\GitHub\instabot.py\src\instabot.py", line 285, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
[Finished in 0.5s with exit code 1]

thanks a lot

**Comment by mcallist3r** [comment]
allways the same problem, with 2 accounts, the same
