### ISSUE TITLE
I keep getting 'chromedriver' executable needs to be in PATH

### ISSUE THREAD

**Issue by GregBorrelly** [InstaPy/InstaPy#253]
`>>> from instapy import InstaPy
>>> session = InstaPy(username='test', password='test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "instapy/instapy.py", line 37, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

`

**Comment by converge** [comment]
is chromedriver file at assets/ folder ?

**Comment by thebitbrine** [comment]
Same issue.

**Comment by GregBorrelly** [comment]
Solved !!
