### ISSUE TITLE
nothing work

### ISSUE THREAD

**Issue by AntoineIN** [InstaPy/InstaPy#2560]
Try to reconfigure my instapy after this weeks bug...

And right now, nothing work. I reinstall all the project, and nothing.

i got : 
"instapy.instapy.InstaPyError: ensure chromedriver is installed at /root/InstaPy/assets/chromedriver"

Thanks

**Comment by Deret007** [comment]
For me the same. Nothing works. This is my log.

`ERROR [2018-07-29 00:09:16] [kafevklidu]  Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 3.16.0-5-amd64 x86_64)
Traceback (most recent call last):
  File "/root/InstaPy/instapy/instapy.py", line 297, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 3.16.0-5-amd64 x86_64)`

**Comment by HCWcoder** [comment]
u need to download chromdriver.exe and put it in the assets folder

**Comment by PJUllrich** [comment]
And make sure that you actually have chrome installed
You can install it on Debian like explained [here](https://github.com/timgrossmann/InstaPy/issues/2179#issuecomment-397460795)
