### ISSUE TITLE
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href,'followers')]/span"}

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2568]
Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/unfollow_util.py", line 817, in get_given_user_followers
    allfollowers = format_number(browser.find_element_by_xpath("//a[contains"
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href,'followers')]/span"}
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-23-generic x86_64)

**Comment by tifDev** [comment]
same

**Comment by Marichka310** [comment]
The same issue :(
