### ISSUE TITLE
Error occured while getting a DB for 'None'

### ISSUE THREAD

**Issue by luigifaticoso** [InstaPy/InstaPy#2574]
Did you find the same error? something has meesed up with last commits

```
Wah! Error occured while getting a DB for 'None':
	b'unable to open database file'
Traceback (most recent call last):
  File "pippo.py", line 27, in <module>
    multi_logs=True)
  File "/Users/luigicali/Proejcts/InstaPy/instapy/instapy.py", line 192, in __init__
    get_db(True)
  File "/Users/luigicali/Proejcts/InstaPy/instapy/database_engine.py", line 65, in get_db
    if conn:
UnboundLocalError: local variable 'conn' referenced before assignment


```

**Comment by luigifaticoso** [comment]
adding a folder called 'db' has worked !

**Comment by anselayala** [comment]
Thank you for this, it worked instantly...
