### ISSUE TITLE
Could not locate Chrome: Message: timeout   (Session info: chrome=68.0.3440.75)   (Driver info: chromedriver=2.38.552522 

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2594]
WARNING [2018-08-01 10:54:10] [xxx]  Could not locate Chrome: Message: timeout
  (Session info: chrome=68.0.3440.75)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-29-generic x86_64)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-01 10:54:10] [xxx]  Session ended - 2018-08-01 10:54:10
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/quickstart.py", line 26, in <module>
    session.follow_user_followers(['John Travolta','thehughjackman','thehughjackman','johntravolta','michaelbuble','j_corden'], amount=40, randomize=False, interact=True)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 2079, in follow_user_followers
    followed = self.follow_by_list(person, self.follow_times, sleep_delay, interact)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 720, in follow_by_list
    self.logfolder)
  File "/home/fredrik/InstaPy/instapy/unfollow_util.py", line 557, in follow_given_user
    web_adress_navigator(browser, user_link)
  File "/home/fredrik/InstaPy/instapy/util.py", line 584, in web_adress_navigator
    browser.get(link)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=68.0.3440.75)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-29-generic x86_64)

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7fae7ecb3f60>>
Traceback (most recent call last):
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 163, in __del__
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 139, in stop
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by fgisslen** [comment]
Why does this happen?

**Comment by sionking** [comment]
update the cjhrome driver to 40-41

**Comment by fgisslen** [comment]
@sionking how do I do that?
Running on ubuntu, I have chromedriver in assets but I think also insalled on computer

**Comment by tompicca** [comment]
I have the same problem

`WARNING [2018-08-03 21:16:30] [awsmplace]  Could not locate Chrome: Message: timeout
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.13.4 x86_64)`

Any solution?

**Comment by fgisslen** [comment]
Hi, my problem still exists.
I now use chrome 68.***** and chromedriver 2.41.***

Any solution for this.

It just happens in the middle of the script.

**Comment by fgisslen** [comment]
@sionking
