### ISSUE TITLE
Sig handler is broken when instapy is not the main thread.

### ISSUE THREAD

**Issue by jaybocc2** [InstaPy/InstaPy#2595]
## Expected Behavior
Instapy to keep running without errors
## Current Behavior
Instapy eventually throws an error trying to capture a signal 
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/jaybocc2/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/jaybocc2/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "quickstart.py", line 244, in worker
    instabot.run_job(job)
  File "quickstart.py", line 133, in run_job
    session.end()
  File "/home/jaybocc2/.pyenv/versions/instabotter/lib/python3.6/site-packages/instapy/instapy.py", line 2718, in end
    with interruption_handler():
  File "/home/jaybocc2/.pyenv/versions/3.6.5/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/jaybocc2/.pyenv/versions/instabotter/lib/python3.6/site-packages/instapy/util.py", line 599, in interruption_handler
    original_handler = signal.signal(SIG_type, handler)
  File "/home/jaybocc2/.pyenv/versions/3.6.5/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

**Comment by sionking** [comment]
sing works only in main theered ... multilog ppl .... find a solution
