### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dpashutskii** [InstaPy/InstaPy#2602]
## Expected Behavior
Script starts correctly

## Current Behavior
After `python3 quickstart.py` I've got an error:
```
Traceback (most recent call last):
  File "quickstart.py", line 47, in <module>
    session.set_dont_unfollow_active_users(enabled=True, posts=10)
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 2555, in set_dont_unfollow_active_users
    self.logger)
  File "/home/ubuntu/InstaPy/instapy/util.py", line 221, in get_active_users
    "//span[contains(@class,'g47SY')]")[0].text)
IndexError: list index out of range
```
After commenting ` session.set_dont_unfollow_active_users(enabled=True, posts=10)` everything works fine

## InstaPy configuration
```
session = InstaPy(username=insta_username,
                  password=insta_password,
                  multi_logs=True,
                  nogui=True,
                  headless_browser=True)

# settings
    session.set_relationship_bounds(
        enabled=True,
        potency_ratio=1.21,
        delimit_by_numbers=True,
        max_followers=None,
        max_following=None,
        min_followers=45,
        min_following=77
    )
    session.set_do_comment(enabled=True, percentage=10)
    session.set_comments(
        ['Amazing!'],
        media='Photo'
    )
    session.set_smart_hashtags(['travel'], limit=15, sort='random', log_tags=True)
    session.set_dont_unfollow_active_users(enabled=True, posts=10)
    session.set_user_interact(amount=3, randomize=True, percentage=70, media='Photo')

    # actions
    session.follow_user_followers(
        ['wanderersand'],
        amount=10,
        randomize=True,
        interact=True,
        sleep_delay=600
    )
    session.like_by_tags(amount=10, use_smart_hashtags=True)
    session.unfollow_users(
        amount=60,
        InstapyFollowed=(True, "nonfollowers"),
        style="FIFO",
        unfollow_after=50*60*60,
        sleep_delay=501
    )
```

**Comment by spikeyhair** [comment]
I notice this error came out intermittently but sometimes I can have the bot to run for a week without issue. Could it be network connection that caused it?

**Comment by dpashutskii** [comment]
Hey @spikeyhair, thanks for the comment. I really doubt the network connection cased that error because I've tried to run it on the AWS.

**Comment by ghost** [comment]
same problem here

**Comment by dpashutskii** [comment]
The issue solved
