### ISSUE TITLE
The bot randomly stopped at Simulated follow

### ISSUE THREAD

**Issue by spikeyhair** [InstaPy/InstaPy#2613]
## Expected Behavior
Just go on after Simulated follow a few people

## Current Behavior
It randomly failed at Simulated follow. Not all Simulated follow will fail but just randomly. Therefore the bot gets terminated and stopped running.

Anyone facing this issue?

**Comment by spikeyhair** [comment]
This is the error message:
Traceback (most recent call last):
  File "quickstart.py", line 175, in <module>
    session.follow_user_following("user1", amount=5, randomize=True, sleep_delay=60)
  File "D:\Dropbox\Instapy\instapy\instapy.py", line 2154, in follow_user_follow
ing
    self.logfolder)
  File "D:\Dropbox\Instapy\instapy\unfollow_util.py", line 948, in get_given_use
r_following
    channel, logger, logfolder)
  File "D:\Dropbox\Instapy\instapy\unfollow_util.py", line 679, in get_users_thr
ough_dialog
    if quick_username[0] not in simulated_list:
IndexError: list index out of range
Press any key to continue . . .

**Comment by uluQulu** [comment]
Hi @spikeyhair 
It is being discussed at #2555.  

Feel free to join the troubleshooting discussion there! 🙋🏼‍♂️
