### ISSUE TITLE
InstaPy on Raspberry Pi3  ImportError: No module named configparser

### ISSUE THREAD

**Issue by x225am** [InstaPy/InstaPy#2616]
Hi All, I have issue on starting instaPy on my Raspberry Pi3 
This is I am starting quickstart.py

pi@SPiScreen:~/Projects/InstaPy $ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 7, in <module>
    from instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 21, in <module>
    from .clarifai_util import check_image
  File "/home/pi/Projects/InstaPy/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Image as ClImage
  File "/usr/local/lib/python2.7/dist-packages/clarifai/rest/__init__.py", line 3, in <module>
    from .client import ApiClient, ApiError, UserError, TokenError
  File "/usr/local/lib/python2.7/dist-packages/clarifai/rest/client.py", line 19, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser

I have flowed instructions on this link:

https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md

However can not make it working.
Any idea how to fix it?
Thanks in advance

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)
