### ISSUE TITLE
Exception like by tags

### ISSUE THREAD

**Issue by michaelBielang** [InstaPy/InstaPy#2625]
I have here an error I cannot fix on my own because I don't understand why it is caused. Can anyone help please?

## Expected Behavior
should run 
## Current Behavior

Traceback (most recent call last):
  File "quickstart.py", line 153, in <module>
    amount=3)
  File "/home/user/venv/bin/InstaPy/instapy/instapy.py", line 1241, in like_by_tags
    web_adress_navigator(self.browser, link)
  File "/home/user/venv/bin/InstaPy/instapy/util.py", line 598, in web_adress_navigator
    browser.get(link)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=68.0.3440.84)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-24-generic x86_64)

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7f38596a39e8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 163, in __del__
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 139, in stop
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by rodriguesprobr** [comment]
Did you try to delete the cookie file from this account after running the bot?
