### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#2631]
Hello, i often get this error, anyone please ? (i got last files)
it happens randomly

Traceback (most recent call last):
  File "/Users/Edhim/Desktop/INSTAPY/LentillesMaroc/quickstart.py", line 41, in <module>
    session.follow_user_followers(['xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx'], amount=10, randomize=True, sleep_delay=60)
  File "/Users/INSTAPY/LentillesMaroc/instapy/instapy.py", line 2034, in follow_user_followers
    self.logfolder)
  File "/Users/INSTAPY/LentillesMaroc/instapy/unfollow_util.py", line 869, in get_given_user_followers
    channel, logger, logfolder)
  File "/Users/INSTAPY/LentillesMaroc/instapy/unfollow_util.py", line 679, in get_users_through_dialog
    if quick_username[0] not in simulated_list:
IndexError: list index out of range

@uluQulu 

Thanks.

**Comment by uluQulu** [comment]
Hey @Edhim 
It has already been solved at https://github.com/timgrossmann/InstaPy/issues/2555#issuecomment-410475845

>It would be great if you could PR it.

-------

Cheers 😁

**Comment by Edhim** [comment]
Thank @uluQulu  :D
