### ISSUE TITLE
After last update

### ISSUE THREAD

**Issue by collaxd** [InstaPy/InstaPy#2632]
## Expected Behavior
$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 7, in <module>
    from instapy import InstaPy
  File "C:\Users\xxx\Desktop\Arquivos InstaGram\InstaPy\xxx\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "C:\Users\xxx\Desktop\Arquivos InstaGram\InstaPy\xxx\instapy\instapy.py", line 22, in <module>
    from .comment_util import comment_image
  File "C:\Users\xxx\Desktop\Arquivos InstaGram\InstaPy\xxx\instapy\comment_util.py", line 5, in <module>
    from .util import update_activity
  File "C:\Users\xxx\Desktop\Arquivos InstaGram\InstaPy\xxx\instapy\util.py", line 16, in <module>
    from .database_engine import get_database
ImportError: cannot import name 'get_database' from 'instapy.database_engine' (C:\Users\xxx\Desktop\Arquivos InstaGram\InstaPy\xxx\instapy\database_engine.py)

## InstaPy configuration

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=False,
				 potency_ratio=-0.9,
				  delimit_by_numbers=True,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['TOP!', 'SHOW!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.unfollow_users(amount=4000, allFollowing=True, style="LIFO", unfollow_after=3*60*60, sleep_delay=300)

**Comment by mrrobotsca** [comment]
same here
