### ISSUE TITLE
Can't seem to get it to work on raspberry pi 3

### ISSUE THREAD

**Issue by krmstrong322** [InstaPy/InstaPy#2637]
## Expected Behavior

When I run the quickstart.py I get this error, I''ve tried a few solutions I have found but none seem to work for me.
 

Traceback (most recent call last):
  File "quickstart.py", line 20, in <module>
    password=insta_password)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 192, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 299, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 61, in __init__
    self.service.start()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 62, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by ofurman** [comment]
same issue

**Comment by timm83** [comment]
same issue, anyone?

**Comment by gitpatrickhub** [comment]
Have you tried;
sudo python3 quickstart.py
