### ISSUE TITLE
Problem with run quickstart - chromedriver crashed

### ISSUE THREAD

**Issue by DarkSaTla** [InstaPy/InstaPy#2640]
Hey,
i tried to install the instapy, i downloaded all the pip needed i did anything, but nothing work heres my error:

WARNING [2018-08-06 20:10:11] [None]  Heeh! Error occured while getting a DB profile for 'None':
        b'NOT NULL constraint failed: profiles.name'
ERROR [2018-08-06 20:10:12] [None]  Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.4.0-97-generic x86_64)
Traceback (most recent call last):
  File "/root/InstaPy/instapy/instapy.py", line 299, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.4.0-97-generic x86_64)

Traceback (most recent call last):
  File "/root/InstaPy/instapy/instapy.py", line 299, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.4.0-97-generic x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/root/InstaPy/instapy/instapy.py", line 192, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 303, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /root/InstaPy/assets/chromedriver

if someone can help me thanks :)

**Comment by fxmeister** [comment]
This is a known issue with the most recent version.

**Comment by sionking** [comment]
@ogtimothymiller Which version ? Chrome / chromedriver / instapy ?

**Comment by bgunsberger** [comment]
I'm having the same problem.

**Comment by rajinfokiit** [comment]
also facing same issue, please suggest solution.

WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 3.10.0-514.el7.x86_64 x86_64)

**Comment by barbaracabral** [comment]
Same problem to me.

**Comment by ThomasViennet-zz** [comment]
Same problem to me.

**Comment by danzan** [comment]
Same to me

**Comment by VietQuoc** [comment]
Same to me

**Comment by ThomasViennet-zz** [comment]
I think this [issue](https://github.com/timgrossmann/InstaPy/issues/2678) can help you

**Comment by Raghu1992** [comment]
Any workaround for this issue? I have added the below in my capabilities object.

chromeOptions: {
            args: ["--headless", "--disable-gpu", "--window-size=800,600", "--disable-dev-shm-usage", "--no-sandbox"]
        }

Still I get the same issue.

**Comment by sripathivamsi** [comment]
Same here

**Comment by converge** [comment]
not exactly a bug.

could you confirm that your quickstart.py has a username set ?

example:
```python
session = InstaPy(username='your_username',
                  password='your_password',
```

I was able to reproduce it if the ```username``` variable is empty

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
