### ISSUE TITLE
sqlite3.OperationalError: no such table: recordActivity

### ISSUE THREAD

**Issue by tifDev** [InstaPy/InstaPy#2643]
After i have done a pull request in my local repo (to get an updated version) i got this:

```
Updating 0e71a71..1645d61
Fast-forward
 README.md                  |  22 ++++--
 db/instapy.db              | Bin 8192 -> 0 bytes
 instapy/comment_util.py    |  10 ++-
 instapy/commenters_util.py |   4 +-
 instapy/database_engine.py | 130 +++++++++++++++++++++++++++++++++++
 instapy/instapy.py         | 121 +++++++++++++++++---------------
 instapy/like_util.py       |  42 +++++++-----
 instapy/login_util.py      |   2 +-
 instapy/settings.py        |   7 ++
 instapy/unfollow_util.py   | 168 +++++++++++++++++++++++++++++++++------------
 instapy/util.py            | 165 +++++++++++++++++++++++++++++++++++---------
 tests/test_like_util.py    |   2 +-
 12 files changed, 507 insertions(+), 166 deletions(-)
 delete mode 100644 db/instapy.db
 create mode 100644 instapy/database_engine.py

```

So my local instapy.db was replaced.

Now i get this errors:

```
sudo python3 qs1.py
WARNING [2018-08-07 12:04:43] [tads_publicidade]  Heeh! Error occured while getting a DB profile for 'tads_publicidade':
	b'no such table: profiles'

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-07 12:04:44] [tads_publicidade]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

ERROR [2018-08-07 12:04:47] [tads_publicidade]  Pow! Error occured while dumping follow restriction data to a local JSON:
	b'no such table: followRestriction'
ERROR [2018-08-07 12:04:47] [tads_publicidade]  Pow! Error occured while dumping record activity data to a local JSON:
	b'no such table: recordActivity'

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-07 12:04:47] [tads_publicidade]  Session ended - 2018-08-07 12:04:47
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "qs1.py", line 26, in <module>
    session.login()
  File "/home/kmms/Programs/Instapy/virtualenvironment/instapy/bin/InstaPy/instapy/instapy.py", line 350, in login
    self.bypass_suspicious_attempt):
  File "/home/kmms/Programs/Instapy/virtualenvironment/instapy/bin/InstaPy/instapy/login_util.py", line 100, in login_user
    update_activity()
  File "/home/kmms/Programs/Instapy/virtualenvironment/instapy/bin/InstaPy/instapy/util.py", line 159, in update_activity
    cur.execute("SELECT * FROM recordActivity WHERE profile_id=:var AND created == date('now')", {"var":id})
sqlite3.OperationalError: no such table: recordActivity

```
What is the solution to get this running again?

**Comment by giuseppefrattura** [comment]
hi, i solved this problem by deleting db folder
