### ISSUE TITLE
Please help me.

### ISSUE THREAD

**Issue by kpol17** [InstaPy/InstaPy#2647]
Error: INFO [2018-08-08 03:01:59] [cyan_stylist] Session started!
 INFO [2018-08-08 03:02:32] [cyan_stylist] Logged in successfully!
 INFO [2018-08-08 03:02:34] [cyan_stylist] Tag [1/1]
 INFO [2018-08-08 03:02:34] [cyan_stylist] --> b'\xed\x8f\x89\xec\xb4\x8c'
 INFO [2018-08-08 03:02:42] [cyan_stylist] desired amount: 50 | top posts [disabled]: 9 | possible posts: 239470
 Traceback (most recent call last):
 File "quickstart.py", line 11, in <module>
 session.like_by_tags(['����'], amount=50, media=None)
 File "C:\MyPython\InstaPy-master\instapy\instapy.py", line 1203, in like_by_tags
 self.logger)
 File "C:\MyPython\InstaPy-master\instapy\like_util.py", line 257, in get_links_for_tag
 "window.scrollTo(0, document.body.scrollHeight);")
 File "C:\Users\Cyan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 635, in execute_script
 'args': converted_args})['value']
 File "C:\Users\Cyan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
 self.error_handler.check_response(response)
 File "C:\Users\Cyan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
 (Session info: chrome=67.0.3396.99)
 (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.17134 x86_64)

**Comment by ManfredHam** [comment]
update Chrome Driver maybe, "Line 1203" really so long?

**Comment by sahilr2050** [comment]
Same Issue. Is there any solution?
