### ISSUE TITLE
Unable to locate element - xpath

### ISSUE THREAD

**Issue by TR0X** [InstaPy/InstaPy#2653]
It seems that there is again the issue with finding the followers via xpath:

```
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    session.follow_user_followers(['love'], amount=100, randomize=False, interact=True, sleep_delay=300)
  File "/home/pi/InstaPy/instapy/instapy.py", line 2052, in follow_user_followers
    self.logfolder)
  File "/home/pi/InstaPy/instapy/unfollow_util.py", line 869, in get_given_user_followers
    channel, logger, logfolder)
  File "/home/pi/InstaPy/instapy/unfollow_util.py", line 614, in get_users_through_dialog
    "//div[text()='Followers' or text()='Following']/following-sibling::div")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/following-sibling::div"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmp9XlUsi/extensions/fxdriver@googlecode.com/components/driver-component.js:10770)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmp9XlUsi/extensions/fxdriver@googlecode.com/components/driver-component.js:625)

```

Any ideas how to fix this?

**Comment by doubledare704** [comment]
Seems that instagram changed their layout on page, so unfollow not working now
