### ISSUE TITLE
Getting this error when trying to run:

### ISSUE THREAD

**Issue by levfo** [InstaPy/InstaPy#2687]
I've tried both "sudo python quickstart.py" and "sudo python3 quickstart.py"

I am running it on a raspberry pi 3

Any ideas?
Thank you.

Traceback (most recent call last):
  File "quickstart.py", line 24, in <module>
    headless_browser=True)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 193, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 300, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by levfo** [comment]
Possible Issue: I may have a 64 bit version of chromedriver.

**Comment by levfo** [comment]
Downloaded 32bit version and getting same error.

**Comment by Areahints** [comment]
hello what is the output of `which python3` and `python3 --version` on your system?

**Comment by levfo** [comment]
Hey, thanks for the reply. Sorry for the late response. Here is the output:

/usr/bin/python3
Python 3.5.3

**Comment by timm83** [comment]
Ive got the same problem while trying to start running on raspberry pi

Anyone a solution?
