### ISSUE TITLE
Error running quickstart.py (InstaPy)

### ISSUE THREAD

**Issue by amiryassa** [InstaPy/InstaPy#2692]
I did the following:
1. git clone https://github.com/timgrossmann/InstaPy.git
2. cd InstaPy
3. python setup.py install
Installed chromedriver
When I run quickstart.py i get the below output. any thoughts?

python quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 11, in <module>
    driver = webdriver.Chrome('/usr/local/bin')
  File "/home/amiryassa1/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/home/amiryassa1/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 89, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'bin' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver
/home

**Comment by CamiloB** [comment]
dis you installed but you copy the driver in the folder assests?
