### ISSUE TITLE
Connection refused during session.end

### ISSUE THREAD

**Issue by booksix** [InstaPy/InstaPy#2712]
## Expected Behavior
quickstart.py execute to completion, exiting cleanly after a successful session.end call.

## Current Behavior
quickstart.py fails during session.end (yet somehow after the script declares the session has ended) with the following output (also happens using python 3.6.5):

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-18 18:43:15] [username]  Session ended - 2018-08-18 18:43:15
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "username", line 41, in job
    session.login()
  File "/Users/username/Downloads/InstaPy-master/instapy/instapy.py", line 350, in login
    self.bypass_suspicious_attempt):
  File "/Users/username/Downloads/InstaPy-master/instapy/login_util.py", line 98, in login_user
    browser.get('https://www.instagram.com')
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 375, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=63868): Max retries exceeded with url: /session/710858523b9b2238ce68309d842ee018/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b04edd0>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by mmncs** [comment]
Just experienced the same issue today. Did you solve it somehow?

**Comment by alexsmedile** [comment]
Similar here
`Failed to establish a new connection: [Errno 111] Connection refused`

**Comment by Joyen12** [comment]
Same for me. How did you fix it ?
