### ISSUE TITLE
Instapy on server with no_gui error

### ISSUE THREAD

**Issue by YannikFirre** [InstaPy/InstaPy#2713]
Hello,

I try to install instapy on a server hosting on planethoster.net. Installation it's fine with pip but when i try to start it with no_gui parameter, it's fail and i get this error :

```
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/slymprdu/instapy.slym.io/slymphotography/public/instapy/instapy.py", line 92, in __init__
    self.display = Display(visible=0, size=(800, 600))
  File "/home/slymprdu/virtualenv/instapy.slym.io_slymphotography/2.7/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/home/slymprdu/virtualenv/instapy.slym.io_slymphotography/2.7/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/home/slymprdu/virtualenv/instapy.slym.io_slymphotography/2.7/lib/python2.7/site-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/home/slymprdu/virtualenv/instapy.slym.io_slymphotography/2.7/lib/python2.7/site-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error!
```

Any idea ? 

Thanks,

Yannik

**Comment by Mehran** [comment]
and whats is your configuration in `quickstart.py` ?

**Comment by YannikFirre** [comment]
@Mehran 

Hello,

thanks for your interest, here it is : 

```
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = 'XXXXXXXXXX'
insta_password = 'XXXXXXXXXX'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                 no_gui=True,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=False,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)

    session.like_by_tags(['bnw', 'blacknwhite', 'instablackandwhite'], amount=100, media='Photo')
    session.end()

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

```

**Comment by Mehran** [comment]
@InfinityWebMe did you install `Xvfb` ? if not `apt-get install Xvfb`

**Comment by YannikFirre** [comment]
I don't have access to apt on my server. I can try to ask to my hosting if he can install it :-/

It would be interesting to add in the readme that the dependencie Xvfb is required.
