### ISSUE TITLE
get_active_users     "//div[contains(@class, '_9AhH0')]")[0].click()

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2747]
Traceback (most recent call last):
  File "/home/fredrik/InstaPy/5b7c1a7d9bcb2900144168d1.py", line 29, in <module>
    session.set_dont_unfollow_active_users(enabled=True, posts=5)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 2578, in set_dont_unfollow_active_users
    self.logger)
  File "/home/fredrik/InstaPy/instapy/util.py", line 249, in get_active_users
    "//div[contains(@class, '_9AhH0')]")[0].click()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="_9AhH0"></div> is not clickable at point (134, 485). Other element would receive the click: <span class="_0DvBq">...</span>
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-32-generic x86_64)

@uluQulu any idea?

**Comment by uluQulu** [comment]
Hey @fgisslen 
You're good at reporting issues 😂😂😂😂😂😂😂

To solve, open up **util.py** file,
**replace**
```python
    browser.find_elements_by_xpath(
        "//div[contains(@class, '_9AhH0')]")[0].click()
```
**with**
```python
    latest_post = browser.find_elements_by_xpath(
                        "//div[contains(@class, '_9AhH0')]")[0]
    click_element(browser, latest_post)
```

Also, PR this please 🤓

---------

Cheers 😁
----------

**Comment by fgisslen** [comment]
@uluQulu hehe yes, I know. I hope that is a good thing :)

I will PR this and the other one tomorrow. 

Cheers

**Comment by inakiabt** [comment]
FYI, a quick fix is to post at least one photo to your profile. That solved the issue for me :)
