### ISSUE TITLE
unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by michaelBielang** [InstaPy/InstaPy#2748]
Hi, since my last pull today I get this exception:

 ```
 (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-30-generic x86_64)
Traceback (most recent call last):
  File "/home/user/venv/bin/InstaPy/instapy/instapy.py", line 300, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-30-generic x86_64)

Traceback (most recent call last):
  File "/home/user/venv/bin/InstaPy/instapy/instapy.py", line 300, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-30-generic x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/user/venv/bin/InstaPy/instapy/instapy.py", line 193, in __init__
    self.set_selenium_local_session()
  File "/home/user/venv/bin/InstaPy/instapy/instapy.py", line 304, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/user/venv/bin/InstaPy/assets/chromedriver
```

Any idea how to fix it? I have changed nothing except the quickstart with the commands in the docu. Worked fine for the last 5 month.

Settings

> session = InstaPy(username=insta_username,
>                   password=insta_password,
>                   headless_browser=False,
>                   multi_logs=True)

imports

```
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

```

end

```
    except Exception as exc:
        # if changes to IG layout, upload the file to help us locate the change
        if isinstance(exc, NoSuchElementException):
            file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
            with open(file_path, 'wb') as fp:
                fp.write(session.browser.page_source.encode('utf8'))
            print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
                '*' * 70, file_path))
        # full stacktrace when raising Github issue
        raise
```

**Comment by x225am** [comment]
try to update chromedriver

**Comment by michaelBielang** [comment]
@x225am update to what? 2.41.578700 is the newest http://chromedriver.chromium.org/ ?

**Comment by Areahints** [comment]
are you using nogui=true ?

**Comment by michaelBielang** [comment]
@Areahints where is this setting? I updated my question with my settings. I never saw a module where i can setup nogui=true

**Comment by MasterGregg** [comment]
I get same problem !

**Comment by MasterGregg** [comment]
I solved my problem with theses lines in quickstart.py : 
headless_browser=True,
multi_logs=True,
nogui=True

**Comment by michaelBielang** [comment]
Cool, that worked for me as well. Thank you!

**Comment by SchDen** [comment]
@realsony thank you. 

It helped me but it works without `multi_logs=True` for me, only with:
```
headless_browser=True,
nogui=True
```

One more think.
I work with Docker (compose) and i got error with this config:
`No such file or directory: 'Xvfb': 'Xvfb'` 
and i solved it by change `docker_conf/python/Dockerfile`:
```
FROM python:3.6
RUN mkdir /code
RUN mkdir /config
WORKDIR /code
COPY ./requirements.txt /config/
RUN pip install -r /config/requirements.txt
RUN apt-get update
RUN apt-get -y install Xvfb
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
COPY ./ /code/
```

maybe it will be useful for somebody
