### ISSUE TITLE
Error at following users

### ISSUE THREAD

**Issue by spikeyhair** [InstaPy/InstaPy#2756]
## Expected Behavior
It should start following users

## Current Behavior
Whenever this function, session.follow_user_followers, been executed, bot terminated with errors.

.............................................................
INFO [2018-08-25 14:17:01] [xxx]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-08-25 14:17:05] [xxx]  User 'ericxx19' [1/1]
**********************************************************************
If raising an issue, please also upload the file located at:
C:\Users\xxx\AppData\Local\Temp\20180825-141734.html
**********************************************************************

Traceback (most recent call last):
  File "D:\Dropbox\Instapy\quickstart_verify.py", line 177, in <module>
    session.follow_user_followers(['ericxx19'], amount=5, randomize=True, sleep_
delay=30)
  File "D:\Dropbox\Instapy\instapy\instapy.py", line 2031, in follow_user_follow
ers
    self.logfolder)
  File "D:\Dropbox\Instapy\instapy\unfollow_util.py", line 869, in get_given_use
r_followers
    channel, logger, logfolder)
  File "D:\Dropbox\Instapy\instapy\unfollow_util.py", line 614, in get_users_thr
ough_dialog
    "//div[text()='Followers' or text()='Following']/following-sibling::div")
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\webdriver.py", line 385, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\webdriver.py", line 955, in find_element
    'value': value})['value']
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Una
ble to locate element: {"method":"xpath","selector":"//div[text()='Followers' or
 text()='Following']/following-sibling::div"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5
ab),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by jeffarese** [comment]
See https://github.com/timgrossmann/InstaPy/issues/2754#issuecomment-415950495
