### ISSUE TITLE
Following Issue

### ISSUE THREAD

**Issue by cesarcm96** [InstaPy/InstaPy#2763]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-25 09:41:32] [**********]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

....................................................................
INFO [2018-08-25 09:42:08] [*********]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-08-25 09:42:11] [*********]  User 'innvictusmx' [1/1]
INFO [2018-08-25 09:42:29] [*********]  Simulated follow : 1
INFO [2018-08-25 09:42:32] [*********]  --> Followed b'eibrajam100'
Traceback (most recent call last):
  File "sinmarcamexico.py", line 19, in <module>
    session.follow_user_followers(['innvictusmx'], amount=488, randomize=True, sleep_delay=255)
  File "C:\Users\Usuario\Documents\instapy\instapy\instapy.py", line 2052, in follow_user_followers
    self.logfolder)
  File "C:\Users\Usuario\Documents\instapy\instapy\unfollow_util.py", line 910, in get_given_user_followers
    channel, logger, logfolder)
  File "C:\Users\Usuario\Documents\instapy\instapy\unfollow_util.py", line 671, in get_users_through_dialog
    scroll_bottom(browser, dialog, 2)
  File "C:\Users\Usuario\Documents\instapy\instapy\util.py", line 429, in scroll_bottom
    "arguments[0].scrollTop = arguments[0].scrollHeight", element)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 546, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.17134 x86_64)

**Comment by marcosgb** [comment]
same here

**Comment by A-S-C-I-I** [comment]
I am having the same issue.  None of the previous solutions I have found for this have worked for me (though I may have missed something).

I run InstaPy headless, and the issue seems to be specifically with the follow function.  If I comment out all follow lines it runs normally (unfollow, like, comment, etc).

**Comment by clevebounce** [comment]
same error with cesarcm96

**Comment by britotiagos** [comment]
I had a similar problem with unfollowing and fixed it pulling the updated files from the repository. " git pull "

**Comment by marcosgb** [comment]
hello I just fixed it by putting in quickstart
session.set_simulation(enabled=False)

**Comment by A-S-C-I-I** [comment]
@britotiagos did you do a virtualenv install?  i am not able to git pull from mine.

@marcosgb that did it for me, too.  thanks!
