### ISSUE TITLE
Stale Element after Pull on session.follow_user_followers

### ISSUE THREAD

**Issue by CalebBuxton** [InstaPy/InstaPy#2772]
## Expected Behavior

Expected to run and follow

## Current Behavior

Launches and logs in, gets to the first account to follow users for and times out with the error

`  File "/root/instagram/InstaPy/instapy/instapy.py", line 2052, in follow_user_followers
    self.logfolder)
  File "/root/instagram/InstaPy/instapy/unfollow_util.py", line 910, in get_given_user_followers
    channel, logger, logfolder)
  File "/root/instagram/InstaPy/instapy/unfollow_util.py", line 712, in get_users_through_dialog
    quick_username = dialog_username_extractor(quick_button)
  File "/root/instagram/InstaPy/instapy/unfollow_util.py", line 751, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 68, in text return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute  return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-30-generic x86_64)`

## InstaPy configuration

This is the most recent pull as of 2  hours ago as I just rebuilt my server. Checked the `unfollow_util.py` suggestions in other threads and all of those lines are in the current release that I have but the script is still failing.

**Comment by CTZNkjs** [comment]
For the time being, I set simulation to false until the issue is figured out

**Comment by Areahints** [comment]
same issue. how do you set simulation to false? @CTZNkjs

**Comment by martinsnajdr** [comment]
I have the same issue. +1

**Comment by jtrieuDev** [comment]
same issue here

**Comment by xaniel** [comment]
Simulation on false working for me

**Comment by elypsis** [comment]
same issue

**Comment by CTZNkjs** [comment]
sorry for the late response 

session.set_simulation(enabled=False)

**Comment by s-h-a-d-o-w-pixel** [comment]
Same issue, but the simulation false is not working for me

**Comment by Areahints** [comment]
@jiuguangw @charlesccc thanks for the fix. however the fix is selective of python versions?!

```output using python 3.5
Traceback (most recent call last):
  File "me.py", line 48, in <module>
    session.follow_user_followers(['user1', 'user2', 'user3'], amount=25, randomize=True, sleep_delay=60)
  File "/root/InstaPy/instapy/instapy.py", line 2052, in follow_user_followers
    self.logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 924, in get_given_user_followers
    channel, logger, logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 712, in get_users_through_dialog
    quick_username = dialog_username_extractor(quick_button)
  File "/root/InstaPy/instapy/unfollow_util.py", line 760, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.4.0-134-generic x86_64)```

when i run with python 2.7 no problems at all

**Comment by CharlesCCC** [comment]
@Areahints I didn't aware of the version issue. but if you got it to work with 2.7, I would stick with 2.7 for now.

**Comment by Areahints** [comment]
sorry, had an update pending! works perfectly..

**Comment by Areahints** [comment]
error popping up again @charlesccc

```

Traceback (most recent call last):
  File "me.py", line 48, in <module>
    session.follow_user_followers(['user1', 'user2', 'user3'], amount=25, randomize=True, sleep_delay=60)
  File "/root/InstaPy/instapy/instapy.py", line 2052, in follow_user_followers
    self.logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 924, in get_given_user_followers
    channel, logger, logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 712, in get_users_through_dialog
    quick_username = dialog_username_extractor(quick_button)
  File "/root/InstaPy/instapy/unfollow_util.py", line 760, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.4.0-134-generic x86_64)

**Comment by CharlesCCC** [comment]
this is a duplicate with #2745 close this issue for now
