### ISSUE TITLE
Issue during Following action

### ISSUE THREAD

**Issue by cormo1990** [InstaPy/InstaPy#2780]
@uluQulu @sionking thanks for the help friends,

Latest release of InstaPy, it happens during following followers action
below the traceback

> Traceback (most recent call last):
  File "xxxx", line 44, in <module>
    session.follow_user_followers(['xxxx'], amount=800, randomize=False, interact=False)
  File "/Users/lucacornago/Desktop/InstaPy/instapy/instapy.py", line 2052, in follow_user_followers
    self.logfolder)
  File "/Users/xxxx/Desktop/InstaPy/instapy/unfollow_util.py", line 910, in get_given_user_followers
    channel, logger, logfolder)
  File "/Users/xxxx/Desktop/InstaPy/instapy/unfollow_util.py", line 671, in get_users_through_dialog
    scroll_bottom(browser, dialog, 2)
  File "/Users/xxxx/Desktop/InstaPy/instapy/util.py", line 426, in scroll_bottom
    "arguments[0].scrollTop = arguments[0].scrollHeight", element)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.12.6 x86_64)

**Comment by CharlesCCC** [comment]
did you get the latest version ?  because this should have been fixed by last PR merge.

**Comment by cormo1990** [comment]
@CharlesCCC i'm testing right now with the solution of @uluQulu and it seems works.

For be sure i'll wait the latest PR by @uluQulu for update all the InstaPy.

thanks to all of you guys, your work is a masterpiece

**Comment by uluQulu** [comment]
Thanks a bunch, @cormo1990!
The series of those issues is solved completely with the latest solution- https://github.com/uluQulu/InstaPy/commit/99774d65deaf1d44660971eb95a9c66bcdd43ef2.

I also wrote the changes needed for the current version of InstaPy if you like to see-
https://github.com/timgrossmann/InstaPy/issues/2774#issuecomment-416583797


----------

Cheers 😁
--------
