### ISSUE TITLE
 OSError: [Errno 8] Exec format error - Raspberry Pi

### ISSUE THREAD

**Issue by andifds** [InstaPy/InstaPy#2791]
I got this after trying to exceute quickstart.py on Raspberry pi. Raspbian is brand new, reinstalled it thinking about misconfiguration. Tried to use Chrome headless and got this. InstaPy works when using Firefox, but not headless.
## Expected Behavior
Start sessión and operation
commands used and failed
`sudo xvfb-run python quickstart.py`
`sudo python3 quickstart.py`
`sudo python quickstart.py`

Installed all requirements on `pip3 `and `pip `but still not working
## Current Behavior
`Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/pi/InstaPy/instapy/instapy.py", line 193, in __init__
    self.set_selenium_local_session()
  File "/home/pi/InstaPy/instapy/instapy.py", line 300, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
`

## InstaPy configuration

Nothing else than username, password and action. Installed chromedriver directly, by command, and not working.

**Comment by Apao123** [comment]
hey @andifds - I also face the same problem. How did you solve it?

**Comment by tomtactom** [comment]
I have the same problem

**Comment by dsmh** [comment]
Same problem here, any solution?

**Comment by andifds** [comment]
Follow rhe CLI instructions for RasPi and it will work.

Also is recommended uninstall LibreOffice and anyother chrome or chromium
reference on raspbian.


It took long time for me to work but finally it's active.
