### ISSUE TITLE
Function follow_user_followers crashes chromedriver

### ISSUE THREAD

**Issue by luquitared** [InstaPy/InstaPy#2797]
My script has the same setup as the basic setup in the readme.

Using this function:
`session.follow_user_followers(['mkbhd'], amount=100, randomize=False)`

I run into this error:
`    session.follow_user_followers(['mkbhd'], amount=100, randomize=False)
  File "/Users/lucas/InstaPy/instapy/instapy.py", line 2052, in follow_user_followers
    self.logfolder)
  File "/Users/lucas/InstaPy/instapy/unfollow_util.py", line 924, in get_given_user_followers
    channel, logger, logfolder)
  File "/Users/lucas/InstaPy/instapy/unfollow_util.py", line 712, in get_users_through_dialog
    quick_username = dialog_username_extractor(quick_button)
  File "/Users/lucas/InstaPy/instapy/unfollow_util.py", line 760, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 68, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363),platform=Mac OS X 10.13.2 x86_64)

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x11188fd68>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 163, in __del__
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 139, in stop
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down`

**Comment by dnishiyama** [comment]
I'm getting this error too

**Comment by luquitared** [comment]
@dnishiyama Here is a workaround that achieves the same result:
`followers = session.grab_followers(username="mkbhd", amount=100, live_match=False, store_locally=True)`

`session.follow_by_list(followlist=followers, times=1, sleep_delay=600, interact=False)`

**Comment by dnishiyama** [comment]
@luquitared Thank you for that. I'm back up and running with that work around :)

**Comment by wrhsescp** [comment]
what to do in case of using multiple usernames ?

**Comment by dnishiyama** [comment]
I did this
`accts_with_followers_to_follow = ['cool_user1', 'cool_user2', 'cool_user3', 'cool_user4', 'cool_user5']`
`followers_per_acct = 50`
`interactions = 2 `
`followers = []`
`for acct in accts_with_followers_to_follow:`
    `    acct_followers = session.grab_followers(username=acct, amount=followers_per_acct, live_match=False, store_locally=True)`
    `followers += random.sample(acct_followers, min(followers_per_acct, len(acct_followers)))`
    `logging.info(f'Looking at {len(followers)} followers!'); `
    `session.interact_by_users(followers, amount=interactions, randomize=True, media='Photo')`

As you can tell, I have no idea how to make a comment in github, but hopefully you get the idea. Let me know if you have questions
