### ISSUE TITLE
session.set_relationship_bounds causing session.follow_user_followers to crash?

### ISSUE THREAD

**Issue by boldestfortune** [InstaPy/InstaPy#2809]
So I'm using the latest master of instapy from 3 days ago w/ #2782 update, but `session.follow_user_followers` still crashing the bot. ran some primitive basic tests to see what was causing it. (bear with me as I don't know how to maintain colour when copying code)
## Current Behavior
```
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    session.follow_user_followers(['user', 'user', 'user', 'user'], amount=10, randomize=True)
  File "C:\Users\user\dev\account\instapy\instapy\instapy.py", line 2053, in follow_user_followers
    self.logfolder)
  File "C:\Users\user\dev\acct\instapy\instapy\unfollow_util.py", line 924, in get_given_user_followers
    channel, logger, logfolder)
  File "C:\Users\user\dev\acct\instapy\instapy\unfollow_util.py", line 712, in get_users_through_dialog
    quick_username = dialog_username_extractor(quick_button)
  File "C:\Users\user\dev\acct\instapy\instapy\unfollow_util.py", line 760, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "C:\Users\user\dev\acct\lib\site-packages\selenium\webdriver\remote\webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "C:\Users\user\dev\acct\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\user\dev\acct\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user\dev\acct\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)
```
I tried uninstalling & reinstalling Selenium but that did not seem to help.
## Possible Solution (optional)
Removing all the relationship settings seemed to let it run fine for a few minutes before I manually ended the task.

```
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

try:
    session.login()

    # settings


    # actions

    session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
    session.follow_user_followers(['user1', 'user2', 'user3', 'user4'], amount=10, randomize=True)



    session.unfollow_users(amount=100, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
    session.set_dont_unfollow_active_users(enabled=True, posts=3)
```

This is the `session.set_relationship_bounds` that I removed:

```
  session.set_relationship_bounds(enabled=True,
               potency_ratio=-1.2,
                delimit_by_numbers=True,
                 max_followers=15000,
                  max_following=15000,
                   min_followers=75,
                    min_following=75)
  session.set_do_comment(False, percentage=10)
  session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
  session.set_use_clarifai(enabled=True, api_key='--')
  session.clarifai_check_img_for(['nsfw', 'gay', 'hijab', 'niqab', 'religion', 'shirtless', 'fitness', 'yamaka', 'rightwing'])
  session.set_dont_like(['dick', 'squirt', 'gay', 'homo', '#fit', '#fitfam', '#fittips', '#abs', '#kids', '#children', '#child', '[nazi', 'jew', 'judaism', '[muslim', '[islam', 'bangladesh','[hijab', '[niqab',
  '[farright', '[rightwing', '#conservative', 'death'])
  session.set_do_follow(enabled=True, percentage=25, times=2)
```

## InstaPy configuration
```
This is the full config that I used which was breaking.

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.2,
				  delimit_by_numbers=True,
				   max_followers=15000,
				    max_following=15000,
				     min_followers=75,
				      min_following=75)
    session.set_do_comment(False, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_use_clarifai(enabled=True, api_key='api')
    session.clarifai_check_img_for(['nsfw', 'gay', 'hijab', 'niqab', 'religion', 'shirtless', 'fitness', 'yamaka', 'rightwing'])
    session.set_dont_like([])
    session.set_do_follow(enabled=True, percentage=25, times=2)

    # actions
    session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
    session.follow_user_followers(['user1', 'user2', 'user3', 'user4', 'user5'], amount=10, randomize=True)

    session.set_smart_hashtags([], limit=10, sort='random', log_tags=True)
    session.like_by_tags(amount=5, use_smart_hashtags=True)
    session.set_delimit_liking(enabled=True, max=1005, min=5)


    session.unfollow_users(amount=100, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
    session.set_dont_unfollow_active_users(enabled=True, posts=3)


except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

```

Any suggestions on how to fix? or am I missing something very simple (not a programmer IRL)

**Comment by michelalbers** [comment]
I ran into the same error and don't know why this happens. I guess something in the instagram dom changed. I just catched the exception inside follower_util.py. This is not really a fix - more like a "ignore that" statement but it works for me:

In line 776 in *instapy/unfollow_util.py* edit the **dialog_username_extractor** to look as follows:
```python
def dialog_username_extractor(buttons):
    """ Extract username of a follow button from a dialog box """

    if not isinstance(buttons, list):
        buttons = [buttons]

    person_list = []
    for person in buttons:

        try:
            if person and hasattr(person, 'text') and person.text:
                try:
                    person_list.append(person.find_element_by_xpath("../../../*")
                            .find_elements_by_tag_name("a")[1].text)

                except IndexError:
                    pass  # Element list is too short to have a [1] element
        except StaleElementReferenceException:
            pass  # Dont know why this happens, just ignore

    return person_list
```

**Comment by narchiii** [comment]
Thanks michelalbers. That works for me.

**Comment by davisonio** [comment]
Same error for me

**Comment by boldestfortune** [comment]
Brilliant. This did the trick. thanks
