### ISSUE TITLE
The error of user interaction continues

### ISSUE THREAD

**Issue by zsvendo** [InstaPy/InstaPy#2820]
INFO [2018-09-01 08:17:51] [***]  --> Followed b'p888'
INFO [2018-09-01 08:18:01] [***]  Simulated follow : 7
INFO [2018-09-01 08:18:07] [*****]  --> Followed b'mtfoot'
INFO [2018-09-01 08:18:10] [*****]  Simulated follow : 8
Traceback (most recent call last):
  File "1.py", line 8, in <module>
    session.interact_user_followers(['****'], amount=1000, randomize=False)
  File "C:\InstaPy\instapy\instapy.py", line 1816, in interact_user_followers
    self.logfolder)
  File "C:\InstaPy\instapy\unfollow_util.py", line 948, in get_given_user_followers
    channel, logger, logfolder)
  File "C:\InstaPy\instapy\unfollow_util.py", line 728, in get_users_through_dialog
    quick_username = dialog_username_extractor(quick_button)
  File "C:\InstaPy\instapy\unfollow_util.py", line 776, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "C:\Users\Avell\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "C:\Users\Avell\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute

**Comment by zsvendo** [comment]
@uluQulu ? Help

**Comment by uluQulu** [comment]
hi @zsvendo 
My live latest PR solves it

----------

Cheers 😁😁
---------

**Comment by zsvendo** [comment]
@uluQulu I have the latest update, but I do not know if that's what you said.

**Comment by uluQulu** [comment]
@zsvendo 
https://github.com/timgrossmann/InstaPy/pull/2771

**Comment by zsvendo** [comment]
@uluQulu now see the error you are giving after changing the files with # 2771

C:\>cd InstaPy

C:\InstaPy>python 1.py
Traceback (most recent call last):
  File "1.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\InstaPy\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "C:\InstaPy\instapy\instapy.py", line 23, in <module>
    from .comment_util import comment_image
  File "C:\InstaPy\instapy\comment_util.py", line 7, in <module>
    from .util import update_activity
  File "C:\InstaPy\instapy\util.py", line 20, in <module>
    from .quota_supervisor import quota_supervisor
  File "C:\InstaPy\instapy\quota_supervisor.py", line 7, in <module>
    from plyer import notification
ModuleNotFoundError: No module named 'plyer'

**Comment by uluQulu** [comment]
@zsvendo 
You should install `plyer` from pip

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)
