### ISSUE TITLE
Message: session not created exception from tab crashed

### ISSUE THREAD

**Issue by dule91sd** [InstaPy/InstaPy#2823]
I'm struggling to find out what the problem is, but I do not succeed.
I updated everything and still not working
Can anybody to help me to solve this problem?

## Current Behavior
ERROR [2018-09-01 19:23:45] []  Message: session not created exception
from tab crashed
  (Session info: headless chrome=68.0.3440.75)
  (Driver info: chromedriver=2.38 (undefined),platform=Linux 4.14.62-v7+ armv7l)
Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 300, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: session not created exception
from tab crashed
  (Session info: headless chrome=68.0.3440.75)
  (Driver info: chromedriver=2.38 (undefined),platform=Linux 4.14.62-v7+ armv7l)

Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 193, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 304, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/Projects/InstaPy/assets/chromedriver

**Comment by dule91sd** [comment]
Please guys anyone can solve me this issue? I really dont't know what to do.
I tried almost everything and nothing working.
I really need to start running instapy.

**Comment by epokheio** [comment]
Encountering the same issue on my raspberry pi.
