### ISSUE TITLE
error get_following_status with

### ISSUE THREAD

**Issue by Luisjanz** [InstaPy/InstaPy#2832]
## Expected Behavior
bot works 24/7
## Current Behavior
bot crashes after a while
## Possible Solution (optional)
?
## InstaPy configuration
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-09-02 17:38:23] [*username*]  Session ended - 2018-09-02 17:38:23
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "quickstart.py", line 39, in <module>
    session.like_by_tags(['Wheelie', 'Sportbike', 'dirtbike', '4stroke', '2stroke', 'motocrossgirl', 'moto', 'gopro', 'beta', 'querly'], amount=100)
  File "/home/pi/InstaPy/instapy/instapy.py", line 1340, in like_by_tags
    self.logfolder)
  File "/home/pi/InstaPy/instapy/unfollow_util.py", line 535, in follow_user
    are_we_following, follow_button = get_following_status(browser, user_name, logger)
  File "/home/pi/InstaPy/instapy/unfollow_util.py", line 108, in get_following_status
    raise Exception
Exception
 --> error get_following_status with biker.hub, maybe no longer exists...

**Comment by axlright** [comment]
I've gotten the same error. I would help, but I'm not smart enough : : :

```
--> Warning: Comment Button Not Found: May cause issues with browser windows of smaller widths
...
ERROR [2018-09-02 10:10:49] [xxxxxxx]  --> error get_following_status with xxxxxxx_, maybe no longer exists...
...
Traceback (most recent call last):
  File "user-xxxxxx-hashtag-xxxxxxx.py", line 67, in <module>
    session.like_by_tags(['#xxxxxxxx'], amount=822)
  File "/Users/xxxxxxx/Documents/Code/InstaPy/instapy/instapy.py", line 1340, in like_by_tags
    self.logfolder)
  File "/Users/xxxxxxx/Documents/Code/InstaPy/instapy/unfollow_util.py", line 535, in follow_user
    are_we_following, follow_button = get_following_status(browser, user_name, logger)
  File "/Users/xxxxxxx/Documents/Code/InstaPy/instapy/unfollow_util.py", line 108, in get_following_status
    raise Exception
Exception
```

**Comment by axlright** [comment]
Hmmm, just happened again 🤕

**Comment by shariqmoosa** [comment]
I am facing the exact same issue after some activity,

it was not happening with older version I did the last pull 2 days ago

the error is:
```
ERROR [2018-09-03 16:18:04]   --> error get_following_status with b'instauser1', maybe no longer exists...
Traceback (most recent call last):
  File "\InstaPy-master\instapy\unfollow_util.py", line 100, in get_following_status
    "//*[contains(text(), 'Requested')]")
  File "\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 393, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), 'Requested')]"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.14393 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart-merch.py", line 21, in <module>
    session.like_by_tags(['tag','tag1'], amount=1000, skip_top_posts=False)
  File "\InstaPY\inbound-pro\InstaPy-master\instapy\instapy.py", line 1340, in like_by_tags
    self.logfolder)
  File "\InstaPy-master\instapy\unfollow_util.py", line 535, in follow_user
    are_we_following, follow_button = get_following_status(browser, user_name, logger)
  File "\InstaPy-master\instapy\unfollow_util.py", line 108, in get_following_status
    raise Exception
Exception
```

Thanks

**Comment by joanroig** [comment]
Same error here but only on multiple accounts, when running only one account it works as always.
