### ISSUE TITLE
InstaPy raspberry pi guide is not working

### ISSUE THREAD

**Issue by Backronn1** [InstaPy/InstaPy#2838]
I followed the set up guide for raspberry pi with chromium, but it is not working any more.

I have downgraded chromedriver to v33 but I still get the following error:

root@pi:/home/pi/repo/InstaPy# python quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/pi/repo/InstaPy/instapy/instapy.py", line 193, in __init__
    self.set_selenium_local_session()
  File "/home/pi/repo/InstaPy/instapy/instapy.py", line 300, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by dule91sd** [comment]
Also I have the same problem but I don't know why

**Comment by sebblessing** [comment]
The older version of the Chromedriver works but I also can't setup a new Pi, because the old one isn't availible and the new one don't works

**Comment by dule91sd** [comment]
@sebblessing  I updated everything that I can update but still I got following error.
I really don't have idea how to solve this issue :-(

```
ERROR [2018-09-04 08:34:14] [maske_online_shop]  Message: session not created exception
from tab crashed
  (Session info: headless chrome=68.0.3440.75)
  (Driver info: chromedriver=2.38 (undefined),platform=Linux 4.14.62-v7+ armv7l)
Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 300, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: session not created exception
from tab crashed
  (Session info: headless chrome=68.0.3440.75)
  (Driver info: chromedriver=2.38 (undefined),platform=Linux 4.14.62-v7+ armv7l)

Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 193, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 304, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/Projects/InstaPy/assets/chromedriver

```

**Comment by nikartz** [comment]
The problem is, that both of you are using the wrong version of Chrome and Chromedriver. [Here](http://chromedriver.chromium.org/downloads) you can check our, which version of the driver works with with version of Chrome. As you are currently using Chrome v68 you need Chromedriver v2.39 or 2.40. Both are not available for Raspbian atm.
The best thing to do right now is to downgrade Chrome and everything else to v67 and everything should work fine.
There are multiple ways, however I simply use `sudo apt-get install <package-name>=<package-version-number>`

**Comment by Backronn1** [comment]
I think you are correct that there is a compatibility issue. The latest chromedriver version that supports 32-bit is v2.33. I have managed to download that one but it is only compatible with chrome v60-62 and I have problem finding/installing that one. 

root@pi:/etc/apt# sudo apt-get install chromium-browser=62.0.3202
Reading package lists... Done
Building dependency tree        
Reading state information... Done
E: Version '62.0.3202' for 'chromium-browser' was not found

Any suggestion how to install this chrome version?

**Comment by guitar9** [comment]
somebody has a solution for raspberry pi 3?

**Comment by thEpisode** [comment]
Guys check this #2678
