### ISSUE TITLE
line 103, in get_following_status     "//*[contains(text(), 'Requested')]")

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2843]
@uluQulu any suggestions?

ERROR [2018-09-04 10:09:39] [xxx]  --> error get_following_status with b'xxx', maybe no longer exists...

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-09-04 10:09:40] [xxx]  Session ended - 2018-09-04 10:09:40
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/unfollow_util.py", line 103, in get_following_status
    "//*[contains(text(), 'Requested')]")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 393, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), 'Requested')]"}
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.36 (7165af0ca9863529f28e493568ae3d105eddcdef),platform=Linux 4.15.0-33-generic x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/5b87c55a3e1f010014e239f5.py", line 20, in <module>
    session.like_by_tags(['#x','#x','#x'], amount=50)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 1345, in like_by_tags
    self.logfolder)
  File "/home/fredrik/InstaPy/instapy/unfollow_util.py", line 548, in follow_user
    are_we_following, follow_button = get_following_status(browser, user_name, logger)
  File "/home/fredrik/InstaPy/instapy/unfollow_util.py", line 111, in get_following_status
    raise Exception
Exception

**Comment by uluQulu** [comment]
@fgisslen 
All those problems and more in that definition- `get_following_status()` are solved in my live PR ⚽
>If you really wonder how it could happen, see line `535` in **unfollow_util.py** file WHERE the raised `Exception` is on the fly.
----------

Cheers 😁😁
--------

**Comment by sunnygill** [comment]
What is the PR numbers?

**Comment by uluQulu** [comment]
@sunnygill 
https://github.com/timgrossmann/InstaPy/pull/2771
