### ISSUE TITLE
"chromedriver unexpectedly exited" on Raspberry Pi

### ISSUE THREAD

**Issue by strione** [InstaPy/InstaPy#2845]
## Error
Hello, 
I have tried to follow instructions by [#2678](https://github.com/timgrossmann/InstaPy/issues/2678#issuecomment-413777310) but no success... I'm getting error about chromedriver unexpectedly exited (with status code -4)
I have tried using python 3.5 and I'm getting the same error.
I'm out of ideas how to launch it...  
All day wasted already. :smile: 

## Some debug info:
Raspberry: b+ (old one, 2014 year release)
Software: RASPBIAN STRETCH LITE 4.14

## InstaPy configuration
quickstart.py
headless_browser=True

**pi@raspberrypi:~/instapy $ ls -lha assets/**
total 8.1M
drwxr-xr-x  2 pi pi 4.0K Sep  4 16:20 .
drwxr-xr-x 13 pi pi 4.0K Sep  4 15:38 ..
-rwxrwxrwx  1 pi pi 8.1M Aug 13 15:42 chromedriver
-rw-r--r--  1 pi pi   61 Sep  4 15:10 .gitignore
-rw-r--r--  1 pi pi  489 Sep  4 15:10 unicodes.md

## Error log
pi@raspberrypi:~/instapy $ sudo python quickstart.py
ERROR [2018-09-04 16:29:12] [username]  Message: Service /home/pi/instapy/assets/chromedriver unexpectedly exited. Status code was: -4
Traceback (most recent call last):
  File "/home/pi/instapy/instapy/instapy.py", line 300, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 86, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 99, in assert_process_still_running
    % (self.path, return_code)
WebDriverException: Message: Service /home/pi/instapy/assets/chromedriver unexpectedly exited. Status code was: -4

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/pi/instapy/instapy/instapy.py", line 193, in __init__
    self.set_selenium_local_session()
  File "/home/pi/instapy/instapy/instapy.py", line 304, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/instapy/assets/chromedriver

**Comment by dule91sd** [comment]
I have the same issue on RaspberryPi 3 with NOOBS OS and trying to solve this issue for a week without any result. I have no idea what else to do....
@timgrossmann @CharlesCCC @sionking 
Guys can you help us to solve this issue? Few users have the same issue....

**Comment by strione** [comment]
Today I tried to use firefox and once again with no success...
Any ideas what I am missing? 

Btw status code the same as chrome driver 
## Error 

pi@raspberrypi:~/instapy $ sudo python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 23, in <module>
    multi_logs=True)
  File "/home/pi/instapy/instapy/instapy.py", line 193, in __init__
    self.set_selenium_local_session()
  File "/home/pi/instapy/instapy/instapy.py", line 255, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 157, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: -4

**Comment by baletskyi** [comment]
Any solutions for this error?

**Comment by RemakingEden** [comment]
Sorry to dig up an old thread but I cannot find reference to this error code anywhere!! Did anyone manage to solve this issue? I'm getting it on my Pi Zero now.

**Comment by tE3m** [comment]
https://github.com/timgrossmann/InstaPy/issues/4033#issuecomment-466491400 yes. Here's the solution for Pi Zeros.

**Comment by RemakingEden** [comment]
> [#4033 (comment)](https://github.com/timgrossmann/InstaPy/issues/4033#issuecomment-466491400) yes. Here's the solution for Pi Zeros.

Thank you!!
