### ISSUE TITLE
TimeoutException: Message: timeout

### ISSUE THREAD

**Issue by dpashutskii** [InstaPy/InstaPy#2847]
Hi @uluQulu!
I started to get timeouts often, changed nothing. Do you know what could it possibly be?

```
Traceback (most recent call last):
  File "quickstart.py", line 39, in <module>
    session.like_by_tags(amount=10, use_smart_hashtags=True)
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 1238, in like_by_tags
    self.logger)
  File "/home/ubuntu/InstaPy/instapy/util.py", line 91, in validate_username
    followers_count, following_count = get_relationship_counts(browser, username, logger)
  File "/home/ubuntu/InstaPy/instapy/util.py", line 526, in get_relationship_counts
    web_adress_navigator(browser, user_link)
  File "/home/ubuntu/InstaPy/instapy/util.py", line 598, in web_adress_navigator
    browser.get(link)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-1020-aws x86_64)
```

**Comment by uluQulu** [comment]
Hi @guar47 
If you use the changes in my PR, it has been solved there

-------

Cheers 😁
-------

**Comment by dpashutskii** [comment]
Hi @uluQulu, You mean that already in `master` or one else? I've just pulled all changes from `master` and got the same error:
```
Traceback (most recent call last):
  File "quickstart.py", line 39, in <module>
    session.like_by_tags(amount=10, use_smart_hashtags=True)
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 1244, in like_by_tags
    web_adress_navigator(self.browser, link)
  File "/home/ubuntu/InstaPy/instapy/util.py", line 607, in web_adress_navigator
    browser.get(link)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-1020-aws x86_64)
```

**Comment by uluQulu** [comment]
@guar47 
#2771

**Comment by dpashutskii** [comment]
Thanks, @uluQulu! Pulled your changes as upstream. Testing.

**Comment by dpashutskii** [comment]
@uluQulu Work like a charm! Thank you very much.
