### ISSUE TITLE
Hi This my problem line 100 unfollow_utill.py

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#2852]
Traceback (most recent call last):
  File "/Users/jonathanverdier/Desktop/Valentin/instapy/unfollow_util.py", line 100, in get_following_status
    "//*[contains(text(), 'Requested')]")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), 'Requested')]"}
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.13.6 x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 50, in <module>
    session.like_by_tags(['musculation','teamshape','getfit','fit','fitnessmodel','fitspo','crossfit','muscu','shooting','fitfrenchies'], amount=10, interact=True)
  File "/Users/jonathanverdier/Desktop/Valentin/instapy/instapy.py", line 1340, in like_by_tags
    self.logfolder)
  File "/Users/jonathanverdier/Desktop/Valentin/instapy/unfollow_util.py", line 535, in follow_user
    are_we_following, follow_button = get_following_status(browser, user_name, logger)
  File "/Users/jonathanverdier/Desktop/Valentin/instapy/unfollow_util.py", line 108, in get_following_status
    raise Exception
Exception
Jonathans-M

**Comment by HansDaigle** [comment]
Same here, it only happen sometime though. I added a try except to skip it that happen for now.

**Comment by Pormientras** [comment]
@HansDaigle I am having this same error, but I dont know much about python. How do you code an except inside the quickstart?

**Comment by HansDaigle** [comment]
This is not a permanent fix at all. But I did something like that in quickstart 

```
error_count = 0
...
try:
    # let's say this is the line raising your exception
    session.like_by_tags(amount=2, use_smart_hashtags=True, interact=False, media='Photo')
except Exception:
    error_count += 1
    if error_count > 3:
        raise
```

you could also ignore errors all the time, but that's risky.

```

try:
    # let's say this is the line raising your exception
    session.like_by_tags(amount=2, use_smart_hashtags=True, interact=False, media='Photo')
except Exception:
    pass
```
