### ISSUE TITLE
No module named plyer

### ISSUE THREAD

**Issue by aku6640** [InstaPy/InstaPy#2871]
## Expected Behavior

Traceback (most recent call last):
  File "custom.py", line 8, in <module>
    from instapy import InstaPy
  File "/home/pi/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/home/pi/InstaPy/instapy/instapy.py", line 23, in <module>
    from .comment_util import comment_image
  File "/home/pi/InstaPy/instapy/comment_util.py", line 7, in <module>
    from .util import update_activity
  File "/home/pi/InstaPy/instapy/util.py", line 20, in <module>
    from .quota_supervisor import quota_supervisor
  File "/home/pi/InstaPy/instapy/quota_supervisor.py", line 7, in <module>
    from plyer import notification
ImportError: No module named plyer

i did sudo pip install plyer, but still getting this error...

**Comment by johnvfitness** [comment]
I have a same problem #2868 look

**Comment by aku6640** [comment]
sudo pip install plyer doesn't work either..

**Comment by snakelab** [comment]
`sudo pip install plyer`
worked for me in venv python environment.

**Comment by jeremycjang** [comment]
^worked for me too. Make sure you've done ```git pull origin master``` and have the latest files installed

**Comment by aku6640** [comment]
still getting this error, I tried the things you said guys

Traceback (most recent call last):
  File "custom.py", line 8, in <module>
    from instapy import InstaPy
  File "/home/pi/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/home/pi/InstaPy/instapy/instapy.py", line 23, in <module>
    from .comment_util import comment_image
  File "/home/pi/InstaPy/instapy/comment_util.py", line 7, in <module>
    from .util import update_activity
  File "/home/pi/InstaPy/instapy/util.py", line 20, in <module>
    from .quota_supervisor import quota_supervisor
  File "/home/pi/InstaPy/instapy/quota_supervisor.py", line 7, in <module>
    from plyer import notification
ImportError: No module named plyer


anyone other ideas?

**Comment by aku6640** [comment]
update: 

i tried to run my script by writing sudo python3 custom.py (or maybe in your case, quickstart.py)
it then said no module named  " " (different modules)

i did sudo pip install "modulename" a few times and now the script is running again!

**Comment by britotiagos** [comment]
Just go to the folder where you have Installed the "ven" and run `sudo pip install plyer` get back to the instaPy folder and run `python quickstart.py`. 

PS: if needed a better explanation let me know. ;)

**Comment by aku6640** [comment]
hi @britotiagos  it already runs, thank you!
