### ISSUE TITLE
Error occured while getting a DB profile for 'None'

### ISSUE THREAD

**Issue by axlright** [InstaPy/InstaPy#2872]
## Expected Behavior

Newest update to run after copying `logs/username` directory into fresh install of InstaPy 

## Current Behavior

After downloading a fresh install of the newest update of InstaPy, running `pip install .`, copying Chrome Driver into `assets` and copying previous multiuser log directory into `logs` and running a session based on newest `quickstart.py`, get this crash:

```
WARNING [2018-09-07 13:33:28] [None]  Heeh! Error occured while getting a DB profile for 'None':
	b'NOT NULL constraint failed: profiles.name'
Traceback (most recent call last):
  File "hashtag-xxx.py", line 22, in <module>
    multi_logs=True)
  File "/Users/xxx/Documents/Code/InstaPy-xxxusernamexxx/instapy/instapy.py", line 209, in __init__
    get_database(make=True)
  File "/Users/xxx/Documents/Code/InstaPy-xxxusernamexxx/instapy/database_engine.py", line 43, in get_database
    id = get_profile(name, address, logger) if id is None or make else id
  File "/Users/xxx/Documents/Code/InstaPy-xxxusernamexxx/instapy/database_engine.py", line 129, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable
```

## InstaPy configuration

Mac running Homebrew Python 3.7

**Comment by axlright** [comment]
Tried again in a new session not having copied over the log files from a previous install - `logs` directory is empty, using a new session from `quickstart.py` and get a new directory `logs/None` and the error message

```
WARNING [2018-09-07 13:52:07] [None]  Heeh! Error occured while getting a DB profile for 'None':
	b'NOT NULL constraint failed: profiles.name'
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/Users/alexwright/Documents/Code/InstaPy-xxxusernamexxx/instapy/instapy.py", line 209, in __init__
    get_database(make=True)
  File "/Users/alexwright/Documents/Code/InstaPy-xxxusernamexxx/instapy/database_engine.py", line 43, in get_database
    id = get_profile(name, address, logger) if id is None or make else id
  File "/Users/alexwright/Documents/Code/InstaPy-xxxusernamexxx/instapy/database_engine.py", line 129, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable
```

**Comment by axlright** [comment]
Tried again in a new session not having copied over the log files from a previous install - logs directory is empty, using a new session from quickstart.py and get a new directory logs/None and the error message

```
WARNING [2018-09-07 13:52:07] [None]  Heeh! Error occured while getting a DB profile for 'None':
	b'NOT NULL constraint failed: profiles.name'
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/Users/xxx/Documents/Code/InstaPy-xxxusernamexxx/instapy/instapy.py", line 209, in __init__
    get_database(make=True)
  File "/Users/xxx/Documents/Code/InstaPy-xxxusernamexxx/instapy/database_engine.py", line 43, in get_database
    id = get_profile(name, address, logger) if id is None or make else id
  File "/Users/xxx/Documents/Code/InstaPy-xxxusernamexxx/instapy/database_engine.py", line 129, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable
```

**Comment by sandy1812** [comment]
I am having the same problem.
Was getting "Invalid like element" error, then I updated master, now this error -

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/root/InstaPy/instapy/instapy.py", line 209, in __init__
    get_database(make=True)
  File "/root/InstaPy/instapy/database_engine.py", line 43, in get_database
    id = get_profile(name, address, logger) if id is None or make else id
  File "/root/InstaPy/instapy/database_engine.py", line 129, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable

**Comment by IamRuby** [comment]
I'm also having this problem. I tried [this](https://github.com/timgrossmann/InstaPy/issues/2588), but it didn't help.

**Comment by sandy1812** [comment]
@timgrossmann Any help on this?

**Comment by callum8004** [comment]
Also struggling to get this to work :(

**Comment by axlright** [comment]
FWIW I am no longer having this issue. Can't point at which exact commit may have fixed it, but my installs are loading and working fine.

**Comment by sandy1812** [comment]
> FWIW I am no longer having this issue. Can't point at which exact commit may have fixed it, but my installs are loading and working fine.

Did you update the master again?

**Comment by axlright** [comment]
>Did you update the master again?
Yes I check for and pull / merge updates every time I use the application.

**Comment by Javi4** [comment]
Still having this issue :(

**Comment by AdamMoffitt** [comment]
Same issue here
