### ISSUE TITLE
Problem installing "plyer"

### ISSUE THREAD

**Issue by yxorp** [InstaPy/InstaPy#2879]
## Expected Behavior
plyer is successfully installed

## Current Behavior
I get this following error message when trying to install plyer using pip3

(venv) ubuntu@ip-172-31-8-139:~/InstaPy$ pip install plyer
Collecting plyer
  Using cached https://files.pythonhosted.org/packages/c4/19/f7cf7658e0f671294d8675a0bcc5d76883e8e738cc1e78dd097e2ea5fa72/plyer-1.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4koqrt35/plyer/setup.py", line 28, in <module>
        changelog = fd.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4636: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-4koqrt35/plyer/
(venv) ubuntu@ip-172-31-8-139:~/InstaPy$

**Comment by yxorp** [comment]
solved: had the LOCALE env variable set to "C". Set it to "export LC_ALL="en_US.UTF-8"" and it worked.
