### ISSUE TITLE
SyntaxError: EOL while scanning string literal

### ISSUE THREAD

**Issue by frankiefe** [InstaPy/InstaPy#2883]
Hello. I am trying to run quickstart.py for the first time and I get this. Can you please help me with this? I have Python 3.7 and did the configuration as the guide says. The only thing that i couldn`t do is to run get-pip.py (not sure if the problem is related)

Thanks a lot!!

**SyntaxError: EOL while scanning string literal**

C:\Users\usuario\Downloads\Fran\InstaPy>quickstart.py
Traceback (most recent call last):
  File "C:\Users\usuario\Downloads\Fran\InstaPy\quickstart.py", line 7, in <module>
    from instapy import InstaPy
  File "C:\Users\usuario\Downloads\Fran\InstaPy\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "C:\Users\usuario\Downloads\Fran\InstaPy\instapy\instapy.py", line 21
    'from .clarifai_util import check_image
                                          ^
SyntaxError: EOL while scanning string literal

**Comment by frankiefe** [comment]
![image](https://user-images.githubusercontent.com/43122235/45270711-c344b280-b476-11e8-95ee-ac76763b8384.png)

**Comment by frankiefe** [comment]
Once I installed emojis (pip install emoji) it worked out perfectly
