### ISSUE TITLE
Launch InstaPy and InstaPy Light

### ISSUE THREAD

**Issue by chairle007** [InstaPy/InstaPy#2895]
I have – I guess – the same kind of problem with InstaPy and InstaPy Light. 
Solved the first issue with the: pip3 install selenium

But the terminal says this: 

MacBook-Pro:Instapy honzakloucek$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 7, in <module>
    from instapy import InstaPy
  File "/Users/honzakloucek/Documents/workspace/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/Users/honzakloucek/Documents/workspace/InstaPy/instapy/instapy.py", line 11, in <module>
    import requests
ImportError: No module named requests
MacBook-Pro:Instapy honzakloucek$ cd /
MacBook-Pro:/ honzakloucek$ cd /Users/honzakloucek/Documents/workspace/InstaPy-Light
MacBook-Pro:InstaPy-Light honzakloucek$ python config.py
Traceback (most recent call last):
  File "config.py", line 5, in <module>
    from app import InstaPyLight
  File "/Users/honzakloucek/Documents/workspace/InstaPy-Light/app/__init__.py", line 1, in <module>
    from .instapy import InstaPyLight
  File "/Users/honzakloucek/Documents/workspace/InstaPy-Light/app/instapy.py", line 9, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay
MacBook-Pro:InstaPy-Light honzakloucek$

**Comment by kukkakeppi** [comment]
sudo python setup.py install <-- Try that one.

**Comment by chairle007** [comment]
Have tried it and still the same message :(

**Comment by converge** [comment]
it's because of your python version, you should do ```python3 quickstart.py```
