### ISSUE TITLE
selenium.common.exceptions.StaleElementReferenceException 

### ISSUE THREAD

**Issue by JoeFertig** [InstaPy/InstaPy#2899]
## Expected Behavior
Login, start running.

## Current Behavior:
pi@raspberrypi:~/instagram/Projects/InstaPy $ sudo xvfb-run python quickstart.py

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-09-11 21:27:37] [LOGINNAME]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...
Traceback (most recent call last):
  File "quickstart.py", line 29, in <module>
    session.login()
  File "/home/pi/instagram/Projects/InstaPy/instapy/instapy.py", line 370, in login
    self.bypass_suspicious_attempt):
  File "/home/pi/instagram/Projects/InstaPy/instapy/login_util.py", line 150, in login_user
    ActionChains(browser).move_to_element(login_elem).click().perform()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <a> stale: either the element is no longer attached to the DOM or the page has been refreshed

## Possible Solution (optional)
I really don't know :(

## InstaPy configuration
Running on a Rasp Pi 3+ with all Instapy Updates && Upgrades. Running headless or normal with Firefox.

Somehow it is super difficult to run this bot on the pi? Especially when using Chromium which doesn't work anymore. Too bad cause Chromium was really nice.

Would be so cool if we have a working installation for Instapy on Raspberry Pi 3+.

Please help :)

**Comment by thepoison606** [comment]
Same problem over here :/

**Comment by lukeacparsons** [comment]
I had "bypass_suspicious_attempt=True" in my quickstart.py and was getting this error on the Pi. Removed the line and it started running.
