### ISSUE TITLE
Exec format error on Raspberry Pi

### ISSUE THREAD

**Issue by Nocturnal-2** [InstaPy/InstaPy#2902]
## Info

I am setting up InstaPy in Raspberry Pi for the first time (using latest code from repository). I am getting "Exec format error"

## Log

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/pi/Desktop/Projects/py3virtualenv/InstaPy/instapy/instapy.py", line 212, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Desktop/Projects/py3virtualenv/InstaPy/instapy/instapy.py", line 319, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/Desktop/Projects/py3virtualenv/lib/python3.4/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/home/pi/Desktop/Projects/py3virtualenv/lib/python3.4/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

## Configuration

`session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)
`

**Comment by Nocturnal-2** [comment]
I am sorry, running as  **_sudo** python quickstart.py_ solved this issue.

**Comment by Nocturnal-2** [comment]
I tried installing in Ubuntu to see if I was facing the same error. But it is working well there. 

I face this issue only on Raspberry Pi (running Raspbian). Any help greatly appreciated! Thank you!

**Comment by shariqmoosa** [comment]
+1

**Comment by olaims** [comment]
one more here with the same error on Raspberry Pi 3

**Comment by Obsessi0n** [comment]
I'm having the same problem, I tested first on ubuntu and it worked fine, now I tried to install on raspberrypi 3 and I'm getting that error.

**Comment by tE3m** [comment]
I'm also having the same problem on a Raspberry Pi 3 Model B+.

**Comment by Cerebrock** [comment]
Same problem... no ideas?

**Comment by tE3m** [comment]
@Cerebrock this means that you have the wrong chromedriver binary for your system. I assume you're using an RPi, you can get the correct chromedriver like this:
```
pip3 install instapy-chromedriver==2.36.post0
```

**Comment by papillon-unix** [comment]
same problem on raspberry since updating to latest version (0.6). But since it's now firefox only, I guess it shouldn't be fixed with chromedriver 2.36, what do you think @TarekJ03 ? 
Any idea everyone? I'm struggling with this issue since days.
