### ISSUE TITLE
Error occured while deleting cookies from web browser!

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2913]
INFO [2018-09-12 06:23:22] [xxx]  --> Not following
INFO [2018-09-12 06:23:23] [xxx]  [15/40]
INFO [2018-09-12 06:23:23] [xxx]  https://www.instagram.com/p/x/?tagged=x
ERROR [2018-09-12 07:09:10] [xxx]  Error occured while deleting cookies from web browser!
        b'Message: timeout\n  (Session info: headless chrome=69.0.3497.81)\n  (Driver info: chromedriver=2.36 (7165af0ca9863529f28e493568ae3d105eddcdef),platform=Linux 4.1$
Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/util.py", line 658, in web_address_navigator
    browser.get(link)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=69.0.3497.81)
  (Driver info: chromedriver=2.36 (7165af0ca9863529f28e493568ae3d105eddcdef),platform=Linux 4.15.0-33-generic x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/5b6b2c94cecd67001461cda9.py", line 22, in <module>
    session.like_by_tags(['x','x','x','x','x','x','x'], amount=40)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 1462, in like_by_tags
    self.logger)
  File "/home/fredrik/InstaPy/instapy/like_util.py", line 404, in check_link
    web_address_navigator(browser, post_link)
  File "/home/fredrik/InstaPy/instapy/util.py", line 668, in web_address_navigator
    str(link).encode("utf-8"), str(exc).encode("utf-8")))
selenium.common.exceptions.TimeoutException: Message: Retried 7 times to GET 'b'https://www.instagram.com/p/BnnSxLZnr2E/?tagged=gothenburg'' webpage but failed out of a ti$
        b'Message: timeout\n  (Session info: headless chrome=69.0.3497.81)\n  (Driver info: chromedriver=2.36 (7165af0ca9863529f28e493568ae3d105eddcdef),platform=Linux 4.1$

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 3288, in end
    self.browser.delete_all_cookies()
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 866, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=69.0.3497.81)
  (Driver info: chromedriver=2.36 (7165af0ca9863529f28e493568ae3d105eddcdef),platform=Linux 4.15.0-33-generic x86_64)

**Comment by uluQulu** [comment]
@fgisslen The error message in the name of this thread is written by me and I know why it handles like that.
1-) Sometimes there are problems while deleting cookies and closing web browser, there are lots of problems in various kinds BUT I decided to catch all of them and only notify in WebDriverExceptions.

_Note that most of time it will successfully delete cookies and  close the web browser and SOMEtimes it will make such problems_.

Fine the thing is those exceptions occurred while deleting cookies and closing web are NON serious. [BASICALLY] and should be avoided.
But if you ALWAYS get problems with it then there is a problem.
The reasons I decided to output the `WebDriverException` messages is, it is an error just worth to see.


#### Lets's turn to the real problem in the issue ABOVE:
It failed out of timeout to GET the a webpage of `https://www.instagram.com/p/BnnSxLZnr2E/?tagged=gothenburg`.

How frequently you do get that kind of failures out of timeouts?

------

Cheers 😁
--------

**Comment by Joyen12** [comment]
Hi,
I got a similar error but I get it all the time.
Before everything was fine, I always do the same things but the yesterday it start to bahave that way, very strange...
 occurred while deleting cookies from web browser!
	Message: invalid session id
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-39-generic x86_64)
Traceback (most recent call last):
  File "/home/osboxes/InstaPy/instapy/instapy.py", line 3625, in end
    self.browser.delete_all_cookies()
  File "/home/osboxes/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/home/osboxes/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/osboxes/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: invalid session id
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-39-generic x86_64)

Thank a lot for your help

**Comment by Joyen12** [comment]
Third time I post, never get a reply...
So many bug that I always need to change machine and often re-install
I know it's free and you already done a good job but if you could help the guy struggling with those bugs that would be nice...

**Comment by tomtactom** [comment]
I have the same problem
how I can fix the error?

**Comment by LuismiLabs** [comment]
same here!!
