### ISSUE TITLE
When trying to use a proxy

### ISSUE THREAD

**Issue by namesreallyblank** [InstaPy/InstaPy#2941]
Traceback (most recent call last):
  File "quickstart.py", line 23, in <module>
    multi_logs=True)
  File "/root/InstaPy/instapy/instapy.py", line 212, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 298, in set_selenium_local_session
    proxy = ":".join([self.proxy_address, self.proxy_port])
TypeError: sequence item 1: expected string, int found

**Comment by ceribbo** [comment]
in the file instapy.py, search for self.proxy_port

when you see an if  (line starting with the if) you must substitute 
self.proxy_port with int(self.proxy_port)
