### ISSUE TITLE
latest master update issue

### ISSUE THREAD

**Issue by HCWcoder** [InstaPy/InstaPy#2958]
## Current Behavior
```
Traceback (most recent call last):
  File "xxx.py", line 71, in <module>
    session.follow_user_followers(competitors, amount=randint(140, 190), randomize=True, interact=True)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\instapy.py", line 2514, in follow_user_followers
    self.logfolder)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 884, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 698, in get_users_through_dialog
    person_list = dialog_username_extractor(buttons)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 721, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)
```

another error from another account and pc

```
Traceback (most recent call last):
  File "C:\Users\testing\Documents\GitHub\InstaPy\xxxx.py", line 69, in <module>
    session.follow_user_followers(competitors, amount=randint(140, 190), randomize=True, interact=True)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\instapy.py", line 2582, in follow_user_followers
    interact)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\instapy.py", line 905, in follow_by_list
    self.user_interact_media)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\instapy.py", line 1939, in interact_by_users
    self.logger('username actions: following={} commenting={} liking={}'.format(following, commenting, liking))
TypeError: 'LoggerAdapter' object is not callable
```

more 

```
Traceback (most recent call last):
  File "www.py", line 39, in job
    session.interact_user_followers(['example'], amount=1500, randomize=True)
  File "C:\Users\JP\Documents\GitHub\InstaPy\instapy\instapy.py", line 2286, in interact_user_followers
    self.user_interact_media)
  File "C:\Users\JP\Documents\GitHub\InstaPy\instapy\instapy.py", line 1939, in interact_by_users
    self.logger('username actions: following={} commenting={} liking={}'.format(following, commenting, liking))
TypeError: 'LoggerAdapter' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rrr.py", line 55, in <module>
    job()
  File "rrr.py", line 50, in job
    except WebDriverException:
NameError: name 'WebDriverException' is not defined
```

USING latest master update
Windows 10

everything was working before update but when updating Github got errors maybe because i fixed someprob previously and now the code didnt update so i had to remove instapy and clone again.

new errors shown 
please help

**Comment by sionking** [comment]
PR FIX:
self.logger
to:
self.logger.info

PR : https://github.com/timgrossmann/InstaPy/pull/2959

**Comment by Mizi91** [comment]
Last update didnt work for me. Any ideas? I get this error:

> Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.follow_user_followers(['anetasynkova', 'simonadockalova', 'kristyn.kolar', 'zuzanasedlacek', 'karolinahuvarova', 'nickynellow', 'verunka_s', 'andrejka_oo', 'kristyna_sixtova'], amount=100, randomize=True, interact=True, sleep_delay=180)
  File "C:\Program Files (x86)\Python37-32\InstaPy-master\instapy\instapy.py", line 2514, in follow_user_followers
    self.logfolder)
  File "C:\Program Files (x86)\Python37-32\InstaPy-master\instapy\unfollow_util.py", line 884, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "C:\Program Files (x86)\Python37-32\InstaPy-master\instapy\unfollow_util.py", line 644, in get_users_through_dialog
    scroll_bottom(browser, dialog, 2)
  File "C:\Program Files (x86)\Python37-32\InstaPy-master\instapy\util.py", line 466, in scroll_bottom
    "arguments[0].scrollTop = arguments[0].scrollHeight", element)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 635, in execute_script
    'args': converted_args})['value']
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)
PS C:\Program Files (x86)\Python37-32\InstaPy-master>

**Comment by uluQulu** [comment]
@HCWcoder 
@Mizi91 
Are your files up-to-date?

**Comment by Mizi91** [comment]
> @HCWcoder
> @Mizi91
> Are your files up-to-date?

I have reinstalled the script (deleted old files, downloaded now, runned python setup.py install and copied logs back, restart PC). It seems to work now. Is this the best way to update intapy?

**Comment by uluQulu** [comment]
That's great, @Mizi91
Your method of updating is a traditional way 😋

The thing is code integrity.
Actually, it does not matter how you apply it UNLESS you apply the changes properly.
It can be some new files or modifications in existing files, etc.

Arguebly, the best way is using powerful `git` commands
But I use GitHub's desktop app which auto-updates the files for me in a click.

You might have encounter some conflicts while pulling new changes, that's why I suggest you to learn a little bit about git.

Mastering `git` is always worthy these days cos it is gonna dominate source control systems.

------

Cheers 😁
----

**Comment by Mizi91** [comment]
> That's great, @Mizi91
> Your method of updating is a traditional way 😋
> 
> The thing is code integrity.
> Actually, it does not matter how you apply it UNLESS you apply the changes properly.
> It can be some new files or modifications in existing files, etc.
> 
> Arguebly, the best way is using powerful `git` commands
> But I use GitHub's desktop app which auto-updates the files for me in a click.
> 
> You might have encounter some conflicts while pulling new changes, that's why I suggest you to learn a little bit about git.
> 
> Mastering `git` is always worthy these days cos it is gonna dominate source control systems.
> 
> ## Cheers 😁

Thank you for advice :-)

However this  error still appears, but then instapy works properly. Is it crucial?
`ERROR:shader_disk_cache.cc(237) Failed to create shader cache entry: -2`

**Comment by uluQulu** [comment]
@Mizi91 
It not in our side, it is produced by the _chromedriver_ executable.
And I have seen it for a long time and never had a problem.

_Actually, there will be some error messages like that from the webdriver in your console but most of time they are not making a problem and should be avoided_.

------

Cheers 😁
----

**Comment by HCWcoder** [comment]
> @HCWcoder
> @Mizi91
> Are your files up-to-date?

Thanks for your reply

Yes it was [this issue](https://github.com/timgrossmann/InstaPy/issues/2958#issuecomment-422988561)

Its fixed now!
