### ISSUE TITLE
Error occured while deleting cookies from web browser!

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2962]
@uluQulu why is it trying to delete a cookie here?

INFO [2018-09-19 15:13:36] [xx]  New link found...
INFO [2018-09-19 15:13:36] [xx]  [1 posts liked /20 amount]
INFO [2018-09-19 15:13:36] [xx]  https://www.instagram.com/p/xx/
ERROR [2018-09-19 15:58:51] [xx]  Error occured while deleting cookies from web browser!
        b'Message: timeout\n  (Session info: headless chrome=69.0.3497.81)\n  (Driver info: chromedriver=2.36 (7165af0ca9863529f28e493568ae3d105eddcdef),platform=Linux 4.15.0-33-generic x86_64)\n'
Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/util.py", line 656, in web_address_navigator
    browser.get(link)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=69.0.3497.81)
  (Driver info: chromedriver=2.36 (7165af0ca9863529f28e493568ae3d105eddcdef),platform=Linux 4.15.0-33-generic x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/5b84834e2106a80014090937.py", line 24, in <module>
    session.like_by_feed(amount=20, randomize=True, unfollow=False, interact=False)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 2835, in like_by_feed
    for i in self.like_by_feed_generator(**kwargs):
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 2928, in like_by_feed_generator
    self.logger)
  File "/home/fredrik/InstaPy/instapy/like_util.py", line 404, in check_link
    web_address_navigator(browser, post_link)
  File "/home/fredrik/InstaPy/instapy/util.py", line 666, in web_address_navigator
    str(link).encode("utf-8"), str(exc).encode("utf-8")))
selenium.common.exceptions.TimeoutException: Message: Retried 7 times to GET 'b'https://www.instagram.com/p/Bn6U6wNlgaO/'' webpage but failed out of a timeout!
        b'Message: timeout\n  (Session info: headless chrome=69.0.3497.81)\n  (Driver info: chromedriver=2.36 (7165af0ca9863529f28e493568ae3d105eddcdef),platform=Linux 4.15.0-33-generic x86_64)\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 3298, in end
    self.browser.delete_all_cookies()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 866, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=69.0.3497.81)
  (Driver info: chromedriver=2.36 (7165af0ca9863529f28e493568ae3d105eddcdef),platform=Linux 4.15.0-33-generic x86_64)

**Comment by uluQulu** [comment]
Hi @fgisslen 
>TimeoutException: Message: Retried 7 times to GET 'b'https://www.instagram.com/p/Bn6U6wNlgaO/'' webpage but failed out of a timeout!

It failed to get that page WHERE it raises a TimeoutException WHICH kills the program at that stage.
I have intentionally chose that termination after those attempts.
If you think the program should continue after a timeout WELL it can be accomplished but will be difficult.

I offer again try to get a HEALTHY [not FAST since even 1MB/s is enough 🙂] connection.

Well, as you know once program exits it executes `end()` method WHICH removes the cookies and closes the web browser.
And it is an unknown fact that it sometimes fails to delete cookies BUT it is not an issue.

----

Cheers 😁
-----

**Comment by fgisslen** [comment]
@uluQulu thanks for your answer.
But I actually think the connection is healthy this one was through digital ocean.

Or maybe it was on an other server, will check. But okey. Maybe I should place every account on cloud server.

**Comment by jeremycjang** [comment]
Experiencing this as well running locally instead of from a server; only seeing it if running concurrent sessions for different accounts though
