### ISSUE TITLE
BUG: xpath element for login changed.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2974]
For 10% of users i get the following:

This section of code:
```
    # Check if the first div is 'Create an Account' or 'Log In'
    login_elem = browser.find_element_by_xpath(
        "//article/div/div/p/a[text()='Log in']")
```
throw:
```
 Traceback (most recent call last):
  File "quickstart.py", line 69, in job
    session.login()
  File "C:\Users\1\1\instapy\instapy.py", line 473, in login
    self.bypass_suspicious_attempt):
  File "C:\Users\1\1\instapy\login_util.py", line 162, in login_user
    "//article/div/div/p/a[text()='Log in']")
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 393, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//article/div/div/p/a[text()='Log in']"}
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)

```

**Comment by sionking** [comment]
UPDATE:
this is something wrong in graphql activity_counts have changed.

**Comment by sionking** [comment]
Need to check for:
valid_connection = browser.execute_script(
                    "return window._sharedData.config.viewer")

instead

**Comment by sionking** [comment]
PERFORMANCE:
we shall not check for:
```
    # Cookie has been loaded, user should be logged in. Ensurue this is true
    login_elem = browser.find_elements_by_xpath(
        "//*[contains(text(), 'Log in')]")
```
every login, since most of the login times we are already logged in, and this element look up is taking too long, we shall look for logged in element first.

**Comment by d3rf** [comment]
> 
> 
> PERFORMANCE:
> we shall not check for:
> 
> ```
>     # Cookie has been loaded, user should be logged in. Ensurue this is true
>     login_elem = browser.find_elements_by_xpath(
>         "//*[contains(text(), 'Log in')]")
> ```
> 
> every login, since most of the login times we are already logged in, and this element look up is taking too long, we shall look for logged in element first.

So what I should do?
