### ISSUE TITLE
Running InstaPy Bot on Pythonanywhere 

### ISSUE THREAD

**Issue by J-Arasti** [InstaPy/InstaPy#2992]
Hi, 
First of all, sorry for my English!
I've done everything for installing and running this bot on pythonanywhere, but last error that i've recieved and could not solve is this:
(ENV) 10:36 ~ $ python quickstart.py
ERROR [2018-09-23 10:44:00] [*******]  Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Traceback (most recent call last):
  File "/home/JAPython1/ENV/local/lib/python2.7/site-packages/instapy/instapy.py", line 331, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/JAPython1/ENV/local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/JAPython1/ENV/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/JAPython1/ENV/local/lib/python2.7/site-packages/instapy/instapy.py", line 215, in __init__
    self.set_selenium_local_session()
  File "/home/JAPython1/ENV/local/lib/python2.7/site-packages/instapy/instapy.py", line 335, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/JAPython1/ENV/local/lib/python2.7/site-packages/assets/chromedriver
ANYONE CAN HLEP ME? 
Thanks a lot

**Comment by IH4xx3R** [comment]
A lot of linux users have issues with the "ensure chromedriver" error. Still waiting for a solution..

**Comment by J-Arasti** [comment]
waiting for IT is stupid, change the way. something i've got from pythonanywhere response bot is it could not support chromedriver
