### ISSUE TITLE
Having trouble installing InstaPy for the first time

### ISSUE THREAD

**Issue by pinkoveralls** [InstaPy/InstaPy#3036]
Hi, I'm trying to install InstaPy on my Windows 10 64 desktop, and I'm having trouble. The tutorial is a bit outdated and Microsoft Visual C++ 2015 Build Tools is no longer available to download, so I have the 2017 version. I also can't figure out how to install Microsoft .NET Framework V.3.5 (Including: .NET Framework 2.0 and 3.0, and includes .NET Framework 2.0 service pack 1 and .NET Framework 3.0 service pack 1), I've downloaded the file linked in the windows installation guide, but it doesn't have an installation process. 

I have everything else, and have python, pip, and pathways set up already, but I can't get through the installation process and I'm not sure what I'm doing wrong (probably a lot lol). 

Thank you in advance for any help.

When I run imput python setup.py install I get:

```
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    platforms=["win32", "linux", "linux2", "darwin"]
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\install.py", line 117, in do_egg_install
    cmd.run()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\easy_install.py", line 646, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\easy_install.py", line 742, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 850, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 1122, in best_match
    return self.obtain(req, installer)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 1134, in obtain
    return installer(requirement)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\easy_install.py", line 665, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\easy_install.py", line 876, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\easy_install.py", line 1115, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\easy_install.py", line 1101, in run_setup
    run_setup(setup_script, args)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\sandbox.py", line 251, in run_setup
    raise
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\sandbox.py", line 143, in resume
    type, exc = map(pickle.loads, self._saved)
ModuleNotFoundError: No module named 'commands'
```

**Comment by kwstasna** [comment]
Test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by animetrk** [comment]
It says "ModuleNotFoundError: No module named 'commands'" in the last line. You should try `pip install commands` and any other modules that will give error after that.

**Comment by pinkoveralls** [comment]
@animetrk When I run that it gives me 

'Could not find a version that satisfies the requirement commands (from versions: )
No matching distribution found for commands'

**Comment by pinkoveralls** [comment]
Never mind I got it working, the basics installation says 3. pip install . or 3. python setup.py install, I needed to do both, now it works.
