### ISSUE TITLE
Problem raspberry 3B+ Firefox ESR

### ISSUE THREAD

**Issue by julienkermarec** [InstaPy/InstaPy#3038]
## Expected Behavior
Since Wednesday, i have a error because DOM of instagram login have changed, i have installed the new version today, but i have this error in  ActionChains(browser).move_to_element(login_elem).click().perform()

# Current Behavior
Traceback (most recent call last):
  File "examples/firefoxExample.py", line 27, in <module>
    session.login()
  File "/usr/local/lib/python2.7/dist-packages/instapy/instapy.py", line 350, in login
    self.bypass_suspicious_attempt):
  File "/usr/local/lib/python2.7/dist-packages/instapy/login_util.py", line 142, in login_user
    ActionChains(browser).move_to_element(login_elem).click().perform()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (888.5, 709) is out of bounds of viewport width (1280) and height (585)

## InstaPy configuration
raspberry 3B+
Firefox ESR

**Comment by julienkermarec** [comment]
Solved with the firefox patcher example, in examples/firefox_patcher.
[https://github.com/timgrossmann/InstaPy/pull/2865/commits/789bb030cbdf4d64a208970844215c938414dd2f](url)

I have updated my launcher : 

from instapy.monkey_patcher import patch_all
patch_all()

Thank you @nyx-rattapoom  !!

**Comment by julienkermarec** [comment]
Issue reopened, do you have more info @nyx-rattapoom ?

![capture d ecran 2018-10-01 a 15 09 31](https://user-images.githubusercontent.com/3876561/46290422-1ac4d280-c58c-11e8-9412-54d8e2eb0be7.png)

**Comment by julienkermarec** [comment]
Partially solved with resolution update 

![capture d ecran 2018-10-01 a 15 27 04](https://user-images.githubusercontent.com/3876561/46291352-84de7700-c58e-11e8-9c1d-4f748feafda2.png)

**Comment by nyx-rattapoom** [comment]
@julienkermarec use `click_element` function from .util 

change 
`
ActionChains(browser).move_to_element(login_elem).click().perform()
`
to
`
click_element(browser, login_elem)
`
if you use raspberry pi 3 you can use chrome headless. it much more stable than firefox esr.
ps. bug is from W3C Command internal use of firefox legacy version it has been resolve in newer.
my patch useless in some case :(
