### ISSUE TITLE
Raspberry PI: WARNING [2018-09-28 20:57:01] [None]  Heeh! Error occured while getting a DB profile for 'None':

### ISSUE THREAD

**Issue by S4nderr** [InstaPy/InstaPy#3041]
how do i set the right DB profile?

`
WARNING [2018-09-28 20:57:01] [None]  Heeh! Error occured while getting a DB profile for 'None':
	NOT NULL constraint failed: profiles.name
Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    headless_browser=False)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 214, in __init__
    get_database(make=True)
  File "/home/pi/Projects/InstaPy/instapy/database_engine.py", line 43, in get_database
    id = get_profile(name, address, logger) if id is None or make else id
  File "/home/pi/Projects/InstaPy/instapy/database_engine.py", line 129, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable
`

**Comment by sandy1812** [comment]
same issue with me

**Comment by arcasoy** [comment]
Same here! Any help from anyone?

**Comment by fahmiteka** [comment]
heeelp ! me

**Comment by thEpisode** [comment]
Include your credentials in quickstart.py
