### ISSUE TITLE
cookie file not found, creating cookie... 

### ISSUE THREAD

**Issue by muraterdogann** [InstaPy/InstaPy#3076]
I've tried previous topic's solutions. But my bot still can not create cookie.Anyone got the latest working login_util.py?

**Comment by AustereSG** [comment]
same issue

Cookie file not found, creating cookie...
Traceback (most recent call last):
  File "C:\Users\Auste\Downloads\InstaPy-master\InstaPy-master\quickstart.py", line 20, in <module>
    session.login()
  File "C:\Users\Auste\Downloads\InstaPy-master\InstaPy-master\instapy\instapy.py", line 384, in login
    self.bypass_suspicious_attempt):
  File "C:\Users\Auste\Downloads\InstaPy-master\InstaPy-master\instapy\login_util.py", line 239, in login_user
    "//form/span/button[text()='Log in']")
  File "C:\Users\Auste\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Auste\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Auste\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Auste\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)

**Comment by pilarfc** [comment]
Same problem here!

**Comment by Zettt** [comment]
Is anyone working on this? I saw some other issues such as #3092 and #3075, which look exactly like this issue might cause it. Are they related?

**Comment by eschick** [comment]
Experiencing the exact same issue! I've even tried reinstalling all of Instapy, which usually works but got the same issue.

**Comment by Zettt** [comment]
Still unable to login. Tried firefox for a change. Here's the log.

```
Cookie file not found, creating cookie...
Traceback (most recent call last):
  File "instapy_zettt.py", line 43, in <module>
    session.login()
  File "/Users/zettt/Coding/InstaPy/instapy/instapy.py", line 390, in login
    self.bypass_suspicious_attempt):
  File "/Users/zettt/Coding/InstaPy/instapy/login_util.py", line 239, in login_user
    "//form/span/button[text()='Log in']")
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //form/span/button[text()='Log in']
```

@muraterdogann Would it be possible for you to update your issue, and fill in the blanks for "expected behavior"?

**Comment by ajankuv** [comment]
see #3137 hope this helps
