### ISSUE TITLE
: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//footer[@class='_s5vm9']/div

### ISSUE THREAD

**Issue by imv7** [InstaPy/InstaPy#3092]
staPy root# python quickstart.py 
INFO - Session started - 2018-10-06 18:44:17
Traceback (most recent call last):
  File "quickstart.py", line 9, in <module>
    session.login()
  File "/Users/igor/Desktop/InstaPy/instapy/instapy.py", line 219, in login
    self.switch_language):
  File "/Users/igor/Desktop/InstaPy/instapy/login_util.py", line 18, in login_user
    "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav[@class='_luodr']/ul[@class='_g8wl6']/li[@class='_538w0'][10]/span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8),platform=Mac OS X 10.13.5 x86_64)

IGOR-3:InstaPy root#

**Comment by imv7** [comment]
It is only typing PASSWORD

**Comment by imv7** [comment]
seems not finding USERNAME and being redirected from instagram.com to login url
