### ISSUE TITLE
Continue by location

### ISSUE THREAD

**Issue by facamx** [InstaPy/InstaPy#3098]
## Expected Behavior
Could you help me ?

I would like the script to find all the people in a location, from various locations, to like any image of any of these people that has at least 10 followers, and to follow people who are over 30 followers Or that follow all could also be.

The locations I have are about 30.

Then I want to stop following them at the time and never again follow someone who already follows me.

My account already has about 75,000 followers (no script).

Would they help me? I executed it 1 day but it did not give much results, with my parameters clear, if someone was kind enough to help me generate a quickstart to do this !! thank you very much.

**Comment by facamx** [comment]
After executing by location 3 hours, when returning now to relaunch it I get the following error: INFO [2018-10-09 00:11:32] [xxxxxxx.yyyy] Location [1/1]
INFO [2018-10-09 00:11:32] [xxxxxxx.yyyy] -> 237453756
Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.like_by_locations (['237453756'], amount = 200)
  File "/InstaPy/instapy/instapy.py", line 1098, in like_by_locations
    skip_top_posts)
  File "/InstaPy/instapy/like_util.py", line 79, in get_links_for_location
    web_address_navigator (browser, location_link)
  File "/InstaPy/instapy/util.py", line 778, in web_address_navigator
    current_url = get_current_url (browser)
  File "/InstaPy/instapy/util.py", line 1222, in get_current_url
    current_url = browser.execute_script ("return window.location.href")
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args}) ['value']
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute (driver_command, params)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request (command_info [0], url, body = data)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 433, in _request
    resp = self._conn.getresponse ()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin ()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status ()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline (_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv (self._rbufsize)
socket.error: [Errno 54] Connection reset by peer
bash-3.2 #
