### ISSUE TITLE
'Service' Object has no attribute 'process'

### ISSUE THREAD

**Issue by Ketcap** [InstaPy/InstaPy#310]
`Traceback (most recent call last):
  File "index.py", line 3, in <module>
    InstaPy(username="xxxxx",password="xxxx")\
  File "/Users/ketchup/Desktop/InstaPy/instapy/instapy.py", line 38, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x100785c50>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 163, in __del__
    self.stop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 135, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'`

I got this error on MacOS

Already installed with 
pip3 install . 
and folder has permissions chromedriver inside path variables

**Comment by Ketcap** [comment]
I got the problem after i wrote it. Chromedriver should be inside assets instead of path
