### ISSUE TITLE
resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3118]
Hi got this wierd error.
@uluQulu any idea?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/util.py", line 622, in click_element
    element.click()
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.15.0-36-generic x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/5ba8916314f15b001380f7a8.py", line 30, in <module>
    session.follow_commenters(['xx'], amount=70, daysold=100,max_pic = 100, sleep_delay=600, interact=True)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 653, in follow_commenters
    commenters = extract_information(self.browser, username, daysold, max_pic)
  File "/home/fredrik/InstaPy/instapy/commenters_util.py", line 217, in extract_information
    user_commented_list, pic_date_time = extract_post_info(browser)
  File "/home/fredrik/InstaPy/instapy/commenters_util.py", line 54, in extract_post_info
    click_element(browser, load_more_comments_element)
  File "/home/fredrik/InstaPy/instapy/util.py", line 663, in click_element
    click_element(browser, element, tryNum)
  File "/home/fredrik/InstaPy/instapy/util.py", line 663, in click_element
    click_element(browser, element, tryNum)
  File "/home/fredrik/InstaPy/instapy/util.py", line 663, in click_element
    click_element(browser, element, tryNum)
  File "/home/fredrik/InstaPy/instapy/util.py", line 648, in click_element
    "document.getElementsByClassName('" + element.get_attribute("class") + "')[0].click()")
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 143, in get_attribute
    resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.15.0-36-generic x86_64)

**Comment by benniphilipp** [comment]
The same thing

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
