### ISSUE TITLE
Crash with commenting [verify_commenting()]

### ISSUE THREAD

**Issue by botboteverywhere** [InstaPy/InstaPy#3143]
## Expected Behavior

Commenting on posts containing specific hashtags (either generally or specifically using Clarifai image recognition).

My setup:
- Mac OS 10.12.6
- Chrome
- Latest InstaPy
- Latest Chromedriver

## Current Behavior
The bot crashes instead. See traceback below. 

NB: As suggested in #1408, I tried to add "self.logfolder" as a fifth argument to the verify_commenting() function (in instapy.py, line 1819), but it continued to crash afterwards.

See console traceback below:

```
Traceback (most recent call last):

  File "quickstart.py", line 64, in <module>

    session.like_by_tags(random.sample(like_tag_list, 3), amount=random.randint(5,8), interact=True, skip_top_posts=True, use_smart_hashtags=False, randomize=True, media='Photo')

  File "/Users/*XXX*/Documents/*FILEPATH*/instapy/instapy.py", line 1636, in like_by_tags

    self.user_interact_media)

  File "/Users/*XXX*/Documents/*FILEPATH*/instapy/instapy.py", line 1819, in like_by_users

    self.logger)

TypeError: verify_commenting() takes exactly 5 arguments (4 given)
```

## Possible Solution (optional)
Add another 5th function to verifycommenting(), but which one?

## InstaPy configuration

```
#additional imports random amount of likes, hastags, comments and unfollows
import random

from instapy import InstaPy
from instapy.util import smart_run



#login credentials
insta_username = 'xxx'
insta_password = 'yyy'

dont_likes = ['stranger', 'sopretty','swole', 'snowstorm', 'todayimwearing', 'teens', 'teen', 'thought', 'tag4like', 'thighs', 'undies', 'follow4follow','yolo','struggleisreal']

friends = ["xxx", "yyy" ]

like_tag_list = ['planetdiscovery','theglobewanderer','exploringtheglobe','modernoutdoors' 'collectivelycreate', 'liveoutdoors']


session = InstaPy(username=insta_username,
                password=insta_password,
                nogui=False,
                headless_browser=False,
                disable_image_load=False,
                selenium_local_session=True,
                use_firefox=False,
                browser_profile_path=None,
                page_delay=20,
                show_logs=True,
                proxy_address=None,
                proxy_chrome_extension=None,
                proxy_port=0,
                bypass_suspicious_attempt=True,
                multi_logs=True)

with smart_run(session):
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=0.4,
				  delimit_by_numbers=True,
				   max_followers=2000,
				    max_following=4000,
				     min_followers=150,
				      min_following=200)

                      
    session.set_dont_include(friends)
    session.set_dont_like(dont_likes)
    session.set_user_interact(amount=random.randint(1,3), randomize=True, percentage=100)
    session.set_delimit_liking(enabled=True, max=None, min=3)
    session.set_delimit_commenting(enabled=True, max=30, min=None)
    session.set_do_follow(enabled=True, percentage=80, times=1)
    session.set_do_comment(enabled=True, percentage=30)
    session.set_use_clarifai(enabled=True, api_key='WWW', full_match=False)
    session.clarifai_check_img_for(tags=['traveller','ocean','seaside','holidays','roadtrip'], tags_skip=['rest','indoor','sleep','death','grief','sadness','mourning','injury','hospital'], comment=True, comments=[u'@{} All in! :fire:','Nice trip!', u"it's THAT time of the year again! :100:"])
    session.set_comments(['that one is great', u'cool! :100:', '@{} sweet!'])


    # actions
    session.like_by_tags(random.sample(like_tag_list, 3), amount=random.randint(5,8), interact=True, skip_top_posts=True, use_smart_hashtags=False, randomize=True, media='Photo')


    session.unfollow_users(amount=random.randint(71,87), InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=48*60*60, sleep_delay=501)
```

**Comment by sionking** [comment]
you are right I missed one:
like_by_users

change:
```
                                     disapproval_reason) = verify_commenting(
                                        self.browser,
                                        self.max_comments,
                                        self.min_comments,
                                        self.logger)
```
to:
```
                                     disapproval_reason) = verify_commenting(
                                        self.browser,
                                        self.max_comments,
                                        self.min_comments,
                                        self.comments_mandatory_words,
                                        self.logger)
```

**Comment by botboteverywhere** [comment]
thanks @sionking!

**Comment by botboteverywhere** [comment]
think we can close this issue now
