### ISSUE TITLE
Traceback (most recent call last):   File "john2.py", line 45, in <module> this my problem today

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#3157]
Traceback (most recent call last):
  File "john2.py", line 45, in <module>
    session.follow_user_followers(['tiboinshape','jujufitcats','justinegallice','stanimal9','antonao','carolineclnfit', 'fitbyclem','chloe_fit_','mmjhottie','__bigwill__'], amount=10, randomize=True, interact=True, sleep_delay=600)
  File "/Users/jonathanverdier/Desktop/Bot/instapy/instapy.py", line 2523, in follow_user_followers
    self.logfolder)
  File "/Users/jonathanverdier/Desktop/Bot/instapy/unfollow_util.py", line 906, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/Users/jonathanverdier/Desktop/Bot/instapy/unfollow_util.py", line 713, in get_users_through_dialog
    person_list = dialog_username_extractor(buttons)
  File "/Users/jonathanverdier/Desktop/Bot/instapy/unfollow_util.py", line 736, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webelement.py", line 68, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=69.0.3497.100)
  (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.13.6 x86_64)

@uluQulu

**Comment by alexmourer** [comment]
I had this error as well. I updated to the latest version of InstaPy and the error was corrected.

**Comment by johnvfitness** [comment]
Thx I test @alexmourer :)

**Comment by johnvfitness** [comment]
Same error :(

**Comment by alexmourer** [comment]
Try comparing the file your executing vs the Quick Start file. It looks like this has recently changed. Maybe that is your issue?

**Comment by johnvfitness** [comment]
same problem I have next file quick start same issue bro :(

**Comment by Danrrodrigues** [comment]
I commented "#session.set_delimit_commenting" its work, but it does not answer :(
