### ISSUE TITLE
Issue with cookie

### ISSUE THREAD

**Issue by cormo1990** [InstaPy/InstaPy#3160]
Hi friends, I have this issue with one of my account and I don't know how to fix it.
@uluQulu @sionking @anna-osipova can you help please? 

after start instaPy, the browser try to login on IG but on my console screen appeared this message:

"issue with cookie of xxxx, creating new cookie"

after that InstaPy crash

Traceback (most recent call last):
  File "xxxx.py", line 25, in <module>
    session.login()
  File "/Users/xxx/Desktop/InstaPy/instapy/instapy.py", line 382, in login
    self.bypass_suspicious_attempt):
  File "/Users/xxx/Desktop/InstaPy/instapy/login_util.py", line 239, in login_user
    "//form/span/button[text()='Log in']")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.14.1-py3.7.egg/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.14.1-py3.7.egg/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.14.1-py3.7.egg/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.14.1-py3.7.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.12.6 x86_64)

**Comment by cormo1990** [comment]
Solved download the latest version...sorry guys
