### ISSUE TITLE
 Failed to establish a new connection: [Errno 111] Connection refused',))

### ISSUE THREAD

**Issue by GriffinCrown** [InstaPy/InstaPy#3162]
**## Expected Behavior**

Session runs and likes 500 photos based off the tag.

**## Current Behavior**

I am receiving a connection refused error. It ran fine the first time I ran it for 10 likes, I then went and changed the tags and set the like amount to 500. It is now giving me the following error:

**## InstaPy configuration**

root@instapy:~# cd InstaPy
root@instapy:~/InstaPy# python quickstart.py

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-18 23:56:28] [myusername]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

.................................................................
INFO [2018-10-18 23:57:02] [myusername]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-10-18 23:57:05] [myusername]  Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
currently FOLLOWING 0 users & has got 0 FOLLOWERS

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-18 23:57:05] [myusername]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2018-10-18 23:57:05] [myusername]  Tag [1/1]
INFO [2018-10-18 23:57:05] [myusername]  --> travelphotography
Traceback (most recent call last):
  File "quickstart.py", line 33, in <module>
    session.like_by_tags(["travelphotography"], amount=500)
  File "/root/InstaPy/instapy/instapy.py", line 1491, in like_by_tags
    self.logger)
  File "/root/InstaPy/instapy/like_util.py", line 209, in get_links_for_tag
    web_address_navigator(browser, tag_link)
  File "/root/InstaPy/instapy/util.py", line 791, in web_address_navigator
    current_url = get_current_url(browser)
  File "/root/InstaPy/instapy/util.py", line 1235, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriv                                                                                                                                   er.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriv                                                                                                                                   er.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_                                                                                                                                   connection.py", line 376, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_                                                                                                                                   connection.py", line 399, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 72, in                                                                                                                                    request
    **urlopen_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 150, in                                                                                                                                    request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 323                                                                                                                                   , in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line                                                                                                                                    667, in urlopen
    **response_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line                                                                                                                                    667, in urlopen
    **response_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line                                                                                                                                    667, in urlopen
    **response_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line                                                                                                                                    638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 398,                                                                                                                                    in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=6093                                                                                                                                   5): Max retries exceeded with url: /session/f5a7c936ebf5289374a01bd201957624/exe                                                                                                                                   cute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at                                                                                                                                    0x7f95811c0550>: Failed to establish a new connection: [Errno 111] Connection r                                                                                                                                   efused',))
root@instapy:~/InstaPy#

_______________________________________________-

What can I do to try and solve this? Let me know if there is anything else that you need!

**Comment by namesreallyblank** [comment]
I had the same issue, posted it and got no reply. I solved this issue by destroying my droplet, got another new one and installed a fresh InstaPy. Make sure you read the docs and download any custom quickstart file you made and upload it on the new server. Hope that helps...

**Comment by AdamStone32** [comment]
Check your template...most likely your session calls are running outside the smart_run(session) call due to indentation.

**Comment by gitpatrickhub** [comment]
See solution in #3311 it worked for me, no longer receiving this error
