### ISSUE TITLE
Message: unknown error: unable to discover open pages

### ISSUE THREAD

**Issue by dpashutskii** [InstaPy/InstaPy#3163]
## Expected Behavior
Work without error.

## Current Behavior
Started to get this error a few days ago, tried reinstall chrome driver and pulled all last changes from the repo, still have an error:
```
ERROR [2018-10-19 14:47:13] [dn.journey]  Message: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-1020-aws x86_64)
Traceback (most recent call last):
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 341, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-1020-aws x86_64)

Traceback (most recent call last):
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 341, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-1020-aws x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    nogui=True)
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 225, in __init__
    self.set_selenium_local_session()
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 345, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/ubuntu/InstaPy/assets/chromedriver
```

## InstaPy configuration
```
    session.login()

    # settings
    session.set_do_comment(enabled=True, percentage=10)
    session.set_smart_hashtags([['XXXX', 'XXXX2'], limit=15, sort='top', log_tags=True)
    session.set_comments(
        ['XXXX', 'XXXX2'],
        media='Photo'
    )
    session.set_do_follow(enabled=True, percentage=15, times=2)
    session.set_user_interact(amount=4, randomize=True, percentage=60, media='Photo')
    session.like_by_tags(amount=10, use_smart_hashtags=True)

    # actions
    session.follow_user_followers(
         ['XXXX', 'XXXX2'],
         amount=15,
         randomize=True,
         interact=True,
         sleep_delay=600
     )
    session.unfollow_users(
        amount=150,
        nonFollowers=True,
        style="RANDOM",
        unfollow_after=42*60*60,
        sleep_delay=655
    )
```

**Comment by dpashutskii** [comment]
@uluQulu @timgrossmann Could you help?
