### ISSUE TITLE
TypeError in Instapy.py

### ISSUE THREAD

**Issue by sebblessing** [InstaPy/InstaPy#3177]
## Expected Behavior
I've this Error:

```
Traceback (most recent call last):
  File "Campange1_4.py", line 425, in <module>
    
  File "Campange1_4.py", line 287, in likeSeq
    session.like_by_tags(['tag1','tag2'], amount=randint(30,50), interact=True)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 1583, in like_by_tags
    self.photo_comments)
TypeError: unsupported operand type(s) for +: 'method' and 'method'
```

My Function just use session.like_by_tags and the Error should be in the instapy.py. I've no idea how to fix it.

## InstaPy configuration
It runs on the RPi 3+ with Rasbian and the Chromium and Chromedriver Version form the Installationguide.
The quickstart works fine. Just the like_by_tags method makes issures.

This is my InstaPy configuration:
       
        session.login()
        session.set_relationship_bounds(enabled=False)
        session.set_comments(comments=kommentare, media='Photo')
        session.set_do_comment(enabled=True, percentage = randint(50,80)) 
        session.set_do_like(enabled=True, percentage=randint(50,80))
        session.set_do_follow(enabled=True, percentage=randint(20,30), times=1)
        session.set_user_interact(amount=1, randomize=True, percentage=randint(80,99), media='Photo')
        session.set_blacklist(enabled=True, campaign=blacklist)
        session.set_simulation(enabled=True)

**Comment by sebblessing** [comment]
Oh i fixed it, sorry guys, my false!
