### ISSUE TITLE
Stale element reference and cannot read property 'scrollIntoView' of undefined.

### ISSUE THREAD

**Issue by nazariyv** [InstaPy/InstaPy#3187]
## Expected Behavior
I do not get the error.

## Current Behavior
This is running a simple quickstart.

I am either getting a `stale element reference now`, or `cannot read property 'scrollIntoView' of undefined`

Here are the tracebacks (first stale element, and then 'scrollIntoView'):

```
Traceback (most recent call last):
  File "quickstart_ua.py", line 92, in <module>
    interact=True)
  File "/home/nazariy/git/InstaPy/instapy/instapy.py", line 2490, in follow_user_followers
    self.logfolder)
  File "/home/nazariy/git/InstaPy/instapy/unfollow_util.py", line 918, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/home/nazariy/git/InstaPy/instapy/unfollow_util.py", line 704, in get_users_through_dialog
    quick_username = dialog_username_extractor(quick_button)
  File "/home/nazariy/git/InstaPy/instapy/unfollow_util.py", line 751, in dialog_username_extractor
    .find_elements_by_tag_name("a")[1].text)
  File "/home/nazariy/anaconda/envs/insta_fame/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 320, in find_elements_by_tag_name
    return self.find_elements(by=By.TAG_NAME, value=name)
  File "/home/nazariy/anaconda/envs/insta_fame/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 680, in find_elements
    {"using": by, "value": value})['value']
  File "/home/nazariy/anaconda/envs/insta_fame/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/home/nazariy/anaconda/envs/insta_fame/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/nazariy/anaconda/envs/insta_fame/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=70.0.3538.67)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-36-generic x86_64)
```
And
```
Traceback (most recent call last):
  File "quickstart_en.py", line 94, in <module>
    interact=True)
  File "/home/nazariy/git/InstaPy/instapy/instapy.py", line 2490, in follow_user_followers
    self.logfolder)
  File "/home/nazariy/git/InstaPy/instapy/unfollow_util.py", line 918, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/home/nazariy/git/InstaPy/instapy/unfollow_util.py", line 664, in get_users_through_dialog
    scroll_to_bottom_of_followers_list(browser, dialog)
  File "/home/nazariy/git/InstaPy/instapy/unfollow_util.py", line 621, in scroll_to_bottom_of_followers_list
    "arguments[0].children[1].scrollIntoView()", element)
  File "/home/nazariy/anaconda/envs/insta_fame/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 635, in execute_script
    'args': converted_args})['value']
  File "/home/nazariy/anaconda/envs/insta_fame/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/nazariy/anaconda/envs/insta_fame/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'scrollIntoView' of undefined
  (Session info: chrome=70.0.3538.67)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-36-generic x86_64)
```

**Comment by cormo1990** [comment]
INFO [2018-10-22 20:03:44] [user]  Ongoing Unfollow [1/1000]: now unfollowing 'b'xxx''...
ERROR [2018-10-22 20:04:54] [user]  Unfollow loop error:  Message: unknown error: Cannot read property 'scrollIntoView' of undefined
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.12.6 x86_64)


INFO [2018-10-22 20:04:54] [user]  --> Total people unfollowed : 0


Probably the same issue.
sometimes this is what happen to me during the unfollow session for the mode Unfollow "non followers".

@uluQulu @sionking could you help us please? thanks a bunch as always for the great work

**Comment by botpadawan** [comment]
same issue here

**Comment by aku6640** [comment]
Same here

**Comment by sunnygill** [comment]
same issue here

**Comment by escariao** [comment]
@uluQulu @converge Hi, friends. Is there a possibility that instagram has changed anything? I received this on one of the bots

`Unfollow loop error:  Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (82816abaad3930c3702cf23489f0506ba13b1529),platform=Linux 4.14.71-v7+ armv7l)`

**Comment by converge** [comment]
@escariao I dont think so, how do you reproduce the error ?

**Comment by escariao** [comment]
@converge Hi, JP... I do not even know what's going on. I have two normal ones, and only one is with this error. ;(
--edit
I got this now

Traceback (most recent call last):
  File "quickstart.py", line 63, in <module>
    session.follow_user_followers(['user1', 'user2'], amount=150, randomize=False, interact=True, sleep_delay=650)
  File "/home/.../instapy/instapy.py", line 2840, in follow_user_followers
    self.logfolder)
  File "/home/.../instapy/unfollow_util.py", line 885, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/home/.../instapy/unfollow_util.py", line 724, in get_users_through_dialog
    person_list = dialog_username_extractor(buttons)
  File "/home/.../instapy/unfollow_util.py", line 750, in dialog_username_extractor
    .find_elements_by_tag_name("a")[1].text)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.71-v7+ armv7l)

**Comment by escariao** [comment]
@converge The last one I showed you, it happens during processing. There are a sequence of errors. I even saw it happen (also happens) when deleting browser cookies.

-edit: one of

 Error occurred while deleting cookies from web browser!
	b'Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=65.0.3325.181)\n  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.71-v7+ armv7l)\n'

**Comment by escariao** [comment]
@converge This issue persist: Error occurred while deleting cookies from web browser!
Why?

```
ERROR:my_login:Unfollow loop error:  Message: Retried 7 times to GET 'b'https://www.instagram.com/proftuliolages/'' webpage but failed out of a timeout!
	b'Message: timeout\n  (Session info: chrome=65.0.3325.181)\n  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.71-v7+ armv7l)\n'
```

```
ERROR [2018-11-30 17:49:04] [my_login]  Error occurred while deleting cookies from web browser!
	b'Message: timeout\n  (Session info: chrome=65.0.3325.181)\n  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.71-v7+ armv7l)\n'
Traceback (most recent call last):
  File "/home/pi/Projects/newinst/instapy/instapy.py", line 3797, in end
    self.browser.delete_all_cookies()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.71-v7+ armv7l)

ERROR:my_login:Error occurred while deleting cookies from web browser!
	b'Message: timeout\n  (Session info: chrome=65.0.3325.181)\n  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.71-v7+ armv7l)\n'
Traceback (most recent call last):
  File "/home/pi/Projects/newinst/instapy/instapy.py", line 3797, in end
    self.browser.delete_all_cookies()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.71-v7+ armv7l)
```

**Comment by Hassankashi** [comment]
same issue...
