### ISSUE TITLE
NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105ab1890>: Failed to establish a new connection: [Errno 61] Connection refused',))

### ISSUE THREAD

**Issue by facamx** [InstaPy/InstaPy#3205]
bash-3.2# python quicklast.py 

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-23 18:10:48] [xxxxx.yyyyy]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

........................................................................
INFO [2018-10-23 18:11:57] [xxxxx.yyyyy]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-10-23 18:12:02] [xxxxx.yyyyy]  Sessional Live Report:
	|> LIKED 0 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0
currently FOLLOWING 3424 users & has got 74849 FOLLOWERS

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-23 18:12:02] [xxxxx.yyyyy]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2018-10-23 18:12:02] [xxxxx.yyyyy]  Location [1/9]
INFO [2018-10-23 18:12:02] [xxxxx.yyyyy]  --> 255031356
Traceback (most recent call last):
  File "quicklast.py", line 31, in <module>
    session.like_by_locations(['255031356','237453756','386505608','1024801436','422599999','1021765577','822594479','640974136','1403303396361491'],amount=100, skip_top_posts=False)
  File "/InstaPy/instapy/instapy.py", line 1114, in like_by_locations
    skip_top_posts)
  File "/InstaPy/instapy/like_util.py", line 79, in get_links_for_location
    web_address_navigator(browser, location_link)
  File "/InstaPy/instapy/util.py", line 791, in web_address_navigator
    current_url = get_current_url(browser)
  File "/InstaPy/instapy/util.py", line 1235, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/Library/Python/2.7/site-packages/selenium-3.14.1-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium-3.14.1-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Python/2.7/site-packages/selenium-3.14.1-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 376, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Python/2.7/site-packages/selenium-3.14.1-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 399, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/Library/Python/2.7/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/Library/Python/2.7/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Library/Python/2.7/site-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Python/2.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=52455): Max retries exceeded with url: /session/e7c8959a5c45514eb654b7d534f636b1/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105ab1890>: Failed to establish a new connection: [Errno 61] Connection refused',))
bash-3.2#

**Comment by DNUSH** [comment]
Same error

**Comment by tE3m** [comment]
Me too

**Comment by AdamStone32** [comment]
Check your template and ensure you have correct spacing for each session call.  Generally I'll see that if i have improper indentation and it's trying to execute outside of the with smart_run(session) call.

**Comment by gitpatrickhub** [comment]
See solution in #3311 it worked for me, no longer receiving this error
