### ISSUE TITLE
Is anyone else getting this error?

### ISSUE THREAD

**Issue by leoch20** [InstaPy/InstaPy#3216]
I have been getting this error for a while. I even got the latest version of InstaPy and ran it with only a `session.follow_user_following(['user'], amount=3, randomize=False)` and I got this error. Has anyone seen it?

`File "D:\InstaPy-master\instapy\instapy.py", line 2648, in follow_user_following
    self.logfolder)
  File "D:\InstaPy-master\instapy\unfollow_util.py", line 1007, in get_given_user_following
    channel, jumps, logger, logfolder)
  File "D:\InstaPy-master\instapy\unfollow_util.py", line 727, in get_users_through_dialog
    person_list = dialog_username_extractor(buttons)
  File "D:\InstaPy-master\instapy\unfollow_util.py", line 750, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=70.0.3538.67)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)`

**Comment by tomeberle** [comment]
Having the same issue on Mac and RPI3.

```
Traceback (most recent call last):
  File "quickstart_scheduled.py", line 153, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 493, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 78, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 131, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 411, in run
    ret = self.job_func()
  File "quickstart_scheduled.py", line 88, in start_instaPy
    session.follow_user_followers(accs, amount=6, randomize=False)
  File "/home/pi/Documents/InstaPy/instapy/instapy.py", line 2490, in follow_user_followers
    self.logfolder)
  File "/home/pi/Documents/InstaPy/instapy/unfollow_util.py", line 913, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/home/pi/Documents/InstaPy/instapy/unfollow_util.py", line 720, in get_users_through_dialog
    person_list = dialog_username_extractor(buttons)
  File "/home/pi/Documents/InstaPy/instapy/unfollow_util.py", line 743, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "/usr/local/lib/python3.5/dist-packages/selenium-3.14.1-py3.5.egg/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium-3.14.1-py3.5.egg/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium-3.14.1-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium-3.14.1-py3.5.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.71-v7+ armv7l)
```

**Comment by trooperas** [comment]
yeah, me too!

**Comment by mastix** [comment]
My guess (when looking at the code) is:

When you scroll down, elements get detached from the DOM (IG is probably doing that for performance reasons). So when you try to access the elements that are stale (not attached to the DOM anymore), you'll get this error message.

@timgrossmann The fix should be to fetch the information while scrolling. Because the code scrolls down and when it reached the bottom, it tries to analyse the elements... and when they are stale, it will fail with the error message above.

Just tried it by removing this line (659 of unfollow_util.py):

scroll_to_bottom_of_followers_list(browser, dialog)

Now it works. (But I don't know which other errors will follow with this change)

**Comment by leoch20** [comment]
@mastix Thanks for the tip, it did work. hopefully it won't break much
