### ISSUE TITLE
The element reference of <a class="_fcn8k"> stale

### ISSUE THREAD

**Issue by cazaa** [InstaPy/InstaPy#322]
I'm trying to run the script on a Raspberry Pi 3 Model B. So far I've changed the webdriver from Chrome to Firefox in **instapy/instapy.py**:
`self.browser = webdriver.Firefox()`

My only modification in **quickstart.py** is this:
`InstaPy(username='XXX', password='YYY', nogui=True)\`

When executing the script I get the following error:
```
Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    InstaPy(username='XXX', password='YYY', nogui=True)\
  File "/home/pi/InstaPy/instapy/instapy.py", line 80, in login
    if not login_user(self.browser, self.username, self.password):
  File "/home/pi/InstaPy/instapy/login_util.py", line 20, in login_user
    action = ActionChains(browser).move_to_element(login_elem).click().perform()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/action_chains.py", line 77, in perform
    self.w3c_actions.perform()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <a class="_fcn8k"> stale: either the element is no longer attached to the DOM or the page has been refreshed
```
It looks like the script is unable to locate the login button: `<a class="_fcn8k">`. I've tried adding the following lines in **instapy/login_util.py** for low-level debugging:
```
html_source = browser.page_source
print html_source
```
This reveals that the DOM has been loaded and that it includes the _fcn8k class:
`<a class="_fcn8k" href="javascript:;">Log in</a>`

But for some reason the script can't locate the element. I really hope someone can help me solve this issue?

**Comment by timgrossmann** [comment]
@cazaa Did you try to first set it up with FireFox on your local machine to make sure there are no errors before moving onto the RasPi?
