### ISSUE TITLE
I can not execute it with any type of setup. It fails all the time. For 2 days.

### ISSUE THREAD

**Issue by facamx** [InstaPy/InstaPy#3225]
## Current Behavior
Traceback (most recent call last):
  File "quick2.py", line 61, in <module>
    session.like_by_tags(random.sample(like_tag_list, 3), amount=200, interact=True, skip_top_posts=True, use_smart_hashtags=False, randomize=True, media='Photo')
  File "/InstaPy/instapy/instapy.py", line 1495, in like_by_tags
    self.logger)
  File "/InstaPy/instapy/like_util.py", line 209, in get_links_for_tag
    web_address_navigator(browser, tag_link)
  File "/InstaPy/instapy/util.py", line 778, in web_address_navigator
    current_url = get_current_url(browser)
  File "/InstaPy/instapy/util.py", line 1222, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 433, in _request
    resp = self._conn.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 54] Connection reset by peer
bash-3.2#

**Comment by bbbutterfly** [comment]
Same here, but I think I've just found the issue.

Try updating chromedriver in assets folder, just download the latest version and delete the extension. I think we've updated chrome and it stopped working.

Please tell if it worked for you.
Thank you.

**Comment by facamx** [comment]
> Same here, but I think I've just found the issue.
> 
> Try updating chromedriver in assets folder, just download the latest version and delete the extension. I think we've updated chrome and it stopped working.
> 
> Please tell if it worked for you.
> Thank you.

I update chrome and chromedriver, Nothing has been solved.
