### ISSUE TITLE
please help !!! this script DON'T work any more !!!!!!! in any macos any hardware.... :(

### ISSUE THREAD

**Issue by facamx** [InstaPy/InstaPy#3233]
update chrome
download chromedriver
update macos
test in 3 mac's..... with virtualenv, without virtualenv, etc
test session by locations, by tags, unfollow, etc.....
test root and user

INFO [2018-10-26 15:40:14] [xxx.oficial]  Tag [1/3]
INFO:instapy.instapy:Tag [1/3]
INFO [2018-10-26 15:40:14] [xxx.oficial]  --> cortaderas
INFO:instapy.instapy:--> cortaderas
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a1cbe50>: Failed to establish a new connection: [Errno 61] Connection refused',)': /session/8292040df4763826a8a69032c179467a/execute
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a1f0110>: Failed to establish a new connection: [Errno 61] Connection refused',)': /session/8292040df4763826a8a69032c179467a/execute
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a1f0210>: Failed to establish a new connection: [Errno 61] Connection refused',)': /session/8292040df4763826a8a69032c179467a/execute
Traceback (most recent call last):
  File "/InstaPy/quick2.py", line 61, in <module>
    session.like_by_tags(random.sample(like_tag_list, 3), amount=300, interact=True, skip_top_posts=True, use_smart_hashtags=False, randomize=True, media='Photo')
  File "/InstaPy/instapy/instapy.py", line 1493, in like_by_tags
    self.logger)
  File "/InstaPy/instapy/like_util.py", line 209, in get_links_for_tag
    web_address_navigator(browser, tag_link)
  File "/InstaPy/instapy/util.py", line 791, in web_address_navigator
    current_url = get_current_url(browser)
  File "/InstaPy/instapy/util.py", line 1235, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/lala/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/lala/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/lala/venv/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 376, in execute
    return self._request(command_info[0], url, body=data)
  File "/lala/venv/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 399, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/lala/venv/lib/python2.7/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/lala/venv/lib/python2.7/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/lala/venv/lib/python2.7/site-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/lala/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/lala/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/lala/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/lala/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/lala/venv/lib/python2.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49684): Max retries exceeded with url: /session/8292040df4763826a8a69032c179467a/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a1f0310>: Failed to establish a new connection: [Errno 61] Connection refused',))
bash-3.2#

**Comment by andreescocard** [comment]
The script works, i am currently running in a raspberry pi 3
The new update bug some functions, the follow_user_followers for example
Looks like your environment, something here: 
`MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49684)`
Are you using proxy?

**Comment by Joyen12** [comment]
Hi guys,
Exact same problem for me...And I am not using a proxy
Were you able to fix it ?
Thanks a lot

**Comment by gitpatrickhub** [comment]
Same issue for me on Raspberry Pi 3 running Jessie, Firefox-ESR headless. I’m not using a proxy. Any ideas?

**Comment by gitpatrickhub** [comment]
See solution in #3311 it worked for me.
