### ISSUE TITLE
Session not created exception from tab crashed

### ISSUE THREAD

**Issue by TravisH84** [InstaPy/InstaPy#3237]
## Expected Behavior
Expected to work, did up to a week ago but now no luck :(

## Current Behavior
Appears to crash;

 File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: session not created exception
from tab crashed
  (Session info: headless chrome=69.0.3497.92)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.71-v7+ armv7l)

Traceback (most recent call last):
  File "like_home.py", line 41, in <module>
    multi_logs=True)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 229, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 349, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/Projects/InstaPy/assets/chromedriver

## InstaPy configuration
Headless browser, Chrome
session.like_by_feed(amount=20, randomize=True, unfollow=True, interact=True)

**Comment by sandeshghanta** [comment]
Hey @TravisH84 I have looked into this issue. Your error log says that your chromedriver is not there in the expected path. Can you please verify if the chromedriver is there in the location.

**Comment by TravisH84** [comment]
Hi @sandeshghanta, I double checked and chromedriver is there, I also reinstalled it just to make sure and get the same issue.  I don't think it is actually related to chromedriver because in the error log (above) it talks about from tag crashed

**Comment by converge** [comment]
No activity for a long time. pls, reopen it if you need.
