### ISSUE TITLE
OSError=[Errno 2] No such file or directory: 'Xvfb'

### ISSUE THREAD

**Issue by JithinAntony4** [InstaPy/InstaPy#3247]
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
Oct 28 15:29:35 pythongram gunicorn[1560]: OSError=[Errno 2] No such file or directory: 'Xvfb'
Oct 28 15:29:35 pythongram gunicorn[1560]: Program install error!
Oct 28 15:29:35 pythongram gunicorn[1560]: You can install it in terminal:
Oct 28 15:29:35 pythongram gunicorn[1560]: sudo apt-get install xvfb

BUT this code work when run using gunicorn

**Comment by akogay** [comment]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/easyprocess/__init__.py", line 225, in start
    env=self.env,
  File "/opt/conda/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb': 'Xvfb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/easyprocess/__init__.py", line 178, in check_installed
    self.call()
  File "/opt/conda/lib/python3.7/site-packages/easyprocess/__init__.py", line 194, in call
    self.start().wait(timeout=timeout)
  File "/opt/conda/lib/python3.7/site-packages/easyprocess/__init__.py", line 230, in start
    raise EasyProcessError(self, 'start error')
easyprocess.EasyProcessError: start error <EasyProcess cmd_param=['Xvfb', '-help'] cmd=['Xvfb', '-help'] oserror=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb' return_code=None stdout="None" stderr="None" timeout_happened=False>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "InstaPy/quickstart.py", line 16, in <module>
    nogui=True#, headless_browser=False
  File "/home/calve/InstaPy/instapy/instapy.py", line 97, in __init__
    self.display = Display(visible=0, size=(800, 600))
  File "/opt/conda/lib/python3.7/site-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/opt/conda/lib/python3.7/site-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/opt/conda/lib/python3.7/site-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/opt/conda/lib/python3.7/site-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb'
Program install error!

**Comment by converge** [comment]
hey guys, you can use headless mode, there is more info about it on the docs.

**Comment by converge** [comment]
No activity for a long time. pls, reopen it if you need.
