### ISSUE TITLE
 element is not attached to the page document , session.follow_user_followers

### ISSUE THREAD

**Issue by Mehran** [InstaPy/InstaPy#3251]
## Current Behavior
```
Traceback (most recent call last):
  File "new2-follow.py", line 47, in follow
    session.follow_user_followers(['donya', 'arat.gym'], amount=5, randomize=False)
  File "/home/it/new-Instapy/InstaPy/instapy/instapy.py", line 2493, in follow_user_followers
    self.logfolder)
  File "/home/it/new-Instapy/InstaPy/instapy/unfollow_util.py", line 881, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/home/it/new-Instapy/InstaPy/instapy/unfollow_util.py", line 720, in get_users_through_dialog
    person_list = dialog_username_extractor(buttons)
  File "/home/it/new-Instapy/InstaPy/instapy/unfollow_util.py", line 743, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 68, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.9.0-6-amd64 x86_64)
```
## Possible Solution (optional)
seems XPath need update . @uluQulu 
## InstaPy configuration
`session.follow_user_followers(['user1', 'user2'], amount=5, randomize=False)`

**Comment by uluQulu** [comment]
Hi @Mehran 
I have included its fix- e692436 at #3226 which is now merged.
Just pull master to get it.

---

Cheer 😁
---

**Comment by AntoliniMatteo** [comment]
Thank you so much!! @uluQulu

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
