### ISSUE TITLE
After GIT PULL does not work

### ISSUE THREAD

**Issue by kristofenyi** [InstaPy/InstaPy#3258]
Script was running just fine for months. After git pull is now unable to start

I tried to run the quickstart.py

Any suggestions?

## Current Behavior
~/InstaPy# python quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 24, in <module>
    from .comment_util import comment_image
  File "/root/InstaPy/instapy/comment_util.py", line 7, in <module>
    from .util import update_activity
  File "/root/InstaPy/instapy/util.py", line 25, in <module>
    from .quota_supervisor import quota_supervisor
  File "/root/InstaPy/instapy/quota_supervisor.py", line 7, in <module>
    from plyer import notification
ImportError: No module named plyer

**Comment by timgrossmann** [comment]
@3p1demicz What makes you think that this is due to the git pull.

Please use the search function for the issues.

Half of the issues state this same `no module named ...` error.
It's always the same solution.
`pip install <your_module>` where `<your_module>` has to be replaced with the name of the missing module. 
In your case this would be `pip install plyer`

**Comment by kristofenyi** [comment]
Thanks a lot!

❤️ I really appreciate your work
S pozdravem,

Krištof Kelecsényi
