### ISSUE TITLE
Proxy error with lates chromedriver

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3259]
Hi, tried the latest chromedriver. Gets this error when using proxy.
@uluQulu @sionking

ERROR [2018-10-29 13:37:29] [xx]  Message: invalid argument: cannot parse capability: proxy
from invalid argument: Specifying 'socksProxy' requires an integer for 'socksVersion'
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-36-generic x86_64)
Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 351, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: cannot parse capability: proxy
from invalid argument: Specifying 'socksProxy' requires an integer for 'socksVersion'
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-36-generic x86_64)

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 351, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: cannot parse capability: proxy
from invalid argument: Specifying 'socksProxy' requires an integer for 'socksVersion'
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-36-generic x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "5bd5c2e1fbd65b00137cabb7.py", line 16, in <module>
    session = InstaPy(username=insta_username, password=insta_password, headless_browser=True, nogui=True, disable_image_load=True, multi_logs=True, proxy_address=proxy, proxy_port=port)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 230, in __init__
    self.set_selenium_local_session()
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 355, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/fredrik/InstaPy/assets/chromedriver

**Comment by sionking** [comment]
The changed the way proxy is inputs. use 2.42 until someone will figure this out lol

**Comment by fgisslen** [comment]
@sionking Yeah :)

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.

**Comment by khansaad1275** [comment]
can anyone please tell me how can i change chrome driver version?

**Comment by eracle** [comment]
@khansaad1275 you have to download the right version an put it on the assets folder. Checkout your workspace configuration.

@converge This thing seems to be still broken, shall we purge the usage of proxy username/passwords, taking into account that the new release has the create_proxy_extension functionality?

**Comment by converge** [comment]
this is a good starting point @eracle https://github.com/timgrossmann/InstaPy/pull/4256

**Comment by eracle** [comment]
Thanks, I included a comment on #4256
