### ISSUE TITLE
Cant start -> ModuleNotFoundError: No module named 'plyer'

### ISSUE THREAD

**Issue by xerZV** [InstaPy/InstaPy#3266]
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "D:\social\InstaPy-master\InstaPy-master\InstaPy-master\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "D:\social\InstaPy-master\InstaPy-master\InstaPy-master\instapy\instapy.py", line 24, in <module>
    from .comment_util import comment_image
  File "D:\social\InstaPy-master\InstaPy-master\InstaPy-master\instapy\comment_util.py", line 7, in <module>
    from .util import update_activity
  File "D:\social\InstaPy-master\InstaPy-master\InstaPy-master\instapy\util.py", line 25, in <module>
    from .quota_supervisor import quota_supervisor
  File "D:\social\InstaPy-master\InstaPy-master\InstaPy-master\instapy\quota_supervisor.py", line 7, in <module>
    from plyer import notification
ModuleNotFoundError: No module named 'plyer'

**Comment by fabian-pandas** [comment]
Hi there =)

try:
`sudo pip install plyer`

cheers!

**Comment by nRsWork** [comment]
Windows?

**Comment by xerZV** [comment]
> Hi there =)
> 
> try:
> `sudo pip install plyer`
> 
> cheers!

Thank you, but can you tell me how can I run it on Windows?

**Comment by giulianoporro** [comment]
I have same error, i used "sudo pip install plyer"
but nothing change...

**Comment by converge** [comment]
@giulianoporro ```pip3 install plyer``` , did it fix the issue ?

**Comment by giulianoporro** [comment]
Yes, it works. now is working properly.

Il giorno lun 5 nov 2018 alle ore 19:59 João Paulo Vanzuita <
notifications@github.com> ha scritto:

**Comment by xerZV** [comment]
Its not closed.. wtf... i asked help for windows?

**Comment by converge** [comment]
@nRsWork https://www.google.com/search?client=firefox-b-ab&q=pip+windows 😄
