### ISSUE TITLE
Cant Follow commenters 

### ISSUE THREAD

**Issue by LordAch** [InstaPy/InstaPy#3267]
same thing that happened with login before i update the script ,

 log : 
Traceback (most recent call last):
  File "quickstart.py", line 34, in <module>
    session.follow_commenters(['imachref'], amount=100, daysold=365, max_pic = 1
00, sleep_delay=600, interact=False)
  File "C:\Users\ash\Desktop\New folder\InstaPy-master\instapy\instapy.py", line
 749, in follow_commenters
    commenters = extract_information(self.browser, username, daysold, max_pic)
  File "C:\Users\ash\Desktop\New folder\InstaPy-master\instapy\commenters_util.p
y", line 217, in extract_information
    user_commented_list, pic_date_time = extract_post_info(browser)
  File "C:\Users\ash\Desktop\New folder\InstaPy-master\instapy\commenters_util.p
y", line 54, in extract_post_info
    click_element(browser, load_more_comments_element)
  File "C:\Users\ash\Desktop\New folder\InstaPy-master\instapy\util.py", line 67
5, in click_element
    click_element(browser, element, tryNum)
  File "C:\Users\ash\Desktop\New folder\InstaPy-master\instapy\util.py", line 67
5, in click_element
    click_element(browser, element, tryNum)
  File "C:\Users\ash\Desktop\New folder\InstaPy-master\instapy\util.py", line 67
5, in click_element
    click_element(browser, element, tryNum)
  File "C:\Users\ash\Desktop\New folder\InstaPy-master\instapy\util.py", line 66
0, in click_element
    "document.getElementsByClassName('" + element.get_attribute("class") + "')[0
].click()")
  File "C:\Users\ash\Anaconda2\lib\site-packages\selenium-2.53.6-py2.7.egg\selen
ium\webdriver\remote\webelement.py", line 111, in get_attribute
    resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
  File "C:\Users\ash\Anaconda2\lib\site-packages\selenium-2.53.6-py2.7.egg\selen
ium\webdriver\remote\webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\ash\Anaconda2\lib\site-packages\selenium-2.53.6-py2.7.egg\selen
ium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ash\Anaconda2\lib\site-packages\selenium-2.53.6-py2.7.egg\selen
ium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale elemen
t reference: element is not attached to the page document
  (Session info: chrome=70.0.3538.77)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d287
4a),platform=Windows NT 6.1.7600 SP3 x86)

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
