### ISSUE TITLE
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by dtypo** [InstaPy/InstaPy#3273]
Hello to everyone :)
Yesterday I've used the follow commenters function of Instapy.
At the beginning the script does its job quite well, but after half an hour working, It suddenly stops with this error.
I've already used it in past, but with only the "like" fuction.
I've even tried to redownload the updated master (the usual git clone), but the error keep bothering.
Someone can help me with this? :)
Thanks in advance.

## Current Behavior

Traceback (most recent call last):
  File "quickstart.py", line 42, in <module>
    session.follow_commenters(['UserX', 'UserY', 'UserZ'], amount=112, daysold=365, max_pic = 97, sleep_delay=300, interact=True)
  File "C:\Users\MyUser\Desktop\BOT\InstaPy\instapy\instapy.py", line 749, in follow_commenters
    commenters = extract_information(self.browser, username, daysold, max_pic)
  File "C:\Users\MyUser\Desktop\BOT\InstaPy\instapy\commenters_util.py", line 217, in extract_information
    user_commented_list, pic_date_time = extract_post_info(browser)
  File "C:\Users\MyUser\Desktop\BOT\InstaPy\instapy\commenters_util.py", line 54, in extract_post_info
    click_element(browser, load_more_comments_element)
  File "C:\Users\MyUser\Desktop\BOT\InstaPy\instapy\util.py", line 675, in click_element
    click_element(browser, element, tryNum)
  File "C:\Users\MyUser\Desktop\BOT\InstaPy\instapy\util.py", line 675, in click_element
    click_element(browser, element, tryNum)
  File "C:\Users\MyUser\Desktop\BOT\InstaPy\instapy\util.py", line 675, in click_element
    click_element(browser, element, tryNum)
  File "C:\Users\MyUser\Desktop\BOT\InstaPy\instapy\util.py", line 660, in click_element
    "document.getElementsByClassName('" + element.get_attribute("class") + "')[0].click()")
  File "C:\Programmi\Python2.7\lib\site-packages\selenium\webdriver\remote\webelement.py", line 143, in get_attribute
    resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
  File "C:\Programmi\Python2.7\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Programmi\Python2.7\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Programmi\Python2.7\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=70.0.3538.77)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)

## InstaPy configuration

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=12000,
                                        min_followers=45,
                                        min_following=77)
    # activity
    session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
    session.set_do_like(True, percentage=70)
    session.follow_commenters(['UserX', 'UserY', 'UserZ'], amount=112, daysold=365, max_pic = 97, sleep_delay=300, interact=True)

**Comment by kiankji** [comment]
+1
In my logs i get additional this error:
Timed out with failure while explicitly waiting until title contains 'Login' string!

**Comment by snakelab** [comment]
+1 got the same error

**Comment by wrhsescp** [comment]
same issue here

**Comment by fabian-pandas** [comment]
same issue here +1

**Comment by karltaylor** [comment]
+1

**Comment by coreyriviello** [comment]
+1

**Comment by gh-cobaia** [comment]
Having the same problem here... Any solution?

**Comment by lovrom23** [comment]
Getting the exact same error, @uluQulu @timgrossmann @sionking - you might look into this as it is common.

**Comment by AdamMoffitt** [comment]
same issue
