### ISSUE TITLE
NOT RUNNING AT ALL - Failed to establish a new connection: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by thorseshoe** [InstaPy/InstaPy#3281]
It won't run at all and only survives til the page after it logs in. It's been this way for weeks. Everything is up to date as far as I know.

File "/Library/Python/2.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=64620): Max retries exceeded with url: /session/063c2ecfad1b6b2eedc8f0219c0f677d/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104814450>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by CharlesCCC** [comment]
more detail need, make sure you post your configuration and also do a `git fetch/pull` on your locally.

**Comment by Joyen12** [comment]
Same for me, please help.
I am on macOS, it works the day before yesterday and then always getting this error, tried to reinstall and many things but nothing to do.

I really don't know how to solve this...Is there some experienced programmer to help ?

Thanks a lot

**Comment by Joyen12** [comment]
I am on Mac OS X, I don't use any proxy.
Here is the exact error :

WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ecc9550>: Failed to establish a new connection: [Errno 61] Connection refused',)': /session/f660e8800687363311f1e535cf43aee9/execute
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ecc9810>: Failed to establish a new connection: [Errno 61] Connection refused',)': /session/f660e8800687363311f1e535cf43aee9/execute
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ecc98d0>: Failed to establish a new connection: [Errno 61] Connection refused',)': /session/f660e8800687363311f1e535cf43aee9/execute
Traceback (most recent call last):
  File "instapy-quikstart.py", line 58, in <module>
    session.like_by_tags(["mbappe"], amount=20)
  File "/Users/Joyen/insta/lib/python2.7/site-packages/instapy/instapy.py", line 1594, in like_by_tags
    self.logger)
  File "/Users/Joyen/insta/lib/python2.7/site-packages/instapy/like_util.py", line 210, in get_links_for_tag
    web_address_navigator(browser, tag_link)
  File "/Users/Joyen/insta/lib/python2.7/site-packages/instapy/util.py", line 812, in web_address_navigator
    current_url = get_current_url(browser)
  File "/Users/Joyen/insta/lib/python2.7/site-packages/instapy/util.py", line 1256, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/Users/Joyen/insta/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/Users/Joyen/insta/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/Joyen/insta/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/Joyen/insta/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/Users/Joyen/insta/lib/python2.7/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/Users/Joyen/insta/lib/python2.7/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/Joyen/insta/lib/python2.7/site-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/Joyen/insta/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/Users/Joyen/insta/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/Users/Joyen/insta/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/Users/Joyen/insta/lib/python2.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/Joyen/insta/lib/python2.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=56348): Max retries exceeded with url: /session/f660e8800687363311f1e535cf43aee9/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ecc99d0>: Failed to establish a new connection: [Errno 61] Connection refused',))

@timgrossmann  @uluQulu @CharlesCCC @sionking Maybe one of you might know the issue ?

Thanks a lot for your help

**Comment by gitpatrickhub** [comment]
See solution in #3311 it resolved this issue for me.
