### ISSUE TITLE
NOT RUNNING AT ALL

### ISSUE THREAD

**Issue by PythonFrank** [InstaPy/InstaPy#3285]
Traceback (most recent call last):
  File "instapy.py", line 17, in <module>
    from pyvirtualdisplay import Display
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pyvirtualdisplay-0.2.1-py3.6.egg\pyvirtualdisplay\__init__.py", line 3, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pyvirtualdisplay-0.2.1-py3.6.egg\pyvirtualdisplay\display.py", line 1, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pyvirtualdisplay-0.2.1-py3.6.egg\pyvirtualdisplay\abstractdisplay.py", line 1, in <module>
ModuleNotFoundError: No module named 'easyprocess'

Any ideas ?

**Comment by timgrossmann** [comment]
#2871
