### ISSUE TITLE
Crash using 'interact_user_followers' for liking pictures after awhile

### ISSUE THREAD

**Issue by jtrieuDev** [InstaPy/InstaPy#3288]
Hi everyone, I have some troubles using the function **interact_user_followers** in order to like someone's else followers's pictures:
The script is running well but at one moment it crashes:
(It used to work well)
```
INFO [2018-11-04 13:50:58] [username]  User 'petitebobo' [325/858]
INFO [2018-11-04 13:51:03] [username]  Interaction [200/858]  |  Total Interaction: 200
INFO [2018-11-04 13:51:03] [username]  Username [1/1]
INFO [2018-11-04 13:51:03] [username]  --> petitebobo
INFO [2018-11-04 13:51:03] [username]  username actions: following=False commenting=False liking=True
INFO [2018-11-04 13:51:03] [username]  Getting petitebobo image list...
INFO [2018-11-04 13:51:05] [username]  Post [1/3]
INFO [2018-11-04 13:51:05] [username]  https://www.instagram.com/p/BnqKphQgpcC/
INFO [2018-11-04 13:51:09] [username]  Image from: petitebobo
INFO [2018-11-04 13:51:09] [username]  Link: https://www.instagram.com/p/BnqKphQgpcC/
INFO [2018-11-04 13:51:09] [username]  Description: Carte blanche créative#moussedelégumesconcombreoeufsdetobiko#oeufparfaitnouxdecajoucocodepaimpolcressecrèmedecourge#cabillaudgeléedepommefenouilcrèmedaubergine#bavettedeveauaucarameldesojapuréedecarottesésamepuréepimentsojahuiledesésame#jeunecantalmarmeladeauyuzu#sorbetfraisechantillybasilicfraisescrumbleàlhuiledolive#marsannayrouge#cuisine#gastronomie#bistronomie#table#saveurs#pierresanginoberkampf
INFO [2018-11-04 13:51:16] [username]  --> Image Liked!
INFO [2018-11-04 13:51:19] [username]  --> Not commented
INFO [2018-11-04 13:51:20] [username]  Post [2/3]
INFO [2018-11-04 13:51:20] [username]  https://www.instagram.com/p/BnDi37VgVuB/
INFO [2018-11-04 13:51:23] [username]  Image from: petitebobo
INFO [2018-11-04 13:51:23] [username]  Link: https://www.instagram.com/p/BnDi37VgVuB/
INFO [2018-11-04 13:51:23] [username]  Description: Chambre avec vue...#VillaExtramuros#chambre5#terrealentejane#Arraiolos#château#oliveraie#sunrise#sunset#maisondhôtes#boutiquehotel#maisondarchitecte#interiordesign#homedesign#@villaextramuros#@voyageursdumonde
INFO [2018-11-04 13:51:31] [username]  --> Image Liked!
INFO [2018-11-04 13:51:33] [username]  --> Not commented
INFO [2018-11-04 13:51:34] [username]  Post [3/3]
INFO [2018-11-04 13:51:34] [username]  https://www.instagram.com/p/Bo5UPGOgt9p/
INFO [2018-11-04 13:51:37] [username]  Image from: petitebobo
INFO [2018-11-04 13:51:37] [username]  Link: https://www.instagram.com/p/Bo5UPGOgt9p/
INFO [2018-11-04 13:51:37] [username]  Description: Divinement divin...# @agapeparis #étoilemichelin#yoshitakatakayanagi#gastronomie#accordmetsetvins#artdelatable#tartaredethonverveinecitronnée#tomatesdepleinchampsburratadespouillesananasetagastache#cuissesdegrenouillecourgettesjaunesetailnoirjapinais#lieujaunedéclinaisonautourdelartichautcondimentolivenoireparmiggiano#pavlovafruitsexotiquesgingembrecitronvertcrèmeglacéebanane#saumurblancdeloire#blancdulanguedoc#rieslingmillésimépierredietrich#hydromiel#tousaurestaurant#letabling
INFO [2018-11-04 13:51:38] [username]  Sessional Live Report:
	|> LIKED 485 images  |  ALREADY LIKED: 33
	|> COMMENTED on 0 images
	|> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> INAPPROPRIATE images: 3
	|> NOT VALID users: 0

Traceback (most recent call last):
  File "quickstart.py", line 47, in <module>
    session.interact_user_followers(['username'], amount=1000, randomize=False)
  File "/Desktop/instagram/InstaPy/instapy/instapy.py", line 2613, in interact_user_followers
    self.user_interact_media)
  File "/Desktop/instagram/InstaPy/instapy/instapy.py", line 2152, in interact_by_users
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 79: ordinal not in range(128)
```

The code I am using:
```
    session.login()

    # settings
    session.set_relationship_bounds(enabled=False,
				 potency_ratio=-1.21,
				  delimit_by_numbers=False,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    session.set_simulation(enabled=False)
    session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
    session.set_dont_include(['user3', 'user2', 'username1', 'test'])
    session.set_do_like(enabled=True, percentage=90)
    session.interact_user_followers(['username'], amount=1000, randomize=False)
```

**Comment by lbenassi** [comment]
Why do you use the setting: `session.set_simulation(enabled=False)`?
What advantage do you have in using this setting?

**Comment by KingKorSin** [comment]
Ran into the same problem a few times, not sure why it happens or how to fix it sadly. Subscribing for updates.

**Comment by kushpvo** [comment]
Subscribing
