### ISSUE TITLE
[WINDOWS] Cant start -> ModuleNotFoundError: No module named 'plyer'

### ISSUE THREAD

**Issue by xerZV** [InstaPy/InstaPy#3301]
WINDOWS PROBLEM

Traceback (most recent call last):
File "quickstart.py", line 3, in 
from instapy import InstaPy
File "D:\social\InstaPy-master\InstaPy-master\InstaPy-master\instapy_init_.py", line 2, in 
from .instapy import InstaPy
File "D:\social\InstaPy-master\InstaPy-master\InstaPy-master\instapy\instapy.py", line 24, in 
from .comment_util import comment_image
File "D:\social\InstaPy-master\InstaPy-master\InstaPy-master\instapy\comment_util.py", line 7, in 
from .util import update_activity
File "D:\social\InstaPy-master\InstaPy-master\InstaPy-master\instapy\util.py", line 25, in 
from .quota_supervisor import quota_supervisor
File "D:\social\InstaPy-master\InstaPy-master\InstaPy-master\instapy\quota_supervisor.py", line 7, in 
from plyer import notification
ModuleNotFoundError: No module named 'plyer'

the solution for linux is pip3 install plyer, but how about windows?

**Comment by ugurozturk** [comment]
@nRsWork its not WINDOWS PROBLEM
it is just a simply thing on python developing.

read here well.
https://github.com/timgrossmann/InstaPy/issues/3266#issuecomment-435993456

if you still dont understand how to do that then.
Just google it like
"How to python module install"

Your error is : **ModuleNotFoundError: No module named 'plyer'**

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)
