### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by krcha** [InstaPy/InstaPy#3305]
Hey guys I get this error after I have updated InstaPy, is it error because some configuration changed or I need to reconfigure something?

It worked before new pull

Also I have updated chromedriver in hope that will resolve problem but without any luck

## InstaPy configuration
```

""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run



# login credentials
insta_username = 'igaccount'
insta_password = 'password'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)


with smart_run(session):
    """ Activity flow """
    # settings
    session.set_skip_users(skip_private=False, skip_no_profile_pic=True)
    #min_media=10
    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=154590,
                                        min_followers=90,
                                        min_following=100)
    
session.unfollow_users(amount=100, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
session.set_user_interact(amount=2, percentage=75, randomize=True, media='Photo')
session.follow_user_followers(['user1', 'user2'], amount=20, randomize=False)
session.set_user_interact(amount=2, percentage=70, randomize=True, media='Photo')
session.follow_likers (['user1', 'user2''], photos_grab_amount = 2, times=1, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=False)
session.follow_likers (['user1', 'user2'], photos_grab_amount = 2, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=False)
session.like_by_locations(['123456780', '123456790', '123456789'], amount=10, skip_top_posts=False)
#session.follow_likers (['user1'], photos_grab_amount = 2, follow_likers_per_photo = 30, randomize=True, sleep_delay=600, interact=False)
session.like_by_feed(amount=100, randomize=True, unfollow=True, interact=True)

````

## CMD log

```
_______________________________________________________________________________________
INFO [2018-11-06 17:21:41] [instagram_account]  Starting to follow user `Followers`..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-11-06 17:21:41] [instagram_account]  User 'drustvena_dinamika' [1/24]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 171, in _new_conn

    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 79, in create_connection
    raise err
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 196, in connect
    conn = self._new_conn()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 180, in _new_conn

    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001D4EABC7DA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 32, in <module>
    session.follow_user_followers(['user1', 'user2'], amount=20, randomize=False)
  File "C:\Users\user\Documents\GitHub\InstaPy\instapy\instapy.py", line 2840, in follow_user_followers
    self.logfolder)
  File "C:\Users\user\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 851, in get_given_user_followers
    web_address_navigator(browser, user_link)
  File "C:\Users\user\Documents\GitHub\InstaPy\instapy\util.py", line 803, in web_address_navigator
    current_url = get_current_url(browser)
  File "C:\Users\user\Documents\GitHub\InstaPy\instapy\util.py", line 1247, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 376, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 399, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\request.py", line 72, in request
    **urlopen_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\poolmanager.py", line 322, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=50969): Max retries exceeded with url: /session/74dc5fc8c04ef87270b385241ee329c2/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D4EABC7DA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
```

**Comment by AdamStone32** [comment]
> > 
> with smart_run(session):
>     """ Activity flow """
>     # settings
>     session.set_skip_users(skip_private=False, skip_no_profile_pic=True)
>     #min_media=10
>     session.set_relationship_bounds(enabled=True,
>                                       delimit_by_numbers=True,
>                                        max_followers=154590,
>                                         min_followers=90,
>                                         min_following=100)
>     
> session.unfollow_users(amount=100, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
> session.set_user_interact(amount=2, percentage=75, randomize=True, media='Photo')
> session.follow_user_followers(['user1', 'user2'], amount=20, randomize=False)
> session.set_user_interact(amount=2, percentage=70, randomize=True, media='Photo')
> session.follow_likers (['user1', 'user2''], photos_grab_amount = 2, times=1, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=False)
> session.follow_likers (['user1', 'user2'], photos_grab_amount = 2, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=False)
> session.like_by_locations(['123456780', '123456790', '123456789'], amount=10, skip_top_posts=False)
> #session.follow_likers (['user1'], photos_grab_amount = 2, follow_likers_per_photo = 30, randomize=True, sleep_delay=600, interact=False)
> session.like_by_feed(amount=100, randomize=True, unfollow=True, interact=True)

> 
Your second set of session calls are out of the indentation of your with smart_run(session) call.
basically...make sure your sessions are all lined up top to bottom. (same spaces on each row) You are making the call to execute a session outside the session call.

**Comment by gitpatrickhub** [comment]
See solution in #3311 it worked for me, no longer receiving this error
