### ISSUE TITLE
Potential Chomedriver/Selenium Issue?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#3310]
## Expected Behavior

For the script to work until it is finished.

## Current Behavior

It usually crashes about 35-40 followers in.

## InstaPy configuration

InstaPy is configured the way it came. I'm using the quickstart script and one other template script that I modified. Have tried other scripts that I haven't modified and basically the same things are happening. Here is the error log.

Traceback (most recent call last):
  File "quickstart.py", line 19, in <module>
    session.follow_user_followers(['mens_cult', 'menslaw', 'mensrealm'], amount=3000, sleep_delay=175, randomize=True, interact=True)
  File "/home/evan/InstaPy/instapy/instapy.py", line 2840, in follow_user_followers
    self.logfolder)
  File "/home/evan/InstaPy/instapy/unfollow_util.py", line 885, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/home/evan/InstaPy/instapy/unfollow_util.py", line 674, in get_users_through_dialog
    buttons = get_buttons_from_dialog(dialog, channel)
  File "/home/evan/InstaPy/instapy/unfollow_util.py", line 1208, in get_buttons_from_dialog
    "//button[text()='Follow']")
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/webelement.py", line 381, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/webelement.py", line 685, in find_elements
    {"using": by, "value": value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=70.0.3538.77)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-29-generic x86_64)

**Comment by converge** [comment]
how is the output using python3 ?

**Comment by arshiyasolei** [comment]
@converge I am about to make a pull request for this

**Comment by arshiyasolei** [comment]
I made some manual changes a while ago

**Comment by ghost** [comment]
@converge So the following is using python3. Gets to 21 followers then crashes, including the web page it was using.

Traceback (most recent call last):
  File "quickstart.py", line 19, in <module>
    session.follow_user_followers(['carpenterwatches', 'artworth_brothers', 'ryans_watches'], amount=3000, sleep_delay=175, randomize=True, interact=True)
  File "/home/evan/InstaPy/instapy/instapy.py", line 2840, in follow_user_followers
    self.logfolder)
  File "/home/evan/InstaPy/instapy/unfollow_util.py", line 885, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/home/evan/InstaPy/instapy/unfollow_util.py", line 670, in get_users_through_dialog
    scroll_bottom(browser, dialog, 2)
  File "/home/evan/InstaPy/instapy/util.py", line 605, in scroll_bottom
    "arguments[0].scrollTop = arguments[0].scrollHeight", element)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=70.0.3538.77)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-29-generic x86_64)

**Comment by ghost** [comment]
@arshiyasoleimani Still having issues, were you able to find a solution? Can't seem to figure out where I'm going wrong.
