### ISSUE TITLE
Can't work

### ISSUE THREAD

**Issue by AntoineIN** [InstaPy/InstaPy#3314]
Hello, just update the bot with the new files. The bot didn't work since 7 days.

After the today update, i got this message :

Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 25, in <module>
    from .comment_util import comment_image
  File "/root/InstaPy/instapy/comment_util.py", line 7, in <module>
    from .util import update_activity
  File "/root/InstaPy/instapy/util.py", line 25, in <module>
    from .quota_supervisor import quota_supervisor
  File "/root/InstaPy/instapy/quota_supervisor.py", line 7, in <module>
    from plyer import notification
ModuleNotFoundError: No module named 'plyer'

Anyone got an answer ? didn't find in the issues...

Thanks

**Comment by alxhoff** [comment]
You're missing the python package plyer. You should try googling you're issues first.

Google "plyer pip install" to solve your problem 😉

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)
