### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Mrezagolbaba** [InstaPy/InstaPy#3323]
Traceback (most recent call last):
  File "quickstart.py", line 36, in <module>
    session.like_by_tags(random.sample(like_tag_list, 3), amount=random.randint(50, 100), interact=True)
  File "/Users/mohamadreza/WorkSpace/InstaPy/instapy/instapy.py", line 1625, in like_by_tags
    validation, details = self.validate_user_call(user_name)
  File "/Users/mohamadreza/WorkSpace/InstaPy/instapy/instapy.py", line 1110, in validate_user_call
    self.logger)
  File "/Users/mohamadreza/WorkSpace/InstaPy/instapy/util.py", line 134, in validate_username
    with open("{}blacklist.csv".format(logfolder), 'rt') as f:
IOError: [Errno 2] No such file or directory: '/Users/mohamadreza/WorkSpace/InstaPy/logs/top_aroosi/blacklist.csv'

**Comment by alekseitsvetkov** [comment]
I created the file manually, it works now

**Comment by raphson93** [comment]
@alekseytsvetkov just create an empty file will do? I created but it failed to decode

**Comment by danialmoghaddam** [comment]
I temporarily fixed it by running `> /InstaPy/logs/username/blacklist.csv`
