### ISSUE TITLE
Mac High Sierra OSX Chromedriver error

### ISSUE THREAD

**Issue by andrewsteinmeyer** [InstaPy/InstaPy#3326]
I am getting the following error on Mac OSX.  I downloaded the 2.43 chromedriver for Mac and copied it in the /assets folder.  I did chmod +x chromedriver and chmod 755 chromedriver.

I am still getting the error that chromedriver is not found???  Help please!

andrewsteinmeyernew@Andrews-MacBook-Pro InstaPy (master) $ python3 quickstart.py 
ERROR [2018-11-08 16:06:58] [andrewsteinmeyer]  Message: Can not connect to the Service /Users/andrewsteinmeyernew/dev/InstaPy/assets/chromedriver
Traceback (most recent call last):
  File "/Users/andrewsteinmeyernew/dev/InstaPy/instapy/instapy.py", line 357, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 104, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /Users/andrewsteinmeyernew/dev/InstaPy/assets/chromedriver

ERROR:andrewsteinmeyer:Message: Can not connect to the Service /Users/andrewsteinmeyernew/dev/InstaPy/assets/chromedriver
Traceback (most recent call last):
  File "/Users/andrewsteinmeyernew/dev/InstaPy/instapy/instapy.py", line 357, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 104, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /Users/andrewsteinmeyernew/dev/InstaPy/assets/chromedriver

Traceback (most recent call last):
  File "/Users/andrewsteinmeyernew/dev/InstaPy/instapy/instapy.py", line 357, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 104, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /Users/andrewsteinmeyernew/dev/InstaPy/assets/chromedriver

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    headless_browser=False)
  File "/Users/andrewsteinmeyernew/dev/InstaPy/instapy/instapy.py", line 232, in __init__
    self.set_selenium_local_session()
  File "/Users/andrewsteinmeyernew/dev/InstaPy/instapy/instapy.py", line 361, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /Users/andrewsteinmeyernew/dev/InstaPy/assets/chromedriver

**Comment by converge** [comment]
No activity for a long time. pls, reopen it if you need.
