### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined

### ISSUE THREAD

**Issue by FBosler** [InstaPy/InstaPy#333]
Had the script crash for two nights in a row now with the following error

```
Traceback (most recent call last):
  File ".../Instalike.py", line 15, in <module>
    .like_by_tags(['thegoodlife'], amount=200, media='Photo')\
  File ".../instapy.py", line 383, in like_by_tags
    self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)
  File ".../like_util.py", line 170, in check_link
    post_page = browser.execute_script("return window._sharedData.entry_data.PostPage")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
```

Any idea what this means?

**Comment by timgrossmann** [comment]
@FBosler You really have weird errors 🤔 
Did you follow the How_to_Ubuntu in the docs folder?

Did you try to create a new droplet and start from scratch?

**Comment by FBosler** [comment]
Actually I think you can close this one down (this error happend before I switched over to server).
