### ISSUE TITLE
Switch language and login with Firefox

### ISSUE THREAD

**Issue by thejeromelouis** [InstaPy/InstaPy#3350]
## Expected Behavior
The language should switch from German to English in my Firefox Browser
## Current Behavior
The language is not (always) switching from German to English in Firefox
## Possible Solution (optional)
I'm quite new with Python and Selenium, but this works for me in the login_util.py:
 ```
if switch_language:
    browser.find_element_by_xpath("//select[@class='hztqj']").click()
    browser.find_element_by_xpath("//option[@value='en']").click()
```
instead of:
```
language_element_ENG = browser.find_element_by_xpath(
       "//select[@class='hztqj']/option[text()='English']")
click_element(browser, language_element_ENG)
```

Maybe someone knows a better solution...

**Comment by thejeromelouis** [comment]
@converge Actually it is not a discussion. The code from InstaPy is not working for me. I have to copy and paste my solution in the latest version of InstaPy that its working.

**Comment by converge** [comment]
please, propose a pull request.

**Comment by thejeromelouis** [comment]
I tried it now several times - not possible. The page is just reloaded and still in German. No exception or anything like that. My print-command in the if-condition is working, but it's not possible to switch the language.

**Comment by thejeromelouis** [comment]
#3462 solved my problem! Thanks @converge

**Comment by fgisslen** [comment]
Traceback (most recent call last):
  File "/root/InstaPy/5be3ee3d34c0320013c1d5d7.py", line 16, in <module>
    with smart_run(session):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/root/InstaPy/instapy/util.py", line 1409, in smart_run
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 440, in login
    self.bypass_with_mobile):
  File "/root/InstaPy/instapy/login_util.py", line 177, in login_user
    browser.find_element_by_xpath("//select[@class='hztqj']").click()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='hztqj']"}
  (Session info: headless chrome=70.0.3538.77)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.15.0-39-generic x86_64)
