### ISSUE TITLE
Problem with comment

### ISSUE THREAD

**Issue by iskorini** [InstaPy/InstaPy#3363]
## Expected Behavior

Comment post

## Current Behavior

I have this error every time that bot tries to comment a post: 
> Traceback (most recent call last):
  File "edo.py", line 72, in <module>
    main()
  File "edo.py", line 54, in main
    job()
  File "edo.py", line 45, in job
    session.like_by_tags(hashtags, amount=math.ceil(105/len(hashtags)))
  File "/home/pi/InstagramBot/Edo/instapy/instapy.py", line 1684, in like_by_tags
    self.logfolder)
  File "/home/pi/InstagramBot/Edo/instapy/comment_util.py", line 66, in comment_image
    comment_input[0].clear()
  File "/usr/local/lib/python3.5/dist-packages/selenium-3.141.0-py3.5.egg/selenium/webdriver/remote/webelement.py", line 95, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "/usr/local/lib/python3.5/dist-packages/selenium-3.141.0-py3.5.egg/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium-3.141.0-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium-3.141.0-py3.5.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.33 (undefined),platform=Linux 4.14.71-v7+ armv7l)

## InstaPy configuration

- Raspberry PI 3 B with "Raspbian GNU/Linux 9 (stretch)"
- Chromedriver 2.33

`
def job():
	try:
		session = InstaPy(censored, headless_browser = True, bypass_suspicious_attempt = False).set_switch_language(False).login()

		# settings
		session.set_relationship_bounds(enabled=False)
		session.set_do_comment(True, percentage=30)
		session.set_comments(photo_comments, media='Photo')
		#session.set_comments(video_comments, media='Video')
		session.set_ignore_users(ignored_users)
		session.set_dont_like(ignored_hashtags)
		# actions
		session.like_by_tags(hashtags, amount=math.ceil(105/len(hashtags)))
		#session.like_by_users(specific_users, amount=6, randomize=True)
	finally:
		# end the bot session
		session.end()`

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
