### ISSUE TITLE
Fresh install, getting 'ImportError: sys.meta_path is None, Python is likely shutting down'

### ISSUE THREAD

**Issue by dannyvoid** [InstaPy/InstaPy#339]
First time trying to run this app, getting this every time.
Using the latest Python, webdriver, etc. On Windows 10.
Tried with GUI, and multiple other example quickstarts.

G:\ProgramFiles\InstaPy-master>python3 quickstart.py
Logged in successfully!
Tag [1/2]
--> b'dog'
Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    .like_by_tags(['dog', '#cat'], amount=100)\
  File "G:\ProgramFiles\InstaPy-master\instapy\instapy.py", line 367, in like_by_tags
    links = get_links_for_tag(self.browser, tag, amount, media)
  File "G:\ProgramFiles\InstaPy-master\instapy\like_util.py", line 121, in get_links_for_tag
    sleep(1)
  File "G:\ProgramFiles\InstaPy-master\instapy\time_util.py", line 22, in sleep
    original_sleep(randomize_time(t))
  File "G:\ProgramFiles\InstaPy-master\instapy\time_util.py", line 16, in randomize_time
    t = gauss(mean, stdev)
  File "C:\Python36\lib\random.py", line 603, in gauss
    g2rad = _sqrt(-2.0 * _log(1.0 - random()))
ValueError: math domain error
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x04E33F10>>
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 163, in __del__
  File "C:\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 139, in stop
  File "C:\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by timgrossmann** [comment]
@Nemixalone Could you also look into that, please?

I'll try to find out, what's wrong here...

**Comment by komad1na** [comment]
@dannyvoid Please copy whole **quickstart.py** file and paste it here. Thanks

**Comment by onyxim** [comment]
Try to [run with new docker micro services](https://github.com/timgrossmann/InstaPy#running-with-docker-microservices-manual). It completely solves many environment setup problems.

**Comment by olgavasileva** [comment]
Same problem here
