### ISSUE TITLE
Problem running instapy on EC2 instance

### ISSUE THREAD

**Issue by stefanosambruna** [InstaPy/InstaPy#3395]
I created an instance on EC2. The OS is ubuntu-xenial-16.04-amd64-server-20180912. I followed these instructions to run instapy: 
1. virtualenv venv
2. source venv/bin/activate
3. pip install git+https://github.com/timgrossmann/InstaPy.git
But I get this error:

```
Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    nogui=True)
  File "/home/ubuntu/instapy/venv/local/lib/python2.7/site-packages/instapy/instapy.py", line 232, in __init__
    self.set_selenium_local_session()
  File "/home/ubuntu/instapy/venv/local/lib/python2.7/site-packages/instapy/instapy.py", line 357, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/ubuntu/instapy/venv/local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/ubuntu/instapy/venv/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory

```

Do you know why?

**Comment by imkimchi** [comment]
did you install chromedriver ?

**Comment by stefanosambruna** [comment]
Yes, I put it inside assets

**Comment by imkimchi** [comment]
can you put your source code here?

**Comment by stefanosambruna** [comment]
Resolved! The problem was a wrong configuration of the session object. With the following code it works fine:
`session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)`
