### ISSUE TITLE
ConnectionAbortedError: [WinError 10053]

### ISSUE THREAD

**Issue by mgconejero** [InstaPy/InstaPy#3404]
Hi guys, i am having this problem constantly, it will login and stop suddenly... 
I have very limited knowledge of coding, alredy tried with google but cannot find the solution... somebody had the same issue? 

## Current Behavior
INFO [2018-11-20 23:50:19] []  Retrieving live `Following` data of  at "full" range
Traceback (most recent call last):
  File "c:/Users/MGC/Desktop/BOTS//quickstart.py", line 45, in <module>
    f_following = session.grab_following(username="f", amount="full", live_match=False, store_locally=True)
  File "c:\Users\MGC\Desktop\BOTS\\instapy\instapy.py", line 3534, in grab_following
    self.logfolder)
  File "c:\Users\MGC\Desktop\BOTS\\instapy\relationship_tools.py", line 240, in get_following
    web_address_navigator(browser, user_link)
  File "c:\Users\MGC\Desktop\BOTS\\instapy\util.py", line 810, in web_address_navigator
    current_url = get_current_url(browser)
  File "c:\Users\MGC\Desktop\BOTS\\instapy\util.py", line 1259, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "C:\Users\MGC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 635, in execute_script
    'args': converted_args})['value']
  File "C:\Users\MGC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 318, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\MGC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 472, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\MGC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 495, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "C:\Users\MGC\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\MGC\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\MGC\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\MGC\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Users\MGC\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
ConnectionAbortedError: [WinError 10053] Se ha anulado una conexión establecida por el software en su equipo host

## InstaPy configuration

""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = ''
insta_password = ''

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

with smart_run(session):
    """ Activity flow """
    
    # general settings
    session.set_relationship_bounds(enabled=None,
                                      delimit_by_numbers=None,
                                       max_followers=None,
                                        min_followers=None,
                                        min_following=None)
    session.set_simulation(enabled=True)
    session.set_skip_users(skip_private=False,
                       private_percentage=100,
                       skip_no_profile_pic=False,
                       no_profile_pic_percentage=100,
                       skip_business=False,
                       business_percentage=100,
                       skip_business_categories=[],
                       dont_skip_business_categories=[])

    session.set_dont_include(["

    
    # activity

   # Guardar los seguidores como lista
    
f_following = session.grab_following(username="", amount="full", live_match=False, store_locally=True)
 
session.set_do_follow(enabled=True, percentage=100)
session.follow_likers ([''], photos_grab_amount = 10, follow_likers_per_photo = 10, randomize=False, sleep_delay=400, interact=True)
session.follow_user_followers([''], amount=100,sleep_delay=400, randomize=False, interact=False)

**Comment by w4ngel** [comment]
Instagram was down yesterday for a period, that could be your issue. Could you try again today please?

**Comment by mgconejero** [comment]
> Instagram was down yesterday for a period, that could be your issue. Could you try again today please?

Thank you w4ngel, 

Sadly, it keeps with the same issue. I just download the last update of the code, give it a try and the same problem appear...

**Comment by mgconejero** [comment]
I download again the new update of the code, run it with the same settings and it worked. Might be just the instagram update (recently they changed de profile layout). 

Thank you again w4ngel 👍
