### ISSUE TITLE
Error: Cannot determine loading status

### ISSUE THREAD

**Issue by FBosler** [InstaPy/InstaPy#341]
Script keeps crashing (pretty much every night for the last few days). New Errors now. What I also find very strange is the low number of tags the script picks up on. I run my script by calling (manually, i.e. no cronjob):
`nohup python3.5 LikeScript.py &` on DigitalOcean Droplet with: 1 GB Memory / 30 GB Disk / Ubuntu 16.04.2 x64.

this is my script:
```excludePpl = ['list of my friends']

InstaPy(username='myName', password='myPass!', nogui=True)\
  .login()\
  .set_dont_include(excludePpl)\
  .set_upper_follower_count(limit = 500)\
  .set_do_follow(enabled=True, percentage=10, times=1)\
  .set_do_comment(True, percentage=15)\
  .set_comments(['Fantastic!', 'Awesome!', 'Brilliant!', 'Cool!', 'I love it', u'⭐']) \
  .set_use_clarifai(enabled=True, secret='mySecret', proj_id='myProjectId')\
  .clarifai_check_img_for(['nsfw'])\
  .like_by_tags(['myTags'], amount=300, media='Photo')\
  .unfollow_users(amount=75)\
  .end()
```

```
Logged in successfully!
Tag [1/4]
--> b'sport'
Traceback (most recent call last):
  File "LikeSCript.py", line 16, in <module>
    .like_by_tags(['sport','skiing','surfing','winter'], amount=300, media='Photo')\
  File "/root/InstaPy/instapy/instapy.py", line 367, in like_by_tags
    links = get_links_for_tag(self.browser, tag, amount, media)
  File "/root/InstaPy/instapy/like_util.py", line 150, in get_links_for_tag
    body_elem.send_keys(Keys.HOME)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 320, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': keys_to_typing(value)})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=59.0.3071.109)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-81-generic x86_64)
```

```
Logged in successfully!
Tag [1/3]
--> b'skiing'
Traceback (most recent call last):
  File "LikeSCript.py", line 16, in <module>
    .like_by_tags(['skiing','surfing','winter'], amount=300, media='Photo')\
  File "/root/InstaPy/instapy/instapy.py", line 367, in like_by_tags
    links = get_links_for_tag(self.browser, tag, amount, media)
  File "/root/InstaPy/instapy/like_util.py", line 158, in get_links_for_tag
    links = [link_elem.get_attribute('href') for link_elem in link_elems
  File "/root/InstaPy/instapy/like_util.py", line 159, in <listcomp>
    if link_elem.text in media]
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 68, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=59.0.3071.109)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-81-generic x86_64)
```

```
[32/300]
...
Traceback (most recent call last):
  File "LikeSCript.py", line 16, in <module>
    .like_by_tags(['skiing','surfing','winter'], amount=300, media='Photo')\
  File "/root/InstaPy/instapy/instapy.py", line 386, in like_by_tags
    liked = like_image(self.browser)
  File "/root/InstaPy/instapy/like_util.py", line 279, in like_image
    browser.execute_script("document.getElementsByClassName('" + like_elem[0].get_attribute("class") + "')[0].click()")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 111, in get_attribute
    resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=59.0.3071.109)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-81-generic x86_64)
```

**Comment by FBosler** [comment]
Bug keeps crashing the script :(

**Comment by timgrossmann** [comment]
@FBosler Did you restart the server to make sure there are no zombie instances of chrome eating up all the memory?

**Comment by FBosler** [comment]
I did, so far its looking good. But again, even before restating I checked my processes to makes sure that there aren't any undead chrome processes running, and if there were I killed them off. So I don't really think that was the issue.

Anyhow, after rebooting all is looking good so far. I'll let you know how it goes.

**Comment by timgrossmann** [comment]
@FBosler Awesome, if you want to make sure that that's not the problem, you can call the reboot command after the script is done:

```python
from subprocess import call
call(['reboot'])
