### ISSUE TITLE
like_by_feed method returning unhandled exception.

### ISSUE THREAD

**Issue by octavius-1** [InstaPy/InstaPy#3423]
Has anyone else been having this issue when trying to perform a like_by_feed method? 

Traceback (most recent call last):
  File "file.py", line 81, in <module>
    session.like_by_feed(amount=2, randomize=False, unfollow=False, interact=False)
  File "/home/pi/InstaBot/instapy/instapy.py", line 3175, in like_by_feed
    for i in self.like_by_feed_generator(**kwargs):
  File "/home/pi/InstaBot/instapy/instapy.py", line 3213, in like_by_feed_generator
    self.logger)
  File "/home/pi/InstaBot/instapy/like_util.py", line 34, in get_links_from_feed
    "window.scrollTo(0, document.body.scrollHeight);")
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.71-v7+ armv7l)

**Comment by david-vendel** [comment]
Seems like  your page crashed, probably small RAM? Like by feed maybe scrolls too deeply so it loads a huge page into the RAM. 
PS: Why don't u use python 3?
