### ISSUE TITLE
InstaPy crashing when loading user followers 

### ISSUE THREAD

**Issue by carsonmclarson** [InstaPy/InstaPy#3456]
I'ts been running fine for almost a month up until earlier today it started crashing while loading user followers. I've been using set user interact to do following and liking.

**Comment by silensinator** [comment]
In unfollow_util.py

Temporary replace 

```
dialog = browser.find_element_by_xpath(
        "//div[text()='Followers' or text()='Following']/../../following-sibling::div")
```

with 

```
dialog = browser.find_element_by_xpath(
        "//div[contains(@class,'isgrP')]")
```

IT WORKS!
Use this to temporary fix and get your algorithm running. Cause it is working for me.

**Comment by kranechan** [comment]
#3455 has the solution

**Comment by carsonmclarson** [comment]
> #3455 has the solution

This doesn't work unfortunately

**Comment by kranechan** [comment]
What is the error you are receiving?

**Comment by carsonmclarson** [comment]
> What is the error you are receiving?

it just says to upload an html file

**Comment by kranechan** [comment]
Whats got to do with html file? Do copy the error code here cause my solution has been proven working on the other thread

**Comment by carsonmclarson** [comment]
I'm not getting any error code

**Comment by cormo1990** [comment]
I have the same issue:

Traceback (most recent call last):
  File "xxxx.py", line 48, in <module>
    session.follow_user_followers(['xxxx',], amount=800, randomize=False, interact=False)
  File "/Users/xxxx/Desktop/InstaPy-master/instapy/instapy.py", line 2490, in follow_user_followers
    self.logfolder)
  File "/Users/xxxx/Desktop/InstaPy-master/instapy/unfollow_util.py", line 881, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/Users/xxxx/Desktop/InstaPy-master/instapy/unfollow_util.py", line 648, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.14.1-py3.7.egg/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.14.1-py3.7.egg/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.14.1-py3.7.egg/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.14.1-py3.7.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.12.6 x86_64)

**Comment by sergiosre** [comment]
some one can help??? i have the same problem :(

**Comment by thejeromelouis** [comment]
same problem :/

**Comment by epichfallen** [comment]
Having the same problem, Instagram might have changed something.

**Comment by epichfallen** [comment]
Fix working thanks to converge. Please refer to #3463

**Comment by carsonmclarson** [comment]
Okay I got it working I didn't see there are two parts in the unfollow_util with the find dialog box comment. swapped code under both of these comments and now it is working.

**Comment by carsonmclarson** [comment]
> Whats got to do with html file? Do copy the error code here cause my solution has been proven working on the other thread

works now thanks. initially I didn't change the code under the second find dialog box comment.

**Comment by LotusPainter** [comment]
How to I update my local copy with this updates? (windows)
