### ISSUE TITLE
InstaPy crash since 11/29/2018 evening

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#3461]
When i want to start my InstaPy bot i get this error since yesterday
I running this bot for almost 2 weeks with a crontab so i didn't touch it
since yesterday i get this:

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-11-30 12:02:45] [myusername]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

....................................................................
INFO [2018-11-30 12:03:22] [myusername]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

__________________________________________________________________________________
INFO [2018-11-30 12:03:26] [myusername]  Starting to follow user `Followers`..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-11-30 12:03:26] [myusername]  User 'prive' [1/3]
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20181130-120357.html
**********************************************************************

INFO [2018-11-30 12:03:58] [myusername]  Sessional Live Report:
	|> No any statistics to show
On session start was FOLLOWING 698 users & had 412 FOLLOWERS

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-11-30 12:03:58] [myusername]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "test.py", line 17, in <module>
    session.follow_user_followers(['prive','prive','prive'], amount=800, randomize=False, interact=False)
  File "/home/***/InstaPy/instapy/instapy.py", line 2907, in follow_user_followers
    self.logfolder)
  File "/home/***/InstaPy/instapy/unfollow_util.py", line 884, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/home/***/InstaPy/instapy/unfollow_util.py", line 651, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}
  (Session info: headless chrome=70.0.3538.110)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.18.0-11-generic x86_64)

**Comment by converge** [comment]
https://github.com/timgrossmann/InstaPy/issues/3453
