### ISSUE TITLE
following user followers crash

### ISSUE THREAD

**Issue by ibroudy** [InstaPy/InstaPy#3466]
this is a new issue i came across, i have had instapy working perfectly until yesterday i encounter this error when it tries to follow a users followers 

Traceback (most recent call last):
  File "quickstart.py", line 29, in <module>
    session.follow_user_followers(['thehookupfau', 'f45_training_bocaraton', 'bocatribune'], amount=38, randomize=True)
  File "/Users/ianbroudy/Desktop/new/instapy/instapy.py", line 2504, in follow_user_followers
    self.logfolder)
  File "/Users/ianbroudy/Desktop/new/instapy/unfollow_util.py", line 906, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/Users/ianbroudy/Desktop/new/instapy/unfollow_util.py", line 644, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 393, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.14.0 x86_64)

**Comment by w4ngel** [comment]
As seen here where a few solutions are provided:
#3456 #3455 #3453

**Comment by ibroudy** [comment]
those solutions have not worked for me in the unfollow util.py
