### ISSUE TITLE
Continuing Issue

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#3468]
## Expected Behavior
To work
## Current Behavior
Stops working after 1 processed, sometimes more.
## InstaPy configuration
Everything is freshly installed and downloaded. Here is the console output.

INFO [2018-12-01 00:58:46] [the.mens.playbook]  User 'carpenterwatches' [1/3]
INFO:the.mens.playbook:User 'carpenterwatches' [1/3]
Traceback (most recent call last):
  File "quickstart.py", line 19, in <module>
    session.follow_user_followers(['carpenterwatches', 'artworth_brothers', 'ryans_watches'], amount=3000, sleep_delay=175, randomize=True, interact=True)
  File "/home/evan/InstaPy/instapy/instapy.py", line 2840, in follow_user_followers
    self.logfolder)
  File "/home/evan/InstaPy/instapy/unfollow_util.py", line 885, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/home/evan/InstaPy/instapy/unfollow_util.py", line 652, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}
  (Session info: chrome=70.0.3538.77)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-39-generic x86_64)

**Comment by converge** [comment]
https://github.com/timgrossmann/InstaPy/issues/3453
