### ISSUE TITLE
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='hztqj']/option[text()='English']"}

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3472]
I can't get this fixed. It happens often to some accounts. @timgrossmann @sionking @converge @uluQulu 

Traceback (most recent call last):
  File "/root/InstaPy/5bf493ef6d3a6a001447ea35.py", line 16, in <module>
    with smart_run(session):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/root/InstaPy/instapy/util.py", line 1409, in smart_run
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 440, in login
    self.bypass_with_mobile):
  File "/root/InstaPy/instapy/login_util.py", line 178, in login_user
    "//select[@class='hztqj']/option[text()='English']")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='hztqj']/option[text()='English']"}
  (Session info: headless chrome=70.0.3538.102)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.4.0-139-generic x86_64)

**Comment by bastian147-dev** [comment]
Same issue here

**Comment by thejeromelouis** [comment]
I had almost the same problem in #3350.
Try to replace this in your login_util.py:

```
language_element_ENG = browser.find_element_by_xpath(
       "//select[@class='hztqj']/option[text()='English']")
click_element(browser, language_element_ENG)
```
with the following code:
```
   browser.find_element_by_xpath("//select[@class='hztqj']").click()
   browser.find_element_by_xpath("//option[@value='en']").click()
```

This works for me. Hopefully for you guys as well!

**Comment by fgisslen** [comment]
@thejeromelouis Hi, thanks for your answer. 
I use Chrome, but it should work for chrome to right?

**Comment by fgisslen** [comment]
@thejeromelouis 
Traceback (most recent call last):
  File "/root/InstaPy/5be3ee3d34c0320013c1d5d7.py", line 16, in <module>
    with smart_run(session):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/root/InstaPy/instapy/util.py", line 1409, in smart_run
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 440, in login
    self.bypass_with_mobile):
  File "/root/InstaPy/instapy/login_util.py", line 177, in login_user
    browser.find_element_by_xpath("//select[@class='hztqj']").click()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='hztqj']"}
  (Session info: headless chrome=70.0.3538.77)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.15.0-39-generic x86_64)

**Comment by fgisslen** [comment]
@thejeromelouis 
Traceback (most recent call last):
  File "/root/InstaPy/5bfd629a8eafbf00142049c9.py", line 16, in <module>
    with smart_run(session):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/root/InstaPy/instapy/util.py", line 1409, in smart_run
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 440, in login
    self.bypass_with_mobile):
  File "/root/InstaPy/instapy/login_util.py", line 177, in login_user
    browser.find_element_by_xpath("//select[@class='hztqj']").click()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='hztqj']"}
  (Session info: headless chrome=70.0.3538.102)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.4.0-139-generic x86_64)

**Comment by thejeromelouis** [comment]
It could be that the search item is executed before it is present on the page. Have you tried to increase your page-delay?

**Comment by fgisslen** [comment]
> It could be that the search item is executed before it is present on the page. Have you tried to increase your page-delay?

@thejeromelouis I have had 100 in page delay. wondering if I should try not to use page delay.
How much page delay do you have?

**Comment by mj-01** [comment]
I have the same issue when I try to use proxy server

**Comment by ocimen** [comment]
Changing proxy solved this issue.

**Comment by octavius-1** [comment]
@ocimen What do you mean with "changing proxy"?

**Comment by ocimen** [comment]
@octavius-1 i'm using free proxy server. After a while (generally 3 or 4 days later) the proxy server having an issue i get this error. When i switch proxy server to a newer one, everthing works fine again.
