### ISSUE TITLE
after git pull 

### ISSUE THREAD

**Issue by oshri122** [InstaPy/InstaPy#3473]
after git pull today 

Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 25, in <module>
    from .comment_util import comment_image
  File "/root/InstaPy/instapy/comment_util.py", line 7, in <module>
    from .util import update_activity
  File "/root/InstaPy/instapy/util.py", line 7, in <module>
    import regex
ModuleNotFoundError: No module named 'regex'

**Comment by Nuzzo235** [comment]
You need to install the new packages that were added after the last pull. cd to the instapy directory and run: `pip install -r requirements.txt` in your shell. Cheers, Nuzzo

**Comment by oshri122** [comment]
installed 
same error

**Comment by Nuzzo235** [comment]
Alright, since the regex package is missing (`ModuleNotFoundError: No module named 'regex'`) try to add it manually via `pip install regex`

**Comment by oshri122** [comment]
tnx !
i install it with pip3
