### ISSUE TITLE
Error can't multiply squence. Why?

### ISSUE THREAD

**Issue by M4RC0Sx** [InstaPy/InstaPy#3476]
Traceback (most recent call last):                                                                                                                                                                                 
  File "quickstart.py", line 165, in <module>                                                                                                                                                                      
    schedule.run_pending()                                                                                                                                                                                         
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 493, in run_pending                                                                                                                     
    default_scheduler.run_pending()                                                                                                                                                                                
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 78, in run_pending                                                                                                                      
    self._run_job(job)                                                                                                                                                                                             
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 131, in _run_job                                                                                                                        
    ret = job.run()                                                                                                                                                                                                
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 411, in run                                                                                                                             
    ret = self.job_func()                                                                                                                                                                                          
  File "quickstart.py", line 100, in xunfollow                                                                                                                                                                     
    session = get_session()                                                                                                                                                                                        
  File "quickstart.py", line 30, in get_session                                                                                                                                                                    
    multi_logs=False)                                                                                                                                                                                              
  File "/home/Instagram/Marcos/AutoFollowUnfollow/instapy/instapy.py", line 250, in __init__                                                                                                                       
    self.set_selenium_local_session()                                                                                                                                                                              
  File "/home/Instagram/Marcos/AutoFollowUnfollow/instapy/instapy.py", line 391, in set_selenium_local_session                                                                                                     
    highlight_print(self.username, message, "initialization", "info", self.logger)                                                                                                                                 
  File "/home/Instagram/Marcos/AutoFollowUnfollow/instapy/util.py", line 929, in highlight_print                                                                                                                   
    print("\n{}".format(upper_char * ceil(output_len/len(upper_char))))                                                                                                                                            
TypeError: can't multiply sequence by non-int of type 'float'      

I use the quickstart template that follows and unfollows and sends telegram messages. The error is on the xunfollow section.

**Comment by JoeFertig** [comment]
Are you using python2 or 3?

**Comment by uluQulu** [comment]
Hi there

@M4RC0Sx,
The solution is shared at https://github.com/timgrossmann/InstaPy/issues/3451#issuecomment-443006555.
