### ISSUE TITLE
follow doesn't work 

### ISSUE THREAD

**Issue by tackop** [InstaPy/InstaPy#3496]
hi guy recently i cannot use instapy for follow anymore, when i started the run I received this msg 

Traceback (most recent call last):
  File "follow.py", line 30, in <module>
    session.follow_user_followers(['(someone)'], amount=500, randomize=False)
  File "/Users/Me/Downloads/InstaPy/instapy/instapy.py", line 2490, in follow_user_followers
    self.logfolder)
  File "/Users/Me/Downloads/InstaPy/instapy/unfollow_util.py", line 913, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/Users/Me/Downloads/InstaPy/instapy/unfollow_util.py", line 648, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/Users/Me/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Me/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Me/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Me/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.12.6 x86_64)

can you help me to find an issue for this please

**Comment by octavius-1** [comment]
Same issue around here in interact_user_followers

**Comment by mattymacnj** [comment]
same problem here
