### ISSUE TITLE
quickstart failing

### ISSUE THREAD

**Issue by tariquesani** [InstaPy/InstaPy#3503]
Hi, 
Can anyone look at this traceback and let me know what is wrong.

`Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    headless_browser=False)
  File "/home/tariquesani/Projects/instapy/venv/local/lib/python2.7/site-packages/instapy/instapy.py", line 250, in __init__
    self.set_selenium_local_session()
  File "/home/tariquesani/Projects/instapy/venv/local/lib/python2.7/site-packages/instapy/instapy.py", line 391, in set_selenium_local_session
    highlight_print(self.username, message, "initialization", "info", self.logger)
  File "/home/tariquesani/Projects/instapy/venv/local/lib/python2.7/site-packages/instapy/util.py", line 929, in highlight_print
    print("\n{}".format(upper_char * ceil(output_len/len(upper_char))))
TypeError: can't multiply sequence by non-int of type 'float'
`

**Comment by octavius-1** [comment]
Had the same issue, try casting to int the result of the division, otherwise you’re going to have n.0 instead of n 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BrianneHostutler** [comment]
I have the same issue, @octavius-1 can you elaborate on what needs to be changed?

**Comment by BrianneHostutler** [comment]
Actually found the answer here: https://github.com/timgrossmann/InstaPy/issues/3451. I had to update to python 3 and pip 3 and it is working now.

**Comment by tariquesani** [comment]
Using `virtualenv -p python3 venv` fix it for me. May be the instructions in README should be changed
