### ISSUE TITLE
The bot is not starting its showing some errors

### ISSUE THREAD

**Issue by khansaad1275** [InstaPy/InstaPy#3509]
## Expected Behavior
it should be running 
## Current Behavior
it's not working, the terminal is just opening and showing this error 
Traceback (most recent call last):
  File "C:\Users\thmsb\Desktop\InstaPy\quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "C:\Users\thmsb\Desktop\InstaPy\instapy\__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "C:\Users\thmsb\Desktop\InstaPy\instapy\instapy.py", line 25, in <module>
    from .clarifai_util import check_image
  File "C:\Users\thmsb\Desktop\InstaPy\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "C:\Users\thmsb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\clarifai-2.4.2-py3.7.egg\clarifai\rest\__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "C:\Users\thmsb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\clarifai-2.4.2-py3.7.egg\clarifai\rest\client.py", line 22, in <module>
    from jsonschema import validate
  File "C:\Users\thmsb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jsonschema-3.0.0a3-py3.7.egg\jsonschema\__init__.py", line 12, in <module>
    from jsonschema.exceptions import (
  File "C:\Users\thmsb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jsonschema-3.0.0a3-py3.7.egg\jsonschema\exceptions.py", line 6, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
>>>

**Comment by khansaad1275** [comment]
i just commented line 24 in instapy/insta.py
 
from .clarifai_util import check_image

and its running but templates are not working properly

**Comment by FUKCHEFBLU** [comment]
IM HAVING THIS ISSUE PLEASE HELP

**Comment by FUKCHEFBLU** [comment]
Someone help step by step

**Comment by khansaad1275** [comment]
@FUKCHEFBLU 

1.open the main folder containing all files (where your quick start.py is stored)
2.there you will find a folder named Instapy.
3.open the folder and then you will find some .py files(files looking like Quick start.py)
4.open the insta.py file with IDLE or sublime text editor or notepad++.
5.just go on line 24 form top and ad a # in the start of the line so it will turn into a comment.
e.i. before: from .clarifai_util import check_image 
      after: # from .clarifai_util import check_image (i just added hash before the line)
6.save the file and it will start running.

**Comment by xerZV** [comment]
SAme, can't start, even can't login. No errors. Just can't start!
