### ISSUE TITLE
yesterday is working fine but today there seems to be a problem starting

### ISSUE THREAD

**Issue by nosecretz** [InstaPy/InstaPy#3513]
i dont know whats going on. can someone help me? thanks.

----------------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\instapy\InstaPy-master - Copy\quickstart.py", line 25, in <module>
    session.login()
  File "C:\Users\instapy\InstaPy-master - Copy\instapy\instapy.py", line 350, in login
    self.bypass_suspicious_attempt):
  File "C:\Users\instapy\InstaPy-master - Copy\instapy\login_util.py", line 162, in login_user
    "//form/span/button[text()='Log in']")
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 393, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

>>>

**Comment by psyfox** [comment]
Hi @nosecretz
Same error here.
Looks like a code change from Instagrams website. This is a normal condition since websites keep changing their codes and projects(with Selenium) must catch up to stay running. So, you can fix it by yourself or wait for a solution from this project.

**Comment by lbenassi** [comment]
Same error. Does anyone know how to solve? Thanks

**Comment by SMarcinno** [comment]
I don't think the IG-Site has changed. I don't have that problem. 
It is running fine right now.

**Comment by bergeny** [comment]
Just change the login_button xpath in login_util.py

"//form/div[3]/button[text()='Log in']"

**Comment by xerZV** [comment]
SAme, can't start, even can't login. No errors. Just can't start!
