### ISSUE TITLE
AttributeError: 'list' object has no attribute 'format'

### ISSUE THREAD

**Issue by highmountainwoody** [InstaPy/InstaPy#3518]
Getting the following error while using one of the quickstart scripts.  "Target followers of similar accounts..."

```
Traceback (most recent call last):
  File "custom.py", line 100, in <module>
    session.follow_user_followers(random_targets, amount=random.randint(30,60), randomize=True, sleep_delay=600, interact=True)
  File "/root/InstaPy/instapy/instapy.py", line 3017, in follow_user_followers
    interact)
  File "/root/InstaPy/instapy/instapy.py", line 1071, in follow_by_list
    self.user_interact_media)
  File "/root/InstaPy/instapy/instapy.py", line 2211, in interact_by_users
    self.logfolder)
  File "/root/InstaPy/instapy/comment_util.py", line 61, in comment_image
    rand_comment = (random.choice(comments).format(username))
AttributeError: 'list' object has no attribute 'format' 
```

**Below is the whole code block from this script.**

```
 # FOLLOW+INTERACTION on TARGETED accounts
    """ Select users form a list of a predefined targets...
    """
    number = random.randint(3, 5)
    random_targets = targets

    if len(targets) <= number:
        random_targets = targets

    else:
        random_targets = random.sample(targets, number)

    """ Interact with the chosen targets...
    """
    session.follow_user_followers(random_targets, amount=random.randint(30,60), randomize=True, sleep_delay=600, interact=True)
```

**Comment by ghost** [comment]
Same Error

**Comment by uluQulu** [comment]
Hi @highmountainwoody @notefortroy 

Inside that _quickstart template_,
**replace**
```erlang
session.set_comments([comments], media='Photo')
```
**with**
```erlang
session.set_comments(comments, media='Photo')
```

---

Cheers 😁
---
