### ISSUE TITLE
can'n install :(

### ISSUE THREAD

**Issue by amar3142** [InstaPy/InstaPy#3524]
## InstaPy configuration
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/home/amar/Documents/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/amar/Documents/InstaPy/instapy/instapy.py", line 25, in <module>
    from .clarifai_util import check_image
  File "/home/amar/Documents/InstaPy/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "/usr/local/lib/python2.7/dist-packages/clarifai-2.4.2-py2.7.egg/clarifai/rest/__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "/usr/local/lib/python2.7/dist-packages/clarifai-2.4.2-py2.7.egg/clarifai/rest/client.py", line 22, in <module>
    from jsonschema import validate
  File "/usr/local/lib/python2.7/dist-packages/jsonschema-3.0.0a3-py2.7.egg/jsonschema/__init__.py", line 12, in <module>
    from jsonschema.exceptions import (
  File "/usr/local/lib/python2.7/dist-packages/jsonschema-3.0.0a3-py2.7.egg/jsonschema/exceptions.py", line 8, in <module>
    from jsonschema import _utils
  File "/usr/local/lib/python2.7/dist-packages/jsonschema-3.0.0a3-py2.7.egg/jsonschema/_utils.py", line 6, in <module>
    from jsonschema.compat import str_types, MutableMapping, urlsplit
  File "/usr/local/lib/python2.7/dist-packages/jsonschema-3.0.0a3-py2.7.egg/jsonschema/compat.py", line 35, in <module>
    from functools32 import lru_cache

**Comment by Mehran** [comment]
you can try my auto installation script , i tested on `ubuntu 16 & 18`  , 

`curl -s https://gist.githubusercontent.com/Mehran/970a4a6a705f5898ca465312e785f8f4/raw/1d3c46130fb1c6e8af140dd76fd690ab53210335/instapy-easy.sh | sh`
