### ISSUE TITLE
.follow_by_list breaking after following a few accounts. My bad?

### ISSUE THREAD

**Issue by jedbanger** [InstaPy/InstaPy#354]
If i understand correctly the use of of` .follow_by_list` is to give it an array of usernames to follow.
When I use it, it correctly follows the first usernames in the array,  but after opening an n account, it breaks with this error:

Log:

Logged in successfully!
--> **** instagram account is opened...
---> Now following: ****
********************
--> **** instagram account is opened...
---> Now following: ****
********************
********************
--> **** instagram account is opened...

`Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session.follow_by_list(array1, times=1)
  File "C:\Users\AndyL\Downloads\InstaPy-master\InstaPy-master\instapy\instapy.py", line 217, in follow_by_list
    followed += follow_given_user(self.browser, acc_to_follow, self.follow_restrict)
  File "C:\Users\AndyL\Downloads\InstaPy-master\InstaPy-master\instapy\unfollow_util.py", line 67, in follow_given_user
    if follow_button.text == 'Follow':
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 73, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.10240 x86_64)`

Am i doing something incorrectly? Thanks

**Comment by saurabh-kumar-vit** [comment]
What do you mean when you say 

> but after opening an n account

What does n mean?

**Comment by jedbanger** [comment]
Sorry for not being clear. I meant that it doesn't always stop after the same ammount of follows. 
At first I thought that it broke what it encountered a private account but then i also saw the same problem with a public account.

**Comment by timgrossmann** [comment]
#336
