### ISSUE TITLE
Docker interact_user_followers() exception: "element is not attached to the page document"

### ISSUE THREAD

**Issue by kacpermaciejevvski** [InstaPy/InstaPy#3542]
Problem appears after  ~5 min.

I tried wiping `/InstaPy/logs/<user>` folder mentioned in  #2261,
I applied fix for `post_unfollow_cleanup()` function mentioned in #3535

Logs: 

web_1       | INFO [2018-12-10 12:45:45] [<myUser>]  User '<userC>' [3/4]
web_1       | Traceback (most recent call last):
web_1       |   File "docker_quickstart.py", line 72, in <module>
web_1       |     job()
web_1       |   File "docker_quickstart.py", line 45, in job
web_1       |     session.interact_user_followers(['<userA>', '<userB>', '<userC>', '<userD>'], amount=10, randomize=True)
web_1       |   File "/code/instapy/instapy.py", line 2634, in interact_user_followers
web_1       |     self.logfolder)
web_1       |   File "/code/instapy/unfollow_util.py", line 892, in get_given_user_followers
web_1       |     channel, jumps, logger, logfolder)
web_1       |   File "/code/instapy/unfollow_util.py", line 727, in get_users_through_dialog
web_1       |     person_list = dialog_username_extractor(buttons)
web_1       |   File "/code/instapy/unfollow_util.py", line 750, in dialog_username_extractor
web_1       |     if person and hasattr(person, 'text') and person.text:
web_1       |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 76, in text
web_1       |     return self._execute(Command.GET_ELEMENT_TEXT)['value']
web_1       |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
web_1       |     return self._parent.execute(command, params)
web_1       |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
web_1       |     self.error_handler.check_response(response)
web_1       |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
web_1       |     raise exception_class(message, screen, stacktrace)
web_1       | selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
web_1       |   (Session info: chrome=70.0.3538.110)
web_1       |   (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-42-generic x86_64)
web_1       | 
instapy_web_1 exited with code 1

**Comment by kacpermaciejevvski** [comment]
The problem appears when InstaPy grabs too many followers from user. Probably an array is being overloaded with too many followers names (around 16,2kk) and selenium is crashing. Answer was to simply remove user from interact_user_followers() list. However its a hack instead of solution so it should be fixed soon.
