### ISSUE TITLE
Fail to run quickstart.py on Raspbian Stretch

### ISSUE THREAD

**Issue by daliborg** [InstaPy/InstaPy#3544]
Hi guys,

I've just installed InstaPy on the Raspbian Strech fresh installed image but cannot get it working.
Below is the log output what I get when try to run quickstart.py:

root@raspberrypi:/home/pi/InstaPy# python3 quickstart.py
Traceback (most recent call last):
File "quickstart.py", line 17, in <module>
headless_browser=True)
File "/home/pi/InstaPy/instapy/instapy.py", line 255, in __init__
self.set_selenium_local_session()
File "/home/pi/InstaPy/instapy/instapy.py", line 380, in set_selenium_local_session
chrome_options=chrome_options)
File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
self.service.start()
File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
stdin=PIPE)
File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
restore_signals, start_new_session)
File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

Can somebody help with this?

**Comment by andreescocard** [comment]
This error is related to chromedriver, probably you are using a version not compatible with arm devices

**Comment by andreescocard** [comment]
check https://github.com/timgrossmann/InstaPy/issues/2678
