### ISSUE TITLE
It was working But Now Does Not

### ISSUE THREAD

**Issue by GraduErd** [InstaPy/InstaPy#3556]
It was working awesome. I tried open 2 terminal. It worked. A terminal was following and the other was unfollowing. After that i changed some settings and re-start. There was no problem still. But suddenly it stopped and when i try to connect always this error:
INFO [2018-12-12 13:27:46] [*]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

............................................................
INFO [2018-12-12 13:28:19] [*]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2018-12-12 13:28:22] [*]  Sessional Live Report:
	|> No any statistics to show
On session start was FOLLOWING 1027 users & had 169 FOLLOWERS

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-12-12 13:28:22] [*]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooo

________________________________________________________________
INFO [2018-12-12 13:28:22] [*]  Starting to follow likers..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

Getting likers from user:  * 

Traceback (most recent call last):
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/Users/**/InstaPy/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x113b9b4a8>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 37, in <module>
    session.follow_likers (['*' , '*'], photos_grab_amount = 3, follow_likers_per_photo = 125, randomize=True, sleep_delay=600, interact=False)
  File "/Users/**/InstaPy/instapy/instapy.py", line 904, in follow_likers
    photo_urls = get_photo_urls_from_profile(self.browser, username, photos_grab_amount, randomize)
  File "/Users/**/InstaPy/instapy/commenters_util.py", line 367, in get_photo_urls_from_profile
    web_address_navigator(browser,'https://www.instagram.com/' + username +'/')
  File "/Users/e*/InstaPy/instapy/util.py", line 839, in web_address_navigator
    current_url = get_current_url(browser)
  File "/Users/*/InstaPy/instapy/util.py", line 1313, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/Users/**/InstaPy/venv/lib/python3.6/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/*/InstaPy/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=*): Max retries exceeded with url: /session/0d53f00ff1ff61ee3a8858f0d303dad8/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b9b4a8>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by GraduErd** [comment]
Solved.

**Comment by NooriP** [comment]
@erdemnohutcu Can you please share the solution i am having the same issue.

Same issue raised for many accounts.

**Comment by GraduErd** [comment]
just space problem

**Comment by julienteyssier** [comment]
Could you develop please ? I have the same issue
