### ISSUE TITLE
Traceback module

### ISSUE THREAD

**Issue by sonnyobrien** [InstaPy/InstaPy#356]
upon running the example.py

Traceback (most recent call last):
  File "C:\Users\Sonny\Downloads\InstaPy-master(1)\InstaPy-master\examples\example.py", line 2, in <module>
    from instapy import InstaPy
ImportError: No module named instapy
>>>

**Comment by philsiegel** [comment]
Move the example.py to the InstaPy-master folder instead of the examples folder

**Comment by sonnyobrien** [comment]
I tried that. Now I am receiving this from example.py

Traceback (most recent call last):
  File "C:\Users\Sonny\Downloads\InstaPy-master(1)\InstaPy-master\InstaPy\example.py", line 2, in <module>
    from instapy import InstaPy
  File "C:\Users\Sonny\Downloads\InstaPy-master(1)\InstaPy-master\InstaPy\instapy.py", line 10, in <module>
    from .clarifai_util import check_image
ValueError: Attempted relative import in non-package
>>>

**Comment by sonnyobrien** [comment]
Just want to add that I have clarifai:
C:\Users\Sonny>pip install future
Requirement already satisfied: future in c:\python27\lib\site-packages

C:\Users\Sonny>pip install clarifai
Requirement already satisfied: clarifai in c:\python27\lib\site-packages
Requirement already satisfied: Pillow==2.9.0 in c:\python27\lib\site-packages (f
rom clarifai)
Requirement already satisfied: future==0.15.2 in c:\python27\lib\site-packages (
from clarifai)
Requirement already satisfied: jsonschema==2.5.1 in c:\python27\lib\site-package
s (from clarifai)
Requirement already satisfied: requests==2.13.0 in c:\python27\lib\site-packages
 (from clarifai)
Requirement already satisfied: configparser==3.5.0 in c:\python27\lib\site-packa
ges (from clarifai)
Requirement already satisfied: functools32; python_version == "2.7" in c:\python
27\lib\site-packages (from jsonschema==2.5.1->clarifai)

**Comment by sonnyobrien** [comment]
I receive this error when opening the quickstart.py:

Traceback (most recent call last):
  File "C:\Users\Sonny\Downloads\InstaPy-master(1)\InstaPy\quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\Sonny\Downloads\InstaPy-master(1)\InstaPy\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\Users\Sonny\Downloads\InstaPy-master(1)\InstaPy\instapy\instapy.py", line 11, in <module>
    from .comment_util import comment_image
  File "C:\Users\Sonny\Downloads\InstaPy-master(1)\InstaPy\instapy\comment_util.py", line 10, in <module>
    import emoji
ImportError: No module named emoji
>>>

**Comment by immersivescience** [comment]
im receiving this error...
Traceback (most recent call last):
  File "C:\Users\Phillip\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\quickstart.py", line 19, in <module>
    from instapy import InstaPy
  File "C:\Users\Phillip\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 25, in <module>
    from .clarifai_util import check_image
ImportError: attempted relative import with no known parent package
>>>
