### ISSUE TITLE
Wah! Error occurred while getting a DB for 'username': unable to open database file

### ISSUE THREAD

**Issue by mirlannur** [InstaPy/InstaPy#3565]
## Current Behavior
Getting error when running quickstart.py

> WARNING [2018-12-13 18:25:41] [username]  Wah! Error occurred while getting a DB for 'username':
        unable to open database file
> Traceback (most recent call last):
>   File "quickstart.py", line 16, in <module>
>     headless_browser=False)
>   File "D:\╤юЄЁєфэшъш\username\projects\InstaPy\instapy\instapy.py", line 253, in __init__
    get_database(make=True)
>   File "D:\╤юЄЁєфэшъш\username\projects\InstaPy\instapy\database_engine.py", line 42, in get_database
>     create_database(address, logger, name)
>   File "D:\╤юЄЁєфэшъш\username\projects\InstaPy\instapy\database_engine.py", line 68, in create_database
>     if connection:
> UnboundLocalError: local variable 'connection' referenced before 

There exists the folder db, but it's empty.

**Comment by mirlannur** [comment]
# Fixed
The problem was in full path of instapy.db - "D:\╤юЄЁєфэшъш\username\projects\InstaPy\db\instapy.db"

Solution
Renamed cyryllic foldername ╤юЄЁєфэшъш
