### ISSUE TITLE
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3587]
Traceback (most recent call last):
  File "/root/InstaPy/5c0b9b81a06549001483f02f.py", line 27, in <module>
    session.interact_user_followers(['xx','xx','xx','xx','xx'], amount=40, randomize=True)
  File "/root/InstaPy/instapy/instapy.py", line 2720, in interact_user_followers
    self.user_interact_media)
  File "/root/InstaPy/instapy/instapy.py", line 2121, in interact_by_users
    media)
  File "/root/InstaPy/instapy/like_util.py", line 371, in get_links_for_username
    following, follow_button = get_following_status(browser, 'profile', username, person, None, logger, logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 155, in get_following_status
    following_status = follow_button.text
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=70.0.3538.77)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-39-generic x86_64)

**Comment by converge** [comment]
could you provide a step by step to reproduce the issue ?
