### ISSUE TITLE
clarifai.rest import Workflow

### ISSUE THREAD

**Issue by Narbe26** [InstaPy/InstaPy#3612]
Hello, i have this problem it's possible to solve it ?

Thanks you

pc57:InstaPy narbe$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/Users/narbe/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/narbe/InstaPy/instapy/instapy.py", line 21, in <module>
    from .clarifai_util import check_image
  File "/Users/narbe/InstaPy/instapy/clarifai_util.py", line 4, in <module>
    from clarifai.rest import Workflow

**Comment by HCWcoder** [comment]
@Narbe26 
just commented line 24 in instapy/insta.py

`from .clarifai_util import check_image`

**Comment by Narbe26** [comment]
Thank but It's don't work for me

**Comment by HCWcoder** [comment]
@Narbe26 

because you are running the script outside its path !

run your script that is inside instapy or create a shortcut outside
