### ISSUE TITLE
Problem with installing InstaPy on a server.

### ISSUE THREAD

**Issue by KirjoZzZ** [InstaPy/InstaPy#3618]
Hello. Im very new to this bot. I have managed to install everything on my pc but im having some trouble starting it on VPS server. It is Windows server 2012. The problem is, when I try to run the script it just instantly shuts it down.

This is an error which I see:

```
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
=== RESTART: C:\Users\Administrator\Documents\GitHub\InstaPy\quickstart.py ===
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\InstaPy\quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "C:\Users\Administrator\Documents\GitHub\InstaPy\instapy\__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "C:\Users\Administrator\Documents\GitHub\InstaPy\instapy\instapy.py", line 12, in <module>
    import requests
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.21.0-py3.6.egg\requests\__init__.py", line 44, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'
>>> 
```

**Comment by IH4xx3R** [comment]
ModuleNotFoundError means that you have to install a missing module.
In this case it's 'chardet'.
You can install it using pip install chardet.

**Comment by KirjoZzZ** [comment]
Thank you a lot. That helped.
