### ISSUE TITLE
Windows Run Issue - ModuleNotFoundError: No module named 'emoji'

### ISSUE THREAD

**Issue by gethubuser24** [InstaPy/InstaPy#364]
1. This is the error I get when running from the command prompt 

C:\Program Files (x86)\Python36-32\Scripts\InstaPy-master>py quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Program Files (x86)\Python36-32\Scripts\InstaPy-master\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\Program Files (x86)\Python36-32\Scripts\InstaPy-master\instapy\instapy.py", line 11, in <module>
    from .comment_util import comment_image
  File "C:\Program Files (x86)\Python36-32\Scripts\InstaPy-master\instapy\comment_util.py", line 10, in <module>
    import emoji
ModuleNotFoundError: No module named 'emoji'

Any ideas on what would cause this?

2.  For your Windows install you stated:

_"4. Edit the instapy.py file

Open file instapy.py an disabling the clarifai import
comment the line "from clarifai.client import ClarifaiApi"
from clarifai.client import ClarifaiApi"_

Did you mean the clarifai_util file?

**Comment by timgrossmann** [comment]
@gethubuser24 Please use the search function...

If `No module named xxx` shows up, just do `pip3 install xxx`

In this case `pip3 install emoji`
