### ISSUE TITLE
Firefox + geckodriver doesn't really work

### ISSUE THREAD

**Issue by oskarkrawczyk** [InstaPy/InstaPy#3656]
I had some issues with `chromedriver` so tried to use `geckodriver`, unfortunately that doesn't work at all:

```zsh
Traceback (most recent call last):
  File "qs-follow.py", line 17, in <module>
    with smart_run(session):
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/oskarkrawczyk/Sites/InstaPy/instapy/util.py", line 1415, in smart_run
    session.login()
  File "/Users/oskarkrawczyk/Sites/InstaPy/instapy/instapy.py", line 349, in login
    self.bypass_with_mobile):
  File "/Users/oskarkrawczyk/Sites/InstaPy/instapy/login_util.py", line 207, in login_user
    .move_to_element(login_elem)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (901.4916915893555, 695) is out of bounds of viewport width (1280) and height (694)
```

Doesn't look like many people use it so perhaps the easiest way would be just to remove it from the docs.

**EDIT**

OS: macOS Mojave
Firefox: 64.0
Geckodriver: 0.23.0

**Comment by gitpatrickhub** [comment]
It depends on many variables; Platform, Operating System, version of OS,  version of FireFox, version of Geckodriver. 

I'm using it on;
Platform = Raspberry Pi 3
OS = Debian Jessie
Firefox = 60.3.0 ESR
Geckodriver = 0.22.0

**Comment by w4ngel** [comment]
> ov

Hi,

I use geckodriver exclusively and I don't get this- whereabouts does this happen?

**Comment by converge** [comment]
#3662 @oskarkrawczyk could you check if the PR fix the issue ?

**Comment by w4ngel** [comment]
@oskarkrawczyk please pull the latest version that should fix your issue.

**Comment by oskarkrawczyk** [comment]
Awesome, I can confirm the issue is now fixed!

Thanks @converge!
