### ISSUE TITLE
Windows locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by gethubuser24** [InstaPy/InstaPy#366]
I receive the following error about an "unsupported locale setting"  what am I missing?

C:\Program Files (x86)\Python36-32\Scripts\InstaPy-master>start.bat
C:\Program Files (x86)\Python36-32\Scripts\InstaPy-master>set PYTHONIOENCODING=UTF-8
C:\Program Files (x86)\Python36-32\Scripts\InstaPy-master>py quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Program Files (x86)\Python36-32\Scripts\InstaPy-master\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\Program Files (x86)\Python36-32\Scripts\InstaPy-master\instapy\instapy.py", line 20, in <module>
    from .unfollow_util import unfollow
  File "C:\Program Files (x86)\Python36-32\Scripts\InstaPy-master\instapy\unfollow_util.py", line 9, in <module>
    locale.setlocale( locale.LC_ALL, 'en_US.UTF-8' )
  File "C:\Program Files (x86)\Python36-32\lib\locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

--------
Here is what my system is set to:
>>> import locale
>>> locale.setlocale(locale.LC_ALL, '')
'English_United States.1252'

**Comment by s6s8** [comment]
For windows you have to edit the file:
instapy\unfollow_util.py line 9
from:` locale.setlocale( locale.LC_ALL, 'en_US.UTF-8' )`
to: `locale.setlocale( locale.LC_ALL, 'English_United States.1252' )`

This error happen after last update.
