### ISSUE TITLE
Follow user followers - DOESN'T WORK

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#3672]
Hi everyone,

I'm trying to use the bot to **FOLLOW USER FOLLOWERS**.

This is the code:

""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = 'jonnysatta'
insta_password = '**********'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                    min_followers=45,
                                    min_following=77)

    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])

    # activity
    session.follow_user_followers(['pretovich7'], amount=25, randomize=False, sleep_delay=30)

This is the **ERROR MESSAGE** i receive everytime:

=========== RESTART: C:/Users/Luca Plastina/Desktop/quickstart.py ===========
ERROR [2019-01-03 14:09:03] [jonnysatta]  Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Traceback (most recent call last):
  File "C:\Users\Luca Plastina\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\Luca Plastina\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Luca Plastina\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Luca Plastina\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 117, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\Luca Plastina\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Luca Plastina\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Traceback (most recent call last):
  File "C:/Users/Luca Plastina/Desktop/quickstart.py", line 14, in <module>
    headless_browser=False)
  File "C:\Users\Luca Plastina\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 256, in __init__
    self.set_selenium_local_session()
  File "C:\Users\Luca Plastina\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 305, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.instapy.InstaPyError: ensure chromedriver is installed at C:\Users\Luca Plastina\AppData\Local\Programs\Python\Python37-32\lib\site-packages\assets\chromedriver
>>>

**Comment by EvraCloak** [comment]
Did you install chrome driver ? For to put it in the asselts folder.

**Comment by ghost** [comment]
I downloaded it and put in the "Asset" folder, however I never installed it.

Should I run "chromedriver.exe" file ?

Thank you in advance


Il giorno gio 3 gen 2019, 16:30 EvraCloak <notifications@github.com> ha
scritto:

**Comment by ghost** [comment]
resolved.

File.py always need to stay in the same folder (Instapy general) to work well.  if it's out (desktop for example) it doesn't fine chromedriver so don't work
