### ISSUE TITLE
Setup always fails with AttributeError / Fake-Useragent

### ISSUE THREAD

**Issue by imlukedewitt** [InstaPy/InstaPy#3686]
Hello, I'm trying to get started with InstaPy and am having trouble with setup. I followed the [Windows installation instructions](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Windows.md) up to step 3.1 and am getting the same error on setup.py, no matter what I try.

- Python 3.6.4 is installed and the path is set. Pip is up to date (18.1), and I can run Python scripts without problem
- Microsoft Build Tools 2015 is installed
- Microsoft Visual C++ 2017 Build Tools is installed. Do I need to uninstall and install the 2015 version?
- The Microsoft .NET Framework V.3.5 exe never opens an installer after gaining admin access, but I checked in RegEdit and it appears to already be installed
- I downloaded the latest version of Chrome Driver and placed the exe in the assets folder
- I've got an elevated powershell pointed at the root InstaPy folder

## Expected Behavior
Working installation
## Current Behavior
Running `python setup.py install` results in the following:

    Traceback (most recent call last):
    File "setup.py", line 3, in <module>
        from setuptools import setup
    File "c:\python36\lib\site-packages\setuptools\__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
    File "c:\python36\lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
    File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
        @_call_aside
    File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
    File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
    File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2577, in activate
        declare_namespace(pkg)
    File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
    File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
    File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

Running `pip install .` results in the same message. If I continue in the instructions and try to run quickstart.py, a window opens briefly and then disappears. Any help with this would be great appreciated!

Running the installer in CMD gives me an additional message at the bottom: 
`Command "python setup.py egg_info" failed with error code 1 in C:\Users\Luke\AppData\Local\Temp\pip-install-558weusi\fake-useragent\`

**Comment by imlukedewitt** [comment]
Update: I decided to try installing Instabot while I wait, and got the same error message

**Comment by imlukedewitt** [comment]
Update: found the solution [in this thread](https://github.com/googleapis/google-cloud-python/issues/3884)

Running `pip install --upgrade setuptools` fixed the issue.
