### ISSUE TITLE
Error after trying to follow users followers

### ISSUE THREAD

**Issue by jvbraganca** [InstaPy/InstaPy#3697]
Hi, I'm getting this error after trying to follow users followers:

`Traceback (most recent call last):
  File "quickstart.py", line 165, in <module>
    interact=True)
  File "/root/InstaPy/instapy/instapy.py", line 2839, in follow_user_followers
    self.logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 883, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 650, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}
  (Session info: headless chrome=70.0.3538.110)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-42-generic x86_64)`

Here it is my quickstart.py:

```python
import random
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = 'xxx'
insta_password = 'xxx'

"""
Prevent commenting on and unfollowing your good
friends (the images will still be liked)...
"""
friends = []

# Prevent posts that contain...
ignore_list = []
# TARGET data

# Set similar accounts and influencers from your niche to target...
# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs=True)
# let's go! :>
with smart_run(session):
    # HEY HO LETS GO
    # general settings

    # my account is small at the moment, so I keep smaller upper threshold
    # "server_calls",
    # peak_server_calls=(1500, 9000)
    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "follows"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(180, 2160),
                                 peak_follows=(55, 500),
                                 )
    session.set_simulation(enabled=True)

    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=-0.50,
                                    delimit_by_numbers=True,
                                    max_followers=7500,
                                    max_following=3000,
                                    min_followers=25,
                                    min_following=25,
                                    min_posts=3)
    session.set_skip_users(skip_private=True,
                           skip_no_profile_pic=True,
                           skip_business=True)
    session.set_user_interact(amount=2, randomize=True, percentage=80, media='Photo')
    session.set_do_like(enabled=True, percentage=90)
    session.set_do_follow(enabled=True, percentage=40, times=1)
    session.set_sleep_reduce(66)

#   activities
#   UNFOLLOW activity

#   Unfollow nonfollowers after one day...
    session.unfollow_users(amount=random.randint(75, 100),
                           InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=24 * 60 * 60, sleep_delay=300)
# Unfollow all users followed by InstaPy after three days to keep the
# following-level clean...
    session.unfollow_users(amount=random.randint(200, 500),
                           InstapyFollowed=(True, "all"), style="FIFO",
                           unfollow_after=72 * 60 * 60, sleep_delay=300)

#    FOLLOW+INTERACTION on TARGETED accounts
#   Select users form a list of a predefined targets...
    targets = [
    'xxx',
    'yyy',
    'zzz']
    number = random.randint(3, 5)
    random_targets = targets
    if len(targets) <= number:
        random_targets = targets
    else:
        random_targets = random.sample(targets, number)

#   Interact with the chosen targets...
    session.follow_user_followers(
        random_targets,
        amount=random.randint(30,60),
        randomize=True,
        sleep_delay=300,
        interact=True)
    session.interact_user_followers(
        random_targets,
        amount=10,
        randomize=True)
    session.follow_user_following(
        random_targets,
        amount=10,
        randomize=True,
        sleep_delay=60)
```

![Screenshot of terminal](https://i.imgur.com/UqJ68C5.png)

**Comment by ghost** [comment]
Having the same issue.. unable to run a simple "follow users followers" - just freezes at first user in list.

**Comment by Chenchela** [comment]
@anocai , @jvbraganca any update on this issue?
