### ISSUE TITLE
Chrome Driver Error on Raspbian

### ISSUE THREAD

**Issue by dyakimchuk** [InstaPy/InstaPy#3700]

**Comment by dyakimchuk** [comment]
Hello! Have an issue contacting the chrome driver.
After instalation according to manual: https://github.com/timgrossmann/InstaPy/commit/3915cd50b58c944acb73a11cf8548b392677cff8
On starting from virtual envirement (vanv36) i am getting error "ERROR [2019-01-08 17:55:57] [nowcallmecacao]  Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41,platform=Linux 4.14.58v7-aufs armv7l)
Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/instapy/browser.py", line 122, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/venv36/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/pi/venv36/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pi/venv36/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/venv36/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/venv36/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41,platform=Linux 4.14.58v7-aufs armv7l)

Traceback (most recent call last):
  File "quickstart.py", line 32, in <module>
    headless_browser=False)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 262, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 314, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/Projects/InstaPy/assets/chromedriver
"

If i am trying to start without VENV36 i am getting following error:
Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    from instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 12, in <module>
    from selenium import webdriver
ImportError: No module named selenium


Any ideas how to solve?
