### ISSUE TITLE
Problem with like and comment by tags 

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#3715]
python3 /Users/Edhim/Desktop/INSTAPY/Edhim/quickstart.py 

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-01-11 12:11:04] [djedhim]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

.............................................................
INFO [2019-01-11 12:11:11] [djedhim]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-01-11 12:11:11] [djedhim]  Saving account progress...
INFO [2019-01-11 12:11:14] [djedhim]  Tag [1/18]
INFO [2019-01-11 12:11:14] [djedhim]  --> b'milan'
INFO [2019-01-11 12:11:23] [djedhim]  desired amount: 8  |  top posts [disabled]: 9  |  possible posts: 16635627
INFO [2019-01-11 12:11:30] [djedhim]  [1/8]
INFO [2019-01-11 12:11:30] [djedhim]  https://www.instagram.com/p/BsfftKhl7zE/
ERROR [2019-01-11 12:11:33] [djedhim]  Pow! Error occurred while dumping record activity data to a local JSON:
	b'Expecting value: line 1 column 1 (char 0)'

INFO [2019-01-11 12:11:33] [djedhim]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 18 users & had 7188 FOLLOWERS
[Session lasted 31.67 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-01-11 12:11:33] [djedhim]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "/Users/Edhim/Desktop/INSTAPY/Edhim/quickstart.py", line 45, in <module>
    session.like_by_tags(['xxx', 'xxx', 'xxx'], amount=8, skip_top_posts=True)
  File "/Users/Edhim/Desktop/INSTAPY/Edhim/instapy/instapy.py", line 1674, in like_by_tags
    self.logger)
  File "/Users/Edhim/Desktop/INSTAPY/Edhim/instapy/like_util.py", line 537, in check_link
    ''', user_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 635, in execute_script
    'args': converted_args})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'edges' of undefined
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363),platform=Mac OS X 10.14.2 x86_64)

Any idea please @uluQulu 

Thank you

**Comment by jeromefaria** [comment]
I have the same problem that started to happen today, before and after pulling the latest changes from master.

```
Traceback (most recent call last):
  File "quickstart.py", line 29, in <module>
    session.like_by_tags(["natgeo"], amount=10)
  File "/Users/jeromefaria/code/github/InstaPy/instapy/instapy.py", line 1674, in like_by_tags
    self.logger)
  File "/Users/jeromefaria/code/github/InstaPy/instapy/like_util.py", line 537, in check_link
    ''', user_name)
  File "/Users/jeromefaria/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py",
 line 636, in execute_script
    'args': converted_args})['value']
  File "/Users/jeromefaria/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py",
 line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/jeromefaria/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.p
y", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'edges' of undefine
d
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.14.2 x
86_64)
```

**Comment by cdp181** [comment]
Duplicate of #3712

**Comment by brocool** [comment]
same problem

**Comment by brocool** [comment]
the solution is in #3712
