### ISSUE TITLE
Failed to scroll using 'follow_user_followers' "element is not attached to the page document"

### ISSUE THREAD

**Issue by jtrieuDev** [InstaPy/InstaPy#3736]
Hi, there is a problem with the scrolling using the function "follow_user_followers", this is the error I have
It crashes right after the script is executed and try to scroll
```
  File "follow.py", line 49, in <module>
    session.follow_user_followers(['user'], amount=1500, randomize=False)
  File "/Users/user/Desktop/instagram/InstaPy/instapy/instapy.py", line 3048, in follow_user_followers
    self.logfolder)
  File "/Users/user/Desktop/instagram/InstaPy/instapy/unfollow_util.py", line 998, in get_given_user_followers
    logger, logfolder)
  File "/Users/user/Desktop/instagram/InstaPy/instapy/unfollow_util.py", line 745, in get_users_through_dialog
    scroll_to_bottom_of_followers_list(browser, dialog)
  File "/Users/user/Desktop/instagram/InstaPy/instapy/unfollow_util.py", line 707, in scroll_to_bottom_of_followers_list
    "arguments[0].children[1].scrollIntoView()", element)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
```

Code I am using =>

```
    session.login()
    session.set_relationship_bounds(enabled=True,
				  delimit_by_numbers=True,
				   max_followers=4000,
				    max_following=5000,
				     min_followers=45,
				      min_following=70)

    session.set_simulation(enabled=False)
    session.follow_user_followers(['user'], amount=1500, randomize=False)
```

**Comment by henry0666** [comment]
same

**Comment by Tachenz** [comment]
Got this one as well, something changed within Instagram...

**Comment by jasonbleasdell** [comment]
Yea I believe something has changed. The code just needs to be updated to reflect this issue. An error also occurs for creating a list for unfollowing as well.

**Comment by BukanPawkemon** [comment]
I'm also facing the same problem

Here is my log

> Traceback (most recent call last):
  File "quickstart.py", line 44, in <module>
    interact=True, sleep_delay=240)
  File "C:\Users\HP\Documents\GitHub\InstaPy\instapy\instapy.py", line 3048, in follow_user_followers
    self.logfolder)
  File "C:\Users\HP\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 998, in get_given_user_followers
    logger, logfolder)
  File "C:\Users\HP\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 819, in get_users_through_dialog
    person_list = dialog_username_extractor(buttons)
  File "C:\Users\HP\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 843, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "C:\Users\HP\Envs\BotInstaPy\lib\site-packages\selenium-3.141.0-py3.7.egg\selenium\webdriver\remote\webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "C:\Users\HP\Envs\BotInstaPy\lib\site-packages\selenium-3.141.0-py3.7.egg\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\HP\Envs\BotInstaPy\lib\site-packages\selenium-3.141.0-py3.7.egg\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\HP\Envs\BotInstaPy\lib\site-packages\selenium-3.141.0-py3.7.egg\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.17134 x86_64)

**Comment by Tr1pke** [comment]
Facing the same issue

**Comment by botpadawan** [comment]
same here

**Comment by bobbyjer** [comment]
same

**Comment by tomijunior** [comment]
this is my quick fix for DOM change issue in follow dialog.

in file unfollow_util.py
def get_users_through_dialog   

change  
    dialog_address = "//div[@role='dialog']"

def scroll_to_bottom_of_followers_list
change
     browser.execute_script(
        "arguments[0].children[1].children[1].scrollIntoView()", element)

def dialog_username_extractor
change
                  try:
                person_list.append(person.find_element_by_xpath("./../..")
                                   .find_elements_by_tag_name("a")[1].text)

file util.py
def scroll_bottom
change
 browser.execute_script(
            "arguments[0].children[1].scrollTop = arguments[0].children[1].scrollHeight", element)

Hope this can help.

**Comment by Tr1pke** [comment]
if i change that i get a loop and quit

**Comment by Ugar93** [comment]
+1

**Comment by Tachenz** [comment]
Yep, gets into the loop for me as well

**Comment by marcosgb** [comment]
same here

**Comment by syond** [comment]
same

**Comment by mortezahei** [comment]
mute the thread

Sent from Yahoo Mail on Android 
 
  On یکشنبه, ژانویهٔ ۲۰, ۲۰۱۹ at ۱۹:۰۵, syond<notifications@github.com> wrote:   
same

**Comment by wisdomtheif** [comment]
Same issue :(

**Comment by andreescocard** [comment]
https://github.com/timgrossmann/InstaPy/issues/3902
