### ISSUE TITLE
today not work....

### ISSUE THREAD

**Issue by TheXeon81** [InstaPy/InstaPy#374]
This is the error:

C:\InstaPy>py quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    session.login()
  File "C:\InstaPy\instapy\instapy.py", line 83, in login
    if not login_user(self.browser, self.username, self.password):
  File "C:\InstaPy\instapy\login_util.py", line 29, in login_user
    sleep(2)
  File "C:\InstaPy\instapy\time_util.py", line 22, in sleep
    original_sleep(randomize_time(t))
  File "C:\InstaPy\instapy\time_util.py", line 16, in randomize_time
    t = gauss(mean, stdev)
  File "C:\Programs\Python\Python36-32\lib\random.py", line 603, in gauss
    g2rad = _sqrt(-2.0 * _log(1.0 - random()))
ValueError: math domain error

**Comment by TheXeon81** [comment]
C:\Users\lucia\OneDrive\Watermark\InstaPy>py quickstart.py
Logged in successfully!
Number of people followed automatically remaining: 171
following_link error
 Message: unknown error: Element <li class="_218yx">...</li> is not clickable at point (598, 204). Other element would receive the click: <span class="_bkw5z" title="...">174</span>
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.16232 x86_64)

Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session.unfollow_users(amount=59)
  File "C:\Users\lucia\OneDrive\Watermark\InstaPy\instapy\instapy.py", line 486, in unfollow_users
    unfollowNumber = unfollow(self.browser, self.username, amount, self.dont_include, onlyInstapyFollowed, self.automatedFollowedPool)
  File "C:\Users\lucia\OneDrive\Watermark\InstaPy\instapy\unfollow_util.py", line 51, in unfollow
    dialog = browser.find_element_by_xpath('/html/body/div[2]/div/div[2]/div/div[2]')
  File "C:\Users\lucia\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\lucia\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Users\lucia\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Users\lucia\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[2]/div/div[2]/div/div[2]"}
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.16232 x86_64)

**Comment by TheXeon81** [comment]
the problem is in the file ./logs/******_followedPool.csv!!!!

1. I opened the file
2. Deleted its contents
3. restart instapy and now work!

**Comment by TheXeon81** [comment]
after 2 minute .... ko! With the same error :-(
