### ISSUE TITLE
[New Issue] Multi Account- Error Selenium 

### ISSUE THREAD

**Issue by HCWcoder** [InstaPy/InstaPy#3748]
@timgrossmann 
@uluQulu 
@sionking 

Everything was working fine 
Lately only 1 account can run Headless mode and the 2 other account giving same error even on 2 different laptops that was running so fine
![error](https://user-images.githubusercontent.com/9588426/51239240-82f3c480-1981-11e9-866c-a6e1b27dfcd6.PNG)

```
INFO [2019-01-16 12:17:34] [UserQuickstart]  User 'TargetedUser' [1/3]
Traceback (most recent call last):
  File "C:\Users\testing\Documents\GitHub\InstaPy\UserQuickstart.py", line 67, in follow
    session.follow_user_followers(my_competitors, amount=random.randint(50,100), randomize=True, sleep_delay=180, interact=True)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\instapy.py", line 3048, in follow_user_followers
    self.logfolder)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 998, in get_given_user_followers
    logger, logfolder)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 747, in get_users_through_dialog
    buttons = get_buttons_from_dialog(dialog, channel)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 1365, in get_buttons_from_dialog
    "//button[text()='Follow']")
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 381, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 680, in find_elements
    {"using": by, "value": value})['value']
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)
```

Thanks.

**Comment by HCWcoder** [comment]
account 1 still working good without errors

Account 2 restarted : Failed to load desired amount of users but grabbed only 31!
its started with them then when it will go for another Profile to target and get the new amount of followers : 

```
INFO [2019-01-16 12:30:04] [user]  Ongoing Follow [30/31]: now following 'elegant_towel'...
INFO [2019-01-16 12:30:09] [user]  User: 'elegant_towel'  |> followers: 352  |> following: 658  |> relationship ratio: 0.53
INFO [2019-01-16 12:30:10] [user]  --> Followed 'b'elegant_towel''!
INFO [2019-01-16 12:30:16] [user]  Follow per user: 2  |  Total Follow: 2

INFO [2019-01-16 12:30:16] [user]  Ongoing Follow [31/31]: now following 'glamdust_byangela'...
INFO [2019-01-16 12:30:19] [user]  User: 'glamdust_byangela'  |> followers: 35  |> following: 1  |> relationship ratio: 35.0
INFO [2019-01-16 12:30:19] [user]  User 'glamdust_byangela's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 12:30:19] [user]  User 'user1' [2/3]
Traceback (most recent call last):
  File "C:\Users\testing\Documents\GitHub\InstaPy\User.py", line 67, in follow
    session.follow_user_followers(my_competitors, amount=random.randint(50,100), randomize=True, sleep_delay=180, interact=True)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\instapy.py", line 3048, in follow_user_followers
    self.logfolder)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 998, in get_given_user_followers
    logger, logfolder)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 747, in get_users_through_dialog
    buttons = get_buttons_from_dialog(dialog, channel)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 1365, in get_buttons_from_dialog
    "//button[text()='Follow']")
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 381, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 680, in find_elements
    {"using": by, "value": value})['value']
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)
```


Instapy Quickstart 👍 
```
try:
        session.login()
        session.set_relationship_bounds(enabled=True,
                         potency_ratio=None,
                          delimit_by_numbers=True,
                           max_followers=15000,
                            max_following=6500,
                             min_followers=56,
                              min_following=56,
                               min_posts=5,
                                max_posts=1500)
        session.set_skip_users(skip_private=False,
                               private_percentage=100,
                               skip_no_profile_pic=True,
                               no_profile_pic_percentage=100,
                               skip_business=True,
                               business_percentage=100)

        session.set_do_follow(enabled=True, percentage=100, times=2)
        session.set_do_comment(enabled=False, percentage=35)
        session.set_do_like(True, percentage=100)
        session.set_delimit_liking(enabled=True, max=100, min=0)
        session.set_delimit_commenting(enabled=True, max=20, min=0)
        session.set_simulation(enabled=False)


        #ACtions----------------------------------------------------------------------/////////////////////////////////////////////////////////////////////////////
        session.follow_user_followers(my_competitors, amount=random.randint(50,100), randomize=True, sleep_delay=180, interact=True)
        session.set_do_follow(enabled=False, percentage=100, times=2)
        session.like_by_tags(like_tag_lists, amount=random.randint(30,100))
except:
        import traceback
        print(traceback.format_exc())
```

**Comment by Tr1pke** [comment]
most of us have the same problem, instagram probably changed something in their layout

**Comment by HCWcoder** [comment]
> most of us have the same problem, instagram probably changed something in their layout

ah okey thanks alot for the update ! @Tr1pke 
 have a nice day
