### ISSUE TITLE
interact_users_followers ( quit working )

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#3755]
```
Traceback (most recent call last):
  File "quickstart.py", line 55, in <module>
    session.interact_user_followers(['ig1', 'ig2', 'ig3', 'ig4'], amount=1200, randomize=True)
  File "/home/ubuntu/newbot3/instapy/instapy.py", line 2715, in interact_user_followers
    self.logfolder)
  File "/home/ubuntu/newbot3/instapy/unfollow_util.py", line 1007, in get_given_user_followers
    logger, logfolder)
  File "/home/ubuntu/newbot3/instapy/unfollow_util.py", line 828, in get_users_through_dialog
    person_list = dialog_username_extractor(buttons)
  File "/home/ubuntu/newbot3/instapy/unfollow_util.py", line 852, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "/usr/local/lib/python3.6/dist-packages/selenium-3.141.0-py3.6.egg/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium-3.141.0-py3.6.egg/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium-3.141.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium-3.141.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=70.0.3538.67)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-1031-aws x86_64)
```

**Comment by c0d3x27** [comment]
i had been having this problem since yesterday

**Comment by haydenrear** [comment]
I think that they changed it so that you have to press a button "see all suggestions" at the bottom of the few followers you are able to view in order to open a new window to be able to see all of the followers of that person. It used to be that if you just scrolled down they would keep loading (infinite scrolling).

**Comment by marcosgb** [comment]
I have the same problem! This error: selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button class="Z4IfV _0mzm- sqdOP yWX7d        " type="button" disabled="">...</button> is not clickable at point (640, 209). Other element would receive the click: <li class="lnrre">...</li>

**Comment by c0d3x27** [comment]
> I think that they changed it so that you have to press a button "see all suggestions" at the bottom of the few followers you are able to view in order to open a new window to be able to see all of the followers of that person. It used to be that if you just scrolled down they would keep loading (infinite scrolling).

wtf?! these people are always just fucking it up for us
