### ISSUE TITLE
Follow by Commenters not working

### ISSUE THREAD

**Issue by AdamMoffitt** [InstaPy/InstaPy#3757]
Follow by commenters is not working.

Here is my code:

# FOLLOW COMMENTERS
    session.set_user_interact(amount=3,percentage=100,randomize=True,media='Photo')
    session.set_relationship_bounds(enabled=False)   ##FROM now on, verification based on relationship bounds, is disabled
    session.set_do_like(enabled=True, percentage=100)
    session.follow_commenters(['zaralarsson'], amount=1000, daysold=30, max_pic = 15, sleep_delay=600, interact=True)

Here is the error i get: Traceback (most recent call last):
  File "Tiffany.py", line 44, in <module>
    # session.follow_commenters(['zaralarsson'], amount=1000, daysold=30, max_pic = 15, sleep_delay=600, interact=True)
  File "/Users/adammoffitt/Desktop/InstaPy/InstaPy/instapy/instapy.py", line 715, in follow_commenters
    max_pic)
  File "/Users/adammoffitt/Desktop/InstaPy/InstaPy/instapy/commenters_util.py", line 235, in extract_information
    user_commented_list, pic_date_time = extract_post_info(browser)
  File "/Users/adammoffitt/Desktop/InstaPy/InstaPy/instapy/commenters_util.py", line 55, in extract_post_info
    comments = comment_list.find_elements_by_tag_name('li')
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 320, in find_elements_by_tag_name
    return self.find_elements(by=By.TAG_NAME, value=name)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 685, in find_elements
    {"using": by, "value": value})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.13.6 x86_64)

**Comment by nbgabriel** [comment]
Same here.

**Comment by tolgaada** [comment]
Same

**Comment by hddeus** [comment]
same @timgrossmann @AdamMoffitt @nbgabriel @tolgaada @SathyaBhat @AlainPilon

**Comment by hddeus** [comment]
@calvinclaus @rzfzr @AlainPilon @

**Comment by AlainPilon** [comment]
Cant look at it right now, but quick guess based on the error would be that the page structure changed and Selenium cant find the dom element anymore.

**Comment by DanielLuu** [comment]
Hi I'm no longer getting an error but the script can't find comments
