### ISSUE TITLE
[NEW] Script stops running, because of Chrome?

### ISSUE THREAD

**Issue by nobodysguilthub** [InstaPy/InstaPy#3762]
So I run the script, and something happens. See below:

DevTools listening on ws://127.0.0.1:64704/devtools/browser/ef6dc1ff-bef2-4d6a-bc5c-e7e998fcf786

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-01-17 11:44:30] [baby_mansion]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...

..................................................................
INFO [2019-01-17 11:45:01] [baby_mansion]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-01-17 11:45:01] [baby_mansion]  Saving account progress...
INFO [2019-01-17 11:45:04] [baby_mansion]  User 'dearestdaughters' [1/2]

Then it does nothing, but in google chrome it says:
"Aw snap! Something went wrong while displaying this webpage."

**Comment by alxlion** [comment]
Duplicate: https://github.com/timgrossmann/InstaPy/issues/3760

**Comment by AyuntamientoToledo** [comment]
Same

**Comment by zumacaya** [comment]
Same here... any solution please? 👍

**Comment by Tr1pke** [comment]
my new error:
python3 tests.steven.ig.py 

ERROR [2019-01-17 18:55:34] [steven.ig]  Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.18.0-13-generic x86_64)
Traceback (most recent call last):
  File "/home/steven/InstaPy/instapy/browser.py", line 122, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.18.0-13-generic x86_64)

Traceback (most recent call last):
  File "tests.steven.ig.py", line 11, in <module>
    headless_browser=False)
  File "/home/steven/InstaPy/instapy/instapy.py", line 263, in __init__
    self.set_selenium_local_session()
  File "/home/steven/InstaPy/instapy/instapy.py", line 315, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/steven/InstaPy/assets/chromedriver

**Comment by nobodysguilthub** [comment]
> Duplicate: #3760

It's not duplicate, I don't get any errors.
