### ISSUE TITLE
Instapy crashes: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by stefanosambruna** [InstaPy/InstaPy#3770]
Hi everyone, 
Instapy works perfectly but at lest once a week it crashes and I noticed this message error in the log. 

```
ERROR [2019-01-15 20:02:06] [username]  Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.4.0-1074-aws x86_64)
Traceback (most recent call last):
  File "/home/ubuntu/InstaPy/instapy/browser.py", line 122, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.4.0-1074-aws x86_64)
```

**Comment by webdevandeverythingelse** [comment]
Hey @ste23s, any updates? Struggling with the same issue on Windows 64-bit OS here.

It's only recently this started happening, past couple weeks. It's very strange, because when I toggle the "headless browser" option to True, it'll work for a couple runs. Then it'll fail, I'll switch back to False, it'll work a couple times, then fail... repeat.

I should mention I also run this through windows task scheduler, but haven't had any problem for months until this.

`Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "C:\Users\brb72\Documents\GitHub\insta\instapy\browser.py", line 122, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\brb72\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\brb72\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\brb72\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\brb72\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "C:\Users\brb72\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 6.1.7601 SP1 x86_64)`

**Comment by webdevandeverythingelse** [comment]
Figured this out - it was the update to the Chrome Driver. I was only getting this issue when run via the Windows Task Scheduler, but it would run fine manually (headless and not).

Downgrading from 2,45 to 2.44 fixed it: https://chromedriver.storage.googleapis.com/index.html?path=2.44/

Hope this helps someone else!
