### ISSUE TITLE
Starting with a fresh install on Ubuntu

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#3775]
## Expected Behavior
Installed from the Ubuntu [guide ](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md)on here normally it works fine, set headless browser to true and nogui to true as well. 

## Current Behavior

Try to run quickstart get this:

```
sudo python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/home/ubuntu/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 12, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
```

I've done the `pip install selenium` but then it asks for another module, then another.. Any ideas?

**Comment by ghost** [comment]
This resolved it for me, FYI 
#3591 
https://github.com/timgrossmann/InstaPy/issues/3591#issuecomment-449861676
