### ISSUE TITLE
Session started!->Logged in successfully!->collect smart hashtags->Using smart hashtags->Session ended!->no result

### ISSUE THREAD

**Issue by ghanimkhan** [InstaPy/InstaPy#3777]
Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooTraceback (most recent call last):

  File "/home/kingkhan05/Desktop/lol/InstaPy/quickstart2.py", line 38, in <module>
    session.like_by_tags(amount=100, use_smart_hashtags=True)
  File "/home/kingkhan05/Desktop/lol/InstaPy/instapy/instapy.py", line 1517, in like_by_tags
    self.logger)
  File "/home/kingkhan05/Desktop/lol/InstaPy/instapy/like_util.py", line 469, in check_link
    ''', user_name)
  File "/home/kingkhan05/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/kingkhan05/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/kingkhan05/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'edges' of undefined
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-42-generic x86_64)

[Finished in 100.2s with exit code 1]
[shell_cmd: python -u "/home/kingkhan05/Desktop/lol/InstaPy/quickstart2.py"]
[dir: /home/kingkhan05/Desktop/lol/InstaPy]
[path: /home/kingkhan05/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games]

**Comment by ghanimkhan** [comment]
![screenshot from 2019-01-19 14-00-11](https://user-images.githubusercontent.com/30781223/51424363-90fc4c00-1bf2-11e9-8162-551db6aba1bc.png)
![screenshot from 2019-01-19 13-58-52](https://user-images.githubusercontent.com/30781223/51424369-9a85b400-1bf2-11e9-97be-8bfa826db069.png)

**Comment by ghanimkhan** [comment]
please help me with this error the script is running completely fine on other 4 accounts but not working on this one please help me out....cant find the issue

**Comment by ghanimkhan** [comment]
no result found
