### ISSUE TITLE
Running InstaPy on AWS EC2

### ISSUE THREAD

**Issue by rishkebab** [InstaPy/InstaPy#3853]
Hey, does anyone have any advice or pointers on how to set up InstaPy on AWS EC2?

I have cloned the git repo and successfully installed all required packages for InstaPy to run.

I have also installed chromedriver and Google Chrome on the EC2 instance, however, when I try to run any scripts, I am faced with the following errors:

ERROR [2019-01-31 01:34:06] [pets.urbanfreedom]  Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.14.77-70.59.amzn1.x86_64 x86_64)
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.6/site-packages/instapy/browser.py", line 122, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.14.77-70.59.amzn1.x86_64 x86_64)

Traceback (most recent call last):
  File "unf.py", line 14, in <module>
    password=insta_password)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/instapy/instapy.py", line 263, in __init__
    self.set_selenium_local_session()
  File "/home/ec2-user/.local/lib/python3.6/site-packages/instapy/instapy.py", line 315, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/ec2-user/.local/lib/python3.6/site-packages/assets/chromedriver

**Comment by AdamMoffitt** [comment]
Did you solve this? curious to know the answer

**Comment by rishkebab** [comment]
> Did you solve this? curious to know the answer

Yep, using this sort of code to create the session allowed me to run it on an EC2 instance:

```
session = InstaPy(username="your username",
                      password="your password",
                      headless_browser=True, multi_logs=True) 
```
