### ISSUE TITLE
Grabbed 0 usernames - session ended

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#3890]
Got a recent isseu, it doenst happen all the time just 1 out of 3

i got this:

INFO [2019-02-04 20:29:36] [MyInstaAccount]  Grabbed 0 usernames from 'Randstadbe's `Followers` to do following

INFO [2019-02-04 20:29:36] [MyInstaAccount]  User 'brussels.sprout' [2/5]

INFO [2019-02-04 20:29:43] [MyInstaAccount]  Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> LIKED 0 comments
        |> REPLIED to 0 comments
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0

On session start was FOLLOWING 968 users & had 1976 FOLLOWERS
[Session lasted 0.1 hours]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-02-04 20:29:43] [MyInstaAccount]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "InstaPy/MyInstaAccount-follow-unfollow.py", line 25, in <module>
    session.follow_user_followers(['Randstadbe','brussels.sprout','digitalwallonia','startlab.be','cirb_cibg'], amount=40, randomize=True, interact=False)
  File "/home/steven/InstaPy/instapy/instapy.py", line 3048, in follow_user_followers
    self.logfolder)
  File "/home/steven/InstaPy/instapy/unfollow_util.py", line 998, in get_given_user_followers
    logger, logfolder)
  File "/home/steven/InstaPy/instapy/unfollow_util.py", line 745, in get_users_through_dialog
    scroll_to_bottom_of_followers_list(browser, dialog)
  File "/home/steven/InstaPy/instapy/unfollow_util.py", line 707, in scroll_to_bottom_of_followers_list
    "arguments[0].children[1].scrollIntoView()", element)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'scrollIntoView' of undefined
  (Session info: headless chrome=72.0.3626.81)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.18.0-13-generic x86_64)

There is a screen on:
        10066.MyInstaAccount     (04/02/19 19:19:20)     (Detached)
1 Socket in /run/screen/S-steven.
steven@ST-Meise:~$ 

I use this MyInstaAccount.py for months now.
and it started since a couple of days to fail.

**Comment by Tr1pke** [comment]
I updated the whole Instapy/instapy folder and now i got this:

Traceback (most recent call last):
  File "InstaPy/MyInstagramAcc-follow-unfollow.py", line 1, in <module>
    from instapy import InstaPy
  File "/home/steven/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/steven/InstaPy/instapy/instapy.py", line 71, in <module>
    from .browser import set_selenium_local_session
  File "/home/steven/InstaPy/instapy/browser.py", line 16, in <module>
    from .file_manager import get_chromedriver_location
  File "/home/steven/InstaPy/instapy/file_manager.py", line 11, in <module>
    from instapy_chromedriver import binary_path
ModuleNotFoundError: No module named 'instapy_chromedriver'
There is a screen on:
        16095.MyInstagramAcc  (04/02/19 21:29:20)     (Detached)
1 Socket in /run/screen/S-steven.

Trying a fresh install now

**Comment by JakeShore98** [comment]
keep me updated, I am having the same issue. Any way you can walk me through how to fix it step by step if you figure it out?

**Comment by Tr1pke** [comment]
> keep me updated, I am having the same issue. Any way you can walk me through how to fix it step by step if you figure it out?

Sure, since when do you have it?

**Comment by JakeShore98** [comment]
i started using instapy around 2 weeks ago, just started having this issue around an hour ago
I do not have much coding experience

**Comment by Tr1pke** [comment]
a **_FRESH_** install gave me this:

Traceback (most recent call last):
  File "InstaPy/MYINSTAGRAMACCOUNT-follow-unfollow.py", line 23, in <module>
    session.follow_user_followers(['dogs.lovers','dogs','dogsofinstagram','dogsofinstaworld'], amount=40, randomize=True, interact=False)
  File "/home/steven/InstaPy/instapy/instapy.py", line 3068, in follow_user_followers
    self.logfolder)
  File "/home/steven/InstaPy/instapy/unfollow_util.py", line 998, in get_given_user_followers
    logger, logfolder)
  File "/home/steven/InstaPy/instapy/unfollow_util.py", line 745, in get_users_through_dialog
    scroll_to_bottom_of_followers_list(browser, dialog)
  File "/home/steven/InstaPy/instapy/unfollow_util.py", line 707, in scroll_to_bottom_of_followers_list
    "arguments[0].children[1].scrollIntoView()", element)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'scrollIntoView' of undefined
  (Session info: headless chrome=72.0.3626.81)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.18.0-13-generic x86_64)

**Comment by gitpatrickhub** [comment]
I had to comment out the below line in the file_manager.py file after the latest git pull;

```
from instapy_chromedriver import binary_path
```
I use firefox headless on Raspberry Pi3 and have similar error reported here

```
File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 2735, in interact_user_followers
    self.logfolder)
  File "/home/pi/Projects/InstaPy/instapy/unfollow_util.py", line 998, in get_given_user_followers
    logger, logfolder)
  File "/home/pi/Projects/InstaPy/instapy/unfollow_util.py", line 745, in get_users_through_dialog
    scroll_to_bottom_of_followers_list(browser, dialog)
  File "/home/pi/Projects/InstaPy/instapy/unfollow_util.py", line 707, in scroll_to_bottom_of_followers_list
    "arguments[0].children[1].scrollIntoView()", element)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: arguments[0].children[1] is undefined
```

**Comment by gitpatrickhub** [comment]
Latest merge #3893 has fixed this error

**Comment by JakeShore98** [comment]
@gitpatrickhub how do i get the latest merge? thanks!!!

**Comment by xRyul** [comment]
> @gitpatrickhub how do i get the latest merge? thanks!!!

hey, I had same problem changing Line 740 in instaPy/instapy/unfollow_util.py fixed it for me:  

Change this: 

-`dialog_address = "//body/div[2]/div/div/div[2]"`

with

+ `dialog_address = "//body/div[2]/div"`

The anwser can be found here:
https://github.com/timgrossmann/InstaPy/pull/3893/files

**Comment by gitpatrickhub** [comment]
@jakeshore98 from the command line;
```
git pull
```
That will merge the latest branch of code.

**Comment by Tr1pke** [comment]
works again:

sudo pip install instapy -U

**Comment by tE3m** [comment]
@gitpatrickhub that won't work with the new installation anymore. Updating happens with 
```
pip install instapy -U
```
from now on.

**Comment by Tr1pke** [comment]
It only works on one server. Second server keeps failing. Even after a fresh install
