### ISSUE TITLE
Issue with unfollow script

### ISSUE THREAD

**Issue by gyrex** [InstaPy/InstaPy#3897]
I git pulled the latest version of InstaPy (it was working perfectly yesterday with a pull from a week ago) and now the unfollow script doesn't work:

```
Traceback (most recent call last):
  File "/home/john/InstaPy/parky-au_unfollow.py", line 2, in <module>
    from instapy import InstaPy
  File "/home/john/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/john/InstaPy/instapy/instapy.py", line 71, in <module>
    from .browser import set_selenium_local_session
  File "/home/john/InstaPy/instapy/browser.py", line 16, in <module>
    from .file_manager import get_chromedriver_location
  File "/home/john/InstaPy/instapy/file_manager.py", line 11, in <module>
    from instapy_chromedriver import binary_path
ImportError: No module named instapy_chromedriver
```

InstaPy script:

```
# imports
from instapy import InstaPy
from instapy.util import smart_run
from random import sample
```

**Comment by gyrex** [comment]
Issue related to #3891

**Comment by greggjaskiewicz** [comment]
Is it tho? The other issue is to do with asset folder. 
The problem I am having is that at some point, I have updated to the latest git head - and I got this error all of the sudden. What's changed?
