### ISSUE TITLE
Fresh install fails

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#3913]
i just installed ubuntu and i did this:
apt install python python-pip -y
pip install instapy
FAIL then i did
apt install python python-pip3
pip3 install instapy

now:

python3.6 steven.triathlon-follow-unfollow.py 

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
No any custom workspace provided.	~using existing..

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/steven/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-02-05 19:58:08] [steven.triathlon]  Using built in instapy-chromedriver executable (version 2.44)
ERROR [2019-02-05 19:58:09] [steven.triathlon]  Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.18.0-14-generic x86_64)
Traceback (most recent call last):
  File "/home/steven/.local/lib/python3.6/site-packages/instapy/browser.py", line 123, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/steven/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/steven/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/steven/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/steven/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/steven/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.18.0-14-generic x86_64)

Traceback (most recent call last):
  File "steven.triathlon-follow-unfollow.py", line 13, in <module>
    headless_browser=True)
  File "/home/steven/.local/lib/python3.6/site-packages/instapy/instapy.py", line 276, in __init__
    self.set_selenium_local_session()
  File "/home/steven/.local/lib/python3.6/site-packages/instapy/instapy.py", line 328, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /home/steven/.local/lib/python3.6/site-packages/instapy_chromedriver/chromedriver_linux64
steven@srv-purple:~/InstaPy$ reboot

**Comment by Tr1pke** [comment]
i restart and it worked, now i get this:

steven@srv-purple:~/InstaPy$ python3 steven.triathlon-follow-unfollow.py 
Traceback (most recent call last):
  File "steven.triathlon-follow-unfollow.py", line 1, in <module>
    from instapy import InstaPy
ModuleNotFoundError: No module named 'instapy'
steven@srv-purple:~/InstaPy$

**Comment by ishandutta2007** [comment]
already tracked here https://github.com/timgrossmann/InstaPy/issues/3895
