### ISSUE TITLE
InstaPy crashes when loading user followers

### ISSUE THREAD

**Issue by GuillaumeQuerso** [InstaPy/InstaPy#3914]
Basically, InstaPy cannot load the followers of a user when using the function: **follow_user_followers**. 
The issue is caused by an html change in the Instagram web page. 

My Traceback:
Traceback (most recent call last):
  File "basic_follow-unfollow_activity.py", line 57, in <module>
    session.follow_user_followers(['user1', 'user2'], amount=300, randomize=False, interact=True, sleep_delay=60)
  File "/path/to/InstaPy/instapy/instapy.py", line 3048, in follow_user_followers
    self.logfolder)
  File "/path/to/instapy/InstaPy/instapy/unfollow_util.py", line 998, in get_given_user_followers
    logger, logfolder)
  File "/path/to/instapy/InstaPy/instapy/unfollow_util.py", line 745, in get_users_through_dialog
    scroll_to_bottom_of_followers_list(browser, dialog)
  File "/path/to/instapy/InstaPy/instapy/unfollow_util.py", line 707, in scroll_to_bottom_of_followers_list
    "arguments[0].children[1].scrollIntoView()", element)
  File "/path/to/instapy/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/path/to/instapy/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/path/to/instapy/InstaPy/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'scrollIntoView' of undefined

You can solve the issue by changing in the file **unfollow_util.py**:
**line 740** `dialog_address = "//body/div[2]/div/div/div[2]"`
into `dialog_address = "/html/body/div[2]/div"`

**Comment by ishandutta2007** [comment]
already tracked here https://github.com/timgrossmann/InstaPy/issues/3896
