### ISSUE TITLE
Quick Start fails on Ubuntu Desktop

### ISSUE THREAD

**Issue by quanta-kt** [InstaPy/InstaPy#3923]
Fresh installed InstaPy. Seemed to work fine at first.
It redirects to my own account profile and crashes in some seconds
Here is the complete output which it thew to my console

P.S: I'm using Python 3.6 on Kubuntu which is Plasma 5/KDE flavor of Ubuntu

` ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/abhijeet/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-02-06 21:03:32] [abhijeet.nkt]  Using built in instapy-chromedriver executable (version 2.44)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-02-06 21:03:34] [abhijeet.nkt]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

..................................................................
INFO [2019-02-06 21:04:26] [abhijeet.nkt]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-02-06 21:04:26] [abhijeet.nkt]  Saving account progress...

INFO [2019-02-06 21:04:34] [abhijeet.nkt]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 74 users & had 222 FOLLOWERS
[Session lasted 1.02 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-02-06 21:04:34] [abhijeet.nkt]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2019-02-06 21:04:34] [abhijeet.nkt]  Tag [1/5]
INFO [2019-02-06 21:04:34] [abhijeet.nkt]  --> b'programming'
Traceback (most recent call last):
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fcb7959b048>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./igauto.py", line 31, in <module>
    session.like_by_tags(["programming", "linux", "physics", "science", "astronomy"], amount=15)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/instapy/instapy.py", line 1659, in like_by_tags
    self.logger)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/instapy/like_util.py", line 233, in get_links_for_tag
    web_address_navigator(browser, tag_link)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/instapy/util.py", line 1008, in web_address_navigator
    current_url = get_current_url(browser)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/instapy/util.py", line 1541, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/home/abhijeet/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/abhijeet/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/abhijeet/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=45895): Max retries exceeded with url: /session/81bb14967719d3b2c1f206f14cc0fa87/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb7959b048>: Failed to establish a new connection: [Errno 111] Connection refused',))`

**Comment by DemOnJR** [comment]
1. check for updates: chrome, webdriver, python & libs.
2. try ubuntu desktop, with the default python just install instapy and run quickstart.py for me working fine.
