### ISSUE TITLE
ImportError: No module named ordered_dict

### ISSUE THREAD

**Issue by WSADKeysGaming** [InstaPy/InstaPy#3953]
## Expected Behavior
start instapy with quickstart.py
## Current Behavior
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/usr/local/lib/python2.7/dist-packages/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/usr/local/lib/python2.7/dist-packages/instapy/instapy.py", line 11, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 92, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict

## InstaPy configuration

""" Quickstart script for InstaPy usage ""
from instapy import InstaPy
from instapy import smart_run
insta_username = 'censored'
insta_password = 'censored'
set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=false)
session.like_by_feed(amount=100, randomize=True, unfollow=false, interact=True)

**Comment by tE3m** [comment]
Do you intentionally use python2.7?

**Comment by antwal** [comment]
use python >= 3.5

**Comment by WSADKeysGaming** [comment]
Didn't even notice. Thanks

**Comment by tE3m** [comment]
Did that fix it? If so, please close the issue.
