### ISSUE TITLE
Issue with running script

### ISSUE THREAD

**Issue by samajami** [InstaPy/InstaPy#3978]
Unable to make a stable script that can run 24/7..

Can someone please share some basic working scrip, I tried few from templates but have some issues.
Mass follow and unfollow just follows like 100 people in 24 hours etc..

**Comment by tE3m** [comment]
Please provide more information. Noone is able to debug if you say
> *but have some issues.*

**Comment by samajami** [comment]
# imports
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace
import random

# login credentials
insta_username = 'xxx'
insta_password = 'xxx'


# set workspace folder at desired location (default is at your home folder)
set_workspace(path=None)

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

with smart_run(session):
    """ Activity flow """
    # general settings

    with smart_run(session):
        hashtags = ['travelcouples', 'travelcommunity', 'passionpassport',
                'travelingcouple',
                'backpackerlife', 'travelguide', 'travelbloggers',
                'travelblog', 'letsgoeverywhere',
                'travelislife', 'stayandwander', 'beautifuldestinations',
                'moodygrams',
                'ourplanetdaily', 'travelyoga', 'travelgram', 'sunsetporn',
                'lonelyplanet',
                'igtravel', 'instapassport', 'travelling', 'instatraveling',
                'travelingram',
                'mytravelgram', 'skyporn', 'traveler', 'sunrise',
                'sunsetlovers', 'travelblog',
                'sunset_pics', 'visiting', 'ilovetravel',
                'photographyoftheday', 'sunsetphotography',
                'explorenature', 'landscapeporn', 'exploring_shotz',
                'landscapehunter', 'colors_of_day',
                'earthfocus', 'ig_shotz', 'ig_nature', 'discoverearth',
                'thegreatoutdoors']
    random.shuffle(hashtags)
    my_hashtags = hashtags[:10]

    # general settings
    session.set_dont_like(['sad', 'rain', 'depression'])
    session.set_do_follow(enabled=True, percentage=38, times=1)
    session.set_do_comment(enabled=True, percentage=28)
    session.set_comments([
                             u'What an amazing shot! :heart_eyes: ',
                             u'Wonderful!! :heart_eyes: Would be awesome if '
                             u'you would checkout my photos as well!',
                             u'Wonderful!! :heart_eyes: '
                             u' Checkout my images and tell me '
                             u'what you think. :wink:',
                             u'This is awesome!! :heart_eyes: Any feedback '
                             u'for my photos? :wink:',
                             u'This is awesome!! :heart_eyes:  maybe you '
                             u'like my photos, too? :wink:',
                             u'I really like the way you captured this. I '
                             u'bet you like my photos, too :wink:',
                             u'I really like the way you captured this. If '
                             u'you have time, check out my photos, too. I '
                             u'bet you will like them. :wink:',
                             u'Great capture!!! :smiley: Any feedback for my '
                             u'recent photos? :wink:',
                             u'Great capture!! :smiley: :thumbsup: What do '
                             u'you think of my recent photo?'], media='Photo')
    session.set_do_like(True, percentage=70)
    session.set_delimit_liking(enabled=True, max=100, min=15)
    session.set_delimit_commenting(enabled=True, max=20, min=0)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=3000,
                                    max_following=2000,
                                    min_followers=100,
                                    min_following=50)

    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "follows"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(78, 800),
                                 peak_comments=(21, 250),
                                 peak_follows=(167, None))

    session.set_user_interact(amount=1, randomize=False, percentage=40)

    # activity
    session.like_by_tags(my_hashtags, amount=60, media=None)
    session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=12 * 60 * 60, sleep_delay=501)
    session.unfollow_users(amount=500, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=24 * 60 * 60, sleep_delay=501)

this code leaves me a lot of errors pointing in certain files in python folder. Can anyone try to debug it, basic ones function perfectly but this one does not.. thanks

**Comment by tE3m** [comment]
Please provide *the specific error messages*, else noone knows what you're talking about.

**Comment by samajami** [comment]
Traceback (most recent call last):
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0458A250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\likekoment.py", line 93, in <module>
    session.like_by_tags(my_hashtags, amount=60, media=None)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 1659, in like_by_tags
    self.logger)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\like_util.py", line 233, in get_links_for_tag
    web_address_navigator(browser, tag_link)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\util.py", line 1008, in web_address_navigator
    current_url = get_current_url(browser)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\util.py", line 1541, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\request.py", line 72, in request
    **urlopen_kw)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\To~shiba~ko~ludo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=50850): Max retries exceeded with url: /session/94aca25a09c4e3968ce655bcb205ad91/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0458A250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
>>>

**Comment by tE3m** [comment]
Check indentation, that might cause that.

**Comment by samajami** [comment]
Indentation is correct.. thanks for fast reply
