### ISSUE TITLE
AttributeError: 'InstaPy' object has no attribute 'aborting'

### ISSUE THREAD

**Issue by Cas7or** [InstaPy/InstaPy#398]
Hi Guys,

After reinstalling windows10 and reinstalling instapy I get the following output:

C:\Users\usrname\Documents\GitHub\InstaPy>quickstart.py
Traceback (most recent call last):
  File "C:\Users\usrname\Documents\GitHub\InstaPy\quickstart.py", line 3, in <module>
    session = InstaPy(username='usrname', password='pass')
  File "C:\Users\usrname\Documents\GitHub\InstaPy\instapy\instapy.py", line 40, in __init__
    self.set_selenium_local_session()
  File "C:\Users\usrname\Documents\GitHub\InstaPy\instapy\instapy.py", line 79, in set_selenium_local_session
    if self.aborting:
AttributeError: 'InstaPy' object has no attribute 'aborting'

Can you please help because I've been trying for 20h now and no luck.
Thank you in advance!

**Comment by botpadawan** [comment]
I also got the same error updating the latest code

**Comment by onyxim** [comment]
I've created [the pull request](https://github.com/timgrossmann/InstaPy/pull/399) to fix it.

[Pull the update from my master branch fork](https://github.com/onyxim/InstaPy)  if you want to fix it right now.

**Comment by SameerKhan** [comment]
I get the same error after a pull


python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    InstaPy() \
  File "/Users/sameer/OuzelSystems/Experiments/InstaPy/instapy/instapy.py", line 40, in __init__
    self.set_selenium_local_session()
  File "/Users/sameer/OuzelSystems/Experiments/InstaPy/instapy/instapy.py", line 79, in set_selenium_local_session
    if self.aborting:
AttributeError: InstaPy instance has no attribute 'aborting'

**Comment by timgrossmann** [comment]
#400
