### ISSUE TITLE
Issues with running instypy 24/7

### ISSUE THREAD

**Issue by yaca8** [InstaPy/InstaPy#3985]
## Expected Behavior
To Run QS in Loop 24/7

## Current Behavior
After all activities are finished, Session ends

Not sure what am I doing wrong, I want to run this script in the loop, when it finish once activity it will jump to the other, and back again to the first activity, do i have to copy and paste activities to achieve this? or there is some other way? below is only set for example to see would it work, but it always ends the session after unfollow is complete.

I would really appreciate if someone could point me what am I missing here? I dont want to schedule this, just want it to run all the time.

import random
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = ''
insta_password = ''

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)
like_tag_list = ['as','asd','asdf']
comments_list = [u'\U0000270C', u'\U0001F525']

with smart_run(session):
    # settings

    session.set_quota_supervisor(enabled=True, sleep_after=["server_calls_h"],
                                 sleepyhead=True, stochastic_flow=True,,
                                 peak_likes=(60, 200), peak_follows=(30, None),
                                 peak_unfollows=(30, 200),
                                 peak_server_calls=(500, None))

    session.set_user_interact(amount=2, randomize=True, percentage=40)
    session.set_do_follow(enabled=True, percentage=50)
    session.set_do_like(enabled=True, percentage=80)
    session.set_comments (comments_list, media='Photo')
    session.set_do_comment(enabled=True, percentage=35)

    session.like_by_tags(random.sample(like_tag_list, 2),
                         amount=random.randint(20, 50), interact=True)
    session.unfollow_users(amount=random.randint(5, 10), nonFollowers=True, style="FIFO", sleep_delay=501)

**Comment by tE3m** [comment]
Quota doesn't automatically rerun it for you. It only *supervises* the likes/comments etc per hour and day. To run it 24/7, put everything from `with smart_run(session):` into an infinite loop.

**Comment by tourhuntr** [comment]
use while true: instead of with smart_run(session)

**Comment by tE3m** [comment]
@tourhuntr that's not correct, you shouldn't do that. `while True:` doesn't replace `with smart_run(session)`. They do completely different things.

**Comment by yaca8** [comment]
I know that Quota wont rerun it, I want to use it for safe limits, @TarekJ03 can you tell me how exactly i can loop that range?

**Comment by tourhuntr** [comment]
+1. I want to do the same

**Comment by tE3m** [comment]
```
while True:
    with smart_run(session):
        <script>
```

**Comment by tourhuntr** [comment]
Works, too easy to understand ;)

**Comment by yaca8** [comment]
I must be keep doing something wrong at the end of the session when it suppose to rerun the script i get this:

Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000265437154E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user1\Downloads\instapy-quickstart-master\quickstart.py", line 15, in <module>
    with smart_run(session):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 1662, in smart_run
    session.login()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 373, in login
    self.bypass_with_mobile):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\login_util.py", line 161, in login_user
    web_address_navigator(browser, ig_homepage)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 1008, in web_address_navigator
    current_url = get_current_url(browser)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 1541, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\request.py", line 72, in request
    **urlopen_kw)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49381): Max retries exceeded with url: /session/753c8e20946e68e2321c28c1b3b1574a/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000265437154E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
>>>

**Comment by yaca8** [comment]
OK Got it working :) @TarekJ03 Thanks a lot works perfect!
