### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by ljacobo** [InstaPy/InstaPy#3992]
## Expected Behavior
Is posible to use instapy with multiple accounts with the same internet provider?

I am planning to make a docker server to host a few accounts, but im trying to avoid problems with instagram and getting blocked.

**Comment by tE3m** [comment]
It is, but you shouldn't run too many from the same IP. 3 to 4 are perfectly fine.

**Comment by ljacobo** [comment]
Thanks

**Comment by sohumsanu** [comment]
I'm running 5 accounts right now and it works perfectly fine.

**Comment by ljacobo** [comment]
For a multiple account setup, do you recommend docker in a linux pc or a few raspberry pi? Or maybe some VMs with ubuntu?

Thanks

**Comment by joaoleite** [comment]
How many accounts are you running? @ljacobo ?

**Comment by c0d3x27** [comment]
im running my account in docker, im using the commeting and liking set up for 500 people. when it reach 500 it stop. is there a way i can make it auto restart?

**Comment by ljacobo** [comment]
> How many accounts are you running? @ljacobo ?

2 accounts with raspberry pi 3 each one.

**Comment by ljacobo** [comment]
> im running my account in docker, im using the commeting and liking set up for 500 people. when it reach 500 it stop. is there a way i can make it auto restart?

i am working 24/7 with supervisor quota. Just perfect.

**Comment by sohumsanu** [comment]
> For a multiple account setup, do you recommend docker in a linux pc or a few raspberry pi? Or maybe some VMs with ubuntu?
> 
> Thanks

I'm doing VMs in Ubuntu, you just have to make sure the server has a decent amount of memory and it will easily run multiple accounts.

**Comment by platramos** [comment]
For those using Docker, I'm having trouble running multiple accounts via docker-compose. Do you guys have a different setup or am I doing something wrong?

**docker-compose.yml**
```version: '3'
services:
  account_one:
    command: ["./code/wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "code/account_one.py"]
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
      dockerfile: ./docker_conf/python/Dockerfile
    depends_on:
      - selenium
  account_two:
    command: ["./code/wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "code/account_two.py"]
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
      dockerfile: ./docker_conf/python/Dockerfile
    depends_on:
      - selenium
  account_three:
    command: ["./code/wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "code/account_three.py"]
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
      dockerfile: ./docker_conf/python/Dockerfile
    depends_on:
      - selenium
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug
    ports:
      - "5901:5900"
    shm_size: 128M
```
**Error**

```
2019-03-01T22:26:04.251361000Z ERROR [2019-03-01 22:26:04] [newwealthattitude]  Error occurred while deleting cookies from web browser!
2019-03-01T22:26:04.251398500Z 	b'Message: invalid session id\n  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.9.125-linuxkit x86_64)\n'
2019-03-01T22:26:04.251426000Z Traceback (most recent call last):
2019-03-01T22:26:04.251451400Z   File "/code/instapy/util.py", line 1677, in smart_run
2019-03-01T22:26:04.251478500Z     yield
2019-03-01T22:26:04.251510900Z   File "code/newwealthattitude.py", line 48, in <module>
2019-03-01T22:26:04.251538200Z     session.like_by_tags(my_hashtags, amount=60, media=None)
2019-03-01T22:26:04.251563800Z   File "/code/instapy/instapy.py", line 1665, in like_by_tags
2019-03-01T22:26:04.251589200Z     self.logger)
2019-03-01T22:26:04.251615100Z   File "/code/instapy/like_util.py", line 308, in get_links_for_tag
2019-03-01T22:26:04.251640500Z     "window.scrollTo(0, document.body.scrollHeight);")
2019-03-01T22:26:04.251664800Z   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
2019-03-01T22:26:04.251690200Z     'args': converted_args})['value']
2019-03-01T22:26:04.251715400Z   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
2019-03-01T22:26:04.251740500Z     self.error_handler.check_response(response)
2019-03-01T22:26:04.251765600Z   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
2019-03-01T22:26:04.251790900Z     raise exception_class(message, screen, stacktrace)
2019-03-01T22:26:04.251837600Z selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
2019-03-01T22:26:04.251863100Z from tab crashed
2019-03-01T22:26:04.251888200Z   (Session info: chrome=71.0.3578.98)
2019-03-01T22:26:04.251913400Z   (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.9.125-linuxkit x86_64)
2019-03-01T22:26:04.251938700Z```

**Comment by jeremycjang** [comment]
@awesome205 To clarify, do you mean you're running the program for 5 accounts using the same IP at the same time without problems, or 5 accounts alternating the times you run them? I've heard that 5 is the cap and after that, you might risk your IP getting blocked

**Comment by tucu10871** [comment]
Hello @platramos , i have the exacly same problem? Did you solve?
Which is the correct configuration of the docker-compose file for multiple account?
Thank you
