### ISSUE TITLE
While true doesn't work

### ISSUE THREAD

**Issue by tourhuntr** [InstaPy/InstaPy#4002]
## Expected Behavior

A 24/7 script with while true infinite loop and quota supervisor

## Current Behavior

After doing that was written in the script (like 5 images of 2 followers of the targeted account) it displayed me this error:

-----
pi@raspberrypi:~/projects/InstaPy $ python3 simple_but_effective.py 

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-02-16 22:12:08] []  Using built in instapy-chromedriver executable (version 2.36.post0)

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7497e030>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simple_but_effective.py", line 26, in <module>
    with smart_run(session):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/pi/projects/InstaPy/instapy/util.py", line 1662, in smart_run
    session.login()
  File "/home/pi/projects/InstaPy/instapy/instapy.py", line 373, in login
    self.bypass_with_mobile):
  File "/home/pi/projects/InstaPy/instapy/login_util.py", line 161, in login_user
    web_address_navigator(browser, ig_homepage)
  File "/home/pi/projects/InstaPy/instapy/util.py", line 1008, in web_address_navigator
    current_url = get_current_url(browser)
  File "/home/pi/projects/InstaPy/instapy/util.py", line 1541, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=57341): Max retries exceeded with url: /session/fc1662f04515939af27bb13202ab2747/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7497e030>: Failed to establish a new connection: [Errno 111] Connection refused',))

## InstaPy configuration

from instapy import InstaPy
from instapy.util import smart_run

insta_username = ''
insta_password = ''

get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

let's go! :>
while True:
    with smart_run(session):
        # general settings
        session.set_relationship_bounds(enabled=True,
                                     delimit_by_numbers=True,
                                      max_followers=15000,
                                      max_following=1500,
                                      min_followers=0,
                                      min_following=30)
        session.set_quota_supervisor(enabled=True,sleep_after=["likes"], sleepyhead=True, stochastic_flow=True, notify_me=True,peak_likes=(57, 700), peak_follows=(48, None), peak_unfollows=(35, 402), peak_server_calls=(500, None))

        # like activity
        ammount_number=2
        session.set_user_interact(amount=5, randomize=False, percentage=50, media='Photo')
        session.interact_user_followers(['xxx','xxxl'], amount=ammount_number, randomize=True)
        session.end()

**Comment by tourhuntr** [comment]
no one an idea?

**Comment by tE3m** [comment]
Watch your indentation. That might cause it

**Comment by sionking** [comment]
you need to del old session before new one

**Comment by tourhuntr** [comment]
How do I make that?

**Comment by alfijuan** [comment]
`session.end()`

https://github.com/timgrossmann/InstaPy/blob/master/instapy/instapy.py#L3991

**Comment by Tidle999** [comment]
so when using scheduling, how can i exit the first session and start another? for example:


```
def follow():
   do some stuff

def unfollow():
   do som other stuff

schedule.every().day.at("13:34").do(follow)
schedule.every().day.at("13:36").do(unfollow)

while True:
    schedule.run_pending()
    time.sleep(1)
```

i would expect that the funciton unfollowing is starting 13:36 and is therefore ending the session following. but thats not working, the session with following keeps running.

regards

**Comment by tourhuntr** [comment]
Insert Session.end()


![while true](https://user-images.githubusercontent.com/46623690/52974320-648a4a00-33c1-11e9-882c-a028fd05c36f.PNG)


Same Error Message

**Comment by alfijuan** [comment]
@tourhuntr I think is because you are not declaring the session between the `whille True:` and the `smart_run`.

Should be:
```
while True:
    session = InstaPy(username=insta_username,
                  password=insta_password)

    with smart_run(session):
        # your code

    session.end()
```

**Comment by tourhuntr** [comment]
Thanks, it works:

![while true works](https://user-images.githubusercontent.com/46623690/52974303-550b0100-33c1-11e9-9f5b-6c24eb203b1a.PNG)

**Comment by tE3m** [comment]
Great that you were able to resolve it @alfijuan @tourhuntr. We can close this now, right?

**Comment by tourhuntr** [comment]
For me you can close it
