### ISSUE TITLE
Cookie file not found, creating cookie...

### ISSUE THREAD

**Issue by lucasghelal** [InstaPy/InstaPy#4037]
## Current Behavior

Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    with smart_run(session):
  File "/home/lucas/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/lucas/workspace/InstaPy/instapy/util.py", line 1676, in smart_run
    session.login()
  File "/home/lucas/workspace/InstaPy/instapy/instapy.py", line 378, in login
    self.bypass_with_mobile):
  File "/home/lucas/workspace/InstaPy/instapy/login_util.py", line 262, in login_user
    "//button[text()='Log in']")
  File "/home/lucas/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/lucas/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/lucas/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lucas/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[text()='Log in']"}
  (Session info: headless chrome=72.0.3626.96)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-45-generic x86_64)

## Possible Solution (optional)
Solution by @SeoMinbong 

hi

you can change login_util.py

```
login_button = browser.find_element_by_xpath(
    "//button[text()='Log in']")
```
to

```
login_button = browser.find_element_by_xpath(
    "//button//div[text()='Log in']")
```

**Comment by SeoMinbong** [comment]
You can check #4036

**Comment by lucasghelal** [comment]
> You can check #4036

hey.. thankss so much :)

**Comment by timgrossmann** [comment]
`pip install -U instapy`

**Comment by octavius-1** [comment]
Guys, I'm still looking at this (sstarted looking at it when tried to add proxy) and yes, I already updated to the latest version:

```
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
INFO [2019-02-28 14:52:29] [my username]  Using built in instapy-chromedriver executable (version 2.46)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-02-28 14:52:30] [my username]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20190228-145308.html
**********************************************************************

INFO [2019-02-28 14:53:08] [my username]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 39.53 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-02-28 14:53:08] [my username]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "my_script.py", line 63, in <module>
    with smart_run(session):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/instapy/util.py", line 1676, in smart_run
    session.login()
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 378, in login
    self.bypass_with_mobile):
  File "/usr/local/lib/python3.6/dist-packages/instapy/login_util.py", line 179, in login_user
    "//select[@class='hztqj']/option[text()='English']")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='hztqj']/option[text()='English']"}
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-1032-aws x86_64)
``` 

Please help, I'm not able to do anything, I'm attaching my Instapy config:

    session = InstaPy(username=info.insta_username,
                      password=info.insta_password,
                      proxy_chrome_extension=proxy_chrome_extension,
                      headless_browser=True,
                      disable_image_load=True,
                      page_delay=info.page_delay,
                      proxy_username=proxy_username,
                      proxy_password=proxy_password,
                      proxy_address=address,
                      proxy_port=port,
                      bypass_suspicious_attempt=True
                      )

And I do already have a cookie loaded in /home/ubuntu/InstaPy/logs/my_username/
