### ISSUE TITLE
unable to log in with new accounts

### ISSUE THREAD

**Issue by zmcdbiz** [InstaPy/InstaPy#4047]
Traceback (most recent call last):
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python37\Lib\site-packages\marylandmotors.py", line 26, in <module>
    with smart_run(session):
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\util.py", line 1662, in smart_run
    session.login()
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\instapy.py", line 373, in login
    self.bypass_with_mobile):
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\login_util.py", line 262, in login_user
    "//button[text()='Log in']")
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[text()='Log in']"}
  (Session info: chrome=72.0.3626.109)
  (Driver info: chromedriver=2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90),platform=Windows NT 10.0.17763 x86_64)

what does this error mean ? I can log in on previous accounts but when i try to with new accounts it fails

**Comment by timgrossmann** [comment]
@zmcdbiz You have to update instapy. `pip install -U instapy`

**Comment by analyticsdept** [comment]
@timgrossmann seems like this issue has surfaced again. Performed a clean install (RP3b / Python 3.5.3) and getting the following... reinstating backups of cookie files and DBs allows accounts that were previously working to run fine, but new accounts still get stuck trying to log in.

selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[text()='Log in']"}
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.50-v7+ armv7l)

Any idea what the fix was that solved it in the update? Thanks!

**Comment by tE3m** [comment]
@analyticsdept the newest version of InstaPy shouldn't have this issue anymore. What version are you on? Btw, RPi's can now install chromium v72 :)

**Comment by analyticsdept** [comment]
@TarekJ03 thanks for the heads up about Chromium! I'm on 0.3.4 - is there a newer version? It's the one I'm getting through pip3 install instapy

**Comment by analyticsdept** [comment]
Just following up on this - I've got a fresh InstaPy install straight from the repo and for some reason log in with new accounts still can't find that xpath. I've taken a look at the browser version of Instagram and the button text hasn't changed so I'm not sure what the solution is.
