### ISSUE TITLE
Error Quickstart.py

### ISSUE THREAD

**Issue by combatlobsang** [InstaPy/InstaPy#4057]
Hello, 
i can't execute 'quickstart.py'... this is the message in terminal. I use OS X Mojave 10.14

Traceback (most recent call last):
  File "/Users/cristina/treballsJordi/INSTAPY/InstaPy-master/quickstart.py", line 5, in <module>
    from instapy import InstaPy
  File "/Users/cristina/treballsJordi/INSTAPY/InstaPy-master/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/cristina/treballsJordi/INSTAPY/InstaPy-master/instapy/instapy.py", line 12, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

I running 
`pip install -U requests` but the message is the same... any help?

**Comment by timgrossmann** [comment]
Ahh... the error say `ModuleNotFoundError: No module named 'selenium'`
Why would you update requests and expect it to work 🤔 

Which way have you installed instapy ?

**Comment by degerogretmen** [comment]
Just an easy idea. This is what happens to me. 

call the py file in terminal as below:
`python3 quickstart.py` 
Sometimes python quickstart.py looks for another folders and can't find th selenium module.
