### ISSUE TITLE
Script Creation - Issues while combining elements from templates

### ISSUE THREAD

**Issue by rudyvanbebu** [InstaPy/InstaPy#4069]
Hi, 

I'm trying to combine diferent ideas suggested in the templates. I can make the functions run separately but when combined into this script, I am receiving errors. Can someone more experience in Python take a look? (Follow by target + Scheduling + Telegram notifications)

I'm planning to add more tasks to the schedule but I'd need your help to debug this part. Either an issue with the random.targets variable or not returning sessions correctly?  Thanks 

`
import random

from instapy import InstaPy
from instapy import smart_run

import time
from datetime import datetime
import schedule
import traceback
import requests

# login credentials
insta_username = ''
insta_password = ''

# restriction data
dont_likes = ['#exactmatch', '[startswith', ']endswith', 'broadmatch', 'nsfw', 'cellphone', 'hotgirl']
ignore_users = ['user1', 'user2', 'user3']

""" Prevent commenting on and unfollowing your good friends (the images will
still be liked)...
"""
friends = ['']

""" Prevent posts that contain...
"""
ignore_list = ['']

# TARGET data
""" Set similar accounts and influencers from your niche to target...
"""
targets = ['']

""" Skip all business accounts, except from list given...
"""
target_business_categories = ['category2', 'category3']

# COMMENT data
comments = [':)']

bot_token = ''
bot_chatID = ''

def get_session():

    # get a session!
    session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs=True)

    # let's go! :>
    with smart_run(session):
            # HEY HO LETS GO
            # general settings
            session.set_dont_include(friends)
            session.set_dont_like(dont_likes)
            session.set_ignore_if_contains(ignore_list)
            session.set_ignore_users(ignore_users)
            session.set_simulation(enabled=True)
            session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=7500,
                                    max_following=3000,
                                    min_followers=25,
                                    min_following=25,
                                    min_posts=10)

            session.set_skip_users(skip_private=True,
                           skip_no_profile_pic=True,
                           skip_business=True,
                           dont_skip_business_categories=[
                               target_business_categories])

            session.set_user_interact(amount=3, randomize=True, percentage=80,
                              media='Photo')
            session.set_do_like(enabled=True, percentage=90)
            session.set_do_comment(enabled=False, percentage=0)
            session.set_comments(comments, media='Photo')
            session.set_do_follow(enabled=True, percentage=40, times=1)

    return session

    # activities

    # FOLLOW+INTERACTION on TARGETED accounts

def follow():

    # Send notification to my Telegram
    requests.get(
        'https://api.telegram.org/bot' + bot_token + '/sendMessage?chat_id=' + bot_chatID + '&parse_mode=Markdown&text=Bot Started following @ {}'
        .format(datetime.now().strftime("%H:%M:%S")))

    # Select users form a list of a predefined targets...
    number = random.randint(3, 5)
    random_targets = targets

    if len(targets) <= number:
        random_targets = targets

    else:
        random_targets = random.sample(targets, number)

    # get a session!
    session = get_session()

    # Interact with the chosen targets...
    try:
        session.follow_user_followers(random_targets,
                                      amount=random.randint(1, 2),
                                      randomize=True, sleep_delay=600,
                                      interact=True)

    except Exception:
        print(traceback.format_exc())

    # Send notification to my Telegram
    requests.get(
        'https://api.telegram.org/bot' + bot_token + '/sendMessage?chat_id=' + bot_chatID + '&parse_mode=Markdown&text=Bot Stopped following @ {}'
        .format(datetime.now().strftime("%H:%M:%S")))

# schedulers
schedule.every().day.at("15:45").do(follow)

while True:
    schedule.run_pending()
    time.sleep(1)

`

**Comment by rudyvanbebu** [comment]
This is the type of error I am receiving, after correct session creation / login

Traceback (most recent call last):
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001FB302CF668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "InstaPy 1st Draft with schedule.py", line 119, in follow
    interact=True)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\instapy.py", line 3082, in follow_user_followers
    self.logfolder)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\unfollow_util.py", line 973, in get_given_user_followers
    web_address_navigator(browser, user_link)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\util.py", line 1022, in web_address_navigator
    current_url = get_current_url(browser)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\util.py", line 1555, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\request.py", line 72, in request
    **urlopen_kw)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=60811): Max retries exceeded with url: /session/9dc63a7f2b7ffe3e3ab94da490d16701/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FB302CF668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

**Comment by rudyvanbebu** [comment]
Solved on my own, you can close this issue

**Comment by AlokinVetob** [comment]
What was the solution :?????

**Comment by rudyvanbebu** [comment]
Incorrect indentation of these lines defining random target value

Make sure all variables are correctly placed, specially while handling scheduling. I'm a noob in Python so for me the issue was not clear at first sight 

```
number = random.randint(3, 3)
random_targets = targets

if len(targets) <= number:
    random_targets = targets

else:
    random_targets = random.sample(targets, number)
```
