### ISSUE TITLE
Scheduled run exits with selenium.common.exceptions.WebDriverException: Message: unknown error: unknown sessionId

### ISSUE THREAD

**Issue by hpatrik92** [InstaPy/InstaPy#4073]
## Expected Behavior
I have been running the script for 2 weeks without problems
## Current Behavior
Script exits after a while with the following error:

INFO [2019-02-26 10:11:17] [username]  User 'blahalujza' [31/97]

INFO [2019-02-26 10:11:20] [username]  Sessional Live Report:
	|> LIKED 95 images  |  ALREADY LIKED: 16
	|> COMMENTED on 0 images
	|> FOLLOWED 36 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> LIKED 0 comments
	|> REPLIED to 0 comments
	|> INAPPROPRIATE images: 150
	|> NOT VALID users: 0

On session start was FOLLOWING 1004 users & had 540 FOLLOWERS
[Session lasted 1.68 hours]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-02-26 10:11:20] [username]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "username.py", line 69, in <module>
    schedule.run_pending()
  File "/home/pi/.local/lib/python3.5/site-packages/schedule/__init__.py", line 563, in run_pending
    default_scheduler.run_pending()
  File "/home/pi/.local/lib/python3.5/site-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/home/pi/.local/lib/python3.5/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/home/pi/.local/lib/python3.5/site-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
  File "username.py", line 48, in job
    amount=100, randomize=False)
  File "/home/pi/InstaPy/instapy/instapy.py", line 2782, in interact_user_followers
    validation, details = self.validate_user_call(person)
  File "/home/pi/InstaPy/instapy/instapy.py", line 1134, in validate_user_call
    self.logfolder)
  File "/home/pi/InstaPy/instapy/util.py", line 182, in validate_username
    logger)
  File "/home/pi/InstaPy/instapy/util.py", line 928, in get_relationship_counts
    web_address_navigator(browser, user_link)
  File "/home/pi/InstaPy/instapy/util.py", line 1042, in web_address_navigator
    browser.get(link)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unknown sessionId
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)

pi@raspberrypi:~/InstaPy $

**Comment by acidx00** [comment]
Hi, same problem here since yesterday

**Comment by hpatrik92** [comment]
> Hi, same problem here since yesterday

It happens since yesterday for me too

**Comment by apulido305** [comment]
Failing for me as well slightly different error. looks like IG has adapted lol

**Comment by gedankenstrom** [comment]
same problem here.

**Comment by joanroig** [comment]
Hmh I have the same problem but only for one of my accounts, others are working fine.
EDIT: I can see it fails after some follows by list or after some likes by hashtags

**Comment by x225am** [comment]
Hi there,
the same problem since Monday

**Comment by x225am** [comment]
Any ideas why it could happen?

**Comment by riconem** [comment]
Hi, I had the same problem. I used tmux for terminal session. Since I use crontab its working fine.

**Comment by joanroig** [comment]
@timgrossmann I'm experiencing this issue after running scripts with schedule for some days, do you know who can help us on this? This issue happens since last Monday, appeared at the same time as the "Log in" issue :S

**Comment by jeremycjang** [comment]
I've begun observing this recently too. Perhaps it's isolated to Raspberry Pi users?

@breuerfelix  Chromium on Raspberry Pi is only supported up to version 65 and doesn't seem to have any updates. Do you know if this issue experienced by some might be related to the more recent changes in browser behavior/configuration that have happened? I haven't quite kept up with everything that's been going on

**Comment by breuerfelix** [comment]
to be honest i got no clue at all, never experienced this issue :S  
i just googeled a little bit and someone said that he had the same issue cause of a popping notification.

does instagram show notifications ? anybody knows that ?

**Comment by jeffarese** [comment]
Happening here too, RPi3B+

**Comment by JoeFertig** [comment]
I had this error just once.
Then restarted the bot and everything was fine again.
Let's see if it occurs more often now.

**Comment by JoeFertig** [comment]
The error occurs in more sessions now.
Any fixes?

**Comment by joanroig** [comment]
Up, I see this error once a day or more. No clues for now, but seems an isolated issue of Raspberry Pi

**Comment by thejeromelouis** [comment]
Same problem on every account with my RPi 3B+.

**Comment by mafredas** [comment]
Same here..with clear installation!!

Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/instapy/util.py", line 939, in get_relationship_counts
    "return window._sharedData.entry_data."
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 65, in <module>
    randomize=True, interact=False, sleep_delay=randint(330, 605))
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 3173, in follow_user_followers
    validation, details = self.validate_user_call(person)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 1186, in validate_user_call
    self.logfolder)
  File "/home/pi/Projects/InstaPy/instapy/util.py", line 185, in validate_username
    logger)
  File "/home/pi/Projects/InstaPy/instapy/util.py", line 945, in get_relationship_counts
    browser.find_element_by_xpath("//a[contains"
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unknown sessionId
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)

**Comment by riconem** [comment]
Do you use some kind of session-tool like tmux?

Try to use cronjobs:
https://github.com/timgrossmann/InstaPy/issues/4068#issuecomment-467827395

I dont get this error anymore

**Comment by anitato** [comment]
I also have this problem :( #4192 (and I have the correct version of chrome!). I did a clean install yesterday and it runs for a few hours successfully before quitting. Also, the count for liking photos and following individuals is incorrect for me (underestimates drastically or says "0"):
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO                                                                          [11/1837]
INFO [2019-03-19 19:22:09] [_username_]  Session ended!                                                                                   
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                                                   
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
Traceback (most recent call last):                                                                                                               
  File "quickstart.schedule.py", line 562, in <module>                                                                                       
    schedule.run_pending()                                                                                                                       
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 563, in run_pending                                                   
    default_scheduler.run_pending()                                                                                                              
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 94, in run_pending                                                    
    self._run_job(job)
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
  File "quickstart.scheduleMod6.py", line 129, in tuesd
    session.like_by_tags(['tags'], amount=51, interact=True, skip_top_posts=True)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 1848, in like_by_tags
    self.logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 704, in follow_user
    logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 1531, in verify_action
    logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 156, in get_following_status
    valid_page = is_page_available(browser, logger)
  File "/usr/local/lib/python3.5/dist-packages/instapy/util.py", line 1654, in is_page_available
    page_title = get_page_title(browser, logger)
  File "/usr/local/lib/python3.5/dist-packages/instapy/util.py", line 1716, in get_page_title
    explicit_wait(browser, "PFL", [], logger, 10)
  File "/usr/local/lib/python3.5/dist-packages/instapy/util.py", line 1543, in explicit_wait
    result = wait.until(condition)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/usr/local/lib/python3.5/dist-packages/instapy/util.py", line 1531, in <lambda>
    "return document.readyState")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unknown sessionId
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.27-v7+ armv7l)

**Comment by martinkrulltott** [comment]
Same here on my RPi3B+, some sessions run fine from start to finish, some of them finish early with this error.

**Comment by hugio55** [comment]
Any solution yet? It's killin' me.

**Comment by jeremycjang** [comment]
Potentially related: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2333

Going to test, if someone else tests please share the results (downgrade to chromedriver 2.35)

**Comment by jeremycjang** [comment]
As a disclaimer, I don't know enough about the structure of this ```instapy-chromedriver``` code to know how it works or how it's affected.

**Comment by jeremycjang** [comment]
Also potentially related #4441
