### ISSUE TITLE
Problems with Unfollowing

### ISSUE THREAD

**Issue by kushpvo** [InstaPy/InstaPy#408]
C:\Users\kushpvo\Documents\GitHub\InstaPy>set PYTHONIOENCODING=UTF-8

C:\Users\kushpvo\Documents\GitHub\InstaPy>py quickstart.py
Logged in successfully!
('set_automated_followed_pool error \n', "[Errno 2] No such file or directory: './logs/the.couples.stuff_followedPool.csv'")
Traceback (most recent call last):
  File "quickstart.py", line 11, in <module>
    session.unfollow_users(amount=10, onlyInstapyFollowed = False )
  File "C:\Users\kushpvo\Documents\GitHub\InstaPy\instapy\instapy.py", line 517, in unfollow_users
    self.automatedFollowedPool)
  File "C:\Users\kushpvo\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 51, in unfollow
    dialog = browser.find_element_by_xpath('/html/body/div[2]/div/div[2]/div/div[2]')
  File "C:\Users\kushpvo\Anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\kushpvo\Anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Users\kushpvo\Anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Users\kushpvo\Anaconda2\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[2]/div/div[2]/div/div[2]"}
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.14393 x86_64)

**Comment by lgr** [comment]
I had the same problem on OSX, just created a pull request to fix it:
https://github.com/timgrossmann/InstaPy/pull/412

**Comment by stevenselcuk** [comment]
For temporary fix change this
`dialog = browser.find_element_by_xpath('/html/body/div[2]/div/div[2]/div/div[2]')`
this line as
`dialog = browser.find_element_by_class_name('_4gt3b')`
on InstaPy/instapy/unfollow_util.py Line 53

**Comment by timgrossmann** [comment]
#412
