### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by JacobSobolev** [InstaPy/InstaPy#4095]
I installed instapy on raspberry pi 3 B with the updated tutorial from two days ago
the issue is solved by changing the default workspace. 
I think you should add this in the tutorial or the change the code to use the default workspace of the file location instead of /root/InstaPy

## Current Behavior
`sudo python3 bot.py 

 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-03-03 04:06:57] [myuser]  Using built in instapy-chromedriver executable (version 2.46)
Traceback (most recent call last):
  File "bot.py", line 23, in <module>
    headless_browser=True)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 279, in __init__
    self.set_selenium_local_session()
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 331, in set_selenium_local_session
    self.logger)
  File "/usr/local/lib/python3.5/dist-packages/instapy/browser.py", line 135, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
`

## Possible Solution (optional)
the issue is that instapy uses defulat workspace as /root/InstaPy.
just include that code in the script

```
from instapy import set_workspace
set_workspace(path='/home/pi/InstaPy')
```

## InstaPy configuration
None

**Comment by tE3m** [comment]
That's because it's *normal* to use it without **sudo** . If you don't use sudo, `/home/pi/InstaPy/` is the normal directory.

**Comment by JacobSobolev** [comment]
> That's because it's _normal_ to use it without **sudo** . If you don't use sudo, `/home/pi/InstaPy/` is the normal directory.

if i run without sudo i get different errors. i think maybe the chromedriver need to run under the admin as in widnows

**Comment by tE3m** [comment]
No. If you get `[Errno 8]` that means that you didn't install the binary that's specific for RPi.

**Comment by JacobSobolev** [comment]
> No. If you get `[Errno 8]` that means that you didn't install the binary that's specific for RPi.

what do you mean I didn't install the binary specific to the RPI?
I used the latest guide to install the instapy on the raspberry pi
