### ISSUE TITLE
interact_user_followers error

### ISSUE THREAD

**Issue by aron9711** [InstaPy/InstaPy#4098]
## InstaPy configuration
```
# -*- coding: UTF-8 -*-
import time
from datetime import datetime
import schedule
import traceback
import requests

from instapy import InstaPy
from instapy.util import smart_run


insta_username = 'username'
insta_password = 'password'


def get_session():
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      bypass_suspicious_attempt=True,
                      headless_browser=True,
                      nogui=True,
                      multi_logs=False)

    return session

def like():

    session = get_session()

    with smart_run(session):
        session.set_user_interact(amount=1, randomize=True, percentage=50, media='Photo')
        session.set_do_follow(enabled=True, percentage=70)
        session.set_do_like(enabled=False, percentage=70)
        session.set_do_comment(enabled=False, percentage=80)
        session.interact_user_followers(['natgeo'], amount=10, randomize=True)

like()
```

## Error message
`Traceback (most recent call last):
  File "quickstart.py", line 58, in <module>
    like()
  File "quickstart.py", line 56, in like
    session.interact_user_followers(['natgeo'], amount=10, randomize=True)
  File "/root/InstaPy/instapy/instapy.py", line 2720, in interact_user_followers
    self.logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 998, in get_given_user_followers
    logger, logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 745, in get_users_through_dialog
    scroll_to_bottom_of_followers_list(browser, dialog)
  File "/root/InstaPy/instapy/unfollow_util.py", line 707, in scroll_to_bottom_of_followers_list
    "arguments[0].children[1].scrollIntoView()", element)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'scrollIntoView' of undefined
  (Session info: headless chrome=72.0.3626.109)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-116-generic x86_64)
`

**Comment by aron9711** [comment]
## Solution
8e4fb1455ded426a1fc57407d9d08e4a56b6a308
