### ISSUE TITLE
Issue running quickstart.py on updated python... 

### ISSUE THREAD

**Issue by crowg** [InstaPy/InstaPy#4118]
in hopes to fix a few issues I have had with quickstart in the past I did a major update to Python and Pip. Now when I command Quickstart.py I receive this code immediately. I believe i installed everything correct including  pip install instapy and I can't get past this... can anyone help me make sense of it? googling the issues doesn't seem to give me a solution that I can figure out with the new updates to instapy. Thank you! 

Message: 'chromedriver_mac64' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy_chromedriver-2.44-py3.7.egg/instapy_chromedriver/chromedriver_mac64'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bbamagic/Desktop/InstaPy/instapy/browser.py", line 135, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_mac64' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    disable_image_load=True)
  File "/Users/bbamagic/Desktop/InstaPy/instapy/instapy.py", line 279, in __init__
    self.set_selenium_local_session()
  File "/Users/bbamagic/Desktop/InstaPy/instapy/instapy.py", line 333, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy_chromedriver-2.44-py3.7.egg/instapy_chromedriver/chromedriver_mac64

**Comment by Jaywrkr** [comment]
The same for me!!!!

**Comment by crowg** [comment]
while trying to update instapy i notice this code. 

Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instapy-0.2.3.dist-info/METADATA'

could there be a communication issue with the fact that Python has been updated to 3.7 and everything is still reading in 3.6?

**Comment by crowg** [comment]
by the way i still get the messages while running quickstart as a headless browser.

**Comment by crowg** [comment]
@timgrossmann

**Comment by KingWillonius** [comment]
Did you ever find a solution to this issue?
