### ISSUE TITLE
'InstaPy' object has no attribute 'aborting'

### ISSUE THREAD

**Issue by eurunuela** [InstaPy/InstaPy#413]
I get this error when executing python3 quickstart.py on my Raspberry.

`Traceback (most recent call last):
  File "quickstart.py", line 19, in <module>
    .end()
  File "/home/pi/InstaPy/instapy/instapy.py", line 40, in __init__
    self.set_selenium_local_session()
  File "/home/pi/InstaPy/instapy/instapy.py", line 79, in set_selenium_local_session
    if self.aborting:
AttributeError: 'InstaPy' object has no attribute 'aborting'
`

**Comment by timgrossmann** [comment]
@Nkuutz Please paste your quickstart.py file here.

**Comment by eurunuela** [comment]
There you go.
[quickstart.txt](https://github.com/timgrossmann/InstaPy/files/1150335/quickstart.txt)

**Comment by eurunuela** [comment]
Having done a few tweaks that I cannot now remember, I get this error.

`Traceback (most recent call last):
  File "quickstart.py", line 23, in <module>
    .end()
  File "/home/pi/InstaPy/instapy/instapy.py", line 76, in __init__
    self.set_selenium_local_session()
  File "/home/pi/InstaPy/instapy/instapy.py", line 89, in set_selenium_local_session
    self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options)
  File "/usr/local/lib/python3.4/dist-packages/selenium-2.53.6-py3.4.egg/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.4/dist-packages/selenium-2.53.6-py3.4.egg/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7697cbb0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/selenium-2.53.6-py3.4.egg/selenium/webdriver/common/service.py", line 163, in __del__
    self.stop()
  File "/usr/local/lib/python3.4/dist-packages/selenium-2.53.6-py3.4.egg/selenium/webdriver/common/service.py", line 135, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'
`

**Comment by converge** [comment]
bug fix #400 (merged)

**Comment by zanlahome** [comment]
I have been trying to set it up but still got error. Please take a look. Thank you

Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password)
  File "/root/Projects/InstaPy/instapy/instapy.py", line 135, in __init__
    self.set_selenium_local_session()
  File "/root/Projects/InstaPy/instapy/instapy.py", line 194, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception

What am I missing?
