### ISSUE TITLE
InstaPy crashes on rasperry pi

### ISSUE THREAD

**Issue by thejeromelouis** [InstaPy/InstaPy#4149]
## Current Behavior
InstaPy is always crashing after 5-10 minutes running on my raspberry pi 3 b+. Does anyone know why?
## InstaPy configuration
```
Traceback (most recent call last):
  File "Like_Interact.py", line 59, in <module>
    session.like_by_locations(milliontowns, amount=200)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 1285, in like_by_locations
    self.logger))
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/like_util.py", line 502, in check_link
    web_address_navigator(browser, post_link)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1042, in web_address_navigator
    browser.get(link)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: unknown sessionId
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)

```

**Comment by mafredas** [comment]
Same here with clear setup!!

**Comment by JoeFertig** [comment]
#4073

**Comment by ljacobo** [comment]
Hi, 

are you still working with rpb 3?

I tried playing with chrome driver versions, but not success.

Somebody has a functional setup with raspberry pi?

Thnks

**Comment by tE3m** [comment]
@ljacobo yes... the RPi install guide leads to a successful installation. The chromedriver you need is `instapy-chromedriver==2.36.post0`

**Comment by ljacobo** [comment]
Thanks, everything works as it should!!

**Comment by anitato** [comment]
This didn't fix my problem. I still crash even after updating the chromedriver #4192

**Comment by thejeromelouis** [comment]
@anitato I still have that problem, too.
