### ISSUE TITLE
Instapy issue with Dependencies, MeaningCloud

### ISSUE THREAD

**Issue by Unutuku** [InstaPy/InstaPy#4150]
I already tried to uninstall and re-install instapy in many ways. Using pip3, pip, updates etc. 

Whenever I try to run quickstart.py, it will throw a ModuleNotFound error. First it was Regex, then it was MeaningCloud, etc. 

Sometimes I can manage to install these modules manually, but MeaningCloud is not working at all. Whenever I say pip install MeaningCloud-python, or any of the variations, it just tells me that this requirement is already satisfied. 

```
Requirement already satisfied: meaningcloud-python in /anaconda3/lib/python3.7/site-packages/MeaningCloud_python-1.1.1-py3.7.egg (1.1.1)
Requirement already satisfied: requests[security] in /anaconda3/lib/python3.7/site-packages (from meaningcloud-python) (2.21.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /anaconda3/lib/python3.7/site-packages (from requests[security]->meaningcloud-python) (1.24.1)
Requirement already satisfied: idna<2.9,>=2.5 in /anaconda3/lib/python3.7/site-packages (from requests[security]->meaningcloud-python) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.7/site-packages (from requests[security]->meaningcloud-python) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.7/site-packages (from requests[security]->meaningcloud-python) (3.0.4)
Requirement already satisfied: pyOpenSSL>=0.14; extra == "security" in /anaconda3/lib/python3.7/site-packages (from requests[security]->meaningcloud-python) (18.0.0)
Requirement already satisfied: cryptography>=1.3.4; extra == "security" in /anaconda3/lib/python3.7/site-packages (from requests[security]->meaningcloud-python) (2.3.1)
Requirement already satisfied: six>=1.5.2 in /anaconda3/lib/python3.7/site-packages (from pyOpenSSL>=0.14; extra == "security"->requests[security]->meaningcloud-python) (1.11.0)
Requirement already satisfied: asn1crypto>=0.21.0 in /anaconda3/lib/python3.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->meaningcloud-python) (0.24.0)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /anaconda3/lib/python3.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->meaningcloud-python) (1.11.5)
Requirement already satisfied: pycparser in /anaconda3/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.7->cryptography>=1.3.4; extra == "security"->requests[security]->meaningcloud-python) (2.18)

```

But it still throws: 

```
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/anaconda3/lib/python3.7/site-packages/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/anaconda3/lib/python3.7/site-packages/instapy/instapy.py", line 72, in <module>
    from .text_analytics import text_analysis
  File "/anaconda3/lib/python3.7/site-packages/instapy/text_analytics.py", line 11, in <module>
    from meaningcloud import SentimentResponse, SentimentRequest
ModuleNotFoundError: No module named 'meaningcloud'
```

The previous fixes with MeaningCloud that people had, did not work. What's going on here? How can I fix it? 

And more importantly, what's the underlying issues? I think once I get MeaningCloud to work, it will just throw the next ModuleNotFound error for another dependency.

**Comment by octavius-1** [comment]
What I just do is:
sudo pip3 install module_name for every missing module.

**Comment by Unutuku** [comment]
> What I just do is:
> sudo pip3 install module_name for every missing module.

But... I already said that this doesn't work in my post. It says these modules are installed, but when trying to run the program, it says module not found.

**Comment by Unutuku** [comment]
ok, solved it by running in a virtual environment.
