### ISSUE TITLE
New issues after Update. Hopefully an easy fix. 

### ISSUE THREAD

**Issue by crowg** [InstaPy/InstaPy#4164]
Due to the recent Update I finally got my Quickstart.py file up and running. Thank you! 
But while running instapy, I received these error and issues. 
______________________________________________________________________________________________
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyer/platforms/macosx/notification.py", line 8, in <module>
    import pyobjus  # pylint: disable=unused-import
ModuleNotFoundError: No module named 'pyobjus'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyer/utils.py", line 96, in _ensure_obj
    mod = __import__(module, fromlist='.')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyer/platforms/macosx/notification.py", line 11, in <module>
    "pyobjus missing, please install it. "
Exception: pyobjus missing, please install it. `python -m pip install git+http://github.com/kivy/pyobjus/`
-----------------------------------------------------------------------
Last login: Thu Mar 14 00:42:22 on ttys000
*****-MacBook-Pro:~ ***********$ python -m pip install git+http://github.com/kivy/pyobjus/
Collecting git+http://github.com/kivy/pyobjus/
  Cloning http://github.com/kivy/pyobjus/ to /private/var/folders/1p/lrhw33g16b340lb6tyrwbx9h0000gn/T/pip-req-build-1buk6_76
    Complete output from command python setup.py egg_info:
    Pyobjus platform is darwin
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1p/lrhw33g16b340lb6tyrwbx9h0000gn/T/pip-req-build-1buk6_76/setup.py", line 20, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/1p/lrhw33g16b340lb6tyrwbx9h0000gn/T/pip-req-build-1buk6_76/
____________________________________________________________________________

**Comment by FranklinClinton** [comment]
Not trying to be mean, but have you tried googling the error message?

Everytime it says no module named "..." it cannot find a python module with that name. Either there is a typo or which is more likely, you haven't installed that module.

pip install cython

**Comment by Zettt** [comment]
I had the same issue(s). Try installing `pyobjus` and `cython` with pip.
