### ISSUE TITLE
chromedriver_linux64

### ISSUE THREAD

**Issue by LuciferWolf** [InstaPy/InstaPy#4183]
File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-1075-aws x86_64)

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    headless_browser=False)
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 287, in __init__
    self.set_selenium_local_session()
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 341, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /home/ubuntu/.local/lib/python2.7/site-packages/instapy_chromedriver/chromedriver_linux64

**Comment by vanyacohen** [comment]
What was your solution?

**Comment by tE3m** [comment]
@vanyacohen the actual error isn't the last one, that one gets thrown every time. That person's problem was that chtomium wasn't running, so it probably wasn't installed.
