### ISSUE TITLE
Session ends suddenly with error

### ISSUE THREAD

**Issue by chuck-23** [InstaPy/InstaPy#4186]
## Expected Behavior
Session should not end, since it is in a boot loop and it does with an error I do not understand.
## Current Behavior
I attach the terminal log error.

```
INFO [2019-03-18 06:14:00] [username]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 153 users & had 2248 FOLLOWERS
[Session lasted 1.68 hours]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-03-18 06:14:00] [username]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "carlos.py", line 78, in <module>
    session.like_by_tags(my_hashtags, amount=60, media=None)
  File "/home/carlos/.local/lib/python2.7/site-packages/instapy/instapy.py", line 1745, in like_by_tags
    self.logger)
  File "/home/carlos/.local/lib/python2.7/site-packages/instapy/like_util.py", line 609, in check_link
    if not check_character_set(image_text):
  File "/home/carlos/.local/lib/python2.7/site-packages/instapy/instapy.py", line 5163, in check_character_set
    for uchr in unistr
  File "/home/carlos/.local/lib/python2.7/site-packages/instapy/instapy.py", line 5164, in <genexpr>
    if uchr.isalpha())
  File "/home/carlos/.local/lib/python2.7/site-packages/instapy/instapy.py", line 5147, in is_mandatory_character
    unicodedata.name(uchr))
TypeError: name() argument 1 must be unicode, not str
```
## InstaPy configuration
Running latest version on instapy on latest version of pip on an Ubuntu 18.04 VPS. 
I attach my file .py (I have changed hashtags and users for privacy):

```
"""
This template is written by @the-unknown

What does this quickstart script aim to do?
- This is my template which includes the new QS system.
  It includes a randomizer for my hashtags... with every run, it selects 10
  random hashtags from the list.

NOTES:
- I am using the bot headless on my vServer and proxy into a Raspberry PI I
have at home, to always use my home IP to connect to Instagram.
  In my comments, I always ask for feedback, use more than 4 words and
  always have emojis.
  My comments work very well, as I get a lot of feedback to my posts and
  profile visits since I use this tactic.

  As I target mainly active accounts, I use two unfollow methods. 
  The first will unfollow everyone who did not follow back within 12h.
  The second one will unfollow the followers within 24h.
"""

# !/usr/bin/python2.7
import random
from instapy import InstaPy
from instapy import smart_run

# get a session!
while True:
    session = InstaPy(username='username', password='password', headless_browser=True)

    # let's go! :>
    with smart_run(session):
        hashtags = ['htg', 'htg', 'htg', 'htg', 'htg', 'htg']
        random.shuffle(hashtags)
        my_hashtags = hashtags[:10]

        # general settings
        session.set_dont_include(["usr", "usr", "usr", "usr"])
        session.set_skip_users(skip_private=True, private_percentage=100)
        session.set_mandatory_language(enabled=True, character_set='LATIN')
        session.set_dont_like(['sad', 'rain', 'depression'])
        session.set_do_follow(enabled=True, percentage=40, times=1)
        session.set_do_comment(enabled=True, percentage=30)
        session.set_comments([
                                 u'¡Que foto más chula! :heart_eyes: ¿Has visto las de mi perfil??',
                                 u'¡Qué foto más chula!! :heart_eyes: Creo que también te gustarán las mias. :wink:',
                                 u'¡¡Precioso!! :heart_eyes: ¡Sería genial si pudieses ver mis fotos!',
                                 u'¡¡Precioso!! :heart_eyes: Estaría bien si pudieses darme tu opinión sobre mis fotos. :wink:',
                                 u'¡¡Esto es alucinante!! :heart_eyes: ¿Puedes darme feedback sobre mis fotos? :wink:',
                                 u'¡¡Esto es una pasada!! :heart_eyes:  Seguramente también te gusten mis fotos :wink:',
                                 u'Me encanta la forma en la que has capturado esto. Apuesto a que te encantarán también mis fotos :wink:',
                                 u'Me encanta la forma en la que has capturado esto. Si tienes tiempo revisa mis fotos. Estoy seguro de que también te encantarán. :wink:',
                                 u'¡¡Buena toma!! :smiley: ¿Me puedes dar feedback en mi última foto? :wink:',
                                 u'¡¡Buen disparo!! :smiley: :thumbsup: ¿Qué te parece mi última foto??'],
                             media='Photo')
        session.set_do_like(True, percentage=70)
        session.set_delimit_liking(enabled=True, max=100, min=0)
        session.set_delimit_commenting(enabled=True, max=20, min=0)
        session.set_relationship_bounds(enabled=True,
                                        potency_ratio=None,
                                        delimit_by_numbers=True,
                                        max_followers=3000,
                                        max_following=2000,
                                        min_followers=100,
                                        min_following=50)

        session.set_quota_supervisor(enabled=True,
                                     sleep_after=["likes", "follows"],
                                     sleepyhead=True, stochastic_flow=True,
                                     notify_me=True,
                                     peak_likes=(100, 1000),
                                     peak_comments=(21, 250),
                                     peak_follows=(200, None))

        session.set_user_interact(amount=1, randomize=False, percentage=40)

        # activity
        session.like_by_tags(my_hashtags, amount=60, media=None)
        session.unfollow_users(amount=7500, allFollowing=True, style="LIFO", unfollow_after=72*60*60, sleep_delay=450)
        session.end()
```

**Comment by anitato** [comment]
Same problem. :( #4192
