### ISSUE TITLE
Session crash

### ISSUE THREAD

**Issue by chuck-23** [InstaPy/InstaPy#4188]
## Expected Behavior
Session should not stop since it is in loop
## Current Behavior
Session at some point crashes. I attach the Terminal log:

```
INFO [2019-03-18 15:24:37] [username]  Sessional Live Report:
	|> LIKED 0 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 500 users
	|> LIKED 0 comments
	|> REPLIED to 0 comments
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0

On session start was FOLLOWING 6148 users & had 11169 FOLLOWERS
[Session lasted 18.72 hours]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-03-18 15:24:37] [username]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.follow_by_tags(['tg1', 'tg2'], amount=750)
  File "/home/carlos/.local/lib/python2.7/site-packages/instapy/instapy.py", line 4270, in follow_by_tags
    self.logger)
  File "/home/carlos/.local/lib/python2.7/site-packages/instapy/like_util.py", line 609, in check_link
    if not check_character_set(image_text):
  File "/home/carlos/.local/lib/python2.7/site-packages/instapy/instapy.py", line 5163, in check_character_set
    for uchr in unistr
  File "/home/carlos/.local/lib/python2.7/site-packages/instapy/instapy.py", line 5164, in <genexpr>
    if uchr.isalpha())
  File "/home/carlos/.local/lib/python2.7/site-packages/instapy/instapy.py", line 5147, in is_mandatory_character
    unicodedata.name(uchr))
TypeError: name() argument 1 must be unicode, not str
```
## InstaPy configuration

Running Instapy latest version on pip (latest version) on Ubuntu 18.04. I attach the Quickstart.py

```
""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'username'
insta_password = 'password'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
while True:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=True)

    with smart_run(session):
        """ Activity flow """
        # general settings
        session.set_relationship_bounds(enabled=True,
                                        delimit_by_numbers=True,
                                        max_followers=4590,
                                        min_followers=45,
                                        min_following=77)

        session.set_mandatory_language(enabled=True, character_set='LATIN')

        # activity
        session.unfollow_users(amount=500, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)
        session.follow_by_tags(['tg1', 'tg2'], amount=750)
        session.like_by_feed(amount=500, randomize=True, unfollow=True, interact=True)

```

**Comment by tE3m** [comment]
Why are you using `python2.7`?
