### ISSUE TITLE
Keeps failing on RPi3 (crashes) - what is going on??

### ISSUE THREAD

**Issue by anitato** [InstaPy/InstaPy#4192]
## Expected Behavior
Run smoothly on Raspberry Pi 3B+ (w/ headless mode, pip3). Is anybody else encountering this issue?

## Current Behavior
Runs for ~20 minutes (follows and likes ~30-60 photos/users), and then crashes. I've done a clean install of the most recent version on my RPi3.

Edit: having run it a few more times, the run time has high variability. Sometimes for 2 minutes, sometimes for 3 hours... I'm not an expert coder so I'm not sure where the problem lies.

```
[Session lasted 22.08 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-03-20 14:31:46] [user]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "quickstart.py", line 56, in <module>
    session.like_by_tags(random.sample(like_tags_list, random.randint(18,21)), amount=random.randint(41,51), interact=True, skip_top_posts=True)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 1848, in like_by_tags
    self.logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 704, in follow_user
    logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 1531, in verify_action
    logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 156, in get_following_status
    valid_page = is_page_available(browser, logger)
  File "/usr/local/lib/python3.5/dist-packages/instapy/util.py", line 1654, in is_page_available
    page_title = get_page_title(browser, logger)
  File "/usr/local/lib/python3.5/dist-packages/instapy/util.py", line 1716, in get_page_title
    explicit_wait(browser, "PFL", [], logger, 10)
  File "/usr/local/lib/python3.5/dist-packages/instapy/util.py", line 1543, in explicit_wait
    result = wait.until(condition)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/usr/local/lib/python3.5/dist-packages/instapy/util.py", line 1531, in <lambda>
    "return document.readyState")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unknown sessionId
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.27-v7+ armv7l)
```

## InstaPy configuration

```
import random
from instapy import InstaPy
from instapy.util import smart_run

import time
from datetime import datetime
import traceback
import requests

insta_username = 'something'
insta_password = 'something'

session = InstaPy(username=insta_username,
					  password=insta_password,
					  headless_browser=True,
					  multi_logs=True,
					  nogui=True)

requests.get(
		"https://api.telegram.org/...")

dont_likes = ['profanity']
friends = ['friends']
like_tags_list = ['tags']
like_locations_list = ['locations']

with smart_run(session):
	session.set_relationship_bounds(enabled=True,
										potency_ratio=None,
										delimit_by_numbers=True,
										max_followers=2100,
										max_following=800,
										min_followers=10,
										min_following=20)
	session.set_delimit_liking(enabled=True, max=99, min=0) # min/max number of likes for a photo that you can like
	session.set_dont_like(dont_likes)
	session.set_simulation(enabled=False)
	session.set_skip_users(skip_private=False,
					   private_percentage=0,
					   skip_no_profile_pic=True,
					   no_profile_pic_percentage=100,
					   skip_business=False,
					   business_percentage=100,
					   skip_business_categories=[],
					   dont_skip_business_categories=[])

	# actions
	session.set_user_interact(amount=1, randomize=True, percentage=100, media='Photo')
	session.set_do_follow(enabled=True, percentage=100, times = 1)
	session.set_do_like(enabled=True, percentage=70)
	
	session.like_by_tags(random.sample(like_tags_list, random.randint(18,21)), amount=random.randint(40,50), interact=True, skip_top_posts=True)
	session.like_by_locations(random.sample(like_locations_list, random.randint(14,16)), amount=random.randint(27,34), skip_top_posts=True)
		
	session.set_dont_include(friends)
	session.set_dont_unfollow_active_users(enabled=True, posts=5)
	session.unfollow_users(amount=random.randint(350,435), InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=161*60*60, sleep_delay=181)

#	session.like_by_feed(amount=100, randomize=True, unfollow=False, interact=False)

	session.set_quota_supervisor(enabled=True, 
									sleep_after=["likes", "follows", "unfollows", "server_calls"], 
									sleepyhead=True, 
									stochastic_flow=True,
									notify_me=True,
									peak_likes=(100, 1000),
									peak_comments=(1, 1),
									peak_follows=(60, 500),
									peak_unfollows=(120, 500),
									peak_server_calls=(700, None))

requests.get(
		"https://api.telegram.org/...")

```

**Comment by anitato** [comment]
I encounter varying error messages depending on the run. It's hard for me to pinpoint what is going on because of this. Am I just doing something wrong?

I'm running the most recent version of instapy on a clean install currently (followed the updated install directions), but this was a problem back when I was using an older version of instapy back in late February. Nothing seems to have changed.

```
[Session lasted 1.7 minutes]                                                                                                     

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO                                                         [984/1933]
INFO [2019-03-20 20:28:00] [user]  Session ended!                                                                   
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                                   
                                                                                                                                                                                                                                        
Traceback (most recent call last):                                                                                               
  File "quickstart.py", line 56, in <module>                                                                     
    session.like_by_tags(random.sample(like_tags_list, random.randint(18,21)), amount=random.randint(41,51), interact=True, skip_
top_posts=True)                                                                                                                  
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 1770, in like_by_tags                                   
    self.logfolder)                                                                                                              
  File "/usr/local/lib/python3.5/dist-packages/instapy/like_util.py", line 679, in like_image                                    
    like_elem = browser.find_elements_by_xpath(like_xpath)                                                                       
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 410, in find_elements_by_xpath      
    return self.find_elements(by=By.XPATH, value=xpath)                                                                          
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 1007, in find_elements              
    'value': value})['value'] or []                                                                                              
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute                     
    self.error_handler.check_response(response)                                                                                  
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response           
    raise exception_class(message, screen, stacktrace)                                                                           
selenium.common.exceptions.WebDriverException: Message: unknown error: unknown sessionId                                         
  (Session info: headless chrome=65.0.3325.181)                                                                                  
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.27-v7+ armv7l)   
```

**Comment by captv89** [comment]
While using function `session.follow_commenters` i have rcvd the following error and RPi B+ has crashed after about 1 hr of running.. the same function works alright on mac.. I didn't open a new issue as I believe its due to memory issue.. 
`Traceback (most recent call last):
  File "interactiveGuy.py", line 86, in 
    session.follow_commenters((random.sample(accounts,3)), amount=random.randint(90,117), daysold=120, max_pic = 100, sleep_delay=random.randint(360, 630), interact=True)
  File "/home/pi/virtual_env/instapy/lib/python3.5/site-packages/instapy/instapy.py", line 733, in follow_commenters
    max_pic)
  File "/home/pi/virtual_env/instapy/lib/python3.5/site-packages/instapy/commenters_util.py", line 241, in extract_information
    user_commented_list, pic_date_time = extract_post_info(browser)
  File "/home/pi/virtual_env/instapy/lib/python3.5/site-packages/instapy/commenters_util.py", line 61, in extract_post_info
    comments = comment_list.find_elements_by_tag_name('li')
  File "/home/pi/virtual_env/instapy/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 320, in find_elements_by_tag_name
    return self.find_elements(by=By.TAG_NAME, value=name)
  File "/home/pi/virtual_env/instapy/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 685, in find_elements
    {"using": by, "value": value})['value']
  File "/home/pi/virtual_env/instapy/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/pi/virtual_env/instapy/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/virtual_env/instapy/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)`

**Comment by chuck-23** [comment]
Have you guys found any solution to this?

**Comment by anitato** [comment]
Nope. Same old, same old. Still crashed in the middle of the script. No clear pattern/reason why.

**Comment by hugio55** [comment]
Yeah, having this same issue too, sadly.

**Comment by chuck-23** [comment]
Here is another error I usually get in another machine (also with Ubuntu 18.04)

```
Traceback (most recent call last):
  File "carlos.py", line 73, in <module>
    session.like_by_tags(my_hashtags, amount=60, media=None)
  File "/home/carlos/.local/lib/python2.7/site-packages/instapy/instapy.py", line 1879, in like_by_tags
    reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 44: ordinal not in range(128)
```

**Comment by marcus-d5r** [comment]
Just weighing in, don't have a solution unfortunately.
But I'm also experiencing heavy unreliability when running InstaPy on Raspbi Model 3 B+.
Running headless-browser on
> Release = Raspbian GNU/Linux 9 (stretch)
> Kernel = Linux 4.14.98-v7+

Random crashes at different points in the script.

When running on my Macbook locally, it runs much more reliable.

**Comment by chuck-23** [comment]
For all of you. I've experienced that running the script on pip3 it turns -a bit- more stable and I get this errors less frequently (but I also get them unfortunately).

**Comment by tourhuntr** [comment]
i also get them on a pi3b+ with headless and pip3
