### ISSUE TITLE
Error with option "interact=True": Message: unknown error: cannot focus element

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4194]
## Expected Behavior
Program works as always
## Current Behavior
Traceback (most recent call last):
  File "/home/dlenskyi/Desktop/smart_gear/my_functions/inter_tag.py", line 83, in inter_tag
    interact=True)
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 1821, in like_by_tags
    self.logfolder)
  File "/usr/local/lib/python3.7/site-packages/instapy/comment_util.py", line 78, in comment_image
    comment_input[0].send_keys('\b')
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot focus element
  (Session info: chrome=73.0.3683.75)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-46-generic x86_64)
## InstaPy configuration
def inter_tag():
    try:
        session = InstaPy(username=insta_username, 
                        password=insta_password, 
                        proxy_chrome_extension=proxy_chrome_extension, 
                        nogui=True)
        session.login()
        ############SETTINGS##############
        session.set_skip_users(skip_private=False, 
                            private_percentage=0, 
                            skip_no_profile_pic=True, 
                            no_profile_pic_percentage=100)
        session.set_do_follow(enabled=True, 
                            percentage=35)
        session.set_do_comment(enabled=True, 
                            percentage=40)

        session.set_comments(comments)

        session.set_do_like(enabled=True, 
                            percentage=70)
        session.set_user_interact(amount=1, 
                                randomize=True, 
                                percentage=80, 
                                media='Photo')
        ############SETTINGS##############
        session.unfollow_users(amount=200, 
                            nonFollowers=True, 
                            style="RANDOM",
                            unfollow_after=35 * 60 * 60, 
                            sleep_delay=300)
        session.follow_by_tags(my_hashtags, 
                            amount=35, 
                            randomize=True)
        session.like_by_tags(my_hashtags, 
                            amount=35, 
                            randomize=True, 
                            interact=True)
        session.end()
    except:
        import traceback
        print(traceback.format_exc())

I'm running this configuration for both of my accounts. For first account there is no problem and it works fine, but for the second account almost every time there is an error, which I posted above. What to do?

**Comment by dlenskyi** [comment]
This behavior occures when user is trying to comment post, and I have the latest version of InstaPy

**Comment by dlenskyi** [comment]
Problem solved, second account got banned.

**Comment by dlenskyi** [comment]
That was not solved, on my account without ban there is the same error
