### ISSUE TITLE
Help: Problem with start/login [pi]

### ISSUE THREAD

**Issue by xerZV** [InstaPy/InstaPy#4204]
Raspberry pi b+ (Raspbian)

The InstaPy was running perfectly but I had to reinstall the raspbian.
Followed the installation tips 
```
sudo apt-get install chromium-browser
python3 -m pip install --user instapy
python3 -m pip uninstall instapy-chromedriver
python3 -m pip install instapy-chromedriver==2.36.post0
```
It started for the first time and then failed and cant start again.

It loads the chrome and then boom this errors

![help](https://user-images.githubusercontent.com/23699044/54867643-42eafc80-4d8b-11e9-8fa2-077fb8a31111.JPG)

**Comment by tE3m** [comment]
It seems like that's a connection issue. Is your internet connection stable?

**Comment by xerZV** [comment]
Yes, it is stable. I can login into Instagram. The chrome starts, loads the instagram page and trying to click login and then fails in the console but the chrome remains open and I can manually login.

**Comment by billidani7** [comment]
I have the exact same issue I tried the new instructions with no luck

[https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md](url)

**Comment by NLJames** [comment]
I am having the exact same problem, script runs on my mac but not on my RPi B+. Exact same events and errors. Did you figure out the issue in the end?

**Comment by xerZV** [comment]
No. Nobody helped me.
I tried with reinstall raspbian (clear install) - nope.
I even cant run `pip3 install instapy -U` because there is an error with pip main method.
Now the bot is running with `python3 startFile.py --headless-browser` and cannot run only with `python3 startFile.py`

I asked for help in the Discord chat - nothing.

**Comment by xerZV** [comment]
> I am having the exact same problem, script runs on my mac but not on my RPi B+. Exact same events and errors. Did you figure out the issue in the end?

No. Nobody helped me.
I tried with reinstall raspbian (clear install) - nope.
I even cant run `pip3 install instapy -U` because there is an error with pip main method.
Now the bot is running with `python3 startFile.py --headless-browser` and cannot run only with `python3 startFile.py`

I asked for help in the Discord chat - nothing.

**Comment by NLJames** [comment]
Oh yeh I went through the 'main error' problem too. In the end I uninstalled pip then reinstalled it. try `python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall` I think that is how I eventually fixed it. but still I am getting this output when trying to run the quickstart script.



`Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 33, in <module>
    with smart_run(session):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1683, in smart_run
    session.login()
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 393, in login
    self.bypass_with_mobile):
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/login_util.py", line 173, in login_user
    reload_webpage(browser)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1710, in reload_webpage
    browser.execute_script("location.reload()")
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))`

Actually the first time I have successfully logged in was just now using your suggestion `python3 startFile.py --headless-browser` so thanks!!

**Comment by xerZV** [comment]
@nebulloyd Yeah, that's cool but it's not a solution for the problem. Its just workaround... I need to run it without `--headless-browser` option. 
I will try `python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall` for the pip3 'main error' problem!

**Comment by NLJames** [comment]
Yeh sorry I am very new to all this, I would only keep trawling through threads like this trying different commands and filling my pi with crap! Do let me know if we get a miracle answer though...

**Comment by xerZV** [comment]
Wait what? The  issue has not been resolved yet!!
