### ISSUE TITLE
Timeout on get_url

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4213]
## Current Behavior
There was a mistake:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instapy/util.py", line 1045, in web_address_navigator
    browser.get(link)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-46-generic x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dlenskyi/Desktop/smart_gear/my_functions/inter_user_followers.py", line 78, in inter_user_followers
    randomize=True)
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 2834, in interact_user_followers
    validation, details = self.validate_user_call(person)
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 1180, in validate_user_call
    self.logfolder)
  File "/usr/local/lib/python3.7/site-packages/instapy/util.py", line 273, in validate_username
    web_address_navigator(browser, user_link)
  File "/usr/local/lib/python3.7/site-packages/instapy/util.py", line 1058, in web_address_navigator
    str(exc).encode("utf-8")))
selenium.common.exceptions.TimeoutException: Message: Retried 7 times to GET 'b'https://www.instagram.com/oleksandr.troyan/'' webpage but failed out of a timeout!
 b'Message: timeout\n  (Session info: chrome=73.0.3683.86)\n  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-46-generic x86

Why this error occured?
Timeout on getting image_url
I’m running latest version of instapy.

**Comment by dlenskyi** [comment]
Can someone tell me what’s the problem?
I get this error every second time
