### ISSUE TITLE
Instapy slash windows 

### ISSUE THREAD

**Issue by AshrafArab2019** [InstaPy/InstaPy#4217]
Traceback (most recent call last):
  File "C:/Users/XXX/AppData/Local/Programs/Python/Python37-32/Lib/site-packages/instapy/quickstart.py", line 19, in <module>
    from instapy import InstaPy
  File "C:/Users/XXX/AppData/Local/Programs/Python/Python37-32/Lib/site-packages/instapy\instapy.py", line 20, in <module>
    from .comment_util import comment_image
ImportError: attempted relative import with no known parent package

I think that the problem is in slash\Instapy.py  C:/Users/XXX/AppData/Local/Programs/Python/Python37-32/Lib/site-packages/instapy\instapy.py"
but how to change it?

**Comment by CharlesCCC** [comment]
`pip install instapy` 
it seems like your instapy package is not installed correctly.

**Comment by AshrafArab2019** [comment]
> `pip install instapy`
> it seems like your instapy package is not installed correctly.
after install and update , same problem..
