### ISSUE TITLE
Failed to run quickstart.py (Chrome error)

### ISSUE THREAD

**Issue by lidoramrani** [InstaPy/InstaPy#4234]
I am experiencing problem while trying to run the quickstart.py file. I get this message: 

""

No any custom workspace provided.       ~using existing..
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/lidoramrani21/InstaPy"
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-04-01 12:00:53] [redteallo]  Using built in instapy-chromedriver executable (version 2.46)
ERROR [2019-04-01 12:01:00] [redteallo]  Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assumin
g that Chrome has crashed.)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-1028-gcp 
x86_64)
Traceback (most recent call last):
  File "/home/lidoramrani21/InstaPy/instapy/browser.py", line 146, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/lidoramrani21/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in
 __init__
    desired_capabilities=desired_capabilities)
  File "/home/lidoramrani21/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, i
n __init__
    self.start_session(capabilities, browser_profile)
  File "/home/lidoramrani21/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, i
n start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/lidoramrani21/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, i
n execute
    self.error_handler.check_response(response)
  File "/home/lidoramrani21/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242
, in check_response
    raise exception_class(message, screen, stacktrace)

""

How can I solve it?

**Comment by jvmvl** [comment]
Same problem
```
._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/root/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    headless_browser=False)
  File "/usr/local/lib/python2.7/dist-packages/instapy/instapy.py", line 287, in __init__
    self.set_selenium_local_session()
  File "/usr/local/lib/python2.7/dist-packages/instapy/instapy.py", line 339, in set_selenium_local_session
    self.logger)
  File "/usr/local/lib/python2.7/dist-packages/instapy/browser.py", line 88, in set_selenium_local_session
    chromedriver_location = get_chromedriver_location()
  File "/usr/local/lib/python2.7/dist-packages/instapy/file_manager.py", line 224, in get_chromedriver_location
    from instapy_chromedriver import binary_path
ImportError: No module named instapy_chromedriver
```

**Comment by shredstick** [comment]
You have to set "headless_browser=True" parameter in your start script. The default is usually "headless_browser=False" depending on your script. Here is an example:
 
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)
