### ISSUE TITLE
Like someone else's followers

### ISSUE THREAD

**Issue by jufelka** [InstaPy/InstaPy#4250]
## Expected Behavior
Hi. I need to like someone else's followers, so I make config:
session.set_simulation(enabled=True, percentage=66)
session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=True, percentage=100)
session.set_do_comment(enabled=False, percentage=80)
session.interact_user_followers(['user1', 'user2', 'user3', 'user4', 'user5'], amount=3, randomize=True)

## Current Behavior
I got this in log file:
On session start was FOLLOWING xxx users & had xxx FOLLOWERS
[Session lasted 40.03 seconds]
INFO [2019-04-02 16:00:42] [xxx]  Session ended!
INFO [2019-04-02 16:00:42] [xxx]  User 'username' [1/11]
INFO [2019-04-02 19:00:03] [xxx]  Session started!
INFO [2019-04-02 19:00:36] [xxx]  Logged in successfully!
INFO [2019-04-02 19:00:36] [xxx]  Saving account progress...
INFO [2019-04-02 19:00:39] [xxx]  Sessional Live Report:
	|> No any statistics to show

**Comment by primopierotz** [comment]
I'm having the same problem

**Comment by ThatDudeIsReal** [comment]
Same here, Updated to newest 4.0 Version. Must be a xPath Issue


Traceback (most recent call last):
  File "start.py", line 52, in <module>
    session.interact_user_followers(my_hashtags, amount=300, randomize=True)
  File "C:\InstaPy\instapy\instapy.py", line 2735, in interact_user_followers
    self.logfolder)
  File "C:\InstaPy\instapy\unfollow_util.py", line 1015, in get_given_user_followers
    logger, logfolder)
  File "C:\InstaPy\instapy\unfollow_util.py", line 743, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "C:\Program Files (x86)\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files (x86)\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files (x86)\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90),platform=Windows NT 10.0.17134 x86_64)

**Comment by anna-sunberg** [comment]
I'm having the same problem, but when I try to reproduce it with a non-headless browser to see what's going on, it works fine 🤔Will try to figure something out.

**Comment by primopierotz** [comment]
I think I have resolved

The problem, if I have understood well, is that Instagram put another div in the html page. xpath does not find the dialog div anymore.

So in the unfollow_util.py file, in instapy, you have to change line 809 (it may be different for you, it's after the line with     # find dialog box )

from
    dialog_address = "//body/div[2]/div/div[2]"
to
    dialog_address = "//body/div[3]/div/div[2]"

@timgrossmann maybe developers may check if I am right
(however, it works again for me)

**Comment by jufelka** [comment]
Doesn't work for me:

INFO [2019-04-04 23:07:27] [user]  User 'usertolike' [1/11]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7effbf625198>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 41, in <module>
    session.interact_user_followers(['...', '...', '...', '...', '...', '...', '...', '...', '...', '...', '...'], amount=3, randomize=True)
  File "/home/.../instapy/instapy.py", line 2801, in interact_user_followers
    self.logfolder)
  File "/home/.../instapy/unfollow_util.py", line 1036, in get_given_user_followers
    web_address_navigator(browser, user_link)
  File "/home/.../instapy/util.py", line 1025, in web_address_navigator
    current_url = get_current_url(browser)
  File "/home/.../instapy/util.py", line 1558, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=60553): Max retries exceeded with url: /session/d63d5bcedf0c5d256277080f4de65de7/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7effbf625198>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by akbarijedi** [comment]
> I think I have resolved
> 
> The problem, if I have understood well, is that Instagram put another div in the html page. xpath does not find the dialog div anymore.
> 
> So in the unfollow_util.py file, in instapy, you have to change line 809 (it may be different for you, it's after the line with # find dialog box )
> 
> from
> dialog_address = "//body/div[2]/div/div[2]"
> to
> dialog_address = "//body/div[3]/div/div[2]"
> 
> @timgrossmann maybe developers may check if I am right
> (however, it works again for me)

Thank You.
