### ISSUE TITLE
OSError: [Errno 8] Exec format error, ImportError: No module named... What is happening?

### ISSUE THREAD

**Issue by alexsmedile** [InstaPy/InstaPy#4254]
Hi, I keep having problem after problem with every InstaPy update. Last time, I couldn't get my head around, I actually cleaned up my Raspberry and installed a fresh version of Raspian on it. There was something wrong with Python, Pip, and InstaPy. Nobody was able to talk to the right version of the others so I started from scratch.

Now I'm back. Everything it's fresh and I shouldn't have any problem, or should I? Well, turns out I still have something wrong. I followed the [How_to_Raspberry](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md) guide and the first time I run my code I got something wrong with the row `page_delay=.5`, so I deleted it. Now, I don't know what's wrong with `bypass_suspicious_attempt=True`. I thought maybe it's because I need cookies before I can bypass any suspicious attempt, so I changed it to `false`. Then, same error, but with false (as you can see down below).

Going deeper into my error message, I thought, maybe it's chrome drivers fault. I updated InstaPy (as suggested in the guide) and chrome drivers, too.

If I try to run `python3 myscript.py` that's what I get:
```
Using built in instapy-chromedriver executable (version 2.46)
Traceback (most recent call last):
  File "z_schedule.py", line 4, in <module>
    from z_instabot import *
  File "/home/pi/InstaPy/z_instabot.py", line 14, in <module>
    bypass_suspicious_attempt=False)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 287, in __init__
    self.set_selenium_local_session()
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 339, in set_selenium_local_session
    self.logger)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/browser.py", line 146, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
```
`OSError: [Errno 8] Exec format error` I don't know what that means. But I searched the web and I found [this issue](https://github.com/timgrossmann/InstaPy/issues/1107) here on the InstaPy repository.

I installed selenium again. And I noticed that somebody also suggested to run it with `sudo`. So I tried it: `sudo python3 z_schedule.py`. That's when things start to get interesting:
```
Traceback (most recent call last):
  File "z_schedule.py", line 2, in <module>
    from z_config import *
  File "/home/pi/InstaPy/z_config.py", line 7, in <module>
    import os, csv, json, time, requests, re, gspread
ImportError: No module named 'gspread'
```
I'm back with the same problem I started last time.
I have installed gspread😭 what's wrong now!? Can somebody help me figure out how to fix it? Thanks.

**Comment by alexsmedile** [comment]
I fixed it. You need to install everything with `sudo pip3`.
