### ISSUE TITLE
Getting errors while running the script

### ISSUE THREAD

**Issue by jinayG** [InstaPy/InstaPy#4255]
I am running the quickstart script of @Nuzzo235
Getting the below error and the program is terminated when it is selecting the followers of the user. Also I Git dosent allow to attach HTML files which is generated.

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 114, in <module>
    interact=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 3134, in follow_user_followers
    self.logfolder)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\unfollow_util.py", line 1082, in get_given_user_followers
    logger, logfolder)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\unfollow_util.py", line 810, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

**Comment by CharlesCCC** [comment]
before post new issue, I highly suggest you read previous issue, in this case, it already been addressed.

**Comment by Kicke02** [comment]
> before post new issue, I highly suggest you read previous issue, in this case, it already been addressed.

Then wouldn't a link help him?

**Comment by CharlesCCC** [comment]
#4244

**Comment by jinayG** [comment]
Thanks a lot @CharlesCCC
