### ISSUE TITLE
New kind of error?

### ISSUE THREAD

**Issue by misterscraper** [InstaPy/InstaPy#4260]
**I'm running the following script;**

```python
""" Quickstart script for InstaPy usage """


# imports
from instapy import InstaPy
from instapy import smart_run
import schedule
import time

# login credentials
insta_username = 'XXXXXX'
insta_password = 'XXXXXX'

def likes():
  session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
  with smart_run(session):
    session.like_by_feed(amount=200, randomize=False, unfollow=False, interact=True)

def follows():
  session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
  with smart_run(session):
    session.set_relationship_bounds(enabled=False, delimit_by_numbers=False, max_followers=3000000, min_followers=1, min_following=1)
    session.set_skip_users(skip_private=False)
    session.follow_user_following(['XXXXXX','XXXXXX', 'XXXXXX', 'XXXXXX', 'XXXXXX'], amount=3000, randomize=False, sleep_delay=60)

schedule.every().day.at("9:30").do(likes)
schedule.every().day.at("12:00").do(likes)
schedule.every().day.at("13:00").do(likes)
schedule.every().day.at("16:00").do(follows)
schedule.every().day.at("21:00").do(likes)

while True:
 schedule.run_pending()
 time.sleep(1)
```

**It's been running fine for a good while but recently I've noticed I keep getting the following error;**

```
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/Nick/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-04-03 16:00:02] [XXXXXX]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

..............................................................
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-04-03 16:00:38] [XXXXXX]  Logged in successfully!
INFO [2019-04-03 16:00:38] [XXXXXX]  Saving account progress...
____________________________________________________________________________
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-04-03 16:00:42] [XXXXXX]  Starting to follow user `Following`..
INFO [2019-04-03 16:00:42] [XXXXXX]  User 'XXXXXX' [1/5]
WARNING [2019-04-03 16:00:45] [XXXXXX]  'XXXXXX' has less following- 1772 than the desired amount of 3000
**********************************************************************
If raising an issue, please also upload the file located at:
/var/folders/jt/dmqg3jy51qx7_vm0sjmppds40000gn/T/20190403-160113.html
**********************************************************************

INFO [2019-04-03 16:01:13] [XXXXXX]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 3383 users & had 300 FOLLOWERS
[Session lasted 1.22 minutes]
INFO [2019-04-03 16:01:13] [XXXXXX]  Session ended!
Traceback (most recent call last):
  File "/Users/Nick/Downloads/instapy-quickstart-master/quickstart.py", line 31, in <module>
    schedule.run_pending()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/schedule/__init__.py", line 493, in run_pending
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
ooooooooooooooooooooooooooooooooooooooooooooooooooooo



    default_scheduler.run_pending()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/schedule/__init__.py", line 78, in run_pending
    self._run_job(job)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/schedule/__init__.py", line 131, in _run_job
    ret = job.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/schedule/__init__.py", line 411, in run
    ret = self.job_func()
  File "/Users/Nick/Downloads/instapy-quickstart-master/quickstart.py", line 22, in follows
    session.follow_user_following(['XXXXXX','XXXXXX', 'XXXXXX', 'XXXXXX', 'XXXXXX'], amount=3000, randomize=False, sleep_delay=60)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/instapy/instapy.py", line 3303, in follow_user_following
    self.logfolder)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/instapy/unfollow_util.py", line 1186, in get_given_user_following
    logger, logfolder)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/instapy/unfollow_util.py", line 810, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Mac OS X 10.14.3 x86_64)

[Finished in 10437.676s]
```

Can anyone help me?

**Comment by CharlesCCC** [comment]
#4240

**Comment by misterscraper** [comment]
I'm now getting the following error again;

`INFO [2019-04-04 16:01:14] [nkcr.jpg]  Session ended!
Traceback (most recent call last):
  File "/Users/Nick/Downloads/instapy-quickstart-master/quickstart.py", line 31, in <module>
    schedule.run_pending()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/schedule/__init__.py", line 493, in run_pending
    default_scheduler.run_pending()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/schedule/__init__.py", line 78, in run_pending
    self._run_job(job)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/schedule/__init__.py", line 131, in _run_job
    ret = job.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/schedule/__init__.py", line 411, in run
    ret = self.job_func()
  File "/Users/Nick/Downloads/instapy-quickstart-master/quickstart.py", line 22, in follows
    session.follow_user_following(['alicekasslingerie','tommitchellphoto', 'rvds', 'deanmartindale', 'luccoiffait'], amount=3000, randomize=False, sleep_delay=60)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/instapy/instapy.py", line 3303, in follow_user_following
    self.logfolder)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/instapy/unfollow_util.py", line 1186, in get_given_user_following
    logger, logfolder)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/instapy/unfollow_util.py", line 810, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Mac OS X 10.14.3 x86_64)`

**Comment by misterscraper** [comment]
![Screenshot 2019-04-04 at 16 11 53](https://user-images.githubusercontent.com/33800433/55566862-736c5800-56f4-11e9-9962-dfe38f7b463d.png)

**Comment by CharlesCCC** [comment]
this is exact the same error you are getting.  the change didn't apply correctly, clean your *.pyc files.

**Comment by misterscraper** [comment]
> this is exact the same error you are getting. the change didn't apply correctly, clean your *.pyc files.

how am I able to do that in Atom on Mac OS?

**Comment by CharlesCCC** [comment]
@nkycldn a simple google should have give you the answer, but since you asked. 
It should within a folder named `__pycache__`

**Comment by davidkessler-ch** [comment]
Same for me, the error stays the same. I have cleared all the .pyc files....

**Comment by davidkessler-ch** [comment]
@CharlesCCC

> @nkycldn a simple google should have give you the answer, but since you asked.
> It should within a folder named `__pycache__`

I have deleted all .pyc files everywhere, as well as cookies and everything. The error persists as:

"Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/bot.py", line 36, in <module>
    interact=True, sleep_delay=200)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 3134, in follow_user_followers
    self.logfolder)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/unfollow_util.py", line 1082, in get_given_user_followers
    logger, logfolder)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/unfollow_util.py", line 810, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}
  (Session info: headless chrome=72.0.3626.121)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)"

**Comment by GeoffreyPG** [comment]
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[3]/div/div[2]"}
