### ISSUE TITLE
I get this error when doing the script shown in the video

### ISSUE THREAD

**Issue by Zerbster213** [InstaPy/InstaPy#4271]
Traceback (most recent call last):
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\login_util.py", line 260, in login_user
    "//div[text()='Log in']")
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Log in']"}
  (Session info: chrome=73.0.3683.103)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\Lib\site-packages\quickstart.py", line 34, in <module>
    with smart_run(session):
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\util.py", line 1683, in smart_run
    session.login()
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\instapy.py", line 386, in login
    self.bypass_with_mobile):
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\login_util.py", line 264, in login_user
    "//div[text()='Log In']")
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Zerb\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Log In']"}
  (Session info: chrome=73.0.3683.103)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

**Comment by CharlesCCC** [comment]
@timgrossmann i think it is time to merge my login fix :)

**Comment by timgrossmann** [comment]
@CharlesCCC Already in there 😋 
Thanks for the fix 😊

**Comment by oppugnator** [comment]
hey guys,

I'm still getting this error...

is it the same issue?!


```
  File "/anaconda3/lib/python3.7/site-packages/instapy/util.py", line 1092, in highlight_print
    output_len = (28 + len(username) + 3 + len(message) if logger

TypeError: object of type 'NoneType' has no len()
```

**Comment by CharlesCCC** [comment]
@oppugnator your issue is different than this original issue, you can create a new issue with the issue template. 
(please close it @Zerbster213 if it not an issue anymore).
