### ISSUE TITLE
Cannot start - Remote end closed connection without response

### ISSUE THREAD

**Issue by xerZV** [InstaPy/InstaPy#4277]
Trying to start instapy on raspberry pi b+ with `python3 quickstart.py` and get this error.
This was working perfectly  for almost 3 months before reinstall the raspbian.
```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 8, in <module>
    with smart_run(session):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1683, in smart_run
    session.login()
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 393, in login
    self.bypass_with_mobile):
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/login_util.py", line 167, in login_user
    browser.add_cookie(cookie)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 894, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

I have stable network connection and it starts with `python3 quickstart.py --headless-browser`

**Comment by NLJames** [comment]
same problem here

**Comment by xerZV** [comment]
> same problem here

No. Nobody helped me.
I tried with reinstall raspbian (clear install) - nope.
I even cant run pip3 install instapy -U because there is an error with pip main method.
Now the bot is running with python3 startFile.py --headless-browser and cannot run only with python3 startFile.py

I asked for help in the Discord chat - nothing.

**Comment by rox-wolf** [comment]
I'm also getting the same issue on Raspberry Pi 3+ It starts Chromium and then crashes with the same error.

**Comment by xerZV** [comment]
> I'm also getting the same issue on Raspberry Pi 3+ It starts Chromium and then crashes with the same error.

Try with `python3 quickstart.py --headless-browser` . But its not the problem's solution

**Comment by lizechoo** [comment]
same, anyone can help with this?

**Comment by lizechoo** [comment]
@xerZV that worked, thanks! Is there a more permanent fix for this?

**Comment by xerZV** [comment]
> @xerZV that worked, thanks! Is there a more permanent fix for this?

Still waiting for fix but I think no one thinks its a problem.....

**Comment by xerZV** [comment]
anybody?>

**Comment by dsmh** [comment]
Same problem here, any clue?

**Comment by dsmh** [comment]
I just tried with a fresh installation and worked. 

> Same problem here, any clue?

**Comment by xerZV** [comment]
> I just tried with a fresh installation and worked.
> 
> > Same problem here, any clue?


The problem is still there
Did fresh installation work for you? I tried 2 fresh installations but didn't work

**Comment by dsmh** [comment]
> > I just tried with a fresh installation and worked.
> > > Same problem here, any clue?
> 
> The problem is still there
> Did fresh installation work for you? I tried 2 fresh installations but didn't work

You are totally right, the problem still there. My fresh installation just died this morning with the same error.

**Comment by tE3m** [comment]
About that pip thing with the error that can't import main: instead of `pip3`, use `python3 -m pip`. That is a workaround, even though I don't know what causes the error. If it persists, create an alias

**Comment by psvtg** [comment]
same thing RPi3, Python 3.5

**Comment by kev-mas** [comment]
I'm getting `Failed to establish a new connection: [Errno 111] Connection refused`

```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=36078): Max retries exceeded with url: /session/e301c77420c29d05d294ab0df1557958/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbd37ec4d50>: Failed to establish a new connection: [Errno 111] Connection refused',))

```

**Comment by xerZV** [comment]
Anyone?

**Comment by kev-mas** [comment]
Still getting the same issue. I've tried fresh installation, docker... Always the same.

**Comment by kev-mas** [comment]
This is the full error I get:

```
INFO [2019-05-20 14:10:21] [insta_account]  Tag [1/47]
INFO [2019-05-20 14:10:21] [insta_account]  --> b'tagname'
Traceback (most recent call last):
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f90a4f25e80>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insta.py", line 206, in <module>
    session.like_by_tags(lon_tags, amount=randomnumber, media='Photo', skip_top_posts=True)
  File "/home/superman/.local/lib/python3.6/site-packages/instapy/instapy.py", line 1726, in like_by_tags
    self.logger)
  File "/home/superman/.local/lib/python3.6/site-packages/instapy/like_util.py", line 234, in get_links_for_tag
    web_address_navigator(browser, tag_link)
  File "/home/superman/.local/lib/python3.6/site-packages/instapy/util.py", line 1029, in web_address_navigator
    current_url = get_current_url(browser)
  File "/home/superman/.local/lib/python3.6/site-packages/instapy/util.py", line 1562, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/home/superman/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/superman/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/superman/.local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/superman/.local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 326, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/superman/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=59961): Max retries exceeded with url: /session/e6de9d19f210955bdd50b57ad57be7a2/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a4f25e80>: Failed to establish a new connection: [Errno 111] Connection refused',))
```


I've tried many different ways and are not able to get it to work. I see other users have the same issue, but I can't find a solution.

Any idea/suggestion on how to fix this @timgrossmann ?

**Comment by kev-mas** [comment]
Ok, got it to work.

It looks like it was for some reason caused by some comments I had in the top, and wrong indentation throughout the file... 

The only weird thing is that descriptions look odd ad the moment.

```
Description: b'\xd0\x90 \xd0\xb2\xd1\x8b \xd0\xb7\xd0\xb0\xd0\xbc\xd0\xb5\xd1\x87\xd0\xb0\xd0\xb5\xd1\x82\xd0\xb5 \xd0\xbc\xd0\xb5\xd0\xbb\xd0\xbe\xd1\x87\xd0\xb8 , \xd0\xba\xd0\xbe\xd1\x82\xd0\xbe\xd1\x80\xd1\x8b\xd0\xb5 \xd0\xb4\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x8e\xd1\x82 \xd0\xbd\xd0\xb0\xd1\x88\xd1\x83 \xd0\xbb\xd1\x8e\xd0\xb1\xd0\xbe\xd0\xb2\xd1\x8c \xd0\xb2\xd0\xb0\xd0\xb6\xd0\xbd\xd0\xb5\xd0\xb5? \xd0\x9d\xd0\xb0\xd0\xbf\xd1\x80\xd0\xb8\xd0\xbc\xd0\xb5\xd1\x80, \xd0\xba\xd0\xbe\xd0\xb3\xd0\xb4\xd0\xb0 \xd1\x82\xd0\xb0\xd0\xba \xd1\x82\xd0\xb8\xd1\x85\xd0\xbe \xd0\xb7\xd0\xb0\xd0\xba\xd1\x80\xd1\x8b\xd0\xb2\xd0\xb0\xd1\x8e\xd1\x82 \xd0\xb4\xd0\xb2\xd0\xb5\xd1\x80\xd1\x8c, \xd1\x87\xd1\x82\xd0\xbe\xd0\xb1\xd1\x8b \xd0\xbd\xd0\xb5 \xd1\x80\xd0\xb0\xd0\xb7\xd0\xb1\xd1\x83\xd0\xb4\xd0\xb8\xd1\x82\xd1\x8c. \xd0\x9a\xd0\xb0\xd0\xba \xd1\x80\xd0\xb0\xd0\xb7\xd1\x80\xd0\xb5\xd1\x88\xd0\xb0\xd1\x8e\xd1\x82 \xd1\x81\xd1\x8a\xd0\xb5\xd1\x81\xd1\x82\xd1\x8c \xd0\xb2\xd0\xb8\xd1\x88\xd0\xb5\xd0\xbd\xd0\xba\xd1\x83 \xd0\xb8\xd0\xb7 \xd1\x81\xd0\xb2\xd0\xbe\xd0\xb5\xd0\xb3\xd0\xbe \xd0\xba\xd0\xbe\xd0\xba\xd1\x82\xd0\xb5\xd0\xb9\xd0\xbb\xd1\x8f, \xd0\xba\xd0\xb0\xd0\xba \xd1\x83\xd1\x82\xd1\x80\xd0\xbe\xd0\xbc \xd0\xb2\xd1\x81\xd1\x82\xd0\xb0\xd1\x8e\xd1\x82 \xd0\xbd\xd0\xb5\xd0\xbc\xd0\xbd\xd0\xbe\xd0\xb6\xd0\xba\xd0\xbe \xd1\x80\xd0\xb0\xd0\xbd\xd1\x8c\xd1\x88\xd0\xb5, \xd1\x87\xd1\x82\xd0\xbe\xd0\xb1\xd1\x8b \xd1\x83\xd1\x81\xd0\xbf\xd0\xb5\xd1\x82\xd1\x8c \xd0\xbf\xd1\x80\xd0\xb8\xd0\xb3\xd0\xbe\xd1\x82\xd0\xbe\xd0\xb2\xd0\xb8\xd1\x82\xd1\x8c \xd0\xb7\xd0\xb0\xd0\xb2\xd1\x82\xd1\x80\xd0\xb0\xd0\xba \xd0\xb8 \xd1\x85\xd0\xbe\xd0\xb4\xd1\x8f\xd1\x82 \xd0\xbd\xd0\xb0 \xd1\x86\xd1\x8b\xd0\xbf\xd0\xbe\xd1\x87\xd0\xba\xd0\xb0\xd1\x85. \xd0\x9d\xd0\xb5\xd0\xb6\xd0\xbd\xd0\xbe \xd0\xbe\xd0\xb1\xd0\xbd\xd0\xb8\xd0\xbc\xd0\xb0\xd1\x8e\xd1\x82 \xd0\xbf\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb4 \xd1\x81\xd0\xbd\xd0\xbe\xd0\xbc. \xd0\x9b\xd1\x8e\xd0\xb1\xd0\xbe\xd0\xb2\xd1\x8c \xd1\x81\xd0\xbe\xd1\x81\xd1\x82\xd0\xbe\xd0\xb8\xd1\x82  \xd0\xb8\xd0\xb7 \xd1\x82\xd0\xb0\xd0\xba\xd0\xb8\xd1\x85 \xd0\xbd\xd0\xb5\xd0\xb6\xd0\xbd\xd1\x8b\xd1\x85 \xd0\xb5\xd0\xb6\xd0\xb5\xd0\xb4\xd0\xbd\xd0\xb5\xd0\xb2\xd0\xbd\xd1\x8b\xd1\x85 \xd0\xbc\xd0\xb5\xd0\xbb\xd0\xbe\xd1\x87\xd0\xb5\xd0\xb9. \xd0\x98 \xd0\xb2\xd0\xb0\xd0\xb6\xd0\xbd\xd0\xbe \xd0\xb7\xd0\xb0\xd0\xbc\xd0\xb5\xd1\x87\xd0\xb0\xd1\x82\xd1\x8c \xd0\xb8\xd1\x85 \xd0\xb2 \xd0\xb5\xd0\xb6\xd0\xb5\xd0\xb4\xd0\xbd\xd0\xb5\xd0\xb2\xd0\xbd\xd0\xbe\xd0\xb9 \xd1\x81\xd1\x83\xd0\xbc\xd0\xb0\xd1\x82\xd0\xbe\xd1\x85\xd0\xb5 \xf0\x9f\x92\x93\n\xe2\xa0\x80\n\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\n\xd0\x9f\xd1\x80\xd0\xbe\xd1\x81\xd1\x82\xd0\xbe \xd1\x81\xd0\xb5\xd0\xb3\xd0\xbe\xd0\xb4\xd0\xbd\xd1\x8f \xd0\xb4\xd0\xb5\xd0\xbd\xd1\x8c \xd0\xb2\xd0\xbb\xd1\x8e\xd0\xb1\xd0\xbb\xd1\x91\xd0\xbd\xd0\xbd\xd1\x8b\xd1\x85 \xd0\xb2 \xd0\x9a\xd0\xb8\xd1\x82\xd0\xb0\xd0\xb5 \xe2\x99\xa1 \xe2\x99\xa1 \xe2\x99\xa1'

```

**Comment by xerZV** [comment]
Wow, in my case it cant start and gets the remote error

**Comment by NLJames** [comment]
I found if I added one follow command first at the start of my script before letting it do the unfollow bit that it works perfectly. Seems to be able to establish a connection when that is the first action which I realised since my follow script is working fine. It’s not pretty but it’s efficient and most importantly, it works...

________________________________

**Comment by Areahints** [comment]
this bug still present

**Comment by xerZV** [comment]
@Areahints Yep. Same! Still no solution. Try with` python3 quickstart.py --headless-browser` . But this is not the problem's solution.

**Comment by TheVashishth** [comment]
I think the problem might be in your pip version or in a urllib3 module. So, first, update the urllib3 and pip to the latest version and try again. For your urllib3 connectionpool.py file problem, Please refers following links


https://stackoverflow.com/questions/48105448/python-http-server-client-remote-end-closed-connection-without-response-error

and for the crashing issue in raspberry pi look out in this issue #4149

**Comment by xerZV** [comment]
> I think the problem might be in your pip version or in a urllib3 module. So, first, update the urllib3 and pip to the latest version and try again. For your urllib3 connectionpool.py file problem, Please refers following links
> 
> https://stackoverflow.com/questions/48105448/python-http-server-client-remote-end-closed-connection-without-response-error
> 
> and for the crashing issue in raspberry pi look out in this issue #4149

Hello @Dark-Atom, I have a problem with pip3 too. There is error in main 
`  File "/usr/bin/pip3", line 9, in <module>
    from pip import main`

**Comment by stevecohenfr** [comment]
In my case adding nogui=True and running in a screen was causing this error. I leaves the screen and it word fine. In think in a screen you need to export DISPLAY:=0

**Comment by tjuzen** [comment]
anyone still has the problem? cant figure out the solution, tried your answers but didnt work ..
edit : i can make it work by spamming python3 quickstart.py, it works 1 times on 20

**Comment by xerZV** [comment]
I still have the problem. Try with `python3 quickstart.py --headless-browser` as workaround

**Comment by xerZV** [comment]
@timgrossmann Can you please help with that one? The problem is still there. I am running it on a raspberry pi 3b+
It was running perfectly before reinstall the Pi.

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 8, in <module>
    with smart_run(session):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1679, in smart_run
    session.login()
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 407, in login
    self.bypass_with_mobile):
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/login_util.py", line 167, in login_user
    browser.add_cookie(cookie)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 894, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```
