### ISSUE TITLE
First run issue - clarifai 2.6.1

### ISSUE THREAD

**Issue by Minnen** [InstaPy/InstaPy#4278]
I have just downloaded and installed instapy, **during installation i had an [error message](https://pastebin.com/raw/HbNa660G)** and when i try to run 'quickstart.py' as shown in the youtube tutorial i get the following error:

```
Traceback (most recent call last):
  File "C:\Users\JWST\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "C:\Users\JWST\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 22, in <module>
    from .clarifai_util import check_image
ImportError: attempted relative import with no known parent package
```
I get that output while trying to initialize the script 'quickstart.py' for the first run from IDLE.

Looking forward to solve this and start using this bot.

Thanks in advance.

**UPDATE**

I did a full clean reinstall of both python and intapy and was able to narrow down the issue to the following output during instapy installation:

```
clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.
0.1 which is incompatible.
```
[Here's the complete updated installation log from instapy.](https://pastebin.com/raw/U7fHhjnf)

**Comment by Minnen** [comment]
**ISSUE SOLVED**

_Further info about the solution_

I made a clean reinstall of both python and intapy, python in installation was made withe admin rights this time and the PATH checkbox was selectd, received no errors druing installation, instapy was installed after a reboot of the system and it gave no errors regarding the paths associations this time, clarifi however did had a minor issue regarding its jsonschema requirement as stated in the update on the post but this time i was able to run the instapy module from IDLE successfully.

Hope this helps people with future issues of this kind.
