### ISSUE TITLE
If raising an issue, please also upload the file located at

### ISSUE THREAD

**Issue by KingCodeKing** [InstaPy/InstaPy#4285]
eror please help 

If raising an issue, please also upload the file located at:
C:\Users\Click\AppData\Local\Temp\20190408-172336.html
**********************************************************************

INFO [2019-04-08 17:23:39] [havijshop]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 3763 users & had 1618 FOLLOWERS
[Session lasted 51.69 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-04-08 17:23:39] [havijshop]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    randomize=True)
  File "C:\Users\Click\Desktop\New folder\InstaPy-master\instapy\instapy.py", line 3146, in follow_user_followers
    self.logfolder)
  File "C:\Users\Click\Desktop\New folder\InstaPy-master\instapy\unfollow_util.py", line 1082, in get_given_user_followers
    logger, logfolder)
  File "C:\Users\Click\Desktop\New folder\InstaPy-master\instapy\unfollow_util.py", line 810, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "C:\Users\Click\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Click\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Click\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Click\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[3]/div/div[2]"}
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

{"method":"xpath","selector":"//body/div[3]/div/div[2]"}
change but eror
please help

**Comment by jointyje** [comment]
ya same, since a few days ago

**Comment by w1s3m4n** [comment]
Same here. It seems that HTML has changed again...

**Comment by papillon-unix** [comment]
same for me since few days.. any idea to fix it?

**Comment by callaghanjames** [comment]
Anything on this yet?

**Comment by prospekt123** [comment]
Same problem with 3 accounts in Ubuntu...
