### ISSUE TITLE
Message: unknown error: cannot focus element

### ISSUE THREAD

**Issue by dpashutskii** [InstaPy/InstaPy#4310]
## Expected Behavior
The bot works without error
## Current Behavior
I get this error, tried to update bot and update chrome driver. The bot running on DO server ( Ubuntu 16.04.6 LTS)

```
Traceback (most recent call last):
  File "quickstart.py", line 99, in <module>
    session.follow_user_followers(random_targets, amount=random.randint(20, 30), randomize=True, sleep_delay=600, interact=True)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 3210, in follow_user_followers
    interact)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 1095, in follow_by_list
    self.user_interact_media)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 2357, in interact_by_users
    self.logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/comment_util.py", line 78, in comment_image
    comment_input[0].send_keys('\b')
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot focus element
  (Session info: headless chrome=73.0.3683.103)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.4.0-145-generic x86_64)
```
## InstaPy configuration
my quickstart.py:
```
import random
from instapy import InstaPy
from instapy import smart_run
import requests
from datetime import datetime

# telegram message function
def telegram_bot_sendtext(bot_message):

    bot_token = <token>
    bot_chatID = <bot_id>

    send_text = 'https://api.telegram.org/bot' + bot_token + '/sendMessage?chat_id=' + bot_chatID + '&parse_mode=Markdown&text=' + bot_message
    response = requests.get(send_text)

    return response.json()

# login credentials
insta_username = <username>
insta_password = <password>

# restriction data
dont_likes = ['#sex', '#dick', '#pussy', '#squirt', '#gay', '#naked', '#fight']
ignore_users = []

""" Prevent commenting on and unfollowing your good friends (the images will
still be liked)...
"""
friends = [<my friends list>]

""" Prevent posts that contain...
"""
ignore_list = []

# TARGET data
""" Set similar accounts and influencers from your niche to target...
"""
targets = [<instagram targets>]

""" Skip all business accounts, except from list given...
"""

# COMMENT data
comments = [<my comments>]

telegram_bot_sendtext("InstaPy interaction started @ {}".format(datetime.now().strftime("%H:%M:%S")))

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
		  headless_browser=True,
                  multi_logs=True)

# let's go! :>
with smart_run(session):
    # general settings
    session.set_dont_include(friends)
    session.set_dont_like(dont_likes)
    session.set_ignore_if_contains(ignore_list)
    session.set_ignore_users(ignore_users)
    session.set_simulation(enabled=True)
    session.set_relationship_bounds(enabled=True, potency_ratio=None)

    session.set_smart_hashtags(['travel', 'wanderlust'], limit=15, sort='random', log_tags=True)
    session.set_skip_users(skip_private=True, skip_no_profile_pic=True)

    session.set_user_interact(amount=3, randomize=True, percentage=60, media='Photo')
    session.set_do_like(enabled=True, percentage=40)
    session.set_do_comment(enabled=True, percentage=15)
    session.set_comments(comments, media='Photo')
    session.set_do_follow(enabled=True, percentage=40, times=1)

    # activities

    # FOLLOW+INTERACTION on TARGETED accounts
    """ Select users form a list of a predefined targets...
    """
    number = random.randint(3, 5)
    random_targets = targets

    if len(targets) <= number:
        random_targets = targets

    else:
        random_targets = random.sample(targets, number)

    """ Interact with the chosen targets
    """
    session.follow_user_followers(random_targets, amount=random.randint(20, 30), randomize=True, sleep_delay=600, interact=True)

    """ Liking by smart hashtags.
    """
    session.like_by_tags(amount=10, use_smart_hashtags=True)

    telegram_bot_sendtext("InstaPy interaction stoped @ {}".format(datetime.now().strftime("%H:%M:%S")))

    # UNFOLLOW activity
    """ Unfollow nonfollowers after 50 hours
    """
    telegram_bot_sendtext("Bot 50 hours unfollowing started at {}'".format(datetime.now().strftime("%H:%M:%S")))

    session.unfollow_users(amount=random.randint(150, 200),
                           InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=50 * 60 * 60, sleep_delay=600)

    """ Unfollow all users followed by InstaPy after 300 hours to keep the
    following-level clean
    """
    telegram_bot_sendtext("InstaPy Weekly Unfollowing Started at {}'".format(datetime.now().strftime("%H:%M:%S")))

    session.unfollow_users(amount=random.randint(500, 600),
                           InstapyFollowed=(True, "all"), style="FIFO",
                           unfollow_after=300  * 60 * 60, sleep_delay=600)

    telegram_bot_sendtext("InstaPy unfollowing stopped @ {}".format(datetime.now().strftime("%H:%M:%S")))
```

**Comment by dpashutskii** [comment]
Still having this issue. @timgrossmann, @uluQulu, @converge can you help me out? I don't know python but ready to assist as much as possible :)

**Comment by yossi-levi** [comment]
I'm having the same issue, any chance someone can help here?

**Comment by thomaslc66** [comment]
Same issue here, is there any change in the instagram website ? Or is it just a chrome driver issue ?

**Comment by dpashutskii** [comment]
For me, the error just disappears. Don't know what was the reason.

**Comment by alexsmedile** [comment]
Same issue

```
Traceback (most recent call last):
  File "/home/pi/InstaPy/z_instabot.py", line 255, in interact_by
    randomize=True)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 2890, in interact_user_followers
    self.user_interact_media)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 2350, in interact_by_users
    self.logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/comment_util.py", line 78, in comment_image
    comment_input[0].send_keys('\b')
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot focus element
  (Session info: headless chrome=72.0.3626.121)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.57-v7+ armv7l)
```
