### ISSUE TITLE
Mandatory Language feature not working...

### ISSUE THREAD

**Issue by mystechal** [InstaPy/InstaPy#4333]
## Expected Behavior

Restrict the interactions, liking and following if any character of the description is outside of the character set selected (the location is not included and non-alphabetic characters are ignored). For example if you choose LATIN, any character in Cyrillic will flag the post as inappropriate.

## Current Behavior

Receive following error when enabled in instapy.py...

Traceback (most recent call last):
  File "/home/InstaPy/instapy/instapy.py", line 5157, in is_mandatory_character
    return self.check_letters[uchr]
KeyError: 'U'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/InstaPy/instapy/instapy.py", line 1758, in like_by_tags
    self.logger)
  File "/home/InstaPy/instapy/like_util.py", line 609, in check_link
    if not check_character_set(image_text):
  File "/home/InstaPy/instapy/instapy.py", line 5177, in check_character_set
    for uchr in unistr
  File "/home/InstaPy/instapy/instapy.py", line 5178, in <genexpr>
    if uchr.isalpha())
  File "/home/InstaPy/instapy/instapy.py", line 5161, in is_mandatory_character
    unicodedata.name(uchr))
TypeError: 'in <string>' requires string as left operand, not list

Any ideas on how to resolve this? Have checked PR from #3434

**Comment by mystechal** [comment]
Anyone???

**Comment by visualheroes** [comment]
I use it everyday without any problem. However i'm a couple of versions behind. 
I'll try to update to the last version and re-test it when i have enough time.
