### ISSUE TITLE
follow_user_followers interact crash

### ISSUE THREAD

**Issue by danielbeltejar** [InstaPy/InstaPy#4337]
Traceback (most recent call last):
  File "alejandra.py", line 115, in <module>
    randomize=True, sleep_delay=350,interact=True)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 32
03, in follow_user_followers
    interact)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 10
56, in follow_by_list
    self.logfolder)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/unfollow_util.py", l
ine 704, in follow_user
  gfolder)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/unfollow_util.py", l
ine 1547, in verify_action
  load_webpage(browser)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 1710,
 in reload_webpage
  owser.execute_script("location.reload()")
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/we
bdriver.py", line 636, in execute_script
  rgs': converted_args})['value']
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/we
bdriver.py", line 321, in execute
  lf.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/er
rorhandler.py", line 242, in check_response

**Comment by LuismiLabs** [comment]
Hey @danenco , sé que estás corriendo alrededor de 250 cuentas al tiempo, me podrías contactar por fa? Te envié un privado por discord.
