### ISSUE TITLE
basic_follow-unfollow_activity template doesn't work

### ISSUE THREAD

**Issue by ofromf** [InstaPy/InstaPy#4350]
ERROR [2019-04-23 11:48:07] [username]  Error occurred while deleting cookies from web browser!
        b'Message: invalid session id\n  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-47-generic x86_64)\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/instapy/util.py", line 1684, in smart_run
    yield
  File "quickstart.py", line 52, in <module>
    randomize=False, interact=False)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 3146, in follow_user_followers
    self.logfolder)
  File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 1082, in get_given_user_followers
    logger, logfolder)
  File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 903, in get_users_through_dialog
    person_list = dialog_username_extractor(buttons)
  File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 930, in dialog_username_extractor
    .find_elements_by_tag_name("a")[1].text)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=73.0.3683.103)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-47-generic x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 230, in close_browser
    browser.delete_all_cookies()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid session id
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-47-generic x86_64)

INFO [2019-04-23 11:48:08] [andikilli]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 165 users & had 733 FOLLOWERS
[Session lasted 6.32 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-04-23 11:48:08] [andikilli]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "quickstart.py", line 52, in <module>
    randomize=False, interact=False)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 3146, in follow_user_followers
    self.logfolder)
  File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 1082, in get_given_user_followers
    logger, logfolder)
  File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 903, in get_users_through_dialog
    person_list = dialog_username_extractor(buttons)
  File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 930, in dialog_username_extractor
    .find_elements_by_tag_name("a")[1].text)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=73.0.3683.103)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-47-generic x86_64)

**Comment by cormo1990** [comment]
Hi, for this kind of activity try to use my template 😃✌️

**Comment by ofromf** [comment]
hei, it's actually your template :) , but it's solved yesterday. i just replace my droplet and it work

**Comment by RhaegarTargaryen55** [comment]
> Hi, for this kind of activity try to use my template 😃✌️

Hey, where i can find ur template?

**Comment by cormo1990** [comment]
Hi, download the latest release and search into template folder, my template is called cormotemplate 😃✌️ Feel free to ask

**Comment by RhaegarTargaryen55** [comment]
> Hi, download the latest release and search into template folder, my template is called cormotemplate 😃✌️ Feel free to ask

Thanks for quick feedback, there are only 3 folders: 
tests
instapy
.github

and i can't find ur template here: https://github.com/InstaPy/instapy-quickstart/tree/master/quickstart_templates

Hope you can send me a link where i can find it

**Comment by cormo1990** [comment]
It is renamed, basic follow-unfollow activity.
If you open the template you can fine my nickname into the description at the top of the file 😃✌️

**Comment by RhaegarTargaryen55** [comment]
> It is renamed, basic follow-unfollow activity.
> If you open the template you can fine my nickname into the description at the top of the file 😃✌️

got you bro, thanks again

**Comment by RhaegarTargaryen55** [comment]
> It is renamed, basic follow-unfollow activity.
> If you open the template you can fine my nickname into the description at the top of the file 😃✌️

i'm getting this with your template (as well as with mine):
Grabbed 0 usernames from 'xxxxx's Followers` to do following

any idea?

**Comment by cormo1990** [comment]
You have to give me more information...i’m Running this template right now and I don’t have any problem

**Comment by RhaegarTargaryen55** [comment]
it's pretty much exactly the same as here #4367, probably it's not about the templates, i'm running yours with default settings on mac
