### ISSUE TITLE
Error occurred while deleting cookies from web browser!

### ISSUE THREAD

**Issue by LuismiLabs** [InstaPy/InstaPy#4380]
**Hi people**
I'm getting this error man times in Digital Ocean
I'm running 3 accounts in one droplet
what can i do to solve it?

ERROR [2019-04-29 18:25:32] [xxxx]  Error occurred while deleting cookies from web browser!

```
ERROR [2019-04-29 18:25:32] [xxxx]  Error occurred while deleting cookies from web browser!
	b'Message: invalid session id\n  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-145-generic x86_64)\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/instapy/util.py", line 1684, in smart_run
    yield
  File "xxxx.py", line 205, in <module>
    amount=follows, randomize=True, interact=True, sleep_delay=s_follows)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 3146, in follow_user_followers
    self.logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 1082, in get_given_user_followers
    logger, logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 903, in get_users_through_dialog
    person_list = dialog_username_extractor(buttons)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 930, in dialog_username_extractor
    .find_elements_by_tag_name("a")[1].text)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 320, in find_elements_by_tag_name
    return self.find_elements(by=By.TAG_NAME, value=name)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 685, in find_elements
    {"using": by, "value": value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=73.0.3683.103)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-145-generic x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/instapy/browser.py", line 230, in close_browser
    browser.delete_all_cookies()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid session id
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-145-generic x86_64)

INFO [2019-04-29 18:25:33] [xxxx]  Sessional Live Report:

```

**Comment by LuismiLabs** [comment]
who knows??

**Comment by kranechan** [comment]
@Luismij refer to https://github.com/timgrossmann/InstaPy/issues/4441
