### ISSUE TITLE
Unknown SessionID Raspberry Pi 3B+

### ISSUE THREAD

**Issue by Joker6888** [InstaPy/InstaPy#4389]
## Expected Behavior
Run the scheduled script

## Current Behavior
Script is starting but often not running through, just stopping on various positions.

## Possible Solution (optional)
Tried everything I can find in this Forum or google-search, even fresh installation doesn't help. 

## InstaPy configuration

Traceback (most recent call last):
  File "quickstart.py", line 118, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 563, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
  File "quickstart.py", line 103, in job
    session.like_by_tags(like_tags, amount=random.randint(55,75), randomize=True, media='Photo')
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 1689, in like_by_tags
    self.logger)
  File "/home/pi/Projects/InstaPy/instapy/like_util.py", line 502, in check_link
    web_address_navigator(browser, post_link)
  File "/home/pi/Projects/InstaPy/instapy/util.py", line 1028, in web_address_navigator
    browser.get(link)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: unknown sessionId
  (Session info: headless chrome=72.0.3626.121)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.36-v7+ armv7l)

**Comment by martinkrulltott** [comment]
Having the same issue. Similar to this I suppose https://github.com/timgrossmann/InstaPy/issues/4073 

I’m not a Python programmer. But since it seems to crash softly (it’s writing the Sessional Live Report before crashing), maybe a temporary solution could be to wrap the initial call(in my case made from a crontab) in a try/catch and if it fails use the log to figure out at far it had come along and make another call to continue where it left off.

**Comment by Joker6888** [comment]
Same issue, now it does it on every run, sometimes after 10 minutes, sometimes after 1 1/2 hours. Any ideas or a workaround?

**Comment by Joker6888** [comment]
It seems like it’s a problem with the like_by_tags session because my unfollow-activity (separate session) runs without any problems.

**Comment by tjuzen** [comment]
hey, still having this issue. any suggestions?
