### ISSUE TITLE
Get error while using standard quickstart_template

### ISSUE THREAD

**Issue by joost-heijden** [InstaPy/InstaPy#4391]
```
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    from instapy import InstaPy
  File "/Users/heijden/Desktop/InstaPy-master/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/heijden/Desktop/InstaPy-master/instapy/instapy.py", line 26, in <module>
    from .like_util import check_link
  File "/Users/heijden/Desktop/InstaPy-master/instapy/like_util.py", line 19, in <module>
    from .unfollow_util import get_following_status
  File "/Users/heijden/Desktop/InstaPy-master/instapy/unfollow_util.py", line 814
    scroll_to_bottom_of_followers_list(browser, dialog)
    ^
IndentationError: unexpected indent
```
My template:
```
from instapy import InstaPy
from instapy.util import smart_run

insta_username = 'xxxxxx'
insta_password = 'xxxxxx'

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

# let's go! :>
with smart_run(session):
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=6000,
                                    max_following=3000,
                                    min_followers=30,
                                    min_following=30)
    session.set_user_interact(amount=2, randomize=True, percentage=30,
                              media='Photo')
    session.set_do_like(enabled=True, percentage=100)
    session.set_do_comment(enabled=True, percentage=5)
    session.set_comments(
        ['Nice shot! @{}', 'I love your profile! @{}', '@{} Love it!',
         '@{} :heart::heart:',
         '@{}:revolving_hearts::revolving_hearts:', '@{}:fire::fire::fire:'],
        media='Photo')

    # unfollow activity
    session.unfollow_users(amount=126, nonFollowers=True, style="RANDOM",
                           unfollow_after=42 * 60 * 60, sleep_delay=300)

    # follow activity
    ammount_number = 500
    session.follow_user_followers(['blackbananasnl', 'konceptstore.nl'],
                                  amount=ammount_number, randomize=False,
                                  interact=True, sleep_delay=240)
```

**Comment by GeoffreyPG** [comment]
Same

**Comment by GeoffreyPG** [comment]
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/schedule/__init__.py", line 563, in run_pending
    default_scheduler.run_pending()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()

**Comment by GeoffreyPG** [comment]
Edit unfollow_util.py (line 809)
https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L809

Old
dialog_address = "//body/div[3]/div/div[2]"

New
dialog_address = "//body/div[@role=\"presentation\"]/div/div[2]"

**Comment by joost-heijden** [comment]
@GeoffreyPG

Get another error after updating the unfollow_until.py file:

Traceback (most recent call last):
```
  File "quickstart.py", line 8, in <module>
    from instapy import InstaPy
  File "/Users/heijden/Desktop/InstaPy-master/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/heijden/Desktop/InstaPy-master/instapy/instapy.py", line 26, in <module>
    from .like_util import check_link
  File "/Users/heijden/Desktop/InstaPy-master/instapy/like_util.py", line 19, in <module>
    from .unfollow_util import get_following_status
  File "/Users/heijden/Desktop/InstaPy-master/instapy/unfollow_util.py", line 809
    dialog_address = "//body/div[@ROLE="presentation"]/div/div[2]"
SyntaxError: invalid syntax
```

**Comment by rickycm** [comment]
Doesn't work neither.... got :
no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[@ROLE='presentation']/div/div[2]"}

**Comment by rickycm** [comment]
Edit unfollow_util.py (line 809)
https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L809

Old
dialog_address = "//body/div[3]/div/div[2]"

I changed it to 
dialog_address = "//body/div[2]/div/div[2]"

seems it worked!

**Comment by joost-heijden** [comment]
@rickycm @GeoffreyPG 

try to change adress to "//body/div[2]/div/div[2]", but still get a error:
```
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    from instapy import InstaPy
  File "/Users/heijden/Desktop/InstaPy-master/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/heijden/Desktop/InstaPy-master/instapy/instapy.py", line 26, in <module>
    from .like_util import check_link
  File "/Users/heijden/Desktop/InstaPy-master/instapy/like_util.py", line 19, in <module>
    from .unfollow_util import get_following_status
  File "/Users/heijden/Desktop/InstaPy-master/instapy/unfollow_util.py", line 814
    scroll_to_bottom_of_followers_list(browser, dialog)
```

**Comment by rickycm** [comment]
@joost-heijden  you can try this:
dialog_address = "//div[@role='dialog']/div[2]"

**Comment by joost-heijden** [comment]
@rickycm doesn't work at a Mac :(

**Comment by joost-heijden** [comment]
Changed it back to the standard [unfollow_util.py](https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py)

And put the firefox browser in, and now it works!
# get a session!
```
session = InstaPy(username=insta_username,
                  password=insta_password,
                  use_firefox=True,
                  headless_browser=True,
                  multi_logs=True)
```
