### ISSUE TITLE
Error with chromedriver?

### ISSUE THREAD

**Issue by sebo361** [InstaPy/InstaPy#4394]
I am using schedule for starting the bot on a remote server, but approx. once a day i get following error:

Traceback (most recent call last):
File "schedulescript.py", line 168, in 
schedule.run_pending()
File "/usr/local/lib/python3.6/dist-packages/schedule/init.py", line 563, in run_pending
default_scheduler.run_pending()
File "/usr/local/lib/python3.6/dist-packages/schedule/init.py", line 94, in run_pending
self._run_job(job)
File "/usr/local/lib/python3.6/dist-packages/schedule/init.py", line 147, in _run_job
ret = job.run()
File "/usr/local/lib/python3.6/dist-packages/schedule/init.py", line 466, in run
ret = self.job_func()
File "schedulescript.py", line 112, in follow
session.like_by_tags(random.sample(like_tag_list, 3), amount=random.randint(5, 15), interact=True)
File "/root/InstaPy/instapy/instapy.py", line 1751, in like_by_tags
self.logger)
File "/root/InstaPy/instapy/like_util.py", line 509, in check_link
web_address_navigator(browser, post_link)
File "/root/InstaPy/instapy/util.py", line 1049, in web_address_navigator
browser.get(link)
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
self.execute(Command.GET, {'url': url})
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
(Session info: headless chrome=73.0.3683.75)
(Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-45-generic x86_64)

Any idea how i can solve that?

**Comment by sebo361** [comment]
Does anyone know how to solve this issue?

**Comment by kranechan** [comment]
@sebo313 refer to https://github.com/timgrossmann/InstaPy/issues/4441
