### ISSUE TITLE
Cannot create a new cookie - RPI3b+

### ISSUE THREAD

**Issue by ar82249728** [InstaPy/InstaPy#4400]
Hello,

I cannot resolve this error since 3 weeks. So I'm posting for help. I don't understand the error I get. Can someone tell me what's wrong with this error  please ? I use RPI 3b+. Thank you ! :)

` ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-05-07 10:54:43] [xxx]  Using built in instapy-chromedriver executable (version 2.36.post0)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-05-07 10:54:47] [xxxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Issue with cookie for user xxx. Creating new cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20190507-105526.html
**********************************************************************

INFO [2019-05-07 10:55:27] [xxx]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 44.51 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-05-07 10:55:27] [xxx]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "quickstart.py", line 17, in <module>
    with smart_run(session):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/instapy/util.py", line 1676, in smart_run
    session.login()
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 378, in login
    self.bypass_with_mobile):
  File "/usr/local/lib/python3.5/dist-packages/instapy/login_util.py", line 262, in login_user
    "//button//div[text()='Log in']")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button//div[text()='Log in']"}
  (Session info: headless chrome=72.0.3626.121)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)

**Comment by ar82249728** [comment]
Anyone to identify the problem ? :)

**Comment by Joker6888** [comment]
#4441 
The last part should solve it.
