### ISSUE TITLE
error in starting chrome / chromedriver

### ISSUE THREAD

**Issue by MMeybodi** [InstaPy/InstaPy#4416]
i have searched a lot in similar issues but i still have the problem
i have installed chrome and chromedriver but
when i run the program i get this message:

No any custom workspace provided.       ~using existing..

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/**********/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
INFO [2019-05-10 03:42:49] [**********]  Using built in instapy-chromedriver executable (version 2.46)
ERROR [2019-05-10 03:42:50] [**********]  Message: unknown error: Failed to create a Chrome process.
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platfor
m=Windows NT 10.0.15063 x86_64)
Traceback (most recent call last):
  File "C:\**************\instapy\browser.py", line 146, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\**********\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py"
, line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\**********\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py"
, line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\**********\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py"
, line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\********\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py"
, line 321, in execute
    self.error_handler.check_response(response)
  File "C:\**********\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.
py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Failed to create a Chrome process.
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platfor
m=Windows NT 10.0.15063 x86_64)

Traceback (most recent call last):
  File "********.py", line 11, in <module>
    session = InstaPy(username='*********', password='********')
  File "C:\Users\**********\instapy\instapy.py", line 295, in __init__
    self.set_selenium_local_session()
  File "C:\Users\**********\instapy\instapy.py", line 349, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at C:\**********\AppData\Local\Programs\Python\Pytho
n37\lib\site-packages\instapy_chromedriver\chromedriver_win32.exe

may i get some help?

**Comment by MMeybodi** [comment]
downgraded chrome from 74 to 72. solved.
saw the solution in a comment in discord group.

**Comment by kranechan** [comment]
Hi @mmogit11 how do you downgrade to 72? are you using raspberry pi?
