### ISSUE TITLE
Error with chromedriver / selenium

### ISSUE THREAD

**Issue by sebo361** [InstaPy/InstaPy#4418]
Hello, i am currently facing the following error which occurs approx. once a day. Does anyone know how to handle it?

Traceback (most recent call last):
  File "script.py", line 164, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 563, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
  File "script.py", line 108, in follow
    randomize=True, sleep_delay=403, interact=True)
  File "/root/InstaPy/instapy/instapy.py", line 3179, in follow_user_followers
    validation, details = self.validate_user_call(person)
  File "/root/InstaPy/instapy/instapy.py", line 1189, in validate_user_call
    self.logfolder)
  File "/root/InstaPy/instapy/util.py", line 186, in validate_username
    logger)
  File "/root/InstaPy/instapy/util.py", line 935, in get_relationship_counts
    web_address_navigator(browser, user_link)
  File "/root/InstaPy/instapy/util.py", line 1049, in web_address_navigator
    browser.get(link)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=71.0.3578.80)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-45-generic x86_64)

**Comment by ericjmachado** [comment]
Same issue

**Comment by celdeldel** [comment]
same issue

**Comment by willlogs** [comment]
make sure "headless_browser" is equal to True

it worked for me

also install the InstaPy using the quick install provided with it
