### ISSUE TITLE
i am unable to use proxy

### ISSUE THREAD

**Issue by khansaad1275** [InstaPy/InstaPy#4424]
```
""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = 'user12751'
insta_password = '********'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                 potency_ratio=1.34,
                  delimit_by_numbers=True,
                   max_followers=8500,
                    max_following=4490,
                     min_followers=100,
                      min_following=56,
                       min_posts=10,
                        max_posts=1000)

    session.set_quota_supervisor(enabled=False, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(57, 585),
                               peak_comments=(21, 182),
                                peak_follows=(48, None),
                                 peak_unfollows=(35, 402),
                                  peak_server_calls=(None, 4700))


    session.set_do_follow(enabled=True, percentage=10, times=2)

    session.set_simulation(enabled=False, percentage=5)
    
    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])
    session.set_do_comment(enabled=False, percentage=30)
    session.set_comments([ u'What an amazing shot! :heart_eyes:@{}',
                             u'What an amazing shot! :heart_eyes: @{}',
                             u'Wonderful!! :heart_eyes:@{}',
                             u'Wonderful Click!! :heart_eyes:@{}',
                             u'This is awesome!! :heart_eyes: @{}',
                             u'This is awesome!! :heart_eyes:@{}',
                             u'I really like the way you captured this. @{}',
                             u'I really like the way you captured this Picture.@{}',
                             u'Great capture!! :smiley: @{}',
                             u'Great capture!! :smiley: :thumbsup:@{}',
                             u'Dynamic 🔥 @{}',
                             u'Nice Pic 🔥 @{}',
                             u'Cool :heart_eyes:@{}'],media='Photo')

    # activity
    session.unfollow_users(amount=5, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=48*60*60, sleep_delay=100)
    #session.follow_user_followers(['xam_me'], amount=5, randomize=False)
    #session.like_by_feed(amount=30, randomize=False, unfollow=False, interact=True)
    #session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
    session.like_by_locations(["489299857","361112920","936141473194544","945370618859036","289069090","492107350","273483874","16537813","236082607","217381472","229007940","234372086","608537925","237678137","1485238004835900","287163486","230262318","297340607","766043071","21312876","240065348","272529008","354032978","281958558","1656984457727249","320598589","253939292","829858098"], amount=200)
    #session.like_by_tags(["australia","Sydney","Albury","Broken Hill","Cessnock"], amount=1, interact=True)
```

here is the error:
INFO [2019-05-12 22:34:43] [_netflix_india]  Using built in instapy-chromedriver executable (version 2.46)
ERROR [2019-05-12 22:34:46] [_netflix_india]  Message: invalid argument: cannot parse capability: proxy
from invalid argument: Specifying 'socksProxy' requires an integer for 'socksVersion'
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)
Traceback (most recent call last):
  File "C:\InstaPy-master\instapy\browser.py", line 146, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\Saad\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium-3.141.0-py3.7.egg\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\Saad\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium-3.141.0-py3.7.egg\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Saad\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium-3.141.0-py3.7.egg\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Saad\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium-3.141.0-py3.7.egg\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Saad\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium-3.141.0-py3.7.egg\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: proxy
from invalid argument: Specifying 'socksProxy' requires an integer for 'socksVersion'
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

Traceback (most recent call last):
  File "C:\InstaPy-master\proxy.py", line 16, in <module>
    headless_browser=False)
  File "C:\InstaPy-master\instapy\instapy.py", line 295, in __init__
    self.set_selenium_local_session()
  File "C:\InstaPy-master\instapy\instapy.py", line 349, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at C:\Users\Saad\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy_chromedriver\chromedriver_win32.exe

**Comment by khansaad1275** [comment]
its working now you just have to downgrade the chrome-driver version.
version 2.42 is working fine and here is the method to downgrade it.
1.download the chrome driver version 2.42 here is the link https://chromedriver.storage.googleapis.com/index.html?path=2.42/
2.navigate to the assets folder. in my windows10 the path is C:\Users\your-username\InstaPy\assets
3.extract the chrome driver in the assets folder.
