### ISSUE TITLE
It has been running just fine until...

### ISSUE THREAD

**Issue by kthyaki** [InstaPy/InstaPy#443]
It has been running just fine until certain point then I get the following message:

```
`Traceback (most recent call last):
  File "C:\Users\KTF\Desktop\A&F\quickstart.py", line 20, in <module>
    .like_by_tags(likebytags, amount=17) \
  File "C:\Users\KTF\Desktop\A&F\instapy\instapy.py", line 470, in like_by_tags
    followed += follow_user(self.browser, self.follow_restrict, self.username, user_name)
  File "C:\Users\KTF\Desktop\A&F\instapy\unfollow_util.py", line 130, in follow_user
    follow_button.click()
  File "C:\Users\KTF\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\KTF\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KTF\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KTF\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button class="_ah57t _84y62 _i46jh _rmr7s">...</button> is not clickable at point (920, 14). Other element would receive the click: <div class="_df358">...</div>
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.1.7601 SP1 x86_64)`
```

Would anyone help please?

**Comment by FBosler** [comment]
Same error as a few other Issues. I think this one has the most tracktion: https://github.com/timgrossmann/InstaPy/issues/335
