### ISSUE TITLE
chrome error pythonanywhere

### ISSUE THREAD

**Issue by Modderov** [InstaPy/InstaPy#4443]
hi, i cant run quickstart due to this error:

21:49 ~/InstaPy (master)$ python quickstart.py
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/myname/InstaPy"
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-05-16 21:50:18] [myname]  Using built in instapy-chromedriver executable (version 2.46)
ERROR [2019-05-16 21:50:22] [myname]  Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome ha
s crashed.)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-1075-aws x86_64)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/myname/InstaPy/instapy/browser.py", line 146, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/myname/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/myname/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/myname/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/myname/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/myname/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-1075-aws x86_64)

Traceback (most recent call last):
  File "quickstart.py", line 59, in <module>
    multi_logs=True)
  File "/home/myname/InstaPy/instapy/instapy.py", line 295, in __init__
    self.set_selenium_local_session()
  File "/home/myname/InstaPy/instapy/instapy.py", line 349, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /home/myname/.local/lib/python2.7/site-packages/instapy_c
hromedriver/chromedriver_linux64

**Comment by JustAskMarina** [comment]
Hi, I think it's related to an incompatible chromedriver. Which Chrome version are you running? It seems I've just solved it manually updating chromedriver to the correct version directly from it's website.

**Comment by Modderov** [comment]
i have this google versione on my pc:

Versione 74.0.3729.157 (Build ufficiale) (a 64 bit)

**Comment by JustAskMarina** [comment]
Same. That solution seems to be working for me, you might try it.

**Comment by Modderov** [comment]
so from pythonanywhere what can i do to update chromedriver?

**Comment by JustAskMarina** [comment]
Sorry, I don't know how that platform works, but if you can access the assets folder in the instapy folder there should be some way to place there the chromedriver file
