### ISSUE TITLE
Element blocking when interacting by tags

### ISSUE THREAD

**Issue by SirCipher** [InstaPy/InstaPy#4447]
## Expected Behavior
To continue interacting by tags.

## Current Behavior
```
Traceback (most recent call last):
  File "[redacted]ig/venv/lib/python3.6/site-packages/instapy/util.py", line 829, in click_element
    element.click()
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="oW_lN _0mzm- sqdOP yWX7d        A086a" type="button"> is not clickable at point (936,151) because another element <div class="bY2yH"> obscures it


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[redacted]ig/venv/lib/python3.6/site-packages/instapy/util.py", line 829, in click_element
    element.click()
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="oW_lN _0mzm- sqdOP yWX7d        A086a" type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[redacted]ig/venv/lib/python3.6/site-packages/instapy/util.py", line 829, in click_element
    element.click()
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="oW_lN _0mzm- sqdOP yWX7d        A086a" type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[redacted]ig/venv/lib/python3.6/site-packages/instapy/util.py", line 829, in click_element
    element.click()
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="oW_lN _0mzm- sqdOP yWX7d        A086a" type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "accounts/[redacted].py", line 94, in <module>
    interaction()
  File "accounts/[redacted].py", line 40, in interaction
    session.like_by_tags(selected_tags, amount=10)
  File "[redacted]ig/venv/lib/python3.6/site-packages/instapy/instapy.py", line 1859, in like_by_tags
    self.logfolder)
  File "[redacted]ig/venv/lib/python3.6/site-packages/instapy/unfollow_util.py", line 704, in follow_user
    logfolder)
  File "[redacted]ig/venv/lib/python3.6/site-packages/instapy/unfollow_util.py", line 1551, in verify_action
    click_visibly(browser, follow_button)
  File "[redacted]ig/venv/lib/python3.6/site-packages/instapy/util.py", line 1744, in click_visibly
    click_element(browser, element)
  File "[redacted]ig/venv/lib/python3.6/site-packages/instapy/util.py", line 876, in click_element
    click_element(browser, element, tryNum)
  File "[redacted]ig/venv/lib/python3.6/site-packages/instapy/util.py", line 876, in click_element
    click_element(browser, element, tryNum)
  File "[redacted]ig/venv/lib/python3.6/site-packages/instapy/util.py", line 876, in click_element
    click_element(browser, element, tryNum)
  File "[redacted]ig/venv/lib/python3.6/site-packages/instapy/util.py", line 860, in click_element
    "class") + "')[0].click()")
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 141, in get_attribute
    self, name)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "[redacted]ig/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="oW_lN _0mzm- sqdOP yWX7d        A086a" type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
```
## Possible Solution (optional)
Unsure. This issue wasn't present using the ChromeDriver, however, due to the issues currently present in it I am using Gecko.

## InstaPy configuration
Fails during `session.like_by_tags(selected_tags, amount=10)`. This happens on three different accounts all which are using Gecko but have different configurations.

**Comment by DennyZen** [comment]
have same errors..
