### ISSUE TITLE
After having the issue #335 solved, I got a new issue...

### ISSUE THREAD

**Issue by kthyaki** [InstaPy/InstaPy#446]
First of all, I would like to thank @FBosler for helping me out with my issue #443.

I just did it full screen and it worked fine until I have this new issue...

``[4/6]
Image from: b'king_goldendog'
Number of Followers: 3501
Link: b'https://www.instagram.com/p/BS3qo4OhgES/?tagged=petbamboo'
Description: b'Ningu\xc3\xa9m me tira daqui... #goldenretriever  #golden  #pet  #camapet  #petbamboo  @petbamboo'
--> Image Liked!
--> Not commented
--> Not following

[5/6]
Image from: b'lisamaria_dog'
Traceback (most recent call last):
  File "C:\Users\KTF\Desktop\X\quickstart.py", line 20, in <module>
    .like_by_tags(likebytags, amount=17) \
  File "C:\Users\KTF\Desktop\X\instapy\instapy.py", line 430, in like_by_tags
    self.like_by_followers_lower_limit)
  File "C:\Users\KTF\Desktop\X\instapy\like_util.py", line 242, in check_link
    browser.get(userlink)
  File "C:\Users\KTF\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\KTF\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KTF\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.1.7601 SP1 x86_64)``

Would anyone help please?

**Comment by converge** [comment]
@kthyaki some news about this issue ? how can we reproduce it ?

**Comment by converge** [comment]
as there is no interaction for a long time, we're closing this issue. please, reopen it if you need help about this topic.
