### ISSUE TITLE
Issue to run bot with CentOS 7

### ISSUE THREAD

**Issue by mehdiirh** [InstaPy/InstaPy#4471]
Hi I runned instaPy on CentOS7 and i got this error:

`[root@cloud-9466a31741b2b62d4 InstaPy]# python3.7 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 23, in <module>
    from .comment_util import comment_image
  File "/root/InstaPy/instapy/comment_util.py", line 8, in <module>
    from .util import update_activity
  File "/root/InstaPy/instapy/util.py", line 19, in <module>
    import sqlite3
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
`

What Should I do ??

**Comment by CamiloB** [comment]
looks like you dont have installed sqlite on your server try to install it and run it again
