### ISSUE TITLE
Message: TypeError: arguments[0].children[1] is undefined

### ISSUE THREAD

**Issue by joost-heijden** [InstaPy/InstaPy#4484]
Hi get this error. Someone can help me out?

```
Traceback (most recent call last):
  File "quickstart.py", line 48, in <module>
    amount=8000, randomize=True)
  File "/Users/heijden/Desktop/InstaPy-master-joost/instapy/instapy.py", line 2813, in interact_user_followers
    self.logfolder)
  File "/Users/heijden/Desktop/InstaPy-master-joost/instapy/unfollow_util.py", line 1082, in get_given_user_followers
    logger, logfolder)
  File "/Users/heijden/Desktop/InstaPy-master-joost/instapy/unfollow_util.py", line 814, in get_users_through_dialog
    scroll_to_bottom_of_followers_list(browser, dialog)
  File "/Users/heijden/Desktop/InstaPy-master-joost/instapy/unfollow_util.py", line 776, in scroll_to_bottom_of_followers_list
    "arguments[0].children[1].scrollIntoView()", element)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: arguments[0].children[1] is undefined
```

```
"""
This template is written by @loopypanda

What does this quickstart script aim to do?
- My settings is for running InstaPY 24/7 with approximately 1400
follows/day - 1400 unfollows/day running follow until reaches 7500 and than
switch to unfollow until reaches 0.
"""

from instapy import InstaPy
from instapy.util import smart_run

# get a session!
session = InstaPy(username='xxxx', password='xxxx',
                  use_firefox=True,
                  headless_browser=True,
                  multi_logs=True)

# let's go! :>
with smart_run(session):
    # general settings

    # session.set_relationship_bounds(enabled=True,
    # delimit_by_numbers=False, max_followers=12000, max_following=4500,
    # min_followers=35, min_following=35)
    session.set_user_interact(amount=2, randomize=True, percentage=100,
    media='Photo')
    session.set_do_follow(enabled=True, percentage=100)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments(['comment'])
    session.set_do_comment(enabled=True, percentage=10)
    # session.set_user_interact(amount=2, randomize=True, percentage=100,
    # media='Photo')
    session.set_skip_users(skip_private=False,
                           private_percentage=0,
                           skip_no_profile_pic=True,
                           no_profile_pic_percentage=100,
                           skip_business=True,
    		               skip_non_business=False,
                           business_percentage=100,
    #                       skip_business_categories=[],
    #                       dont_skip_business_categories=[]
                           )

    # activity

    session.interact_user_followers(['xxxx', 'xxxx', 'xxxx'],
    amount=8000, randomize=True)
    session.follow_user_followers(['xxxx', 'xxxx','xxxx'],
    amount=8000, randomize=False, interact=True)
    # session.unfollow_users(amount=7500, nonFollowers=True, style="RANDOM",
    # unfollow_after=42*60*60, sleep_delay=3)
    # session.like_by_tags(['???'], amount=8000)

```

**Comment by joost-heijden** [comment]
Used this command: `pip3 install -U instapy` and i think it works again.

**Comment by fintzd** [comment]
Still an issue here?
