### ISSUE TITLE
Constant crash on script for following target's follwers.

### ISSUE THREAD

**Issue by Vitruvia** [InstaPy/InstaPy#4494]
I'm getting an error in the middle of my script for following target's followers.

I was using a short script with windows task scheduler to keep repeating it, so maybe this was happening before and I hadn't noticed.

I've changed to a single continuous running program because I want to implement a bypass for two-step authentication, and I want to do it only once in the day and then keep the program running.

I have instapy running on a PC with Windows 10 installed. One of the reasons why I only want to bypass 2-step-authentication once is because I can't be home all the time to do it. My account is growing and I want to protect it.

Chrome webdriver is up to date.
I have a similar setup in a script for liking other's posts and another one for unfollowing, and both run without issues. I'm going to post them for reference.

Here is the error.

## Expected Behavior
Keeps running until cancelled.

## Current Behavior
```
Error occurred while deleting cookies from web browser!
    b'Message: invalid session id\n  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)\n'
Traceback (most recent call last):
  File "C:\Users\Thales\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 1684, in smart_run
    yield
  File "P:\instapy\Follows.py", line 107, in <module>
    interact=True)
  File "C:\Users\Thales\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 3210, in follow_user_followers
    interact)
  File "C:\Users\Thales\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 1095, in follow_by_list
    self.user_interact_media)
  File "C:\Users\Thales\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 2241, in interact_by_users
    media)
  File "C:\Users\Thales\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\like_util.py", line 406, in get_links_for_username
    web_address_navigator(browser, user_link)
  File "C:\Users\Thales\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 1049, in web_address_navigator
    browser.get(link)
  File "C:\Users\Thales\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Thales\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Thales\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid session id
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)
 

During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\Users\Thales\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\browser.py", line 230, in close_browser
    browser.delete_all_cookies()
  File "C:\Users\Thales\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "C:\Users\Thales\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Thales\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid session id
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)
 
ERROR [2019-05-30 16:14:32] [_thalesalexandre]  Pow! Error occurred while dumping follow restriction data to a local JSON:
    b'Expecting value: line 1 column 1 (char 0)'
```

## InstaPy configuration
```python
import random
import time
import argparse
from group_lists import All_Lists
from instapy import InstaPy
from instapy import smart_run


my_parser = argparse.ArgumentParser()
# add the arguments as you like WHICH you will pass
# e.g., here is the simplest example you can see,
my_parser.add_argument("--name")
args, args_unknown = my_parser.parse_known_args()

name = args.name

# login credentials
insta_username = ''
insta_password = ''

# restriction data
dont_likes = All_Lists.bad_tags

print('Launching Follows')
time.sleep(2)
print(f'Logging as {name}...')
time.sleep(3)
if name == 'thales':
    friends = All_Lists.thales_friends

    #prevent posts that contain
    ignore_list = []
    ignore_users = []

    targets = All_Lists.thales_targets
    target_business_categories = ['Personal Blog', 'Just For Fun', 'Medical & Health']
    print(f'Successfully logged as {name}!')

elif name == 'medicina':
    friends = All_Lists.medicina_friends
    #prevent posts that contain
    ignore_list = []
    ignore_users = []

    targets = All_Lists.medicina_targets
    target_business_categories = ['Personal Blog', 'Just For Fun', 'Medical & Health']
    print(f'Successfully logged as {name}!')

comments = []

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs=True)

# let's go! :>
with smart_run(session):
    # HEY HO LETS GO
    # general settings
    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"],
                                 sleepyhead=True,
                                 stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(None, 5000),
                                 peak_comments=(0, 0),
                                 peak_follows=(100, None),
                                 peak_unfollows=(None, 7500),
                                 peak_server_calls=(None, 80000))

    session.set_dont_include(friends)
    session.set_dont_like(dont_likes)
    session.set_ignore_if_contains(ignore_list)
    session.set_ignore_users(ignore_users)
    session.set_simulation(enabled=True)

    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=0.5,
                                    delimit_by_numbers=True,
                                    max_followers=10000,
                                    max_following=1200,
                                    min_followers=40,
                                    min_following=25,
                                    min_posts=3)

    session.set_skip_users(skip_private=False,
                           skip_no_profile_pic=True,
                           skip_business=True,
                           dont_skip_business_categories=[
                               target_business_categories])

    session.set_action_delays(enabled=True,
                              like=2,
                              randomize=True,
                              random_range=(70, 200))

    session.set_do_like(enabled=True, percentage=85)
    session.set_user_interact(amount=2, randomize=False, percentage=80, media='Photo')

    session.set_do_comment(enabled=False, percentage=0)
    session.set_do_follow(enabled=True, percentage=60, times=1)

    # activities
    """ Interact with the chosen targets...
    """
    session.follow_user_followers(targets,
                                  amount=random.randint(50, 100),
                                  randomize=True, sleep_delay=random.randint(120, 250),
                                  interact=False)
```

## Likes script
```python
import random
import time
import argparse
from group_lists import All_Lists
from instapy import InstaPy
from instapy import smart_run


my_parser = argparse.ArgumentParser()
# add the arguments as you like WHICH you will pass
# e.g., here is the simplest example you can see,
my_parser.add_argument("--name")
args, args_unknown = my_parser.parse_known_args()

name = args.name

# login credentials
insta_username = ''
insta_password = ''

# restriction data
dont_likes = All_Lists.bad_tags

print('Launching Likes')
time.sleep(2)
print(f'Logging as {name}...')
time.sleep(3)
if name == 'thales':
    friends = All_Lists.thales_friends

    #prevent posts that contain
    ignore_list = []

    targets = All_Lists.thales_targets + ['medicinadoaprimoramento', '_thalesalexandre']
    target_business_categories = ['Personal Blog', 'Just For Fun', 'Medical & Health']
    ignore_users = []
    print(f'Successfully logged as {name}!')

elif name == 'medicina':
    friends = All_Lists.medicina_friends
    #prevent posts that contain
    ignore_list = []
    targets = All_Lists.medicina_targets + ['_thalesalexandre', 'medicinadoaprimoramento']
    target_business_categories = ['Personal Blog', 'Just For Fun', 'Medical & Health']
    ignore_users = []
    print(f'Successfully logged as {name}!')

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs=True)


with smart_run(session):
    # HEY HO LETS GO
    # general settings
    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"],
                                 sleepyhead=True,
                                 stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(300, 5000),
                                 peak_server_calls=(None, None))

    session.set_dont_like(dont_likes)
    session.set_ignore_if_contains(ignore_list)
    session.set_ignore_users(ignore_users)
    session.set_simulation(enabled=True)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=0.5,
                                    delimit_by_numbers=True,
                                    max_followers=8000,
                                    max_following=1000,
                                    min_followers=60,
                                    min_following=35,
                                    min_posts=3)
    session.set_skip_users(skip_private=True,
                           skip_no_profile_pic=True,
                           skip_business=True,
                           dont_skip_business_categories=[
                               target_business_categories])


    session.set_action_delays(enabled=True,
                              like=3,
                              randomize=True,
                              random_range=(70, 140))

    session.set_do_like(enabled=True, percentage=100)
    session.set_do_comment(enabled=False, percentage=0)
    session.set_do_follow(enabled=False, percentage=0, times=0)

    # activities
    session.set_user_interact(amount=random.randint(2, 3), randomize=False, percentage=100, media='Photo')
    session.set_do_like(enabled=True, percentage=100)
    session.interact_user_followers(targets, amount=random.randint(150, 350), randomize=True)
```

## Unfollow script
```python
import random
import time
import argparse
from group_lists import All_Lists
from instapy import InstaPy
from instapy import smart_run


my_parser = argparse.ArgumentParser()
# add the arguments as you like WHICH you will pass
# e.g., here is the simplest example you can see,
my_parser.add_argument("--name")
args, args_unknown = my_parser.parse_known_args()

name = args.name

# login credentials
insta_username = ''
insta_password = ''

# restriction data
dont_likes = All_Lists.bad_tags

print('Launching Unfollows')
time.sleep(2)
print(f'Logging as {name}...')
time.sleep(3)
if name == 'thales':
    friends = All_Lists.thales_friends

    #prevent posts that contain
    ignore_list = []

    targets = All_Lists.thales_targets
    target_business_categories = ['Personal Blog', 'Just For Fun', 'Medical & Health']
    ignore_users = []
    print(f'Successfully logged as {name}!')

elif name == 'medicina':
    friends = All_Lists.medicina_friends
    #prevent posts that contain
    ignore_list = []
    targets = All_Lists.medicina_targets
    target_business_categories = ['Personal Blog', 'Just For Fun', 'Medical & Health']
    ignore_users = []
    print(f'Successfully logged as {name}!')

comments = []

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs=True)

# let's go! :>
with smart_run(session):
    # HEY HO LETS GO
    # general settings
    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"],
                                 sleepyhead=True,
                                 stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(100, 1000),
                                 peak_comments=(0, 0),
                                 peak_follows=(70, None),
                                 peak_unfollows=(120, 7500),
                                 peak_server_calls=(None, 80000))
    session.set_dont_include(friends)
    session.set_dont_like(dont_likes)
    session.set_ignore_if_contains(ignore_list)
    session.set_ignore_users(ignore_users)
    session.set_simulation(enabled=True)
    session.set_action_delays(enabled=True,
                              unfollow=10,
                              randomize=True,
                              random_range=(70, 200))


    # UNFOLLOW activity

    """Unfollow all users
    """
    while True:
        session.unfollow_users(amount=600, allFollowing=True, style="LIFO", unfollow_after=48 * 60 * 60,
                               sleep_delay=random.randint(60, 180))
        time.sleep(60)
```

**Comment by Vitruvia** [comment]
Update #1: it seems that my likes script is also crashing in the same way.

**Comment by octavius-1** [comment]
Happens a lot when using chromedriver, just handle the exception and restart the script

**Comment by Vitruvia** [comment]
> Happens a lot when using chromedriver, just handle the exception and restart the script

I won't be able to bypass the 2-step-verification this way, though.

**Comment by octavius-1** [comment]
What I do is restart the session everytime an exception shows up and my scripts work properly (running for weeks even with those crashes)

**Comment by Vitruvia** [comment]
> What I do is restart the session everytime an exception shows up and my scripts work properly (running for weeks even with those crashes)

Can you show me how you do that?

**Comment by octavius-1** [comment]
```
exception_happened = False
while True:
    try:
        if exception_happened:
           print ("sleeping 2 minutes because an exception happened")
            time.sleep(2*60)

        exception_happened = False
        session = InstaPy (blah blah)
        with smart_run(session):
            while True:
                if exception_happened:
                    break
                #I declare a list of actions here (like by tags, follow followers, etc)
                for action in actions:
                    try:
                        action()
                     except Exception as e:
                         print ("An exception happened while running an instapy internal function")
                         exception_happened = True
                         break
    except Exception as e:
        print ("General exception happened, restarting everything")
        exception_happened = True
        pass
```

**Comment by Vitruvia** [comment]
> ```
> exception_happened = False
> while True:
>     try:
>         if exception_happened:
>            print ("sleeping 2 minutes because an exception happened")
>             time.sleep(2*60)
> 
>         exception_happened = False
>         session = InstaPy (blah blah)
>         with smart_run(session):
>             while True:
>                 if exception_happened:
>                     break
>                 #I declare a list of actions here (like by tags, follow followers, etc)
>                 for action in actions:
>                     try:
>                         action()
>                      except Exception as e:
>                          print ("An exception happened while running an instapy internal function")
>                          exception_happened = True
>                          break
>     except Exception as e:
>         print ("General exception happened, restarting everything")
>         exception_happened = True
>         pass
> ```

Thanks! I have adapted this to my scripts and I will come back saying if it works or not. If it works, then it's a fine solution in my opinion.

**Comment by Vitruvia** [comment]
It seems to be working fine, thanks!
I'll close the issue for now. Hope this solution can help other people.
