### ISSUE TITLE
urllib3.exceptions.MaxRetryError [Errno 111]

### ISSUE THREAD

**Issue by Areahints** [InstaPy/InstaPy#4495]
## Expected Behavior
Run normally!
## Current Behavior
returns an error
## Error message
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fed06febc18>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "care.py", line 48, in <module>
    session.follow_likers (['hustlerpage' ,'blaq_steve', 'hustlersquare'], photos_grab_amount = 3, follow_likers_per_photo = 10, randomize=True, sleep_delay=40, interact=True)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 901, in follow_likers
    randomize)
  File "/usr/local/lib/python3.5/dist-packages/instapy/commenters_util.py", line 392, in get_photo_urls_from_profile
    'https://www.instagram.com/' + username + '/')
  File "/usr/local/lib/python3.5/dist-packages/instapy/util.py", line 1029, in web_address_navigator
    current_url = get_current_url(browser)
  File "/usr/local/lib/python3.5/dist-packages/instapy/util.py", line 1562, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=46704): Max retries exceeded with url: /session/54b1c6744ce9685de346876f1020c0de/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fed06febc18>: Failed to establish a new connection: [Errno 111] Connection refused',))

```

## InstaPy configuration
```
from instapy import InstaPy
from instapy import smart_run

# get a session!
session = InstaPy(username='', password='', headless_browser=True)

photo_comments = ['Nice shot! @{}',
 'I love your profile! @{}',
 'Your feed is an inspiration :thumbsup:',
 'Just incredible :open_mouth:',
 'lovely @{}!',
 'Love your posts @{}',
 'Looks awesome @{}',
 'Getting inspired by you @{}',
 ':raised_hands: Yes!',
 'I can feel your passion @{} :muscle:']

# let's go! :>
with smart_run(session):
 # settings
     session.set_relationship_bounds(enabled=True,
                 potency_ratio=1.34,
                  delimit_by_numbers=True,
                   max_followers=8500,
                    max_following=4490,
                     min_followers=100,
                      min_following=56,
                       min_posts=10,
                        max_posts=1000)

session.set_quota_supervisor(enabled=False, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(57, 585),
                               peak_comments=(21, 182),
                                peak_follows=(50, None),
                                 peak_unfollows=(35, 402),
                                  peak_server_calls=(None, 4700))

session.set_simulation(enabled=False)
session.set_do_like(enabled=True, percentage=25)
session.set_ignore_users([])
session.set_do_comment(enabled=True, percentage=15)
session.set_do_follow(enabled=True, percentage=100, times=1)
session.set_comments(photo_comments)
session.set_ignore_if_contains([])
session.set_action_delays(enabled=True, like=40)

# activity
session.follow_likers (['acct1' ,'acct2', 'acct3'], photos_grab_amount = 3, follow_likers_per_photo = 10, randomize=True, sleep_delay=40, interact=True)
session.like_by_tags(["a","b"], amount=1, interact=True)
session.like_by_locations(["numbers","numbers","numbers"], amount=200) 
""" Joining Engagement Pods...
"""
session.join_pods()

```
checked #3955 but no solution, python version is 3.5, this was working before when I was using a much simpler script

## simple script

```
from instapy import InstaPy
from instapy import smart_run

# get a session!
session = InstaPy(username='', password='', headless_browser=True)

photo_comments = ['Nice shot! @{}',
 'I love your profile! @{}',
 'Your feed is an inspiration :thumbsup:',
 'Just incredible :open_mouth:',
 'lovely @{}!',
 'Love your posts @{}',
 'Looks awesome @{}',
 'Getting inspired by you @{}',
 ':raised_hands: Yes!',
 'I can feel your passion @{} :muscle:']

# let's go! :>
with smart_run(session):
 # settings
 session.set_user_interact(amount=3, randomize=True, percentage=100,
 media='Photo')
 session.set_relationship_bounds(enabled=True,
 potency_ratio=None,
 delimit_by_numbers=True,
 max_followers=3000,
 max_following=900,
 min_followers=50,
 min_following=50)
 session.set_simulation(enabled=False)
 session.set_do_like(enabled=True, percentage=25)
 session.set_ignore_users([])
 session.set_do_comment(enabled=True, percentage=15)
 session.set_do_follow(enabled=True, percentage=100, times=1)
 session.set_comments(photo_comments)
 session.set_ignore_if_contains([])
 session.set_action_delays(enabled=True, like=40)

 # activity
 session.follow_likers (['a' , 'b'], photos_grab_amount = 3, follow_likers_per_photo = 10, randomize=True, sleep_delay=40, interact=True)
 """ Joining Engagement Pods...
 """
 session.join_pods()

```

**Comment by Areahints** [comment]
checking this on [StackOverflow](https://stackoverflow.com/questions/52627563/cant-understand-errno-111-connection-refused) 
```
Connection refused is generated by the kernel because sender refuses to establish TCP connection. Possible reasons are:

No on listen on this host/port
iptables (or other firewall) specifically -j REJECT connections.
From your code it's hard to say if you listen on a proper host/port or not.

How to debug?

Run you service. Without connecting to it run 'netstat -lnpt', it should provide you with list of services listening on this host.
Try nc host port (note - not a ':', but a space here), if connection is refused, nc will terminate instantly. If not, you've established connection (try to type 'GET / HTTP/1.1' and Enter twice in this case).
Just print output of socket.gethostname() and port variable in your code.
I suspect that in your case socket.gethostname() has been resolved into something different than localhost.
```

checking 3 other Errno 111 and it seems to be related to OS and localhost specifically.

**Comment by Areahints** [comment]
For some reason, the simple script is working.. perhaps the code organization of my InstaPy configuration is at fault
