### ISSUE TITLE
Error after updating instapy

### ISSUE THREAD

**Issue by Mathieu-5** [InstaPy/InstaPy#4514]
## Current Behavior
Hi, i use Instapy since two months on my raspberry and it's work very well. But, since i have updated instapy to the last version 5.0 i have an error few minutes after i run the script

thanks for your help

------------
INFO [2019-06-05 14:38:24] [myUser]  Sessional Live Report:
	|> LIKED 12 images  |  ALREADY LIKED: 0
	|> COMMENTED on 11 images
	|> FOLLOWED 19 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> LIKED 0 comments
	|> REPLIED to 0 comments
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0

On session start was FOLLOWING 816 users & had 3978 FOLLOWERS
[Session lasted 27.84 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-06-05 14:38:24] [myUser]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 939, in get_relationship_counts
    "return window._sharedData.entry_data."
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: headless chrome=72.0.3626.121)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Bureau/InstaPy/quickstart.py", line 471, in <module>
    interact=True)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 3224, in follow_user_followers
    validation, details = self.validate_user_call(person)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 1214, in validate_user_call
    self.logfolder)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 188, in validate_username
    logger)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 945, in get_relationship_counts
    browser.find_element_by_xpath(read_xpath(get_relationship_counts.__name__,"followers_count")).text)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: 'value' must be a string
  (Session info: headless chrome=72.0.3626.121)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)

## InstaPy configuration
Instapy V.0.5.0
Raspberry 3
Home network
Chromedriver 2.36 (don't work with 2.46 (errno 8 error) )
Headless mode

**Comment by luizguilherme5** [comment]
Same here

**Comment by anitato** [comment]
I also cannot run Instapy after updating. The error I receive is:
Using built in instapy-chromedriver executable (version 2.46)
Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    multi_logs=True
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 309, in __init__
    self.set_selenium_local_session()
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 361, in set_selenium_local_session
    self.logger)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/browser.py", line 146, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

I have tried:
sudo pip3 uninstall instapy-chromedriver
sudo pip3 install instapy-chromedriver==2.36.post0

So I don't know why it still says I'm using chromedriver 2.46 (where can I replace this "built-in" version?

**Comment by InfraRedApple** [comment]
@Mathieu-Parisot  I submitted a fix [#4520](https://github.com/timgrossmann/InstaPy/pull/4520)

**Comment by Mathieu-5** [comment]
Thanks, what do you mean by removing .text ? Which files i have to remove ?

**Comment by lucicocosta** [comment]
same here
