### ISSUE TITLE
erroR!!! HELP MEEE

### ISSUE THREAD

**Issue by lucicocosta** [InstaPy/InstaPy#4521]
hi, i have an error few minutes after i run the script...anyone can help me plzzzz
## errror

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\util.py", line 939, in get_relationship_counts
    "return window._sharedData.entry_data."
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'entry_data' of undefined
  (Session info: headless chrome=75.0.3770.80)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\quickstart.py", line 34, in <module>
    session.follow_likers (['biel'], photos_grab_amount = 2, follow_likers_per_photo = 600, randomize=False, sleep_delay=5, interact=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 952, in follow_likers
    interact)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 1056, in follow_by_list
    validation, details = self.validate_user_call(acc_to_follow)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 1214, in validate_user_call
    self.logfolder)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\util.py", line 188, in validate_username
    logger)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\util.py", line 945, in get_relationship_counts
    browser.find_element_by_xpath(read_xpath(get_relationship_counts.__name__,"followers_count")).text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'value' must be a string
  (Session info: headless chrome=75.0.3770.80)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)
## InstaPy configuration
from instapy import InstaPy
from instapy.util import smart_run

while True:
    session = InstaPy(username='',
                  password='',
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs=True)

    with smart_run(session):

          session.set_relationship_bounds(enabled=True,
          delimit_by_numbers=True, max_followers=12000, max_following=1500,
          min_followers=100, min_following=100)
          session.set_user_interact(amount=2, randomize=True, percentage=100,
          media='Photo')
          session.set_do_follow(enabled=True, percentage=100)
          session.set_do_like(enabled=True, percentage=60)
          session.set_quota_supervisor(enabled=True,
             sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], 
               sleepyhead=True, 
                stochastic_flow=True, 
                 notify_me=True,
                   peak_likes=(70, 750), 
                     peak_follows=(50, 600),
                       peak_unfollows=(30, 600), 
                         peak_server_calls=(600,None))

    
    # activity

          session.follow_likers ([''], photos_grab_amount = 2, follow_likers_per_photo = 600, randomize=False, sleep_delay=5, interact=True)   
    
          session.unfollow_users(amount=500, nonFollowers=True, style="RANDOM",
          unfollow_after=42*60*60, sleep_delay=3)

          session.follow_likers ([''], photos_grab_amount = 2, follow_likers_per_photo = 600, randomize=False, sleep_delay=5, interact=True)
    
          session.unfollow_users(amount=500, nonFollowers=True, style="RANDOM",
          unfollow_after=42*60*60, sleep_delay=3)
        
         
    session.end()

**Comment by 2firstnames** [comment]
I am having the same issue...

Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    with smart_run(session):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/root/InstaPy/instapy/util.py", line 1679, in smart_run
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 407, in login
    self.bypass_with_mobile):
  File "/root/InstaPy/instapy/login_util.py", line 271, in login_user
    bypass_suspicious_login(browser, bypass_with_mobile)
  File "/root/InstaPy/instapy/login_util.py", line 137, in bypass_suspicious_login
    read_xpath(bypass_suspicious_login.__name__,"wrong_login")))
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver                                                       .py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver                                                       .py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver                                                       .py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhand                                                       ler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'v                                                       alue' must be a string
  (Session info: headless chrome=75.0.3770.80)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926                                                       ),platform=Linux 4.15.0-51-generic x86_64)

root@instapy:~/InstaPy# selenium.common.exceptions.InvalidArgumentException: Messa                                                       ge: invalid argument: 'value' must be a string
selenium.common.exceptions.InvalidArgumentException:: command not found

**Comment by lucicocosta** [comment]
The same error too!!!

**Comment by mateuszpokojowczyk** [comment]
Same error here.

**Comment by ghost** [comment]
Replace "NoSuchElementException" in 143 line of login_util.py with "Exception".

**Comment by positivez** [comment]
Same issue here, @mateuszpokojowczyk 's solution unfortunately did not solve the issue.

Any other recommendation would be highly appreciated.

Cheers!

**Comment by ghost** [comment]
Solved for me, though.

**Comment by grgaortiz** [comment]
Same issue for me as well. Not able to resolve. Other commands work great but using unfollow_users only yields this error response: 

`Sorry, an error occurred: Message: invalid argument: 'value' must be a string (Session info: headless chrome=75.0.3770.100) (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.12.3 x86_64)`
