### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: Element

### ISSUE THREAD

**Issue by westondeboer** [InstaPy/InstaPy#454]
`[58/100]
Image from: alirehman11
Number of Followers: 406
Link: https://www.instagram.com/p/BXQ7qVNnX1e/?tagged=clothes
Description: 😎 #ootd #outfitoftheday #lookoftheday #fashion #fashiongram #style #love #beautiful #currentlywearing #lookbook #wiwt #whatiwore #whatiworetoday #ootdshare #outfit #clothes #wiw #mylook #fashionista #todayimwearing #instastyle #instafashion #outfitpost #fashionpost #todaysoutfit #fashiondiaries
--> Image Liked!
--> Commented: Awesome!
Traceback (most recent call last):
  File "./docker_quickstart.py", line 23, in <module>
    .like_by_tags([ '#love'], amount=100)\
  File "/home/user/InstaPy/instapy/instapy.py", line 470, in like_by_tags
    followed += follow_user(self.browser, self.follow_restrict, self.username, user_name)
  File "/home/usern/InstaPy/instapy/unfollow_util.py", line 130, in follow_user
    follow_button.click()
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button class="_ah57t _84y62 _i46jh _rmr7s">...</button> is not clickable at point (688, 14). Other element would receive the click: <div class="_pq5am">...</div>
  (Session info: chrome=60.0.3112.78)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-21-generic x86_64)
`

This is a Selenium error right? 

Everything is updated, ubuntu, running in google cloud.

**Comment by westondeboer** [comment]
on line 126 in unfollow_util.py Changed 
`    follow_button = browser.find_element_by_xpath("//article/header/span/button")
`
to 

`    follow_button = browser.find_element_by_xpath("//*[contains(text(), 'Follow')]")
`

**Comment by westondeboer** [comment]
I have lowered like by tag amounts, and this seems to have fixed the issue.

**Comment by westondeboer** [comment]
This didn't fix it, I have added a sleep before follow_button

`
sleep(2)
follow_button = browser.find_element_by_xpath("//article/header/span/button")
`

And that fixed it.

**Comment by westondeboer** [comment]
Don't know why this was still coming up for me, but that did not fix it.

So instead I am faking the click:
`follow_button.send_keys("\n")`

And well see if the error comes up again, running it on two accounts now. 

had to import
```
from selenium.webdriver.common.keys import Keys

from selenium.webdriver.common.action_chains import ActionChains
```
