### ISSUE TITLE
NameError: name 'ModuleNotFoundError' is not defined

### ISSUE THREAD

**Issue by shrey1728** [InstaPy/InstaPy#4562]
starting instapy with quickstart
================================
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35\lib\site-packages\instapy\instapy.py", line 20, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named 'pyvirtualdisplay'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "C:\Users\shrey\AppData\Local\Programs\Python\Python35\lib\site-packages\instapy\__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "C:\Users\shrey\AppData\Local\Programs\Python\Python35\lib\site-packages\instapy\instapy.py", line 21, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
Press any key to continue . . .

**Comment by mikediachenko** [comment]
Seems you need to re-run full circle of installation procedure according to InstaPY wiki.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AlexKnoch** [comment]
Did you try installing pyvirtualdisplay? It's required for running on a server. 

Also, are you running in headless mode? Which driver?

**Comment by mariomolla** [comment]
it just happens me right now. How can I solve it?

**Comment by Viktor19931** [comment]
for me as well
