### ISSUE TITLE
Instapy Crash on Raspberry Pi 3B+ after few likes

### ISSUE THREAD

**Issue by shariqmoosa** [InstaPy/InstaPy#4570]
## Expected Behavior
Instapy Should continue liking the posts 

## Current Behavior
Instapy crashes after 150-160 likes

## Error log:

INFO [2019-06-21 23:12:37] [insta-account]  Like# [**162/1000**]
INFO [2019-06-21 23:12:37] [insta-account]  https://www.instagram.com/p/Bw8blMCnw2l/
INFO [2019-06-21 23:12:43] [insta-account]  Image from: b'tropcoollamarquedutemps'
INFO [2019-06-21 23:12:43] [insta-account]  Link: b'https://www.instagram.com/p/Bw8blMCnw2l/'
INFO [2019-06-21 23:12:43] [insta-account]  Description: b'Big Dog \xf0\x9f\x90\xb6 Tee-shirts \xc2\xbb Disponible sur www.tropcool.me \xf0\x9f\x99\x83 #tropcoollamarquedutemps \xe2\x8f\xb3'
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1045, in web_address_navigator
    browser.get(link)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=72.0.3626.121)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.42-v7+ armv7l)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart-mc.py", line 32, in <module>
    session.like_by_tags(['digitalmarketing'], amount=1000)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 1797, in like_by_tags
    user_name)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 1214, in validate_user_call
    self.logfolder)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 276, in validate_username
    web_address_navigator(browser, user_link)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1058, in web_address_navigator
    str(exc).encode("utf-8")))
selenium.common.exceptions.TimeoutException: Message: Retried 7 times to GET 'b'https://www.instagram.com/tropcoollamarquedutemps/'' webpage but failed out of a timeout!
	b'Message: timeout\n  (Session info: headless chrome=72.0.3626.121)\n  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.42-v7+ armv7l)\n'

## InstaPy configuration

rom instapy import InstaPy

insta_username = xxx
insta_password = xxx

session = InstaPy(username=insta_username, password=insta_password, headless_browser=True, disable_image_load=True)
session.login()

session.set_relationship_bounds(enabled=False,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)

session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(57, 585),
                               peak_comments=(21, 182),
                                peak_follows=(48, None),
                                 peak_unfollows=(35, 402),
                                  peak_server_calls=(None, 4700))

session.like_by_tags(['digitalmarketing'], amount=1000)

session.end()

**Comment by rodriguesprobr** [comment]
Same error on Ubuntu 18.04
