### ISSUE TITLE
Crash when calling get_relationship_counts() on inexistent/not-found instagram username.

### ISSUE THREAD

**Issue by tibohei** [InstaPy/InstaPy#4575]
## Expected Behavior

Do not call `get_relationship_counts()` on an invalid instagram username or the function `get_relationship_counts()` must handle invalid usernames.

## Current Behavior

`get_relationship_counts()` is called on invalid or non-existing usernames (e.g. `'_.lintey._'`) and raises an exception (see logs). Call on `user_link` return HTML Status Code 404 which leads to `JavascriptException: Message: javascript error: Cannot read property 'entry_data' of undefined` later in the code.

## Possible Solution (optional)

Validate instagram username before calling `get_relationship_counts()` or return someting like `'user not found'`or handle the exception.

### InstaPy logs

When executing `interact_user_followers()`

```
Jun 23 12:32:47 02813dd864fd python3[17692]: INFO     [2019-06-23 12:32:47] [0x2813dd864fd] [**********] Starting to interact by users..
Jun 23 12:32:47 02813dd864fd python3[17692]: INFO     [2019-06-23 12:32:47] [0x2813dd864fd] [**********] Username [1/1]
Jun 23 12:32:47 02813dd864fd python3[17692]: INFO     [2019-06-23 12:32:47] [0x2813dd864fd] [**********] --> b'emily_biltris'
Jun 23 12:32:47 02813dd864fd python3[17692]: INFO     [2019-06-23 12:32:47] [0x2813dd864fd] [**********] username actions: following=True commenting=False liking=False
Jun 23 12:32:47 02813dd864fd python3[17692]: INFO     [2019-06-23 12:32:47] [0x2813dd864fd] [**********] Getting emily_biltris image list...
Jun 23 12:32:51 02813dd864fd python3[17692]: INFO     [2019-06-23 12:32:51] [0x2813dd864fd] [**********] Post [1/3]
Jun 23 12:32:51 02813dd864fd python3[17692]: INFO     [2019-06-23 12:32:51] [0x2813dd864fd] [**********] https://www.instagram.com/p/ByKBLY-nyqb/
Jun 23 12:32:56 02813dd864fd python3[17692]: INFO     [2019-06-23 12:32:56] [0x2813dd864fd] [**********] Image from: b'emily_biltris'
Jun 23 12:32:56 02813dd864fd python3[17692]: INFO     [2019-06-23 12:32:56] [0x2813dd864fd] [**********] Link: b'https://www.instagram.com/p/ByKBLY-nyqb/'
Jun 23 12:32:56 02813dd864fd python3[17692]: INFO     [2019-06-23 12:32:56] [0x2813dd864fd] [**********] Description: b'\xe2\x98\x80\xef\xb8\x8f\xe2\x98\x81\xef\xb8\x8f\xe2\xad\x90\xef\xb8\x8f\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n#juucehaircare #VSCO #pink #purple #mac #toofaced #tea #sis #sister #life #living #glam #photo #instagram #stila #sun #morphe #cottonon #sportsgirl #aus #au #australia #pets'
Jun 23 12:32:56 02813dd864fd python3[17692]: INFO     [2019-06-23 12:32:56] [0x2813dd864fd] [**********] Location: b'Coco Chanel'
Jun 23 12:32:56 02813dd864fd python3[17692]: INFO     [2019-06-23 12:32:56] [0x2813dd864fd] [**********] Post [1/3]
Jun 23 12:32:56 02813dd864fd python3[17692]: INFO     [2019-06-23 12:32:56] [0x2813dd864fd] [**********] https://www.instagram.com/p/ByBaRZgnt3d/
Jun 23 12:33:01 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:01] [0x2813dd864fd] [**********] Image from: b'emily_biltris'
Jun 23 12:33:01 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:01] [0x2813dd864fd] [**********] Link: b'https://www.instagram.com/p/ByBaRZgnt3d/'
Jun 23 12:33:01 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:01] [0x2813dd864fd] [**********] Description: b'\xf0\x9f\x8c\xbalive your own life\xf0\x9f\x8c\xba \xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n#CGM #VSCO #pink #purple #mac #toofaced #tea #sis #sister #life #living #glam #photo #instagram #stila #sun #morphe #cottonon #sportsgirl #aus #au #australia #pets #emily #melbourne #scoutme #livinglife #juccehaircare #hairjam'
Jun 23 12:33:01 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:01] [0x2813dd864fd] [**********] Location: b'Melbourne, Victoria, Australia'
Jun 23 12:33:01 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:01] [0x2813dd864fd] [**********] Post [1/3]
Jun 23 12:33:01 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:01] [0x2813dd864fd] [**********] https://www.instagram.com/p/ByECYOlH8Pg/
Jun 23 12:33:06 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:06] [0x2813dd864fd] [**********] Image from: b'emily_biltris'
Jun 23 12:33:06 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:06] [0x2813dd864fd] [**********] Link: b'https://www.instagram.com/p/ByECYOlH8Pg/'
Jun 23 12:33:06 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:06] [0x2813dd864fd] [**********] Description: b'\xf0\x9f\x92\x95Be you\xf0\x9f\x92\x95\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n#CGM #VSCO #pink #purple #mac #toofaced #tea #sis #sister #life #living #glam #photo #instagram #stila #sun #morphe #cottonon #sportsgirl #aus #au #australia #pets #hairjam #juuce_haircare #juccehaircare'
Jun 23 12:33:06 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:06] [0x2813dd864fd] [**********] Location: b'Melbourne, Victoria, Australia'
Jun 23 12:33:14 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:14] [0x2813dd864fd] [**********] --> Followed 'b'emily_biltris''!
Jun 23 12:33:17 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:17] [0x2813dd864fd] [**********] -------------
Jun 23 12:33:17 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:17] [0x2813dd864fd] [**********] --> Given amount not fullfilled, image pool reached its end
Jun 23 12:33:19 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:19] [0x2813dd864fd] [**********] User 'trangvu912' [6/49]
Jun 23 12:33:22 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:22] [0x2813dd864fd] [**********] User: 'trangvu912'  |> followers: 13  |> following: 185  |> relationship ratio: 0.07
Jun 23 12:33:22 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:22] [0x2813dd864fd] [**********] User 'trangvu912's followers count is less than minimum limit  ~skipping user
Jun 23 12:33:22 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:22] [0x2813dd864fd] [**********] User 'sahlty.poison_' [7/49]
Jun 23 12:33:26 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:26] [0x2813dd864fd] [**********] User: 'sahlty.poison_'  |> followers: 1114  |> following: 1000  |> relationship ratio: 1.11
Jun 23 12:33:26 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:26] [0x2813dd864fd] [**********] User 'sahlty.poison_'s following count exceeds maximum limit  ~skipping user
Jun 23 12:33:26 02813dd864fd python3[17692]: INFO     [2019-06-23 12:33:26] [0x2813dd864fd] [**********] User '_.lintey._' [8/49]
Jun 23 12:33:29 02813dd864fd python3[17692]: Process Process-16:
Jun 23 12:33:29 02813dd864fd python3[17692]: Traceback (most recent call last):
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/opt/boxagram-box/libs/InstaPy/instapy/util.py", line 939, in get_relationship_counts
Jun 23 12:33:29 02813dd864fd python3[17692]:     "return window._sharedData.entry_data."
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
Jun 23 12:33:29 02813dd864fd python3[17692]:     'args': converted_args})['value']
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
Jun 23 12:33:29 02813dd864fd python3[17692]:     self.error_handler.check_response(response)
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
Jun 23 12:33:29 02813dd864fd python3[17692]:     raise exception_class(message, screen, stacktrace)
Jun 23 12:33:29 02813dd864fd python3[17692]: selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'entry_data' of undefined
Jun 23 12:33:29 02813dd864fd python3[17692]:   (Session info: headless chrome=73.0.3683.75)
Jun 23 12:33:29 02813dd864fd python3[17692]:   (Driver info: chromedriver=73.0.3683.75,platform=Linux 4.19.38-sunxi armv7l)
Jun 23 12:33:29 02813dd864fd python3[17692]: During handling of the above exception, another exception occurred:
Jun 23 12:33:29 02813dd864fd python3[17692]: Traceback (most recent call last):
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
Jun 23 12:33:29 02813dd864fd python3[17692]:     self.run()
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
Jun 23 12:33:29 02813dd864fd python3[17692]:     self._target(*self._args, **self._kwargs)
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/opt/boxagram-box/main.py", line 544, in bot
Jun 23 12:33:29 02813dd864fd python3[17692]:     session.interact_user_followers(settings['interactUserFollowers']['users'],**settings['interactUserFollowers']['kwargs'])
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/opt/boxagram-box/libs/InstaPy/instapy/instapy.py", line 2891, in interact_user_followers
Jun 23 12:33:29 02813dd864fd python3[17692]:     validation, details = self.validate_user_call(person)
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/opt/boxagram-box/libs/InstaPy/instapy/instapy.py", line 1214, in validate_user_call
Jun 23 12:33:29 02813dd864fd python3[17692]:     self.logfolder)
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/opt/boxagram-box/libs/InstaPy/instapy/util.py", line 188, in validate_username
Jun 23 12:33:29 02813dd864fd python3[17692]:     logger)
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/opt/boxagram-box/libs/InstaPy/instapy/util.py", line 945, in get_relationship_counts
Jun 23 12:33:29 02813dd864fd python3[17692]:     browser.find_element_by_xpath(read_xpath(get_relationship_counts.__name__,"followers_count")).text)
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
Jun 23 12:33:29 02813dd864fd python3[17692]:     return self.find_element(by=By.XPATH, value=xpath)
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
Jun 23 12:33:29 02813dd864fd python3[17692]:     'value': value})['value']
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
Jun 23 12:33:29 02813dd864fd python3[17692]:     self.error_handler.check_response(response)
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
Jun 23 12:33:29 02813dd864fd python3[17692]:     raise exception_class(message, screen, stacktrace)
Jun 23 12:33:29 02813dd864fd python3[17692]: selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'value' must be a string
Jun 23 12:33:29 02813dd864fd python3[17692]:   (Session info: headless chrome=73.0.3683.75)
Jun 23 12:33:29 02813dd864fd python3[17692]:   (Driver info: chromedriver=73.0.3683.75,platform=Linux 4.19.38-sunxi armv7l)
Jun 23 12:33:29 02813dd864fd python3[17692]: Exception in thread Thread-56:
Jun 23 12:33:29 02813dd864fd python3[17692]: Traceback (most recent call last):
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
Jun 23 12:33:29 02813dd864fd python3[17692]:     self.run()
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/usr/lib/python3.5/threading.py", line 1180, in run
Jun 23 12:33:29 02813dd864fd python3[17692]:     self.function(*self.args, **self.kwargs)
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/opt/boxagram-box/main.py", line 434, in start_bot
Jun 23 12:33:29 02813dd864fd python3[17692]:     if return_dict["exit_status"] == 0:
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "<string>", line 2, in __getitem__
Jun 23 12:33:29 02813dd864fd python3[17692]:   File "/usr/lib/python3.5/multiprocessing/managers.py", line 732, in _callmethod
Jun 23 12:33:29 02813dd864fd python3[17692]:     raise convert_to_error(kind, result)
Jun 23 12:33:29 02813dd864fd python3[17692]: KeyError: 'exit_status'

```

**Comment by JustAskMarina** [comment]
Is happening to me too. Don't know if solution [#4305](https://github.com/timgrossmann/InstaPy/issues/4305) would be effective because we're dealing with inexistent/not-found accounts.
