### ISSUE TITLE
Error while run instapy in a server

### ISSUE THREAD

**Issue by TheBestNoobEver** [InstaPy/InstaPy#4579]
Hello everybody, 

First i'm sorry for my english. 

So, i installed instapy on my ubuntu server (aws.amazon server) and then i tried to run instapy after the installation but i don't really understand what happening... 

I don't understand why i have this error message and why i can run instapy from windows but not from my ubuntu server. 

There is the error message after typing " python3 quickstart.py " 

ubuntu@ip-172-31-23-148:~/instapy-quickstart$ python3 quickstart.py

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/ubuntu/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 24, in <module>
    headless_browser=True)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 309, in __init__
    self.set_selenium_local_session()
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 361, in set_selenium_local_session
    self.logger)
  File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 146, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/ubuntu/InstaPy/assets/chromedriver'
ubuntu@ip-172-31-23-148:~/instapy-quickstart$

Thanks if someone can help me !!

**Comment by mikediachenko** [comment]
@TheBestNoobEver Hi. Are you sure that while installation there were no error? Did you make changes in quickstart.py script?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheBestNoobEver** [comment]
It's ok, i found the what happend. My drivers was not the good ones and also import the webdriver into the script and change the value of the webbrowser line in the script in =True !!

Thanks !

if you know someone who have the same problem let me know

**Comment by papillon-unix** [comment]
@TheBestNoobEver I've the same since updated to 0.6 : how did you fix it?
