### ISSUE TITLE
To few images, skipping this tag

### ISSUE THREAD

**Issue by skaeslin** [InstaPy/InstaPy#4612]
Hello everyone
There have already been problems like these in the past, but they have been solved and merged. So this seems to be something different. 

Thanks a lot in advance for your help. 

# Expected Behavior

Like images

## Current Behavior

Skipping a lot of tags because of "Too few images, skipping this tag"

## Possible Solution (optional)

???

## InstaPy configuration
IntsaPy on Raspberry Pi 3, just installed everything new today. 

```
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-03 23:46:36] [sk]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo


...................................................................
INFO [2019-07-03 23:48:25] [sk]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-07-03 23:48:25] [sk]  Saving account progress...
WARNING [2019-07-03 23:48:29] [sk]  Unable to save account progress, skipping data update
INFO [2019-07-03 23:49:07] [sk]  Tag [1/16]
INFO [2019-07-03 23:49:07] [sk]  --> b'justgoshoot'
INFO [2019-07-03 23:55:55] [sk]  Too few images, skipping this tag

INFO [2019-07-03 23:49:26] [sk]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 102 users & had 1015 FOLLOWERS
[Session lasted 2.86 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-03 23:49:26] [sk]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "quickstart.py", line 41, in <module>
    session.like_by_tags(['justgoshoot', 'djiglobal', 'worldplaces', 'myfeatureshoot', 'blickheimat', 'drohne', 'fotografie', 'artofvisuals', 'mavicpro', 'exploretocreate', 'liveofadventure', 'folkmagazine', 'theglobewanderer', 'peoplescreatives', 'watson_schweiz', 'visualsoflife'], amount=3)   
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 1755, in like_by_tags
    self.logger)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/like_util.py", line 235, in get_links_for_tag
    web_address_navigator(browser, tag_link)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1045, in web_address_navigator
    browser.get(link)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unknown sessionId
  (Session info: headless chrome=67.0.3396.87)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.52-v7+ armv7l)
```

Instapy file: 
```

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True,
                  bypass_suspicious_attempt=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=False,
				 potency_ratio=1,
				  delimit_by_numbers=True,
				   max_followers=10000,
				    max_following=2000,
				     min_followers=400,
				      min_following=50)
    session.set_dont_include([XXX])
    session.set_dont_like(['pizza', 'girl', 'nsfw', 'naked'])


    # actions
    session.like_by_tags(['justgoshoot', 'djiglobal', 'worldplaces', 'myfeatureshoot', 'blickheimat', 'drohne', 'fotografie', 'artofvisuals', 'mavicpro', 'exploretocreate', 'liveofadventure', 'folkmagazine', 'theglobewanderer', 'peoplescreatives', 'watson_schweiz', 'visualsoflife'], amount=3)   


finally:
    # end the bot session
    session.end()
```

**Comment by module17** [comment]
Instagram updates it seems. This started happening in the past day or so. Perhaps your instance has been detected as bot activity. Does the account work with another device?

**Comment by C3PablO** [comment]
having this same problem. I'm not sure what to do. I'm running the latest instapy

**Comment by its-ogawa** [comment]
I'm having the same problem.

I'm using common tags like "instagood", but the message "To few images" is a bit confusing.
