### ISSUE TITLE
Instapy stops after liking a picture

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#4614]

**Comment by Tr1pke** [comment]
Every action gives an error 
```
INFO [2019-07-04 13:02:45] [MyAccount]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-07-04 13:02:45] [MyAccount]  Saving account progress...

____________________________________________________________________________________
INFO [2019-07-04 13:02:49] [MyAccount]  Starting to follow user `Followers`..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-07-04 13:02:49] [MyAccount]  User 'xxx' [1/4]


INFO [2019-07-04 13:03:03] [MyAccount]  Grabbed 1 usernames from 'blabla's `Followers` to do following

INFO [2019-07-04 13:03:03] [MyAccount]  Ongoing Follow [1/1]: now following 'xxx_xxx'...
INFO [2019-07-04 13:03:06] [MyAccount]  User: 'xxx'  |> followers: 115  |> following: 105  |> relationship ratio: 1.09
INFO [2019-07-04 13:03:15] [MyAccount]  --> Followed 'xxx_xxx''!

INFO [2019-07-04 13:03:16] [MyAccount]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 271 users & had 9963 FOLLOWERS
[Session lasted 1.08 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-04 13:03:16] [MyAccount]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "InstaPy/MyAccount-scriptje.py", line 28, in <module>
    session.follow_user_followers(['xxx','xxx_xxx','xx.xx','xx_xx'], amount=1, randomize=True, interact=False)
  File "/home/steven/.local/lib/python3.7/site-packages/instapy/instapy.py", line 3255, in follow_user_followers
    interact)
  File "/home/steven/.local/lib/python3.7/site-packages/instapy/instapy.py", line 1088, in follow_by_list
    self.logfolder)
```
