### ISSUE TITLE
Bug at launch 

### ISSUE THREAD

**Issue by Micktoon** [InstaPy/InstaPy#4615]
## Expected Behavior
The bot should launch the chrome window and start working 

## Current Behavior
However, this one doesn't launch anything and indicates the following error code, but from time to time it will still work.

```
Traceback (most recent call last):
  File "quickstart.py", line 26, in <module>
    with smart_run(session):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 1679, in smart_run
    session.login()
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 407, in login
    self.bypass_with_mobile):
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/login_util.py", line 173, in login_user
    reload_webpage(browser)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 1706, in reload_webpage
    browser.execute_script("location.reload()")
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: unknown sessionId
  (Session info: chrome=74.0.3729.157)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.50-v7+ armv7l)
```

## InstaPy configuration
Instapy is install in Raspbery Pi B+

Thx,

**Comment by Micktoon** [comment]
I have a problem with likes, the bot does 1 and crashes with error 

```
Traceback (most recent call last):
  File "quick.py", line 59, in <module>
    amount=random.randint(50, 100), interact=True)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 1811, in like_by_tags
    liked_img)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/like_util.py", line 696, in like_image
    naply = get_action_delay("like")
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 1771, in get_action_delay
    custom_delay = config[action]
KeyError: 'like'

```
