### ISSUE TITLE
Exception when init work

### ISSUE THREAD

**Issue by vincenzopalazzo** [InstaPy/InstaPy#4630]
## Expected Behavior and Current Behavior
```
Traceback (most recent call last):
  File "quickstart.py", line 27, in <module>
    "london", "amazing", "paris", "holiday", "life", "toscana"], amount=10)
  File "/home/vincenzo/Instapy/InstaPy/instapy/instapy.py", line 1811, in like_by_tags
    liked_img)
  File "/home/vincenzo/Instapy/InstaPy/instapy/like_util.py", line 696, in like_image
    naply = get_action_delay("like")
  File "/home/vincenzo/Instapy/InstaPy/instapy/util.py", line 1771, in get_action_delay
    custom_delay = config[action]
KeyError: 'like'

```
## InstaPy configuration

```
# imports
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

# login credentials
insta_username = 'myUsername'
insta_password = 'myPassword'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)


with smart_run(session):
  """ Activity flow """		
  # activity		
  session.like_by_tags(['italy',
                          'italia', 'love', 'travel', 'photography', 'instagood',
                          'picoftheday', 'nature', 'photooftheday', 'follow', 'instagram',
                          'rome', 'milano', 'photo', 'sea', 'fashion', "landscape", "igersitalia", "beautiful",
                          "instalike", "food", "europe", "travelphotography", "italian", "sky", "bhfyp", 
                          "architecture", "sun", "style", "napoli", "france", "sunset", "spring", "sicily", "music", "mare", "madeinitaly",
                          "usa", "milan", "puglia", "tuscany", "travelgram", "foodporn", "likeforlikes", "followme", "germany", "summer",
                         "london", "amazing", "paris", "holiday", "life", "toscana"], amount=10)
```

**Comment by beatdeddeer** [comment]
You have to use ‘ not “ change that and I think it will work :)

**Comment by vincenzopalazzo** [comment]
@beatdeddeer Where?

**Comment by vincenzopalazzo** [comment]
@beatdeddeer The problem persisted
