### ISSUE TITLE
New Error Pls Help

### ISSUE THREAD

**Issue by GPaolella12** [InstaPy/InstaPy#4636]
## Expected Behavior
Follow
## Current Behavior
Traceback (most recent call last):
  File ".\ardnajela_m.py", line 92, in <module>
    job()
  File ".\ardnajela_m.py", line 76, in job
    session.follow_user_followers(referencias, amount=100, randomize=False, sleep_delay=60)
  File "C:\Users\Admin\Desktop\masFollows\InstaPy\instapy\instapy.py", line 3255, in follow_user_followers
    interact)
  File "C:\Users\Admin\Desktop\masFollows\InstaPy\instapy\instapy.py", line 1088, in follow_by_list
    self.logfolder)
  File "C:\Users\Admin\Desktop\masFollows\InstaPy\instapy\unfollow_util.py", line 764, in follow_user
    naply = get_action_delay("follow")
  File "C:\Users\Admin\Desktop\masFollows\InstaPy\instapy\util.py", line 1771, in get_action_delay
    custom_delay = config[action]
KeyError: 'follow'
## InstaPy configuration
```
from instapy import smart_run
from instapy import set_workspace
import schedule
import time
import random
from instapy import InstaPy

#your login credentials
insta_username = ''
insta_password = ''

#referencias
referencias = ['haruescarcega', 'tania_karam_oficial', 'Andrea.delamora', 'psictalinacuen']

#locations
locations = ['213270076/mexico-city-mexico/']

#hashtags
tags = ['AccessConsciousness', 'MedicinaAlternativa', 'ThetaHealing', 'TerapiasHolísticas']

#path to your workspace
set_workspace(path=None)

session = InstaPy(username=insta_username,
                password=insta_password,
                headless_browser=False,
                disable_image_load=True,
                bypass_suspicious_attempt=True,
                multi_logs=True)

def job():

    with smart_run(session):
        """ Activity flow """
        # settings
        session.set_relationship_bounds(enabled=True,
                                        max_followers=15000)

        session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(57, 585),
                               peak_comments=(21, 182),
                                peak_follows=(48, 550),
                                 peak_unfollows=(35, 402),
                                  peak_server_calls=(None, 4700))

        # session.set_dont_include(friends)
        # session.set_dont_like(dont_likes)
        # session.set_ignore_if_contains(ignore_list)

        session.set_skip_users(skip_private=False,
                       private_percentage=100)

        session.set_user_interact(amount=2, randomize=True, percentage=60)
        session.set_do_follow(enabled=True, percentage=40)
        session.set_do_like(enabled=True, percentage=80)

        # activity

        #cantidades
            #follows = 200 + 100 + 100 = 400
            #likes = 200 + 50 = 250
            #unfollows = 150

        #LOCATIONS
        # session.follow_by_locations(locations, amount=200, skip_top_posts=Fsalse)
        # session.like_by_locations(locations, amount=200)

        # #REFERENCIAS
        session.follow_user_followers(referencias, amount=100, randomize=False, sleep_delay=60)

        # #TAGS
        session.like_by_tags(random.sample(tags, 3),
                             amount=random.randint(25, 50), interact=True)
        session.follow_by_tags(tags, amount=100)

        #UNFOLLOW
        session.unfollow_users(amount=random.randint(75, 150),
                               InstapyFollowed=(True, "all"), style="FIFO",
                               unfollow_after=5 * 60 * 60, sleep_delay=501)
        session.unfollow_users(amount=random.randint(75, 150),
                               InstapyFollowed=(False, "all"), style="FIFO",
                               nonFollowers=True,
                               unfollow_after=5 * 60 * 60, sleep_delay=501)
        # session.join_pods()
job()
schedule.every().day.at("09:00").do(job)
while True:
  schedule.run_pending()
  time.sleep(10)
```

**Comment by GPaolella12** [comment]
pls help!

**Comment by GitNees** [comment]
I have a simular issue the moment is Likes something it crashes.
But last line is: KeyError: 'like'

Might be related

**Comment by stevecohenfr** [comment]
I got a similar issue too, my last line is :

    KeyError: 'follow'

I think something has changed in Instagram HTML and InstaPy has to be updated.

To avoid this crash I applied this PR to my InstaPy : #4620

    curl https://patch-diff.githubusercontent.com/raw/timgrossmann/InstaPy/pull/4620.patch | git am

It avoid crash but InstaPy still have problems, now it say that it "can't verify the follow"
