### ISSUE TITLE
massive follow and unfollow error

### ISSUE THREAD

**Issue by immersivescience** [InstaPy/InstaPy#4649]
## Current Behavior
Traceback (most recent call last):
  File "C:\Users\Phillip\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\quickstart.py", line 19, in <module>
    from instapy import InstaPy
  File "C:\Users\Phillip\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 25, in <module>
    from .clarifai_util import check_image
ImportError: attempted relative import with no known parent package
>>>

**Comment by ayushere** [comment]
comment out clarifai module
