### ISSUE TITLE
Errno 111 between runs

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4666]
Hi,
so I migrated instapy to Ubuntu Desktop 18.04 LTS because of turning off headless browser.
It doesn't work fine for me. If I run script, everything goes ok but if script runs again in i.e. 1 hour, it shows me error:

`On session start was FOLLOWING 442 users & had 2129 FOLLOWERS
[Session lasted 4.67 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-15 20:01:06] [myinstausername]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2019-07-15 20:10:00] [myinstausername]  Sessional Live Report:
	|> LIKED 1 images  |  ALREADY LIKED: 1
	|> COMMENTED on 0 images
	|> FOLLOWED 2 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 1 users
	|> LIKED 0 comments
	|> REPLIED to 0 comments
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0

On session start was FOLLOWING 442 users & had 2129 FOLLOWERS
[Session lasted 13.57 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-15 20:10:00] [myinstausername]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2ec7bc9c88>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myusername/scripts/instagram/instapy/test.py", line 49, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 563, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
  File "/home/myusername/scripts/instagram/instapy/test.py", line 18, in job
    with smart_run(session):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/instapy/util.py", line 1679, in smart_run
    session.login()
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 407, in login
    self.bypass_with_mobile):
  File "/usr/local/lib/python3.6/dist-packages/instapy/login_util.py", line 160, in login_user
    web_address_navigator(browser, ig_homepage)
  File "/usr/local/lib/python3.6/dist-packages/instapy/util.py", line 1025, in web_address_navigator
    current_url = get_current_url(browser)
  File "/usr/local/lib/python3.6/dist-packages/instapy/util.py", line 1558, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py", line 326, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=33451): Max retries exceeded with url: /session/fddfc6cccddf4c9400de0cb2f8a43384/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ec7bc9c88>: Failed to establish a new connection: [Errno 111] Connection refused',))

`

**Comment by ghost** [comment]
My script (test):
> """ InstaPy script """
> # imports
> from instapy import InstaPy
> from instapy import smart_run
> import schedule
> import time
> 
> # login credentials
> insta_username = 'myinstausername'
> insta_password = 'umypassword'
> 
> # get an InstaPy session!
> # set headless_browser=True to run InstaPy in the background
> session = InstaPy(username=insta_username,
>                   password=insta_password,
>                   headless_browser=False)
> def job():
>  with smart_run(session):
> 
>     # activity
>     session.like_by_tags(["hashtag1", "hashtag2"], randomize=True, amount=1)
>     session.follow_by_tags(['hashtag1', 'hashtag2'], randomize=True, amount=1)
>     session.unfollow_users(amount=1, InstapyFollowed=(True, "all"), style="RANDOM", unfollow_after=24*60*60, sleep_delay=300)
>     #session.like_by_feed(amount=5, randomize=True, unfollow=False, interact=True)
> 
>     session.set_skip_users(skip_private=True,
>                            private_percentage=100,
>                            skip_no_profile_pic=True,
>                            no_profile_pic_percentage=100)
> 
>     session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
>                               peak_likes=(50, 307),
>                                peak_comments=(21, 182),
>                                 peak_follows=(50, None),
>                                  peak_unfollows=(50, None),
>                                   peak_server_calls=(None, 4700))
> 
> schedule.every().day.at("20:10").do(job)
> schedule.every().day.at("20:20").do(job)
> 
> while True:
>     schedule.run_pending()
> time.sleep(1)
