### ISSUE TITLE
Installing instapy on raspberry pi 3 B+

### ISSUE THREAD

**Issue by stuart5915** [InstaPy/InstaPy#4690]
I have been struggling for a couple days on this and figured you guys could help me out <3

When I startup my script this is the error...

Traceback (most recent call last):
  File "/home/pi/InstaPy/Stuart.py", line 28, in <module>
    with smart_run(session):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 1679, in smart_run
    session.login()
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 407, in login
    self.bypass_with_mobile):
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/login_util.py", line 173, in login_user
    reload_webpage(browser)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 1706, in reload_webpage
    browser.execute_script("location.reload()")
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=74.0.3729.157)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.57-v7+ armv7l)

Any suggestions or ideas for this to start working?

**Comment by shhackleton** [comment]
Same here! No answer from the developers was given...

**Comment by pinkpanthers** [comment]
hoping i would get some answers here but i also have some trouble with the following terminal responses:


  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 53, in <module>
    with smart_run(session):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1677, in smart_run
    session.login()
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 411, in login
    self.bypass_with_mobile):
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/login_util.py", line 182, in login_user
    reload_webpage(browser)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1704, in reload_webpage
    browser.execute_script("location.reload()")
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/poolmanager.py", line 326, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

**Comment by pinkpanthers** [comment]
I have also tried running everything on win10 and it works perfectly fine.

**Comment by andifds** [comment]
Have you checked chrome or chromium is already installed? Have you installed the correct chromedriver for RPi ?

## How to keep updated on Raspberry Pi
Keep your setup updated, but keeping ```instapy-chromedriver==2.36.post0```

1. ```sudo pip install instapy -U```
2. ```sudo pip uninstall instapy-chromedriver```
3. ```sudo pip install instapy-chromedriver==2.36.post0```

**Comment by KatzeMau** [comment]
Same problem but i cant fix it :) 👎🏻
