### ISSUE TITLE
Problems setting up Chromedriver on Raspbian

### ISSUE THREAD

**Issue by gosadaque** [InstaPy/InstaPy#4727]
Hey, so I already set InstaPy up befor on several servers (four or five times). But I admit I'm giving up right now setting it up on my new Raspberry, just bought for running InstaPy on.
Already tried to reinstall several times, including resetting whole SD card, to be sure.
## Expected Behavior
Running..

## Current Behavior
```
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-28 16:07:25] [usernamerino]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...
ERROR [2019-07-28 16:07:31] [dohhc]  Error occurred while deleting cookies from web browser!
        b'Message: chrome not reachable\n  (Session info: headless chrome=74.0.3729.157)\n  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.58-v7+ armv7l)\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/instapy/util.py", line 1677, in smart_run
    session.login()
  File "/usr/local/lib/python3.7/dist-packages/instapy/instapy.py", line 411, in login
    self.bypass_with_mobile):
  File "/usr/local/lib/python3.7/dist-packages/instapy/login_util.py", line 182, in login_user
    reload_webpage(browser)
  File "/usr/local/lib/python3.7/dist-packages/instapy/util.py", line 1704, in reload_webpage
    browser.execute_script("location.reload()")
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=74.0.3729.157)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.58-v7+ armv7l)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/instapy/browser.py", line 243, in close_browser
    browser.delete_all_cookies()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=74.0.3729.157)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.58-v7+ armv7l)


INFO [2019-07-28 16:07:31] [usernamerino]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 9.76 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-28 16:07:31] [usernamerino]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "quickstart.py", line 18, in <module>
    with smart_run(session):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/dist-packages/instapy/util.py", line 1677, in smart_run
    session.login()
  File "/usr/local/lib/python3.7/dist-packages/instapy/instapy.py", line 411, in login
    self.bypass_with_mobile):
  File "/usr/local/lib/python3.7/dist-packages/instapy/login_util.py", line 182, in login_user
    reload_webpage(browser)
  File "/usr/local/lib/python3.7/dist-packages/instapy/util.py", line 1704, in reload_webpage
    browser.execute_script("location.reload()")
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=74.0.3729.157)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.58-v7+ armv7l)`
```

I tried to delete the /InstaPy/db, because of this "cookie delete error".
-> Same error
Added 777 rights on all ChromeDriver files
-> Same error

## InstaPy configuration

```
""" Quickstart script for InstaPy usage """

# imports
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace


# set workspace folder at desired location (default is at your home folder)


# get an InstaPy session!
session = InstaPy(username="usernamerino",
                  password="hardpasswordiguess",
                  headless_browser=True,
                  nogui=True)

with smart_run(session):
    # general settings
    session.set_dont_include(["friend1", "friend2", "friend3"])

    # activity
    session.like_by_tags(["natgeo"], amount=10)
```

If you need any additional information, just ask.

I thank a lot in advance for all help

EDIT: Only aesthetics

**Comment by andifds** [comment]
Have you checked if `chrome-browser` or `chromium-browser` it is already installed?

**Comment by gosadaque** [comment]
> Have you checked if `chrome-browser` or `chromium-browser` it is already installed?

It is installed right now. Or do you mean pre-installed?

**Comment by Mathieu-5** [comment]
Same for me ... Which Python Version ?

**Comment by gosadaque** [comment]
> Same for me ... Which Python Version ?

```
python3 --version
Python 3.7.3
```
Seems ok to me

**Comment by FareedyB** [comment]
> > Same for me ... Which Python Version ?
> 
> ```
> python3 --version
> Python 3.7.3
> ```
> 
> Seems ok to me

Getting this exact same issue. Seems Pythion 3.7.3 not playing ball with the installation instructions

**Comment by mikediachenko** [comment]
@gosadaque Please, remove option `nogui=True` from the config and try again.
