### ISSUE TITLE
Error after update Help Please

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#4758]
C:\Users\VFit-Family\Desktop\test>python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\VFit-Family\Desktop\test\instapy\__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "C:\Users\VFit-Family\Desktop\test\instapy\instapy.py", line 79, in <module>
    from .browser import set_selenium_local_session
  File "C:\Users\VFit-Family\Desktop\test\instapy\browser.py", line 10, in <module>
    from fake_useragent import UserAgent, FakeUserAgentError
ModuleNotFoundError: No module named 'fake_useragent'

**Comment by converge** [comment]
pip3 install -r requirements.txt

**Comment by johnvfitness** [comment]
Thx Bro 👌💪

**Comment by johnvfitness** [comment]
@converge 

C:\Users\VFit-Family>pip3 install -r

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

-r option requires 1 argument

C:\Users\VFit-Family>

**Comment by johnvfitness** [comment]
@converge  

INFO [2019-08-03 16:08:59] [mr_and_mrs_vfit]  --> Image Liked!
INFO [2019-08-03 16:09:26] [mr_and_mrs_vfit]  -------- WARNING! Image was NOT liked! You are have a BLOCK on likes!

**Comment by johnvfitness** [comment]
@converge 

Traceback (most recent call last):
  File "C:\Users\VFit-Family\Google Drive\Bot\John-Bot.py", line 104, in job3
    session = InstaPy(username=insta_username, password=insta_password, headless_browser=False, multi_logs=False)
  File "C:\Users\VFit-Family\Google Drive\Bot\instapy\instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "C:\Users\VFit-Family\Google Drive\Bot\instapy\instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at C:\Users\VFit-Family\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy_chromedriver\chromedriver_win32.exe
