### ISSUE TITLE
cannot focus element on comment in like_by_tag

### ISSUE THREAD

**Issue by JMuffin** [InstaPy/InstaPy#4774]
When trying to comment in like_by_tag (using smart hastags) I get the error:

Traceback (most recent call last):
  File "JMuffin2.py", line 40, in <module>
    session.like_by_tags(amount=30, use_smart_hashtags=True)
  File "/home/pi/InstaPy-jmuffin/instapy/instapy.py", line 1765, in like_by_tags
    self.logfolder)
  File "/home/pi/InstaPy-jmuffin/instapy/comment_util.py", line 78, in comment_image
    comment_input[0].send_keys('\b')
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot focus element
  (Session info: headless chrome=63.0.3239.84)
  (Driver info: chromedriver=2.33 (undefined),platform=Linux 4.19.42-v7+ armv7l)

I've tried update, copy Instapy from another instance (whitch is working fine), uninstall - nothing works :/

Any help?

**Comment by alexsmedile** [comment]
Same here, but with interact
