### ISSUE TITLE
AttributeError: 'list' object has no attribute 'lower'

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#4784]
I get this error:
Anyone know what's wrong?

"AttributeError: 'list' object has no attribute 'lower'"

Traceback (most recent call last):
  File "/home/x/InstaPy/bellman2.py", line 119, in <module>
    session.interact_user_followers(random_targets, amount=random.randint(10, 20), randomize=True)
  File "/home/x/InstaPy/instapy/instapy.py", line 2940, in interact_user_followers
    validation, details = self.validate_user_call(person)
  File "/home/x/InstaPy/instapy/instapy.py", line 1248, in validate_user_call 
    self.logfolder)
  File "/home/x/InstaPy/instapy/util.py", line 382, in validate_username
    if bio_keyword.lower() in profile_bio.lower():
AttributeError: 'list' object has no attribute 'lower'

**Comment by fgisslen** [comment]
@uluQulu

**Comment by uluQulu** [comment]
Hey @fgisslen 

It is a bug in **util.py**:

![image](https://user-images.githubusercontent.com/33269249/62539248-d702bf80-b865-11e9-9b79-8cf453e3e6be.png)

1. Add a new line:
```python
profile_bio = getUserData("graphql.user.biography", browser)
profile_bio = [pb.lower() for pb in profile_bio]   # ADD THIS NEW LINE
```
2. Change this line:
```python
if bio_keyword.lower() in profile_bio.lower():
```
becomes
```python
if bio_keyword.lower() in profile_bio:
```

Chill 😎

**Comment by fgisslen** [comment]
@uluQulu thx m8

**Comment by fgisslen** [comment]
@uluQulu actually I still get after editing:


Traceback (most recent call last):
  File "x.py", line 119, in <module>
    session.interact_user_followers(random_targets, amount=random.randint(10, 20), randomize=True)
  File "/home/x/InstaPy/instapy/instapy.py", line 2940, in interact_user_followers
    validation, details = self.validate_user_call(person)
  File "/home/x/InstaPy/instapy/instapy.py", line 1248, in validate_user_call
    self.logfolder)
  File "/home/x/InstaPy/instapy/util.py", line 383, in validate_username
    if bio_keyword.lower() in profile_bio:
AttributeError: 'list' object has no attribute 'lower'

**Comment by rudyvanbebu** [comment]
Thanks all for revising this, tested after editing. Exiting script / session with the following traceback log

Traceback (most recent call last):
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\Follow Unfollow Schedule Like Feed Adapted Following CommentersV2.py", line 195, in follow
    interact=True)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\instapy.py", line 3273, in follow_user_followers
    validation, details = self.validate_user_call(person)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\instapy.py", line 1248, in validate_user_call
    self.logfolder)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\util.py", line 383, in validate_username
    if bio_keyword.lower() in profile_bio:
AttributeError: 'list' object has no attribute 'lower'

**Comment by uluQulu** [comment]
@fgisslen 
Revert back previous changes, I just checked, graphql returns a string rather than list.
So, the problem is in user entry,
How do you provide `skip_bio_keyword` value in quickstart script?
Make sure it has only 1 level of list; In other words, it is a list having strings only.

**Comment by fgisslen** [comment]
@uluQulu I don't use skip_bio_keyword

**Comment by uluQulu** [comment]
Can you tell which exact version of InstaPy you are using or attach util.py and instapy.py files.
Also attach your qucikstart script (personal data removed).

**Comment by uluQulu** [comment]
ok ok no need to it,
it is a mechanical bug;

**Comment by fgisslen** [comment]
@uluQulu perfect!
How do we solve it? :)

**Comment by uluQulu** [comment]
![image](https://user-images.githubusercontent.com/33269249/62542780-8ee79b00-b86d-11e9-8bae-4d2777d016d6.png)
It is passed instead of the `dont_skip_business_categories` place which is prob a list of list that makes the issue.

So, move down the formal argument into its correct order.
![image](https://user-images.githubusercontent.com/33269249/62543137-4da3bb00-b86e-11e9-9bfc-05fa5573dd87.png)

Have fun ☕

**Comment by fgisslen** [comment]
@uluQulu thx for the help :) Cheers!

**Comment by rudyvanbebu** [comment]
> @uluQulu thx for the help :) Cheers!

Thanks for your help @uluQulu ! Made the mods and already working on one session. Will keep testing acrross today in case I see something else. Cheers!

**Comment by sannyd** [comment]
thank you so much, @uluQulu !  working awesome now!
