### ISSUE TITLE
Problem with chromedriver (I think)

### ISSUE THREAD

**Issue by sakowicz** [InstaPy/InstaPy#48]
`$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    InstaPy(username='XXX', password='XXX')\
  File "/home/giebeka/InstaPy/instapy/instapy.py", line 34, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/usr/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
`

**Comment by eduardocalazansjr** [comment]
Download the right chromedriver for you OS, put on ./assets folder and fix the permissions (chmod +a, chmod 755)

**Comment by sakowicz** [comment]
I've done that before, same error

**Comment by eduardocalazansjr** [comment]
Well, the `Exec format error` refers to 

- Multiple chromedriver binary / versions on machine
- Chrome and its dependencies not installed

What OS are you running?

**Comment by sakowicz** [comment]
CentOS 7

**Comment by eduardocalazansjr** [comment]
@giebeka i've created on droplet on DO and everything seems ok.
Here's my from-scratch-setup:

```
#General dependencies
yum update
yum -y install unzip yum-utils epel-release git
yum-builddep python
yum -y install python34 python34-devel 
yum -y install Xvfb libXfont Xorg
yum -y groupinstall "X Window System" "Desktop" "Fonts" "General Purpose Desktop"

#Python-pip
curl https://bootstrap.pypa.io/get-pip.py | python

#Chrome-stable
cd ~
wget http://chrome.richardlloyd.org.uk/install_chrome.sh
chmod u+x install_chrome.sh
./install_chrome.sh

#InstaPy
git clone 
wget "http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip"
unzip chromedriver_linux64
mv chromedriver InstaPy/assets/chromedriver
chmod +x InstaPy/assets/chromedriver
chmod 755 InstaPy/assets/chromedriver
pip install .

#got an error there, but fixed running -> yum install python-devel

```

After all this, i've uncommented the display lines on instapy/instapy.py (self.display)
Also check the machine configs, 512MB of ram isn't enough to chrome.

**Comment by sakowicz** [comment]
I've done everything as you but I'm still getting error... I've got 1,7GB Ram
`$ python quickstart.py
Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    InstaPy(username=XXXXXXX', password='XXXXXX')\
  File "/home/giebeka/InstaPy/instapy/instapy.py", line 83, in login
    log_follower_num(self.browser, self.username)
  File "/home/giebeka/InstaPy/instapy/print_log_writer.py", line 10, in log_follower_num
    ('//a[@href="/' + username.lower()  + '/followers/"]')
  File "/usr/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@href="/XXXXXx/followers/"]"}
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 3.10.0-514.6.2.el7.x86_64 x86_64)
`

**Comment by eduardocalazansjr** [comment]
Nice, we've got rid of the chromedriver error.
This last error was fixed on https://github.com/timgrossmann/InstaPy/commit/d30e87e475e7c5e7910a7a0379f8444a837b66a2.

**Comment by sakowicz** [comment]
Thank you!
