### ISSUE TITLE
Message: session not created: Chrome version must be between 71 and 75

### ISSUE THREAD

**Issue by muygd** [InstaPy/InstaPy#4800]
I’m receiving this error:

I’ve latest chrome and latest instapy

`Using built in instapy-chromedriver executable (version 2.46)
ERROR [2019-08-08 13:12:44] [username]  Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 6.3.9600 x86_64)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 163, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 6.3.9600 x86_64)

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 14, in <module>
    multi_logs=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy_chromedriver\chromedriver_win32.exe
>>> `

**Comment by ShauryaUppal-1Mg** [comment]
I am also facing this error

**Comment by mattberg88** [comment]
same here

**Comment by mattberg88** [comment]
Found a solution: download chromedriver from here : https://chromedriver.storage.googleapis.com/index.html?path=76.0.3809.68/
then replace (for mac):
 /usr/local/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_mac64
with the new downloaded and unzipped chromedriver(make sure to change the name to chromedriver_mac64)

**Comment by jecrs687** [comment]
(for linux):   /usr/local/lib/python3.6/dist-packages/instapy_chromedriver/ (make sure to change the name to chromedriver_linux64)

thanks @mattberg88

**Comment by stainless33** [comment]
Thanks, @mattberg88  and @jecrs687 this worked out well.

**Comment by Affenjimbo** [comment]
Awesome, worked also on windows.
\User\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy_chromedriver

**Comment by largalaga** [comment]
Thank you so much. It worked.

**Comment by LouisDuncan** [comment]
Does anyone have this work around for Mac?

**Comment by gpiazzese** [comment]
@mattberg88 solution worked on Mac 10.12.6 (Sierra)
thanks

**Comment by piecioshka** [comment]
In my case, I just installed the missing package and reinstall all deps.

```bash
npm i -D webdriver-manager
rm -rf node_modules
npm install
```

**Comment by EdenTheBoa** [comment]
> ```shell
> rm -rf node_modules
> ```

in what directory?

**Comment by piecioshka** [comment]
@Emberm all commands I ran on project directory.

**Comment by crisperi** [comment]
fixed by downloading the chromedriver again and deleting the old one and renaming the new one as chromedriver_win32
