### ISSUE TITLE
How do I run Dev branch 0.6.0

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#4809]
Hi guys, can someone please help me to run this branch:

https://github.com/timgrossmann/InstaPy/pull/4759
I understand it is trying to go around the blocks issue.
I follow all the instructions in the first post, but keep getting webdriver New Session error as on the image:
![62603654-a6b73180-b8f6-11e9-87f6-42ec8cb99c0e](https://user-images.githubusercontent.com/36073534/62804388-cbc5c300-baf5-11e9-906a-7b28486533ae.jpg)

**Comment by Tachenz** [comment]
Aaanyone?😆

**Comment by Zettt** [comment]
Follow these instructions: https://github.com/timgrossmann/InstaPy/pull/4696
Instead of `git checkout feature/hide-headless` you do `git checkout dev` (I think).

**Comment by Tachenz** [comment]
@zettt thank you! Will try!

**Comment by Tachenz** [comment]
@zettt And after checkout git, i should finish final 2 steps? (Uninstall instapy and install - e.)?
0.5.8 works fine with firefox.
But 0.6.0 (after I finish those instructions you referenced, swapping to the line git checkout dev) gives me a NewSession error at the very beginning, as on the screenshot in the first post..

**Comment by papillon-unix** [comment]
hi everyone
I've troubles running this version too (on raspbian):

`  File "instajoseph.py", line 13, in <module>
    disable_image_load=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/instapy.py", line 318, in __init__
    self.logger,
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`

Can't start instapy anymore :(

I tried to ré-install chromedriver from https://chromedriver.storage.googleapis.com/index.html?path=76.0.3809.68/ but didn't change anything..

**Comment by Zettt** [comment]
Download and install Firefox. 0.6 doesn't use chrome.

**Comment by Tachenz** [comment]
@zettt would you have any advice for my error? I really feel I am missing out here :D

**Comment by Tachenz** [comment]
Or was that branch already merged into master...

**Comment by Zettt** [comment]
@Tachenz It was on Monday or so. You just do a `pip3 install -U instapy`. I have no idea what your error exactly means, but maybe you need to install Firefox. Sorry I can't be of any help.

**Comment by papillon-unix** [comment]
@Zettt Thank you for your answer, but after installing Firefox (following the [how-to](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md) for raspberry), I got the exact same error :
`Workspace in use: "/home/joseph/InstaPy"
Traceback (most recent call last):
  File "Projects/instagram/instajoseph.py", line 13, in <module>
    disable_image_load=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/instapy.py", line 318, in __init__
    self.logger,
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`

I guess I need to tell my script to use firefox instead of chrome, but I couldn't find how in the documentation..
