### ISSUE TITLE
Chrome driver issue

### ISSUE THREAD

**Issue by jeffreylm** [InstaPy/InstaPy#481]
Hello Everyone,

I had a fully working version, then I downloaded a new copy, because I got the impression that there was an update. Placed the nessecary files in the asset directory, and now I receive this error.

Tried to figure it out, but got nowhere.
Could someone help with this issue?

Thank you in advance.

**Error code**

C:\Users\jeffrey\Documents\GitHub\InstaPy>py quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    session = InstaPy(username='login', password='pass')
  File "C:\Users\jeffrey\Documents\GitHub\InstaPy\instapy\instapy.py", line 83, in __init__
    self.set_selenium_local_session()
  File "C:\Users\jeffrey\Documents\GitHub\InstaPy\instapy\instapy.py", line 121, in set_selenium_local_session
    self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line
    desired_capabilities=desired_capabilities)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line
    self.error_handler.check_response(response)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", l
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable

**Comment by jeffreylm** [comment]
@timgrossmann 
Here is what solved the problem.

Simply start chrome. Then when I start the start.bat file is connected. The same problem happend hours later and starting then closing chrome fixed the issue. So somewhere in there there is an issue with chromedriver and Python script.

Also the script onlu unfollows up to 246 people and then ends the session and closes the chrome window. It doesn't crash in anyway, it just neatly ends the session. What was the case with the last restating of the script after it stopped att 155 unfollows this time, is that it could not connect to the chrome driver oncse again.

But starting chrome solved it and now it is unfollowing again. This is the error messasge when the first restart was attempted.

  File "C:\Users\jeffrey\Documents\GitHub\InstaPy\instapy\instapy.py", line 83, in __init__
    self.set_selenium_local_session()
  File "C:\Users\jeffrey\Documents\GitHub\InstaPy\instapy\instapy.py", line 121, in set_selenium_local_session
    self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 188, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by jeffreylm** [comment]
Just updated to the latest version. So for now I believe this issue can be closed. The script is running normal so far for the day.

The issue of 246 unfollows is in another issue post, so I will no longer add anything to here.
