### ISSUE TITLE
don't start

### ISSUE THREAD

**Issue by alexander542** [InstaPy/InstaPy#4813]
## Current Behavior
Whenever I'll run the file the following text is shown on my screen:

Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py 

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/Alexander_Hansmann/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-08-10 18:11:03] [alexander_hansmann]  Using built in instapy-chromedriver executable (version 2.46)
ERROR [2019-08-10 18:12:06] [alexander_hansmann]  Message: unknown error: Devtools port number file contents <57295> were in an unexpected format
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)
Traceback (most recent call last):
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 163, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Devtools port number file contents <57295> were in an unexpected format
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

Traceback (most recent call last):
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 30, in <module>
    headless_browser=False)
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy_chromedriver\chromedriver_win32.exe
>>>

**Comment by gerfra** [comment]
You must have the right version of chromedrivers for your Chrome browser, override this version with one appropriate version from here https://chromedriver.chromium.org/downloads. and rename it to chromedriver_win32.exe.

**Comment by FN17** [comment]
//Same Problem

starting instapy with quickstart ================================ ._. ._. ._. ._. ._. ._. ._. ._. ._. Workspace in use: "C:/Users/Admin/InstaPy" ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. INFO [2019-08-10 22:52:50] [smoothiefoodie24] Using built in instapy-chromedriver executable (version 2.46) DevTools listening on ws://127.0.0.1:50396/devtools/browser/11f1af8c-ce4a-4bf9-8f9f-875404e5c13f [704:4372:0810/225251.916:ERROR:broker_win.cc(137)] Error sending sync broker message: Die Pipe wird gerade geschlossen. (0xE8) ERROR [2019-08-10 22:52:53] [smoothiefoodie24] Message: session not created: Chrome version must be between 71 and 75 (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64) Traceback (most recent call last): File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\browser.py", line 163, in set_selenium_local_session chrome_options=chrome_options) File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__ desired_capabilities=desired_capabilities) File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__ self.start_session(capabilities, browser_profile) File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session response = self.execute(Command.NEW_SESSION, parameters) File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute self.error_handler.check_response(response) File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 71 and 75 (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64) Traceback (most recent call last): File "../quickstart.py", line 16, in <module> headless_browser=False) File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 312, in __init__ self.set_selenium_local_session() File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 362, in set_selenium_local_session raise InstaPyError(err_msg) instapy.exceptions.InstaPyError: ensure chromedriver is installed at C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy_chromedriver\chromedriver_win32.exe Drücken Sie eine beliebige Taste . . .

**Comment by gerfra** [comment]
Same answer, check your google Chrome version, than download the cromedriver for your version and rename it chromedriver_win32.exe

**Comment by FN17** [comment]
Perfect works. I copied chromedriver_win32.exe to the wrong directory. Thanks a lot!

**Comment by alexander542** [comment]
My problem ist that I've tryed to install google chrome like 10 times, but I can't install it. Is it possible to use a other browser or only chrome?

**Comment by gerfra** [comment]
!!! Your log explain to you the problem. You need the exacltly cromedriver version for your Chrome browser, then rename it and copy in the right folder... read the log to find it. Yes you can use Firefox and more read the help.

**Comment by e1x4** [comment]
https://github.com/timgrossmann/InstaPy/issues/4747

**Comment by alexander542** [comment]
> 
> 
> !!! Your log explain to you the problem. You need the exacltly cromedriver version for your Chrome browser, then rename it and copy in the right folder... read the log to find it. Yes you can use Firefox and more read the help.

I've downloaded the chromedriver 76 and it doesn't work. Here is the error:

INFO [2019-08-12 10:57:31] [alexander_hansmann]  Using built in instapy-chromedriver executable (version 2.46)
ERROR [2019-08-12 10:57:45] [alexander_hansmann]  Message: session not created: This version of ChromeDriver only supports Chrome version 76
Traceback (most recent call last):
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 163, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 76

Traceback (most recent call last):
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 30, in <module>
    headless_browser=False)
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at C:\Users\Alexander_Hansmann\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy_chromedriver\chromedriver_win32.exe

**Comment by gerfra** [comment]
Ok, step by step download and install this
Chrome Versione 76.0.3809.100
ChromeDriver 76.0.3809.68
Python37
Then
Copy inside the folder \site-packages\instapy_chromedriver\..... the right version of chromedriver_win32.exe
Finish

**Comment by alexander542** [comment]
> 
> 
> Ok, step by step download and install this
> Chrome Versione 76.0.3809.100
> ChromeDriver 76.0.3809.68
> Python37
> Then
> Copy inside the folder \site-packages\instapy_chromedriver..... the right version of chromedriver_win32.exe
> Finish

Sry for this, know it works :)

**Comment by alexander542** [comment]
> 
> 
> Ok, step by step download and install this
> Chrome Versione 76.0.3809.100
> ChromeDriver 76.0.3809.68
> Python37
> Then
> Copy inside the folder \site-packages\instapy_chromedriver..... the right version of chromedriver_win32.exe
> Finish

Sry for this, now it works :)

**Comment by gerfra** [comment]
alexander542 Ok, nice 4you but close the tread!
