### ISSUE TITLE
updated Instapy 0.6 and firefox issue

### ISSUE THREAD

**Issue by e1x4** [InstaPy/InstaPy#4828]
Today I have updated instapy to 0.6 but I get errors, I'm in windows 10 and I have firefox 68 installed. Here the log:

Workspace in use: "C:/Users.../InstaPy"
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 30, in <module>
    headless_browser=False)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by Tachenz** [comment]
I have a similar error as well

(With dev and after updating main repo to 6.1)
https://user-images.githubusercontent.com/36073534/62804388-cbc5c300-baf5-11e9-906a-7b28486533ae.jpg

**Comment by mattberg88** [comment]
same with mac OSX using chrome

**Comment by cutzenfriend** [comment]
Same issue here Debian 10 Buster... Upgrade from 0.5.5 to 0.6.1

**Comment by dsmh** [comment]
I'm unable to run this version with firefox, I had ben trying with a lot of combinations of geckodriver and firefox  (I was running the bot on a raspberry Pi 3), with no luck. 

**With geckodriver 0.17 I got this error:**
```
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused
```
**geckodriver.log says:**

```
1565625107716	geckodriver	INFO	Listening on 127.0.0.1:45259
1565625109326	geckodriver::marionette	INFO	Starting browser /usr/bin/firefox with args ["-marionette"]
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :0
```
Right now I have been 3 weeks without any option to run the bot, this weekend we decided to drop InstatiPy due to all the mess that is going on. Does anybody knows how to put this to work on a Rapberry Pi 3? or another bot to work with?

**Comment by cayetano25** [comment]
It doesn’t seem to work on the raspberry pi right now, either.

**Comment by leo1in88** [comment]
yes i got the exact error like you

**Comment by e1x4** [comment]
the same with instapy 0.6.1

**Comment by papillon-unix** [comment]
same

**Comment by e1x4** [comment]
try this fix https://github.com/timgrossmann/InstaPy/pull/4856

**Comment by papillon-unix** [comment]
Thanks @e1x4, I did it, but it didn't work

` ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/joseph/InstaPy"
Unable to locate the default Firefox binary path, trying to find it...
Firefox is installed at: /usr/bin/firefox
Firefox version: Mozilla Firefox 49.0

Traceback (most recent call last):
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/browser.py", line 118, in set_selenium_local_session
    options=firefox_options,
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Projects/instagram/instajoseph.py", line 13, in <module>
    disable_image_load=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/instapy.py", line 320, in __init__
    self.logger,
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/browser.py", line 130, in set_selenium_local_session
    options=firefox_options,
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`

Maybe the problem is only on my side, because of this mysterious "Firefox binary path" issue.. Anyone else experiencing the same?

**Comment by Tachenz** [comment]
Can confirm here as well, #4865 does NOT fix the "Unable to find a matching set of capabilities error".

I started getting this error after manually downloading 0.24 gecko driver version into Applocal Pytnon and Instapy folders.

If I delete it from there - script crashes with "Message: newSession error"

**Comment by alexsmedile** [comment]
Same issue. I manually updated to v0.23 and tried `sudo xvfb-run python3 quickstart.py` but still does not work.
