### ISSUE TITLE
TypeError: set_delimit_liking() got an unexpected keyword argument 'max'

### ISSUE THREAD

**Issue by Knecki** [InstaPy/InstaPy#4829]
## Expected Behavior

Just logging in and running.

Its from the quickstart_templates folder -> good_commenting_strategy_and_new_qs_system

## Current Behavior

Traceback (most recent call last):
  File "D:\Instagram Bot\Instapy\instapy-quickstart-master\quickstart_templates\good_commenting_strategy_and_new_qs_system.py", line 76, in <module>
    session.set_delimit_liking(enabled=True, max=100, min=0)
TypeError: set_delimit_liking() got an unexpected keyword argument 'max'

**Comment by converge** [comment]
it was updated: https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#liking-based-on-the-number-of-existing-likes-a-post-has

**Comment by Knecki** [comment]
Ah. Yeah. Thanks.. So I guess there are a few more problems with that script i guess.

**Comment by ShubhamBhatt** [comment]
hi i am getting this issue
Traceback (most recent call last):
  File "C:\Users\Jalebee\Desktop\nepi\instapy-quickstart-master\quickstart_templates\good_commenting_strategy_and_new_qs_system.py", line 89, in <module>
    session.like_by_tags(my_hashtags, amount=60, media=None)
  File "C:\Users\Jalebee\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\instapy.py", line 1939, in like_by_tags
    liked_img,
  File "C:\Users\Jalebee\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\like_util.py", line 726, in like_image
    if quota_supervisor("likes") == "jump":
  File "C:\Users\Jalebee\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\quota_supervisor.py", line 41, in quota_supervisor
    quota_state = controller(job)
  File "C:\Users\Jalebee\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\quota_supervisor.py", line 59, in controller
    supervise, interval, target = inspector(job, peaks)
  File "C:\Users\Jalebee\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\quota_supervisor.py", line 118, in inspector
    if hourly_record >= hourly_peak:
TypeError: '>=' not supported between instances of 'int' and 'tuple'
