### ISSUE TITLE
sleep is not defined - from comment_util.py

### ISSUE THREAD

**Issue by VergelDijamco** [InstaPy/InstaPy#483]
Here is the traceback:

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2017.1\helpers\pydev\pydevd.py", line 1585, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2017.1\helpers\pydev\pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2017.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/houseDIJAMCO/AppData/Local/Programs/Python/Python36/InstagramPIPY.py", line 62, in <module>
    session.like_by_tags(['#websitebuilder', '#remarketing', '#funnel', '#socialmediamarketing', '#optimization'], amount=100)
  File "C:/Users/houseDIJAMCO/AppData/Local/Programs/Python/Python36\instapy\instapy.py", line 487, in like_by_tags
    commented += comment_image(self.browser, comments)
  File "C:/Users/houseDIJAMCO/AppData/Local/Programs/Python/Python36\instapy\comment_util.py", line 32, in comment_image

    sleep(2)

NameError: name 'sleep' is not defined

**Comment by timgrossmann** [comment]
@VergelDijamco Do you have the latest version?
`git pull`
