### ISSUE TITLE
This is my input and output simply with error after fresh install 

### ISSUE THREAD

**Issue by GreatMalboro** [InstaPy/InstaPy#4854]
## Expected Behavior
To simply log in (said this previously but I have different error now.)
## Current Behavior
```
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/Higher Thoughts/InstaPy"
Traceback (most recent call last):
  File "C:\Users\Higher Thoughts\Downloads\InstaPy-master\quickstart.py", line 14, in <module>
    password="Holyorders1"))
  File "C:\Users\Higher Thoughts\Downloads\InstaPy-master\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\Higher Thoughts\Downloads\InstaPy-master\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
OSError: [WinError 740] The requested operation requires elevation
```
## Possible Solution (optional)
Again, wait for update. I cant wait. Im a patient man, I have tested errors for two days on my own now. 
## InstaPy configuration

```
""" Quickstart script for InstaPy usage """

# imports
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace


# set workspace folder at desired location (default is at your home folder)
set_workspace(path=None)

# get an InstaPy session!
session = InstaPy(InstaPy(username="Signs of a broken man", 
        password="Jesus christ"))

with smart_run(session):
    # general settings
    session.set_dont_include(["friend1", "friend2", "friend3"])

    # activity
    session.like_by_tags(["natgeo"], amount=10)
```

Im on windows 64bit and pip3 and just pip works.

**Comment by e1x4** [comment]
> greatmalboro

it's better you don't put your password here

**Comment by gerfra** [comment]
Easy read output! User Account Control error, fix your permission on Windows.

**Comment by Ewwwer** [comment]
@gerfra how? i've the same issue

**Comment by gerfra** [comment]
How what? Your log explain you the answer "OSError: [WinError 740] The requested operation requires elevation" this error come from your windows SO, try to reinstall python with the right permission 4 your user.

**Comment by GreatMalboro** [comment]
So uninstall and reinstall using "run as admin"? Im unsure of what you mean other than that.

**Comment by Josexv1** [comment]
You need to run everything as Super user (Administrator)

**Comment by GreatMalboro** [comment]
Im actually unaware of that process but im gonna look it up and report I have that same issue

**Comment by GreatMalboro** [comment]
Ok put simply how do I fix this error 

```
Workspace in use: "C:/Users/Higher Thoughts/InstaPy"
Traceback (most recent call last):
  File "C:\Users\Higher Thoughts\Desktop\InstaPy-master\quickstart.py", line 24, in <module>
    headless_browser=False)
  File "C:\Users\Higher Thoughts\Desktop\InstaPy-master\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\Higher Thoughts\Desktop\InstaPy-master\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Higher Thoughts\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\Higher Thoughts\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
OSError: [WinError 740] The requested operation requires elevation
```

**Comment by gerfra** [comment]
Ok, write here your detailed configuration, like SO, python version etc... do you have Antivirus or Firewall?  View windows event log, and try to install python in C:\.

**Comment by GreatMalboro** [comment]
Windows 64bit, Chrome 76. firefox 68. Python is install in C: PATH. I have avast.

**Comment by GreatMalboro** [comment]
I did another clean install and then dropped the geckodriver directly into the folder with the quickstart file, I get firefox to open up but now it just closes. SO made some progress but now theres this.

**Comment by tamannsharma** [comment]
File "C:\Users\HP\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)

OSError: [WinError 740] The requested operation requires elevation

plz give steps to resolve this error
