### ISSUE TITLE
set_automated_followed_pool error with a bunch off error messages. 

### ISSUE THREAD

**Issue by Backlonely** [InstaPy/InstaPy#486]
Noob and I need help :0 
Thanks in advance :)

C:\Users\No Password\Desktop\InstagramBot\InstaPy-master>set PYTHONIOENCODING=UTF-8

C:\Users\No Password\Desktop\InstagramBot\InstaPy-master>py quickstart.py
Logged in successfully!
set_automated_followed_pool error
 [Errno 2] No such file or directory: './logs/myinstagramusername_followedPool.csv'
Traceback (most recent call last):
  File "quickstart.py", line 6, in <module>
    session.unfollow_users(amount=10)
  File "C:\Users\No Password\Desktop\InstagramBot\InstaPy-master\instapy\instapy.py", line 530, in unfollow_users
    self.automatedFollowedPool)
  File "C:\Users\No Password\Desktop\InstagramBot\InstaPy-master\instapy\unfollow_util.py", line 34, in unfollow
    allfollowing = browser.find_element_by_xpath("//li[3]/a/span").text
  File "C:\Users\No Password\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\No Password\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Users\No Password\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Users\No Password\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//li[3]/a/span"}
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.15063 x86_64)

**Comment by timgrossmann** [comment]
@Backlonely Please try to provide a `page_delay=X` in the Constructor like so:

```python
InstaPy(username="", password="", ..., page_delay=50)
```

And try to put a higher value here like 50 or 100 to test.
Maybe this problem is due to a slow internet connection.

**Comment by Backlonely** [comment]
@timgrossmann Seems like it has nothing to do with the delay. As soon as I start.bat it opens a cmd and closes it fast... I get 70mbps down and 16mbps up.

**Comment by timgrossmann** [comment]
@Backlonely I'll try and look into if the selector is outdated.

**Comment by Backlonely** [comment]
@timgrossmann Did you ever figure out the problem? 

_Sent from my Samsung SM-G935T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by timgrossmann** [comment]
@Backlonely no, sorry. Haven't figured something out yet

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.

**Comment by djrare** [comment]
Ciekawe
