### ISSUE TITLE
Issue with the firefox addon after update to 0.6.1

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4876]
Issue with the new firefox add-on? 

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "instanow.py", line 37, in <module>
    session = InstaPy(username=insta_username, password=insta_password, multi_logs=True)
  File "C:\Users\*\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\*\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 118, in set_selenium_local_session
    browser.install_addon(create_firefox_extension(), temporary=True)
  File "C:\Users\*\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 267, in install_addon
    return self.execute("INSTALL_ADDON", payload)["value"]
  File "C:\Users\*\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\*\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Expected absolute path: [Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: chrome://marionette/content/addon.js :: install :: line 62"  data: no]

**Comment by ghost** [comment]
Updated to 0.6.2 and still the same :p

**Comment by ianmihura** [comment]
Stumbled upon the same issue. Eventually ended up switching from Firefox to Chrome, tho requires to touch a bit of browser.py and get an older version of the chromedriver selenium downloads for you automatically. An adventure, but in the end it works.
Tell me if you want the file, I think I can attach it here somewhere.

**Comment by lambtron** [comment]
hey @ianmihura i would love to checkout your amended code to browser.py! thank you!

**Comment by ianmihura** [comment]
https://drive.google.com/open?id=16oDMiyN2CBbKQGjDq6qkard-vdjBgjPg

**Comment by alexdelorenzo** [comment]
Running into the same issue with Firefox 70.0b14, Selenium 3.141.0, and InstaPy 0.6.4 on Ubuntu 18.04 LTS.

**Comment by mariavd** [comment]
Bringing this issue back to life. I am running Firefox  68.8.0esr on CentOS with python 3 from Anaconda, Selenium 3.141.0 and InstaPy 0.6.8. 


My error ouptut

```
Traceback (most recent call last):
  File "get-followers.py", line 13, in <module>
    session = InstaPy(username="USR", password="PASS")
  File "MYPATH/InstaPy/instapy/instapy.py", line 322, in __init__
    self.logger,
  File "MYPATH/InstaPy/instapy/browser.py", line 122, in set_selenium_local_session
    browser.install_addon(create_firefox_extension(), temporary=True)
  File "MYPATH/anaconda3/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 267, in install_addon
    return self.execute("INSTALL_ADDON", payload)["value"]
  File "MYPATH/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute 
    self.error_handler.check_response(response)
  File "MYPATH/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Expected absolute path: [Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: chrome://marionette/content/addon.js :: install :: line 70"  data: no]
```

**Comment by ugoborrey** [comment]
Hello everyone,
I have the same error message as mariavd
Some help would be highly appreciated ! 
Thanks in advance

**Comment by HaseebLUMS** [comment]
Hello everyone,
I have also come across the same issue. Please guide.
