### ISSUE TITLE
SyntaxError: invalid syntax on instapy.py

### ISSUE THREAD

**Issue by vx8** [InstaPy/InstaPy#4896]
## Current Behavior
Since I pulled the latest version from github I'm unable to run any script due to this error
`  File "/Users/me/Desktop/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/me/Desktop/InstaPy/instapy/instapy.py", line 104
    username: str = None,
            ^
SyntaxError: invalid syntax`

## Expected Behavior
I'm using instapy without any issues since 2 years. I already tried a clean install with no luck

## InstaPy configuration
Standard on macOS

**Comment by raauniovi** [comment]
Same here :(

**Comment by JeremyGRUMEL** [comment]
Same here on MacOS

**Comment by melnikovic** [comment]
Having same issue on Raspberry Pi

**Comment by vx8** [comment]
Any solutions to this?

**Comment by vx8** [comment]
@raauniovi @JeremyGRUMEL @melnikovic 

**TEMPORARY SOLUTION**

I was able to have the script back to work after performing a 2 months rollback of the master branch.

`git checkout `git rev-list -n 1 --first-parent --before="2019-06-27 00:00" master`

Try it yourself and lemme know

**Comment by raauniovi** [comment]
Worked for me on a Mac
git checkout `git rev-list -n 1 --first-parent --before="2019-06-27 00:00" master`
then I got the error
Message: session not created: Chrome version must be between 71 and 75
which was my original reason for upgrading.
Solved here: https://github.com/timgrossmann/InstaPy/issues/4800

**Comment by carlosacchi** [comment]
same here on brand new instapy installation on ubuntu 18.04 


#/usr/local/lib/python3.6/dist-packages/instapy$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 104
    username: str = None,
------------^^
                  SyntaxError: invalid syntax

**Comment by nocomment-bln** [comment]
I got the same problem after using git pull :( any fixes ?

**Comment by nocomment-bln** [comment]
We got still no solution :(

**Comment by followthemoney1** [comment]
same problem +1

**Comment by sticksX2** [comment]
same problem

**Comment by sticksX2** [comment]
Traceback (most recent call last):
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\quickstart.py", line 15, in <module>
    from instapy import InstaPy
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\instapy.py", line 30, in <module>
    from .clarifai_util import check_image
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\clarifai\rest\__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\clarifai\rest\client.py", line 36, in <module>
    from clarifai.rest.grpc.proto.clarifai.api.endpoint_pb2_grpc import V2Stub
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\clarifai\rest\grpc\proto\clarifai\api\endpoint_pb2_grpc.py", line 2, in <module>
    import grpc
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\grpc\__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
  File "src\python\grpcio\grpc\_cython\cygrpc.pyx", line 27, in init grpc._cython.cygrpc
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\asyncio\__init__.py", line 21, in <module>
    from .base_events import *
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\asyncio\base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^
SyntaxError: invalid syntax
>>>

**Comment by dgttm** [comment]
same issue here - any updates?

**Comment by SatoshiSavior** [comment]
same issue
