### ISSUE TITLE
Problem with geckodriver

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4897]
Hi, I installed instapy as mark in https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md

When I run python3 quickstart.py

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 26, in <module>
    headless_browser=False)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 318, in __init__
    self.logger,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/usr/local/bin/geckodriver'

Thank you for helping me.

**Comment by Mr-HaleYa** [comment]
Raspberry pi isn't currently working with instapy

**Comment by papillon-unix** [comment]
@Mr-HaleYa But how serious is the issue? Do you know if it's going to be abandoned or if there is any hope for us?

**Comment by Mr-HaleYa** [comment]
It looks like they just have some typos in identifying OS types. should be fixed relatively soon. Just hold tight. If I find a fix I will post it here.

**Comment by ghost** [comment]
@Mr-HaleYa Thanks you !

**Comment by riccardovalente** [comment]
See my post here: https://github.com/timgrossmann/InstaPy/issues/4890#issuecomment-522350259.

That error means that your geckodriver is not the ARM version. Remove it from /usr/local/bin and install the correct version as per my post

**Comment by ghost** [comment]
@riccardovalente Now it puts me that

Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 26, in <module>
    headless_browser=False)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 31                                                                                                                                                             8, in __init__
    self.logger,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/browser.py", line 11                                                                                                                                                             4, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/w                                                                                                                                                             ebdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/we                                                                                                                                                             bdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/we                                                                                                                                                             bdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/we                                                                                                                                                             bdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/er                                                                                                                                                             rorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't                                                                                                                                                              kill an exited process

**Comment by Flaunkerton2395** [comment]
#4902

**Comment by mwargan** [comment]
@Niplix looks like the same issue as I have :/ https://github.com/timgrossmann/InstaPy/issues/4890#issuecomment-527268443
