### ISSUE TITLE
Im unaware of how to handle this F.Fox element has no attribute

### ISSUE THREAD

**Issue by GreatMalboro** [InstaPy/InstaPy#4911]
## Expected Behavior
"Of course we wrestling with this right now but I throw my hat in the ring"

## Current Behavior
Logs in, loads up the images I guess, and then runs into an exception err.

```
Traceback (most recent call last):
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\instapy\util.py", line 1061, in get_relationship_counts
    "return window._sharedData.entry_data."
  File "C:\Users\Higher Thoughts\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Higher Thoughts\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Higher Thoughts\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window._sharedData.entry_data.ProfilePage[0].graphql is undefined


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\quickstart.py", line 29, in <module>
    session.like_by_tags(["natgeo"], amount=10)
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\instapy\instapy.py", line 1924, in like_by_tags
    validation, details = self.validate_user_call(user_name)
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\instapy\instapy.py", line 1313, in validate_user_call
    self.logfolder,
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\instapy\util.py", line 207, in validate_username
    browser, username, logger
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\instapy\util.py", line 1069, in get_relationship_counts
    str(read_xpath(get_relationship_counts.__name__, "followers_count"))
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\instapy\util.py", line 1002, in format_number
    formatted_num = number.replace(",", "")
AttributeError: 'FirefoxWebElement' object has no attribute 'replace'
```
## Possible Solution (optional)
I was playing with the unfollow.util.

## InstaPy configuration

""" Quickstart script for InstaPy usage """
```
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'herp'  # <- enter username here
insta_password = 'derp'  # <- enter password here

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                     min_followers=45,
                                    min_following=77)

    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])

    # activity
    session.like_by_tags(["natgeo"], amount=10)
```

**Comment by ghost** [comment]
Did you fix that?

**Comment by GreatMalboro** [comment]
Nah I couldn't figure it out so I'm waiting for an update on instapy.
