### ISSUE TITLE
I pay 50$ if anyone help me

### ISSUE THREAD

**Issue by IyanArce99** [InstaPy/InstaPy#4912]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\instapy-quickstart-master\quickstart.py", line 24, in <module>
    headless_browser=False)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 318, in _init_
    self.logger,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in _init_
    keep_alive=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in _init_
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

I am uisng windos server 2019

**Comment by beatdeddeer** [comment]
Well I can help you fix that bug, but it will lead to the next one... and so on. ATM I think the software is pretty much not working in big parts.

**Comment by IyanArce99** [comment]
I need some bot for Instagram. Do you know anyone else?

**Comment by clementizard** [comment]
Found a workaround in this issue: #4923

Add on browse.py file line 81 your firefox's path.

Default should be:
```
firefox_options.binary = r'C:\Program Files\Mozilla Firefox\firefox.exe'
```
