### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower', and dont_skip_business_categories

### ISSUE THREAD

**Issue by shomanishikawa** [InstaPy/InstaPy#4914]
## Expected Behavior
Able to follow, interact with users. Should use dont_skip_business_categories properly like it was doing in previous versions.
## Current Behavior
Session ends, and I get an AttributeError. Also doesn't seem to be properly filtering/allowing certain business categories. This was workign on previous versions.

I was only able to get this far after using this fix: https://github.com/timgrossmann/InstaPy/issues/4908

Logs:
```
Workspace in use: "/Users/shoma/InstaPy"

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-20 10:20:06] [USERNAME]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-08-20 10:20:06] [USERNAME]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-08-20 10:20:06] [USERNAME]  - Internet Connection Status: ok
INFO [2019-08-20 10:20:06] [USERNAME]  - Current IP is "38.142.253.74" and it's from "United States/US"
INFO [2019-08-20 10:20:06] [USERNAME]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-08-20 10:20:10] [USERNAME]  - Instagram WebSite Status: Currently Up
INFO [2019-08-20 10:20:10] [USERNAME]  - Instagram Response Time: 37.585 ms
INFO [2019-08-20 10:20:10] [USERNAME]  - Instagram Reponse Code: 200
INFO [2019-08-20 10:20:10] [USERNAME]  - Instagram Server Status: ok
INFO [2019-08-20 10:20:10] [USERNAME]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-08-20 10:20:10] [USERNAME]  - window.navigator.webdriver response: False
INFO [2019-08-20 10:20:10] [USERNAME]  - Hide Selenium Extension: ok

................................................................
INFO [2019-08-20 10:20:20] [USERNAME]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-08-20 10:20:20] [USERNAME]  Saving account progress...

______________________________________________________________________________
INFO [2019-08-20 10:20:24] [USERNAME]  Starting to follow user `Followers`..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-08-20 10:20:24] [USERNAME]  User 'uniquelyetsy' [1/6]
['the_modern_crafter', 'angieandauggie', 'kerajinan_tangan01', 'jfancicrafts', 'orangedotsbyselin', 'carolinefilou', 'trender.master', 'lucywortonillustration', 'southernbellajewelry', 'yog_artica', 'begi
nnig_mohomshop', 'karivintageornaments', 'strandkleden', 'forager__thelabel', 'mehrdad.s5211', 'lunarchest', 'handmadebyheidijade', 'alycollabs', 'oiledstone', 'markscreative_room', 'moonstone_creative_de
signs', 'popup_soap', 'ganeshcraftsstore', 'gemstones_valley', 'poshkrystalstore', 'bowsitos.ve', 'farmveucrafts', 'hitomi.embroidery', 'kristensensmith', 'istanbulturkeyjewellery', 'agatestoneworkshop',
'veritycarder', 'jbeachnau1', 'sensualingerie.ua', 'jeff_and_stephs', '204events', 'littlebigcookies', 'customdesignportofolio', 'sublimation6', 'goodna_accessoires', 'indonesian_stone_craftsmen', '_kits$
hycoolstuff', 'gumbosgrotto', 'mundopaula_ccp', 'tasneem.342', 'foreverandadaydream_', 'willowlakevintage', 'labascashop', 'lazzoperu', 'dj_gavs', 'soulfoljewelry', 'fairygardenglow', 'heritageonly', 'the
writesidestudio', 'fabcraft.india', '6546mostafa', 'luxuryblingboutique', 'inspiredjewls', 'rooberryoxford', 'soapandparty', 'theballerinaboutique', 'usalasmanos', 'buffalowraps', 'sanistonlietuva', 'ther
ahallfarmandphoto', 'gandg_creations', 'royalminky', 'twynklaccessories', 'sweetstreetdeals', 'oh.so.pawsh.jewlz.and.gemz', 'roseandivycandles', 'allthelittlefinds_shop', 'meyaamber', 'myyellowhat', 'wood
working__.squadron', 'alexamelidesign']

INFO [2019-08-20 10:20:43] [USERNAME]  Grabbed 76 usernames from 'uniquelyetsy's `Followers` to do following

INFO [2019-08-20 10:20:55] [USERNAME]  Ongoing Follow [4/76]: now following 'jfancicrafts'...
INFO [2019-08-20 10:20:57] [USERNAME]  User: 'jfancicrafts'  |> followers: 98  |> following: 434  |> relationship ratio: 4.42
INFO [2019-08-20 10:20:57] [USERNAME]  'jfancicrafts' has a business account

INFO [2019-08-20 10:20:57] [USERNAME]  Ongoing Follow [5/76]: now following 'orangedotsbyselin'...
INFO [2019-08-20 10:21:02] [USERNAME]  User: 'orangedotsbyselin'  |> followers: 95  |> following: 128  |> relationship ratio: 1.34
INFO [2019-08-20 10:21:02] [USERNAME]  'orangedotsbyselin' has a business account

INFO [2019-08-20 10:21:02] [USERNAME]  Ongoing Follow [6/76]: now following 'carolinefilou'...
INFO [2019-08-20 10:21:04] [USERNAME]  User: 'carolinefilou'  |> followers: 177  |> following: 1403  |> relationship ratio: 7.92

INFO [2019-08-20 10:21:05] [USERNAME]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 2228 users & had 1582 FOLLOWERS
[Session lasted 1.09 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-20 10:21:05] [USERNAME]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "autoRunner.py", line 166, in <module>
    interact=True)
  File "/Users/shoma/code/ig-bot/.venv/lib/python3.7/site-packages/instapy/instapy.py", line 3477, in follow_user_followers
    validation, details = self.validate_user_call(person)
  File "/Users/shoma/code/ig-bot/.venv/lib/python3.7/site-packages/instapy/instapy.py", line 1313, in validate_user_call
    self.logfolder,
  File "/Users/shoma/code/ig-bot/.venv/lib/python3.7/site-packages/instapy/util.py", line 417, in validate_username
    if bio_keyword.lower() in profile_bio.lower():
AttributeError: 'NoneType' object has no attribute 'lower'
pipenv run python autoRunner.py  25.83s user 8.01s system 49% cpu 1:08.76 total
```

Script:
```
"""
This template is written by @Nuzzo235

What does this quickstart script aim to do?
- This script is targeting followers of similar accounts and influencers.
- This is my starting point for a conservative approach: Interact with the
audience of influencers in your niche with the help of 'Target-Lists' and
'randomization'.

NOTES:
- For the ease of use most of the relevant data is retrieved in the upper part.
"""

import random
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'USERNAME'
insta_password = 'PASSWORD'

# restriction data
dont_likes = ['sad', 'rain', 'depression']
ignore_users = []

""" Prevent commenting on and unfollowing your good friends (the images will
still be liked)...
"""
friends = []

""" Prevent posts that contain...
"""
ignore_list = []

# TARGET data
""" Set similar accounts and influencers from your niche to target...
"""
targets = [
   TARGETS HERE
]

""" Skip all business accounts, except from list given...
"""
target_business_categories = [
    'Personal Goods & General Merchandise Stores',
    'Home Services',
    'Home Goods Stores',
    'General Interest',
    'Food & Personal Goods',
    'Business & Utility Services',
    'Creators & Celebrities',
    None,
]

# COMMENT data
comments = [
    u'What an amazing shot! :heart_eyes: What do '
    u'you think of my recent shot?',
    u'What an amazing shot! :heart_eyes: I think '
    u'you might also like mine. :wink:',
    u'Wonderful!! :heart_eyes: Would be awesome if '
    u'you would checkout my photos as well!',
    u'Wonderful!! :heart_eyes: I would be honored '
    u'if you would checkout my images and tell me '
    u'what you think. :wink:',
    u'This is awesome!! :heart_eyes: Any feedback '
    u'for my photos? :wink:',
    u'This is awesome!! :heart_eyes:  maybe you '
    u'like my photos, too? :wink:',
    u'I really like the way you captured this. I '
    u'bet you like my photos, too :wink:',
    u'I really like the way you captured this. If '
    u'you have time, check out my photos, too. I '
    u'bet you will like them. :wink:',
    u'Great capture!! :smiley: Any feedback for my '
    u'recent shot? :wink:',
    u'Great capture!! :smiley: :thumbsup: What do '
    u'you think of my recent photo?'
]

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=False)

# let's go! :>
with smart_run(session):
    # HEY HO LETS GO
    # general settings
    session.set_dont_include(friends)
    session.set_dont_like(dont_likes)
    session.set_ignore_if_contains(ignore_list)
    session.set_ignore_users(ignore_users)
    session.set_simulation(enabled=True)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=-1.0,
                                    delimit_by_numbers=True,
                                    max_followers=100000,
                                    max_following=100000,
                                    min_followers=50,
                                    min_following=50,
                                    min_posts=10)

    session.set_skip_users(skip_private=True,
                           skip_no_profile_pic=True,
                           skip_business=True,
                           dont_skip_business_categories=target_business_categories)

    session.set_user_interact(amount=3, randomize=True, percentage=60,
                              media='Photo')
    session.set_do_like(enabled=True, percentage=60)
    session.set_do_comment(enabled=True, percentage=33)
    session.set_comments(comments, media='Photo')
    session.set_do_follow(enabled=True, percentage=75, times=2)
    session.set_delimit_liking(enabled=True, max_likes=80, min_likes=0)
    session.set_delimit_commenting(enabled=True, max_comments=20, min_comments=0)
    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "comments", "follows", "unfollows", "server_calls"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes_hourly=50,
                                 peak_likes_daily=300,
                                 peak_unfollows_hourly=35,
                                 peak_unfollows_daily=402,
                                 peak_comments_hourly=10,
                                 peak_comments_daily=100,
                                 peak_follows_hourly=20,
                                 peak_follows_daily=150)

    # activities

    # FOLLOW+INTERACTION on TARGETED accounts
    """ Select users form a list of a predefined targets...
    """
    number = random.randint(5, 7)
    random_targets = targets

    if len(targets) <= number:
        random_targets = targets

    else:
        random_targets = random.sample(targets, number)

    """ Interact with the chosen targets...
    """
    session.follow_user_followers(random_targets,
                                  amount=random.randint(60, 90),
                                  randomize=True, sleep_delay=300,
                                  interact=True)

    # UNFOLLOW activity
    """ Unfollow nonfollowers after one day...
    """
    session.unfollow_users(amount=random.randint(75, 100),
                           InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=24 * 60 * 60, sleep_delay=600)

    """ Unfollow all users followed by InstaPy after one week to keep the
    following-level clean...
    """
    session.unfollow_users(amount=random.randint(75, 100),
                           InstapyFollowed=(True, "all"), style="FIFO",
                           unfollow_after=168 * 60 * 60, sleep_delay=600)

    """ Joining Engagement Pods...
    """
    session.join_pods()
```

## InstaPy configuration
v.0.6.1

**Comment by dyrgutt** [comment]
Same here -- it used to work, pretty sure prior 0.5.8 -- but the only way i've been able to get instapy working properly these days is to remove the 'dont_skip_business_categories' (for now)?

**Comment by Simon071986** [comment]
I have the same problem somehow. It seems like when instapy tries to read the bio of a user it is looking for a keyword/list which does not exist.
I get this error message : `File "C:\Users\simon\Documents\InstaPy-master\InstaPy-master\instapy\util.py", line 417, in validate_username
    if bio_keyword.lower() in profile_bio.lower():
AttributeError: 'list' object has no attribute 'lower'`
