### ISSUE TITLE
Problem with geckodriver

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4915]
Hello, here is the error I tried to install various versions of geckodriver but I still have the same error.
I have a Raspberry Pi 3 B.

Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 24, in <module>
    headless_browser=True)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 318, in __init__
    self.logger,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/InstaPy/assets/geckodriver'

**Comment by flxdhc** [comment]
same here on mac

**Comment by micherlinman** [comment]
same

**Comment by mikediachenko** [comment]
@Niplix First of all try ‘headless_browser=False’. Second, what are the attributes of ‘geckodriver’ file? It is executable?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
