### ISSUE TITLE
InstaPy not working after the latest update

### ISSUE THREAD

**Issue by vladdd2703** [InstaPy/InstaPy#4924]
I got this error on the unfollowing script which went perfect until new update.

Can you please help me with this?

Traceback (most recent call last):
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart-un-f.py", line 19, in <module>
    from instapy import InstaPy
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy\__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy\instapy.py", line 81, in <module>
    from .browser import set_selenium_local_session
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy\browser.py", line 7, in <module>
    from webdriverdownloader import GeckoDriverDownloader
ModuleNotFoundError: No module named 'webdriverdownloader'

Have a great day.

**Comment by mikediachenko** [comment]
Did you install FireFox and geckodriver?

**Comment by vladdd2703** [comment]
I have FireFox installed but until now the script was opened with chrome. Do I have to change it to FireFox and install this geckodriver?

Thank you

**Comment by mikediachenko** [comment]
> I have FireFox installed but until now the script was opened with chrome. Do I have to change it to FireFox and install this geckodriver?
> 
> Thank you

Yep.

**Comment by RhaegarTargaryen55** [comment]
can somebody help me out with installing of geckodriver on mac?

**Comment by vladdd2703** [comment]
i have windows and i still do not manage to install it. is there any tutorial? I searched the internet and tried several methods but it did not work. i am aware that i cannot manage to install it because i am a total beginner.

So is there any tutorial?

Have a great day

**Comment by vladdd2703** [comment]
i did everything i found over the internet and i still have the same error.

i give up :(

**Comment by Edhim** [comment]
@vladdd2703 pip3 install webdriverdownloader

**Comment by dwai03** [comment]
you need to install webdriverdownloader do pip install webdriverdownloader and it will fix your issue.

**Comment by RhaegarTargaryen55** [comment]
@dwai03 already did that,

1 - https://www.dropbox.com/s/is8vqe65fm32col/Screenshot%202019-08-24%20at%2021.29.34.png?dl=0
2 - https://www.dropbox.com/s/d0tx7b9ekms6pbd/Screenshot%202019-08-24%20at%2021.32.36.png?dl=0

still getting the same error, nothing has been changed

**Comment by mikediachenko** [comment]
Pip install webdriverdownloader —user

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RhaegarTargaryen55** [comment]
@mikediachenko 

NoOne:~ NoOne$ Pip install webdriverdownloader —user
Invalid requirement: '—user'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/req/constructors.py", line 253, in install_req_from_line
    req = Requirement(req)
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8], e.msg
InvalidRequirement: Parse error at "'\xe2\x80\x94user'": Expected W:(abcd...)

NoOne:~ NoOne$

**Comment by mikediachenko** [comment]
>@mikediachenko  ...

@RhaegarTargaryen55 what shows “python -m pip —version”?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RhaegarTargaryen55** [comment]
@mikediachenko 
NoOne:~ NoOne$ python -m pip —version
ERROR: unknown command "—version"

i'm on mac os

**Comment by vladdd2703** [comment]
> you need to install webdriverdownloader do pip install webdriverdownloader and it will fix your issue.

thank you so much.

now i got this error
Traceback (most recent call last):
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart-un-f.py", line 30, in <module>
    headless_browser=False)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: permission denied

Do you know what can i do now?

Thanks

**Comment by vladdd2703** [comment]
now it works but i got this 

Traceback (most recent call last):
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart-un-f - Copy.py", line 40, in <module>
    peak_server_calls=(None, 4700))
TypeError: set_quota_supervisor() got an unexpected keyword argument 'peak_likes'

i have this in my script but it worked smooth until now

session.set_quota_supervisor(enabled=True, sleep_after=['likes', 'comments_d', 'follows', 'unfollows', 'server_calls_h'], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(None, None),
                               peak_comments=(None, None),
                                peak_follows=(None, None),
                                 peak_unfollows=(38, 410),
                                  peak_server_calls=(None, 4700))

**Comment by RhaegarTargaryen55** [comment]
@mikediachenko any help will be highly appreciated

**Comment by mikediachenko** [comment]
@RhaegarTargaryen55 Message: Permission denied. It may sound ridiculous, but seems you user doesn’t have access to the Selenium folder. Could you, please, check it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RhaegarTargaryen55** [comment]
@mikediachenko I honestly can't figure out how to find this Selenium folder to check it out. Spent the whole day trying to google the location of this folder. Never ever had problems like this with InstaPy, at least i could solve the problem myself.

**Comment by mikediachenko** [comment]
>@mikediachenko I honestly can't figure out how to find this Selenium folder to check it out. Spent the whole day trying to google the location of this folder. Never ever had problems like this with InstaPy, at least i could solve the problem myself.

@RhaegarTargaryen55 maybe it did not install correctly? Could you try to reinstall it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RhaegarTargaryen55** [comment]
@mikediachenko i just reinstalled Selenium and everything from the scratch, updated pip3 using

```
pip -V
pip 19.2.3 from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip (python 3.6)
sudo pip3 install --upgrade pip
Requirement already up-to-date: pip in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (19.2.3)
```

then i did 

`Pip3 install webdriverdownloader --user` ,it says that all requirement already satisfied

then i did

`brew install geckodriver`

it says

`geckodriver 0.24.0 is already installed and up-to-date`



after all this stuff i still get this

```
NoOne:InstaPy-master NoOne$ python3 quickstartfollowundollow2.py
Traceback (most recent call last):
  File "quickstartfollowundollow2.py", line 19, in <module>
    from instapy import InstaPy
  File "/Users/NoOne/Documents/Instabot/InstaPy-master/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/NoOne/Documents/Instabot/InstaPy-master/instapy/instapy.py", line 81, in <module>
    from .browser import set_selenium_local_session
  File "/Users/NoOne/Documents/Instabot/InstaPy-master/instapy/browser.py", line 7, in <module>
    from webdriverdownloader import GeckoDriverDownloader
ModuleNotFoundError: No module named 'webdriverdownloader'
```


any chance that i did something wrong or do not understand something?

**Comment by cooperkernan** [comment]
> > I have FireFox installed but until now the script was opened with chrome. Do I have to change it to FireFox and install this geckodriver?
> > Thank you
> 
> Yep.

Wait.... InstaPy uses Firefox now?!
