### ISSUE TITLE
remorte session not working

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4925]
## Expected Behavior
remote session using selenium
## Current Behavior
Traceback (most recent call last):
  File "code/docker_quickstart.py", line 19, in <module>
    bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub', logger=False)
  File "/code/instapy/instapy.py", line 385, in set_selenium_remote_session
    desired_capabilities=DesiredCapabilities.FIREFOX,
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to create new service: GeckoDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '97652ce40052', ip: '172.19.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.125-linuxkit', java.version: '1.8.0_222'
Driver info: driver.version: unknown
Stacktrace:
    at org.openqa.selenium.grid.session.remote.ServicedSession$Factory.lambda$get$0 (ServicedSession.java:135)
    at org.openqa.selenium.grid.session.remote.ServicedSession$Factory.apply (ServicedSession.java:152)
    at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12 (ActiveSessionFactory.java:180)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$11$1.accept (ReferencePipeline.java:440)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
    at java.util.Spliterators$ArraySpliterator.tryAdvance (Spliterators.java:958)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:499)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:486)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
    at java.util.stream.FindOps$FindOp.evaluateSequential (FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst (ReferencePipeline.java:531)
    at org.openqa.selenium.remote.server.ActiveSessionFactory.apply (ActiveSessionFactory.java:183)
    at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2 (NewSessionPipeline.java:66)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
    at java.util.Collections$2.tryAdvance (Collections.java:4719)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:499)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:486)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
    at java.util.stream.FindOps$FindOp.evaluateSequential (FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst (ReferencePipeline.java:531)
    at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3 (NewSessionPipeline.java:69)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.DistinctOps$1$2.accept (DistinctOps.java:175)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
    at java.util.stream.Streams$StreamBuilderImpl.tryAdvance (Streams.java:405)
    at java.util.stream.Streams$ConcatSpliterator.tryAdvance (Streams.java:728)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:499)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:486)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
    at java.util.stream.FindOps$FindOp.evaluateSequential (FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst (ReferencePipeline.java:531)
    at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession (NewSessionPipeline.java:72)
    at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute (BeginSession.java:65)
    at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0 (WebDriverServlet.java:235)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)

## InstaPy configuration
insta_username = 'instagram'
insta_password = 'password'

bot = InstaPy(username=insta_username, password=insta_password, multi_logs=True, bypass_security_challenge_using='sms', selenium_local_session=False)
bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub', logger=False)
bot.login()
bot.set_simulation(enabled=False)
bot.set_relationship_bounds(enabled=True,
             potency_ratio=None,
              delimit_by_numbers=True,
               max_followers=3000,
                max_following=2000,
                 min_followers=45,
                  min_following=10)

**Comment by kusw3** [comment]
Hi @dandy27 ,

I was having the same issue with the latest update. I assume you are using instapy-docker and some "old" quickstart script.

It turns out it's not needed anymore to `set_selenium_remote_session` on each bot session, that's already taken care of. I haven't checked the details yet. I just left InstaPy instantiation like this:

`bot = InstaPy(username=insta_username, password=insta_password, headless_browser=True)`

Let me know if that did the trick.

**Comment by dandy27** [comment]
> headless_browser=True)

thank you for your reply. yes im using some old file. because for some reason they delete some important stuff like using VNC just as i have it here. using your set up will start my docker but i cant see what is doing. 

but i really need to fix a way to mix the new and old features. my old files work but lately i started to have some problems, like everytime i run it i get an email because it doesnt read cookies no more. 

and this gettting me block most of the time. do you  know  a way of using docker just as you posted here but that you can see what is doing using vnc like in the older versions?

**Comment by ghost** [comment]
> Let me know if that did the trick.

hi @kusw3

thank you for your reply. yes im using some old file. because for some reason they delete some important stuff like using VNC just as i have it here. using your set up will start my docker but i cant see what is doing.

but i really need to fix a way to mix the new and old features. my old files work but lately i started to have some problems, like everytime i run it i get an email because it doesnt read cookies no more.

and this gettting me block most of the time. do you know a way of using docker just as you posted here but that you can see what is doing using vnc like in the older versions?
