### ISSUE TITLE
Chrome or Python Error

### ISSUE THREAD

**Issue by albbertim** [InstaPy/InstaPy#4928]
I am having the error below: 

```
"INFO [2019-08-21 20:13:39] [cienciasmed]  Using built in instapy-chromedriver executable (version 2.46)
ERROR [2019-08-21 20:13:43] [cienciasmed]  Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.5 x86_64)
Traceback (most recent call last):
  File "/Users/alberto/Library/Python/2.7/lib/python/site-packages/instapy/browser.py", line 163, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Users/alberto/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/alberto/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/alberto/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/alberto/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/alberto/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.5 x86_64)

Traceback (most recent call last):
  File "../quickstart.py", line 24, in <module>
    headless_browser=False)
  File "/Users/alberto/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "/Users/alberto/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /Users/alberto/Library/Python/2.7/lib/python/site-packages/instapy_chromedriver/chromedriver_mac64
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed."
```

**Comment by romualdoag** [comment]
same here

**Comment by Shynobee** [comment]
you need to use an older version of chrome v71 or 75 will do the trick a little fix up until chrome 76 works on this app 
https://www.slimjet.com/chrome/google-chrome-old-version.php

**Comment by albbertim** [comment]
I tried installing the v74, but still the same error. I think the problem is in Python v2.7, although I have installed Python v3.0 as well.

**Comment by mikediachenko** [comment]
>I tried installing the v74, but still the same error. I think the problem is in Python v2.7, although I have installed Python v3.0 as well.

@albbertim Seems the issue is exactly with python. In error log it is pointing to python2.7. Seems you were installing instaPY only for python2.7. Try to install it for python30 too. `pip3 install instapy -U —user`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by albbertim** [comment]
> `pip3 install instapy -U —user`

The command doesn't work in my mac. Look what happens:

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> ERROR: Invalid requirement: '\xe2\x80\x94user'
