### ISSUE TITLE
permission denied geckodriver.exe

### ISSUE THREAD

**Issue by riishabhz** [InstaPy/InstaPy#4938]
INFO [2019-08-25 02:54:15] [riishabhz]  Workspace in use: "C:/Users/Rishabh/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    password="akshat140724")
  File "C:\Users\Rishabh\Desktop\InstaPy-master\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\Rishabh\Desktop\InstaPy-master\instapy\browser.py", line 110, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\Rishabh\Desktop\InstaPy-master\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "E:\anaconda\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 196, in download_and_install
    shutil.copy2(src_file, dest_file)
  File "E:\anaconda\lib\shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "E:\anaconda\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Rishabh\\InstaPy\\assets\\geckodriver.exe'

**Comment by colorless1** [comment]
same here when is set  headless_browser=True I receive this:
`Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\q.py", line 24, in <module>
    headless_browser=True)
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 110, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 196, in download_and_install
    shutil.copy2(src_file, dest_file)
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\x\\InstaPy\\assets\\geckodriver.exe'`

**Comment by mikediachenko** [comment]
And? The log file shows you an exact error in exact place.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NooriP** [comment]
I have the same problem. Apparently, there's a need to change the path in browser.py 
I am stuck also in this part and can't seem to find a solution. BTW i am running the dev branch and this error is specific when i try to launch multiple instances, the second one have always this error.

Can anyone with a heart help please ? Thank you

**Comment by riishabhz** [comment]
any update what should i do?

**Comment by henriquedevelops** [comment]
> I have the same problem. Apparently, there's a need to change the path in browser.py
> I am stuck also in this part and can't seem to find a solution. BTW i am running the dev branch and this error is specific when i try to launch multiple instances, the second one have always this error.
> 
> Can anyone with a heart help please ? Thank you

Did you manage to solve it? I'm also trying

**Comment by henriquedevelops** [comment]
> any update what should i do?

Did you manage to solve it? I'm also trying

**Comment by Lori10** [comment]
i got same issue. Did anyone manage to solve it?
