### ISSUE TITLE
dont first run

### ISSUE THREAD

**Issue by andropovleva** [InstaPy/InstaPy#4941]
please help

```
._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/vasil/InstaPy"
Traceback (most recent call last):
  File "C:\Users\vasil\Downloads\instapy-quickstart-master\quickstart.py", line 22, in <module>
    multi_logs=True)
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

```

**Comment by andropovleva** [comment]
downloaded firefox and now:
```
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/vasil/InstaPy"
Traceback (most recent call last):
  File "C:\Users\vasil\Downloads\instapy-quickstart-master\quickstart_templates\simple_but_effective.py", line 18, in <module>
    multi_logs=True)
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 110, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37-32\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 196, in download_and_install
    shutil.copy2(src_file, dest_file)
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\vasil\\InstaPy\\assets\\geckodriver.exe'
```

**Comment by NooriP** [comment]
I have the same problem. Apparently, there's a need to change the path in browser.py
I am stuck also in this part and can't seem to find a solution. BTW i am running the dev branch and this error is specific when i try to launch multiple instances, the second one have always this error.

Can anyone with a heart help please ? Thank you

**Comment by andropovleva** [comment]
I solved a problem.
1. download latest firefox
2. download mozilla/geckodriver https://github.com/Mozilla/geckodriver/releases
3. save geckodriver.exe to instapy-quickstart-master 
and to 
C:\Users\username\AppData\Local\Programs\Python\Python37-32

but now I have problem

`ERROR [2019-08-25 *:*:*] [instaname]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.`

please tell me about this 10 comments, where this my comments should be? My comments on the photo other people? Or 10 my comments on my photo?

**Comment by clementizard** [comment]
@andropovleva Try looking #4935
It didn't solved my issue, but worked for others.

Edit: It worked.

**Comment by andropovleva** [comment]
> @andropovleva Try looking #4935
> It didn't solved my issue, but worked for others.
> 
> Edit: It worked.

Thank you. It worked.

pip install -U git+https://github.com/timgrossmann/InstaPy@dev

**Comment by ihugolopes** [comment]
Resolvi colocando o geckodriver.exe na pasta principal do projeto, ele estava procurando, mas não achava. Isso que causou o erro!

**Comment by Alessandro201** [comment]
> I solved a problem.
> 
> 1. download latest firefox
> 2. download mozilla/geckodriver https://github.com/Mozilla/geckodriver/releases
> 3. save geckodriver.exe to instapy-quickstart-master
>    and to
>    C:\Users\username\AppData\Local\Programs\Python\Python37-32
> 
> but now I have problem
> 
> `ERROR [2019-08-25 *:*:*] [instaname] You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.`
> 
> please tell me about this 10 comments, where this my comments should be? My comments on the photo other people? Or 10 my comments on my photo?

It worked, thank you!

**Comment by aampere** [comment]
@andropovleva what do you mean "save to instapy-quickstart-master?"
How do you do that, where/what is instapy-quickstart-master?
Thanks!
