### ISSUE TITLE
Firefox Crash After 10mn this my error thx for help ;)

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#4942]
Traceback (most recent call last):
  File "C:\Users\VFit-Family\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 1109, in get_relationship_counts
    "return window._sharedData.entry_data."
  File "C:\Users\VFit-Family\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\VFit-Family\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\VFit-Family\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window._sharedData is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VFit-Family\Desktop\instapy-quickstart-master\Mr and Mrs Vfit test.py", line 43, in <module>
    session.like_by_tags(['love','instagood','photooftheday','fashion','beautiful','happy','cute','tbt','like4like','followme'], amount=20, interact=True)
  File "C:\Users\VFit-Family\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 1924, in like_by_tags
    validation, details = self.validate_user_call(user_name)
  File "C:\Users\VFit-Family\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 1313, in validate_user_call
    self.logfolder,
  File "C:\Users\VFit-Family\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 207, in validate_username
    browser, username, logger
  File "C:\Users\VFit-Family\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 1117, in get_relationship_counts
    str(read_xpath(get_relationship_counts.__name__, "following_count"))
  File "C:\Users\VFit-Family\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 1002, in format_number
    formatted_num = number.replace(",", "")
AttributeError: 'FirefoxWebElement' object has no attribute 'replace'

**Comment by gtarik** [comment]
have u fixed this issue and how?
