### ISSUE TITLE
SessionNotCreatedException running quickstart.py

### ISSUE THREAD

**Issue by DenisKot** [InstaPy/InstaPy#4948]
Hi guys,
When I run quickstart.py it throws an error:

> Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session = InstaPy()
  File "G:\Downloads\InstaPy-master\InstaPy-master\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "G:\Downloads\InstaPy-master\InstaPy-master\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by xboborx** [comment]
I've got the same issue. My stack is : Python 3.6, Firefox 68.0.2, InstaPy 0.6.1 

```
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/bobor/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 24, in <module>
    headless_browser=False)
  File "/home/bobor/.local/lib64/python3.6/site-packages/instapy/instapy.py", line 318, in __init__
    self.logger,
  File "/home/bobor/.local/lib64/python3.6/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/bobor/.local/lib64/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/bobor/.local/lib64/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/bobor/.local/lib64/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/bobor/.local/lib64/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/bobor/.local/lib64/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

**Comment by clementizard** [comment]
Found a workaround in this issue: #4923 

Add on browse.py file line 81 your firefox's path.
Default should be:
```
firefox_options.binary = r'C:\Program Files\Mozilla Firefox\firefox.exe'
```

**Comment by DenisKot** [comment]
@clementizard yep, it helped, thanks ;)

**Comment by issamarmas** [comment]
works
