### ISSUE TITLE
launching error

### ISSUE THREAD

**Issue by issamarmas** [InstaPy/InstaPy#4969]
I tried everything .. Can you help please

Python 3.7.4 (tags/v3.7.4:e09359112e, Jul 8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

RESTART: C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py

.. .. .. .. .. .. .. ..
Workspace in use: "C:/Users/M/InstaPy"
Traceback (most recent call last):
File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 30, in 
headless_browser=True)
File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 318, in init
self.logger,
File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
options=firefox_options,
File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in init
keep_alive=True)
File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in init
self.start_session(capabilities, browser_profile)
File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
response = self.execute(Command.NEW_SESSION, parameters)
File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by westworldcj** [comment]
I found that adding this to the browser.py on line 81 fixes that. how ever I dont think instagram is liking instapy right now. mine is just going through the motions 

firefox_options.binary = r'C:\Program Files\Mozilla Firefox\firefox.exe'

**Comment by westworldcj** [comment]
![screenshot_3](https://user-images.githubusercontent.com/38078844/63985432-fd92cf80-ca8c-11e9-989d-6535b5109e84.png)


This is what mines is doing now

**Comment by issamarmas** [comment]
of course because you go crazy.. u need to slow down and put a long delay
time

**Comment by issamarmas** [comment]
i got this now

Python 3.7.4 (tags/v3.7.4:e09359112e, Jul 8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

RESTART: C:\Users\M\Desktop\InstaPy-master (1)\InstaPy-master\quickstart.py
.. .. .. .. .. .. .. .. .. .. ..
No any custom workspace provided.	~using existing..
InstaPy Version: 0.6.2
.. .. .. .. .. .. .. ._.
Workspace in use: "C:/Users/M/InstaPy"
Traceback (most recent call last):
File "C:\Users\M\Desktop\InstaPy-master (1)\InstaPy-master\quickstart.py", line 14, in 
password="password")
File "C:\Users\M\Desktop\InstaPy-master (1)\InstaPy-master\instapy\instapy.py", line 321, in init
self.logger,
File "C:\Users\M\Desktop\InstaPy-master (1)\InstaPy-master\instapy\browser.py", line 76, in set_selenium_local_session
firefox_options.binary = r'C:\Program Files\Mozilla Firefox\firefox.exe'
UnboundLocalError: local variable 'firefox_options' referenced before assignment

**Comment by bvanhou** [comment]
What version of Firefox and Gecko? 

Also this a duplicate ticket. Its hard for the community to help when the tickets aren't consolidated. Please review other tickets before, and potentially adding more context to those tickets.
