### ISSUE TITLE
AttributeError: 'FirefoxWebElement' object has no attribute 'replace'

### ISSUE THREAD

**Issue by GreatMalboro** [InstaPy/InstaPy#4970]
## Expected Behavior
I been trying to follow everybody but this is what I been normally coming up with for errors. I been down for a while now.

## Current Behavior
```
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\quickstart.py 

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/Higher Thoughts/InstaPy"

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-29 19:59:19] [greatmalboro]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-08-29 19:59:19] [greatmalboro]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-08-29 19:59:20] [greatmalboro]  - Internet Connection Status: ok
INFO [2019-08-29 19:59:20] [greatmalboro]  - Current IP is "derpest herpest" and it's from "United States/US"
INFO [2019-08-29 19:59:20] [greatmalboro]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-08-29 19:59:32] [greatmalboro]  - Instagram WebSite Status: Currently Up 
INFO [2019-08-29 19:59:32] [greatmalboro]  - Instagram Response Time: 36.144 ms 
INFO [2019-08-29 19:59:32] [greatmalboro]  - Instagram Reponse Code: 200
INFO [2019-08-29 19:59:32] [greatmalboro]  - Instagram Server Status: ok
INFO [2019-08-29 19:59:33] [greatmalboro]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-08-29 19:59:33] [greatmalboro]  - window.navigator.webdriver response: False
INFO [2019-08-29 19:59:33] [greatmalboro]  - Hide Selenium Extension: ok

..................................................................
INFO [2019-08-29 19:59:48] [greatmalboro]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-08-29 19:59:48] [greatmalboro]  Saving account progress...
WARNING [2019-08-29 19:59:53] [greatmalboro]  Unable to save account progress, skipping data update
INFO [2019-08-29 20:00:09] [greatmalboro]  Tag [1/1]
INFO [2019-08-29 20:00:09] [greatmalboro]  --> b'natgeo'
INFO [2019-08-29 20:00:20] [greatmalboro]  desired amount: 10  |  top posts [disabled]: 9  |  possible posts: 17520439
INFO [2019-08-29 20:00:27] [greatmalboro]  Like# [1/10]
INFO [2019-08-29 20:00:27] [greatmalboro]  https://www.instagram.com/p/B1w1Yr4FK8O/
INFO [2019-08-29 20:00:32] [greatmalboro]  Image from: b'kochphil'
INFO [2019-08-29 20:00:32] [greatmalboro]  Link: b'https://www.instagram.com/p/B1w1Yr4FK8O/'
INFO [2019-08-29 20:00:32] [greatmalboro]  Description: b'" The Edge of Tomorrow " - Wisconsin Horizons by Phil Koch. #landscapephotography #travelwisconsin #naturephotography #discoverwisconsin #discover_hd #earthfocus #nature_lovers #nature #ethereal_moods #hdrphotography #igersmidwest #ig_photooftheday #ig_masterpiece #earthofficial #ig_worldphoto #ig_myshots #fineartamerica #fineartamericaartist #natgeo #naturegram #bestcaptureglobal #destination_earth #ig_photooftheday #ryets #earthday #lovelywisconsin #nationaldestinations'

INFO [2019-08-29 20:00:43] [greatmalboro]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 1.73 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-29 20:00:43] [greatmalboro]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\instapy\util.py", line 1061, in get_relationship_counts
    "return window._sharedData.entry_data."
  File "C:\Users\Higher Thoughts\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Higher Thoughts\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Higher Thoughts\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window._sharedData.entry_data.ProfilePage[0].graphql is undefined


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\quickstart.py", line 29, in <module>
    session.like_by_tags(["natgeo"], amount=10)
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\instapy\instapy.py", line 1924, in like_by_tags
    validation, details = self.validate_user_call(user_name)
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\instapy\instapy.py", line 1313, in validate_user_call
    self.logfolder,
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\instapy\util.py", line 207, in validate_username
    browser, username, logger
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\instapy\util.py", line 1069, in get_relationship_counts
    str(read_xpath(get_relationship_counts.__name__, "followers_count"))
  File "C:\Users\Higher Thoughts\Desktop\folderfor bot\InstaPy-master\instapy\util.py", line 1002, in format_number
    formatted_num = number.replace(",", ",")
AttributeError: 'FirefoxWebElement' object has no attribute 'replace'
```
## Possible Solution (optional)
 Again could wait, but from my understand people have theirs active. 

## InstaPy configuration

```
""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'derp'  # <- enter username here
insta_password = 'Herp'  # <- enter password here

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                     min_followers=45,
                                    min_following=77)

    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])

    # activity
    session.like_by_tags(["natgeo"], amount=10)

```

**Comment by InfraRedApple** [comment]
Same issue here.

**Comment by bvanhou** [comment]
What version of Firefox and Gecko?

**Comment by GreatMalboro** [comment]
Firefox Quantum 68.0.2 (64-bit)

And for the Gecko its the lastest unless it has gone through an update. 

Im also using the new instapy update

**Comment by wildwilly18** [comment]
Yeah I am having this issue also.

**Comment by ghost** [comment]
Same problem here. Tried on both Ubuntu/Windows with the same result. Nothing seems to be working with this problem on board.

**Comment by GreatMalboro** [comment]
I never found a fix or workaround, however I have redownloaded the new Instapy and now im back at "Cannot get if user is private." and im unaware how to fix.
