### ISSUE TITLE
I changed to firefox but it still not working

### ISSUE THREAD

**Issue by issamarmas** [InstaPy/InstaPy#4973]
i did add firefox in line number 81 but no results

Traceback (most recent call last):
File "C:\Users\Administrator\Desktop\InstaPy\quickstart.py", line 13, in 
headless_browser=False)
File "C:\Users\Administrator\Desktop\InstaPy\instapy\instapy.py", line 318, in init
self.logger,
File "C:\Users\Administrator\Desktop\InstaPy\instapy\browser.py", line 114, in set_selenium_local_session
options=firefox_options,
File "C:\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in init
keep_alive=True)
File "C:\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in init
self.start_session(capabilities, browser_profile)
File "C:\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
response = self.execute(Command.NEW_SESSION, parameters)
File "C:\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "C:\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by issamarmas** [comment]
now i got this 

Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\M\Desktop\InstaPy-master (1)\InstaPy-master\quickstart.py 
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
No any custom workspace provided.	~using existing..
InstaPy Version: 0.6.2
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/M/InstaPy"
Traceback (most recent call last):
  File "C:\Users\M\Desktop\InstaPy-master (1)\InstaPy-master\quickstart.py", line 14, in <module>
    password="anaissam")
  File "C:\Users\M\Desktop\InstaPy-master (1)\InstaPy-master\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\M\Desktop\InstaPy-master (1)\InstaPy-master\instapy\browser.py", line 76, in set_selenium_local_session
    firefox_options.binary = r'C:\Program Files\Mozilla Firefox\firefox.exe'
UnboundLocalError: local variable 'firefox_options' referenced before assignment

**Comment by issamarmas** [comment]
i got this now

Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\M\Desktop\InstaPy-master (1)\InstaPy-master\quickstart.py 
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
No any custom workspace provided.	~using existing..
InstaPy Version: 0.6.2
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/M/InstaPy"
Traceback (most recent call last):
  File "C:\Users\M\Desktop\InstaPy-master (1)\InstaPy-master\quickstart.py", line 14, in <module>
    password="password")
  File "C:\Users\M\Desktop\InstaPy-master (1)\InstaPy-master\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\M\Desktop\InstaPy-master (1)\InstaPy-master\instapy\browser.py", line 76, in set_selenium_local_session
    firefox_options.binary = r'C:\Program Files\Mozilla Firefox\firefox.exe'
UnboundLocalError: local variable 'firefox_options' referenced before assignment

**Comment by issamarmas** [comment]
works now
