### ISSUE TITLE
Gecko driver error (up to date) 0.6.3

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#4991]
## Current Behavior
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
No any custom workspace provided.       ~using existing..
InstaPy Version: 0.6.3
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/steven/InstaPy"
Traceback (most recent call last):
  File "InstaPy/myinstagramacc.py", line 13, in <module>
    headless_browser=True)
  File "/home/steven/.local/lib/python3.7/site-packages/instapy/instapy.py", line 321, in __init__
    self.logger,
  File "/home/steven/.local/lib/python3.7/site-packages/instapy/browser.py", line 110, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/home/steven/.local/lib/python3.7/site-packages/instapy/browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "/home/steven/.local/lib/python3.7/site-packages/webdriverdownloader/webdriverdownloader.py", line 165, in download_and_install
    tar.extractall(extract_dir)
  File "/usr/lib/python3.7/tarfile.py", line 2002, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2044, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2114, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2155, in makefile
    with bltn_open(targetpath, "wb") as target:
OSError: [Errno 26] Text file busy: '/home/steven/InstaPy/assets/gecko/v0.24.0/geckodriver-v0.24.0-linux64/geckodriver'
There is a screen on:
## Possible Solution (optional)
go back to the old instapy version?
## InstaPy configuration
The same like usual

**Comment by RashminDungrani** [comment]
Same Problem

**Comment by NooriP** [comment]
Same here

**Comment by ceribbo** [comment]
same here

**Comment by mwargan** [comment]
My error reads:
```
InstaPy Version: 0.6.3
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 10, in job
    session = InstaPy(username='nice', password='try', headless_browser=True, disable_image_load=True)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 321, in __init__
    self.logger,
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

```

But I suspect it's also an issue with the drivers. Does anyone know why Chrome was suddenly dropped? I just got it working the other day :P...

**Comment by Tr1pke** [comment]
I killed the gecko driver and it works again. 
It was running in a background. Search the pid and kill it.

**Comment by beld159** [comment]
I'm having this error as well. @Tr1pke how did you kill the driver?

**Comment by Tr1pke** [comment]
Find the process and kill it (Linux top, Windows I don’t know I haven’t used windows for years), Or the easiest solution is reboot

**Comment by hamzasafdar01** [comment]
> I'm having this error as well. @Tr1pke how did you kill the driver?

ps aux | grep geckodriver ===> to find the running process id
kill <process id>

**Comment by Adviser-ua** [comment]
helps for me just set geckodriver_path to prevent download new driver
`session = InstaPy(username=username, password=password, geckodriver_path="/home/kostya/InstaPy/assets/gecko/v0.26.0/geckodriver-v0.26.0-linux64/geckodriver")`

**Comment by J3store** [comment]
> helps for me just set geckodriver_path to prevent download new driver
> `session = InstaPy(username=username, password=password, geckodriver_path="/home/kostya/InstaPy/assets/gecko/v0.26.0/geckodriver-v0.26.0-linux64/geckodriver")`

@Adviser-ua : does it work?
