### ISSUE TITLE
: The element reference of <article class="FyNDV"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

### ISSUE THREAD

**Issue by superryeti** [InstaPy/InstaPy#5006]
## Expected Behavior
interact_user_followers was supposed to get links from the users.
## Current Behavior

```
  File "instabot.py", line 320, in <module>
    competitors, amount=amount, randomize=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/instapy.py", line 3185, in interact_user_followers
    self.user_interact_media,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/instapy.py", line 2471, in interact_by_users
    media,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/like_util.py", line 490, in get_links_for_username
    links = links + get_links(browser, person, logger, media, main_elem)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/like_util.py", line 829, in get_links
    link_elems = element.find_elements_by_xpath('//a[starts-with(@href, "/p/")]')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/remote/webelement.py", line 381, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/remote/webelement.py", line 685, in find_elements
    {"using": by, "value": value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <article class="FyNDV"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
```
## Possible Solution (optional)
I guess instagram changed something. I tried to update the instapy and even ran with the dev version.

## InstaPy configuration
I am using a luminati proxy and cronjob to run the account(Instappy version 0.6.3) on Mac
```
session.interact_user_followers(
                competitors, amount=amount, randomize=True)
```

LOGS
```
InstaPy Version: 0.6.3
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/alexa/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-04 10:53:31] [_Wildin_talent_scout_]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-09-04 10:53:31] [_Wildin_talent_scout_]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-09-04 10:53:31] [_Wildin_talent_scout_]  - Internet Connection Status: ok
INFO [2019-09-04 10:53:31] [_Wildin_talent_scout_]  - Current IP is "2600:6c44:4b7f:f374:0:c87c:21a8:cf7" and it's from "United States/US"
INFO [2019-09-04 10:53:31] [_Wildin_talent_scout_]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-09-04 10:53:38] [_Wildin_talent_scout_]  - Instagram WebSite Status: Currently Up 
INFO [2019-09-04 10:53:38] [_Wildin_talent_scout_]  - Instagram Response Time: 40.983 ms 
INFO [2019-09-04 10:53:38] [_Wildin_talent_scout_]  - Instagram Reponse Code: 200
INFO [2019-09-04 10:53:38] [_Wildin_talent_scout_]  - Instagram Server Status: ok
INFO [2019-09-04 10:53:38] [_Wildin_talent_scout_]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-09-04 10:53:38] [_Wildin_talent_scout_]  - window.navigator.webdriver response: False
INFO [2019-09-04 10:53:38] [_Wildin_talent_scout_]  - Hide Selenium Extension: ok
...........................................................................
INFO [2019-09-04 10:53:49] [_Wildin_talent_scout_]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-09-04 10:53:49] [_Wildin_talent_scout_]  Saving account progress...
Going after competitors [' revice_denim', ' bikinidolls Indybrandclothing', ' whitefoxswim Abellaeyewear', ' zafulswimwear', ' vitaeapparel', 'puravidabracelets', ' sunbum', ' serengetee hitidehawaii']
INFO [2019-09-04 10:54:03] [_Wildin_talent_scout_]  User ' revice_denim' [1/8]
['chloepoeppel', 'rileyyevans', 'magsamillion__']

INFO [2019-09-04 10:54:12] [_Wildin_talent_scout_]  Grabbed 3 usernames from ' revice_denim's `Followers` to do interaction.
INFO [2019-09-04 10:54:12] [_Wildin_talent_scout_]  User 'chloepoeppel' [1/3]
INFO [2019-09-04 10:54:15] [_Wildin_talent_scout_]  User: 'chloepoeppel'  |> followers: 779  |> following: 495  |> relationship ratio: 1.57
INFO [2019-09-04 10:54:15] [_Wildin_talent_scout_]  chloepoeppel is private account, by default skip

INFO [2019-09-04 10:54:15] [_Wildin_talent_scout_]  User 'rileyyevans' [2/3]
INFO [2019-09-04 10:54:18] [_Wildin_talent_scout_]  User: 'rileyyevans'  |> followers: 1317  |> following: 702  |> relationship ratio: 1.87
INFO [2019-09-04 10:54:18] [_Wildin_talent_scout_]  rileyyevans is private account, by default skip

INFO [2019-09-04 10:54:18] [_Wildin_talent_scout_]  User 'magsamillion__' [3/3]
INFO [2019-09-04 10:54:21] [_Wildin_talent_scout_]  User: 'magsamillion__'  |> followers: 1185  |> following: 922  |> relationship ratio: 1.28
INFO [2019-09-04 10:54:46] [_Wildin_talent_scout_]  Interaction [1/3]  |  Total Interaction: 1
___________________________________________________________________________________
INFO [2019-09-04 10:54:46] [_Wildin_talent_scout_]  Starting to interact by users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-09-04 10:54:46] [_Wildin_talent_scout_]  Username [1/1]
INFO [2019-09-04 10:54:46] [_Wildin_talent_scout_]  --> b'magsamillion__'
INFO [2019-09-04 10:54:46] [_Wildin_talent_scout_]  username actions: following=True commenting=False liking=False story=False
INFO [2019-09-04 10:54:46] [_Wildin_talent_scout_]  Getting magsamillion__ image list...

INFO [2019-09-04 10:54:47] [_Wildin_talent_scout_]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 5 users & had 1 FOLLOWERS
[Session lasted 1.37 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-04 10:54:47] [_Wildin_talent_scout_]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo




Traceback (most recent call last):
  File "instabot.py", line 320, in <module>
    competitors, amount=amount, randomize=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/instapy.py", line 3185, in interact_user_followers
    self.user_interact_media,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/instapy.py", line 2471, in interact_by_users
    media,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/like_util.py", line 490, in get_links_for_username
    links = links + get_links(browser, person, logger, media, main_elem)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/like_util.py", line 829, in get_links
    link_elems = element.find_elements_by_xpath('//a[starts-with(@href, "/p/")]')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/remote/webelement.py", line 381, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/remote/webelement.py", line 685, in find_elements
    {"using": by, "value": value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <article class="FyNDV"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
```

**Comment by CamJW101** [comment]
I get the same error. 

`  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 887, in follow_commenters
    commenters = extract_information(self.browser, username, daysold, max_pic)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\commenters_util.py", line 258, in extract_information
    user_commented_list, pic_date_time = extract_post_info(browser)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\commenters_util.py", line 88, in extract_post_info
    comments = comment_list.find_elements_by_tag_name("li")
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 320, in find_elements_by_tag_name
    return self.find_elements(by=By.TAG_NAME, value=name)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 685, in find_elements
    {"using": by, "value": value})['value']
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <ul class="k59kT"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed`

**Comment by selene-y** [comment]
same here, how to fix

**Comment by alexsmedile** [comment]
Same here

**Comment by alexsmedile** [comment]
Possible fix: #5038

**Comment by bradwalls** [comment]
Has this been looked at?

**Comment by rvoets** [comment]
Same error occurring here.

**Comment by rvoets** [comment]
@brnskn Unfortunately the StaleElementReferenceException still occurs when using your fix in the dev branch.

**Comment by mattlethew** [comment]
I am facing the same issue. Anything new on how to solve it?

**Comment by redBaron23** [comment]
Same here

**Comment by miladbonakdar** [comment]
I got this error too.

**Comment by AyouBaws** [comment]
I got this error, randomly too.

**Comment by MarcoLavoro** [comment]
any news about this error?
