### ISSUE TITLE
RaspberryPi was working just fine until the last update...

### ISSUE THREAD

**Issue by kthyaki** [InstaPy/InstaPy#501]
Hey guys!

Would anyone help me with this issue please?

`Traceback (most recent call last):
  File "/home/pi/Desktop/InstaPy/firefoxExample.py", line 18, in <module>
    InstaPy(username='xxx', password='xxx', use_firefox=True, page_delay=25)\
  File "/home/pi/Desktop/InstaPy/instapy/instapy.py", line 85, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Desktop/InstaPy/instapy/instapy.py", line 101, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error`

**Comment by converge** [comment]
hey @kthyaki , did you manage to get it working ?
