### ISSUE TITLE
KeyError: 'content-length'

### ISSUE THREAD

**Issue by dedisupriadi1612** [InstaPy/InstaPy#5024]
Workspace in use: "C:/Users/ASUS-PC/InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 26, in <module>
    headless_browser=False)
  File "C:\Users\ASUS-PC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\ASUS-PC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 110, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\ASUS-PC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "C:\Users\ASUS-PC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 150, in download_and_install
    filename_with_path = self.download(version, show_progress_bar=True)
  File "C:\Users\ASUS-PC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 124, in download
    expected_size = int(data.headers['Content-Length'])
  File "C:\Users\ASUS-PC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'

**Comment by hondem** [comment]
Got exactly the same issue here. Did you find any workaround?
