### ISSUE TITLE
:: ERROR after 2 minutes

### ISSUE THREAD

**Issue by issamarmas** [InstaPy/InstaPy#5026]
after 2 minutes.. this happen

```
Traceback (most recent call last):
  File "e:/Djanget/InstaPy-dev/InstaPy-dev/quickstart.py", line 65, in <module>
    session.follow_likers(['imourishop'], photos_grab_amount = 50, follow_likers_per_photo = 200, randomize=True, sleep_delay=450, interact=True)
  File "e:\Djanget\InstaPy-dev\InstaPy-dev\instapy\instapy.py", line 1038, in follow_likers
    liker, self.follow_times, sleep_delay, interact
  File "e:\Djanget\InstaPy-dev\InstaPy-dev\instapy\instapy.py", line 1154, in follow_by_list
    validation, details = self.validate_user_call(acc_to_follow)
  File "e:\Djanget\InstaPy-dev\InstaPy-dev\instapy\instapy.py", line 1322, in validate_user_call
    self.logfolder,
  File "e:\Djanget\InstaPy-dev\InstaPy-dev\instapy\util.py", line 207, in validate_username
    browser, username, logger
  File "e:\Djanget\InstaPy-dev\InstaPy-dev\instapy\util.py", line 1057, in get_relationship_counts
    web_address_navigator(browser, user_link)
  File "e:\Djanget\InstaPy-dev\InstaPy-dev\instapy\util.py", line 1183, in web_address_navigator
    browser.get(link)
  File "C:\Users\M\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\M\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\M\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=netTimeout&u=https%3A//www.instagram.com/sofoluppalu/&c=UTF-8&f=regular&d=%D9%8A%D8%B3%D8%AA%D8%BA%D8%B1%D9%82%20%D8%A7%D9%84%D8%AE%D8%A7%D8%AF%D9%88%D9%85%20%D9%81%D9%8A%20www.instagram.com%20%D9%88%D9%82%D8%AA%D9%8B%D8%A7%20%D8%B7%D9%88%D9%8A%D9%84%D9%8B%D8%A7%20%D9%84%D9%8A%D8%B3%D8%AA%D8%AC%D9%8A%D8%A8.
```

**Comment by meinert** [comment]
Related to https://github.com/timgrossmann/InstaPy/issues/4960

**Comment by issamarmas** [comment]
> Related to #4960

yes i have seen it before, there is no solution yet

**Comment by issamarmas** [comment]
hello ?§!!!
