### ISSUE TITLE
TypeError: document.body is null - link_elems error local variable 'post_href' referenced before assignment

### ISSUE THREAD

**Issue by Jostino** [InstaPy/InstaPy#5045]
RaspBi3+
Mozilla 60
GeckoDriver 24

The script ended with an error while it was running:

```
INFO [2019-09-10 11:34:06] [xxx]  Starting to interact by users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-09-10 11:34:06] [xxx]  Username [1/1]
INFO [2019-09-10 11:34:06] [xxx]  --> b'rxxx'
INFO [2019-09-10 11:34:06] [xxx]  username actions: following=False commenting=False liking=True story=False
INFO [2019-09-10 11:34:06] [xxx]  Getting renezanella image list...
ERROR [2019-09-10 11:34:34] [xxx]  link_elems error local variable 'post_href' referenced before assignment

INFO [2019-09-10 11:34:42] [xxx]  Sessional Live Report:
	|> LIKED 74 images  |  ALREADY LIKED: 4
	|> COMMENTED on 0 images
	|> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> LIKED 0 comments
	|> REPLIED to 0 comments
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0
	|> WATCHED 0 story(ies)  |  WATCHED 0 reel(s)


[Session lasted 1.65 hours]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-10 11:34:42] [xxx]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "/root/InstaPy/assets/tbmusic.py", line 43, in <module>
    session.interact_user_followers(['xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx'], amount=10, randomize=True)
  File "/root/.local/lib/python3.7/site-packages/instapy/instapy.py", line 3185, in interact_user_followers
    self.user_interact_media,
  File "/root/.local/lib/python3.7/site-packages/instapy/instapy.py", line 2471, in interact_by_users
    media,
  File "/root/.local/lib/python3.7/site-packages/instapy/like_util.py", line 483, in get_links_for_username
    browser.execute_script("window.scrollTo(0, document.body.scrollHeight);")
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: document.body is null
```

Meanwhile was running other script simultaneily.

**Comment by Jangojack14** [comment]
Same Issue

**Comment by maxiwolleb** [comment]
same

**Comment by kmstross** [comment]
Same

**Comment by MaghnusM** [comment]
Also getting this error :/

**Comment by maury37** [comment]
Also having this issue... Anyone solved it ?

**Comment by BlackLz** [comment]
Has anyone solved it? I'm still stuck with it.

**Comment by RhaegarTargaryen55** [comment]
same

**Comment by melnikovic** [comment]
same
