### ISSUE TITLE
Error: TypeError: window._sharedData is undefined

### ISSUE THREAD

**Issue by juauzynhu** [InstaPy/InstaPy#5049]
Lastest InstaPy, not in headerless mode, running on Win10. After a few interactions, I always receive this error:
```
Traceback (most recent call last):
  File "Python\Python37\lib\site-packages\instapy\like_util.py", line 592, in check_link
    "window.insta_data = window.__additionalData[Object.keys(window.__additionalData)[0]].data"
  File "Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: can't convert undefined to object


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File ".vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File ".vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in main
    run()
  File ".vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Documents\Bot Insta\start.py", line 81, in <module>
    session.like_by_tags(my_hashtags, amount=60, media=None) #use_smart_hashtags=True
  File "AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 1925, in like_by_tags
    self.logger,
  File "AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\like_util.py", line 596, in check_link
    "window.insta_data = window._sharedData.entry_data.PostPage[0]"
  File "AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window._sharedData is undefined
```
Tell me if you need more infos.

**Comment by Jostino** [comment]
Hello,
check this:
https://github.com/timgrossmann/InstaPy/issues/5038

**Comment by juauzynhu** [comment]
Worked like a charm!
