### ISSUE TITLE
Unable to get cookie → crash

### ISSUE THREAD

**Issue by ReagentX** [InstaPy/InstaPy#5055]
```
(venv) pi@rpi:~/Projects/InstaPy $ python quickstart.py

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-11 23:40:08] [redacted]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Issue with cookie for user redacted. Creating new cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20190911-234047.html
**********************************************************************

INFO [2019-09-11 23:40:48] [redacted]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 42.15 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-11 23:40:48] [redacted]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "quickstart.py", line 19, in <module>
    with smart_run(session):
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/pi/Projects/InstaPy/instapy/util.py", line 1599, in smart_run
    session.login()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 360, in login
    self.bypass_with_mobile):
  File "/home/pi/Projects/InstaPy/instapy/login_util.py", line 262, in login_user
    "//button[text()='Log in']")
  File "/home/pi/Projects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/pi/Projects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/pi/Projects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/Projects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[text()='Log in']"}
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)
```

**Comment by ReagentX** [comment]
[20190911-234047.html](https://github.com/timgrossmann/InstaPy/files/3603618/20190911-234047.txt)

**Comment by ReagentX** [comment]
[20190911-234047.txt](https://github.com/timgrossmann/InstaPy/files/3603632/20190911-234047.txt)

**Comment by ReagentX** [comment]
[20190911-234047.txt](https://github.com/timgrossmann/InstaPy/files/3603635/20190911-234047.txt)

**Comment by ReagentX** [comment]
[20190911-234047.txt](https://github.com/timgrossmann/InstaPy/files/3603643/20190911-234047.txt)

**Comment by tommy2049** [comment]
same issue
