### ISSUE TITLE
webdriverdownloader, GeckoDriverDownloader

### ISSUE THREAD

**Issue by RhaegarTargaryen55** [InstaPy/InstaPy#5058]
Can somebody please help me out with this?

```
Traceback (most recent call last):
  File "quickstartfollowundollow2.py", line 19, in <module>
    from instapy import InstaPy
  File "/Users/NoOne/Documents/Instabot/InstaPy-master/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/Users/NoOne/Documents/Instabot/InstaPy-master/instapy/instapy.py", line 82, in <module>
    from .browser import set_selenium_local_session
  File "/Users/NoOne/Documents/Instabot/InstaPy-master/instapy/browser.py", line 7, in <module>
    from webdriverdownloader import GeckoDriverDownloader
ModuleNotFoundError: No module named 'webdriverdownloader'
```

I'm on mac, geckodriver and webdriver are both installed and re-installed again a thousand times, can't figure out the problem. Instapy is updated.

**Comment by amauryleproux** [comment]
Same for me :/ did u find any solution? @RhaegarTargaryen55

**Comment by RhaegarTargaryen55** [comment]
@amauryleproux nope, still can't use the bot

**Comment by RhaegarTargaryen55** [comment]
@amauryleproux please share with me if you find any solution

**Comment by singlerodger** [comment]
Also have same problem. Can't use the bot.
