### ISSUE TITLE
instapy running quickstart.py

### ISSUE THREAD

**Issue by Azard96** [InstaPy/InstaPy#5073]
Every time i run the python
Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    headless_browser=False)
  File "C:\Users\Zdzicheu\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\Zdzicheu\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Zdzicheu\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Zdzicheu\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Zdzicheu\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Zdzicheu\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Zdzicheu\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by ellaprogrammer** [comment]
you might not have firefox installed! if you're on mac, try running: brew cask install firefox, otherwise you can use apt-get install firefox
