### ISSUE TITLE
How can i run more than one process at same time?

### ISSUE THREAD

**Issue by maziiiarkrm** [InstaPy/InstaPy#5076]
I get this error
Traceback (most recent call last):
  File "C:/Users/MaaaaaaaaaXXXXXxxxxx/Desktop/InstaPy-master/123123.py", line 29, in <module>
    disable_image_load=True)
  File "C:\Users\MaaaaaaaaaXXXXXxxxxx\Desktop\InstaPy-master\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\MaaaaaaaaaXXXXXxxxxx\Desktop\InstaPy-master\instapy\browser.py", line 112, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\MaaaaaaaaaXXXXXxxxxx\Desktop\InstaPy-master\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "D:\Projects\Python\InstaPy-master\venv\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 196, in download_and_install
    shutil.copy2(src_file, dest_file)
  File "C:\python\lib\shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\python\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\MaaaaaaaaaXXXXXxxxxx\\InstaPy\\assets\\geckodriver.exe'

and when ever i stop the another process , it will be accepted!
i just can run one process at same time
any help for thi?

**Comment by ExportEh** [comment]
It's not worth it. If I open my app on my phone with Instapy is running I get the Please wait almost instantly on Instapy

**Comment by maziiiarkrm** [comment]
no i mean two different processes on two different pages!

**Comment by Jostino** [comment]
https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#instance-settings

try this

**Comment by Jangojack14** [comment]
Same error here when i want to use multi-session at the same time…

Did you find any solution ?
