### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by Bastochee** [InstaPy/InstaPy#5084]
Hello,

Still impossible to make InstaPy work.
reinstalled it, (v0.6.4) and my new error message is :

Workspace in use: "C:/Users/bastoche/InstaPy"
Traceback (most recent call last):
  File ".\simple_but_effective.py", line 18, in <module>
    multi_logs=True)
  File "C:\Users\bastoche\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\bastoche\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\bastoche\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\bastoche\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\bastoche\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\bastoche\AppData\Laocal\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bastoche\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

I've seen post that refers to firefox on the web. I installed it, but nothing changes.
Anyone can help ?

**Comment by prototype127** [comment]
install firefox and dev branch !

**Comment by Jostino** [comment]
Where are you using instapy?
Windows? MaC? Rasp? ...?

**Comment by Bastochee** [comment]
I'm using it on Windows !
Never got this firefox error before, i thought InstaPy was using
chromedriver !

**Comment by avipars** [comment]
Same issue here, what version of chrome are oyu guys running?

**Comment by denis-gref** [comment]
@avipars @Bastochee 

Solution:

1) Download and install Mozilla Firefox (and try to tun a code again)
2) If the first step did not help you, follow this issue: #4923 - simply add this line to browse.py: firefox_options.binary = r'C:\Program Files\Mozilla Firefox\firefox.exe';

**Comment by Bastochee** [comment]
not working, same error message
