### ISSUE TITLE
<button class=" ffKix sqdOP  L3NKy _4pI4F      " type="button"> UNFOLLOW_UTIL.PY

### ISSUE THREAD

**Issue by ljacobo** [InstaPy/InstaPy#5087]
Having this error after interacting:

Traceback (most recent call last):
    interact=True)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 3529, in follow_user_followers
    person, self.follow_times, sleep_delay, interact
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 1193, in follow_by_list
    self.logfolder,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/unfollow_util.py", line 783, in follow_user
    browser, track, login, user_name, None, logger, logfolder
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/unfollow_util.py", line 211, in get_following_status
    following_status = follow_button.text
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of **<button class=" ffKix sqdOP  L3NKy _4pI4F      " type="button"> i**s stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

On RP1 3
Instapy 0.6.4

Thks

**Comment by papillon-unix** [comment]
same here, with the same config

**Comment by carloskvasir** [comment]
I had same bug now

**Comment by SanielDous** [comment]
Same here, but the exception occurs when after the session was ended

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 976, in click_element
    element.click()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="sqdOP  L3NKy _4pI4F  y3zKF     " type="button"> is stale; 
either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

```
