### ISSUE TITLE
Error: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by jonparro** [InstaPy/InstaPy#5089]
Hi,

I cannot run InstaPy

OS: Windows 10
Browsers: Chrome 77, Firefox 69

## Current Behavior
`starting instapy with quickstart
================================
InstaPy Version: 0.6.4
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Jon/InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 24, in <module>
    headless_browser=False)
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`

**Comment by alexsmedile** [comment]
Same here

**Comment by obabuba** [comment]
same everywhere man...

**Comment by denis-gref** [comment]
Hello @obabuba @alexsmedile @jonparro , 

Solution:
1) Download and install Mozilla Firefox (and try to tun a code again)
2) If the first step did not help you, follow this issue: #4923 - simply add this line to **browse.py**: firefox_options.binary = r'C:\Program Files\Mozilla Firefox\firefox.exe';

**Comment by atulpatildbz** [comment]
Worked around by adding one line in options.py
In my case the file was located at
C:\Users\<username>\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\selenium\webdriver\firefox\options.py

add the following code:
`opts["binary"] = "C:\\Program Files\\Mozilla Firefox\\firefox.exe"`
this line should go above `opts.update(self.log.to_capabilities())`

This is just a workaround and not the permanent fix.

**Comment by chetanudawant** [comment]
Thank, it worked for me. :)
