### ISSUE TITLE
not worked selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by myehrajat** [InstaPy/InstaPy#5092]
Traceback (most recent call last):
  File "quickstart.py", line 26, in <module>
    headless_browser=False)
  File "D:\Python37-32\lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "D:\Python37-32\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "D:\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "D:\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by myehrajat** [comment]
i think it is related to chrome version

**Comment by denis-gref** [comment]
Hello @myehrajat , 

Solution: 
1) Download and install Mozilla Firefox (and try to tun a code again) 
2) If the first step did not help you, follow this issue: #4923
