### ISSUE TITLE
Please help whats the problem here?

### ISSUE THREAD

**Issue by obabuba** [InstaPy/InstaPy#5096]
InstaPy Version: 0.6.4
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/Lior Alter/InstaPy"
Traceback (most recent call last):
  File "C:\Users\Lior Alter\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 30, in <module>
    headless_browser=False)
  File "C:\Users\Lior Alter\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\Lior Alter\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Lior Alter\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Lior Alter\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Lior Alter\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Lior Alter\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Lior Alter\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: **Unable to find a matching set of capabilities**

>>>

**Comment by Tomickck** [comment]
Same problem, please help.

**Comment by obabuba** [comment]
For me, it was pretty simple at the end.
I needed to make sure I have a "path" to Firefox, Chrome, and Instapy. 

Once you do this, the firefox browser will pop up and the problem will be solved (at least it work for me..)
If you did it, and still have a problem, make sure everything is update, including drivers etc'.

Good luck :)

**Comment by timuruktus** [comment]
What exactly did you change in instapy files?

> For me, it was pretty simple at the end.
> I needed to make sure I have a "path" to Firefox, Chrome, and Instapy.
> 
> Once you do this, the firefox browser will pop up and the problem will be solved (at least it work for me..)
> If you did it, and still have a problem, make sure everything is update, including drivers etc'.
> 
> Good luck :)
