### ISSUE TITLE
Anyone on RaspberryPI?

### ISSUE THREAD

**Issue by ljacobo** [InstaPy/InstaPy#5097]
Hi,

Is anyone working "OK" in Raspberry PI?

**Comment by sdalawani** [comment]
Yes, what do you need?

**Comment by ljacobo** [comment]
Hi, which version of instapy are you running?

Im running the 0.6.4 with Firefox ESR and still having errors.

**Comment by riccardovalente** [comment]
You don't say what errors.
I had the best results with Buster and geckodriver 0.23 if that helps. I had problems with both 0.24 and 0.25 so I downgraded that.

**Comment by ljacobo** [comment]
Im using Buster and geckodriver 0.23 and after some minutes interacting i am having this error:

Traceback (most recent call last):
  File "quickstart.py", line 71, in <module>
    interact=True)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 3529, in follow_user_followers
    person, self.follow_times, sleep_delay, interact
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 1226, in follow_by_list
    self.user_interact_media,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 2517, in interact_by_users
    self.logger,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/like_util.py", line 613, in check_link
    user_name,
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window.insta_data is undefined

**Comment by riccardovalente** [comment]
I only do simple follow/unfollow so I haven't experienced this, but this seems to be a common problem (similar to #5093) perhaps? There is no solution that I know of at the moment

**Comment by ljacobo** [comment]
Ok, i will try to only do follow/unfollow and see how it goes.

Thanks.

**Comment by llzewy** [comment]
ljacobo , simply follow / unfollow really working ?

**Comment by papillon-unix** [comment]
Not working anymore for me on Raspberry,
It says that I `might be temporarily blocked from following` whereas I've been very carefull with quotas.
And then I always get this error at the end of the session:

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 946, in click_element
    element.click()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "instajoseph_light.py", line 94, in <module>
    session.follow_user_followers(random.sample(accounts, 2), amount=random.randint(2,5), randomize=True, sleep_delay=1000)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 3529, in follow_user_followers
    person, self.follow_times, sleep_delay, interact
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 1193, in follow_by_list
    self.logfolder,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/unfollow_util.py", line 786, in follow_user
    click_visibly(browser, follow_button)  # click to follow
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 1898, in click_visibly
    click_element(browser, element)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 960, in click_element
    + "')[0].scrollIntoView({ inline: 'center' });"
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 141, in get_attribute
    self, name)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
```

Do you know if there is anything I can do to fix it ?

**Comment by llzewy** [comment]
I think this is not only a Rasberry problem. And no one knows how to solve it ...

**Comment by Piero24** [comment]
Can you help me to fix this error on my raspberry pi?

`Workspace in use: "/home/pi/InstaPy"

INFO [2019-09-22 13:05:42] [USERNAME] Using built in instapy-chromedriver executable (version 2.46)
Traceback (most recent call last):
File "quickstart.py", line 24, in
headless_browser=False)
File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 312, in init
self.set_selenium_local_session()
File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 360, in set_selenium_local_session
self.logger)
File "/home/pi/.local/lib/python3.7/site-packages/instapy/browser.py", line 163, in set_selenium_local_session
chrome_options=chrome_options)
File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in init
self.service.start()
File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
stdin=PIPE)
File "/usr/lib/python3.7/subprocess.py", line 775, in init
restore_signals, start_new_session)
File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/.local/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_linux64`

**Comment by zino1337** [comment]
> Im using Buster and geckodriver 0.23 and after some minutes interacting i am having this error:
> 
> Traceback (most recent call last):
> File "quickstart.py", line 71, in
> interact=True)
> File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 3529, in follow_user_followers
> person, self.follow_times, sleep_delay, interact
> File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 1226, in follow_by_list
> self.user_interact_media,
> File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 2517, in interact_by_users
> self.logger,
> File "/home/pi/.local/lib/python3.7/site-packages/instapy/like_util.py", line 613, in check_link
> user_name,
> File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
> 'args': converted_args})['value']
> File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.JavascriptException: Message: TypeError: window.insta_data is undefined

Same here, PI2 with Buster. Any ideas on this?

**Comment by Jostino** [comment]
>  OSError: [Errno 8] Exec format error: '/home/pi/.local/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_linux64`

Dude:
```
OSError: [Errno 8] Exec format error: '/home/pi/.local/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_linux64`
```

You are running something wrong on the wrong OS.
If you are on Rasp, you have to run the 32bit version.

**Comment by Jostino** [comment]
I'm still trying to figure it out how fix the problem of:
```
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```

I'm on Rasp3B+
Instapy "dev" 0.6.4
FirefoxESR 0.60
Gecko 0.23 (same error with 0.24 and 0.25)

If I put `nogui=True` or `headless=True` it works for a while untile the same error above:
```
selenium.common.exceptions.JavascriptException: Message: TypeError: window.insta_data is undefined
```

**Comment by llzewy** [comment]
Check #5093 , i have same error , but i work on notebook ..
Just start instapy and after 2 min he close and give errors ...
This is my error : 

Traceback (most recent call last):
File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\like_util.py", line 592, in check_link
"window.insta_data = window.__additionalData[Object.keys(window.__additionalData)[0]].data"
File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
'args': converted_args})['value']
File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window.__additionalData[Object.keys(...)[0]] is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\test\Desktop\instapy-quickstart-master\quickstart.py", line 32, in 
session.like_by_tags(["sport"], amount=3)
File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 1925, in like_by_tags
self.logger,
File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\like_util.py", line 596, in check_link
"window.insta_data = window._sharedData.entry_data.PostPage[0]"
File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
'args': converted_args})['value']
File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window._sharedData is undefined
