### ISSUE TITLE
So tried following the video to the T and I keep getting this.

### ISSUE THREAD

**Issue by jasonanddane** [InstaPy/InstaPy#5103]
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
== RESTART: C:\Users\Jason\Desktop\instapy-quickstart-master\quickstart.py ==
InstaPy Version: 0.6.4
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/Jason/InstaPy"
Traceback (most recent call last):
  File "C:\Users\Jason\Desktop\instapy-quickstart-master\quickstart.py", line 24, in <module>
    headless_browser=False)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

>>>

**Comment by Arrinasound** [comment]
Following, as this is my exact issue also...

**Comment by jasonanddane** [comment]
Yeah not sure what's going on. It looks selenium doesn't want to open firefox or chrome for me so not sure what I'm missing :/

**Comment by denis-gref** [comment]
I've got exactly the same issue

**Comment by Arrinasound** [comment]
@denis-gref @jasonanddane - Yeah, it looks like either new versions of selenium is throwing off old code ?? Ufortunately I am unfamiliar selenium and the issue, so I cannot help. Hopefully someone with the correct skill set can assist.

**Comment by moorebrb** [comment]
You need to install Firefox

**Comment by Rhydderch** [comment]
Getting the same error...
