### ISSUE TITLE
Completely unknown error during start (Google doesn't know(

### ISSUE THREAD

**Issue by StanleySM** [InstaPy/InstaPy#5109]
Hi,

I'm getting this error when trying to run Instapy through InstapyGUI. Installation was executed with the InstapyGUI step-by-step tutorial. It's running on Rapberry Pi 3+.

When trying to run in the old way, without GUI, still the same error.

```
Traceback (most recent call last):
  File "bot.py", line 10, in <module>
    from instapy import InstaPy, set_workspace
  File "/home/pi/instapy/env/lib/python3.7/site-packages/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/home/pi/instapy/env/lib/python3.7/site-packages/instapy/instapy.py", line 28, in <module>
    from .clarifai_util import check_image
  File "/home/pi/instapy/env/lib/python3.7/site-packages/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "/home/pi/instapy/env/lib/python3.7/site-packages/clarifai/rest/__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "/home/pi/instapy/env/lib/python3.7/site-packages/clarifai/rest/client.py", line 36, in <module>
    from clarifai.rest.grpc.proto.clarifai.api.endpoint_pb2_grpc import V2Stub
  File "/home/pi/instapy/env/lib/python3.7/site-packages/clarifai/rest/grpc/proto/clarifai/api/endpoint_pb2_grpc.py", line 2, in <module>
    import grpc
  File "/home/pi/instapy/env/lib/python3.7/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: /home/pi/instapy/env/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_exchange_8
```

**Comment by mmuruev** [comment]
Have the same issue. I believe the issue related to a different version of clarifai. Got alert about it on installation.

**Comment by vasilisneo18** [comment]
Any chance you have found a solution to this issue?

**Comment by danwetherald** [comment]
This might have something to do with this issue:

https://github.com/grpc/grpc/issues/20400

`pip3 install 'grpcio==1.23.0' --force-reinstal`

**Comment by tE3m** [comment]
It's a problem with python3.7, on python3.5 this error doesn't exist.
