### ISSUE TITLE
Attribute Error: move_to requires a WebElement

### ISSUE THREAD

**Issue by moorebrb** [InstaPy/InstaPy#5122]
I'm running InstaPy on a droplet. It looks like it's hanging up since it's a first time login and it can't select a specific button to get past a prompt of some kind? I would appreciate any feedback or help pointing me in the right direction. Thanks and Cheers!

Traceback (most recent call last):
  File "quickstart.py", line 26, in <module>
    with smart_run(session):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/instapy/util.py", line 1839, in smart_run
    session.login()
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 412, in login
    self.bypass_security_challenge_using,
  File "/usr/local/lib/python3.6/dist-packages/instapy/login_util.py", line 448, in login_user
    bypass_suspicious_login(browser, logger, logfolder, security_code_to_phone)
  File "/usr/local/lib/python3.6/dist-packages/instapy/login_util.py", line 63, in bypass_suspicious_login
    (ActionChains(browser).move_to_element(option).click().perform())
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/action_chains.py", line 273, in move_to_element
    self.w3c_actions.pointer_action.move_to(to_element)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/actions/pointer_actions.py", line 42, in move_to
    raise AttributeError("move_to requires a WebElement")
AttributeError: move_to requires a WebElement

**Comment by moorebrb** [comment]
So I see my problem is this:

Unable to choose (EMAIL) option to bypass the challenge

**Comment by Konstantin555** [comment]
> 
> 
> So I see my problem is this:
> 
> Unable to choose (EMAIL) option to bypass the challenge

Any success in fixing the issue?
