### ISSUE TITLE
[Help] Error Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5139]
**Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\Mia\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\TakipEtUnfollowEt.py 
InstaPy Version: 0.6.4
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/Mia/InstaPy"
Traceback (most recent call last):
  File "C:\Users\Mia\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\TakipEtUnfollowEt.py", line 32, in <module>
    headless_browser=True)
  File "C:\Users\Mia\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\Mia\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Mia\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Mia\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Mia\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Mia\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Mia\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities**

I'm not someone who understands this. I watched the installation video via Youtube. I did the same. I get this error when i run the script.

**Comment by ghost** [comment]
I fix that and now i have different error  

Error
Please wait a few minutes before you try again.

I don't have any problems on my phone, different browser, firefox browser. This problem only occurs when i run the program/script. And i don't think it's a soft ban. Because i only got this error after following 10-15 people with delay. Without like/comment also i don't use suspicious attractive instagram tags.

**Comment by cprkrn** [comment]
I don't follow, could you include more information?

**Comment by smlick** [comment]
Up. Same issue also for me

**Comment by mikestan** [comment]
You guys got banned from your IP. You won't see it on your phone for some reason (prob some key in the app) yet you should see it in a browser. To test, tether your PC to your phone's data plan (shut off wifi on phone to only connect via cell data) and hit your account (should work) then go back to your wifi on your PC (should have error again, immediately)...

How do you fix? Try changing your password from your phone's app - this should reset the IP ban.
