### ISSUE TITLE
What's happening, keeps crashing?

### ISSUE THREAD

**Issue by CentyMade** [InstaPy/InstaPy#5160]
Traceback (most recent call last):
  File "main.py", line 8, in <module>    headless_browser=False)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.7/site-packages/instapy/instapy.py", line 321, in __init__    self.logger,  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.7/site-packages/instapy/browser.py", line 110, in se
t_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()  File "/home/runner/.local/share/virtualenvs/python3/lib/p
ython3.7/site-packages/instapy/browser.py", line 36, in get
_geckodriver    bin_path, sym_path = gdd.download_and_install()
  File "/home/runner/.local/share/virtualenvs/python3/lib/p
ython3.7/site-packages/webdriverdownloader/webdriverdownloader.py", line 186, in download_and_install
    os.symlink(symlink_src, symlink_target)
FileExistsError: [Errno 17] File exists: '/home/runner/InstaPy/assets/gecko/v0.26.0/geckodriver-v0.26.0-linux64/geckod
river' -> '/home/runner/InstaPy/assets/geckodriver'

**Comment by mikediachenko** [comment]
Does geckodriver got an executable attribute?

**Comment by CentyMade** [comment]
> Does geckodriver got an executable attribute?

I'm not sure.  I'm just using an online IDE.  I've installed the package and executed the code to get this error.
