### ISSUE TITLE
The element reference of <textarea class="Ypffh"> is stale

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#5161]
@uluQulu Hi m8, I get this error. Any clues?

Traceback (most recent call last):
  File "quickstart.py", line 87, in <module>
    session.interact_user_followers(random_targets, amount=random.randint(3, 7), randomize=True)
  File "/Users/x/Documents/projekt/InstaPy/instapy/instapy.py", line 3194, in interact_user_followers
    self.user_interact_media,
  File "/Users/x/Documents/projekt/InstaPy/instapy/instapy.py", line 2599, in interact_by_users
    self.logfolder,
  File "/Users/x/Documents/projekt/InstaPy/instapy/comment_util.py", line 92, in comment_image
    .send_keys(comment_to_be_sent)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <textarea class="Ypffh"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

**Comment by RemiHATTINGUAIS** [comment]
Same here:

INFO [2019-10-20 14:08:54] [remicuisine]  Getting lottieje image list...
ERROR [2019-10-20 14:09:20] [remicuisine]  link_elems error Message: The element reference of <article class="FyNDV"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

**Comment by carmenhchung-zz** [comment]
+1 - I just started getting this today (on the latest release).

**Comment by rabbittx** [comment]
same error here !

**Comment by theRouter** [comment]
same problem on windows

**Comment by Phillip-Thomas** [comment]
Hi guys, I was struggling with this for a couple days before I finally thought to actually search for the missing element on instagram via dev tools. Turns out, <textarea class="Ypffh"> refers to the div where you type to leave comments. With this info, I could deduce that commenting is the only issue and have just shut that task off temporarily while others or myself figure out how to work around. Since commenting out set_do_comment and set_comment from my .py I am running smoothly. Hope this helps a little

**Comment by carlobono** [comment]
I must say avoiding comments does not solve the issue.

I no not have set_do_comment / set_comment in my script, yet I get the same exception.

I currently have only set_do_follow, set_do_like and set_user_interact enabled.

For me it happens when it calls follow_user_followers:

`    session.follow_user_followers(random_users, amount=6, randomize=True, interact=True)
  File "/home/pi/InstaPy/dev/InstaPy/instapy/instapy.py", line 3527, in follow_user_followers
    person, self.follow_times, sleep_delay, interact
  File "/home/pi/InstaPy/dev/InstaPy/instapy/instapy.py", line 1191, in follow_by_list
    self.logfolder,
  File "/home/pi/InstaPy/dev/InstaPy/instapy/unfollow_util.py", line 614, in follow_user
    click_visibly(browser, follow_button)  # click to follow
  File "/home/pi/InstaPy/dev/InstaPy/instapy/util.py", line 1897, in click_visibly
    if element.is_displayed():
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 488, in is_displayed
    self)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class=" ffKix sqdOP  L3NKy _4pI4F  y3zKF     " type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
`

**Comment by shubhamtunwal97** [comment]
Still getting this issue

**Comment by alialtintass** [comment]
Still no solution?:(

**Comment by Sonal778** [comment]
BUMP
