### ISSUE TITLE
Stale Element Reference 

### ISSUE THREAD

**Issue by gitpatrickhub** [InstaPy/InstaPy#5177]
## Expected Behavior
Session completes successfully

## Current Behavior
 Session fails after a few interactions with below error:
```
 File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
```

## InstaPy configuration

Raspberry Pi 3
Buster
Python 3
Firefox ESR 60.9.0
InstaPy 6.5

**Comment by theRouter** [comment]
same problem on windows server 2008 ,Firefox . 
any solution ?

**Comment by gitpatrickhub** [comment]
I'm running in headless mode, so I'm not 100% on this interaction, but below is what I observe when I run the interaction manually.

Navigate to User, click on Followers, click on user in the user-list modal, user loads successfully, click on post, like post, click 'X', click Back, click on the next user in the user-list modal, user's story loads in a modal and then plays, upon completing story the modal closes and the user-list modal is displayed. 

This could be the source of the issue since, the bot is expecting to find the user's posts to click, but the option does not exist due to the story playing. Again, I am running headless so it is very difficult for me to confirm. Below is full error:

```
Traceback (most recent call last):
  File "/home/pi/QS/quickstart.py", line 37, in <module>
    session.interact_user_followers(['IG_USER_ACCT'], amount=75, randomize=False)
  File "/usr/local/lib/python3.7/dist-packages/instapy/instapy.py", line 3192, in interact_user_followers
    self.user_interact_media,
  File "/usr/local/lib/python3.7/dist-packages/instapy/instapy.py", line 2469, in interact_by_users
    media,
  File "/usr/local/lib/python3.7/dist-packages/instapy/like_util.py", line 457, in get_links_for_username
    browser, "profile", username, person, None, logger, logfolder
  File "/usr/local/lib/python3.7/dist-packages/instapy/unfollow_util.py", line 212, in get_following_status
    following_status = follow_button.text
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
```

**Comment by gitpatrickhub** [comment]
During today's run the first account that was encountered did not have any posts and the bot crashed with the error posted in this ticket. I can't be certain that this is the root cause, because as I posted earlier the user had an active story running. 2nd run today, the bot crashed on a user with an active story.

Perhaps a check is needed for existing posts and whether a story is running?

Anyone have any ideas? Would appreciate any help or guidance.

**Comment by mattlethew** [comment]
Facing the same issue...anyone could help?
