### ISSUE TITLE
Completely Lost!! Help

### ISSUE THREAD

**Issue by amoffitt123** [InstaPy/InstaPy#519]
Hello all, I am trying to run quickstart.py on my raspberry pi 3 and I just keep on getting errors. Here is my code - 

from instapy import InstaPy

# Write your automation here
# Stuck ? Look at the github page or the examples in the examples folder

dont_like = ['food', 'girl', 'hot']
ignore_words = ['pizza']
friend_list = ['friend1', 'friend2', 'friend3']

# If you want to enter your Instagram Credentials directly just enter
# username=<your-username-here> and password=<your-password> into InstaPy
# e.g like so InstaPy(username="instagram", password="test1234")

InstaPy(username='test', password='test') \
    .login() \
    .set_upper_follower_count(limit=2500) \
    .set_do_comment(True, percentage=10) \
    .set_comments(['Cool!', 'Awesome!', 'Nice!']) \
    .set_dont_include(friend_list) \
    .set_dont_like(dont_like) \
    .set_ignore_if_contains(ignore_words) \
    .like_by_tags(['dog', '#cat'], amount=100) \
    .end()

And these are the errors -

>>> 
Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/quickstart.py", line 23, in <module>
    .end()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 93, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 132, in set_selenium_local_session
    self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/common/service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
>>> 

I have tried looking in the read me file, but no help. Thanks

**Comment by amoffitt123** [comment]
Nevermind guys, GOT IT!!!

**Comment by timgrossmann** [comment]
@amoffitt123 Feel free to post a quick description on how you solved it to help others having the same problem 😉

**Comment by kthyaki** [comment]
@amoffitt123 would you help me with that please? I am having the same issue here. How did you do? #501 

``Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/firefoxExample.py", line 18, in <module>
    InstaPy(username='xxx', password='xxx', use_firefox=True, page_delay=25)\
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 93, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 109, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error``

**Comment by mjortberg521** [comment]
@amoffitt123 I got the same error as you, what steps did you take to fix it?

**Comment by converge** [comment]
@mjortberg521 did you installed chrome browser (not chrome driver) ?

**Comment by mjortberg521** [comment]
@converge I will try installing google Chrome tonight. Does it require ExaGear desktop? I was trying with Chromium...whoops

**Comment by converge** [comment]
@mjortberg521 is it Linux ? check the docs folder, we have a tutorial.
