### ISSUE TITLE
Instapy not working

### ISSUE THREAD

**Issue by mikemancode** [InstaPy/InstaPy#5233]
## Expected Behavior
Instapy to work
## Current Behavior
Instapy not working
## Possible Solution (optional)
InstaPy Version: 0.6.6

InstaPy Version: 0.6.6
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/Dario/InstaPy"
Traceback (most recent call last):
  File "C:\Users\Dario\Desktop\bot.py", line 13, in <module>
    headless_browser=True)
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 319, in __init__
    self.logger,
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Dario\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

>>>

**Comment by erondon11** [comment]
Just ran into the same after a few months without using InstaPy. This seems to be tied to a new requirement to use Firefox. Try downloading it and run your bot.py file again - that did the trick for me. Good luck!

**Comment by sniperpirate** [comment]
ive got the same error

**Comment by mikemancode** [comment]
Thanks erondon11, reinstalling Mozilla worked for me. But now after follow i get the message:
Last follow is not verified! '' " might be temporarily blocked from following

Do you guys have the same thing?
