### ISSUE TITLE
Nothing's working..

### ISSUE THREAD

**Issue by krutarthpatil** [InstaPy/InstaPy#5237]
## Expected Behavior
To run actions: Interact with other users' followers
                           And all the Interact actions.
## Current Behavior
            Showing Error :
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f6383ff55c0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 50, in <module>
    session.interact_user_followers(['natgeo'], amount=10, randomize=True)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 3115, in interact_user_followers
    self.logfolder,
  File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 975, in get_given_user_followers
    web_address_navigator(browser, user_link)
  File "/usr/local/lib/python3.6/dist-packages/instapy/util.py", line 1164, in web_address_navigator
    current_url = get_current_url(browser)
  File "/usr/local/lib/python3.6/dist-packages/instapy/util.py", line 1720, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.6/dist-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49541): Max retries exceeded with url: /session/c29b97a7-cd5d-4fcb-8999-d79d0541fe3c/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6383ff55c0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by addiman** [comment]
same error here

**Comment by krutarthpatil** [comment]
> same error here

I fixed it. It's just due to intend problem.

**Comment by ghost** [comment]
> > same error here
> 
> I fixed it. It's just due to intend problem.

how did you fixed this? help me please

**Comment by krutarthpatil** [comment]
> > > same error here
> > 
> > 
> > I fixed it. It's just due to intend problem.
> 
> how did you fixed this? help me please
Just check the indent properly. That's problem due to indent.

**Comment by ghost** [comment]
> > > > same error here
> > > 
> > > 
> > > I fixed it. It's just due to intend problem.
> > 
> > 
> > how did you fixed this? help me please
> > Just check the indent properly. That's problem due to indent.

what do you mean? how please

**Comment by ghost** [comment]
hey are you here ??? @krutarthpatil

**Comment by krutarthpatil** [comment]
> hey are you here ??? @krutarthpatil

InstaPy doesn't work now bro
