### ISSUE TITLE
Download and Install Issue

### ISSUE THREAD

**Issue by Karahan00** [InstaPy/InstaPy#5244]
## Current Behavior
If I'm starting the installation in the quickstart folder (so the Automatic way) the terminal log shows me the Warning with ("Python2.7") etc. Why ? I know that Instapy needs Python 3 and I had already installed it. But the Automatic installation always not working.

I also get always this Error if I try to run:

Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.6 x86_64)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/instapy/browser.py", line 163, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.6 x86_64)

Traceback (most recent call last):
  File "../quickstart.py", line 24, in <module>
    headless_browser=False)
  File "/usr/local/lib/python2.7/site-packages/instapy/instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "/usr/local/lib/python2.7/site-packages/instapy/instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /usr/local/lib/python2.7/site-packages/instapy_chromedriver/chromedriver_mac64

**Comment by cyberpz** [comment]
Are you on Mac or Linux?
I don't recognize macOS paths. The quickstart is not for installing this library. 
Use `pip install instapy instapy_chromedriver` to install, than try to run the quickstart again.
