### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by samedmonds** [InstaPy/InstaPy#5247]
Hi all, 

Experiencing a problem when trying to run the quickstart file from within the Python IDLE on Raspberry Pi. Have updated and upgraded OS. 

Python 2.7.13 & Python 3.5.3 installed. 

Instapy version 0.6.6

Getting the following error: 
OSError: [Errno 8] Exec format error

**Comment by cyberpz** [comment]
Give us more information, post the full traceback,
I assume that you followed the instruction of the RasPi guide.

**Comment by samedmonds** [comment]
You've assumed correctly. I have had this working from my Pi before. It has just been some time since it's last run (approx a few months). And hence probably needs some heavy maintenance. 

Here is the full error readout: 

Traceback (most recent call last):
  File "/home/pi/InstaPy/quickstartnew.py", line 34, in <module>
    headless_browser=False)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
>>>

**Comment by StellarStoic** [comment]
I'm also stucked with the same "OSError: [Errno 8] Exec format error" on RaspberryPi 3 B+. Tried all known solution without success.

```
i@pi:~/InstaPy $ python3 quickstart.py
InstaPy Version: 0.6.6
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 70, in <module>
    headless_browser=True)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
```
