### ISSUE TITLE
instapy not start

### ISSUE THREAD

**Issue by serhatavcu** [InstaPy/InstaPy#5254]
how fix this eror
Traceback (most recent call last):
  File "C:\Users\Serhat\Desktop\instapy-quickstart-master\quickstart.py", line 24, in <module>
    headless_browser=False)
  File "C:\Users\Serhat\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 319, in __init__
    self.logger,
  File "C:\Users\Serhat\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Serhat\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Serhat\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Serhat\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Serhat\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Serhat\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by orhanavan** [comment]
same

**Comment by khansaad1275** [comment]
i have the same issue
