### ISSUE TITLE
instapy does not start

### ISSUE THREAD

**Issue by zsvendo** [InstaPy/InstaPy#5265]
@uluQulu helpme ? i don't use firefox.

-----------------------------------------------------
Custom workspace set: "C:/InstaPy" :]
InstaPy Version: 0.6.6
 ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/InstaPy"
Traceback (most recent call last):
  File "1.py", line 14, in <module>
    session = InstaPy(username=insta_username,
  File "C:\InstaPy\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\InstaPy\instapy\browser.py", line 111, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\Avell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Avell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Avell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Avell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Avell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by uluQulu** [comment]
Hi @zsvendo 
I am not using InstaPy for some time but last time I checked, Firefox was the only web browser to go since Chrome support was removed due to issues with it leaking selenium usage (not verified though but strongly true) which is why I think if you want to use other browser else than Firefox then be ready to do lots of hand-made modifications meanwhile you could easily start to use Firefox which is also cool even if not being my fav web browser anymore after finding out that it gives direct access to the hard/solid drives rather than running in sandbox like Google Chrome. I use MS Edge though, but Chrome is irreplaceable for inspecting webpages and watching YouTube 🎉

If that solved your issue, let me know.

Have a good time 🎶
---
