### ISSUE TITLE
Mozilla Firefox Extension error

### ISSUE THREAD

**Issue by afrijayaps** [InstaPy/InstaPy#5266]
> Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license()" for more information.
> >>> 
> ============== RESTART: D:\InstaPy-2020\instanusantara_creative.py =============
>  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
> No any custom workspace provided.	~using existing..
> InstaPy Version: 0.6.6
>  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
> Workspace in use: "C:/Users/Administrator/InstaPy"
> Traceback (most recent call last):
>   File "D:\InstaPy-2020\instanusantara_creative.py", line 14, in <module>
>     session = InstaPy(username="instanusantara.creative",password="**",headless_browser=True,disable_image_load=False,multi_logs=True)
>   File "D:\InstaPy-2020\instapy\instapy.py", line 309, in __init__
>     self.browser, err_msg = set_selenium_local_session(
>   File "D:\InstaPy-2020\instapy\browser.py", line 118, in set_selenium_local_session
>     browser.install_addon(create_firefox_extension(), temporary=True)
>   File "D:\InstaPy-2020\instapy\browser.py", line 46, in create_firefox_extension
>     with zipfile.ZipFile(zip_file, "w", zipfile.ZIP_DEFLATED, False) as zipf:
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1249, in __init__
>     self.fp = io.open(file, filemode)
> OSError: [Errno 22] Invalid argument: 'C:\\Users\\Administrator\\InstaPy\\assets\\extension.xpi'

Whyyyy??

**Comment by afrijayaps** [comment]
To fix it end task all firefox on processes
