### ISSUE TITLE
Anyone using or can install instapy on osx or windows?

### ISSUE THREAD

**Issue by sadaweb** [InstaPy/InstaPy#5277]
Anyone using or can install instapy on osx or windows? i try on a clean windows 10 and after run the py file it got me errors , the osx version give me errors during installation process

is it only working at linux right now or what is the situation?

## Current Behavior
Traceback (most recent call last):
  File "M:\games\INSTA_BOT\quickstart.py", line 24, in <module>
    headless_browser=False)
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 319, in __init__
    self.logger,
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by Ghordrin** [comment]
Not providing any of the errors isn't helping at all. I got it to run on windows 10. Not running Linux or whatever.

I do however noticed some errors that weren't documented.

 For example you need to downgrade your protobuf (comes with instapy) from 3.6.1 > 3.6.0 that solved one error for me. As I had the 
`ImportError: DLL load failed` error when trying to launch the bot.

Then I had to manually download Geckodriver and put in the correct environment for it to recognize Firefox.

EDIT: This is with using pyCharm IDE.

**Comment by sadaweb** [comment]
> Not providing any of the errors isn't helping at all. I got it to run on windows 10. Not running Linux or whatever.
> 
> I do however noticed some errors that weren't documented.
> 
> For example you need to downgrade your protobuf (comes with instapy) from 3.6.1 > 3.6.0 that solved one error for me. As I had the
> `ImportError: DLL load failed` error when trying to launch the bot.
> 
> Then I had to manually download Geckodriver and put in the correct environment for it to recognize Firefox.
> 
> EDIT: This is with using pyCharm IDE.

Traceback (most recent call last):
  File "M:\games\INSTA_BOT\quickstart.py", line 24, in <module>
    headless_browser=False)
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 319, in __init__
    self.logger,
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SadaI9\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

this is on windows 10 , completly new reinstall.


i can upload the osx log at the evening but it has problems at installation level and i did it with sudo admin so i dont get it why it has problems.

**Comment by Ghordrin** [comment]
Are you sure you have your geckodriver.exe in your scripts folder? Are you using pycharm? Or just CMD?

**Comment by AnwarAhmedPSU** [comment]
So is anyone still running InstaPy off of Mac? @Yannick-Driessens ??

**Comment by moabe-br-2019** [comment]
Error, unable to determine correct filename for Nonebit win
Traceback (most recent call last):
  File "C:\Users\moabe\AppData\Local\Programs\Python\Python37\Lib\site-packages\quickstart.py", line 30, in <module>
    headless_browser=False)
  File "C:\Users\moabe\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\instapy.py", line 319, in __init__
    self.logger,
  File "C:\Users\moabe\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\browser.py", line 110, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\moabe\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "C:\Users\moabe\AppData\Local\Programs\Python\Python37\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 177, in download_and_install
    show_progress_bar=show_progress_bar)
  File "C:\Users\moabe\AppData\Local\Programs\Python\Python37\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "C:\Users\moabe\AppData\Local\Programs\Python\Python37\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for Nonebit win

**Comment by streetloves** [comment]
i have this error: 

goto instapy.io and take off!
received message: {"handler":"status"}
received message: {"handler":"start","namespace":"gary","setting":"configuracion-basica"}
instapy process started
received message: {"handler":"status"}
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Custom workspace set: "C:/WINDOWS/system32/assets/InstaPy" :]
InstaPy Version: 0.6.7
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/WINDOWS/system32/assets/InstaPy"
Error, unable to determine correct filename for Nonebit win
Traceback (most recent call last):
  File "bot.py", line 125, in <module>
    session = InstaPy(**instapy_args)
  File "C:\WINDOWS\system32\env\lib\site-packages\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\WINDOWS\system32\env\lib\site-packages\instapy\browser.py", line 110, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\WINDOWS\system32\env\lib\site-packages\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "C:\WINDOWS\system32\env\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "C:\WINDOWS\system32\env\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "C:\WINDOWS\system32\env\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for Nonebit win
