### ISSUE TITLE
Error starting Instapy

### ISSUE THREAD

**Issue by classsandiso** [InstaPy/InstaPy#5286]
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: C:\Program Files (x86)\Python38-32\Lib\site-packages\instapy\quickstart.py
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\Lib\site-packages\instapy\quickstart.py", line 19, in <module>
    from instapy import InstaPy
  File "C:\Program Files (x86)\Python38-32\Lib\site-packages\instapy\instapy.py", line 20, in <module>
    from . import __version__
ImportError: attempted relative import with no known parent package
>>>

**Comment by cyberpz** [comment]
Did you tried `python3 -m pip install -U --user instapy` ?
