### ISSUE TITLE
Chrome pops up but it won't load Instagram on MAC

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5292]
```
Traceback (most recent call last):
  File "../quickstart.py", line 14, in <module>
    headless_browser=False)
  File "/Library/Python/2.7/site-packages/instapy/instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "/Library/Python/2.7/site-packages/instapy/instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /Library/Python/2.7/site-packages/instapy_chromedriver/chromedriver_mac64
```

**Comment by marky-mark-88** [comment]
This issue has been closed. If you take a older chrome driver it works for me :)

**Comment by ghost** [comment]
takin an older chrome driver solve the problem
