### ISSUE TITLE
Nonebit win error

### ISSUE THREAD

**Issue by jagus00** [InstaPy/InstaPy#5301]
##  Current Behavior

I have installed Python 3,8 on Windows 10, pip, instaPy, I put correct insta_username and insta_password in quickstart.py. After running file, error appears: 

Error, unable to determine correct filename for Nonebit win
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\qucikstart.py", line 28, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\browser.py", line 110, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for Nonebit win

**Comment by leonidessaguisagjr** [comment]
Hello @jagus00 I made a fix to the webdriverdownloader module that should address the issue.  Thanks arshiyasolei for bringing the issue to my attention.

**Comment by jagus00** [comment]
Hello, I have updated webdriverdownloader and the same issue appears

**Comment by jagus00** [comment]
Error, unable to determine correct filename for Nonebit win
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\qucikstart.py", line 28, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\browser.py", line 110, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for Nonebit win
>>>

**Comment by leonidessaguisagjr** [comment]
@jagus00 Can you verify what version of the WebDriverDownloader library you are on?

**Comment by gvmturl** [comment]
Same error here... how solve that?

**Comment by KR4mP** [comment]
have you solved that issue?

**Comment by jagus00** [comment]
Hi, I didn't solve the problem and I didn't have time to work on in, but
gonna return to it next weekn.
