### ISSUE TITLE
geckodriver issues on raspberrypi

### ISSUE THREAD

**Issue by potentowl** [InstaPy/InstaPy#5343]
```
Workspace in use: "/root/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    headless_browser="True")
  File "/home/pi/InstaPy-master/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/home/pi/InstaPy-master/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/bin/geckodriver unexpectedly exited. Status code was: -11

```

**Comment by JerBear90** [comment]
> ```
> Workspace in use: "/root/InstaPy"
> Traceback (most recent call last):
>   File "quickstart.py", line 15, in <module>
>     headless_browser="True")
>   File "/home/pi/InstaPy-master/instapy/instapy.py", line 319, in __init__
>     self.logger,
>   File "/home/pi/InstaPy-master/instapy/browser.py", line 114, in set_selenium_local_session
>     options=firefox_options,
>   File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
>     self.service.start()
>   File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 98, in start
>     self.assert_process_still_running()
>   File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
>     % (self.path, return_code)
> selenium.common.exceptions.WebDriverException: Message: Service /usr/local/bin/geckodriver unexpectedly exited. Status code was: -11
> ```
@loopypanda 
Where you able to find a solution to this problem?

**Comment by federicozanini** [comment]
i have the same error. let me know if you find a solution!

**Comment by KatzeMau** [comment]
@potentowl Did you fixed it ??????
Can you share the solution ?
