### ISSUE TITLE
Error Starting new Quickstart.py file

### ISSUE THREAD

**Issue by wstokes88** [InstaPy/InstaPy#5355]
I'm running this on a windows machine for the time being and whenever I try to run the windows batch file for my quickstart.py file I get this error:

starting instapy with quickstart
================================
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/wstok/InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 17, in <module>
    multi_logs=True)
  File "C:\Users\wstok\Anaconda3\lib\site-packages\instapy\instapy.py", line 319, in __init__
    self.logger,
  File "C:\Users\wstok\Anaconda3\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\wstok\Anaconda3\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\wstok\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\wstok\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\wstok\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\wstok\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Press any key to continue . . .

**Comment by shafaypro** [comment]
https://github.com/timgrossmann/InstaPy/issues/5337#issuecomment-612905783
