### ISSUE TITLE
Doesnt Work with Raspberry Pi

### ISSUE THREAD

**Issue by Humanoidx** [InstaPy/InstaPy#5356]
## Expected Behavior
It works

## Current Behavior
It doesnt work at all

## InstaPy configuration
Following InstaPy instructions on a raspberry pi.

**Comment by stefanbschneider** [comment]
Same here, I spent several days following the guide here and then trying to fix following errors and bugs, but couldn't get it to work on RPi. Works fine on Windwos and Ubuntu, but not on Pi.

**Comment by orhan-drsn** [comment]
Which Raspberry Pi are you using?

**Comment by Humanoidx** [comment]
Tried it on raspberry pi 3, 3b+, and 4

**Comment by stefanbschneider** [comment]
RPi 3 with the latest Raspbian

**Comment by Tolmino** [comment]
Can you paste here what do you see in your terminal?

**Comment by Humanoidx** [comment]
Ok so a couple issues:When following the installation guide…. There are errors during install:THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.    grpcio>=1.16.1 from https://www.piwheels.org/simple/grpcio/grpcio-1.28.1-cp37-cp37m-linux_armv7l.whl#sha256=412a486f22257d975f06992d0888a3f9cfa85f2943d9f33177b660c6b3e435e6 (from instapy):        Expected sha256 412a486f22257d975f06992d0888a3f9cfa85f2943d9f33177b660c6b3e435e6             Got        0bb8c5ad73008b2fd851a98d4e3463388d87adb344c5bbc31908845cb56fedfa I ran the installer a couple times before all the errors went away.Then when it talks about editing the quickstart file….. there is no quick start file to edit.In addition, there is no InstaPy folder that was ever downloaded to the user or root folders with templates or readmes or whatever.When I create my own quickstart file it runs with the following error.pi@raspberrypi:~ $ python3 Test.pyInstaPy Version: 0.6.8 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. Workspace in use: "/home/pi/InstaPy"Traceback (most recent call last):  File "Test.py", line 24, in <module>    headless_browser=False)  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 319, in __init__    self.logger,  File "/home/pi/.local/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session    options=firefox_options,  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__    keep_alive=True)  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__    self.start_session(capabilities, browser_profile)  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session    response = self.execute(Command.NEW_SESSION, parameters)  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute    self.error_handler.check_response(response)  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response    raise exception_class(message, screen, stacktrace)selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities   Sent from Mail for Windows 10 From: stale[bot]Sent: Friday, April 24, 2020 9:14 PMTo: timgrossmann/InstaPyCc: Humanoidx; AuthorSubject: Re: [timgrossmann/InstaPy] Doesnt Work with Raspberry Pi (#5356) This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.If this problem still occurs, please open a new issue—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Tolmino** [comment]
do you know that you have written in a way that is very hard to understand ??
