### ISSUE TITLE
Windows Error

### ISSUE THREAD

**Issue by balledictorian** [InstaPy/InstaPy#5365]
starting instapy with quickstart
================================
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Nate/InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 24, in <module>
    headless_browser=False)
  File "C:\Users\Nate\Apps\lib\site-packages\instapy\instapy.py", line 319, in __init__
    self.logger,
  File "C:\Users\Nate\Apps\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Nate\Apps\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Nate\Apps\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Nate\Apps\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Nate\Apps\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Nate\Apps\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
 my quickstart.py is:

# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'balledictorian'
insta_password = '*************'

comments = ['Nice shot! @{}',
        'Sickkkkkk! @{}',
        'That was insane :thumbsup:',
        'Just incredible :open_mouth:',
        'HOW??? @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Teach me your ways @{}',
        ':raised_hands: Sick!',
        'That was intense @{} :muscle:']

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
  """ Activity flow """
  # general settings
  session.set_dont_include(["friend1", "friend2", "friend3"])

  # activity
  session.like_by_tags(["fortnite", "battleroyale", "apexlegends", "apex", "gaming", "cod"], amount=10)

  # Joining Engagement Pods
  session.set_do_comment(enabled=True, percentage=35)
  session.set_comments(comments)
  session.join_pods(topic='sports', engagement_mode='no_comments')

**Comment by shafaypro** [comment]
https://github.com/timgrossmann/InstaPy/issues/5337#issuecomment-612905783
