### ISSUE TITLE
problem with follow_user_followers

### ISSUE THREAD

**Issue by fadedreams** [InstaPy/InstaPy#5370]
hi
I started to use follow_user_followers and it seems it  doesn't work anymore
here is my sample code

```
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)
				  
with smart_run(session):
    """ Activity flow """

session.follow_user_followers(['someprofile'], amount=100,
                                  randomize=True, interact=False)	

```
and here is the result

```
Logged in successfully!
Saving account progress...
 Starting to follow user `Followers`..
User 'someprofile' [1/1]
**here it waits a long time and then stops** 
  Sessional Live Report:
No any statistics to show

```

**Comment by mcost45** [comment]
Getting the same:

Traceback (most recent call last):
  File "quickstart.py", line 110, in <module>
    session.follow_user_followers(random_targets,
  File "InstaPy\instapy\instapy.py", line 3454, in follow_user_followers
    person_list, simulated_list = get_given_user_followers(
  File "InstaPy\instapy\unfollow_util.py", line 1013, in get_given_user_followers
    person_list, simulated_list = get_users_through_dialog_with_graphql(
  File "InstaPy\instapy\unfollow_util.py", line 767, in get_users_through_dialog_with_graphql
    browser.get("view-source:{}".format(url))
  File "Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Timeout loading page after 300000ms

**Comment by Twice22** [comment]
I also get the same

**Comment by mcost45** [comment]
Found this on the Discord server:

NEW ISSUE FIXED AND CONFIRMED

Issue is directly related to the newest Mozilla Firefox update 74.0

File "C:\Users\mccune\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Timeout loading page after 300000ms

**Steps to fix:
Downgrade to 73.0.1.**
