### ISSUE TITLE
NOT ABLE TO LOGIN: TypeError: login_user() takes exactly 8 arguments (6 given)

### ISSUE THREAD

**Issue by jinayG** [InstaPy/InstaPy#5383]
## Current Behavior
Traceback (most recent call last):
  File "../quickstart.py", line 86, in <module>
    with smart_run(session):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/jinaygala/Library/Python/2.7/lib/python/site-packages/instapy/util.py", line 1691, in smart_run
    session.login()
  File "/Users/jinaygala/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 414, in login
    self.bypass_with_mobile):
TypeError: login_user() takes exactly 8 arguments (6 given)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

## InstaPy configuration
I am using MACOS.
Chromedriver 72

**Comment by jinayG** [comment]
Is there anything I can change here? @timgrossmann @ishandutta2007
