### ISSUE TITLE
It closes after a while working

### ISSUE THREAD

**Issue by henriquedevelops** [InstaPy/InstaPy#5386]
My Instapy starts working fine, then I leave it running and, after a while, I see that both the browser and the script window are closed... There is no error message, it simply stops and closes the 2 windows, like the session was finished.

Can someone please help me?

Thanks.

Edit:
I was able to find out what the error message was:

"is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed"

It occurs when commenting. I was able to temporarily fix it by removing the comment action, but I wish I could add it again.

Still waiting for help.

Using windows 10

**Comment by billyjones123** [comment]
Anyone?

**Comment by billyjones123** [comment]
I was able to find out what the error message was:

"is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed"

It occurs when commenting. I was able to temporarily fix it by removing the comment action, but I wish I could add it again.

Still waiting for help.

**Comment by Parazok** [comment]
I faced this issue with the headless browser being on
and when I turned that off the problem just vanished

**Comment by henriquedevelops** [comment]
This one I was not able to solve yet. I tried both with headless browser on and off.

**Comment by KonstantinGreat** [comment]
same thing i suppose , instapy stops without errors and not reaching the end
(by the way, is it possible to do not check pages already followed?)
//session with headless_browser=True or False
last sign
**Follow# [106/500]**

```
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
Sessional Live Report:
	|> No any statistics to show
...
[Session lasted 48.68 minutes]
INFO [2020-05-07 17:11:50] [konstantingreat]  Session ended!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/util.py", line 946, in click_element
    element.click()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="oW_lN sqdOP yWX7d    y3zKF     A086a" type="button"> is not clickable at point (223,67) because another element <div class="bY2yH"> obscures it


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/util.py", line 946, in click_element
    element.click()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="oW_lN sqdOP yWX7d    y3zKF     A086a" type="button"> is not clickable at point (223,9) because another element <div class="b5itu "> obscures it


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/util.py", line 946, in click_element
    element.click()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="oW_lN sqdOP yWX7d    y3zKF     A086a" type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/util.py", line 946, in click_element
    element.click()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="oW_lN sqdOP yWX7d    y3zKF     A086a" type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/Downloads/instapy-quickstart-master/quickstart.py", line 40, in <module>
    session.follow_by_locations(['218322188198641'], amount=500)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/instapy.py", line 4569, in follow_by_locations
    follow_state, msg = follow_user(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/unfollow_util.py", line 610, in follow_user
    follow_state, msg = verify_action(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/unfollow_util.py", line 1555, in verify_action
    click_visibly(browser, follow_button)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/util.py", line 1898, in click_visibly
    click_element(browser, element)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/util.py", line 996, in click_element
    click_element(browser, element, tryNum)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/util.py", line 996, in click_element
    click_element(browser, element, tryNum)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/util.py", line 996, in click_element
    click_element(browser, element, tryNum)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/util.py", line 978, in click_element
    + element.get_attribute("class")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 139, in get_attribute
    attributeValue = self.parent.execute_script(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="oW_lN sqdOP yWX7d    y3zKF     A086a" type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

```
