### ISSUE TITLE
TypeError: 'NoneType' object is not callable - error on pip install .

### ISSUE THREAD

**Issue by kiknaio** [InstaPy/InstaPy#54]
I have tried both ways of installation packages but every single time I am getting the same error.
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 357, in _handle_tasks
    debug('task handler got sentinel')
TypeError: 'NoneType' object is not callable
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 330, in _handle_workers
    debug('worker handler exiting')
TypeError: 'NoneType' object is not callable


error: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
```

**Comment by timgrossmann** [comment]
@kiknag Local or server?
If server, which system?
Did you follow the how-to?
Did you install all dependencies?

**Comment by timgrossmann** [comment]
Try installing the dependencies manually:

clarifai
selenium
pyvirtualdisplay

Instead of using the setup.py

**Comment by kiknaio** [comment]
Locally on OSX.
I have solved it. I have just created virtualenv then installed those packages you told me and after it started working, thanks 👍
