### ISSUE TITLE
[SOLVED] Permission denied: 'geckodriver.log'

### ISSUE THREAD

**Issue by iskorini** [InstaPy/InstaPy#5402]
## Expected Behavior
Hi, I've a Raspberry PI and I followed [this instruction](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md). Everything it's working fine, but I would like to run Instapy with supervisor, so I use this configuration file:
```
[program:ig_bot_CS]
command=python3 /home/pi/bot_insta/CS.py 
autostart = true
autorestart = true
user = pi
stdout_logfile = /var/log/IGBOT/CS.out
stderr_logfile = /var/log/IGBOT/CS.err
```
but returns this exception. Any idea?
## Current Behavior
```
Traceback (most recent call last):
  File "/home/pi/bot_insta/CS.py", line 77, in job
    password='PSWD', headless_browser=True)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 163, in __init__
    log_path=service_log_path)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/service.py", line 44, in __init__
    log_file = open(log_path, "a+") if log_path is not None and log_path != "" else None
PermissionError: [Errno 13] Permission denied: 'geckodriver.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/bot_insta/CS.py", line 105, in <module>
    main()
  File "/home/pi/bot_insta/CS.py", line 94, in main
    job()
  File "/home/pi/bot_insta/CS.py", line 91, in job
    session.end()
UnboundLocalError: local variable 'session' referenced before assignment
Traceback (most recent call last):

```
## Possible Solution (optional)
Change configuration file of supervisor with the directory of the python script. 

## InstaPy configuration
- Raspberry PI 3B
- Raspbian 10 (armv7l Linux 4.19.93-v7+)
- Python 3.7.3
- InstaPy 0.6.8

**Comment by henriquedevelops** [comment]
Where can I find the configuration file of supervisor?
