### ISSUE TITLE
won't start on Windows

### ISSUE THREAD

**Issue by chrishsr** [InstaPy/InstaPy#5406]
I get these error messages everytime when i start the quickstart via the batch file.
it doesnt matter what template i choose from the templates folder to sart ist, i didnt change them from the original ones. any idea?

> Workspace in use: "C:/Users/Chris/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 308, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 111, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Drücken Sie eine beliebige Taste . .

**Comment by shafaypro** [comment]
https://github.com/timgrossmann/InstaPy/issues/5337#issuecomment-612905783
