### ISSUE TITLE
Seems to be a problem with Webdriver. Please help!

### ISSUE THREAD

**Issue by RobTheTop** [InstaPy/InstaPy#5410]
I start the bot and all works fine, but then sometime (sometimes after 15 minutes, sometimes after 27 minutes) always different the program crashed with this error:

```
Traceback (most recent call last):
  File "C:\Users\Workstation\AppData\Local\Programs\Python\Python38\Lib\site-packages\instapy\like_util.py", line 598, in check_link
    browser.execute_script(
  File "C:\Users\Workstation\AppData\Local\Programs\Python\Python38\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "C:\Users\Workstation\AppData\Local\Programs\Python\Python38\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Workstation\AppData\Local\Programs\Python\Python38\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: can't convert undefined to object


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "C:\Users\Workstation\AppData\Local\Programs\Python\Python38\Lib\site-packages\quickstart.py", line 69, in <module>
    session.like_by_tags(['couple', 'love', 'cutecouple', 'instacouple', 'couplelove', 'lovehim', 'loveher', 'loveyou', 'iloveyou'], amount=100, media='Photo')
  File "C:\Users\Workstation\AppData\Local\Programs\Python\Python38\Lib\site-packages\instapy\instapy.py", line 1917, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\Workstation\AppData\Local\Programs\Python\Python38\Lib\site-packages\instapy\like_util.py", line 602, in check_link
    browser.execute_script(
  File "C:\Users\Workstation\AppData\Local\Programs\Python\Python38\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "C:\Users\Workstation\AppData\Local\Programs\Python\Python38\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Workstation\AppData\Local\Programs\Python\Python38\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window._sharedData is undefined
```
I can not found an error in my quichstart syntax oder something else.
can someone help me?
Thank you very much.

**Comment by DunkinDonat** [comment]
https://github.com/timgrossmann/InstaPy/issues/5337#issuecomment-612905783

**Comment by RobTheTop** [comment]
This could not help. same problem.

**Comment by shafaypro** [comment]
> This could not help. same problem.

That actually worked for me. Try pulling the Dev-Branch. and then doing the same thing.
