### ISSUE TITLE
Could not run quickstart.py on MacOS

### ISSUE THREAD

**Issue by justadlet** [InstaPy/InstaPy#5418]
Hi, initially I installed everything needed to use InstaPy and configured the quickstart.py file for me and tried to run it:
`python3 quickstart.py`

But I always got that error:
`Traceback (most recent call last):
File "D:/Projects/InstaPy-master/Test.py", line 24, in
headless_browser=True)
File "D:\Projects\InstaPy-master\instapy\instapy.py", line 318, in init
self.logger,
File "D:\Projects\InstaPy-master\instapy\browser.py", line 114, in set_selenium_local_session
options=firefox_options,
File "D:\Projects\InstaPy-master\venv\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in init
keep_alive=True)
File "D:\Projects\InstaPy-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in init
self.start_session(capabilities, browser_profile)
File "D:\Projects\InstaPy-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
response = self.execute(Command.NEW_SESSION, parameters)
File "D:\Projects\InstaPy-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "D:\Projects\InstaPy-master\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`

So, if you are having the same problems, just install Mozila Firefox on your mac and try running qucikstart.py.

**Comment by ColumOD** [comment]
Have you tried updating both Selenium and Firefox? Also, if you are using Firefox Developer that could cause an issue so try to use normal Firefox also if you are not already.
