### ISSUE TITLE
Quickstart error - Traceback (most recent call last)

### ISSUE THREAD

**Issue by marfz** [InstaPy/InstaPy#5424]
Newbie here, trying to run the quickstart script and I get this:

```
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "/Users/marfz/dev/InstaPy/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/Users/marfz/dev/InstaPy/instapy/instapy.py", line 3, in <module>
    import time, random, os, csv, json, requests, logging, unicodedata
ModuleNotFoundError: No module named 'requests'
```

**Comment by lucanello** [comment]
You have to install the packages:
`pip3 install -r requirements.txt`

**Comment by marfz** [comment]
Thanks @lucanello! 

When I do that I get this:

```
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3267, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==20.0.2' distribution was not found and is required by the application
```

I guess there's something wrong with pip? 

`pip -V` returns this

pip 20.1b1 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-20.1b1-py2.7.egg/pip (python 2.7)

**Comment by lucanello** [comment]
You have to upgrade pip first:
`python3 -m pip install --upgrade pip`

**Comment by marfz** [comment]
I upgraded pip – running quickstart.py now returns this:

```
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "/Users/marfz/dev/InstaPy/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/Users/marfz/dev/InstaPy/instapy/instapy.py", line 3, in <module>
    import time, random, os, csv, json, requests, logging, unicodedata
ModuleNotFoundError: No module named 'requests'
```

I installed requests with 
`pip3 install requests`
and I get requirement already satisfied. 

But I'm stilling getting the same error when running quickstart.py

**Comment by lucanello** [comment]
Are you running the quickstart.py file with `python3 quickstart.py`?
There are currently two major Python versions available, that's the reason for the confusion. You should make sure to use Python 3, check your standard version with `python -v`.

**Comment by marfz** [comment]
Yes I am using `python3 quickstart.py`

I have both versions installed, can it cause problems?

Python 2.7.18 and Python 3.8.2

**Comment by marfz** [comment]
I think I made some progress, running `python3 quickstart.py` returns this

```
Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session = InstaPy(username="XXXXXXX", 
  File "/Users/marfz/dev/InstaPy/instapy/instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Users/marfz/dev/InstaPy/instapy/browser.py", line 111, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

**Comment by lucanello** [comment]
No this doesn't make problems in general. Just make sure to run everything with `python3` and use `pip3` to install packages.

There seems to be a problem with the Firefox and geckodriver version. You should have a look at the following bug: https://stackoverflow.com/questions/47782650/selenium-common-exceptions-sessionnotcreatedexception-message-unable-to-find-a

**Comment by marfz** [comment]
Thanks @lucanello, I finally made it work. Stay safe!

**Comment by Godsstar** [comment]
> Thanks @lucanello, I finally made it work. Stay safe!

how?

**Comment by marfz** [comment]
@Godsstar I installed Python 3 correctly, removed 2.7, and installed all the requirements. Make sure you always use `pip3` and `python3`
