### ISSUE TITLE
Wont start in windows, when run quickstart

### ISSUE THREAD

**Issue by MuhammadAbidzarAbdussalam** [InstaPy/InstaPy#5432]
I found this issue when the first time i run this script, ive tried every suggestion that i found like downgrade the chrome, install firefox, download geodriver, but it still error, please tell me how to fix it, and im first in python, so please explain me with the human words ^_^

starting instapy with quickstart
================================
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/abidz/InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 23, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\abidz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\abidz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 111, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\abidz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\abidz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\abidz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\abidz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\abidz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Press any key to continue . . .

**Comment by naimulh247** [comment]
what version of python do you have and see if selenium is downloaded
