### ISSUE TITLE
problem with quikstart instapy

### ISSUE THREAD

**Issue by magontxu** [InstaPy/InstaPy#5439]
starting instapy with quickstart
================================
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/magon/InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\magon\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy-0.6.8-py3.8.egg\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\magon\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy-0.6.8-py3.8.egg\instapy\browser.py", line 110, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\magon\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy-0.6.8-py3.8.egg\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "C:\Users\magon\AppData\Local\Programs\Python\Python38-32\lib\site-packages\webdriverdownloader-1.1.0.3-py3.8.egg\webdriverdownloader\webdriverdownloader.py", line 195, in download_and_install
    with zipfile.ZipFile(os.path.join(self.get_download_path(version), filename), mode="r") as driver_zipfile:
  File "C:\Users\magon\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\magon\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Press any key to continue . . .

**Comment by JNAUS23** [comment]
I get the exact same issue every time. I have tried soo many things to make it work but nothing works... have you fixed it yet?
