### ISSUE TITLE
Cant start the bot because of error in Quickstart.py ? Or something with geckodriver maybe?

### ISSUE THREAD

**Issue by awsm0** [InstaPy/InstaPy#5449]
When I enter python3 quickstart.py

This is what happens:

InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 32, in <module>
    headless_browser=True)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/InstaPy/assets/geckodriver'

**Comment by awsm0** [comment]
I fixed it by installing geckodriver like so:

`wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-arm7hf.tar.gz`

`tar -xvzf geckodriver-v*`

`chmod +x geckodriver`

`sudo cp geckodriver /usr/local/bin/`

I didnt do it in the beginning since it said the latest version automatically installs geckodriver. seems like it doesnt

**Comment by eganay** [comment]
under windows, be sure that python and firefox are under the same bit schema (32bit both or 64bit both)
