### ISSUE TITLE
TimeOut error

### ISSUE THREAD

**Issue by finedesignz** [InstaPy/InstaPy#5461]
## Expected Behavior
Follow users followers is not working

## Current Behavior
```

InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/root/InstaPy"
^CTraceback (most recent call last):
  File "lcd3.py", line 75, in <module>
    page_delay=300)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.6/dist-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
root@Instapy-2:~/instapy-quickstart# python3 lcd3.py
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/root/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-05-06 21:04:31] [lindachristendesigns]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-05-06 21:04:31] [lindachristendesigns]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2020-05-06 21:04:32] [lindachristendesigns]  - Internet Connection Status: ok
INFO [2020-05-06 21:04:32] [lindachristendesigns]  - Current IP is "138.68.12.239" and it's from "United States/US"
INFO [2020-05-06 21:04:32] [lindachristendesigns]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2020-05-06 21:04:32] [lindachristendesigns]  - window.navigator.webdriver response: False
INFO [2020-05-06 21:04:32] [lindachristendesigns]  - Hide Selenium Extension: ok
..........................................................................
INFO [2020-05-06 21:04:44] [lindachristendesigns]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2020-05-06 21:04:44] [lindachristendesigns]  Saving account progress...
________________________________________________________________________________________
INFO [2020-05-06 21:05:03] [lindachristendesigns]  Starting to follow user `Followers`..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2020-05-06 21:05:03] [lindachristendesigns]  User 'sumobonnets' [1/4]

INFO [2020-05-06 21:10:21] [lindachristendesigns]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 3360 users & had 939 FOLLOWERS
[Session lasted 5.97 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-05-06 21:10:21] [lindachristendesigns]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "lcd3.py", line 126, in <module>
    interact=True)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 3466, in follow_user_followers
    self.logfolder,
  File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 1027, in get_given_user_followers
    logfolder,
  File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 767, in get_users_through_dialog_with_graphql
    browser.get("view-source:{}".format(url))
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    **raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Timeout loading page after 300000ms**


```

## Possible Solution (optional)
No idea... tried different things...

## InstaPy configuration
```
"""
This template is written by @Nuzzo235

What does this quickstart script aim to do?
- This script is targeting followers of similar accounts and influencers.
- This is my starting point for a conservative approach: Interact with the
audience of influencers in your niche with the help of 'Target-Lists' and
'randomization'.

NOTES:
- For the ease of use most of the relevant data is retrieved in the upper part.
"""

import random
from instapy import InstaPy
from instapy import smart_run
from selenium import webdriver
from instapy_chromedriver import binary_path # this will get you the path variable
from pyvirtualdisplay import Display
from selenium.webdriver.chrome.options import Options
chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
display = Display(visible=0, size=(800, 800))  
display.start()
driver = webdriver.Chrome(executable_path = binary_path, chrome_options = chrome_options)
driver.set_page_load_timeout(60)
driver.get("http://www.python.org")
assert "Python" in driver.title

# login credentials
insta_username = 'lindachristendesigns'
insta_password = 'piercemorgan'

# restriction data
# dont_likes = ['#exactmatch', '[startswith', ']endswith', 'broadmatch']
# ignore_users = ['user1', 'user2', 'user3']

""" Prevent commenting on and unfollowing your good friends (the images will 
still be liked)...
"""
friends = ["mzahmad", "nikkielizabethwright", "makennalovemodeling", "misstaylor.a", "macfashionhouse", "meghschmitt", "cyndeeceech", "michelleellingtondelgado", "noh3mi64", "tallyg_1", "ebonyfashionweek", "doctor grateful", "shaunabroady", "girardhaley", "peaceloveandlight11", "osheeameriah", "pedalpowerentertainment", "gigiblu888", "annetteledouxspiller", "jdimagery", "thebennettkidz", "cara.gunhild", "daniyellarich", "styledbynataliej", "topmodelbootcamp", "destinyk775", "onthatnotegreetings", "pe777", "destiny0975", "mskareng", "curly_kinky2", "gabbygene", "usjahprincess", "ursulagreen", "nwfashioncollective", "sinchon2011", "darryltureaud", "mayamezzeti", "markismarkp", "cazlynwalters", "calicreolemusic", "fitmomma_of3", "fashiondistrictnw", "tasstrategies", "unapologetic_tibrea"]

""" Prevent posts that contain...
"""
ignore_list = []

# TARGET data
""" Set similar accounts and influencers from your niche to target...
"""
targets = ['sumobonnets', 'graceeleyae', 'loza_tam', 'beforebeadheadz']

""" Skip all business accounts, except from list given...
"""
target_business_categories = ['Fashion Model', 'Health/Beauty', 'Jewelry/Watches']

# COMMENT data
comments = ['Nice shot! @{}',
        'I love your profile! @{}',
        'Your feed is an inspiration :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Getting inspired by you @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:']

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs = True,
                  page_delay=300)

# let's go! :>
with smart_run(session):
    # HEY HO LETS GO
    # general settings
    session.set_dont_include(friends)
    #session.set_dont_like(dont_likes)
    #session.set_ignore_if_contains(ignore_list)
    #session.set_ignore_users(ignore_users)
    session.set_simulation(enabled=True)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=7500,
                                    max_following=3000,
                                    min_followers=25,
                                    min_following=25,
                                    min_posts=10)

    session.set_skip_users(skip_private=True,
                           skip_no_profile_pic=True,
                           skip_business=True,
                           dont_skip_business_categories=[
                               target_business_categories])

    session.set_user_interact(amount=3, randomize=True, percentage=80, media='Photo')
    session.set_do_like(enabled=True, percentage=90)
    session.set_do_comment(enabled=True, percentage=15)
    session.set_comments(comments, media='Photo')
    session.set_do_follow(enabled=True, percentage=40, times=1)

    # activities

    # FOLLOW+INTERACTION on TARGETED accounts
    """ Select users form a list of a predefined targets...
    """
    number = random.randint(3, 5)
    random_targets = targets

    if len(targets) <= number:
        random_targets = targets

    else:
        random_targets = random.sample(targets, number)

    """ Interact with the chosen targets...
    """
    session.follow_user_followers(random_targets,
                                  amount=random.randint(30, 60),
                                  randomize=True, sleep_delay=600,
                                  interact=True)

    # UNFOLLOW activity
    """ Unfollow nonfollowers after one day...
    """
    session.unfollow_users(amount=random.randint(75, 100),
                           InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=24 * 60 * 60, sleep_delay=600)

    """ Unfollow all users followed by InstaPy after one week to keep the 
    following-level clean...
    """
    session.unfollow_users(amount=random.randint(75, 100),
                           InstapyFollowed=(True, "all"), style="FIFO",
                           unfollow_after=168 * 60 * 60, sleep_delay=600)

    """ Joining Engagement Pods...
    """
    session.join_pods()

"""
Have fun while optimizing for your purposes, Nuzzo
"""
session.end();
```

**Comment by finedesignz** [comment]
I have also tried many simpler configurations with lcd.py and nothing with follow users' followers works for me.

**Comment by Tolmino** [comment]
Have you seen that in your instapy configuration there is visible userid and password?

**Comment by finedesignz** [comment]
thanks for reply... yes, creentials work... it is able to connect to Instagram and even do likes and comments, but not follow users' followers
`# login credentials
insta_username = 'lindachristendesigns'
insta_password = 'xxxxxxx'`

**Comment by finedesignz** [comment]
Rebuilt fresh Instapy Install on DO server Ubuntu 16.04.  

Very basic configuration
`# imports
from instapy import InstaPy
from instapy import smart_run


# login credentials
insta_username = 'lindachristendesigns'
insta_password = 'xxxxxxxxxxx'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  nogui=True,
                  headless_browser=True)

with smart_run(session):
  """ Activity flow """		
  # general settings		

  # Like user followers
  session.follow_user_followers(['loza_tam', 'graceeleyae', 'Beforebeadheadz'], amount=187, randomize=True, interact=True)`


SAME ISSUE
`Traceback (most recent call last):
  File "lcd.py", line 32, in <module>
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 3466, in follow_user_followers
    self.logfolder,
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 1027, in get_given_user_followers
    logfolder,
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 767, in get_users_through_dialog_with_graphql
    browser.get("view-source:{}".format(url))
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Timeout loading page after 300000ms
`

**Comment by finedesignz** [comment]
Solved!  Make sure set_user_interaction is before the follow_user_followers and randomize is set to false unless you configure for random.

Changed to this:
```
session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
  session.follow_user_followers(['loza_tam', 'graceeleyae', 'Beforebeadheadz'], amount=27, randomize=False, interact=True)
  session.end(threaded_session=True)
  
```
