### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by TBrannan** [InstaPy/InstaPy#548]
When trying to use the following function

`session.follow_user_followers(['superdeluxe', 'timanderic'], amount=10, random=False)`

I get this error:

```Logged in successfully!
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    session.follow_user_followers(['superdeluxe', 'timanderic'], amount=10, random=False)
  File "/Users/Travis/Documents/GitHub/InstaPy/instapy/instapy.py", line 904, in follow_user_followers
    userFollowed += follow_given_user_followers(self.browser, user, amount, self.dont_include, self.username, self.follow_restrict, random)
  File "/Users/Travis/Documents/GitHub/InstaPy/instapy/unfollow_util.py", line 376, in follow_given_user_followers
    personFollowed = follow_through_dialog(browser, user_name, amount, dont_include, login, follow_restrict, allfollowing, random, callbacks=[])
  File "/Users/Travis/Documents/GitHub/InstaPy/instapy/unfollow_util.py", line 201, in follow_through_dialog
    person_list.append(person.find_element_by_xpath("../../../*").find_elements_by_tag_name("a")[1].text)
IndexError: list index out of range```

**Comment by kushpvo** [comment]
Getting the same error

**Comment by romankk** [comment]
Same here

`Load button not found, working with current images!
Traceback (most recent call last):
  File "/root/InstaPy/index_flg.py", line 15, in <module>
    .interact_user_following(['che_che_vica', 'anya_fedosovaaa', 'kristinka_belousova_'], amount=800, random=True)\
  File "/root/InstaPy/instapy/instapy.py", line 900, in interact_user_following
    self.like_by_users(userToInteract, self.user_interact_amount, self.user_interact_random, self.user_interact_media)
  File "/root/InstaPy/instapy/instapy.py", line 601, in like_by_users
    followed += follow_user(self.browser, self.follow_restrict, self.username, username)
  File "/root/InstaPy/instapy/unfollow_util.py", line 136, in follow_user
    follow_button = flwBtn[0]
IndexError: list index out of range
`

**Comment by timgrossmann** [comment]
@BernardoGO

**Comment by timgrossmann** [comment]
#599
