### ISSUE TITLE
Message: invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by quintendewilde** [InstaPy/InstaPy#5487]
Hi, 

How come the InstaPy is so unreliable? Two years ago It was really good?!

I can't seem to have a stable workflow? Are there people with a stable workflow (also with schedule?) and maybe share there barebones setup. I don't need all you tricks to get more followers. But just a workable setup on a raspberry pi. 

So to go to the specifics. This is were I'm at now.
I got it to works some times for the last few days...

but now it breaks again with this... 

```
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    headless_browser=False)
  File "/home/pi/InstaPy/instapy/instapy.py", line 322, in __init__
    self.logger,
  File "/home/pi/InstaPy/instapy/browser.py", line 118, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

```

**Comment by esmaily** [comment]
I have same error
