### ISSUE TITLE
ERROR : extension.xpi

### ISSUE THREAD

**Issue by spacemishka** [InstaPy/InstaPy#5496]
I have an issue when running this script. I figured out that it is not possible to install this plugin. When you try it manually, it will fail, because it is not signed. It will either fail, if you turn of the verification if a addon is signed or not.

I am on W10

Message

> D:\Python\Instabot>python InstaBot.py
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/peter/InstaPy"
Traceback (most recent call last):
  File "InstaBot.py", line 47, in <module>
    IsntaBot().instaLogin()
  File "InstaBot.py", line 22, in __init__
    instaSession = self.instaLogin()
  File "InstaBot.py", line 28, in instaLogin
    return InstaPy(username=insta_username, password=insta_password, headless_browser=True)
  File "F:\Python37-32\lib\site-packages\instapy\instapy.py", line 319, in __init__
    self.logger,
  File "F:\Python37-32\lib\site-packages\instapy\browser.py", line 118, in set_selenium_local_session
    browser.install_addon(create_firefox_extension(), temporary=True)
  File "F:\Python37-32\lib\site-packages\instapy\browser.py", line 46, in create_firefox_extension
    with zipfile.ZipFile(zip_file, "w", zipfile.ZIP_DEFLATED, False) as zipf:
  File "F:\Python37-32\lib\zipfile.py", line 1207, in __init__
    self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\peter\\InstaPy\\assets\\extension.xpi'

**Comment by theRouter** [comment]
same problem

**Comment by romain-bsn** [comment]
Hi,
Just delete the extension.api file located in C:\Users\peter\InstaPy\assets\

**Comment by vihanga-w** [comment]
I found a fix:
replace line 128 in C:\Users\Your Username\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\browser.py
with
browser.install_addon("C:\\Users\\Your Username\\InstaPy\\assets\\extension.xpi", temporary=True)

Remember to replace Your Username with your username *duh*
