### ISSUE TITLE
StaleElementReferenceException

### ISSUE THREAD

**Issue by tobeyond** [InstaPy/InstaPy#5498]
I'm always getting this error. It works for a while and then it happens:

## Current Behavior

INFO [2020-05-15 15:31:37] [...]  Ongoing Follow [7/50]: now following [...]..
Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.follow_user_following([...], amount=50, randomize=True, sleep_delay=600)
  File "C:\Users\...\Documents\Insta\INSTAPY\INSTAPY\lib\site-packages\instapy\instapy.py", line 3722, in follow_user_following
    person, self.follow_times, sleep_delay, interact
  File "C:\Users\...\Documents\Insta\INSTAPY\INSTAPY\lib\site-packages\instapy\instapy.py", line 1191, in follow_by_list
    self.logfolder,
  File "C:\Users\...\Documents\Insta\INSTAPY\INSTAPY\lib\site-packages\instapy\unfollow_util.py", line 611, in follow_user
    browser, "follow", track, login, user_name, None, logger, logfolder
  File "C:\Users\...\Documents\Insta\INSTAPY\INSTAPY\lib\site-packages\instapy\unfollow_util.py", line 1532, in verify_action
    browser, track, username, person, person_id, logger, logfolder
  File "C:\Users\...\Documents\Insta\INSTAPY\INSTAPY\lib\site-packages\instapy\unfollow_util.py", line 212, in get_following_status
    following_status = follow_button.text
  File "C:\Users\...\Documents\Insta\INSTAPY\INSTAPY\lib\site-packages\selenium\webdriver\remote\webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "C:\Users\...\Documents\Insta\INSTAPY\INSTAPY\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\...\Documents\Insta\INSTAPY\INSTAPY\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\...\Documents\Insta\INSTAPY\INSTAPY\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class=" ffKix sqdOP  L3NKy _4pI4F  y3zKF     A086a" type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

##
It's happening everytime now. How do I fix this?

**Comment by tobeyond** [comment]
I'm not using headless Firefox , nor using the commenting function.
Is there a way not to refresh the page to verify follow/unfollow?
