### ISSUE TITLE
I got this issue

### ISSUE THREAD

**Issue by unaipm** [InstaPy/InstaPy#5507]
Hi, I tried to install it with the quickstart instapy but i get this issue when running:

Traceback (most recent call last):
  File "quickstart.py", line 24, in <module>
    headless_browser=True)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by rodrigofl-dev** [comment]
Have you installed Firefox browser?

**Comment by pedrovcampos** [comment]
I had this install error or fire browser that solve your problem
