### ISSUE TITLE
Exec Format Error on Raspi

### ISSUE THREAD

**Issue by RealDataLLC** [InstaPy/InstaPy#5516]
## Expected Behavior
I'm currently unable to run Instapy on my Raspi 3b+

The main issue is the exec format issue on the geckodriver. 

1. I've followed the raspi docs to the T and made sure to drop the newest version of the gecko driver for in linux in `/home/pi/Instapy/bin/geckodriver`

2. Upgraded to distro to buster and got firefox working
3. Updated Instapy packages

## Current Behavior
```
Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "basic_follow-unfollow_activity.py", line 32, in <module>
    headless_browser=False)
  File "/home/pi/Instapy/lib/python3.7/site-packages/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/home/pi/Instapy/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/Instapy/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/Instapy/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/Instapy/bin/geckodriver'

```
## Possible Solution (optional)
I'm kind of lost at this point, is it because I'm trying to run this inside a virtual environment?

**Comment by mateocabanal** [comment]
The geckodriver that instapy is trying to download is for x86. You will need to compile geckodriver yourself sadly.

**Comment by tperas** [comment]
Do you have any update ? Got the same error only when running as a cron task
