### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: TypeError: rect is undefined

### ISSUE THREAD

**Issue by s2339956** [InstaPy/InstaPy#5528]
## InstaPy configuration

Traceback (most recent call last):
  File "quickstart.py", line 87, in <module>
    session.like_by_tags(amount=10, use_smart_hashtags=True)
  File "/home/tinxie/InstaPy-master/InstaPy-master/instapy/instapy.py", line 2015, in like_by_tags
    self.logfolder,
  File "/home/tinxie/InstaPy-master/InstaPy-master/instapy/comment_util.py", line 92, in comment_image
    .send_keys(comment_to_be_sent)
  File "/home/tinxie/.local/lib/python3.5/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/home/tinxie/.local/lib/python3.5/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/home/tinxie/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/tinxie/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: rect is undefined

**Comment by CodexAsh** [comment]
I am getting same issue.

**Comment by DodoTheDuck** [comment]
Same problem. Anyone any ideas?

**Comment by CodexAsh** [comment]
No. Instapy don't work properly. Leave it
