### ISSUE TITLE
Error quickstart.py

### ISSUE THREAD

**Issue by josepfm** [InstaPy/InstaPy#5530]
I execute python3 quickstart.py and get:

InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/josepfm/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    session = InstaPy(username='usernameInstagram',
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instapy/browser.py", line 111, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by rodrigofl-dev** [comment]
Python version, Geckodriver version, Firefox version?

**Comment by josepfm** [comment]
Python 3.8.3
Firefox 76.0.1 (64-bit)

I had a new error. It is really unstable.

<img width="1439" alt="Captura de pantalla 2020-05-28 a las 19 34 59" src="https://user-images.githubusercontent.com/8105593/83174535-d13ed900-a11a-11ea-8909-179be85b381e.png">

**Comment by josepfm** [comment]
And now, all the while this same mistake. It's very hard to make it work, not to mention impossible.

<img width="952" alt="Captura de pantalla 2020-05-28 a las 19 42 41" src="https://user-images.githubusercontent.com/8105593/83174969-79ed3880-a11b-11ea-82d1-18f6e4f0ac59.png">

**Comment by ediziks** [comment]
@jose46moreno try to comment out server check script in login_util.py. Might work.

```
 # check Instagram.com status
    # try:
    #     logger.info("-- Connection Checklist [2/3] (Instagram Server Status)")
    #     browser.get("https://isitdownorjust.me/instagram-com/")
    #     sleep(2)
    #     # collect isitdownorjust.me website information
    #     website_status = browser.find_element_by_xpath(
    #         read_xpath(login_user.__name__, "website_status")
    #     )
    #     response_time = browser.find_element_by_xpath(
    #         read_xpath(login_user.__name__, "response_time")
    #     )
    #     response_code = browser.find_element_by_xpath(
    #         read_xpath(login_user.__name__, "response_code")
    #     )

    #     logger.info("- Instagram WebSite Status: {} ".format(website_status.text))
    #     logger.info("- Instagram Response Time: {} ".format(response_time.text))
    #     logger.info("- Instagram Reponse Code: {}".format(response_code.text))
    #     logger.info("- Instagram Server Status: ok")
    #     update_activity(
    #         browser,
    #         action=None,
    #         state="Instagram servers are running correctly",
    #         logfolder=logfolder,
    #         logger=logger,
    #     )
    # except Exception:
    #     logger.warn("- Instagram Server Status: error")
    #     update_activity(
    #         browser,
    #         action=None,
    #         state="Instagram server is down",
    #         logfolder=logfolder,
    #         logger=logger,
    #     )
    #     return False
```

**Comment by Cromer17** [comment]
Same issue here, how did you solve it?
