### ISSUE TITLE
Wrong version of google chrome on macOS !

### ISSUE THREAD

**Issue by vincent-cadoret** [InstaPy/InstaPy#5531]
Hello,
I can't start my bot on macOS Catalina, because Google Chrome is in version 83 and I need 71/75 which cannot be found. What to do?

ERROR [2020-05-28 16:40:53] [#]  Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.15.4 x86_64)
Traceback (most recent call last):
  File "/Users/vincent/Library/Python/2.7/lib/python/site-packages/instapy/browser.py", line 163, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Users/vincent/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/vincent/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/vincent/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/vincent/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/vincent/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.15.4 x86_64)

Traceback (most recent call last):
  File "../quickstart.py", line 3, in <module>
    session = InstaPy(username='#', password='#', disable_image_load=True)
  File "/Users/vincent/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "/Users/vincent/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /Users/vincent/Library/Python/2.7/lib/python/site-packages/instapy_chromedriver/chromedriver_mac64

**Comment by rodrigofl-dev** [comment]
Chrome is not supported anymore, use Firefox instead.

**Comment by vincent-cadoret** [comment]
> Chrome is not supported anymore, use Firefox instead.

Ok thanks. But when i use firefox, i need GeckoDriver... How i can install this driver ?

**Comment by jennettageorge** [comment]
> > Chrome is not supported anymore, use Firefox instead.
> 
> Ok thanks. But when i use firefox, i need GeckoDriver... How i can install this driver ?

`brew install geckodriver`
