### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by MacroSolutionsLTD** [InstaPy/InstaPy#5539]
Traceback (most recent call last):
  File ".\efes.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\coler\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\coler\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 111, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\coler\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\coler\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\coler\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\coler\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\coler\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by zaymonoid** [comment]
You'll need to install Firefox to get the Gecko driver.

**Comment by MacroSolutionsLTD** [comment]
installed gecko and firefox and updated

**Comment by Deustavo** [comment]
i decided this problem instaling the last version of Gecko manualy (https://github.com/mozilla/geckodriver/releases) and put the .exe file on folder run. After i start the project clicking in windows_start

**Comment by MacroSolutionsLTD** [comment]
I copy to run folder and start working Thanks

**Comment by Traxido** [comment]
Installing on Ubuntu server and received the same errors. Any help?

**Comment by Cromer17** [comment]
Thanks @Deustavo

**Comment by SockRocks** [comment]
> 
> 
> i decided this problem instaling the last version of Gecko manualy (https://github.com/mozilla/geckodriver/releases) and put the .exe file on folder run. After i start the project clicking in windows_start

I don't understand what you are saying.

**Comment by SockRocks** [comment]
Thank you.
