### ISSUE TITLE
Ran out of input

### ISSUE THREAD

**Issue by aldriebarcena** [InstaPy/InstaPy#5574]
My bot isnt logging in to instagram correctly. Im very new to python and instapy and all that. This is what it says:

Traceback (most recent call last):
  File "C:\Users\aldov\OneDrive\Desktop\nice\yes.py", line 4, in <module>
    session.login()
  File "C:\Users\aldov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 405, in login
    if not login_user(
  File "C:\Users\aldov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\login_util.py", line 283, in login_user
    for cookie in pickle.load(
EOFError: Ran out of input
>>>

**Comment by grndng** [comment]
Can you show us your code?
