### ISSUE TITLE
Comment and follow problem

### ISSUE THREAD

**Issue by AleXi-tech** [InstaPy/InstaPy#5593]
Im currenntly having problem with commenting and following with smart run i get an error message like "unboundLocalError: local variable 'commenting_approved' referenced before assignment" for do_comment code. Without smart run after it gets a post likes it and comments it stuck on the comment page and wont go to follow and it says user is inaccesible and keeps on like that in all posts

Here are my codes;

from instapy import InstaPy
from instapy import smart_run
import os
session = InstaPy(username='xxx', password='xxx', headless_browser=False)
session.login()

with smart_run(session):

    session.set_do_like(enabled=True, percentage=100)
    session.set_do_follow(enabled=True, percentage=100)
    session.set_do_comment(enabled=True, percentage=100)
    session.set_comments(['Nice shot',
            'This is awesome!! :heart_eyes:',
            'I really like the way you captured this',
            'Great capture!! :smiley:',
            'Looks awesome!',
            'Cool',
            'Amazing!',
            'Really nice',
            'Nice!!',
            'Truely masterpiece...'], media=None)

    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes_hourly=57,
                              peak_likes_daily=585,
                               peak_comments_hourly=21,
                               peak_comments_daily=182,
                                peak_follows_hourly=48,
                                peak_follows_daily=None,
                                 peak_unfollows_hourly=35,
                                 peak_unfollows_daily=402,
                                  peak_server_calls_hourly=None,
                                  peak_server_calls_daily=4700)
    session.set_skip_users(skip_private=True,
                       private_percentage=100,
                       skip_no_profile_pic=False,
                       no_profile_pic_percentage=100,
                       skip_business=False,
		                skip_non_business=False,
                       business_percentage=100,)

    session.set_relationship_bounds(enabled=True,
				 potency_ratio=None,
				  delimit_by_numbers=True,
				   max_followers=8500,
				    max_following=4490,
				     min_followers=100,
				      min_following=56,
				       min_posts=10,
                        max_posts=1000)

    session.like_by_tags(['natgeo', 'world'], amount=100)
    session.like_by_feed(amount=100, randomize=True, unfollow=False, interact=True)
    session.follow_user_followers(['xxx'], amount=10, randomize=True, interact=True)
    session.unfollow_users(amount=60, instapy_followed_enabled=True, instapy_followed_param="nonfollowers", style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
    session.accept_follow_requests(amount=100, sleep_delay=1)
    session.set_do_story(enabled = True, percentage = 70, simulate = True)
    session.set_use_clarifai(enabled=True, api_key='xxx', models=['nsfw'], check_video=True)
    session.clarifai_check_img_for(['nsfw'])

**Comment by alokkumarsbg** [comment]
Goto comment_util.py and in line no 427 make the changes as per below code. It will fix the issue but the issue is then in line 100 of the same page.

# comments
    if delimit_commenting:
        (commenting_approved, disapproval_reason,) = verify_commenting(
            browser, max_comments, min_comments, logger,
        )
    # # if not commenting_approved:
        # # logger.info(disapproval_reason)
        # # return False

    else:
        (
        commenting_approved,
        selected_comments,
        disapproval_reason,
        ) = verify_mandatory_words(comments_mandatory_words, comments, browser, logger,)
    if not commenting_approved:
        logger.info(disapproval_reason)
        return False



After making changes get a new issue. Traceback below for new error.

Traceback (most recent call last):
  File "C:\Users\Users\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Users\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Users\.vscode\extensions\ms-python.python-2020.6.91350\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Users\.vscode\extensions\ms-python.python-2020.6.91350\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\Users\.vscode\extensions\ms-python.python-2020.6.91350\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Users\Users\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Users\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Users\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Desktop\Python\Instagram\instapy-quickstart-master\instapy-quickstart-master\Template.py", line 40, in <module>
    session.interact_by_users_tagged_posts(['alokkeshri'], amount=5, randomize=True, media='Photo')
  File "C:\Users\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 2867, in interact_by_users_tagged_posts
    self.logfolder,
  File "C:\Users\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\comment_util.py", line 451, in process_comments
    browser, user_name, selected_comments, blacklist, logger, logfolder,
  File "C:\Users\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\comment_util.py", line 100, in comment_image
    .send_keys(Keys.ENTER)
  File "C:\Users\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "C:\Users\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\actions\action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "C:\Users\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=81.0.4044.138)

**Comment by alokkumarsbg** [comment]
Was able to fix the issue. Instead of separately entering the comments and Sending Enter Key, we can do both at the same time.
Not sure why in Code is separate. I modified it to below code and commenting one. Comment_util.py in Line 100

 # wait, to avoid crash
            sleep(2)
            # click on textarea/comment box and enter comment
            (
                ActionChains(browser)
                .move_to_element(comment_input[0])
                .click()
                .send_keys(comment_to_be_sent)
                .send_keys(Keys.ENTER)
                .perform()
            )
            # wait, to avoid crash
            sleep(2)
            # post comment / <enter>
            """(
                ActionChains(browser)
                .move_to_element(comment_input[0])
                .click()
                .send_keys(Keys.ENTER)
                .perform()
            )"""
