### ISSUE TITLE
how do i combine quota with schedules?

### ISSUE THREAD

**Issue by gdefagot** [InstaPy/InstaPy#5601]
Hi guys! 
I was wondering what's the right way to combine schedules and quota... I want to have a few schedules with different actions (e.g. at 9:30 am follow followers, then at 3 pm follow likers)  but i want both execution to have the same limit for follows...  I mean, if at the 9am run I follow 10 accounts, and I have my daly follow limit set to 30, I want that the run for 3 pm follow 20 accounts tops, not having it´s own new quota of 30... how can I do this?
Right now i'm trying to do it having a global session defined and use smart_run, like this :

```
session = get_session()
while True:
  with smart_run(session):
    schedule.run_pending()
    sleep(1)
``` 

but this is not working... after succesfully creating the session, its failing with this error:

```
Traceback (most recent call last):
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9ddfef6550>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "instabot.py", line 116, in <module>
    with smart_run(session):
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/instapy/util.py", line 1839, in smart_run
    session.login()
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/instapy/instapy.py", line 404, in login
    self.browser.implicitly_wait(temporary_page_delay)
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 911, in implicitly_wait
    self.execute(Command.SET_TIMEOUTS, {
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/Users/gabriel/miniconda3/envs/instabot/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=56462): Max retries exceeded with url: /session/5e4b9aa5-45bc-9c48-8330-377561d9cccd/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ddfef6550>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

Is there any other way to do this? I think that I need just one session to be used by the different schedules, so they share taht quota... is that right?

**Comment by gdefagot** [comment]
Inverting the order of the loop fixed the issue:

```
session = get_session()
with smart_run(session):
while True:
    schedule.run_pending()
    sleep(1)
```
