### ISSUE TITLE
Instapy crashes after a few interactions.

### ISSUE THREAD

**Issue by potentowl** [InstaPy/InstaPy#5615]
```
Traceback (most recent call last):
  File "quickstart.py", line 57, in <module>
    session.interact_user_followers(['123456789'], amount=1000, randomize=True)
  File "/home/north/instapy1/instapy/instapy.py", line 3127, in interact_user_followers
    self.user_interact_media,
  File "/home/north/instapy1/instapy/instapy.py", line 2596, in interact_by_users
    self.logfolder,
  File "/home/north/instapy1/instapy/unfollow_util.py", line 611, in follow_user
    browser, track, login, user_name, None, logger, logfolder
  File "/home/north/instapy1/instapy/unfollow_util.py", line 214, in get_following_status
    following_status = follow_button.text
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
```

## InstaPy configuration
Python 3.6.9
Selenium 3.14.1
Mozilla Firefox 78.0.1
Python 3.6.9
Geckodriver 0.26.0

**Comment by flackoon** [comment]
Same here when I use the **follow_likers** method.

**Comment by gvmturl** [comment]
Take a look on Insomniac 


https://github.com/alexal1/Insomniac
