### ISSUE TITLE
UnboundLocalError local variable 'commenting_approved' referenced before assignment

### ISSUE THREAD

**Issue by JartySharky** [InstaPy/InstaPy#5663]
## Expected Behavior
I can interact with the followers of other accounts with no interruption

## Current Behavior
After the first like of the first account, I get the following:
```
INFO [2020-07-27 17:57:05] [instaname]  --> Image Liked!

INFO [2020-07-27 17:57:50] [instaname]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 2.47 minutes]
INFO [2020-07-27 17:57:50] [instaname]  Session ended!

Traceback (most recent call last):
  File "../quickstart.py", line 53, in <module>
    session.interact_user_followers(['targetinstaname'], amount=340)
  File "C:\Users\Jarty\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 3123, in interact_user_followers
    self.interact_by_users(
  File "C:\Users\Jarty\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 2545, in interact_by_users
    success = process_comments(
  File "C:\Users\Jarty\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\comment_util.py", line 431, in process_comments
    if not commenting_approved:
UnboundLocalError: local variable 'commenting_approved' referenced before assignment
Drücken Sie eine beliebige Taste . . .
```

## InstaPy configuration
I'm using a quickstart template and did noch change anything. "simple_interaction_good_for_beginners"

```
# let's go! :>
with smart_run(session):
    # settings
    session.set_user_interact(amount=3, randomize=True, percentage=100,
                              media='Photo')
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=3000,
                                    max_following=900,
                                    min_followers=50,
                                    min_following=50)
    session.set_simulation(enabled=False)
    session.set_do_like(enabled=True, percentage=100)
    session.set_ignore_users([])
    session.set_do_comment(enabled=True, percentage=35)
    session.set_do_follow(enabled=True, percentage=25, times=1)
    session.set_comments(photo_comments)
    session.set_ignore_if_contains([])
    session.set_action_delays(enabled=True, like=40)

    # activity
    session.interact_user_followers(['targetinstaname'], amount=340)

```

**Comment by danihrndzld** [comment]
same
