### ISSUE TITLE
Click element problem, it happens after a little time working

### ISSUE THREAD

**Issue by elissonnog** [InstaPy/InstaPy#5670]
Traceback (most recent call last):
  File "/home/usuario/InstaPy-master/instapy/util.py", line 976, in click_element
    element.click()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <span class=""> is not clickable at point (28,677) because another element <div class="JxPw3 sHch9   "> obscures it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 158, in <module>
    session.like_by_tags(my_hashtags, amount=30)
  File "/home/usuario/InstaPy-master/instapy/instapy.py", line 1935, in like_by_tags
    liked_img,
  File "/home/usuario/InstaPy-master/instapy/like_util.py", line 758, in like_image
    click_element(browser, like_elem[0])
  File "/home/usuario/InstaPy-master/instapy/util.py", line 990, in click_element
    + "')[0].scrollIntoView({ inline: 'center' });"
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: document.getElementsByClassName(...)[0] is undefined

**Comment by andrenpt** [comment]
I have the same issue...

**Comment by dwikyrestu** [comment]
I try to maximize the window and set zoom scale to 80%, it works

**Comment by gabriel-lemelle** [comment]
#5719
