### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by bilardowyprezes** [InstaPy/InstaPy#5698]
Hi i have this problem....

Workspace in use: "C:/Users/IT-WINDOOR/InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 30, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\IT-WINDOOR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 312, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\IT-WINDOOR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 121, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\IT-WINDOOR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\IT-WINDOOR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\IT-WINDOOR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\IT-WINDOOR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\IT-WINDOOR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Press any key to continue . . .

**Comment by marlon33** [comment]
i have the same problem, did you already fix it?
