### ISSUE TITLE
exceptionwith webdriver (chromedriver)

### ISSUE THREAD

**Issue by nacimgoura** [InstaPy/InstaPy#570]
Hello,
thanks you for your work.
I have a problem when I want to run Instapy in my server.
I followed all the steps more when I execute the program i have this error : 
```
root@nacim:~/project/InstaPy# python3 instanacim.py
Traceback (most recent call last):
  File "instanacim.py", line 5, in <module>
    session = InstaPy(username='username', password='password', nogui=True)\
  File "/root/project/InstaPy/instapy/instapy.py", line 101, in __init__
    self.set_selenium_local_session()
  File "/root/project/InstaPy/instapy/instapy.py", line 140, in set_selenium_local_session
    self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/common/service.py", line 86, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/common/service.py", line 99, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service ./assets/chromedriver unexpectedly exited. Status code was: 127
```

But i have chromedriver in assets folder. I can't resolve this error and I need your help.
Thank you :smile:

**Comment by timgrossmann** [comment]
@nacimgoura You probably forgot to add `nogui=True` to the `InstaPy()` constructor 😉

**Comment by nacimgoura** [comment]
I just checked and I haven't forgotten :disappointed: 
```
session = InstaPy(username='username', password='password', nogui=True)
```
Thank you but it doesn't seem to come from that.
I'll start over from the beginning.

**Comment by ogerasymenko** [comment]
recently I'm wrote in other topic what have issue with crontab [https://github.com/timgrossmann/InstaPy/issues/576](url) Today I made trace all output to file and figure out what program crashes with selenium.common.exceptions.WebDriverException:

Traceback (most recent call last):
  File "insta.py", line 19, in <module>
    session.like_by_tags(tags[tags], amount=30, media='Photo')
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 517, in like_by_tags
    followed += follow_user(self.browser, self.follow_restrict, self.username, user_name)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 132, in follow_user
    follow_button.click()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button class="_qv64e _gexxb _4tgw8 _njrw0">...</button> is not clickable at point (688, 14). Other element would receive the click: <div class="_qlijk">...</div>
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-45-generic x86_64)

**Comment by converge** [comment]
hi @nacimgoura , did you fix it ? how ?

**Comment by nacimgoura** [comment]
Hi, I did not retest for a long time. I will test asap.

**Comment by converge** [comment]
@nacimgoura you forgot to install chrome browser https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
