### ISSUE TITLE
No module named selenium

### ISSUE THREAD

**Issue by RhaegarTargaryen55** [InstaPy/InstaPy#5701]
It's been a while since I used this bot. And now I just installed it via instruction, trying to start it with mac_start.command (quickstat via the instruction) and I get this:

```
NoOne:~ NoOne$ /Users/NoOne/Downloads/instapy-quickstart-master/run/mac_start.command ; exit;
Starting InstaPy with quickstart
====================
Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/Library/Python/2.7/site-packages/instagram_py-0.0.1-py2.7.egg/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Library/Python/2.7/site-packages/instagram_py-0.0.1-py2.7.egg/instapy/instapy.py", line 13, in <module>
    from selenium import webdriver
ImportError: No module named selenium
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Any idea?

**Comment by Kunal614** [comment]
@RhaegarTargaryen55
run - > sudo pip install selenium

**Comment by RhaegarTargaryen55** [comment]
@Kunal614

already did, it says

```
Requirement already satisfied: selenium in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (3.141.0)
Requirement already satisfied: urllib3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from selenium) (1.25.3)
```

and then when I start the bot, it shows exactly the same message like at my first message

**Comment by Kunal614** [comment]
ok then activate virtualenv

**Comment by Kunal614** [comment]
then try to run

**Comment by RhaegarTargaryen55** [comment]
@Kunal614 

> ok then activate virtualenv

how can i do that?

**Comment by Kunal614** [comment]
If you are in linux then go to your project folder and there install 
pip3 install virtualenv
then after that run command virtaulenv .
then after that source bin/activate
After that there you must install selenium and run the code

**Comment by RhaegarTargaryen55** [comment]
@Kunal614 
i'm on mac os, so i guess it's the same code?

**Comment by Kunal614** [comment]
yes run that if  facing any problem then ping me and can you send your code.

**Comment by RhaegarTargaryen55** [comment]
@Kunal614 
okay, so my code looks like this

```
NoOne:~ NoOne$ cd documents
NoOne:documents NoOne$ cd instabot
NoOne:instabot NoOne$ pip3 install virtualenv
-bash: pip3: command not found
```

then i tried pip install virtualenv

```
NoOne:~ NoOne$ cd documents
NoOne:documents NoOne$ cd instabot
NoOne:instabot NoOne$ pip install virtualenv
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: virtualenv in /Users/NoOne/Library/Python/2.7/lib/python/site-packages (20.0.31)
Requirement already satisfied: distlib<1,>=0.3.1 in /Users/NoOne/Library/Python/2.7/lib/python/site-packages (from virtualenv) (0.3.1)
Requirement already satisfied: importlib-metadata<2,>=0.12; python_version < "3.8" in /Users/NoOne/Library/Python/2.7/lib/python/site-packages (from virtualenv) (1.7.0)
Requirement already satisfied: appdirs<2,>=1.4.3 in /Users/NoOne/Library/Python/2.7/lib/python/site-packages (from virtualenv) (1.4.4)
Requirement already satisfied: pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32" in /Users/NoOne/Library/Python/2.7/lib/python/site-packages (from virtualenv) (2.3.5)
Requirement already satisfied: filelock<4,>=3.0.0 in /Users/NoOne/Library/Python/2.7/lib/python/site-packages (from virtualenv) (3.0.12)
Requirement already satisfied: importlib-resources>=1.0; python_version < "3.7" in /Users/NoOne/Library/Python/2.7/lib/python/site-packages (from virtualenv) (3.0.0)
Requirement already satisfied: six<2,>=1.9.0 in /Users/NoOne/Library/Python/2.7/lib/python/site-packages (from virtualenv) (1.15.0)
Requirement already satisfied: configparser>=3.5; python_version < "3" in /Library/Python/2.7/site-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv) (3.5.0)
Requirement already satisfied: zipp>=0.5 in /Users/NoOne/Library/Python/2.7/lib/python/site-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv) (1.2.0)
Requirement already satisfied: contextlib2; python_version < "3" in /Users/NoOne/Library/Python/2.7/lib/python/site-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv) (0.6.0.post1)
Requirement already satisfied: scandir; python_version < "3.5" in /Users/NoOne/Library/Python/2.7/lib/python/site-packages (from pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32"->virtualenv) (1.10.0)
Requirement already satisfied: typing; python_version < "3.5" in /Users/NoOne/Library/Python/2.7/lib/python/site-packages (from importlib-resources>=1.0; python_version < "3.7"->virtualenv) (3.7.4.3)
Requirement already satisfied: singledispatch; python_version < "3.4" in /Users/NoOne/Library/Python/2.7/lib/python/site-packages (from importlib-resources>=1.0; python_version < "3.7"->virtualenv) (3.4.0.3)
NoOne:instabot NoOne$ 
```

is everything correct so far?

**Comment by Kunal614** [comment]
I think first you should update your pip

**Comment by RhaegarTargaryen55** [comment]
@Kunal614 
okay i think i updated it via `sudo pip3 install -U pip --ignore-installed pip`

and now my code looks like this

```
NoOne:~ NoOne$ cd documents
NoOne:documents NoOne$ cd instabot
NoOne:instabot NoOne$ pip install virtualenv
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/utils/misc.py:531: UserWarning: Unbuilt egg for Unknown [unknown version] (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages)
  pkg_resources.working_set.require(req_name)
Collecting virtualenv
  Using cached virtualenv-20.0.31-py2.py3-none-any.whl (4.9 MB)
Collecting appdirs<2,>=1.4.3
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting distlib<1,>=0.3.1
  Using cached distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Requirement already satisfied: six<2,>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from virtualenv) (1.11.0)
Collecting filelock<4,>=3.0.0
  Using cached filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting importlib-metadata<2,>=0.12; python_version < "3.8"
  Using cached importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
Collecting zipp>=0.5
  Using cached zipp-3.1.0-py3-none-any.whl (4.9 kB)
ERROR: Error while checking for conflicts. Please file an issue on pip's issue tracker: https://github.com/pypa/pip/issues/new
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2681, in version
    return self._version
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 535, in _determine_conflicts
    return check_install_conflicts(to_install)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 108, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 50, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2689, in version
    raise ValueError(msg, self)
ValueError: ("Missing 'Version:' header and/or METADATA file at path: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/-ip-19.0.1.dist-info/METADATA", Unknown [unknown version] (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages))
Installing collected packages: appdirs, distlib, filelock, zipp, importlib-metadata, virtualenv
Successfully installed appdirs-1.4.4 distlib-0.3.1 filelock-3.0.12 importlib-metadata-1.7.0 virtualenv-20.0.31 zipp-3.1.0
NoOne:instabot NoOne$ 

```

i don't really know what it means, I'm sorry


however when i tried to start my ig bot, now the error is different, look

```
/Users/NoOne/Documents/Instabot/instapy-quickstart-master/run/mac_start.command ; exit;
NoOne:~ NoOne$ /Users/NoOne/Documents/Instabot/instapy-quickstart-master/run/mac_start.command ; exit;
Starting InstaPy with quickstart
====================
Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/Library/Python/2.7/site-packages/instagram_py-0.0.1-py2.7.egg/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Library/Python/2.7/site-packages/instagram_py-0.0.1-py2.7.egg/instapy/instapy.py", line 25, in <module>
    from .clarifai_util import check_image
  File "/Library/Python/2.7/site-packages/instagram_py-0.0.1-py2.7.egg/instapy/clarifai_util.py", line 4, in <module>
    from clarifai.rest import Workflow
ImportError: cannot import name Workflow
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by Kunal614** [comment]
is virtualenv activated?

**Comment by RhaegarTargaryen55** [comment]
@Kunal614 i'm sorry to waste your time, but how do i check it? I'm not a programmer

**Comment by RhaegarTargaryen55** [comment]
@Kunal614 i hust googled it,

```
Last login: Sat Aug 29 04:07:50 on ttys000
NoOne:~ NoOne$ pip install virtualenv
Requirement already satisfied: virtualenv in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (20.0.31)
Requirement already satisfied: importlib-metadata<2,>=0.12; python_version < "3.8" in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from virtualenv) (1.7.0)
Requirement already satisfied: six<2,>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from virtualenv) (1.11.0)
Requirement already satisfied: distlib<1,>=0.3.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from virtualenv) (0.3.1)
Requirement already satisfied: filelock<4,>=3.0.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from virtualenv) (3.0.12)
Requirement already satisfied: appdirs<2,>=1.4.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from virtualenv) (1.4.4)
Requirement already satisfied: zipp>=0.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv) (3.1.0)
ERROR: Error while checking for conflicts. Please file an issue on pip's issue tracker: https://github.com/pypa/pip/issues/new
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2681, in version
    return self._version
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 535, in _determine_conflicts
    return check_install_conflicts(to_install)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 108, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 50, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2689, in version
    raise ValueError(msg, self)
ValueError: ("Missing 'Version:' header and/or METADATA file at path: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/-ip-19.0.1.dist-info/METADATA", Unknown [unknown version] (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages))
NoOne:~ NoOne$ cd documents
NoOne:documents NoOne$ cd instabot
NoOne:instabot NoOne$ virtualenv igbot
created virtual environment CPython3.7.1.final.0-64 in 382ms
  creator CPython3Posix(dest=/Users/NoOne/Documents/Instabot/igbot, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/NoOne/Library/Application Support/virtualenv)
    added seed packages: pip==20.2.2, setuptools==49.6.0, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
NoOne:instabot NoOne$ source igbot/bin/activate
(igbot) NoOne:instabot NoOne$ 
```

looks like it's activated?

**Comment by Kunal614** [comment]
so here run your .py file and make sure you must install selenium here

**Comment by RhaegarTargaryen55** [comment]
okay, is that correct?

```
(igbot) NoOne:instabot NoOne$ sudo pip install selenium
Password:
WARNING: The directory '/Users/NoOne/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting selenium
  Downloading selenium-3.141.0-py2.py3-none-any.whl (904 kB)
     |████████████████████████████████| 904 kB 553 kB/s 
Collecting urllib3
  Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 4.1 MB/s 
Installing collected packages: urllib3, selenium
Successfully installed selenium-3.141.0 urllib3-1.25.10
(igbot) NoOne:instabot NoOne$ 

```

and after that, please help me to understand which one .py file should i run? i been using mac_start.command (exactly like instruction says)

however i can download the .zip with the bot from here and there is quickstart.py, obviously i should run this one?
if so, where should i place the whole folder with the bot? ar 'igbot' folder i just created with virtualenv? in my case it's ‎⁨Macintosh HD⁩ ▸ ⁨Users⁩ ▸ ⁨NoOne⁩ ▸ ⁨Documents⁩ ▸ ⁨Instabot⁩

**Comment by Kunal614** [comment]
the file in which you are geeting this error run that file.

**Comment by RhaegarTargaryen55** [comment]
@Kunal614 somehow I re-downloaded the bot and now everything works, thanks for your help brother!

**Comment by Kunal614** [comment]
Welcome always brother :)
