### ISSUE TITLE
not a run show some error

### ISSUE THREAD

**Issue by shubham6664** [InstaPy/InstaPy#5706]
InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/Hp/InstaPy"
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\quickstart.py", line 30, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\instapy.py", line 312, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\browser.py", line 120, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\browser.py", line 36, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 225, in download_and_install
    shutil.copy2(src_file, dest_file)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Hp\\InstaPy\\assets\\geckodriver.exe'
>>>

**Comment by Khumoyun098** [comment]
Are you admin of your pc?

**Comment by ERR999R** [comment]
same problem here
