### ISSUE TITLE
Session ended in less than 1 hour

### ISSUE THREAD

**Issue by jjpoc** [InstaPy/InstaPy#5719]
**selenium.common.exceptions.JavascriptException: Message: TypeError: document.getElementsByClassName(...)[0] is undefined**

What is it now, Session ended in less than 1 hour by one error.
What can I do to catch the Class correcty? Please Help me! 

INFO [2020-08-11 11:24:36] [simplifica_estudos]  Sessional Live Report:
        |> LIKED 4 images  |  ALREADY LIKED: 0
        |> COMMENTED on 4 images
        |> FOLLOWED 8 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 31 users
        |> LIKED 0 comments
        |> REPLIED to 0 comments
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
        |> WATCHED 0 story(ies)  |  WATCHED 0 reel(s)

On session start was FOLLOWING 114 users & had 29 FOLLOWERS
[Session lasted 58.73 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-08-11 11:24:36] [simplifica_estudos]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "C:\Users\Win 8.1\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\util.py", line 976, in click_element
    element.click()
  File "C:\Users\Win 8.1\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Win 8.1\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Win 8.1\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Win 8.1\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <span class=""> is not clickable at point (28,667) because another element <a class="gKAyB " href="/"> obscures it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/Win 8.1/Desktop/instapy-quickstart-master/quickstart_templates/simple_but_effective.py", line 52, in <module>
    interact=True, sleep_delay=240)
  File "C:\Users\Win 8.1\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\instapy.py", line 3466, in follow_user_followers
    person, self.follow_times, sleep_delay, interact
  File "C:\Users\Win 8.1\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\instapy.py", line 1226, in follow_by_list
    self.user_interact_media,
  File "C:\Users\Win 8.1\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\instapy.py", line 2518, in interact_by_users
    total_liked_img,
  File "C:\Users\Win 8.1\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\like_util.py", line 758, in like_image
    click_element(browser, like_elem[0])
  File "C:\Users\Win 8.1\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\util.py", line 990, in click_element
    + "')[0].scrollIntoView({ inline: 'center' });"
  File "C:\Users\Win 8.1\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Win 8.1\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Win 8.1\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
**selenium.common.exceptions.JavascriptException: Message: TypeError: document.getElementsByClassName(...)[0] is undefined**

**Comment by stexdev** [comment]
Same error here, any news? I'm running on Ubuntu. The error appears at random moments, I can't identify where is the problem.

**Comment by jjpoc** [comment]
That's Correct sfncrp. Help Us PLEASE!

**Comment by stexdev** [comment]
Still unusable. The quickstart script starts, but after few minutes it crashes. Any ideas?

File "/home/user/pyenvs/instagram/lib/python3.6/site-packages/instapy/util.py", line 990, in click_element
    + "')[0].scrollIntoView({ inline: 'center' });"
  File "/home/user/pyenvs/instagram/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/user/pyenvs/instagram/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/suser/pyenvs/instagram/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: document.getElementsByClassName(...)[0] is undefined

**Comment by stexdev** [comment]
`selenium.common.exceptions.ElementClickInterceptedException: Message: Element <span class=""> is not clickable at point (28,656) because another element <a class="gKAyB Wn8y-" href="/"> obscures it`

Is it possible that the popup of the home icon counter obscures the like button, and so the program crashes ?
Observing the browser at work, seems this may occur.

**Comment by marianopela** [comment]
Don't use a headless browser and increase the windows size

**Comment by metapodcod** [comment]
does anyone have any idea what exactly we should do ?

**Comment by gabriel-lemelle** [comment]
You need to update line 139 in browser.py to: browser.set_window_size(375, 896)
or set headless_browser = "false".
However if you're using docker not sure how to do this ...

**Comment by metapodcod** [comment]
is ending the session even though I do these @Gabyheavy

**Comment by gabriel-lemelle** [comment]
@timgrossmann I noticed there are 3 open issues similar as this bug, are you not experiencing this ?
