### ISSUE TITLE
InstaPy don't start

### ISSUE THREAD

**Issue by marlon33** [InstaPy/InstaPy#5729]
## Expected Behavior
Connection with instagram 
## Current Behavior
```
C:\Bots>insta.py
InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Marlon/InstaPy"
Traceback (most recent call last):
  File "C:\Bots\insta.py", line 24, in <module>
    session = InstaPy(username=insta_username,password=insta_password,browser_ex
ecutable_path=browser_ff)
  File "C:\Bots\instapy\instapy.py", line 323, in __init__
    self.logger,
  File "C:\Bots\instapy\browser.py", line 89, in set_selenium_local_session
    firefox_profile = webdriver.FirefoxProfile()
  File "C:\Users\Marlon\AppData\Local\Programs\Python\Python37\lib\site-packages
\selenium-4.0.0a6.post2-py3.7.egg\selenium\webdriver\firefox\firefox_profile.py"
, line 59, in __init__
    WEBDRIVER_PREFERENCES)) as default_prefs:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Marlon\\AppD
ata\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium-4.0.0a6.pos
t2-py3.7.egg\\selenium\\webdriver\\firefox\\webdriver_prefs.json'
```
## Possible Solution (optional)
I don't know
## InstaPy configuration
only downloaded isntapy and quickstart and execute
```

# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username='User Instagram'
insta_password='Pass Instagram'
browser_ff=r"C:\Program Files\Mozilla Firefox\firefox.exe"

comments = ['Nice shot! @{}',
        'I love your profile! @{}',
        'Your feed is an inspiration :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Getting inspired by you @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:']

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
# headless_browser=False
session = InstaPy(username=insta_username,password=insta_password,browser_executable_path=browser_ff)
session.login()
with smart_run(session):
  """ Activity flow """		
  # general settings		
  session.set_dont_include(["friend1", "friend2", "friend3"])		
  
  # activity		
  session.like_by_tags(["natgeo"], amount=10)

  # Joining Engagement Pods
  session.set_do_comment(enabled=True, percentage=35)
  session.set_comments(comments)
  session.join_pods(topic='sports', engagement_mode='no_comments')
```

**Comment by LeydenJar** [comment]
have you installed the requirements?? You have to go to run this on the instapy directory:

`pip install -r requirements.txt`

once you make progress , you can check this out -> https://github.com/timgrossmann/InstaPy/issues/5672

then it should work

**Comment by marlon33** [comment]
> have you installed the requirements?? You have to go to run this on the instapy directory:
> 
> `pip install -r requirements.txt`
> 
> once you make progress , you can check this out -> #5672
> 
> then it should work

Yes, of course, i do this before the installation, now,
my pip list, i saw in discord, somethings about geckodriver, but i don't know how to install this
```
C:\Bots\InstaPy-master>pip list
Package                   Version
------------------------- -----------
altgraph                  0.17
apipkg                    1.5
astroid                   2.3.3
atomicwrites              1.4.0
attrs                     19.3.0
auto-py-to-exe            2.6.6
beautifulsoup4            4.9.1
bottle                    0.12.18
bottle-websocket          0.2.9
certifi                   2019.11.28
cffi                      1.14.0
chardet                   3.0.4
clarifai                  2.6.2
click                     7.1.1
colorama                  0.4.3
configparser              5.0.0
contextlib2               0.6.0.post1
cryptography              3.0
Cython                    0.29.7
decorator                 4.4.2
easyprocess               0.3
Eel                       0.11.0
emoji                     0.6.0
esky                      0.9.9
execnet                   1.7.1
future                    0.18.2
geckodriver-autoinstaller 0.1.0
gevent                    1.4.0
gevent-websocket          0.10.1
googleapis-common-protos  1.52.0
greenlet                  0.4.15
grpcio                    1.31.0
idna                      2.9
importlib-metadata        1.7.0
iniconfig                 1.0.1
instapy                   0.1.1
instapy-chromedriver      2.44
iqoptionapi               6.8.9.1
isort                     4.3.21
jsonschema                2.6.0
lazy-object-proxy         1.4.3
mccabe                    0.6.1
meaningcloud-python       1.2.2
mock                      4.0.2
more-itertools            8.4.0
numpy                     1.16.2
packaging                 20.4
path                      15.0.0
path.py                   12.5.0
pefile                    2017.9.3
pip                       20.2.2
pluggy                    0.13.1
plyer                     1.4.3
protobuf                  4.0.0rc2
psutil                    5.7.2
py                        1.9.0
pycparser                 2.20
PyInstaller               3.6
pylint                    2.4.4
pyOpenSSL                 19.1.0
pyparsing                 2.4.7
PyQt5                     5.13.0
PyQt5-sip                 12.7.2
pyqt5-tools               5.13.0.1.5
PySide2                   5.14.2
PySimpleGUI               4.16.0
pytest                    6.0.1
pytest-shutil             1.7.0
python-dateutil           2.8.1
python-dotenv             0.12.0
python-telegram-bot       12.8
pytz                      2020.1
PyVirtualDisplay          1.3.2
pywin32-ctypes            0.2.0
pyyaml                    5.3.1
regex                     2020.7.14
requests                  2.23.0
schedule                  0.6.0
selenium                  4.0.0a6.pos
setuptools                49.2.1
shiboken2                 5.14.2
six                       1.14.0
soupsieve                 2.0.1
spark-parser              1.6.1
TA-Lib                    0.4.17
termcolor                 1.1.0
toml                      0.10.1
tornado                   6.0.4
tqdm                      4.48.2
typed-ast                 1.4.1
uncompyle6                2.11.5
unpy2exe                  0.3
urllib3                   1.25.8
webdriverdownloader       1.1.0.3
websocket-client          0.56.0
wheel                     0.34.2
whichcraft                0.6.1
wrapt                     1.11.2
xdis                      3.5.5
zipp                      3.1.0
```

**Comment by nikhil-swamix** [comment]
What worked for me...
`pip uninstall selenium && pip install selenium --upgrade`

it resetted my selenium env and pyinsta started to work again... luckily...
