### ISSUE TITLE
am no coding expert but I think a ship load of errors in this ?! HELP

### ISSUE THREAD

**Issue by GharaibehR** [InstaPy/InstaPy#5754]
Traceback (most recent call last):
  File "../quickstart.py", line 33, in <module>
    with smart_run(session):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/ramigharaibeh/Library/Python/2.7/lib/python/site-packages/instapy/util.py", line 1662, in smart_run
    session.login()
  File "/Users/ramigharaibeh/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 373, in login
    self.bypass_with_mobile):
  File "/Users/ramigharaibeh/Library/Python/2.7/lib/python/site-packages/instapy/login_util.py", line 204, in login_user
    "//article//a[text()='Log in']")
  File "/Users/ramigharaibeh/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/ramigharaibeh/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/ramigharaibeh/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/ramigharaibeh/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//article//a[text()='Log in']"}
  (Session info: chrome=85.0.4183.83)
  (Driver info: chromedriver=2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5),platform=Mac OS X 10.15.6 x86_64)

**Comment by zubus** [comment]
Hi, install python3

**Comment by Kunal614** [comment]
Check your xpath
//article//a[text()='Log in']

**Comment by GharaibehR** [comment]
> Hi, install python3

I have installed python3 but instapy still runs 2.7

**Comment by GharaibehR** [comment]
> Check your xpath
> //article//a[text()='Log in']

Thats what I have in my xpath

"login_elem_no_such_exception": "//a[text()='Log in']",
    "login_elem_no_such_exception_2": "//div[text()='Log In']",
    "nav": "//nav",

still no luck

**Comment by limberger** [comment]
How do you run Instapy?
