### ISSUE TITLE
cant run Instapy

### ISSUE THREAD

**Issue by valikaovalikao** [InstaPy/InstaPy#5759]
**Hello please help me with this issue 
I dont have big computer skill** 
I have a latest Firefox instlled and gecko driver is in instapy folder 

InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/valentin/InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\valentin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 312, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\valentin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 121, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\valentin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\valentin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\valentin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\valentin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\valentin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Press any key to continue . . .

**Comment by l7xn** [comment]
I need haak insta Please🥺

**Comment by BerkSpar** [comment]
I'm having the same issue

```
InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Felipe Passos/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\Felipe Passos\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 312, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\Felipe Passos\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 121, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\Felipe Passos\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Felipe Passos\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Felipe Passos\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Felipe Passos\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Felipe Passos\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

**Comment by joebyjo** [comment]
same prob here aswell ,does it hve anything to do with insta not allowing APIs or something like tht?im a complete beginner are coding so i may be wrong.

**Comment by BerkSpar** [comment]
I solve the issue installing mozilla firefox and downloading lastest geckodriver and putting in the same folder of the script

**Comment by danieltoro** [comment]
same error here on MacOS

**Comment by Percival450** [comment]
same problem here, berkspar could you try to explain it a little bit more accurate for me? (a coding beginner sry)

**Comment by elulcao** [comment]
> same error here on MacOS
Running fine with Firefox 
`80.0.1 (64-bit)`

Python:
```
(venv) ➜  InstaPy git:(master) python --version
Python 3.8.2
```

**Comment by BerkSpar** [comment]
@Percival450 I just downloaded geckodriver on [official mozila repo](https://github.com/mozilla/geckodriver/releases) and put on the folder that a ran my script.

**Comment by Maghil** [comment]
shouldn't they make a option to use other browsers?,driver manager is really useful when it comes to this(takes care of driver)

**Comment by roberterzen** [comment]
If any of you experiencing this problem uses geckodriver 0.27.0 check this out
https://github.com/timgrossmann/InstaPy/issues/5779#issuecomment-702411953
