### ISSUE TITLE
i have tried running instapy, but it works for few mins and then this occurs, HELP !!!

### ISSUE THREAD

**Issue by sauravsemwal** [InstaPy/InstaPy#5766]
Traceback (most recent call last):
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 976, in click_element
    element.click()
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="_5f5mN       jIbKX  _6VtSN      _3yx3p  "> is not clickable at point (220,141) because another element <div class="W1Bne  zKxRE  "> obscures it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 976, in click_element
    element.click()
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="_5f5mN       jIbKX  _6VtSN      _3yx3p  "> is not clickable at point (220,14) because another element <h1 class="K3Sf1"> obscures it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 976, in click_element
    element.click()
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN      _3yx3p  "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 976, in click_element
    element.click()
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN      _3yx3p  "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simple_but_effective.py", line 52, in <module>
    interact=True, sleep_delay=240)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 3466, in follow_user_followers
    person, self.follow_times, sleep_delay, interact
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 1193, in follow_by_list
    self.logfolder,
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\unfollow_util.py", line 611, in follow_user
    browser, "follow", track, login, user_name, None, logger, logfolder
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\unfollow_util.py", line 1555, in verify_action
    click_visibly(browser, follow_button)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 1928, in click_visibly
    click_element(browser, element)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 1026, in click_element
    click_element(browser, element, tryNum)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 1026, in click_element
    click_element(browser, element, tryNum)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 1026, in click_element
    click_element(browser, element, tryNum)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\util.py", line 1009, in click_element
    + "')[0].click()"
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 141, in get_attribute
    self, name)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\saurav\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN      _3yx3p  "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

C:\Users\saurav\Downloads\InstaPy-master\InstaPy-master\instapy-quickstart-master\quickstart_templates>

**Comment by filiperivelli** [comment]
Same issue here.

**Comment by filiperivelli** [comment]
Here I solved this issue maximizing the browser.

**Comment by Lxand3r** [comment]
> Here I solved this issue maximizing the browser.

Hi im having the same issue I maximized the browser at line 139 in browser.py to 375 by 896 are those your settings
