### ISSUE TITLE
Problem whit  Error...  Issue with cookie for user .... Creating new cookie...

### ISSUE THREAD

**Issue by Polkyanik** [InstaPy/InstaPy#5777]
## Expected Behavior
InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-09-12 17:15:09] [..........]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-09-12 17:15:09] [..........]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-09-12 17:15:10] [..........]  - Internet Connection Status: ok
INFO [2020-09-12 17:15:10] [..........]  - Current IP is "..........." and it's from "Italy/IT"
INFO [2020-09-12 17:15:10] [..........] -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-09-12 17:15:10] [..........] - window.navigator.webdriver response: None
INFO [2020-09-12 17:15:10] [[..........] - Hide Selenium Extension: ok
Issue with cookie for user [..........]. Creating new cookie...
Traceback (most recent call last):
  File "/home/pi/pippo.py", line 845, in <module>
    schedule.run_pending()
  File "/home/pi/.local/lib/python3.7/site-packages/schedule/__init__.py", line 563, in run_pending
    default_scheduler.run_pending()
  File "/home/pi/.local/lib/python3.7/site-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/home/pi/.local/lib/python3.7/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/home/pi/.local/lib/python3.7/site-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
  File "/home/pi/pippo.py", line 739, in unfollow
    session.login()
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 415, in login
    self.want_check_browser,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/login_util.py", line 297, in login_user
    (ActionChains(browser).move_to_element(login_elem).click().perform())
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.sendMouseEvent]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://marionette/content/event.js :: event.synthesizeMouseAtPoint :: line 184"  data: no]
## Possible Solution (optional)
i've also encountered this issue. Happens occasionaly
do you have any solution?

## InstaPy configuration
Raspberry Pi 4
InstaPy Version: 0.6.10
Mozilla Firefox 68.12.0esr
geckodriver 0.23.0 ( 2018-10-04)
python3.7
selenium (1.24.1)

**Comment by sakarimov** [comment]
i got the same error, and the session was ended before take any action after creating new cookie

**InstaPy configuration**

Ubuntu 20.04
Latest version of InstaPy
Mozilla Firefox 80.0.1
geckodriver 0.26.0
python 3.8
selenium 3.141.0

**Comment by dpetrov** [comment]
+1:

Raspberry Pi 4
InstaPy Version: 0.6.10
geckodriver 0.27.0 ( 2020-08-26)
Mozilla Firefox 68.12.0esr
Python 3.7.3

**Comment by Polkyanik** [comment]
@timgrossmann 
I can't find a solution; (

**Comment by Polkyanik** [comment]
I updated with the new files and now it is

Cookie file not found, creating cookie...
INFO [2020-09-25 14:14:32] [----------]  Timed out with failure while explicitly waiting until title contains 'Login' string!
INFO [2019-10-13 18:40:54] [----------]   Timed out with failure while explicitly waiting until visibility of element located!
Traceback (most recent call last):
File "/home/pi/pippo.py", line 845, in
schedule.run_pending()
.
.
.

**Comment by Polkyanik** [comment]
I updated with the new files and now it is

Cookie file not found, creating cookie...
INFO [2020-09-25 14:14:32] [----------] Timed out with failure while explicitly waiting until title contains 'Login' string!
INFO [2020-09-25 14:14:32] [----------] Timed out with failure while explicitly waiting until visibility of element located!
Traceback (most recent call last):
File "/home/pi/pippo.py", line 845, in
schedule.run_pending()
.
.
.

**Comment by kbakdev** [comment]
So what about this error? I also have it on raspberry.
