### ISSUE TITLE
I cant find a solution, instapy wont start

### ISSUE THREAD

**Issue by Skorp00** [InstaPy/InstaPy#5778]
## Expected Behavior
should start
## Current Behavior
it gives me those errors:
`
InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/spammyboy420/InstaPy"
Error, unable to determine correct filename for 64bit linux
Traceback (most recent call last):
  File "ez.py", line 32, in <module>
    headless_browser=True)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/instapy/instapy.py", line 323, in __init__
    self.logger,
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/instapy/browser.py", line 120, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/instapy/browser.py", line 36, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/webdriverdownloader/webdriverdownloader.py", line 177, in download_and_install
    show_progress_bar=show_progress_bar)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit linux
`

those are my configs:
`# imports
from instapy import InstaPy
from instapy import smart_run

geckodriver_path = "/home/geckodriver"

insta_username = 'veryconvincingusername'
insta_password = 'truepasswordipromise'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                    min_followers=45,
                                    min_following=77)
    session.set_dont_include(["blablabla"])
    session.set_dont_like(["pizza", "#store"])

    # activities

  
    session.follow_user_followers(['blabla2'], amount=800,
                                  randomize=False, interact=False)

    """ First step of Unfollow action - Unfollow not follower users...
    """
    session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=601)

    """ Second step of Massive Follow...
    """
    session.follow_user_followers(['blablabla'], amount=800,
                                  randomize=False, interact=False)

    """ Second step of Unfollow action - Unfollow not follower users...
    """
    session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=601)

    """ Clean all followed user - Unfollow all users followed by InstaPy...
    """
    session.unfollow_users(amount=500, InstapyFollowed=(True, "all"),
                           style="FIFO", unfollow_after=24 * 60 * 60,
                           sleep_delay=601)`

I tried to manually download the geckodriver from here [https://github.com/mozilla/geckodriver/releases](url) (the linux64bit version of course) and added `geckodriver_path = "/home/geckodriver"` to my configs but still doesnt work.

I also tried, before adding the geckodriver path manually, to fix the 320th line of the webdriver.py . But didnt work.
## Possible Solution (optional)
idk
## InstaPy configuration
im running on ubuntu 18.04 64bit on a e2machine from google cloud

**Comment by Skorp00** [comment]
maybe its more understandable like this:

InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/spammyboy420/InstaPy"
Error, unable to determine correct filename for 64bit linux
Traceback (most recent call last):
  File "ez.py", line 32, in <module>
    headless_browser=True)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/instapy/instapy.py", line 323, in __init__
    self.logger,
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/instapy/browser.py", line 120, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/instapy/browser.py", line 36, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/webdriverdownloader/webdriverdownloader.py", line 177, in download_and_install
    show_progress_bar=show_progress_bar)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit linux

**Comment by elulcao** [comment]
Looks similar to #5282 
could you try: `sudo apt install firefox-geckodriver`, assuming you are using ubuntu.

**Comment by Skorp00** [comment]
> Looks similar to #5282
> could you try: `sudo apt install firefox-geckodriver`, assuming you are using ubuntu.

I've tried what u say with this config [https://github.com/InstaPy/instapy-quickstart/blob/master/quickstart.py](url) but still ...


InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/spammyboy420/InstaPy"
Traceback (most recent call last):
  File "1.py", line 24, in <module>
    headless_browser=True)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/instapy/instapy.py", line 323, in __init__
    self.logger,
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/instapy/browser.py", line 124, in set_selenium_local_
session
    options=firefox_options,
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, i
n __init__
    keep_alive=True)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in
 __init__
    self.start_session(capabilities, browser_profile)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in
 start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in
 execute
    self.error_handler.check_response(response)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242,
 in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

**Comment by hero1ine** [comment]
Hi! You need to make changes in one file..

like [this](https://github.com/leonidessaguisagjr/webdriverdownloader/pull/12/commits/a47a57c3a3ff20d81178989149946b6c128d46c8)

Typical path to file: 

> /home/user/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py

Change string №320:

`filename = [name for name in filenames if os_name + bitness in name]`

to

`filename = [name for name in filenames if os_name + bitness in name and name[-3:] != 'asc' ]`

**Comment by Skorp00** [comment]
> Hi! You need to make changes in one file..
> 
> like [this](https://github.com/leonidessaguisagjr/webdriverdownloader/pull/12/commits/a47a57c3a3ff20d81178989149946b6c128d46c8)
> 
> Typical path to file:
> 
> > /home/user/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py
> 
> Change string №320:
> 
> `filename = [name for name in filenames if os_name + bitness in name]`
> 
> to
> 
> `filename = [name for name in filenames if os_name + bitness in name and name[-3:] != 'asc' ]`





And now those errors:



 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/spammyboy420/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2020-09-15 10:56:03] [xxxx]  Using built in instapy-chromedriver executable (version 2.46)
ERROR [2020-09-15 10:56:05] [xxxx]  Message: session not created: This version of ChromeDriver only supports Chrome version 76
Traceback (most recent call last):
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/instapy/browser.py", line 163, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 76

Traceback (most recent call last):
  File "1.py", line 24, in <module>
    headless_browser=True)
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/instapy/instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "/home/spammyboy420/.local/lib/python3.6/site-packages/instapy/instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /home/spammyboy420/.local/lib/python3.6/site-packages/instapy_chromedriver/chromedriver_linux64



Also if u dont find `webdriverdownloader.py` you can type `pip show webdriverdownloader` to show the location and if it gives you this error `WARNING: Package(s) not found: webdriverinstaller`
you can install it with this `pip install webdriverdownloader`

**Comment by Skorp00** [comment]
ok so i fixed it by removing the current google chrome version on my server 
`sudo apt-get purge google-chrome-stable`
`sudo apt-get autoremove`

and then downloading from here [https://www.slimjet.com/chrome/google-chrome-old-version.php](url) the version 76 and installing it
`wget https://www.slimjet.com/chrome/download-chrome.php?file=files%2F76.0.3809.100%2Fgoogle-chrome-stable_current_amd64.deb`

`sudo dpkg -i 'download-chrome.php?file=files%2F76.0.3809.100%2Fgoogle-chrome-stable_current_amd64.deb' (or yourfilename)`

`sudo apt-get -f install`
you can check the version with this command
`google-chrome --version`

then i remove the autoupdate of chrome
`cd /etc/apt/sources.list.d`
`mv google-chrome.list google-chrome.list.save`

**Comment by Skorp00** [comment]
Now this LMAO


 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/spammyboy420/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2020-09-15 12:13:40] []  Using built in instapy-chromedriver executable (version 2.46)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-09-15 12:13:41] []  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2020-09-15 12:13:41] []  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-09-15 12:13:42] []  - Internet Connection Status: ok
INFO [2020-09-15 12:13:42] []  -- Connection Checklist [2/2] (Instagram Server Status)
INFO [2020-09-15 12:13:45] []  - Instagram WebSite Status: Currently Up 
INFO [2020-09-15 12:13:45] []  - Instagram Response Time: 115.942 ms 
INFO [2020-09-15 12:13:45] []  - Instagram Reponse Code: 200
INFO [2020-09-15 12:13:45] []  - Instagram Server Status: ok
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

.............................................................................................................................
CRITICAL [2020-09-15 12:14:00] []  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2020-09-15 12:14:00] []  Sessional Live Report:
        |> No any statistics to show


[Session lasted 20.12 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-09-15 12:14:00] []  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by cosmicwanderer7** [comment]
._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/HYDRA/InstaPy"
Traceback (most recent call last):
  File "C:/Users/HYDRA/PycharmProjects/untitled1/insta.py", line 3, in <module>
    session: InstaPy = InstaPy(username="anime.fever.in", password="*****", headless_browser=True, disable_image_load=True)
  File "C:\Users\HYDRA\PycharmProjects\untitled1\venv\lib\site-packages\instapy\instapy.py", line 312, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\HYDRA\PycharmProjects\untitled1\venv\lib\site-packages\instapy\browser.py", line 128, in set_selenium_local_session
    browser.install_addon(create_firefox_extension(), temporary=True)
  File "C:\Users\HYDRA\PycharmProjects\untitled1\venv\lib\site-packages\instapy\browser.py", line 46, in create_firefox_extension
    with zipfile.ZipFile(zip_file, "w", zipfile.ZIP_DEFLATED, False) as zipf:
  File "C:\Users\HYDRA\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1250, in __init__
    self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\HYDRA\\InstaPy\\assets\\extension.xpi'

**Comment by cosmicwanderer7** [comment]
> Now this LMAO
> 
> ._. ._. ._. ._. ._. ._. ._. ._. ._. ._.
> Workspace in use: "/home/spammyboy420/InstaPy"
> 
> ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._.
> INFO [2020-09-15 12:13:40] [] Using built in instapy-chromedriver executable (version 2.46)
> 
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2020-09-15 12:13:41] [] Session started!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooo
> 
> INFO [2020-09-15 12:13:41] [] -- Connection Checklist [1/2] (Internet Connection Status)
> INFO [2020-09-15 12:13:42] [] - Internet Connection Status: ok
> INFO [2020-09-15 12:13:42] [] -- Connection Checklist [2/2] (Instagram Server Status)
> INFO [2020-09-15 12:13:45] [] - Instagram WebSite Status: Currently Up
> INFO [2020-09-15 12:13:45] [] - Instagram Response Time: 115.942 ms
> INFO [2020-09-15 12:13:45] [] - Instagram Reponse Code: 200
> INFO [2020-09-15 12:13:45] [] - Instagram Server Status: ok
> Cookie file not found, creating cookie...
> Login A/B test detected! Trying another string...
> 
> .............................................................................................................................
> CRITICAL [2020-09-15 12:14:00] [] Unable to login to Instagram! You will find more information in the logs above.
> '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> 
> INFO [2020-09-15 12:14:00] [] Sessional Live Report:
> |> No any statistics to show
> 
> [Session lasted 20.12 seconds]
> 
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2020-09-15 12:14:00] [] Session ended!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

try running headless

**Comment by sticksX2** [comment]
Traceback (most recent call last):
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\quickstart.py", line 15, in <module>
    from instapy import InstaPy
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\instapy.py", line 30, in <module>
    from .clarifai_util import check_image
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\clarifai\rest\__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\clarifai\rest\client.py", line 36, in <module>
    from clarifai.rest.grpc.proto.clarifai.api.endpoint_pb2_grpc import V2Stub
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\clarifai\rest\grpc\proto\clarifai\api\endpoint_pb2_grpc.py", line 2, in <module>
    import grpc
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\grpc\__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
  File "src\python\grpcio\grpc\_cython\cygrpc.pyx", line 27, in init grpc._cython.cygrpc
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\asyncio\__init__.py", line 21, in <module>
    from .base_events import *
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\asyncio\base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^
SyntaxError: invalid syntax
>>>
