### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by izimizi69** [InstaPy/InstaPy#5780]
Hello im new at git and instapy for general i watched a yt video and i saw that he created a quickstart.py with a template i did it too but when i run it it says me this

Traceback (most recent call last):
  File "C:\Users\User\Desktop\InstaPy-master\fcntl.py", line 28, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\User\Desktop\InstaPy-master\instapy\instapy.py", line 312, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\User\Desktop\InstaPy-master\instapy\browser.py", line 121, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

pls help

**Comment by hero1ine** [comment]
I have same.

You can fix it like this:

`path_to_browser = 'C:\\Program Files\\Mozilla Firefox\\firefox.exe'
session = InstaPy(username=insta_username, password=insta_password, browser_executable_path=path_to_browser)`

**Comment by Lxand3r** [comment]
> I have same.
> 
> You can fix it like this:
> 
> `path_to_browser = 'C:\\Program Files\\Mozilla Firefox\\firefox.exe' session = InstaPy(username=insta_username, password=insta_password, browser_executable_path=path_to_browser)`

where does this go ?

**Comment by x-raay** [comment]
@Lxand3r You can put this in `quickstart.py`. Thanks @hero1ine  for sharing.

**Comment by elulcao** [comment]
Check your `browser_executable_path` for FF.

instance-settings.md:
```python
### Choose the browser version
If you have more than one Firefox version on your system or if you are using a portable version you can instruct InstaPy to use that version using the `browser_executable_path` argument in the class initializer.

Specifying the Firefox executable path can also help you if you are getting the following error message:

`selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`

Example on a Windows machine (with the right path also works on Linux and macOS)

```python
session = InstaPy(username=insta_username,
                  password=insta_password,
                  browser_executable_path=r"D:\Program Files\Mozilla Firefox\firefox.exe")
```
```
