### ISSUE TITLE
Bot not working at all with docker-compose

### ISSUE THREAD

**Issue by wsdt** [InstaPy/InstaPy#5789]
See error log below (username and password are correct): 

```InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/code/InstaPyN"
2445kb [00:03, 754.76kb/s]
Traceback (most recent call last):
  File "docker_quickstart.py", line 19, in <module>
    bot = InstaPy(username=insta_username, password=insta_password, headless_browser=False)
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 323, in __init__
    self.logger,
  File "/usr/local/lib/python3.7/site-packages/instapy/browser.py", line 120, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/usr/local/lib/python3.7/site-packages/instapy/browser.py", line 36, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/usr/local/lib/python3.7/site-packages/webdriverdownloader/webdriverdownloader.py", line 215, in download_and_install
    os.symlink(symlink_src, symlink_target)
OSError: [Errno 71] Protocol error: '/code/InstaPyN/assets/gecko/v0.27.0/geckodriver-v0.27.0-linux64/geckodriver' -> '/code/InstaPyN/assets/geckodriver'
InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/code/InstaPyN"
Traceback (most recent call last):
  File "docker_quickstart.py", line 19, in <module>
    bot = InstaPy(username=insta_username, password=insta_password, headless_browser=False)
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 323, in __init__
    self.logger,
  File "/usr/local/lib/python3.7/site-packages/instapy/browser.py", line 120, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/usr/local/lib/python3.7/site-packages/instapy/browser.py", line 36, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/usr/local/lib/python3.7/site-packages/webdriverdownloader/webdriverdownloader.py", line 215, in download_and_install
    os.symlink(symlink_src, symlink_target)
OSError: [Errno 71] Protocol error: '/code/InstaPyN/assets/gecko/v0.27.0/geckodriver-v0.27.0-linux64/geckodriver' -> '/code/InstaPyN/assets/geckodriver'
```

**Comment by tg1482** [comment]
Hi, I'm having the same issue as this. Running the container on MacOS. Would appreciate any and all help here :) 
![Screen Shot 2021-05-10 at 12 46 37 AM](https://user-images.githubusercontent.com/31661606/117607052-2e178180-b129-11eb-9e6e-d501d2150168.png)
