### ISSUE TITLE
ModuleNotFoundError: No module named 'google.protobuf'

### ISSUE THREAD

**Issue by MiChaelinzo** [InstaPy/InstaPy#5798]
```
user@ubuntu:~$ sudo apt-get install google.protobuf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'ruby-google-protobuf' for regex 'google.protobuf'
ruby-google-protobuf is already the newest version (3.6.1.3-2ubuntu5).
The following packages were automatically installed and are no longer required:
  libfprint-2-tod1 libllvm9 linux-headers-5.4.0-26
  linux-headers-5.4.0-26-generic linux-image-5.4.0-26-generic
  linux-modules-5.4.0-26-generic linux-modules-extra-5.4.0-26-generic
  python3-click python3-colorama
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.

user@ubuntu:~$ pip3 install protobuf
Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (3.6.1)
user@ubuntu:~$ pip3 install google
Collecting google
  Downloading google-3.0.0-py2.py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 54 kB/s 
Requirement already satisfied: beautifulsoup4 in ./.local/lib/python3.8/site-packages (from google) (4.9.1)
Requirement already satisfied: soupsieve>1.2 in ./.local/lib/python3.8/site-packages (from beautifulsoup4->google) (2.0.1)
Installing collected packages: google
Successfully installed google-3.0.0
user@ubuntu:~$ pip3 install google-cloud
Collecting google-cloud
  Downloading google_cloud-0.34.0-py2.py3-none-any.whl (1.8 kB)
Installing collected packages: google-cloud
Successfully installed google-cloud-0.34.0
user@ubuntu:~$ pip3 install google.protobuf


user@ubuntu:~/Documents/InstaPy$ python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "/home/user/Documents/InstaPy/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/home/user/Documents/InstaPy/instapy/instapy.py", line 30, in <module>
    from .clarifai_util import check_image
  File "/home/user/Documents/InstaPy/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "/home/user/.local/lib/python3.8/site-packages/clarifai/rest/__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "/home/user/.local/lib/python3.8/site-packages/clarifai/rest/client.py", line 23, in <module>
    from google.protobuf.struct_pb2 import Struct
ModuleNotFoundError: No module named 'google.protobuf'

```

**Comment by xWHOISF** [comment]
I had the same problem and resolved by deleting and reinstalling it.

pip uninstall protobuf
pip uninstall google
pip install google
pip install protobuf
pip install google-cloud

FYI: if you're using pip version 3, try with this: pip3 uninstall or install....
