### ISSUE TITLE
Problems with browser after updating. OSError: [Errno 8] Exec format error.

### ISSUE THREAD

**Issue by dyakimchuk** [InstaPy/InstaPy#5823]
Hello! After updating today i'v started to get this error. Can anybody give me the idea of what could be wrong?

```

> InstaPy Version: 0.6.11
>  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
> Workspace in use: "/home/denys/InstaPy"
> Traceback (most recent call last):
>   File "_yakimchuk_like.py", line 13, in <module>
>     headless_browser=True)
>   File "/home/denys/.local/lib/python3.5/site-packages/instapy/instapy.py", line 333, in __init__
>     self.logger,
>   File "/home/denys/.local/lib/python3.5/site-packages/instapy/browser.py", line 130, in set_selenium_local_session
>     options=firefox_options,
>   File "/home/denys/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
>     self.service.start()
>   File "/home/denys/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 76, in start
>     stdin=PIPE)
>   File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> OSError: [Errno 8] Exec format error

```

**Comment by elulcao** [comment]
```bash
>   File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> OSError: [Errno 8] Exec format error
```
This means you are trying to run a version of geckodriver that is compiled for a different ARCH.

Check as reference:

```python
### Custom geckodriver
By default, InstaPy downloads the latest version of the geckodriver.
Unless you need a specific version of the geckodriver, you're ready to go.

You can manually download the geckodriver binary and put the path as an argument to the InstaPy contructor:

```python
session = InstaPy(..., geckodriver_path = '/path/to/binary', ...)
```
```
