### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by shua-ie** [InstaPy/InstaPy#5826]
## InstaPy configuration
:~/instapy-quickstart$ python3 quickstart.py
InstaPy Version: 0.6.11
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/jshmcdo/InstaPy"
Error, unable to determine correct filename for 64bit linux
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 321, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 125, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 37, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/home/jshmcdo/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/home/jshmcdo/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/home/jshmcdo/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit linux

**Comment by shua-ie** [comment]
running on ubuntu virtual box - python/pip/chrome installed correctly

**Comment by hijak** [comment]
#5672 might help you

**Comment by shua-ie** [comment]
Thanks!

**Comment by thursd4y** [comment]
When starting instapy manually on my raspberry everything works fine, but doing it via cronjob does not work.

I just tried both versions of the proposed script. Both then yield the new following error:
Traceback (most recent call last):
File "/home/pi/-/interact_plant.py", line 39, in
session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 333, in init
self.logger,
File "/home/pi/.local/lib/python3.7/site-packages/instapy/browser.py", line 130, in set_selenium_local_session
options=firefox_options,
File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in init
self.service.start()
File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
stdin=PIPE)
File "/usr/lib/python3.7/subprocess.py", line 775, in init
restore_signals, start_new_session)
File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/InstaPy/assets/geckodriver'

**Comment by thursd4y** [comment]
Found a fix, by moving everything to a bash script and adding: . /etc/profile to import environment vars.
