### ISSUE TITLE
quickstart

### ISSUE THREAD

**Issue by badmilk1991** [InstaPy/InstaPy#5827]
please help

Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\Bot instagram\InstaPy\quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "C:\Users\Usuario\Desktop\Bot instagram\InstaPy\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\Usuario\Desktop\Bot instagram\InstaPy\instapy\instapy.py", line 109
    username: str = None,
            ^
SyntaxError: invalid syntax
>>>

**Comment by elulcao** [comment]
SyntaxError, check instance-settings.md

ie:
```python
### Running on a Headless Browser

Use `headless_browser` parameter to run the bot via the CLI. Works great if running the scripts locally, or to deploy on a server. No GUI, less CPU intensive. [Example](http://g.recordit.co/BhEgXANLhJ.gif)

**Warning:** Some users discourage the use of this feature as Instagram could [detect](https://antoinevastel.com/bot%20detection/2017/08/05/detect-chrome-headless.html) this headless mode!

```python
session = InstaPy(username='test', password='test', headless_browser=True)
```
```
