### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by OnlyOneMoreHour** [InstaPy/InstaPy#5839]
## Expected Behavior

Run for some hours as does the same script on another VPS. Instapy files and changed to adress the new login page title and skip cookie request. This scripts runs on a Ubuntu 20 Server in a VM, the other one (that worked for 4.5 hours straight) on a ubuntu 18 vps.

## Current Behavior
Script is running and eventually cancels after 15 minutes 

INFO [2020-10-21 20:16:03] [accountname]  --> Image Liked!

INFO [2020-10-21 20:16:06] [accountname]  Sessional Live Report:
        |> LIKED 8 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 8 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> LIKED 0 comments
        |> REPLIED to 0 comments
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
        |> WATCHED 0 story(ies)  |  WATCHED 0 reel(s)

On session start was FOLLOWING 2931 users & had 8850 FOLLOWERS
[Session lasted 14.79 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-10-21 20:16:06] [accountname]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "start_wtv.py", line 275, in <module>
    interact=True)
  File "/home/user1/.local/lib/python3.6/site-packages/instapy/instapy.py", line 3491, in follow_user_followers
    person, self.follow_times, sleep_delay, interact
  File "/home/user1/.local/lib/python3.6/site-packages/instapy/instapy.py", line 1242, in follow_by_list
    self.user_interact_media,
  File "/home/user1/.local/lib/python3.6/site-packages/instapy/instapy.py", line 2585, in interact_by_users
    self.logfolder,
  File "/home/user1/.local/lib/python3.6/site-packages/instapy/comment_util.py", line 462, in process_comments
    logfolder,
  File "/home/user1/.local/lib/python3.6/site-packages/instapy/comment_util.py", line 67, in comment_image
    rand_comment = random.choice(comments).format(username)
IndexError: tuple index out of range
user1@myvps:~$ python3 start.py^C
user1@myvps:~$
user1@myvps:~$ Traceback (most recent call last):
-bash: syntax error near unexpected token `most'
user1@myvps:~$   File "start.py", line 275, in <module>
-bash: syntax error near unexpected token `newline'
user1@myvps:~$     interact=True)
-bash: syntax error near unexpected token `)'
user1@myvps:~$   File "/home/user1/.local/lib/python3.6/site-packages/instapy/instapy.py", line 3491, in follow_user_followers

Code from my script around like 275

`    # FOLLOW+INTERACTION on TARGETED accounts
    """ Select users form a list of a predefined targets...
    """
    number = random.randint(3, 5)
    random_targets = targets

    if len(targets) <= number:
        random_targets = targets

    else:
        random_targets = random.sample(targets, number)

    """ Interact with the chosen targets...
    """
    session.follow_user_followers(random_targets,
                                  amount=random.randint(30, 60),
                                  randomize=True, sleep_delay=600,
                                  interact=True)

    # UNFOLLOW activity
    """ Unfollow nonfollowers after one day...
    """
    session.unfollow_users(amount=random.randint(75, 100),
                           nonFollowers=True,
                           style="FIFO",
                           unfollow_after=24 * 60 * 60, sleep_delay=600)

    """ Unfollow all users followed by InstaPy after one week to keep the 
    following-level clean...
    """
    session.unfollow_users(amount=random.randint(75, 100),
                           allFollowing=True,
                           style="FIFO",
                           unfollow_after=168 * 60 * 60, sleep_delay=600)`

**Comment by OnlyOneMoreHour** [comment]
Problem solved, did not separate the comments I wanted to post by a comma ;)
