### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by rafo** [InstaPy/InstaPy#5842]
When I try to run my code it seems to go fine for a while (around 40mins), and then I get this error:

`Traceback (most recent call last):
  File "/Users/rafael/Documents/Projects/InstaPySimon/InstagramSimonSetup.py", line 92, in <module>
    session.unfollow_users(amount=500, instapy_followed_enabled=True, instapy_followed_param="all", style="RANDOM", unfollow_after=12 * 60 * 60, sleep_delay=501)
  File "/Users/rafael/.pyenv/versions/3.8.1/lib/python3.8/site-packages/instapy/instapy.py", line 2001, in like_by_tags
    success = process_comments(
File "/Users/rafael/.pyenv/versions/3.8.1/lib/python3.8/site-packages/instapy/comment_util.py", line 456, in process_comments
    comment_state, msg = comment_image(
File "/Users/rafael/.pyenv/versions/3.8.1/lib/python3.8/site-packages/instapy/comment_util.py", line 67, in comment_image
    rand_comment = random.choice(comments).format(username)
IndexError: Replacement index 1 out of range for positional args tuple`

## InstaPy configuration
`    # FOLLOW
   session.set_do_follow(enabled=True, percentage=80, times=1)
    session.unfollow_users(amount=500, instapy_followed_enabled=True, instapy_followed_param="all", style="RANDOM", unfollow_after=12 * 60 * 60, sleep_delay=501)
`

I tried RANDOM and FIFO but it produces the same error...

**Comment by elulcao** [comment]
Not reproducible with latest commit,
please create a new issue if still reproducible.
