### ISSUE TITLE
confused on what is causing this

### ISSUE THREAD

**Issue by stankyman** [InstaPy/InstaPy#5857]
Traceback (most recent call last):
  File "C:\Users\james\Pictures\target_followers_of_similar_accounts_and_influencers.py", line 51, in <module>
    multi_logs=True)
  File "C:\Users\james\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 335, in __init__
    geckodriver_log_level,
  File "C:\Users\james\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 131, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\james\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "C:\Users\james\AppData\Local\Programs\Python\Python37-32\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 195, in download_and_install
    with zipfile.ZipFile(os.path.join(self.get_download_path(version), filename), mode="r") as driver_zipfile:
  File "C:\Users\james\AppData\Local\Programs\Python\Python37-32\lib\zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "C:\Users\james\AppData\Local\Programs\Python\Python37-32\lib\zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by stankyman** [comment]
had to add gecko to PATH oops
