### ISSUE TITLE
Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.sendMouseEvent]

### ISSUE THREAD

**Issue by SanielDous** [InstaPy/InstaPy#5867]
## Expected Behavior
The script should login to my account.

## Current Behavior
When running the script it outputs `Issue with cookie for user my.account. Creating new cookie...` and crash. This does not happen every session so it may not be caused by the script itself. So far I could not find any correlating issue. And since this issue only occurs occasionally I have no description how to reproduce it.

Here are the logs of a failed session:

```
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-11-03 10:34:55] [my.account]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-11-03 10:35:02] [my.account]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-11-03 10:35:02] [my.account]  - Internet Connection Status: ok
INFO [2020-11-03 10:35:02] [my.account]  - Current IP is "123.456.789.0" and it's from "Country"
INFO [2020-11-03 10:35:03] [my.account]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-11-03 10:35:03] [my.account]  - window.navigator.webdriver response: None
INFO [2020-11-03 10:35:03] [my.account]  - Hide Selenium Extension: ok
Issue with cookie for user my.account. Creating new cookie...

INFO [2020-11-03 10:35:14] [my.account]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 32.12 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-11-03 10:35:14] [my.account]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo


Traceback (most recent call last):
  File "insta_bot.py", line 100, in <module>
    scripts.script.run_script(tag)
  File "/home/pi/instabot/scripts/script.py", line 31, in run_script
    with smart_run(session):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 1929, in smart_run
    session.login()
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 433, in login
    self.want_check_browser,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/login_util.py", line 296, in login_user
    (ActionChains(browser).move_to_element(login_elem).click().perform())
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.sendMouseEvent]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://marionette/content/event.js :: event.synthesizeMouseAtPoint :: line 184"  data: no]
```

## InstaPy configuration
My InstaPy instance runs on a raspberry-pi 3 in headless mode. So, I only access it via ssh. I have set up crontab to regularly run my main script `/home/pi/instabot/insta_bot.py`. This one just waits for some random offset and sends some telegram messages to me. Then it calls one of the scripts in the `scripts` folder. 

Here you can see my `run_script` method:

```
def run_script(tag=random.choice(tags_to_use)):
    # get an InstaPy session!
    # set headless_browser=True to run InstaPy in the background
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=True)

    with smart_run(session):
        """ Activity flow """
        # general settings
        session.set_relationship_bounds(enabled=True,
                                        potency_ratio=None,
                                        delimit_by_numbers=True,
                                        min_followers=10,
                                        min_following=5,
                                        max_followers=3000,
                                        min_posts=0,
                                        max_posts=100000)

        session.set_simulation(enabled=True, percentage=70)

        session.set_skip_users(skip_private=False,
                               private_percentage=90,
                               skip_no_profile_pic=False,
                               no_profile_pic_percentage=80)

        session.set_quota_supervisor(enabled=True,
                                     sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"],
                                     sleepyhead=True, stochastic_flow=True, notify_me=False,
                                     peak_likes_hourly=50,
                                     peak_likes_daily=500,
                                     peak_comments_hourly=10,
                                     peak_comments_daily=50,
                                     peak_follows_hourly=10,
                                     peak_follows_daily=100,
                                     peak_unfollows_hourly=35,
                                     peak_unfollows_daily=402,
                                     peak_server_calls_hourly=200,
                                     peak_server_calls_daily=2000)

        # LIKE BY TAGS

        interaction_amount = rand(1, 5)
        interaction_percentage = rand(10, 100)
        like_amount = rand(3, 20)

        print("----- Like " + str(like_amount) + " in tag " + tag + " and interact with " +
              str(interaction_percentage) + "% and like " + str(interaction_amount) + " -----")

        # session.set_delimit_liking(enabled=True, max_likes=500, min_likes=0)
        session.set_user_interact(amount=interaction_amount, randomize=True, percentage=interaction_percentage)
        session.like_by_tags([tag], amount=like_amount, randomize=False, interact=True)
```
Someone seeing my mistake/the problem? For setting up InstaPy on my raspberry-pi I followed [this](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md) documentation.

**Comment by ryanayad** [comment]
Same issue here! Been driving me crazy for weeks trying to figure out what's going on!!

**Comment by SanielDous** [comment]
@ryanayad what configuration are you using?

**Comment by v0lumehi** [comment]
Fixing this is simple. All you need to do is this:
`sudo apt-get install xvfb`

This installs the xvfb package. After this execute your quickstart.py or whatever config you are using like this:
`sudo xvfb-run -a python quickstart.py`

There seems to be an issue with cookies though. You need to retry the command above a couple of times until the session doesn't recreate a cookie.

**Comment by v0lumehi** [comment]
It seems like you don't need thex xvfb installation. A workaround at the moment is to restart the bot a couple of times

**Comment by SanielDous** [comment]
> It seems like you don't need thex xvfb installation. A workaround at the moment is to restart the bot a couple of times

Yeah, I also noticed this. I already wrote a script that gives the bot some tries to start. It works for now but I think the solution is not very elegant. Do you know which component (InstaPy/Selenium/Browser) is responsible for the issue and if there is a prospective solution

**Comment by ryanayad** [comment]
@SanielDous My main script gets fairly complicated but to make sure it wasn't my script causing the issues I tried with a simple quick_start script. Its setup on a windows EC2 instance now but the issue was the same running on my PC.. Its a shame because it used to work perfectly!

**Comment by ryanayad** [comment]
> It seems like you don't need thex xvfb installation. A workaround at the moment is to restart the bot a couple of times

Yes.. Restarting it a couple times seems to help but its strange as I haven't even been able to identify a pattern as to when it works or doesn't.. 

What condition are you using to restart the bot?

**Comment by SanielDous** [comment]
> What condition are you using to restart the bot?

Currently, I surrounded the InstaPy execution with `try ... except ...` clause. Additionally, I check the logs for the "Sessional Live Report" and if it contains "No any statistics to show". Most of the times 5 retries are sufficient for me.

**Comment by ryanayad** [comment]
@SanielDous That's a good idea actually!

Out of interest has anyone tested different versions of InstaPy for this issue? Due to the issue not being consistent I have found it hard to tell if a certain version is better than another..

**Comment by Jostino** [comment]
> 
> 
> Fixing this is simple. All you need to do is this:
> `sudo apt-get install xvfb`
> 
> This installs the xvfb package. After this execute your quickstart.py or whatever config you are using like this:
> `sudo xvfb-run -a python quickstart.py`
> 
> There seems to be an issue with cookies though. You need to retry the command above a couple of times until the session doesn't recreate a cookie.


Following this suggestion the error about the OG disappeared, but i have another one about login:

```
Issue with cookie for user earthportfolio. Creating new cookie...
Login A/B test detected! Trying another string...
Could not pass the login A/B test. Trying last string...
............................................................................................................................
CRITICAL [2020-12-24 14:03:53] [earthportfolio]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

```

**Comment by elulcao** [comment]
Check the graphic session to determine if there is a new Window
or IG's question that requires user interaction. from the log above 
seems that you are not able to login to your acct.
