### ISSUE TITLE
selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)

### ISSUE THREAD

**Issue by rexonat** [InstaPy/InstaPy#5897]
## Expected Behavior
Connect to instagram and perfom some actions

## Current Behavior
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 11, in <module>
    session = InstaPy(username=insta_username,
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 322, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 132, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)

**Comment by rexonat** [comment]
I'm using python 3.8, read somewhere that this is not compatible with InstaPy - is this true?

**Comment by rexonat** [comment]
Yep - it was incompatible and now working

**Comment by hadpro24** [comment]
Do you solve this problem @rexonat ? How ?

**Comment by PS1Online** [comment]
How? I want to know too.
