### ISSUE TITLE
Expected browser binary location, but unable to find binary in default location

### ISSUE THREAD

**Issue by MarkChukwuebuka** [InstaPy/InstaPy#5898]
i have tried all possible solutions but i haven't been able to resolve this issue

python insta_bot.py
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/MARK/InstaPy"
Traceback (most recent call last):
  File "insta_bot.py", line 6, in <module>
    session = InstaPy(username="spla_shybae", password="pass2002word", headless_browser=True)
  File "C:\Users\MARK\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\MARK\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 111, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\MARK\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\MARK\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\MARK\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\MARK\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\MARK\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by imbarismustafa** [comment]
Install compatible version of Firefox.

**Comment by v0lumehi** [comment]
It seems that you use an outdated version of InstaPy. Try updating to the current version

**Comment by MarkChukwuebuka** [comment]
@v0lumehi I'm using the latest version of InstaPy

**Comment by MarkChukwuebuka** [comment]
@imbarismustafa I updated to the latest version of Firefox but it still throws the same error.

**Comment by skourtisk** [comment]
Im getting the same error, any fix?

**Comment by skourtisk** [comment]
Hey man, uninstall firefox and install it again. It worked for me

**Comment by saminkhan1** [comment]
@kostis14 what os are you on I am getting the same issue, reinstalled, updated everything still the same error

**Comment by 0nlyfanz** [comment]
It does look like you have an old version of py.  However, I have the new version, reinstalled firefox, etc. etc.... I have the same issue.

**Comment by elulcao** [comment]
This error is because cannot be found FF installation. If you have FF installed in a non-default location which then you need to follow the steps for custom FF location. Documented in InstaPy.org

**Comment by Fiereu** [comment]
So hello @MarkChukwuebuka this has nothing to do with your issue but you're leaking your Instagram credentials. It would be better to remove them even if your account is 2FA secured.

**Comment by bsbilal** [comment]
you have to give firefox path

**Comment by EgShes** [comment]
I had the same issue.

Adding RUN command [from](https://github.com/InstaPy/instapy-docker/blob/master/Dockerfile) the official Dockerfile to my local helped.

Suppose firefox must be installed on the system

**Comment by Jasiri-w** [comment]
### A Solution:
https://github.com/timgrossmann/InstaPy/issues/6070#issuecomment-815819613

For anyone that has found reinstalling Firefox unhelpful, this worked for me instead using a different parameter ( `browser_executable_path = r"C:[Custom Location]" )` I found in the InstaPy class init function

**Comment by EvanThomasKaduthanam** [comment]
Is there a way to use Microsoft Edge rather than Mozilla?

**Comment by happy-san** [comment]
@EvanThomasKaduthanam [check this out](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/)
