### ISSUE TITLE
Login error - After Cookie Creation

### ISSUE THREAD

**Issue by fintzd** [InstaPy/InstaPy#5901]
## Current Behavior

Traceback (most recent call last):
  File "script.py", line 16, in <module>
    with smart_run(session):

  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)

  File "/root/INSTA/instant/lib/python3.8/site-packages/instapy/util.py", line 1920, in smart_run
    session.login()

  File "/root/INSTA/instant/lib/python3.8/site-packages/instapy/instapy.py", line 425, in login
    if not login_user(
  File "/root/INSTA/instant/lib/python3.8/site-packages/instapy/login_util.py", line 320, in login_user
    ActionChains(browser)

  File "/root/INSTA/instant/lib/python3.8/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()

  File "/root/INSTA/instant/lib/python3.8/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)

  File "/root/INSTA/instant/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/INSTA/instant/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.WebDriverException: Message: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.sendMouseEvent]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://marionette/content/event.js :: event.synthesizeMouseAtPoint :: line 189"  data: no]

**Comment by correafer** [comment]
I reset Firefox cookies and data, it fixed the problem for me!

**Comment by fintzd** [comment]
Thank you, I'll try that @ferbsferbs ! :)
