### ISSUE TITLE
Help i have this error

### ISSUE THREAD

**Issue by ManuelCode1** [InstaPy/InstaPy#5902]
Traceback (most recent call last):
  File "C:\Users\manue\Desktop\instapy-quickstart-master\quickstart.py", line 64, in <module>
    with smart_run(session):
  File "C:\Users\manue\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 115, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield

**Comment by cnarvaa** [comment]
Can you share the script? is it the same from the web page?

**Comment by Aassifh** [comment]
I have the same issue, using the quickstart.py script please help !
