### ISSUE TITLE
Does this bot even work?

### ISSUE THREAD

**Issue by wsmith9897** [InstaPy/InstaPy#5909]
## Current Behavior
Never  been able to login to instagram with this bot. I've been getting the same error for months. Never used this successfully. 

Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

............................................................................................................................
CRITICAL [2020-11-17 22:54:39] [myusername]  Unable to login to Instagram! You will find more information in the logs above.

**Comment by elulcao** [comment]
Share the complete configuration file (mask personal info)
and env details. 
thanks.

**Comment by fintzd** [comment]
Well apparently the issue you mentioned should be fixed in the next version, so don't worry about that too much! 

For a quick fix check this reply [reply](https://github.com/timgrossmann/InstaPy/issues/5886#issuecomment-727207957) by @feelqah ! (reference to issue #5886 )

**Comment by kersvanbinsbergen** [comment]
I can't get it working too.

Something with clarifai. I don't need that right? it's about image recognition.

This is my log:

pi@raspberrypi:~/instapi/services/config $ sudo xvfb-run python3 quickstart.py  Traceback (most recent call last):
  File "quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/usr/local/lib/python3.7/dist-packages/instapy-0.6.12-py3.7.egg/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/usr/local/lib/python3.7/dist-packages/instapy-0.6.12-py3.7.egg/instapy/instapy.py", line 33, in <module>
    from .clarifai_util import check_image
  File "/usr/local/lib/python3.7/dist-packages/instapy-0.6.12-py3.7.egg/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
ModuleNotFoundError: No module named 'clarifai'

**Comment by fintzd** [comment]
Hey @kersvanbinsbergen, yes clarifai is an AI visual recognition program. 

Based on what you pasted (I copied the error message below), it would seem that the issue is that you don't have clarifai installed as a python module.
`ModuleNotFoundError: No module named 'clarifai'`

You could try to reinstall InstaPy from the pip library, following this [guide for your Raspberry Pi](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md), or try to install clarifai as a Python module from pip as follows (use the 'python' version you're using to run the quickstart script):
`python -m pip install clarifai`

Hope it helps and who knows, solves the issues you're facing! 

Have a great day! :)
