### ISSUE TITLE
Login successful, but failing after that.

### ISSUE THREAD

**Issue by degatt2** [InstaPy/InstaPy#5913]
**First time i tried, it works like magic ..but next day started to fail:
My login is successful, but after that I always get the following error:**

Traceback (most recent call last):
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x113f085e0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dagonzal/Downloads/instapy-quickstart-master/quickstart.py", line 56, in <module>
    session.set_dont_unfollow_active_users(enabled=True, posts=10)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/instapy/instapy.py", line 4205, in set_dont_unfollow_active_users
    active_users = get_active_users(
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/instapy/util.py", line 626, in get_active_users
    web_address_navigator(browser, user_link)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/instapy/util.py", line 1229, in web_address_navigator
    current_url = get_current_url(browser)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/instapy/util.py", line 1801, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/dagonzal/anaconda2/envs/mypython3/lib/python3.9/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=61087): Max retries exceeded with url: /session/827e6ee6-f24d-2446-8c10-6d6a95cf07bf/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113f085e0>: Failed to establish a new connection: [Errno 61] Connection refused'))

**the python code is the following:** 

# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = ''
insta_password = ''

comments = [
        u'@{} Your artwork is magical! :fire:'
        u'@{} Wow, I love it! :star2:',
        u'Its very inspiring piece! :art:',
        u':heart_eyes: :sparkles:',
        u'Amazing! :heart: :heart:',
        u'So cool! :sunglasses:',
        u'@{} :heart::heart:',
        u'@{} :heart_eyes: Love it',
        u'Looks awesome @{} :fire:',
        u'Amazing @{}!, would love to see your process',
        u'Yeah! :boom:',
        u':heart_eyes:',
        u'You are on fire! :fire:',
        u':raised_hands:',
        u':clap:',
        'Really cool!',
        'Me encanta!',
        u'fascinating :green_heart:',
        u':star2:',
        u'this is interesting :four_leaf_clover:',
        u':green_heart:',
        u':fire: :fire: :fire:',
        'Very expressive!',
        'Cool work!',
        u'@{} Beautiful work :green_heart:',
        u':heart: :heart: :clap: Nice!',
        '@{} This one is so good, great work'
        ]

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False
                  )

with smart_run(session):
  """ Activity flow """		
  

# default enabled=False, follows ~ 10% of the users from the images, times=1
# (only follows a user once (if unfollowed again))
session.set_do_follow( enabled=True, percentage=10, times=1 )
session.set_dont_unfollow_active_users(enabled=True, posts=10)

# activity		
session.set_delimit_liking(enabled=True, min_likes=20)

session.set_relationship_bounds(
                enabled=True,
                potency_ratio=1.34,
                delimit_by_numbers=True,
                min_followers=100,
                min_following=56,
                min_posts=10,
              )

session.set_skip_users( skip_private=True,
                        skip_no_profile_pic=True,
                        skip_business=True,
                        business_percentage=100)

session.like_by_tags([
  "geometricart",
  "artanddesign",
  "painting",
  "contemporaryhome",
  "livingwithart",
  "postminimalist",
  "postminimal",
  "modernist",
  "nonfigurative",
  "contemporarypaintings",
  "geometric",
  "texture",
  "artwork",
  "berlin",
  "germany",
  "dataart",
  "acrilycspainting",
  "staythefuckhome",
  "new_and_abstract",
  "emergingartist",
  "artcollecting",
  "kunstwerk",
  "modernekunst",
  "contemporaryfineart"
  ], amount=10)

# Joining Engagement Pods
session.set_do_comment(enabled=True, percentage=35)
session.set_comments(comments)
# session.join_pods(topic='sports', engagement_mode='no_comments')
session.set_action_delays(enabled=True,
                         like=2,
                         comment=4,
                         follow=3.10,
                         unfollow=20,
                         story=10)

**Comment by fintzd** [comment]
Are you running this on a server or a local computer? 

The error seems to be pointing at the fact that you have made too many requests to the website. If you don't think that's the case, can you check what version of urllib3 you've got installed? Based on what I saw, there was an issue similar to this, but it got fixed quite a while back.

------

EDIT:
Based on [urllib3 documentation](https://urllib3.readthedocs.io/en/latest/reference/urllib3.exceptions.html#urllib3.exceptions.MaxRetryError) 

> exception urllib3.exceptions.MaxRetryError(pool, url, reason=None)
Bases: urllib3.exceptions.RequestError
Raised when the maximum number of retries is exceeded.

So if you've done quite a few trials to get it up and running, you may be blocked, in which case, waiting for a while can be the most simple solution.

**Comment by degatt2** [comment]
Yes, It might have done many requests, actually I let it run overnight on the localhost ... not sure how much time did run. I'll wait and see check again next week. Thanks.

**Comment by degatt2** [comment]
And yes, i was running it on a localhost
*Dega.*
Contemporary artist
phone. +49 1715523165
address. Wöhlertstraße 18, 10115 Berlin
web. http://degafolio.info/paintings/

**Comment by fintzd** [comment]
Alright! If it's all good, don't forget to close the issue :) @degatt2

**Comment by fintzd** [comment]
Hey @elulcao , I think this one can be closed :)
