### ISSUE TITLE
[Crash] Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Naramsim** [InstaPy/InstaPy#592]
I´m running InstaPy in Docker Compose. I have the latest version of the repo. I had two crashes with the same traceback

```pytb
Traceback (most recent call last):
  File "/code/main.py", line 61, in job
    session.like_by_tags(['landscape', 'mountains'], amount=110, media='Photo')
  File "/code/instapy/instapy.py", line 477, in like_by_tags
    self.like_by_followers_lower_limit)
  File "/code/instapy/like_util.py", line 355, in check_link
    "return window._sharedData.entry_data.ProfilePage[0].user.followed_by.count")
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 491, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57),platform=Linux 3.13.0-123-generic x86_64) (WARNING: The server did not provide any stacktrace information)
```

**Comment by iSimonWeb** [comment]
Hey there, I had this issue twice yesterday but I suppose it was an
Instagram issue.
InstaPy gathers info about followers count via a "ProfilePage" attached to
the window JavaScript object; sometimes unfortunately Instagram seems not
to update this value when navigating to the next page.

Now everything seems fine.

**Comment by Naramsim** [comment]
Closing since it never happened again

**Comment by lologibus2** [comment]
Hello, seems that problem is back again. I ran multiple different configurations and had same error on different machines. 

My code:
```
def unfollow(ACCOUNTS):
    try:
        session = InstaPy(username='XXXX', password='XXXX', headless_browser=True)
        session.login()
        print('##### STARTING UNFOLLOWING SESSION #####')
        session.set_dont_include(ACCOUNTS)
        # Prevents unfollow followers who have liked one of your latest 5 posts
        session.set_dont_unfollow_active_users(enabled=True, posts=10)
        session.unfollow_users(amount=100, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=200)
        session.set_sleep_reduce(20)
        session.end()
    except KeyboardInterrupt:
        session.end()
    except:
        import traceback
        print(traceback.format_exc())

unfollow(ACCOUNTS)
```

Error:
```
INFO - Session started - 2018-01-18 04:29:01
INFO - Logged in successfully!
Traceback (most recent call last):
  File "XXXXX_bot.py", line 59, in unfollow
    session.login()
  File "/home/ubuntu/Documents/XXXXX/InstaPy/instapy/instapy.py", line 234, in login
    log_follower_num(self.browser, self.username)
  File "/home/ubuntu/Documents/XXXXX/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/home/ubuntu/venv3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/home/ubuntu/venv3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/venv3/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: headless chrome=63.0.3239.132)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.4.0-1047-aws x86_64)
```

Any suggestions ?

**Comment by flo6913** [comment]
Hello, same for me
`INFO - Session started - 2018-01-20 12:21:20
INFO - Logged in successfully!
INFO - Session ended - 2018-01-20 12:21:25
INFO - --------------------


Traceback (most recent call last):
  File "quickstart.py", line 11, in <module>
    session.login()
  File "/Users/Florent/instapy/InstaPy/instapy/instapy.py", line 234, in login
    log_follower_num(self.browser, self.username)
  File "/Users/Florent/instapy/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.12.5 x86_64)`

**Comment by underclass** [comment]
Try deleting your site cookie @flo6913 @lologibus2
