### ISSUE TITLE
TypeError: can't apply this __setattr__ to instance object

### ISSUE THREAD

**Issue by GurappaVhadlure** [InstaPy/InstaPy#5925]
## Expected Behavior
I have installed InstaPy and trying to run mac_start.command. 
It should now log into Instagram account.

## Current Behavior
I have installed InstaPy and trying to run mac_start.command. 
It should now log into Instagram account but instead gives this error - TypeError: can't apply this __setattr__ to instance object

Any pointer will be appreciated.

**Comment by gorglion** [comment]
Hi ! Sale problème ... Any solution ?

**Comment by gorglion** [comment]
Hi, same probleme... Any solution ?

**Comment by elulcao** [comment]
Could you share the stack trace for this issue, 
Thanks

**Comment by sionann** [comment]
I have the same problem. Did you happen to figure it out?

**Comment by sionann** [comment]
@elulcao 

cyruss-MacBook-Pro:~ sionann$ /Users/sionann/Downloads/instapy-quickstart-master/run/mac_start.command ; exit;
Starting InstaPy with quickstart
====================
/Users/sionann/Library/Python/2.7/lib/python/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (4.0.0) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/Users/sionann/Library/Python/2.7/lib/python/site-packages/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/sionann/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 26, in <module>
    from .comment_util import comment_image
  File "/Users/sionann/Library/Python/2.7/lib/python/site-packages/instapy/comment_util.py", line 8, in <module>
    from .util import update_activity
  File "/Users/sionann/Library/Python/2.7/lib/python/site-packages/instapy/util.py", line 34, in <module>
    from .quota_supervisor import quota_supervisor
  File "/Users/sionann/Library/Python/2.7/lib/python/site-packages/instapy/quota_supervisor.py", line 7, in <module>
    from plyer import notification
  File "/Users/sionann/Library/Python/2.7/lib/python/site-packages/plyer/__init__.py", line 23, in <module>
    accelerometer = Proxy('accelerometer', facades.Accelerometer)
  File "/Users/sionann/Library/Python/2.7/lib/python/site-packages/plyer/utils.py", line 80, in __init__
    object.__setattr__(self, '_obj', None)
TypeError: can't apply this __setattr__ to instance object
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by elulcao** [comment]
Based on CHANGELOG, python 2.7 has been deprecated in favor of python 3
The traces you shared contains references to p2.7 
`File "/Users/sionann/Library/Python/2.7/lib/python/site-packages/instapy/init.py", line 3, in`


```bash
  8 ## [0.5.0] - 2019-06-03
  7
  6 ### Added
  5
  4 - Additional check for like block.
  3
  2 ### Changed
  1
308 - Remove support for python2
  1 - Information regarding the nogui parameter in documentation.
  2 - XPath Isolation
  3 - Remove redundant assignment of pod_post_ids
  4 - Remove address var assigned multiple times without intermediate usage
  5 - `set_mandatory_language` can maintain multiple character sets
  6 - Feature finetuning comments for pods
```

**Comment by sionann** [comment]
@elulcao 
So I don't understand what to do? Is this related to installing the update file?

**Comment by sionann** [comment]
@gorglion @GurappaVhadlure  did either of you solve it?

**Comment by sionann** [comment]
@elulcao I'm sorry to bother you again, but is there any chance you could explain a bit more how to fix it? I'm somewhat comfortable editing code but I'm not a developer so I don't completely understand your comment/instructions above. 

Thank you.

**Comment by elulcao** [comment]
@sionann 
The traces has the reference for python2.7, I recommend to use python3 since python2 has been deprecated.
It seems that you are using the quickstart repo to configure and initialize InstaPy, could you check if you can use this 
version in your local (see below).

macOS has installed python2 and python3 (a little wrapper) by default, so you have to install the complete suite
for python3 if you want to use all the new capabilities from Python. If you are using `brew` or `macports` install 
python3 like any other app, or Download from the official Python page. 
Then after this step, execute again the quickstart script `start.sh` from the zip, it will create a virtualenv to configure InstaPy. 

Probably InstaPy fails if your machine doesn't have the complete version of Python3.
After correct configuration the virtualenv will have the latest version from pip, which is not the latest compared with GitHub.

[instapy-quickstart-pr_update_instapy_quickstart.zip](https://github.com/timgrossmann/InstaPy/files/5702982/instapy-quickstart-pr_update_instapy_quickstart.zip)

**Comment by olhamol** [comment]
Same issue - this is critical, does someone knows how to fix?
