### ISSUE TITLE
Smart_run error apper in any way, How to solve it?

### ISSUE THREAD

**Issue by rsa408** [InstaPy/InstaPy#5946]
I am using the quickstart script but it shows me the error:

```
C:\Users\rsa\AppData\Local\Programs\Python\Python36\python.exe C:/Users/rsa/AppData/Local/Temp/quickstart.py/main.py
Traceback (most recent call last):
  File "C:/Users/rsa/AppData/Local/Temp/quickstart.py/main.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\rsa\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\rsa\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\instapy.py", line 33, in <module>
    from .clarifai_util import check_image
  File "C:\Users\rsa\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "C:\Users\rsa\AppData\Local\Programs\Python\Python36\lib\site-packages\clarifai\rest\__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "C:\Users\rsa\AppData\Local\Programs\Python\Python36\lib\site-packages\clarifai\rest\client.py", line 23, in <module>
    from google.protobuf.struct_pb2 import Struct
  File "C:\Users\rsa\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\struct_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\rsa\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 48, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

Process finished with exit code 1

```
The code is : 
```

`from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace


# set workspace folder at desired location (default is at your home folder)
set_workspace(path=None)

# get an InstaPy session!
session = InstaPy()

with smart_run(session):
    # general settings
    session.set_dont_include(["friend1", "friend2", "friend3"])

    # activity
    session.like_by_tags(["natgeo"], amount=10)
```

IDE: Pycharm 
Python: 3.6.0
OS: Windows 7 x64

I will be appreciated if you guys help me.

**Comment by elulcao** [comment]
@rsa408 

this is most an issue with python3.6 and Windows
I saw the same in [stackoverflow](https://stackoverflow.com/questions/52092810/tensorflow-error-dll-load-failed-the-specified-procedure-could-not-be-found/53111377#53111377)
you should check that post.

**Comment by rsa408** [comment]
I upgrade python to 3.8.6
but the other issue occurred and I tired from installing removing python packages. the last issue is :

```
C:\Users\RSA\AppData\Local\Programs\Python\Python36\python.exe D:/apps/instapy-quickstart/quickstart.py
Traceback (most recent call last):
  File "D:/apps/instapy-quickstart/quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "C:\Users\RSA\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\RSA\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\instapy.py", line 34, in <module>
    from .comment_util import comment_image
  File "C:\Users\RSA\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\comment_util.py", line 8, in <module>
    from .util import update_activity
  File "C:\Users\RSA\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\util.py", line 7, in <module>
    import regex
  File "C:\Users\RSA\AppData\Local\Programs\Python\Python36\lib\site-packages\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\Users\RSA\AppData\Local\Programs\Python\Python36\lib\site-packages\regex\regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "C:\Users\RSA\AppData\Local\Programs\Python\Python36\lib\site-packages\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'
```

**Comment by rsa408** [comment]
I solved the problem.
I removed all versions of Instapy and Regex and all the cached files and started to install fresh on python 3.8.2

thanks.
