### ISSUE TITLE
Error using firefox mode

### ISSUE THREAD

**Issue by peguilherme77** [InstaPy/InstaPy#596]
This error appeared at all times:

Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    session.login()
  File "C:\Users\pedro\Desktop\Github\InstaPy\instapy\instapy.py", line 163, in login
    if not login_user(self.browser, self.username, self.password, self.switch_language):
  File "C:\Users\pedro\Desktop\Github\InstaPy\instapy\login_util.py", line 21, in login_user
    action = ActionChains(browser).move_to_element(login_elem).click().perform()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\action_chains.py", line 77, in perform
    self.w3c_actions.perform()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\actions\action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (932.5, 666) is out of bounds of viewport width (1366) and height (659)

Firefox opens the window on the Instagram page, but it does not get there.

**Comment by converge** [comment]
hey @peguilherme77 , did you managed to fix it ?
