### ISSUE TITLE
tarfile.ReadError: file could not be opened successfully

### ISSUE THREAD

**Issue by Caspertje83** [InstaPy/InstaPy#5965]
I started by opening and closing a session but am getting the following errors

session = InstaPy(username="xxx", password="xxxx")
session.login()

session.end()

Traceback (most recent call last):
  File "/Users/user/Documents/python/insta_bot/app.py", line 4, in <module>
    session = InstaPy(username="xxxxxx", password="xxxxxxx")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 322, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 131, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 191, in download_and_install
    with tarfile.open(os.path.join(self.get_download_path(version), filename), mode="r:*") as tar:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tarfile.py", line 1614, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

**Comment by tg1482** [comment]
Hi, facing the same issue with MacOS. Running the container and cannot find the tar file. Works locally though, just not in the container
![Screen Shot 2021-05-10 at 12 51 24 AM](https://user-images.githubusercontent.com/31661606/117607380-d9283b00-b129-11eb-9e34-af6fc30cd729.png)

Would appreciate any and all help! Thank you!

**Comment by Havanero** [comment]
This issue is happening with python3.9 on ubuntu21.10
