### ISSUE TITLE
Like_by_Feed Crashess the whole session.

### ISSUE THREAD

**Issue by bennocoder** [InstaPy/InstaPy#5988]
## Expected Behavior
Used the Like by Feed configuration. Got this Error on Ubuntu 20.04 and also on 18.04. Like by Hashtag ist working. Tried only t
## Current Behavior
raceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(

File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f16af216580>: Failed to establish a new connection: [Errno 111] Connec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 48, in <module>
    session.like_by_feed(amount=20, randomize=True, unfollow=True, interact=True)
  File "/home/avst/.local/lib/python3.8/site-packages/instapy/instapy.py", line 3874, in like_by_feed
    for _ in self.like_by_feed_generator(amount, randomize, unfollow, interact):
  File "/home/avst/.local/lib/python3.8/site-packages/instapy/instapy.py", line 3918, in like_by_feed_generator
    links = get_links_from_feed(
  File "/home/avst/.local/lib/python3.8/site-packages/instapy/like_util.py", line 44, in get_links_from_feed
    web_address_navigator(browser, feeds_link)
  File "/home/avst/.local/lib/python3.8/site-packages/instapy/util.py", line 1231, in web_address_navigator
    current_url = get_current_url(browser)
  File "/home/avst/.local/lib/python3.8/site-packages/instapy/util.py", line 1803, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/home/avst/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "/home/avst/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/avst/.local/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/avst/.local/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=57877): Max retries exceeded with url: /session/19d3ef7b-bfd0-45d9-bec5-342d2e648
## InstaPy configuration
with smart_run(session):
  """ Activity flow """
session.like_by_feed(amount=20, randomize=True, unfollow=True, interact=True)

Tried all librarys to be updatetd. No Effeckt,

**Comment by elulcao** [comment]
Hi,
I saw that problem time ago, it seems to be an outdated lib (maybe urllib3),
try removing all the packages installed with pip, and then create a virtual env.
once createted the venv, install again the requirements and start again the session.

**Comment by bennocoder** [comment]
Hi,

thank you for your answer. Tried it with venv. All Librarys are in the version they need in the requirements.txt.

Nothing Changed. Have no Idea, what it could be...

Tried it with 1.24.1 1.26.2 and the 2.0 urllib3.

With 2.0 there is a version conflict.

With the 1.* the same error.

Also on  Debian system same error.

**Comment by elulcao** [comment]
Check the follow steps for your venv:

```python
python -m venv venv_instapy
source venv_instapy/bin/activate
pip install -U pip wheel
pip install -r requirements.txt
```

then you have two options, don't mix them (ie: if you use step 1 then do not execute step 2):
1: install Instapy via pip with latest commit `python -m pip install git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf`
2: install InstaPy from GitHub, `git clone https://github.com/timgrossmann/InstaPy.git`

both of them worked in my local.

**Comment by bennocoder** [comment]
Thank you elulcao,

tried also your recommendation. Used all the commands you posted. The same error.  Its only with the like_by_feed function.

Liking by hashtag works. Any further Idea?
