### ISSUE TITLE
browsingContextFn() .currentWindowGlobal is null on instapy

### ISSUE THREAD

**Issue by joeD268** [InstaPy/InstaPy#5989]
Hi there,

I manage to access instagram via instapy but when instagram opens i get an browsing context error and it wont contiune. any idea?

thank you

/Library/Frameworks/Python.framework/Versions/3.9/bin/python3 /Applications/hello.py
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/beccarose/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-12-29 12:36:46] [bdtees_golfuk]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-12-29 12:36:46] [bdtees_golfuk]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-12-29 12:36:47] [bdtees_golfuk]  - Internet Connection Status: ok
INFO [2020-12-29 12:36:47] [bdtees_golfuk]  - Current IP is "87.81.58.153" and it's from "United Kingdom/GB"
INFO [2020-12-29 12:36:47] [bdtees_golfuk]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-12-29 12:36:47] [bdtees_golfuk]  - window.navigator.webdriver response: None
INFO [2020-12-29 12:36:47] [bdtees_golfuk]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
Traceback (most recent call last):
  File "/Applications/hello.py", line 4, in <module>
    session.login()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 425, in login
    if not login_user(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/login_util.py", line 362, in login_user
    dismiss_get_app_offer(browser, logger)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/login_util.py", line 466, in dismiss_get_app_offer
    offer_loaded = explicit_wait(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/util.py", line 1784, in explicit_wait
    result = wait.until(condition)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find_element
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: browsingContextFn().currentWindowGlobal is null

**Comment by elulcao** [comment]
Did you install InstaPy via pip or git?
if you used pip, check that you are using the latest commit.
pip version for InstaPy is a little bit outdated from GitHub,

**Comment by joeD268** [comment]
Name: instapy
Version: 0.6.12
Summary: Tool for automated Instagram interactions
Home-page: https://github.com/timgrossmann/InstaPy
Author: Tim Großmann

Hi - this is my version. i seem to get the same error every way i try to run the code. as per below:

I cant see where it's going wrong. help hugely appreciated 

from instapy import InstaPy

session = InstaPy(username="xx", password="xx")
session.login()
session.like_by_tags(["golf", "golflife"], amount=10)
session.set_dont_like(["naked", "nsfw"])
session.set_do_follow(True, percentage=50)
session.set_do_comment(True, percentage=50)
session.set_comments(["Nice!", "Sweet!"])
session.end()

**Comment by elulcao** [comment]
@joeD268 
Check the follow steps for your venv:

python -m venv venv_instapy
source venv_instapy/bin/activate
pip install -U pip wheel
pip install -r requirements.txt
then you have two options, don't mix them (ie: if you use step 1 then do not execute step 2):
1: install Instapy via pip with latest commit python -m pip install git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf
2: install InstaPy from GitHub, git clone https://github.com/timgrossmann/InstaPy.git

both of them worked in my local.

**Comment by joeD268** [comment]
Thanks so much for trying to help.
I'm on a Mac and downloaded pip install-U wheel and reinstalled Instapy from your Gitlink and still no passing that error message in visual code !!! 😩

**Comment by elulcao** [comment]
ohhh!,
I didn't use that in VSCode, let me give a try. I will share my findings soon.

**Comment by joeD268** [comment]
Thank you so much for your help.

It's been a very frustrating few days!

**Comment by elulcao** [comment]
My workspace has this configuration, the `python.pythonPath` is pointing to the `venv` I created with previous steps (sharing again just in case). 
Using InstaPy form VSCode terminal is the same, I'm guessing that Python3.9 could be the problem, so I will suggest 
to install Pyhon3.8 and then re-create the `venv` with Pyton3.8.

I installed Python3.8 via `[macports](https://www.macports.org)`, if you are in the same try to install from there and configure the `venv` with the correct Python3.8. There is no restriction for having multiple Python Versions.

Hope this helps.


```bash
port version
Version: 2.6.4

python --version
Python 3.8.7
```

```python
python -m venv venv
source venv/bin/activate
pip install -U pip wheel
pip install -r requirements.txt
```

```json
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"editor.fontLigatures": false,
		"editor.rulers": [
			79,
		],
		"explorer.sortOrder": "type",
		"explorer.decorations.colors": true,
		"explorer.decorations.badges": true,
		"files.autoSave": "onFocusChange",
		"files.enableTrash": true,
		"[markdown]": {
			"editor.wordWrap": "wordWrapColumn",
			"editor.wordWrapColumn": 79,
			"editor.quickSuggestions": false
		},
		"python.formatting.provider": "black",
		"python.pythonPath": "/Users/internet/GitHub/InstaPy/venv/bin/python",
		"git.branchSortOrder": "alphabetically",
		"git.decorations.enabled": true,
		"git.ignoreLimitWarning": true,
		"git.enableCommitSigning": true,
		"git.alwaysSignOff": true,
                "terminal.integrated.fontFamily": "'Source Code Pro for Powerline', 'Hack Nerd Font'",
	}
}
```

Finally, this is what I have installed, check if you have the same:

```python
pip freeze
appdirs==1.4.4
APScheduler==3.6.3
beautifulsoup4==4.9.3
black==20.8b1
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
clarifai==2.6.2
click==7.1.2
configparser==3.8.1
cryptography==3.3.1
decorator==4.4.2
EasyProcess==0.3
emoji==0.6.0
future==0.18.2
googleapis-common-protos==1.52.0
grpcio==1.34.0
idna==2.10
jsonschema==2.6.0
MeaningCloud-python==2.0.0
mypy-extensions==0.4.3
pathspec==0.8.1
plyer==2.0.0
protobuf==3.14.0
pycparser==2.20
pyOpenSSL==20.0.1
python-telegram-bot==13.1
pytz==2020.4
PyVirtualDisplay==1.3.2
PyYAML==5.3.1
regex==2020.11.13
requests==2.25.1
selenium==3.141.0
six==1.15.0
soupsieve==2.1
toml==0.10.2
tornado==6.1
tqdm==4.54.1
typed-ast==1.4.1
typing-extensions==3.7.4.3
tzlocal==2.1
urllib3==1.26.2
webdriverdownloader==1.1.0.3
```

**Comment by joeD268** [comment]
Thank you. I have to admit I am relatively new to coding so may have some follow up questions. Sorry for being a pain I appreciate the help and time

**Comment by elulcao** [comment]
No problem, 
happy to help you 

Lets try the steps above to see if Python3.8 works for you

**Comment by joeD268** [comment]
Hi

Is it python 3.8.6 was struggling to find it on macports but have found a link on python website?

https://www.python.org/downloads/mac-osx/

**Comment by elulcao** [comment]
that version should work, 

`https://www.python.org/ftp/python/3.8.7/python-3.8.7-macosx10.9.pkg`

**Comment by joeD268** [comment]
Legend, will message tomorrow after another attempt !

**Comment by joeD268** [comment]
APScheduler==3.6.3
beautifulsoup4==4.9.3
blessings==1.7
Cerberus==1.3.2
certifi==2020.12.5
cffi==1.14.4
chardet==3.0.4
clarifai==2.6.2
colorama==0.4.4
config42==0.4.2
configparser==3.8.1
crayons==0.4.0
cryptography==3.3.1
decorator==4.4.2
EasyProcess==0.3
emoji==0.6.0
fake-useragent==0.1.11
future==0.18.2
googleapis-common-protos==1.52.0
grpcio==1.34.0
idna==2.8
instabot-py==0.7.17
instaloader==4.2.8
instapy==0.6.12
Jinja2==2.11.2
jsonschema==2.6.0
MarkupSafe==1.1.1
MeaningCloud-python==2.0.0
plyer==2.0.0
protobuf==3.14.0
pycparser==2.20
pyOpenSSL==20.0.1
python-telegram-bot==13.1
python-telegram-handler==2.2
pytz==2020.5
PyVirtualDisplay==1.3.2
PyYAML==5.1
regex==2020.11.13
requests==2.22.0
selenium==3.141.0
six==1.15.0
soupsieve==2.1
SQLAlchemy==1.3.11
tornado==6.1
tqdm==4.55.0
tzlocal==2.1
urllib3==1.25.11
webdriver-manager==3.2.2
webdriverdownloader==1.1.0.3
zope.event==4.5.0
zope.interface==5.2.0

**Comment by joeD268** [comment]
Hi again,

ive downloaded version 3.8 successfully. however when i run my version and try to run my environments it defaults to the standard mac python:

beccarose@Beccas-MBP ~ % python --version
Python 2.7.16
beccarose@Beccas-MBP ~ % 

and i get error messages - is there a way to change it so mac assumes python 3.8 in my terminal?

sorry for silly questions

**Comment by joeD268** [comment]
Hi Daniel

thanks again for your help. I have downloaded Python 3.8 as you kindly
suggested. i have attached my screen shot below of my visual code screen,
as i'm getting the same frustrating error. i'm hoping you may be able to
help again? thanks so so much

[image: Screenshot 2020-12-30 at 12.09.03.png]

**Comment by elulcao** [comment]
That's one of the complications with Python and macOS. The default version in macOS is Python2.7 (Do not remove this version, there are some dependencies to this version at OS level), so if we want a newer version we have to install by hand. I personally prefer to install everything with some package manager (like `macports`), since it is easier to install and update packages. 

macOS Catalina, at least, has a little wrapper for Python3, which is very limited and only works for you to do very basic things, thus, better not to use it for development environments.

@joeD268 
in your case, after installed Python3.8 from the Python Site, you need to use the correct version under `/System/Library/Frameworks/Python.framework/Versions/`. To make things easier, you should modify your `bash` or `zsh` to point to a new alias, but that's another setting that we don't have to deal with for now.

My recommendation is therefore to directly use the path of the new version of Python, you should see something like this:
`/System/Library/Frameworks/Python.framework/Versions/3.8/bin/python`

Once the path for the binary is found, execute the following steps in the Terminal every time you want to run InstaPy:

```bash
$ /System/Library/Frameworks/Python.framework/Versions/3.8/bin/python -m venv /path/to/your/venv_instapy
$ source /path/to/your/venv_instapy/bin/activate
(venv_instapy) $ # Now, you are in the venv, 
(venv_instapy) $ pip install -U pip wheel
(venv_instapy) $ pip install -r requirements.txt
(venv_instapy) $ python your_instapy.py
(venv_instapy) # Run `deactivate` to exit the `venv`
```

Notes:
*All the Python versions installed via `pkg` will be saved under `/System/Library/Frameworks/Python.framework/Versions/`
* All Python versions installed with `macports` must be under `/opt/local/bin/
* If you want to use `brew` the path for packages is `/usr/local/bin`; I prefer `macports` ;)
* Unfortunately Python cannot update itself when it is installed directly like you have, so you will have to keep future updates under control.

**Comment by joeD268** [comment]
Daniel, once again very helpful. I am looking to find my saved path for python as i downloaded directly from python link you sent and interestingly it doesnt show python 3.8  saved here:/System/Library/Frameworks/Python.framework/Versions

this is of course causing issues when running the above code in terminal.

i have a folder of python 3.8 saved in /usr/loval/bin but when i run in terminal i get an error - i think this may be part of the problem and im hoping when this is fixed and i can run ylur code above it should fix itself!!

beccarose@Beccas-MBP ~ % /usr/local/bin/Python\ 3.8 
zsh: exec format error: /usr/local/bin/Python 3.8

**Comment by joeD268** [comment]
Hi Daneil

it finally loaded and have found the location file:

zsh: permission denied: /Library/Frameworks/Python.framework/Versions/3.8/bin
beccarose@Beccas-MBP ~ % 

another issue - is for some reason i have access denied !

thanks

**Comment by elulcao** [comment]
Hello @joeD268 

Check that your are an `admin` (`id -Gn beccarose | grep -w admi`), you are an `admin` if you see `admin` in the output; otherwise you are normal user and then limited privileges.

**Comment by joxnumo** [comment]
Hi! I don't know anything about programming but I'm trying to test instapy and I've made it work a couple of times after reinstalling everything but after it works for the first time after reinstalling, it closes and gives me the same error here mentioned.
I have tried with python 3.9 and 3.8 but the error is the same.

ERROR browsingContextFn().currentWindowGlobal is null 

Is there a solution for this?

**Comment by JRamonMC** [comment]
Same issue here in Linux Ubuntu 20

**Comment by kmhmubin** [comment]
I Solve this Problem by adding a browser location path.

```
# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True,
                  browser_executable_path=r"C:\Program Files\Mozilla Firefox\firefox.exe")
```

**Comment by joeD268** [comment]
Thank you, have you got an example of full code you use with this browser location path? Thanks 

@kmhmubin

**Comment by kmhmubin** [comment]
> Thank you, have you got an example of full code you use with this browser location path? Thanks
> 
> @kmhmubin

Welcome, @joeD268

👉 I'm using **windows 10** with python version **3.8**
👉 I just add **Firefox** from my windows **C** directory.

### I'm using the following template from [quickstart template](https://github.com/InstaPy/instapy-quickstart/blob/master/quickstart_templates/good_commenting_strategy_and_new_qs_system.py) with my own customization.

**These script options are,**
- It includes a randomizer for my hashtags... with every run, it selects 10
  random hashtags from the list.
- add comments 
-  target mainly active accounts
- unfollow everyone who did not follow back within 12h
- unfollow the followers within 24h.

```python
import random
from instapy import InstaPy
from instapy import smart_run

insta_username = 'username'
insta_password = 'password'

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True,
                  browser_executable_path=r"C:\Program Files\Mozilla Firefox\firefox.exe")

# let's go! :>
with smart_run(session):
   hashtags = ['sunset', 'nature', 'photography', 'sky', 'travel','love', 'photooftheday', 'landscape' ,'ig', 'sunsetphotography', 'beach', 'naturephotography', 'instagood', 'summer' ,'sun', 'beautiful', 'sunrise', 'picoftheday', 'clouds', 'photo', 'sea', 'travelphotography', 'instagram', 'sunsets', 'landscapephotography']
    random.shuffle(hashtags)
    my_hashtags = hashtags[:10]

    # general settings
    session.set_dont_like(['sad', 'rain', 'depression'])
    session.set_do_follow(enabled=True, percentage=80, times=1)
    session.set_do_comment(enabled=True, percentage=80)
    session.set_comments([
        u'What an amazing shot! :heart_eyes: What do '
        u'you think of my recent shot?',
        u'What an amazing shot! :heart_eyes: I think '
        u'you might also like mine. :wink:',
        u'Wonderful!! :heart_eyes: Would be awesome if '
        u'you would checkout my photos as well!',
        u'Wonderful!! :heart_eyes: I would be honored '
        u'if you would checkout my images and tell me '
        u'what you think. :wink:',
        u'This is awesome!! :heart_eyes: Any feedback '
        u'for my photos? :wink:',
        u'This is awesome!! :heart_eyes:  maybe you '
        u'like my photos, too? :wink:',
        u'I really like the way you captured this. I '
        u'bet you like my photos, too :wink:',
        u'I really like the way you captured this. If '
        u'you have time, check out my photos, too. I '
        u'bet you will like them. :wink:',
        u'Great capture!! :smiley: Any feedback for my '
        u'recent shot? :wink:',
        u'Great capture!! :smiley: :thumbsup: What do '
        u'you think of my recent photo?'],
        media='Photo')
    #session.like_by_feed(amount=100, randomize=False, unfollow=True, interact=False)
    session.set_do_like(True, percentage=70)
    session.set_delimit_liking(enabled=True, max_likes=100, min_likes=0)
    session.set_delimit_commenting(enabled=True, max_comments=20, min_comments=0)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=3000,
                                    max_following=2000,
                                    min_followers=50,
                                    min_following=50)

    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "follows"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes_hourly=200,
                                 peak_likes_daily=585,
                                 peak_comments_hourly=80,
                                 peak_comments_daily=182,
                                 peak_follows_hourly=48,
                                 peak_follows_daily=None,
                                 peak_unfollows_hourly=35,
                                 peak_unfollows_daily=402,
                                 peak_server_calls_hourly=None,
                                 peak_server_calls_daily=4700)

    session.set_user_interact(amount=10, randomize=True, percentage=80)

    # activity
    session.like_by_tags(my_hashtags, amount=90, media=None)

    """ Joining Engagement Pods...
    """
    session.join_pods(topic='coding', engagement_mode='no_comments')

```

--- 

> ### ⭕ If you face any problem or want to know more about those functions please read the [official documentation](https://instapy.org/instance-settings).

Thank you,
Hope you like it.

**Comment by joeD268** [comment]
Hi @kmhmubin 

sadly the same error with file path added 

any ideas?

thanks

  raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: browsingContextFn().currentWindowGlobal is null

import random
from instapy import InstaPy
from instapy import smart_run

insta_username = ''
insta_password = ''

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True,
                  browser_executable_path=r"/Applications/Firefox.app/Contents/MacOS/firefox")

with smart_run(session):
    session.like_by_tags(["natgeo"], amount=10)

**Comment by kmhmubin** [comment]
> Hi @kmhmubin
> 
> sadly the same error with file path added
> 
> any ideas?
> 
> thanks
> 
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: TypeError: browsingContextFn().currentWindowGlobal is null
> 
> import random
> from instapy import InstaPy
> from instapy import smart_run
> 
> insta_username = ''
> insta_password = ''
> 
> # get a session!
> session = InstaPy(username=insta_username,
> password=insta_password,
> headless_browser=False,
> multi_logs=True,
> browser_executable_path=r"/Applications/Firefox.app/Contents/MacOS/firefox")
> 
> with smart_run(session):
> session.like_by_tags(["natgeo"], amount=10)

---
### 👉  [stackoverflow solution link](https://stackoverflow.com/questions/32175170/firefox-is-showing-cannot-find-firefox-binary-in-path-error-in-mac-os)

![image](https://user-images.githubusercontent.com/52270073/104853361-892f2980-592a-11eb-98d0-5ce0303e3cff.png)

hope this work

**Comment by PatrykPetryszen** [comment]
Hey there, is there any solution for it for Python 3.9 either for Windows or MAC?

**Comment by v0lumehi** [comment]
I found a fix for this for Ubuntu 20.
I upgraded my packages to the latest version using `apt`

After that what I did was:


Go to line 1953 of ".../instapy/util.py" and change "PFL" to "VOEL". Worked for me with Python 3.8

```
explicit_wait(browser, "PFL", [], logger, 10)
```

to

```
explicit_wait(browser, "VOEL", [], logger, 10)
```

and that got it working for me.

**Comment by v0lumehi** [comment]
> I found a fix for this for Ubuntu 20.
> I upgraded my packages to the latest version using `apt`
> 
> After that what I did was:
> 
> Go to line 1953 of ".../instapy/util.py" and change "PFL" to "VOEL". Worked for me with Python 3.8
> 
> ```
> explicit_wait(browser, "PFL", [], logger, 10)
> ```
> 
> to
> 
> ```
> explicit_wait(browser, "VOEL", [], logger, 10)
> ```
> 
> and that got it working for me.

It seems like this change is only necessary to create a new session cookie. The follow check doesn’t work with this change and InstaPy crashes. After changing back to “PFL” and using the previously generated cookie with “VOEL”, the bot runs properly.

TODO: Pass different parameter to method for cookie generation
