### ISSUE TITLE
Python39 - help me i am not configure the bot

### ISSUE THREAD

**Issue by Killed596** [InstaPy/InstaPy#5999]
nstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"
Error, unable to determine correct filename for 64bit linux
Traceback (most recent call last):
  File "/root/instapy-quickstart/quickstart.py", line 30, in <module>
    session = InstaPy(username=insta_username,
  File "/usr/local/lib/python3.9/dist-packages/instapy/instapy.py", line 322, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/usr/local/lib/python3.9/dist-packages/instapy/browser.py", line 131, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/usr/local/lib/python3.9/dist-packages/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/usr/local/lib/python3.9/dist-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/usr/local/lib/python3.9/dist-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/usr/local/lib/python3.9/dist-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit linux

**Comment by Tr1pke** [comment]
> nstaPy Version: 0.6.12
> ._. ._. ._. ._. ._. ._. ._.
> Workspace in use: "/root/InstaPy"
> Error, unable to determine correct filename for 64bit linux
> Traceback (most recent call last):
> File "/root/instapy-quickstart/quickstart.py", line 30, in 
> session = InstaPy(username=insta_username,
> File "/usr/local/lib/python3.9/dist-packages/instapy/instapy.py", line 322, in **init**
> self.browser, err_msg = set_selenium_local_session(
> File "/usr/local/lib/python3.9/dist-packages/instapy/browser.py", line 131, in set_selenium_local_session
> driver_path = geckodriver_path or get_geckodriver()
> File "/usr/local/lib/python3.9/dist-packages/instapy/browser.py", line 38, in get_geckodriver
> sym_path = gdd.download_and_install()[1]
> File "/usr/local/lib/python3.9/dist-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
> filename_with_path = self.download(version,
> File "/usr/local/lib/python3.9/dist-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
> download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
> File "/usr/local/lib/python3.9/dist-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
> raise RuntimeError(info_message)
> RuntimeError: Error, unable to determine correct filename for 64bit linux

**First step: DON’T WORK IN YOUR ROOT FOLDER !!!!!**

**Comment by pooja-anandani** [comment]
Make an environment and develop it is always a good practice.

**Comment by elulcao** [comment]
Try with Python3.8
Check that geckodriver and Firefox paths are well defined for the bot Session
Check the doc for the example, [InstaPy](https://instapy.org)
Let us know if that makes a difference
thanks

**Comment by its-ogawa** [comment]
Did you solve this problem?
I still get this problem.

**Comment by Tr1pke** [comment]
yea solved it almost a year ago

**Comment by its-ogawa** [comment]
I think permissions are one of the causes of this problem.

However, your advice of specifying a working directory other than the root folder will still cause this error.
