### ISSUE TITLE
Python39 - don`t start

### ISSUE THREAD

**Issue by definitelyDefi** [InstaPy/InstaPy#6001]
Workspace in use: "C:/Users/username/InstaPy"
Traceback (most recent call last):
  File "c:\Users\username\Desktop\instapy-quickstart-master\quickstart.py", line 12, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 322, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\browser.py", line 140, in set_selenium_local_session
    browser.install_addon(create_firefox_extension(), temporary=True)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\browser.py", line 48, in create_firefox_extension
    with zipfile.ZipFile(zip_file, "w", zipfile.ZIP_DEFLATED, False) as zipf:
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1239, in __init__
    self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\username\\InstaPy\\assets\\extension.xpi'

session.follow_likers(['konch.memes'], photos_grab_amount = 1, follow_likers_per_photo = 100, randomize=True, sleep_delay=3, interact=False)

**Comment by elulcao** [comment]
Could you try with Python3.8
Please let us know if that helps 
thanks

**Comment by johnc2k** [comment]
I also get this error but on Python 3.8.6
