### ISSUE TITLE
Python39 - Error: The element reference of <button class="sqdOP  L3NKy _4pI4F  y3zKF     A086a" type="button">

### ISSUE THREAD

**Issue by nmania** [InstaPy/InstaPy#6008]
My instapy keeps crashing after running for a few minutes with the following error.
I am running the latest commit of instapy on latest firefox on Windows 10.
Any Help would be appreciated.

Traceback (most recent call last):
  File "E:\instapy\quickstart.py", line 50, in <module>
    session.follow_commenters(['average_jonas'], amount=200, daysold=365, max_pic = 5, sleep_delay=100, interact=True)
  File "C:\Users\Nishant\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 939, in follow_commenters
    followed = self.follow_by_list(
  File "C:\Users\Nishant\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1215, in follow_by_list
    follow_state, msg = follow_user(
  File "C:\Users\Nishant\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\unfollow_util.py", line 555, in follow_user
    follow_state, msg = verify_action(
  File "C:\Users\Nishant\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\unfollow_util.py", line 1523, in verify_action
    following_status, follow_button = get_following_status(
  File "C:\Users\Nishant\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\follow_util.py", line 82, in get_following_status
    following_status = follow_button.text
  File "C:\Users\Nishant\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "C:\Users\Nishant\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Nishant\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Nishant\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="sqdOP  L3NKy _4pI4F  y3zKF     A086a" type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

**Comment by elulcao** [comment]
Could you try with Python 3.8
Please let us now if that makes a difference.
