### ISSUE TITLE
Python39 - currentWindowGlobal is `null

### ISSUE THREAD

**Issue by Export-Install** [InstaPy/InstaPy#6011]
It successfully login, but then my mozilla suddenly close with this error...

```
`INFO [2021-01-08 01:37:18] [gyogu4]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-01-08 01:37:18] [gyogu4]  - window.navigator.webdriver response: None
INFO [2021-01-08 01:37:18] [gyogu4]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...

INFO [2021-01-08 01:37:45] [gyogu4]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 1.1 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-01-08 01:37:45] [gyogu4]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "C:\Users\Streamer.gg\Desktop\VB_File\instapy-quickstart-master\quickstart.py", line 26, in <module>
    with smart_run(session):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "C:\Users\Streamer.gg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instapy\util.py", line 1920, in smart_run  
    session.login()
  File "C:\Users\Streamer.gg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instapy\instapy.py", line 425, in login    
    if not login_user(
  File "C:\Users\Streamer.gg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instapy\login_util.py", line 362, in login_user
    dismiss_get_app_offer(browser, logger)
  File "C:\Users\Streamer.gg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instapy\login_util.py", line 466, in dismiss_get_app_offer
    offer_loaded = explicit_wait(
  File "C:\Users\Streamer.gg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instapy\util.py", line 1784, in explicit_wait
    result = wait.until(condition)
  File "C:\Users\Streamer.gg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Streamer.gg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Users\Streamer.gg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Users\Streamer.gg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Users\Streamer.gg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Streamer.gg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Streamer.gg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: browsingContextFn().currentWindowGlobal is null`
```

**Comment by Export-Install** [comment]
can someone help with this error on my windows10?

**Comment by skoenig** [comment]
Possible duplicate of #5989

**Comment by elulcao** [comment]
Try with Python 3.8,
Please let us know if that makes a difference.

**Comment by Dekwin** [comment]
works on`python:3.7` image, but on 3.8 this issue appears.
