### ISSUE TITLE
Selenium Errors 

### ISSUE THREAD

**Issue by digitizesuccess** [InstaPy/InstaPy#6015]
Script will not start. I am working on Mac OS Big Sur M1 and using Python 3.7.2

When starting script after creating the workspace I get the following Selenium errors

Workspace in use: "/Users/using/user/user/user"
Traceback (most recent call last):
  File "/Users/rosie/Desktop/InstaPy-master/GF_Test.py", line 25, in <module>
    multi_logs=True)
  File "/Users/rosie/Desktop/InstaPy-master/instapy/instapy.py", line 337, in __init__
    geckodriver_log_level,
  File "/Users/rosie/Desktop/InstaPy-master/instapy/browser.py", line 127, in set_selenium_local_session
    options=firefox_options,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by elulcao** [comment]
Check that FireFox and Geckodriver are accessible and well defined for the InstaPy session.
There is an example in the official documentation
[InstaPy](https://instapy.org)

**Comment by Jasiri-w** [comment]
### A Solution:
https://github.com/timgrossmann/InstaPy/issues/6070#issuecomment-815819613

I don't know how this works specifically for MacOS but For anyone that has found reinstalling Firefox on Windows unhelpful, this worked for me instead by using a different parameter ( `browser_executable_path = r"C:[Custom Location]" )` I found in the InstaPy class init function
