### ISSUE TITLE
Timed out with failure while explicitly waiting until visibility of element located! (locked on second confim about coockies)

### ISSUE THREAD

**Issue by MarcoLavoro** [InstaPy/InstaPy#6069]
## Expected Behavior
it work
## Current Behavior

stop after the first accept coockie question

error:

Timed out with failure while explicitly waiting until visibility of element located!

LOG:

ma@ma-VirtualBox:~$ python3 '/home/ma/Scrivania/sd/pyton script gadget.py'
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/ma/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-02-06 23:20:23] [best_gadget_addiction]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-02-06 23:20:30] [best_gadget_addiction]  - Cookie file not found, creating cookie...
INFO [2021-02-06 23:21:09] [best_gadget_addiction]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20210206-232114.html
**********************************************************************

INFO [2021-02-06 23:21:15] [best_gadget_addiction]  Sessional Live Report:
|> No any statistics to show

[Session lasted 1.08 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-02-06 23:21:15] [best_gadget_addiction]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "/home/ma/Scrivania/sd/pyton script gadget.py", line 44, in <module>
    with smart_run(session):
  File "/usr/lib/python3.8/contextlib.py", line 115, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield

## InstaPy configuration
exatly as this guide
https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_To_DO_Ubuntu_on_Digital_Ocean.md
On
Ubuntu last version

Someone can help me?

**Comment by MarcoLavoro** [comment]
the problem not occur anymore after I accepted the second confimation manually, but i have to do 3 times manually and now seems to work correctly

Nice!

**Comment by Tr1pke** [comment]
have the same problem
second "cookie" page it gets stuck have to click manually , and then i also have to click manually on the LOG IN button
