### ISSUE TITLE
Python39 - #Question - selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' 

### ISSUE THREAD

**Issue by timekeepr** [InstaPy/InstaPy#6073]
Hi, I got problem when trying to using windows_start

Something like this appear 

Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\instapy-quickstart-master\quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

Could someone help me with the solution please? 

Thank you

**Comment by elulcao** [comment]
Could you set the complete path for FF and geckodriver in the constructor,
that seems to be issue, since the binaries couldn't be found.

**Comment by IlTibetano** [comment]
I've the same error message. try to install firefox, now it works for me.

**Comment by Jasiri-w** [comment]
For anyone that has found reinstalling Firefox unhelpful, this worked for me instead using a different parameter I found in the InstaPy class __init__:

### Solution:
https://github.com/timgrossmann/InstaPy/issues/6070#issuecomment-815819613
