### ISSUE TITLE
Not sure what i need to download in order to run quickstart.py

### ISSUE THREAD

**Issue by KaiHatchman** [InstaPy/InstaPy#608]
I have edited to document to my requirements and have also downloaded the chrome driver and python off of the website and all the requirements in terminal on my apple mac.

it comes up with this when i'm in terminal and type : python quickstart1.py

Traceback (most recent call last):
  File "quickstart1.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password)
  File "/Users/Desktop/InstaPy-master/instapy/instapy.py", line 100, in __init__
    self.set_selenium_local_session()
  File "/Users/Desktop/InstaPy-master/instapy/instapy.py", line 139, in set_selenium_local_session
    self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

I am a beginner to coding so don't have much of a clue as the what any of the above means! any help would be much appreciated!

**Comment by KaiHatchman** [comment]
have edited a few things and is now coming up with this

Traceback (most recent call last):
  File "quickstart1.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/Desktop/InstaPy-master/instapy/__init__.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/Desktop/InstaPy-master/instapy/instapy.py", line 43, in <module>
    class InstaPy:
  File "/Users/Desktop/InstaPy-master/instapy/instapy.py", line 46, in InstaPy
    def __init__(self, username=..., password=..., nogui=False, selenium_local_session=True, use_firefox=False, page_delay=25):
NameError: name '...' is not defined

trying to look up online what i am meant to do but am not having any luck

**Comment by gitpatrickhub** [comment]
@mazehoffman did you place the chrome driver in the assets folder? Also, include your quickstart1.py file code here.

**Comment by KaiHatchman** [comment]
Got it working!
