### ISSUE TITLE
Stale element reference closes the session 

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#6081]
## Expected Behavior
I want InstaPy to follow x user's followers. With x delays.

## Current Behavior
InstaPy works for a few minutes and follows a few people (5-10) and then crashes with:

Traceback (most recent call last):
  File "quickstart.py", line 37, in <module>
    schedule.run_pending()
  File "/home/pi/.local/lib/python3.7/site-packages/schedule/__init__.py", line 592, in run_pending
    default_scheduler.run_pending()
  File "/home/pi/.local/lib/python3.7/site-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/home/pi/.local/lib/python3.7/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/home/pi/.local/lib/python3.7/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "quickstart.py", line 21, in job
    session.follow_user_followers(users, amount=50, randomize=False)
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 3558, in follow_user_followers
    person, self.follow_times, sleep_delay, interact
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 1242, in follow_by_list
    self.logfolder,
  File "/home/pi/Desktop/InstaPy-master/instapy/unfollow_util.py", line 554, in follow_user
    click_visibly(browser, follow_button)  # click to follow
  File "/home/pi/Desktop/InstaPy-master/instapy/util.py", line 1977, in click_visibly
    if element.is_displayed():
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 488, in is_displayed
    self)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)

**selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="sqdOP  L3NKy _4pI4F  y3zKF     " type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed**

## InstaPy configuration

import random
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace
import schedule
import time

def job():
    session = InstaPy(username='xxx', password='xxx.', headless_browser=True)
    with smart_run(session):
        users = session.target_list("/home/pi/Desktop/InstaPy-master/users.txt")
        session.set_action_delays(enabled=True, follow=60, randomize=True, random_range_from=30, random_range_to=90)
        session.set_action_delays(enabled=True, unfollow=60, randomize=True, random_range_from=30, random_range_to=90)
        session.set_quota_supervisor(enabled=True, peak_follows_daily=560, peak_follows_hourly=56, peak_unfollows_hourly=49, peak_unfollows_daily=500, sleep_after=["follows_h", "unfollows_d"], sleepyhead=True, stochastic_flow=True, notify_me=True)
        session.set_skip_users(skip_private=False, 
                       skip_no_profile_pic=False,
                       no_profile_pic_percentage=100,
                       skip_business=True,
                       skip_non_business=False,
                       business_percentage=80,)
        session.follow_user_followers(users, amount=50, randomize=False)

schedule.every().day.at("08:21").do(job)
schedule.every().day.at("10:54").do(job)
schedule.every().day.at("13:22").do(job)
schedule.every().day.at("16:56").do(job)
schedule.every().day.at("19:34").do(job)
schedule.every().day.at("21:57").do(job)
schedule.every().day.at("23:45").do(job)

while True:
  schedule.run_pending()
  time.sleep(10)
  

## My setup
Raspberry pi 3
Raspberry pi OS Full
Python 3.7.3
Geckodriver 0.23
Firefox 60

**Comment by Booleboole** [comment]
Any news about the issue?
