### ISSUE TITLE
instaPy don't start after install

### ISSUE THREAD

**Issue by orhan-drsn** [InstaPy/InstaPy#6082]
## Expected Behavior
InstaPy should start and login

## Current Behavior
Error, unable to determine correct filename for 64bit linux Traceback (most recent call last): 
File "quickstart.py", line 14, in <module> session = InstaPy(username=insta_username, File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 322, in __init__ self.browser, err_msg = set_selenium_local_session( File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 131, in set_selenium_local_session driver_path = geckodriver_path or get_geckodriver() 
File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 38, in get_geckodriver sym_path = gdd.download_and_install()[1] File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install filename_with_path = self.download(version, File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download download_url = self.get_download_url(version, os_name=os_name, bitness=bitness) 
File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url raise RuntimeError(info_message) Runtime

Error: Error, unable to determine correct filename for 64bit linux

## InstaPy configuration
Ubuntu 20.04 LTS (64-bit)
I used [this](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_To_DO_Ubuntu_on_Digital_Ocean.md) guide to install.

**Comment by orhan-drsn** [comment]
Thanks to everyone in advise!

**Comment by orhan-drsn** [comment]
The Solution cames from here: https://github.com/timgrossmann/InstaPy/issues/5779#issuecomment-706201591

Now InstaPy is starting, but it's not possible to Login.
I think it's because second [Cookies Page](https://github.com/timgrossmann/InstaPy/issues/6060).
The mentioned solution doesn't work for me.

**Comment by elulcao** [comment]
What is the problem then, the `for 64bit linux` or the ` it's not possible to Login`?
if this is a different issue, please file a new issue and close the one is solved.

**Comment by Tr1pke** [comment]
> The Solution cames from here: [#5779 (comment)](https://github.com/timgrossmann/InstaPy/issues/5779#issuecomment-706201591)
> 
> Now InstaPy is starting, but it's not possible to Login.
> I think it's because second [Cookies Page](https://github.com/timgrossmann/InstaPy/issues/6060).
> The mentioned solution doesn't work for me.

manually click on the second agree and then click on login, close you vm and voila
