### ISSUE TITLE
My bot stops (InsecureCertificateException)

### ISSUE THREAD

**Issue by RhaegarTargaryen55** [InstaPy/InstaPy#6083]
It's working fine but then stops, I use 'like_by_tag_interact_unfollow' template. Any help? please

`Traceback (most recent call last):
  File "like_by_tag_interact_unfollow.py", line 63, in <module>
    amount=random.randint(50, 100), interact=True)
  File "/Users/NoOne/Documents/Instabot/InstaPy-master/instapy/instapy.py", line 2004, in like_by_tags
    liked_img,
  File "/Users/NoOne/Documents/Instabot/InstaPy-master/instapy/like_util.py", line 806, in like_image
    if not verify_liked_image(browser, logger):
  File "/Users/NoOne/Documents/Instabot/InstaPy-master/instapy/like_util.py", line 832, in verify_liked_image
    browser.refresh()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 831, in refresh
    self.execute(Command.REFRESH)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InsecureCertificateException: Message: `

**Comment by elulcao** [comment]
Try the following in browser.py

```python
118 # geckodriver log in specific user logfolder
119 geckodriver_log = "{}geckodriver.log".format(logfolder)
120 firefox_profile.accept_untrusted_certs = True
121
```

**Comment by RhaegarTargaryen55** [comment]
doesnt work

> Try the following in browser.py
> 
> ```python
> 118 # geckodriver log in specific user logfolder
> 119 geckodriver_log = "{}geckodriver.log".format(logfolder)
> 120 firefox_profile.accept_untrusted_certs = True
> 121
> ```
