### ISSUE TITLE
Selenium error (os error 111) when running 0.6.13

### ISSUE THREAD

**Issue by skiwlkr** [InstaPy/InstaPy#6088]
## Expected Behavior
 Running instapy on a Debian10 Docker image
and getting a selenium error

 ## Current Behavior

selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)

referencing an old issue here
https://github.com/timgrossmann/InstaPy/issues/5822

My Specs:
python: 3.7.4
Selenium version: 3.141.0
Mozilla Firefox 78.7.0esr
geckodriver 0.29.0
InstaPy version: 0.6.13

I'm running the latest instapy build, but I can't get it to work. Any Ideas? 
```
Traceback (most recent call last):
  File "quickstart.py", line 26, in <module>
    headless_browser=True)
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 338, in __init__
    geckodriver_log_level,
  File "/usr/local/lib/python3.7/site-packages/instapy/browser.py", line 127, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)
```
> 
> ## InstaPy configuration
> Logging:
> 
> ```
> def get_session():
>     session = InstaPy(username=insta_username,
>                       password=insta_password,
>                       headless_browser=True)
>     return session
> ```
> 
> Selenium version: 3.141.0
> Mozilla Firefox 81.0
> geckodriver 0.27.0
> InstaPy version: 0.6.6
> 
> Thank you!

InstaPy version is 0.6.6 but current release is 0.6.11
Try the latest one.

_Originally posted by @elulcao in https://github.com/timgrossmann/InstaPy/issues/5822#issuecomment-706719522_

Thanks for helping!

**Comment by skiwlkr** [comment]
I also found the the instapy docker image you deployed and did a test with 6.12 and 6.13 and get the same selenium error... maybe the connection is blocked. I don't know.
https://github.com/InstaPy/instapy-docker

**Comment by elulcao** [comment]
Could you try this in your local:

1. in your docker directory, replace the Instapy version from 12 to 13: `instapy==0.6.13`
2. Run the following in order to create and run the image:
`path to your Instapy Workspace` usually the HOME in your machine.

```bash
docker pull instapy/instapy:latest && \
docker run \
    --rm \
    --name instapy \
    -v <path to your config file>/docker_quickstart.py:/code/docker_quickstart.py:ro \
    -v <path to your Instapy Workspace>:/code/InstaPy:rw \
    -v <path to your Instapy Workspace DB>/db:/root/InstaPy/db:rw \
    -v <path to your Instapy Workspace LOGS>/logs:/root/InstaPy/logs:rw \
    instapy/instapy:latest || exit 1;
```

I created a bash script, that output looks like:

```bash
sh docker_instapy_1.sh
___ starting docker container...
latest: Pulling from instapy/instapy
6ec7b7d162b2: Pull complete
80ff6536d04b: Pull complete
6c51d3836e95: Pull complete
6ce84404158b: Pull complete
6e001f327b45: Pull complete
f626b0fe1650: Pull complete
4f218f175dc7: Pull complete
Digest: sha256:ea52941a40810919e3a663ca24be7fdad2b7e4c98a7a1635ec8de278c1d00170
Status: Downloaded newer image for instapy/instapy:latest
docker.io/instapy/instapy:latest
2595kb [00:00, 7758.52kb/s]
INFO [2021-02-22 14:49:01] [internet]  Session started!
INFO [2021-02-22 14:49:01] [internet]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-02-22 14:49:02] [internet]  - Internet Connection Status: ok
INFO [2021-02-22 14:49:02] [internet]  - Current IP is "0.0.0.0" and it's from "AC/DC"
INFO [2021-02-22 14:49:02] [internet]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-02-22 14:49:02] [internet]  - window.navigator.webdriver response: None
INFO [2021-02-22 14:49:02] [internet]  - Hide Selenium Extension: ok
INFO [2021-02-22 14:49:05] [internet]  - Cookie file for user 'internet' loaded...
WARNING [2021-02-22 14:49:07] [internet]  - Issue with cookie for user 'internet'. Creating new cookie...
INFO [2021-02-22 14:49:07] [internet]  - Deleting browser cookies...
INFO [2021-02-22 14:49:33] [internet]  - Do not save Login Info by now...
INFO [2021-02-22 14:49:46] [internet]  Logged in successfully!
INFO [2021-02-22 14:49:46] [internet]  Saving account progress...
INFO [2021-02-22 14:50:00] [internet]  Getting active users who liked the latest 5 posts:
 ~collecting the usernames from posts with the boundary of 500
```

**Comment by skiwlkr** [comment]
As always, thanks for your fast help elulcao.

I executed the script as you mentioned above. It somehow works but then it doesn't.
The docker_quickstart.py gets loaded, the db and log files are created at the right place but... 
it crashes at the same point, as soon as the session should start

```
> docker pull instapy/instapy:latest && \
> docker run \
>     --rm \
>     --name instapy \
>     -v /volume1/docker/python/docker_quickstart.py:/code/docker_quickstart.py:ro \
>     -v /volume1/docker/workdir:/code/InstaPy:rw \
>     -v /volume1/docker/workdir/db:/root/InstaPy/db:rw \
>     -v /volume1/docker/workdir/logs:/root/InstaPy/logs:rw \
>     instapy/instapy:latest || exit 1;
latest: Pulling from instapy/instapy
6ec7b7d162b2: Pull complete
80ff6536d04b: Pull complete
6c51d3836e95: Pull complete
6ce84404158b: Pull complete
6e001f327b45: Pull complete
f626b0fe1650: Pull complete
4f218f175dc7: Pull complete
Digest: sha256:ea52941a40810919e3a663ca24be7fdad2b7e4c98a7a1635ec8de278c1d00170
Status: Downloaded newer image for instapy/instapy:latest
2595kb [00:00, 7263.64kb/s]
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/root/InstaPy"
Traceback (most recent call last):
  File "docker_quickstart.py", line 18, in <module>
    bot = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 338, in __init__
    geckodriver_log_level,
  File "/usr/local/lib/python3.7/site-packages/instapy/browser.py", line 127, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)
```


I'm using the docker_quickstart.py for testing purpose. Could something be wrong with it?

```
from instapy import InstaPy
from instapy.util import smart_run


insta_username = "xxxxxxxxxxxxx"
insta_password = "xxxxxxxxxx"

dont_like = ["food", "girl", "hot"]
ignore_words = ["pizza"]
friend_list = ["friend1", "friend2", "friend3"]


bot = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
with smart_run(bot):
    bot.set_relationship_bounds(
        enabled=True,
        potency_ratio=-1.21,
        delimit_by_numbers=True,
        max_followers=4590,
        max_following=5555,
        min_followers=45,
        min_following=77,
    )
    bot.set_do_comment(True, percentage=10)
    bot.set_comments(["Cool!", "Awesome!", "Nice!"])
    bot.set_dont_include(friend_list)
    bot.set_dont_like(dont_like)
    bot.set_ignore_if_contains(ignore_words)
    bot.like_by_tags(["dog", "#cat"], amount=100)
    bot.end()
```

Thanks again!

**Comment by elulcao** [comment]
Hello @skiwlkr 
The `111` error is not part of InstaPy logic, but part of Docker layer,
I tried to reproduce in my local, but everything works well at my side.
Could you add this `geckodriver_log_level="trace"` to the constructor's
session? then check the geckodriver.log in order to see why the connection
failed, there must be a hint about why FF cannot reach IG.

```bash
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)
```

**Comment by elulcao** [comment]
Using a VM (debian 10) and /instapy-docker-master,
the session could be started as expected. 

```bash
debian@debian:~$ uname -a
Linux debian 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
debian@debian:~$ 
```

```bash
debian@debian:~/Downloads/instapy-docker-master$ sudo sh start.sh 
[sudo] password for debian: 
___ starting docker container...
latest: Pulling from instapy/instapy
6ec7b7d162b2: Pull complete 
80ff6536d04b: Pull complete 
6c51d3836e95: Pull complete 
6ce84404158b: Pull complete 
6e001f327b45: Pull complete 
f626b0fe1650: Pull complete 
4f218f175dc7: Pull complete 
Digest: sha256:ea52941a40810919e3a663ca24be7fdad2b7e4c98a7a1635ec8de278c1d00170
Status: Downloaded newer image for instapy/instapy:latest
2595kb [00:00, 7006.63kb/s]                          
INFO [2021-02-27 17:18:44] [internet]  Session started!
INFO [2021-02-27 17:18:44] [internet]  -- Connection Checklist [1/2] (Internet Connection Status)
```

```bash
debian@debian:~/Downloads/instapy-docker-master$ sudo docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Sun, 14 Jun 2020 22:12:29 +0200
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Sun Jun 14 20:12:29 2020
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by skiwlkr** [comment]
Hey!
Thanks for your reply and for looking into it.
I wasn't sure were to put the line `geckodriver_log_level="trace"`
Should it be placed in the docker script to start the instapy instance?
Or is it a command für the docker_quickstart.py

I found a geckodriver.log in the Instapy log folder. Maybe this is what you looking for?

```
1614074591840	geckodriver	INFO	Listening on 127.0.0.1:43111
1614074591881	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile81AoQL"
*** You are running in headless mode.

(firefox:13): GLib-GObject-WARNING **: 10:03:21.222: invalid (NULL) pointer instance

(firefox:13): GLib-GObject-CRITICAL **: 10:03:21.315: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(/opt/firefox/firefox-bin:70): GLib-GObject-WARNING **: 10:03:54.304: invalid (NULL) pointer instance

(/opt/firefox/firefox-bin:70): GLib-GObject-CRITICAL **: 10:03:54.492: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(/opt/firefox/firefox-bin:75): GLib-GObject-WARNING **: 10:03:55.697: invalid (NULL) pointer instance

(/opt/firefox/firefox-bin:75): GLib-GObject-CRITICAL **: 10:03:55.697: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Exiting due to channel error.
Exiting due to channel error.
```

I'm running the instapy docker image on a synology. So if the container gets the error and stops I have no access to the file structure of it. I don't know if this make any sense to you. I'm just started to slowly tap into docker.
I assumed the Instapy docker-image is a closed system with no room for modifications.

**Comment by elulcao** [comment]
I partially reproduced the issue, however the `G_TYPE_CHECK_INSTANCE ` is not the problem
at all, in my case the browser started after the internal assertion.

Could you confirm that you are starting the docker as root (privileged user)? 
We need to be sure that your container is able to reach the internet.

```bash
session = InstaPy(
    username="internet",
    password="qinDak-dusru4",
    geckodriver_log_level="trace",
    headless_browser=True,
)
``` 

```bash
docker run -it instapy/instapy /bin/bash
root@26ce8f0f9ac3:/code#
root@26ce8f0f9ac3:/code# ldd `which firefox`
        linux-vdso.so.1 (0x00007ffc27b34000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6453c73000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6453c6e000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6453aea000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6453967000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f645394d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f645378c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6453c9b000)

root@26ce8f0f9ac3:/code# firefox --headless
*** You are running in headless mode.
[GFX1-]: glxtest: libpci missing
[GFX1-]: glxtest: libGL.so.1 missing
[GFX1-]: glxtest: libEGL missing
[GFX1-]: No GPUs detected via PCI

(/opt/firefox/firefox-bin:276): GLib-GObject-CRITICAL **: 01:50:03.908: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(/opt/firefox/firefox-bin:337): GLib-GObject-CRITICAL **: 01:50:04.602: g_object_set: assertion 'G_IS_OBJECT (object)' failed
(/opt/firefox/firefox-bin:355): GLib-GObject-CRITICAL **: 01:50:04.718: g_object_set: assertion 'G_IS_OBJECT (object)' failed
(/opt/firefox/firefox-bin:386): GLib-GObject-CRITICAL **: 01:50:04.964: g_object_set: assertion 'G_IS_OBJECT (object)' failed
^CExiting due to channel error. << CTRL + C, but Firefox was running in background 
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.

root@26ce8f0f9ac3:/code#
```


```bash
1614302420320	geckodriver	INFO	Listening on 127.0.0.1:48157
1614302420327	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileEZJbve"
1614302420329	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:46815
*** You are running in headless mode.

(firefox:13): GLib-GObject-WARNING **: 01:20:20.632: invalid (NULL) pointer instance

(firefox:13): GLib-GObject-CRITICAL **: 01:20:20.633: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
1614302420671	Marionette	TRACE	Marionette enabled
1614302420711	Marionette	TRACE	Received observer notification toplevel-window-ready

(/opt/firefox/firefox-bin:62): GLib-GObject-WARNING **: 01:20:21.094: invalid (NULL) pointer instance

(/opt/firefox/firefox-bin:62): GLib-GObject-CRITICAL **: 01:20:21.095: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(/opt/firefox/firefox-bin:79): GLib-GObject-WARNING **: 01:20:21.178: invalid (NULL) pointer instance

(/opt/firefox/firefox-bin:79): GLib-GObject-CRITICAL **: 01:20:21.179: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
1614302422424	Marionette	TRACE	Received observer notification marionette-startup-requested
1614302422425	Marionette	TRACE	Waiting until startup recorder finished recording startup scripts...
1614302422450	Marionette	TRACE	All scripts recorded.
```

**Comment by skiwlkr** [comment]
Yes, I'm starting the container as root.
I'm running several docker containers right now, so far they have no problems reaching the internet.
Thanks. Didn't know how to enter the bash. I hope this helps.
That's what I got out of the console:

```
root@Neon:~# docker run -it instapy/instapy /bin/bash
root@007538a45c0b:/code# ldd `which firefox`
        linux-vdso.so.1 (0x00007ffd0a6dc000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f653cd5b000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f653cd56000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f653cbd2000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f653ca4f000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f653ca35000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f653c874000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f653cd83000)
root@007538a45c0b:/code# firefox --headless
*** You are running in headless mode.

(firefox:14): GLib-GObject-WARNING **: 15:28:15.415: invalid (NULL) pointer instance

(firefox:14): GLib-GObject-CRITICAL **: 15:28:15.794: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(/opt/firefox/firefox-bin:66): GLib-GObject-WARNING **: 15:29:01.236: invalid (NULL) pointer instance

(/opt/firefox/firefox-bin:66): GLib-GObject-CRITICAL **: 15:29:01.723: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(/opt/firefox/firefox-bin:82): GLib-GObject-WARNING **: 15:29:22.919: invalid (NULL) pointer instance

(/opt/firefox/firefox-bin:82): GLib-GObject-CRITICAL **: 15:29:22.933: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed


(/opt/firefox/firefox-bin:132): GLib-GObject-WARNING **: 15:32:42.683: invalid (NULL) pointer instance

(/opt/firefox/firefox-bin:132): GLib-GObject-CRITICAL **: 15:32:42.904: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Unable to init server: Could not connect: Connection refused
```

**Comment by elulcao** [comment]
mmm, even if you run FF in headless mode the app behaves like a GUI one. My suggestion is to review your 'X' configuration in the Host. 
Here a link for reference: [link headless](http://elementalselenium.com/tips/38-headless)

**Comment by skiwlkr** [comment]
I think the problem resolved itself.
I recently bought a new server and it instantly worked. I don't know what the problem was.

Unfortunatley the current version has a time out problem when trying to accept the cookie
`Timed out with failure while explicitly waiting until visibility of element located!`

This seems to be fixed in 0.6.14.
do you know if and when do you roll it out for the docker image?

**Comment by PS1Online** [comment]
I too am waiting for version 0.6.14.
When it comes out? The version 0.6.13 bug is a blocking bug.

**Comment by elulcao** [comment]
> I too am waiting for version 0.6.14.
> When it comes out? The version 0.6.13 bug is a blocking bug.

They are some commits for UNRELEASED versions, the current version remains the same for now.
If you want the lates changes clone/download the repo.
if you are using pip for installing instaPy append the latest commit to the -U upgrade process.
