### ISSUE TITLE
essage: The element reference of <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed`

### ISSUE THREAD

**Issue by MarcoLavoro** [InstaPy/InstaPy#6091]
## Expected Behavior
Work Properly
## Current Behavior
I get this error after some hours of works

```python
`Traceback (most recent call last):
  File "/home/ma/Desktop/sd/pagina gadget.py", line 309, in <module>
    session.interact_user_followers(random_targets, amount=amountIteraction, randomize=True)
  File "/home/ma/.local/lib/python3.8/site-packages/instapy/instapy.py", line 3207, in interact_user_followers
    self.interact_by_users(
  File "/home/ma/.local/lib/python3.8/site-packages/instapy/instapy.py", line 2499, in interact_by_users
    links = get_links_for_username(
  File "/home/ma/.local/lib/python3.8/site-packages/instapy/like_util.py", line 463, in get_links_for_username
    following_status, _ = get_following_status(
  File "/home/ma/.local/lib/python3.8/site-packages/instapy/follow_util.py", line 82, in get_following_status
    following_status = follow_button.text
  File "/home/ma/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/home/ma/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ma/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ma/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed`
```

**Comment by chuddyni** [comment]
```try:
    following_status = follow_button.text  #this is what normally fails
except:
    reload_webpage(browser)
    sleep(5)
    following_status, follow_button = get_following_status(browser, track, username, person, person_id, logger, logfolder)```
paste this to follow_util.py instead of  ```following_status = follow_button.text ```

**Comment by chuddyni** [comment]
Just edit click_visibly function in util.py to:
```
def click_visibly(browser, element):
    """ Click as the element become visible """
    if not element.is_displayed():
        reload_webpage(browser)
        sleep(10)
        click_element(browser, element)

    if element.is_displayed():
        click_element(browser, element)


    else:
        browser.execute_script(
            "arguments[0].style.visibility = 'visible'; "
            "arguments[0].style.height = '10px'; "
            "arguments[0].style.width = '10px'; "
            "arguments[0].style.opacity = 1",
            element,
        )
        # update server calls
        update_activity(browser, state=None)

        click_element(browser, element)

    return True
```
