### ISSUE TITLE
 The element reference of <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   "> is stale;

### ISSUE THREAD

**Issue by chuddyni** [InstaPy/InstaPy#6095]
## Current Behavior
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 592, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "main.py", line 42, in job
    session.follow_user_followers(['cypriano_italiano'],
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 3545, in follow_user_followers
    followed = self.follow_by_list(
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 1222, in follow_by_list
    follow_state, msg = follow_user(
  File "/usr/local/lib/python3.8/dist-packages/instapy/unfollow_util.py", line 554, in follow_user
    click_visibly(browser, follow_button)  # click to follow
  File "/usr/local/lib/python3.8/dist-packages/instapy/util.py", line 1981, in click_visibly
    browser.execute_script(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

**Comment by elulcao** [comment]
Duplicate of #6091

**Comment by chuddyni** [comment]
Just edit click_visibly function in util.py to:
```
def click_visibly(browser, element):
    """ Click as the element become visible """
    if not element.is_displayed():
        reload_webpage(browser)
        sleep(10)
        click_element(browser, element)

    if element.is_displayed():
        click_element(browser, element)


    else:
        browser.execute_script(
            "arguments[0].style.visibility = 'visible'; "
            "arguments[0].style.height = '10px'; "
            "arguments[0].style.width = '10px'; "
            "arguments[0].style.opacity = 1",
            element,
        )
        # update server calls
        update_activity(browser, state=None)

        click_element(browser, element)

    return True
```
