### ISSUE TITLE
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#6123]
## Current Behavior
```
USER@InstaPyUSER:~$ python3.8 USER.triathlon.py
Traceback (most recent call last):
  File "USER.triathlon.py", line 1, in <module>
    from instapy import InstaPy
  File "/home/USER/.local/lib/python3.8/site-packages/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/home/USER/.local/lib/python3.8/site-packages/instapy/instapy.py", line 33, in <module>
    from .clarifai_util import check_image
  File "/home/USER/.local/lib/python3.8/site-packages/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "/home/USER/.local/lib/python3.8/site-packages/clarifai/rest/__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "/home/USER/.local/lib/python3.8/site-packages/clarifai/rest/client.py", line 29, in <module>
    from clarifai.rest.grpc.grpc_json_channel import GRPCJSONChannel, dict_to_protobuf, protobuf_to_dict
  File "/home/USER/.local/lib/python3.8/site-packages/clarifai/rest/grpc/grpc_json_channel.py", line 13, in <module>
    from clarifai.rest.grpc.proto.clarifai.api.endpoint_pb2 import _V2
  File "/home/USER/.local/lib/python3.8/site-packages/clarifai/rest/grpc/proto/clarifai/api/endpoint_pb2.py", line 33, in <module>
    from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
  File "/home/USER/.local/lib/python3.8/site-packages/google/api/annotations_pb2.py", line 30, in <module>
    from google.api import http_pb2 as google_dot_api_dot_http__pb2
  File "/home/USER/.local/lib/python3.8/site-packages/google/api/http_pb2.py", line 35, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
USER@InstaPyUSER:~$
```

## InstaPy configuration

Any suggestions what i can do?

**Comment by Tr1pke** [comment]
solution was:

export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
locale-gen en_US.UTF-8
sudo dpkg-reconfigure locales
pip3 install --upgrade pip


cd ~
wget "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
sudo dpkg -i google-chrome-stable_current_amd64.deb
sudo apt-get install -y -f
sudo rm google-chrome-stable_current_amd64.deb

pip3 install git+https://github.com/timgrossmann/InstaPy.git@78ad421ec6d1c52b1fad9d5bfb0f73f8cd28c893
