### ISSUE TITLE
error on hyper.sh

### ISSUE THREAD

**Issue by hoangsoft90** [InstaPy/InstaPy#613]
``
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password, nogui=True)
  File "/root/InstaPy/instapy/instapy.py", line 100, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 147, in set_selenium_local_session
    self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options,service_args=service_args, service_log_path=service_log_path)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.62-hyper x86_64)
``

**Comment by converge** [comment]
hey, @hoangsoft90 do you have some news about it?
