### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: session not created from disconnected: unable to send message to renderer

### ISSUE THREAD

**Issue by PatrickConstan1** [InstaPy/InstaPy#6155]
Traceback (most recent call last):
  File "C:\Users\patri\Desktop\Python Projects\selenium\slnium.py", line 6, in <module>
    driver = webdriver.Chrome(path)
  File "C:\Users\patri\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\patri\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\patri\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\patri\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\patri\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to send message to renderer
  (Session info: chrome=90.0.4430.72)

Both my webdriver and chrome up to date.

**Comment by ghost** [comment]
Hey Patrick,
Have you managed to fix this error?
I'm getting the same thing.

PS: I don't know much about coding

**Comment by PatrickConstan1** [comment]
Nope

**Comment by ghost** [comment]
> Nope

Any workarounds so far?

**Comment by PatrickConstan1** [comment]
Nope

În sâm., 24 apr. 2021 la 11:27, Rboflimited ***@***.***> a
scris:

**Comment by FJG-Elelog** [comment]
I have found the same error.
I've being implementing a scraper with selenium that works with docker and in different threads. The thing is when I work with the local webdriver (C:/Users/.../chromedriver.exe) works just fine. But whenever I change to self.chrome = webdriver.Remote("http://localhost:4444/wd/hub", DesiredCapabilities.CHROME) it just dies.

Anyone?
