### ISSUE TITLE
traceback error? Can't figure out the issue

### ISSUE THREAD

**Issue by niloy1187** [InstaPy/InstaPy#6162]
## Current Behavior
Traceback (most recent call last):
  File "C:\Users\Niloy\Desktop\target_followers_of_similar_accounts_and_influencers.py", line 69, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 195, in download_and_install
    with zipfile.ZipFile(os.path.join(self.get_download_path(version), filename), mode="r") as driver_zipfile:
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by JacksonHoggard** [comment]
Can you please post your code?

**Comment by Lrnvrybthksa** [comment]
_

> "C:\Users\Niloy\Desktop\target_followers_of_similar_accounts_and_influencers.py"

_
for this, I think you need to use this file inside the instapy directory and not outside of it to access everything


----------------------------------------------------
> _"
> File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 325, in init
> self.browser, err_msg = set_selenium_local_session(
> File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\browser.py", line 122, in set_selenium_local_session
> driver_path = geckodriver_path or get_geckodriver()
> File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\browser.py", line 38, in get_geckodriver
> sym_path = gdd.download_and_install()[1]"_

You might have to install geckodriver 
I think InstaPy is trying to find and install/use geckodriver 


------------

> File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 195, in download_and_install
with zipfile.ZipFile(os.path.join(self.get_download_path(version), filename), mode="r") as driver_zipfile:
File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1257, in init
self._RealGetContents()
File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1324, in _RealGetContents
raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

I think it's looking for the gecko driver zipfile to unzip and use it. 

You can download geckodriver [here](https://github.com/mozilla/geckodriver/releases)
Also make sure you're using firefox
