### ISSUE TITLE
following_link error \n', 'list index out of range

### ISSUE THREAD

**Issue by T-Developer1** [InstaPy/InstaPy#617]
Hey,
i think i cant unfollow users. 
if my code hits this line
``` .unfollow_users(amount=randint(10,20))\```
the following error appears.

```
Liked: 5
Already Liked: 3
Inappropriate: 10
Commented: 0
Followed: 4
Number of people followed automatically remaining: 229
('following_link error \n', 'list index out of range')
Traceback (most recent call last):
  File "sessionquickstart2.py", line 48, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 452, in run_pendin
g
    default_scheduler.run_pending()
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 75, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 129, in _run_job
    ret = job.run()
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 377, in run
    ret = self.job_func()
  File "sessionquickstart2.py", line 40, in job
    import tracebock
ImportError: No module named tracebock
```

That's my code
```

    InstaPy(username=insta_username, password=insta_password)\
      .login()\
      .set_sleep_reduce(randint(180,230))\
      .set_upper_follower_count(limit=20000)\
      .set_do_follow(enabled=True, percentage=randint(40,60), times=2)\
      .set_user_interact(amount=randint(2,4), random=True, percentage=randint(35,62), media='Photo')\
      .set_dont_include(['friend1', 'friend2', 'friend3'])\
      .set_dont_like(['pizzaPizza'])\
      .like_by_tags(['ecchii', 'sport'], amount=randint(8,12))\
      .unfollow_users(amount=randint(10,20))\
      .like_by_tags(['summer'],amount=randint(7,13))\
      .end()
    sleep(randint(500,1000))
```

**Comment by ArdySan2012** [comment]
Same issue with latest build, even if simply using
session.unfollow_users(amount=10)

Gives similar error:
```
following_link error
 list index out of range
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    session.unfollow_users(amount=10)
  File "C:\Users\Admin\Desktop\InstaPy-master\instapy\instapy.py", line 962, in unfollow_users
    self.automatedFollowedPool)
  File "C:\Users\Admin\Desktop\InstaPy-master\instapy\unfollow_util.py", line 56, in unfollow
    dialog = browser.find_element_by_xpath("//div[text()='following']/following-sibling::div")
  File "D:\Programs\Python 3.6\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "D:\Programs\Python 3.6\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 832, in find_element
    'value': value})['value']
  File "D:\Programs\Python 3.6\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "D:\Programs\Python 3.6\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='following']/following-sibling::div"}
  (Session info: chrome=60.0.3112.113)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.14393 x86_64)
```

I'd be happy to help investigate, if someone points me in the right direction :) New to Pyton, but excited about the project and what @timgrossmann created.

**Comment by ArdySan2012** [comment]
Not sure how, but it worked in Chrome, but still receiving the same error in Firefox (could it be load time related? Gecko seems to be much slower generally).

**Comment by ArdySan2012** [comment]
Also, if in Firefox mode, I manually klick on "Following" button (to pull out list of followers) - while script is displaying "following_link error  list index out of range" - it continues then to unfollow without a problem.

Though LIFO not FiFO (he unfollows those at the top of the list first, so - those which were followed most recently).

**Comment by matteomaggioni89** [comment]
Having a similar issue even if I have pulled to the latest release:

```
Will follow  7 users per account
following_link error 
 list index out of range
Traceback (most recent call last):
  File "quickstart.py", line 53, in job
    session.follow_user_followers(accountsShuffled, amount=amountAccountsFollow, random=False, sleep_delay=300)
  File "/home/lm/InstaPy/instapy/instapy.py", line 902, in follow_user_followers
    userFollowed += follow_given_user_followers(self.browser, user, amount, self.dont_include, self.username, self.follow_restrict, random, sleep_delay)
  File "/home/lm/InstaPy/instapy/unfollow_util.py", line 399, in follow_given_user_followers
    personFollowed = follow_through_dialog(browser, user_name, amount, dont_include, login, follow_restrict, allfollowing, random, delay, callbacks=[])
  File "/home/lm/InstaPy/instapy/unfollow_util.py", line 194, in follow_through_dialog
    dialog = browser.find_element_by_xpath("//div[text()='Followers' or text()='Following']/following-sibling::div")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/following-sibling::div"}
  (Session info: chrome=61.0.3163.79)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.10.0-33-generic x86_64)
```

**Comment by 5p4ce** [comment]
Same here: Running the firefox script on a raspberry pi 3
```
Liked: 742
Already Liked: 0
Inappropriate: 175
Commented: 0
Followed: 185
Number of people followed automatically remaining: 186
('following_link error \n', 'list index out of range')

Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/fire.py", line 27, in <module>
    session.unfollow_users(amount=250, onlyInstapyFollowed = True )
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 962, in unfollow_users
    self.automatedFollowedPool)
  File "/home/pi/Projects/InstaPy/instapy/unfollow_util.py", line 56, in unfollow
    dialog = browser.find_element_by_xpath("//div[text()='Following']/following-sibling::div")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: {"method":"xpath","selector":"//div[text()='Following']/following-sibling::div"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmp4lZEuz/extensions/fxdriver@googlecode.com/components/driver-component.js:10770)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmp4lZEuz/extensions/fxdriver@googlecode.com/components/driver-component.js:625)
```

**Comment by andrei-zgirvaci** [comment]
Same problem here

Logged in successfully!
following_link error
 list index out of range
[Traceback (most recent call last):
  File "anonymzoo-bot.py", line 43, in <module>
    session.follow_user_followers(users, amount=10, random=False, interact=False, sleep_delay=60)
  File "/root/InstaPy/instapy/instapy.py", line 902, in follow_user_followers
    userFollowed += follow_given_user_followers(self.browser, user, amount, self.dont_include, self.username, self.follow_restrict, random, sleep_delay)
  File "/root/InstaPy/instapy/unfollow_util.py", line 435, in follow_given_user_followers
    personFollowed = follow_through_dialog(browser, user_name, amount, dont_include, login, follow_restrict, allfollowing, random, delay, callbacks=[])
  File "/root/InstaPy/instapy/unfollow_util.py", line 230, in follow_through_dialog
    dialog = browser.find_element_by_xpath("//div[text()='Followers' or text()='Following']/following-sibling::div")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/remote_connection.py", line 433, in _request
    resp = self._conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)

**Comment by T-Developer1** [comment]
still no fix for this?

**Comment by emasb238** [comment]
Any news on this issue? Help!

**Comment by converge** [comment]
It's fixed. If you still need some help, please reopen it.

**Comment by davidrocket** [comment]
@converge  Thank for your fix, but the problem is still there when running with firefox. I got the following ERROR message with the latest revision on github:

`selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[text()='Following']/following-sibling::div`

Please take another look

**Comment by andreescocard** [comment]
Latest version, same problem: ERROR - following_link error list index out of range
`Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/following-sibling::div"}
`

**Comment by d3rf** [comment]
So, I discover that when you use capital letters on the list to follow the error occur
`session.follow_user_followers(['Fredericofiuza','Heseatecnologia'], amount=10, randomize=False, sleep_delay=60)`
ERROR
Change to 
`session.follow_user_followers(['fredericofiuza','heseatecnologia'], amount=10, randomize=False, sleep_delay=60)`
Thats gonna work fine!

**Comment by Xifeat** [comment]
Hello, 

Anyone got a solution ?
Same as andreescocard 
and if I apply : https://github.com/timgrossmann/InstaPy/pull/915/commits/09ebab909a0575f5060d0c6cb0bb12bd3e140524

I got  
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[4]/div/div/div[2]/div/div[2]"}

**Comment by d3rf** [comment]
@Xifeat check if in your list of users there are capital letters... 
For example:
`session.follow_user_followers(['Fredericofiuza','Heseatecnologia'], amount=10, randomize=False, sleep_delay=60)`
Change to:
`session.follow_user_followers(['fredericofiuza','heseatecnologia'], amount=10, randomize=False, sleep_delay=60)`

**Comment by Xifeat** [comment]
@d3rf I already saw a post like this, I don't have capital letters on my code,

I just did this : 

session.login()                     
session.unfollow_users(amount=10, sleep_delay=60)
session.end()

**Comment by Xifeat** [comment]
Someone got a solution ? : 
Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[4]/div/div/div[2]/div/div[2]"}

I still have the problem

**Comment by guivinicius** [comment]
Looks like this is an Instagram page issue. Not related to the bot itself.
