### ISSUE TITLE
please help - Python 3.9 - MacOs 10.11 - InstaPy doesn't work

### ISSUE THREAD

**Issue by ligabuemiche** [InstaPy/InstaPy#6171]
Hi,
i really tried in thousand to make InstaPy works..... but nothing....

and i can not overcame this last error (i tried with Chrome, firefox)... please help me... where i'm wrong?

Thanks in advance

MacBookiMacBook:InstagramBot MacBook$ python3 instagram.py
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/MacBook/InstaPy"
Error, unable to determine correct filename for 64bit macos
Traceback (most recent call last):
  File "/Users/MacBook/Desktop/InstagramBot/instagram.py", line 22, in <module>
    session = InstaPy(username = insta_username,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit macos

**Comment by kaerus01** [comment]
I had this issue the other day. I needed to do a `brew install geckodriver` in addition to changing Line 320 to:

`filename = [name for name in filenames if os_name in name and name[-12:] == 'macos.tar.gz' ]`

in this file 
/Library/Python/3.7/site-packages/webdriverdownloader/webdriverdownloader.py

**Comment by rubinho101** [comment]
Running on MacOS 10.13 with Python 3.7 / 3.9 with the following modifications:  
- `brew install geckodriver` (took quite some time)  
- install firefox 68.8.0esr  
- /webdriverdownloader.py line 320: `filename = [name for name in filenames if os_name + bitness in name and name[-3:] != 'asc' ]` #5672  
- change instapy/like_util.py #6143 `span` to `div` `+ "/']/child::div[@class='u7YqG']/child::div"`
