### ISSUE TITLE
like_until update makes som error

### ISSUE THREAD

**Issue by S144S** [InstaPy/InstaPy#6176]
## Current Behavior
Hi, I had some problems with liking "Cannot detect post media type", I read that I should change one line like_until (span to div) but when I changed that I got these error:
`Traceback (most recent call last):
  File "c:\Users\lenovo\Desktop\SubDesk\Click Bloom\click_bloom_v1.0.0\main.py", line 72, in <module>        
    session.like_by_tags(['bitcoin'], amount=11)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\like_util.py", line 
726, in check_link
    quash = re.search(dont_likes_regex, image_text, re.IGNORECASE)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\sre_compile.py", line 764, in compile     
    p = sre_parse.parse(p, flags)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 443, in _parse_sub    
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 671, in _parse        
    raise source.error("multiple repeat",
re.error: multiple repeat at position 8`

what shoud I do?

**Comment by S144S** [comment]
problem solved!
one of my tag contain + and it makes problem
