### ISSUE TITLE
like_util: post_page is getting empty response data

### ISSUE THREAD

**Issue by nitesh585** [InstaPy/InstaPy#6194]
```
Traceback (most recent call last):
  File "quickstart.py", line 67, in <module>
    session.like_by_tags(['jokes','funny'], amount=100, interact=True)
  File "/home/nitesh/venv/lib/python3.8/site-packages/instapy/instapy.py", line 1957, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "/home/nitesh/venv/lib/python3.8/site-packages/instapy/like_util.py", line 636, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0
```

**Comment by Nervanas** [comment]
Similar to #6191 
Don't exactly know what's the best to debug it.
Maybe using a Proxy, then searching the server-side responses for something what's in the post (eg. caption). Then we'd know where the data would come from and could update the part in like_util.
