### ISSUE TITLE
the bot doesn't run for me 

### ISSUE THREAD

**Issue by channelblackri** [InstaPy/InstaPy#6196]
## Current Behavior
I try to run the shell but it doesn't work 

## Possible Solution (optional)
maybe a few things aren't installed? Iam very new to coding and have not a good grasp 

## InstaPy configuration

gwitter@MacBook-Air-von-G InstaPy-master % python3 quickstart.py
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
No any custom workspace provided.	~using existing..
InstaPy Version: 0.6.14
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/gwitter/InstaPy"
Error, unable to determine correct filename for 64bit macos
Traceback (most recent call last):
  File "/Users/gwitter/Desktop/InstaPy-master/quickstart.py", line 13, in <module>
    session = InstaPy(username="(_**DELETED MY NAME Cause of this post**_)", 
  File "/Users/gwitter/Desktop/InstaPy-master/instapy/instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Users/gwitter/Desktop/InstaPy-master/instapy/browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/Users/gwitter/Desktop/InstaPy-master/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit macos

**Comment by Nervanas** [comment]
Possible dublicate of #6145 and #6153

**Comment by channelblackri** [comment]
installed "brew install gekodriver" but still does't work 

gwitter@MacBook-Air-von-G InstaPy-master % python3 quickstart.py
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
No any custom workspace provided.	~using existing..
InstaPy Version: 0.6.14
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/gwitter/InstaPy"
Traceback (most recent call last):
  File "/Users/gwitter/Desktop/InstaPy-master/quickstart.py", line 13, in <module>
    session = InstaPy(username="**(unimportant)**", 
  File "/Users/gwitter/Desktop/InstaPy-master/instapy/instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Users/gwitter/Desktop/InstaPy-master/instapy/browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by channelblackri** [comment]
Iam using the new M1 Processor too, maybe there are compatibility issues

**Comment by JesuTinto** [comment]
Let me install it on my macOS. And see now I come up. Cheers.

**Comment by JesuTinto** [comment]
> Iam using the new M1 Processor too, maybe there are compatibility issues 

Installing Firefox will do the trick after installing the libraries with pip. Is always good to debug the code or paste as much possible about some type of error in dealing with this remember every operating is system is different Unix Linux Darwin and so on....  I'll be testing it but there is another project event better worth a try the one that brings GUI graphical user interface. 😀

**Comment by channelblackri** [comment]
what you mean? Like srsly is that even related with anything..

**Comment by ghost** [comment]
> what you mean? Like srsly is that even related with anything..

If it is not then read your debug message for a second and backtrack the error message. How is this not even related to anything are you a coder or wanna be coder?

**Comment by ghost** [comment]
With you're reply I will ignore you because not only you are. Not a coder but before you ask something read the manual first before getting involved or asking a question. Have a lovely blessed day. Cheers and happy.Sunday.

**Comment by channelblackri** [comment]
...you got serious issues bro.. My first line is literally I am new to coding dafuq is wrong with you.. first you got that totally wrong because the stuff you said didn't make sense for me and thats no shame since Iam a very beginner. Thanks for pointing out to read them manual tho, thats very helpful advice! Really helpful to shame a beginner that has a question.. Let me return you a siimilar helpful advice for you too and get a therapist. No need for YOUR help you pr***

**Comment by ghost** [comment]
At least be grateful when asking a question.

**Comment by channelblackri** [comment]
how the f do you know if Iam grateful or not? Because I literally am for every answer so on github. You just perceived my question a certain way and got offended for literally no reason and jump to assumptions about me, while you clearly didn't even read my introduction. I mean cmon man..

**Comment by Tr1pke** [comment]
> how the f do you know if Iam grateful or not? Because I literally am for every answer so on github. You just perceived my question a certain way and got offended for literally no reason and jump to assumptions about me, while you clearly didn't even read my introduction. I mean cmon man..

seems you are making easy friends in life ... success finding an solution ...

**Comment by elulcao** [comment]
Check #6153
