### ISSUE TITLE
Error: Element  is not clickable at point (920, 14). Other element would receive the click

### ISSUE THREAD

**Issue by hoangsoft90** [InstaPy/InstaPy#621]
i got this error when set_do_follow
``
Traceback (most recent call last):
  File "h-bot1.py", line 133, in job
    '#'+tg], amount=int(tgData['amount']), media=tgData['media'])
  File "D:\HoangData\xampp_htdocs\social\instagram\InstaPy\instapy\instapy.py", line 545, in like_by_tags
    followed += follow_user(self.browser, self.follow_restrict, self.username, user_name)
  File "D:\HoangData\xampp_htdocs\social\instagram\InstaPy\instapy\unfollow_util.py", line 140, in follow_user
    follow_button.click()
  File "D:\HoangData\xampp_htdocs\social\instagram\InstaPy\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "D:\HoangData\xampp_htdocs\social\instagram\InstaPy\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "D:\HoangData\xampp_htdocs\social\instagram\InstaPy\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "D:\HoangData\xampp_htdocs\social\instagram\InstaPy\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Element <button class="_qv64e _gexxb _4tgw8 _njrw0">...</button> is not clickable at point (920, 14). Other element would receive the click: <div class="_qlijk">...</div>
  (Session info: chrome=60.0.3112.113)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 10.0.15063 x86_64)
``

**Comment by timgrossmann** [comment]
@hoangsoft90 Could you do a git pull and try again, please?

**Comment by converge** [comment]
there no interaction for a long time, pls, reopen it if you need.
