### ISSUE TITLE
Problems setting up instapy in raspberry pi 3b

### ISSUE THREAD

**Issue by codewithnick** [InstaPy/InstaPy#6213]
## Expected Behavior
Instapy should be running
## Current Behavior
pi@raspberrypi:~/Desktop/instagram/final-bot $ xvfb-run python3 bug.py
Traceback (most recent call last):
  File "bug.py", line 6, in <module>
    from instapy import InstaPy
  File "/usr/local/lib/python3.7/dist-packages/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/usr/local/lib/python3.7/dist-packages/instapy/instapy.py", line 33, in <module>
    from .clarifai_util import check_image
  File "/usr/local/lib/python3.7/dist-packages/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "/usr/local/lib/python3.7/dist-packages/clarifai/rest/__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "/usr/local/lib/python3.7/dist-packages/clarifai/rest/client.py", line 22, in <module>
    from future.moves.urllib.parse import urlparse
  File "/usr/local/lib/python3.7/dist-packages/future/moves/__init__.py", line 8, in <module>
    import_top_level_modules()
  File "/usr/local/lib/python3.7/dist-packages/future/standard_library/__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "/usr/local/lib/python3.7/dist-packages/future/standard_library/__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "/home/pi/Desktop/instagram/final-bot/test.py", line 10, in <module>
    driver=webdriver.Firefox(capabilities=DesiredCapabilities.FIREFOX)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

## Possible Solution (optional)
I have mentioned in detail here https://stackoverflow.com/questions/67842704/problems-setting-up-instapy-in-raspberry-pi

**Comment by codewithnick** [comment]
I have installed everything as stated in https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md 
but still getting this error ,maybe it is a webdriver exception, how do I get through this
