### ISSUE TITLE
Unable to locate element on Raspberry Pi 

### ISSUE THREAD

**Issue by NikitaAV** [InstaPy/InstaPy#622]
Hi, folks! :)

I'm trying to get the bot running on my Raspberry Pi 3B. I'm digging since days and think i have the correct apps and settings yet but still get one or more error messages. 

> Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    .set_switch_language(True)\
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 161, in login
    if not login_user(self.browser, self.username, self.password, self.switch_language):
  File "/home/pi/Projects/InstaPy/instapy/login_util.py", line 19, in login_user
    login_elem = browser.find_element_by_xpath("//article/div/div/p/a[text()='Log in']")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 354, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 832, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //article/div/div/p/a[text()='Log in']

**Comment by gagankumr** [comment]
Make sure  you have installed selenium. Also when executing make sure you force it to use 3.x instead of 2.x

**Comment by NikitaAV** [comment]
Got this issue fixed by reinstalling/updating selenium... 

`pip install -U selenium`
