### ISSUE TITLE
Traceback Error for interact_user_followers 

### ISSUE THREAD

**Issue by Glyphism** [InstaPy/InstaPy#6223]
## Expected Behavior
InstaPy works as normal

## Current Behavior
My InstaPy was working fine (on a Mac, with Firefox), but then stopped functioning overnight for some reason. It is a simple script that extracts the followers of a specified user and then likes their posts. It can still login and extract the follower list, but as soon as it tries to like the first picture, it terminates with the Traceback Error error below. Is anyone able to identify the cause of this?

## InstaPy configuration
```
Traceback (most recent call last):
  File "/Users/username/Documents/InstaPy/instapy-quickstart-master/run/../quickstart.py", line 31, in <module>
    session.interact_user_followers(['account1' , 'account1' , 'account2' , 'account3'], amount=63, randomize=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 3207, in interact_user_followers
    self.interact_by_users(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 2543, in interact_by_users
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

```

**Comment by filiperivelli** [comment]
You create the same issue here: https://github.com/timgrossmann/InstaPy/issues/6222

**Comment by schealex** [comment]
Already fixed. Please update to current master.
