### ISSUE TITLE
Import instapy errors & pyvirtualdisplay error

### ISSUE THREAD

**Issue by gagankumr** [InstaPy/InstaPy#624]
```
Traceback (most recent call last):
  File "./quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/home/gagan/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/home/gagan/InstaPy/instapy/instapy.py", line 8, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay
```

Im on ubuntu VM

**Comment by gagankumr** [comment]
Nevermind i fixed it. Ill make a video on how to install this on VM for any beginner out there who doesn't know python. Thank god i have programming experience and little python experience  that helped me

If you have any questions and i want to contact me to help you on here, my social media is below:
[Follow -> Twitter](http://twitter.com/kumar_official)
[Follow -> Instagram](http://instagram.com/imgagankumar)
Just DM me or post a comment on latest post
