### ISSUE TITLE
hide selenium error, graphql error

### ISSUE THREAD

**Issue by dragu95** [InstaPy/InstaPy#6246]
While running any test template the following behavior appears:

starting instapy with quickstart
================================
InstaPy Version: 0.6.14
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/user/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-06-24 21:08:26] [xxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-06-24 21:08:26] [xxx]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-06-24 21:08:27] [xxx]  - Internet Connection Status: ok
INFO [2021-06-24 21:08:27] [xxx]  - Current IP is "xxx" and it's from "xxx"
INFO [2021-06-24 21:08:27] [xxx]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-06-24 21:08:27] [xxx]  - window.navigator.webdriver response: True
**WARNING [2021-06-24 21:08:27] [xxx]  - Hide Selenium Extension: error**
INFO [2021-06-24 21:08:33] [xxx]  - Cookie file for user 'xxx' loaded...
.........................................................................
INFO [2021-06-24 21:09:00] [xxx]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2021-06-24 21:09:00] [xxx]  Saving account progress...
**WARNING [2021-06-24 21:09:04] [xxx]  Unable to save account progress, skipping data update
        b"'graphql'"**

INFO [2021-06-24 21:09:05] [xxx]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 44.75 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-06-24 21:09:05] [xxx]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\instapy-quickstart-master (2)\instapy-quickstart-master\quickstart.py", line 26, in <module>
    with smart_run(session):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\instapy\util.py", line 1952, in smart_run
    session.login()
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\instapy\instapy.py", line 472, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\instapy\print_log_writer.py", line 21, in log_follower_num
    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\instapy\util.py", line 490, in getUserData
    data = data[subobject]
KeyError: 'graphql'

Any Solution for the graphql error? 
I already updated to the newest not released version.

Thank you very much

**Comment by soltanwar1212** [comment]
i have same problem
graphql??!!

**Comment by dragu95** [comment]
PUSH, is anyone still working on InstaPy ? There are 1000 bugs right now.

**Comment by Molodoi88** [comment]
help guys. do not ruin my desire to study programming, I must escape from Russia

**Comment by lolicarlos** [comment]
Same here.. N update?
