### ISSUE TITLE
`NameError: global name 'driver' is not defined`

### ISSUE THREAD

**Issue by chrisscholly** [InstaPy/InstaPy#625]
I sometimes get this error (seems like a random issue):
```
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    session.like_by_tags(['#retrogaminglife'], amount=300)
  File "/Users/chrisscholly/Projects/shapes/growth/instapy/instapy/instapy.py", line 531, in like_by_tags
    followed += follow_user(self.browser, self.follow_restrict, self.username, user_name)
  File "/Users/chrisscholly/Projects/shapes/growth/instapy/instapy/unfollow_util.py", line 138, in follow_user
    driver.execute_script("arguments[0].style.visibility = 'visible'; arguments[0].style.height = '10px'; arguments[0].style.width = '10px'; arguments[0].style.opacity = 1", follow_button)
NameError: global name 'driver' is not defined
```

`quickstart.py`:
```python
from instapy import InstaPy

insta_username = 'xxx'
insta_password = 'xxx'

session = InstaPy(username=insta_username, password=insta_password)
session.login()
session.set_lower_follower_count(limit=1000)
session.set_do_comment(True, percentage=80)
session.set_comments(['Cool :)', 'Nice!', 'Dope!'])
session.set_do_follow(enabled=True, percentage=50, times=2)
session.like_by_tags(['#xxx'], amount=300)
session.end()
```
Any idea here pls?

**Comment by dilee716** [comment]
getting this error too since latest pull

**Comment by iSimonWeb** [comment]
This is due to #620 merged to fix the visibility issue but it miscalled the Selenium webdriver as "driver" and not "browser" as this repo used to.

**Comment by timgrossmann** [comment]
@iSimonWeb should be fixed now

**Comment by chrisscholly** [comment]
Thank you guys 🙏🏻
