### ISSUE TITLE
Unable to save account progress, skipping data update   b"'graphql'"

### ISSUE THREAD

**Issue by soltanwar1212** [InstaPy/InstaPy#6254]
Traceback (most recent call last):

  File "D:\InstaPy-master\InstaPy-master\user_run.py", line 17, in <module>
    with smart_run(session):

  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)

  File "D:\InstaPy-master\InstaPy-master\instapy\util.py", line 1952, in smart_run
    session.login()

  File "D:\InstaPy-master\InstaPy-master\instapy\instapy.py", line 472, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)

  File "D:\InstaPy-master\InstaPy-master\instapy\print_log_writer.py", line 21, in log_follower_num
    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)

  File "D:\InstaPy-master\InstaPy-master\instapy\util.py", line 490, in getUserData
    data = data[subobject]

KeyError: 'graphql'

**Comment by dragu95** [comment]
same
