### ISSUE TITLE
Browser window closes without a like

### ISSUE THREAD

**Issue by viciousrene** [InstaPy/InstaPy#6256]
I am quite new to Instapy programming and need some help now. I have two questions for you. The first question is why the Firefox browser opens for me. I thought the default browser was Chrome. 

The second question is why my code is breaking prematurely.  The browser opens, the login works, it also finds an image with the #natgeo. But when he wants to like the picture, the window closes and the code is done. What have I done wrong?

____________________________

starting instapy with quickstart
================================
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/***/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-07-02 09:56:03] [***]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-07-02 09:56:03] [***]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-07-02 09:56:04] [***]  - Internet Connection Status: ok
INFO [2021-07-02 09:56:04] [***]  - Current IP is "***" and it's from "Germany/DE"
INFO [2021-07-02 09:56:04] [***]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-07-02 09:56:04] [***]  - window.navigator.webdriver response: True
WARNING [2021-07-02 09:56:04] [***]  - Hide Selenium Extension: error
INFO [2021-07-02 09:56:07] [***]  - Cookie file for user '***' loaded...
..................................................................
INFO [2021-07-02 09:56:25] [***]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2021-07-02 09:56:25] [***]  Saving account progress...
INFO [2021-07-02 09:56:41] [***]  Tag [1/1]
INFO [2021-07-02 09:56:41] [***]  --> b'natgeo'
INFO [2021-07-02 09:56:52] [***]  desired amount: 19  |  top posts [disabled]: 9  |  possible posts: 23324658
INFO [2021-07-02 09:56:58] [***]  Like# [1/19]
INFO [2021-07-02 09:56:58] [***]  https://www.instagram.com/p/CQ0TQ9rFaCw/

INFO [2021-07-02 09:57:02] [***]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 1.09 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-07-02 09:57:02] [***]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "C:\Users\***\Downloads\instapy-quickstart-master\quickstart.py", line 32, in <module>
    session.like_by_tags(["natgeo"], amount=10)
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instapy\instapy.py", line 1957, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instapy\like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

____________________________

# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = '***'
insta_password = '***'

comments = ['Nice shot! @{}',
        'I love your profile! @{}',
        'Your feed is an inspiration :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Getting inspired by you @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:']

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
  """ Activity flow """		
  # general settings		
  session.set_dont_include(["friend1", "friend2", "friend3"])		
  
  # activity		
  session.like_by_tags(["natgeo"], amount=10)

  # Joining Engagement Pods
  session.set_do_comment(enabled=True, percentage=35)
  session.set_comments(comments)
  session.join_pods(topic='sports', engagement_mode='no_comments')

**Comment by bicravix** [comment]
Hello,

Try this #6202
