### ISSUE TITLE
Program exits without giving any like

### ISSUE THREAD

**Issue by javiersempere** [InstaPy/InstaPy#6257]
## Current Behavior
Program crashing without giving any like

## InstaPy configuration
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)
with smart_run(session):
    """ Activity flow """
    session.like_by_feed(amount=100, randomize=True, unfollow=False, interact=False)

## Python output
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Javier/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-07-04 18:29:35] [sempere.javier]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-07-04 18:29:35] [sempere.javier]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-07-04 18:29:35] [sempere.javier]  - Internet Connection Status: ok
INFO [2021-07-04 18:29:35] [sempere.javier]  - Current IP is "79.159.214.63" and it's from "Spain/ES"
INFO [2021-07-04 18:29:35] [sempere.javier]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-07-04 18:29:35] [sempere.javier]  - window.navigator.webdriver response: True
WARNING [2021-07-04 18:29:35] [sempere.javier]  - Hide Selenium Extension: error
INFO [2021-07-04 18:29:38] [sempere.javier]  - Cookie file for user 'sempere.javier' loaded...
....................................................................
INFO [2021-07-04 18:29:57] [sempere.javier]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2021-07-04 18:29:57] [sempere.javier]  Saving account progress...
INFO [2021-07-04 18:30:16] [sempere.javier]  Total of links feched for analysis: 8
INFO [2021-07-04 18:30:16] [sempere.javier]  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
0 https://www.instagram.com/p/CQ50_j1D4Jn/
1 https://www.instagram.com/p/CQ5ZwXjDRHX/
2 https://www.instagram.com/p/CQ5jwZBHAWls2BGDFG-NkfqCWWrJzox6cQf6M40/
3 https://www.instagram.com/p/CQ4-Ak0A9Wj/
4 https://www.instagram.com/p/CQ4AiYtlcXy/
5 https://www.instagram.com/p/CQ53erWDhvF/
6 https://www.instagram.com/p/CQ6Pc1qBxHw/
7 https://www.instagram.com/p/CQ5r62doKwi/
INFO [2021-07-04 18:30:16] [sempere.javier]  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2021-07-04 18:30:16] [sempere.javier]  New link found...
INFO [2021-07-04 18:30:16] [sempere.javier]  [0 posts liked /100 amount]
INFO [2021-07-04 18:30:16] [sempere.javier]  https://www.instagram.com/p/CQ50_j1D4Jn/

INFO [2021-07-04 18:30:20] [sempere.javier]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 348 users & had 501 FOLLOWERS
[Session lasted 54.96 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-07-04 18:30:20] [sempere.javier]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

The browser loads, and then the program exits without giving any likes.

## Error message
Traceback (most recent call last):
  File "start.py", line 26, in <module>
    session.like_by_feed(amount=100, randomize=True, unfollow=False, interact=False)
  File "D:\_Documentos\Anaconda\envs\Instagram\lib\site-packages\instapy\instapy.py", line 3922, in like_by_feed
    for _ in self.like_by_feed_generator(amount, randomize, unfollow, interact):
  File "D:\_Documentos\Anaconda\envs\Instagram\lib\site-packages\instapy\instapy.py", line 4029, in like_by_feed_generator
    ) = check_link(
  File "D:\_Documentos\Anaconda\envs\Instagram\lib\site-packages\instapy\like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

## Help needed
Thanks a lot for any help!

**Comment by netsvetaev** [comment]
I have the same problem. What did you wrote in «media»?

**Comment by javiersempere** [comment]
Not sure what you mean. The whole code I used is at the beginning of the thread
