### ISSUE TITLE
Hide Selenium Extension error. Still not solved #5346 #5304

### ISSUE THREAD

**Issue by javiersempere** [InstaPy/InstaPy#6258]
## Current Behavior
After reviewing all the proposed solutions in threads #5346 and #5304 the problem is still appearing.
I would be very grateful if some developer could have a deeper look at this and give us any clue about what else can we try.
Thanks!

**Comment by elulcao** [comment]
This is a useful link "https://bugzilla.mozilla.org/show_bug.cgi?id=1632821"
where is explained why "navigator.webdriver" behave different now.
one WA is to use an old version of FF that doesn't have that bug fix.

**Comment by erasmo-co** [comment]
@kharazian Did you solve the problem? I have the same problem.

**Comment by kharazian** [comment]
> FF now cannot be changed to hide the Automator web framework, there is a variable that is read-only. So, InstaPy extension for hiding 😶‍🌫️ to IG we are using an Automated framework is falling with FF those versions. You need to download an old FF version (ie 77) and the corresponding geckodriver to avoid been detected by IG; oficial InstaPy doc has the correct steps for custom Ff and 🦎

Hi @erasmo-co 
As @elulcao said this problem appear with new version of FireFox, So you can use old version to solve this warning or ignore it.

**Comment by kharazian** [comment]
> > > FF now cannot be changed to hide the Automator web framework, there is a variable that is read-only. So, InstaPy extension for hiding face_in_clouds to IG we are using an Automated framework is falling with FF those versions. You need to download an old FF version (ie 77) and the corresponding geckodriver to avoid been detected by IG; oficial InstaPy doc has the correct steps for custom Ff and lizard
> > 
> > 
> > Hi @erasmo-co As @elulcao said this problem appear with new version of FireFox, So you can use old version to solve this warning or ignore it.
> 
> Great !!! Also this issue fixed thanks a lot !!!

You are welcome

**Comment by rogersillyface** [comment]
Out of even more curiosity.. Would this work:

[](https://e4example.blogspot.com/2017/07/run-different-version-of-firefox-using.html)

?

**Comment by elulcao** [comment]
> Out of even more curiosity.. Would this work:
> 
> 
> 
> [https://e4example.blogspot.com/2017/07/run-different-version-of-firefox-using.html](url)
> 
> 
> 
> @elulcao
> 
> 
> 
> ?
> 
> 
> 
> 

I suspect no, FF now has _ navigator.webdriver_ variable as read only. And this is intentionally to indicate the browser is handled by a bot.

**Comment by rogersillyface** [comment]
> > Out of even more curiosity.. Would this work:
> > [https://e4example.blogspot.com/2017/07/run-different-version-of-firefox-using.html](url)
> > @elulcao
> > ?
> 
> I suspect no, FF now has _ navigator.webdriver_ variable as read only. And this is intentionally to indicate the browser is handled by a bot.

Really? Even in the older version of FF?

Is there any wway round this? My account is constantly disabled very quickly and very often..!

**Comment by elulcao** [comment]
> > > Out of even more curiosity.. Would this work:
> 
> > > [https://e4example.blogspot.com/2017/07/run-different-version-of-firefox-using.html](url)
> 
> > > @elulcao
> 
> > > ?
> 
> > 
> 
> > I suspect no, FF now has _ navigator.webdriver_ variable as read only. And this is intentionally to indicate the browser is handled by a bot.
> 
> 
> 
> Really? Even in the older version of FF?
> 
> 
> 
> Is there any wway round this? I can't get instapy to work for very long and my account is disabled very frequently.

Ohhh, I forgot to mention that Older versions are ok, the ESR is a good choice. 
My acct is compromised also because of the same issue with newer FF version.

**Comment by rogersillyface** [comment]
> > > > Out of even more curiosity.. Would this work:
> > 
> > 
> > > > [https://e4example.blogspot.com/2017/07/run-different-version-of-firefox-using.html](url)
> > 
> > 
> > > > @elulcao
> > 
> > 
> > > > ?
> > 
> > 
> > > 
> > 
> > 
> > > I suspect no, FF now has _ navigator.webdriver_ variable as read only. And this is intentionally to indicate the browser is handled by a bot.
> > 
> > 
> > Really? Even in the older version of FF?
> > Is there any wway round this? I can't get instapy to work for very long and my account is disabled very frequently.
> 
> Ohhh, I forgot to mention that Older versions are ok, the ESR is a good choice. My acct is compromised also because of the same issue with newer FF version.

My idea is to have a version of FF that Instapy would solely use - the older version. The Python code is in the link to apparently make it happen...but I have no idea where it would go..!

**Comment by rogersillyface** [comment]
> > > > > Out of even more curiosity.. Would this work:
> > > 
> > > 
> > > > > [https://e4example.blogspot.com/2017/07/run-different-version-of-firefox-using.html](url)
> > > 
> > > 
> > > > > @elulcao
> > > 
> > > 
> > > > > ?
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > I suspect no, FF now has _ navigator.webdriver_ variable as read only. And this is intentionally to indicate the browser is handled by a bot.
> > > 
> > > 
> > > Really? Even in the older version of FF?
> > > Is there any wway round this? I can't get instapy to work for very long and my account is disabled very frequently.
> > 
> > 
> > Ohhh, I forgot to mention that Older versions are ok, the ESR is a good choice. My acct is compromised also because of the same issue with newer FF version.
> 
> My idea is to have a version of FF that Instapy would solely use - the older version. The Python code is in the link to apparently make it happen...but I have no idea where it would go..!

SO! I have finally figured out how to start up a specific version on MacOS..

I was writing the path to the application itself:

browser_executable_path=r"/Applications/Firefox.app

But we need to go deeper and point to the specific executable file within the Firefox application:

browser_executable_path=r"/Applications/Firefox-i/Firefox.app/Contents/MacOS/firefox")

No idea if you were aware of this or not, I am very pleased with myself for sorting this out and feel as though I deserve a cookie.

Cheers!

**Comment by celestinsoum** [comment]
I have install FF 77 but now I have new error message : 

`error, unable to determine correct filename for 64bit linux
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    session = InstaPy(username=insta_username,
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 327, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit linux`

**Comment by elulcao** [comment]
> I have install FF 77 but now I have new error message :
> 
> `error, unable to determine correct filename for 64bit linux Traceback (most recent call last): File "main.py", line 24, in <module> session = InstaPy(username=insta_username, File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 327, in __init__ self.browser, err_msg = set_selenium_local_session( File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 122, in set_selenium_local_session driver_path = geckodriver_path or get_geckodriver() File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 38, in get_geckodriver sym_path = gdd.download_and_install()[1] File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install filename_with_path = self.download(version, File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download download_url = self.get_download_url(version, os_name=os_name, bitness=bitness) File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url raise RuntimeError(info_message) RuntimeError: Error, unable to determine correct filename for 64bit linux`

This is not an Error with InstaPy but webdriverdownloader
We don't have any scope modifying that repo, so, I would suggest to download the geckdriver instead. 

I shared an example here:
https://stackoverflow.com/a/64029210/13222154

**Comment by celestinsoum** [comment]
> > I have install FF 77 but now I have new error message :
> > `error, unable to determine correct filename for 64bit linux Traceback (most recent call last): File "main.py", line 24, in <module> session = InstaPy(username=insta_username, File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 327, in __init__ self.browser, err_msg = set_selenium_local_session( File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 122, in set_selenium_local_session driver_path = geckodriver_path or get_geckodriver() File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 38, in get_geckodriver sym_path = gdd.download_and_install()[1] File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install filename_with_path = self.download(version, File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download download_url = self.get_download_url(version, os_name=os_name, bitness=bitness) File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url raise RuntimeError(info_message) RuntimeError: Error, unable to determine correct filename for 64bit linux`
> 
> This is not an Error with InstaPy but webdriverdownloader We don't have any scope modifying that repo, so, I would suggest to download the geckdriver instead.
> 
> I shared an example here: https://stackoverflow.com/a/64029210/13222154

I have already install geckodriver, version : geckodriver 0.29.0, if I update to last version, I also need to update FF to last version too, and I have I have the initial problem of "Hide Selenium Extension error."

**Comment by elulcao** [comment]
> > > I have install FF 77 but now I have new error message :
> 
> > > `error, unable to determine correct filename for 64bit linux Traceback (most recent call last): File "main.py", line 24, in <module> session = InstaPy(username=insta_username, File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 327, in __init__ self.browser, err_msg = set_selenium_local_session( File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 122, in set_selenium_local_session driver_path = geckodriver_path or get_geckodriver() File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 38, in get_geckodriver sym_path = gdd.download_and_install()[1] File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install filename_with_path = self.download(version, File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download download_url = self.get_download_url(version, os_name=os_name, bitness=bitness) File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url raise RuntimeError(info_message) RuntimeError: Error, unable to determine correct filename for 64bit linux`
> 
> > 
> 
> > This is not an Error with InstaPy but webdriverdownloader We don't have any scope modifying that repo, so, I would suggest to download the geckdriver instead.
> 
> > 
> 
> > I shared an example here: https://stackoverflow.com/a/64029210/13222154
> 
> 
> 
> I have already install geckodriver, version : geckodriver 0.29.0, if I update to last version, I also need to update FF to last version too, and I have I have the initial problem of "Hide Selenium Extension error."

Use FF ESR not the latest.

**Comment by celestinsoum** [comment]
I have install this version (last) : [https://www.ubuntuupdates.org/package/mozilla_esr/focal/main/base/firefox-esr-geckodriver](url) and I have same error message ...

**Comment by elulcao** [comment]
> I have install this version (last) : https://www.ubuntuupdates.org/package/mozilla_esr/focal/main/base/firefox-esr-geckodriver and I have same error message ...

Ohhh no, Search an ESR version like 77. Other newer versions should have included the fix mentioned at https://bugzilla.mozilla.org/show_bug.cgi?id=1632821

**Comment by celestinsoum** [comment]
> > I have install this version (last) : https://www.ubuntuupdates.org/package/mozilla_esr/focal/main/base/firefox-esr-geckodriver and I have same error message ...
> 
> Ohhh no, Search an ESR version like 77. Other newer versions should have included the fix mentioned at https://bugzilla.mozilla.org/show_bug.cgi?id=1632821

Now I have a other error, I opened a new issues cause I think it's not same problem : #6456
