### ISSUE TITLE
InstaPy Not Working

### ISSUE THREAD

**Issue by arunpmurugavel24** [InstaPy/InstaPy#6261]
I ran this simple script after installing instapy using pip:

`from instapy import InstaPy
  
session = InstaPy(username="your username",password="your password")
session.login()`

I get an error message like this:

`InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/Arun prem/InstaPy"
Traceback (most recent call last):
  File "E:/Programs/Big Projects/Instagram Bot/quickstarter.py", line 3, in <module>
    session = InstaPy(username="murugavelarun",password="Arunprem@625")
  File "E:\Applications\Python\lib\site-packages\instapy\instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "E:\Applications\Python\lib\site-packages\instapy\browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "E:\Applications\Python\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "E:\Applications\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "E:\Applications\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "E:\Applications\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "E:\Applications\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line`

I don't know what to do remove this problem. Any help would be great.

Thank You

**Comment by geeks121** [comment]
how you solve this?
