### ISSUE TITLE
Like by tags

### ISSUE THREAD

**Issue by RaspberryPiZero** [InstaPy/InstaPy#6271]
I saw that there was a pull request about this but I'm actually not sure how to fix the like by tags error. I get a message like this in the terminal:

`Traceback (most recent call last):
  File "C:\Users\-\Desktop\Instagram Bot\instagram.py", line 21, in <module>
    session.like_by_tags(['pcmasterrace', 'nvidia'], amount=10, media='Photo')
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0`

What files should I change to solve this and with what code? The software works with the follow/unfollow, I just have this issue when I try liking the photos with the tags I select. Thank you very much.

**Comment by giginghn** [comment]
Sam here!

**Comment by giginghn** [comment]
Same here!

**Comment by rimager** [comment]
Traceback (most recent call last):
  File "/Users/rimagerhard/Downloads/instapy-quickstart-master/quickstart.py", line 32, in <module>
    session.like_by_tags(["americangirldoll"], amount=50)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 1957, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

Same here

**Comment by xerZV** [comment]
same here

**Comment by rimager** [comment]
Install the latest from Github, not pip
python3 -m pip install git+https://github.com/timgrossmann/InstaPy

**Comment by xerZV** [comment]
> Install the latest from Github, not pip
> python3 -m pip install git+https://github.com/timgrossmann/InstaPy

Just tried that - its working. It gives the error for some of the posts.

Thanks @rimager!

**Comment by Sirman13** [comment]
Same here.. 
![image](https://user-images.githubusercontent.com/42942739/126373842-cc1686c3-605e-4583-a7d2-bb8353291083.png)

**Comment by rogersillyface** [comment]
> Install the latest from Github, not pip
> python3 -m pip install git+https://github.com/timgrossmann/InstaPy

Would it be a good idea to put this into the guide on the Instapy homepage?
