### ISSUE TITLE
Error, unable to determine correct filename for 64bit macos

### ISSUE THREAD

**Issue by josepfm** [InstaPy/InstaPy#6284]
Error, unable to determine correct filename for 64bit macos
Traceback (most recent call last):
  File "/Users/josepfm/Downloads/InstaPy-master-2/quickstart.py", line 13, in <module>
    session = InstaPy(username="XXXX", password="XXXX")
  File "/Users/josepfm/Downloads/InstaPy-master-2/instapy/instapy.py", line 327, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Users/josepfm/Downloads/InstaPy-master-2/instapy/browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/Users/josepfm/Downloads/InstaPy-master-2/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit macos

Any help?

**Comment by umidsaidov** [comment]
Set a geckodriver path in your quickstart.py file:

session = InstaPy(username=insta_username,
                  password=insta_password,  geckodriver_path = '/Users/main/Downloads/geckodriver')

**Comment by josepfm** [comment]
Another error:

josepfm@Mark-Pro-13 InstaPy-master-2 % python3 quickstart.py
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
No any custom workspace provided.	~using existing..
InstaPy Version: 0.6.14
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/josepfm/InstaPy"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/josepfm/Downloads/geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/josepfm/Downloads/InstaPy-master-2/quickstart.py", line 13, in <module>
    session = InstaPy(username="beironapp",
  File "/Users/josepfm/Downloads/InstaPy-master-2/instapy/instapy.py", line 327, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Users/josepfm/Downloads/InstaPy-master-2/instapy/browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by umidsaidov** [comment]
Install geckodriver manually and place geckodriver.exe file in Downloads.

**Comment by josepfm** [comment]
Thanks!! 👏

**Comment by elulcao** [comment]
Check #6153
