### ISSUE TITLE
Problem installing instapy on windows

### ISSUE THREAD

**Issue by brunno001v** [InstaPy/InstaPy#6286]
I can't install InstaPy in using 
pip install instapy

This code generates this error 
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\commands\install.py", line 316, in run
    reqs, check_supported_wheels=not options.target_dir
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 168, in _add_to_criteria
    candidates=build_iter_view(matches),
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 164, in build_iter_view
    matches = list(matches)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 417, in <genexpr>
    and all(req.is_satisfied_by(c) for req in requirements[identifier])
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 417, in <genexpr>
    and all(req.is_satisfied_by(c) for req in requirements[identifier])
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\resolution\resolvelib\requirements.py", line 39, in is_satisfied_by
    return candidate == self.candidate
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 172, in __eq__
    return links_equivalent(self._link, other._link)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\models\link.py", line 288, in links_equivalent
    return _CleanResult.from_link(link1) == _CleanResult.from_link(link2)
AttributeError: type object '_CleanResult' has no attribute 'from_link'

**Comment by ErezAmihud** [comment]
What version of python?
https://github.com/pypa/pip/issues/10280#issuecomment-894591699 this say it is a problem in python 3.6.0
try running `pip install -U pip` or using another version of python

**Comment by elulcao** [comment]
Try with a virtualenv, and verify you can install other packages with pip.
InstaPy is not the problem since the failure comes from pip cli.
