### ISSUE TITLE
Instapy --- Unavailable Page error 

### ISSUE THREAD

**Issue by BanannaCode** [InstaPy/InstaPy#6288]
Hi everyone I am experiencing the same error as already mentioned in this thread: 
https://github.com/timgrossmann/InstaPy/issues/5013

The weird thing is that if I use the same code (just logically different login infos) it works for another account of mine just well!

## Expected Behavior
Same code for both accounts, so should work the same.

## Current Behavior
Showing error code  "Unavailable Page", which is why images are not liked for one account.

## InstaPy configuration
from instapy import InstaPy

session = InstaPy(username="user2", password="password").login()
session.login()
session.set_quota_supervisor(enabled=True, 
	sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"],
	sleepyhead=True,
	stochastic_flow=True,
	notify_me=True,
	peak_likes_hourly=20,
	peak_likes_daily=90,
	peak_comments_hourly=20,
	peak_comments_daily=90,
	peak_follows_hourly=5,
	peak_follows_daily=10,
	peak_unfollows_hourly=4,
	peak_unfollows_daily=20,	
        peak_server_calls_hourly=None,
	peak_server_calls_daily=4700)
session.set_do_comment(enabled=True, percentage=100)
session.set_comments([":heart_eyes:"])
session.like_by_tags(["hashtag1", "hashtag2"], amount = 1)
session.set_dont_like(["naked", "nsfw"])
session.end()

**Comment by nckmh** [comment]
I am having the same issue. I created a new Instagram account and tried to implement the same code that I was using for another account. It worked for the previous account but does not work for the new one.

Same error: WARNING [2021-08-04 11:45:04] [user]  Unavailable Page: b'https://www.instagram.com/p/post/'
INFO [2021-08-04 11:45:04] [user]  --> Image not liked: b'Unavailable Page'

**Comment by nckmh** [comment]
Just tested with the old credentials and it still works fine.

**Comment by BanannaCode** [comment]
Same for me it works with one account but using the same prompt code for the other account always gives me errors when it reaches the “liking” section.
It logs in fine but once it comes to liking the pictures it comes up with unavailable post (even though the post pages are loading in the browser etc).
Good to hear I’m not the only one facing this issue!

**Comment by BanannaCode** [comment]
Manage to have both accounts like the images but now for one account it shows errors when it comes to commenting:

Traceback (most recent call last):
  File "C:\Users\A\Documents\03_Hobbies\07_Python\InstaBot\test.py", line 25, in <module>
    session.like_by_tags(["travelgram"], amount = 1)
  File "C:\Python39\lib\site-packages\instapy\instapy.py", line 2056, in like_by_tags
    success = process_comments(
  File "C:\Python39\lib\site-packages\instapy\comment_util.py", line 438, in process_comments
    commented_image, message = verify_commented_image(browser, link, owner, logger)
  File "C:\Python39\lib\site-packages\instapy\comment_util.py", line 359, in verify_commented_image
    data = getMediaData("edge_media_to_parent_comment", browser)
  File "C:\Python39\lib\site-packages\instapy\util.py", line 500, in getMediaData
    data = additional_data["graphql"]["shortcode_media"]
TypeError: 'NoneType' object is not subscriptable

**Comment by BanannaCode** [comment]
Even if I skip commenting in the prompt for this account it does not stick to liking the x posts under one hashtag first, but rather likes one image under hashtag 1 and then proceeds to the next hashtag, likes one image etc.

I don't understand why it behaves so differently - one account completely smooth the other one not at all

**Comment by Ayub-Khan** [comment]
The number of comments and likes for new accounts are lower as compared to old accounts. your system got blocked. Lower the number of likes and comments and delete the cookies file and run again.

**Comment by BanannaCode** [comment]
Hi @Ayub-Khan 
I tried it once more with cookies deleted and like + comment count as only 1.
The liking works, but I get the same error code as mentioned above with TypeError: 'NoneType' object is not subscriptable.
Comparing to the other account on the same post liking and commenting works just fine.
