### ISSUE TITLE
 element not visible

### ISSUE THREAD

**Issue by kushpvo** [InstaPy/InstaPy#629]
Getting this error recently.
Running on a VPS server, 2GB RAM

`Traceback (most recent call last):
  File "quickstart.py", line 24, in <module>
    session.like_by_tags(['#australia', 'belgium', 'brazil'], amount=randint(minTag, maxTag))
  File "/root/InstaPy/instapy/instapy.py", line 531, in like_by_tags
    followed += follow_user(self.browser, self.follow_restrict, self.username, user_name)
  File "/root/InstaPy/instapy/unfollow_util.py", line 134, in follow_user
    follow_button.send_keys("\n")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 350, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=60.0.3112.113)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.10.0-28-generic x86_64)
`

**Comment by kushpvo** [comment]
Even after the latest pull, i'm still getting this error.

**Comment by andrewjburnett** [comment]
Still happening to me. What's the status?

**Comment by kushpvo** [comment]
It's happening to me as well, even after the latest pull

**Comment by GonzaloZiadi** [comment]
Still happening here after pull as well

**Comment by wizarduk** [comment]
Happening to me now has this been fixed ?

**Comment by converge** [comment]
It's fixed. Please reopen it if you still need some help.
