### ISSUE TITLE
TypeError: login_user() takes 8 positional arguments but 9 were given

### ISSUE THREAD

**Issue by ascoolarobban** [InstaPy/InstaPy#6292]
copy pasted from everywhere on the internet but get the same issue everytime:

```bash
INFO [2021-08-04 17:58:05] [username]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 10.36 seconds]
INFO [2021-08-04 17:58:05] [username]  Session ended!
Traceback (most recent call last):
  File "/Users/robin/Library/Mobile Documents/com~apple~CloudDocs/DEV/Python/instaBot/main.py", line 504, in <module>
    newBotLogin()
  File "/Users/robin/Library/Mobile Documents/com~apple~CloudDocs/DEV/Python/instaBot/main.py", line 184, in newBotLogin
    with smart_run(session):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/robin/Library/Mobile Documents/com~apple~CloudDocs/DEV/Python/instaBot/venv/venv/lib/python3.8/site-packages/instapy/util.py", line 1919, in smart_run
    session.login()
  File "/Users/robin/Library/Mobile Documents/com~apple~CloudDocs/DEV/Python/instaBot/venv/venv/lib/python3.8/site-packages/instapy/instapy.py", line 428, in login
    if not login_user(
TypeError: login_user() takes 8 positional arguments but 9 were given
```

im on a mac with Big Sur. some help here?

**Comment by Tr1pke** [comment]
2 years to late sorry

**Comment by elulcao** [comment]
I suspect your Instapy version is quite old, 
install with pip but using the latest commit from git.
