### ISSUE TITLE
Session ends, I don't understand why

### ISSUE THREAD

**Issue by mattheolaroche** [InstaPy/InstaPy#6298]
Here's what I have in the windows powershell (I'm new to github & programming and stuff so please be kind)

Traceback (most recent call last):
  File "C:\Users\LAROCHE Matthéo\Desktop\bot insta\instabot.py", line 21, in <module>
    session.like_by_tags(['tag1', 'tag2'], amount=100, interact=True)
  File "C:\Users\LAROCHE Matthéo\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\LAROCHE Matthéo\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

**Comment by Tr1pke** [comment]
> Here's what I have in the windows powershell (I'm new to github & programming and stuff so please be kind)
> 
> Traceback (most recent call last):
> File "C:\Users\LAROCHE Matthéo\Desktop\bot insta\instabot.py", line 21, in
> session.like_by_tags(['tag1', 'tag2'], amount=100, interact=True)
> File "C:\Users\LAROCHE Matthéo\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags
> inappropriate, user_name, is_video, reason, scope = check_link(
> File "C:\Users\LAROCHE Matthéo\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\like_util.py", line 633, in check_link
> media = post_page[0]["shortcode_media"]
> KeyError: 0

I can tell you why, this project is already for 2/3 years inactive, maybe thats the reason ..................

**Comment by NOCLAF1337** [comment]
>this project is already for 2/3 years inactive, maybe thats the reason ..................

Is Instapy deprecated?

**Comment by elulcao** [comment]
> >this project is already for 2/3 years inactive, maybe thats the reason ..................
> 
> 
> 
> Is Instapy deprecated?

No, it's up and running

**Comment by kharazian** [comment]
> deprecated



> > > this project is already for 2/3 years inactive, maybe thats the reason ..................
> > 
> > 
> > Is Instapy deprecated?
> 
> No, it's up and running

Hi,
this line of code do not work
media = post_page[0]["shortcode_media"]

do you have any idea?
Tanx
