### ISSUE TITLE
Session ended after first Like# Any Help 💻  ✌️ 

### ISSUE THREAD

**Issue by Danudab** [InstaPy/InstaPy#6304]
Hello everyone! I'm new here. 
Thank you for sharing all this info. Everything is working well except that, on each session after the first like the session automatically ends.  Any help? I really appreciate it! 
@timgrossmann 

Details: ⬇️  ⬇️ 

I'm using macOS Catalina 10.15.7
Python 3.9 and starting with quickstart

====================
InstaPy Version: 0.6.13

 Sessional Live Report:
	|> No any statistics to show

[Session lasted 2.1 minutes] Sometimes less.

and then I get this. 

Traceback (most recent call last):
  File "/Users/macbookpro/Desktop/instapy-quickstart-master/run/../quickstart.py", line 60, in <module>
    session.like_by_tags(random.sample(like_tag_list, 3),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 1957, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]

**Comment by Danudab** [comment]
Well actually, I just check back the first action, and the like wasn't there. 
So Instapy log out after trying to make the first action. 
Any idea how can I fix this? 
Thank you in advance

**Comment by parth23** [comment]
@Danudab  I'm also facing the same issue

**Comment by CookieHax** [comment]
Same issue here too.

**Comment by elulcao** [comment]
I would like to know if you are installing with pip and latest commit from git?
try installing with pip but latest commit from git.

```python
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/like_util.py", line 633, in check_link
```

**Comment by NOCLAF1337** [comment]
Same issue.

**Comment by NOCLAF1337** [comment]
> I would like to know if you are installing with pip and latest commit from git? try installing with pip but latest commit from git.

I have the same issue, I installed using `pip install instapy`.

**Comment by NOCLAF1337** [comment]
These commands fixed my problems :

`
pip uninstall instapy
pip install git+https://github.com/timgrossmann/InstaPy
`
