### ISSUE TITLE
NameError: name 'ModuleNotFoundError' is not defined

### ISSUE THREAD

**Issue by MericFournier** [InstaPy/InstaPy#6312]
## Current Behavior
i'm on a mac os v11
trying to launch the demo script 
i followed the installation guide 
and get this error when launching 

how could i resolve this ? 

```
Starting InstaPy with quickstart
====================
Traceback (most recent call last):
  File "../quickstart.py", line 8, in <module>
    from instapy import InstaPy
  File "/Library/Python/2.7/site-packages/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Library/Python/2.7/site-packages/instapy/instapy.py", line 21, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

```

**Comment by ErezAmihud** [comment]
Use python 3.6 and above. Not python 2

**Comment by elulcao** [comment]
Python2 has been deprecated, use Python3 instead as recommended in README
