### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by MehediHassan98** [InstaPy/InstaPy#6313]
Can anyone help me? I got this problem..

Traceback (most recent call last):
File "C:\Users\asus\Desktop\instapy\bot.py", line 141, in
getattr(session, job['functionName'])(**arguments)
File "C:\Users\asus\Desktop\instapy\env\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags
inappropriate, user_name, is_video, reason, scope = check_link(
File "C:\Users\asus\Desktop\instapy\env\lib\site-packages\instapy\like_util.py", line 633, in check_link
media = post_page[0]["shortcode_media"]
KeyError: 0

**Comment by ErezAmihud** [comment]
`pip install -I https://github.com/schealex/InstaPy/zipball/develop`
