### ISSUE TITLE
I received error is not one could you help me guys

### ISSUE THREAD

**Issue by behnoodafshari** [InstaPy/InstaPy#6338]
## InstaPy configuration

Last login: Sun Oct  3 17:58:06 on ttys002

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
/Users/behnoodafsharineshat/Downloads/instapy-quickstart-master/run/mac_start.command ; exit;
(base) iMac:~ behnoodafsharineshat$ /Users/behnoodafsharineshat/Downloads/instapy-quickstart-master/run/mac_start.command ; exit;
Starting InstaPy with quickstart
====================
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/behnoodafsharineshat/InstaPy"
Error, unable to determine correct filename for 64bit macos
Traceback (most recent call last):
  File "../quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "/Users/behnoodafsharineshat/opt/anaconda3/lib/python3.8/site-packages/instapy/instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Users/behnoodafsharineshat/opt/anaconda3/lib/python3.8/site-packages/instapy/browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/Users/behnoodafsharineshat/opt/anaconda3/lib/python3.8/site-packages/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/Users/behnoodafsharineshat/opt/anaconda3/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/Users/behnoodafsharineshat/opt/anaconda3/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/Users/behnoodafsharineshat/opt/anaconda3/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit macos
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]

**Comment by elulcao** [comment]
Install a valid FF browser, a valid geckodriver module and finally configure InstaPy
Please check the official InstaPy documentation for examples and further details.

**Comment by elulcao** [comment]
Check #6153
