### ISSUE TITLE
Error:  Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by hoangsoft90** [InstaPy/InstaPy#635]
when run on VPS (1gb ram), i got error:
``
Traceback (most recent call last):
  File "h-bot1.py", line 41, in job
    session.login()
  File "/root/htdocs/instagram/InstaPy/instapy/instapy.py", line 190, in login
    log_follower_num(self.browser, self.username)
  File "/root/htdocs/instagram/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    followed_by = browser.execute_script("return window._sharedData.entry_data.ProfilePage[0].user.followed_by.count")
  File "/root/htdocs/instagram/InstaPy/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/root/htdocs/instagram/InstaPy/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/root/htdocs/instagram/InstaPy/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: chrome=61.0.3163.79)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 3.13.0-125-generic x86_64)
``

**Comment by timgrossmann** [comment]
@hoangsoft90 Please also include your quickstart.py

**Comment by kevinhowbrook** [comment]
@hoangsoft90 can you run a test with a new account. For me, my issue was login based and not to do with the script itself.

**Comment by converge** [comment]
there is no interaction for a long time, pls reopen it if you need.

**Comment by ravneet89** [comment]
facing the same problem. Haven't been able to resolve since the past couple of days. Any solution for this?

**Comment by rglenn-accenture** [comment]
getting intermittent failures past few days when running on selenium grid with this as the alleged cause: "TypeError: Cannot read property '0' of null"
running angular 4 with following npm dependencies:
- [at]types/cucumber: ^2.0.4
- cucumber: ^3.1.0
- selenium-cucumber-js: ^1.5.2

**Comment by andrewjburnett** [comment]
Also having this issue. Anyone? I thinks its related to hitting the API too many times.

**Comment by hoangsoft90** [comment]
no, thank you.

On Fri, Jan 12, 2018 at 6:51 AM, Andrew J. Burnett <notifications@github.com

**Comment by l-t-k** [comment]
Same here
