### ISSUE TITLE
RPi3 ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by scott12123** [InstaPy/InstaPy#6357]
Hi, 

Just did a fresh install of Raspberry Pi OS, installed InstaPy as per https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md

Getting this error when running a basic quickstart.py

pi@raspberrypi:~ $ python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 33, in <module>
    from .clarifai_util import check_image
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "/home/pi/.local/lib/python3.7/site-packages/clarifai/rest/__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "/home/pi/.local/lib/python3.7/site-packages/clarifai/rest/client.py", line 36, in <module>
    from clarifai.rest.grpc.proto.clarifai.api.endpoint_pb2_grpc import V2Stub
  File "/home/pi/.local/lib/python3.7/site-packages/clarifai/rest/grpc/proto/clarifai/api/endpoint_pb2_grpc.py", line 2, in <module>
    import grpc
  File "/home/pi/.local/lib/python3.7/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/home/pi/.local/lib/python3.7/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /home/pi/.local/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-arm-linux-gnueabihf.so)

I've confirmed that all packages are already up to date.

Appreciate any assistance

Hardware Model: Raspberry Pi 3 Model B Rev 1.2
/etc/debian_version 10.11

Cheers

**Comment by mikestan** [comment]
Came here to leave the same report, yet I had seen a message earlier today that said Ubuntu on Raspberry Pi will work (now I can't find it). I could not get any Ubuntu Server/Core to boot on my Pi 3 Model 1.2. Sounds like a libs issue.

**Comment by scott12123** [comment]
I think you may be referring to this? #GLIBC 2.33 required but outdated #6333

Also shows libc6 is newest version on my pi

sudo apt install libc6 -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6 is already the newest version (2.28-10+rpt2+rpi1).

**Comment by elulcao** [comment]
> I think you may be referring to this? #GLIBC 2.33 required but outdated #6333
> 
> Also shows libc6 is newest version on my pi
> 
> sudo apt install libc6 -f Reading package lists... Done Building dependency tree Reading state information... Done libc6 is already the newest version (2.28-10+rpt2+rpi1).
> 
> My understanding is that GLIBC is meant to be backward compatible?

Hi @scott12123 
glibc it's suppose to be backward compatible, but not 100% accurate.
As mentioned in #6333, you must configure the OS libraries in order to execute 3rdParty applications like InstaPy

This is not an issue with InstaPy since we don't have any ownership about GLIBC.

**Comment by scott12123** [comment]
> to be honest is complicated to me determine what version you installed so I cannot figure out the root cause of the issue with the missing symbol.
> 
> The hard part, is that I cannot emulate ARM in my X64 and then I cannot reproduce the issue to WA it. 
>
> From your log it says you are using `GLIBC_2.28` `libc6 is already the newest version (2.28-10+rpt2+rpi1).` and `gnueabihf` requires `GLIBC_2.33` You need to determine how to update/downgrade the gnueabihf or reinstalling a new OS version that includes `GLIBC_2.33`

Hi @elulcao 

Is there any way I can assist you in figuring out the root cause of the issue? Happy to give any logs etc you may need

**Comment by maury37** [comment]
Hi @scott12123 , 

Did you manage to have InstaPy working again ?

**Comment by scott12123** [comment]
No unfortunately I gave up on trying to resolve this

**Comment by dfullerrowell** [comment]
I'm also experiencing this issue. Specifically, in `PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"` and `python -V` returns `Python 3.6.6`. The error I'm getting with that env is:
`File "/home/pi/miniconda3/envs/assistant-env/lib/python3.6/site-packages/grpc/_compression.py", line 15, in <module>
from grpc._cython import cygrpc
ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /home/pi/miniconda3/envs/assistant-env/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-arm-linux-gnueabihf.so)`

In addition, I have attempted to configure my env on the same arm7l hardware using python 3.5.6 {w/ pip) & more recently 3.8 without pip. I can reproduce the error with 3.5.6, however testing 3.8 is taking some time. Side note: To reproduce the error on 3.5.6 i had to remove trailing commas on a few lines in `/home/pi/miniconda3/envs/py35/lib/python3.5/site-packages/openai/api_resources/abstract/engine_api_resource.py` 

I will report back with my findings, and I would really love to hear any advice you guys have to offer! The other option is ditch trying to run this project on non x86_64 arch devices, which would be a REAL SHAME. It has been over a week of this issue being a stone in my shoe. I'm not an expert, but I was under the impression that, in theory, arm should be capable of the same fundamental operations as x86, so there's nothing fundamentally restricting execution of a newer version. Is it correct to say that the cause of the issue is `cygrpc` is compiled using a version of the c compiler that is incompatible with the latest version of Raspbian?

**Comment by dfullerrowell** [comment]
P.S. I gave up not using pip in python3.8, and i'm seeing this potentially relevant error message when `pip3.8 install google-cloud-texttospeech` 
```
Installing collected packages: grpcio, grpcio-status, google-api-core, google-cloud-texttospeech
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.41.1
    Uninstalling grpcio-1.41.1:
      Successfully uninstalled grpcio-1.41.1
  Attempting uninstall: google-api-core
    Found existing installation: google-api-core 1.16.0
    Uninstalling google-api-core-1.16.0:
      Successfully uninstalled google-api-core-1.16.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cygrpc 1.0.4.post6 requires grpcio-tools==1.23.0, which is not installed.
cygrpc 1.0.4.post6 requires grpcio==1.23.0, but you have grpcio 1.42.0 which is incompatible.
Successfully installed google-api-core-2.2.2 google-cloud-texttospeech-2.9.0 grpcio-1.42.0 grpcio-status-1.42.0
```
or is that a warning?

**Comment by dfullerrowell** [comment]
> @scott12123
> 
> The standard libs, GLIBC, varies from version to version. Said that, the Distros don't usually update the GLIBC version from the one packaged since doing a mistake during the update could give you the chance to reinstall the OS from scratch. As you mentioned, this issue has been discovered after installed the OS. to be honest is complicated to me determine what version you installed so I cannot figure out the root cause of the issue with the missing symbol.
> 
> The hard part, is that I cannot emulate ARM in my X64 and then I cannot reproduce the issue to WA it.
> 
> The problem resides in `cygrpc.cpython-37m-arm-linux-gnueabihf.so` not in InstaPy, and hence no action or recommendation can be done; at least to install a new OS version that includes a new GLIBC
> 
> From your log it says you are using `GLIBC_2.28` `libc6 is already the newest version (2.28-10+rpt2+rpi1).` and `gnueabihf` requires `GLIBC_2.33` You need to determine how to update/downgrade the gnueabihf or reinstalling a new OS version that includes `GLIBC_2.33`

may I send you a raspberry pi? I would gladly send u one (no expectation of a fix). Just as a token of my thanks for ur help so far. PM me where to send it :)

**Comment by mikestan** [comment]
Got InstaPy working by installing Ubuntu server (latest, but NOT "core"  -- use the Raspberry Pi Imager --> Other General Pupose OS -- Ubuntu Server/64-bit) and skip "Install Geckodrivver" part of the Raspberry Pi guide (the part after install FIrefox) on the InstaPy install page for Raspberry Pi page... Not ideal (IMPO), but it works for now to use RPi3B as an IG bot....

**Comment by mikestan** [comment]
> Got InstaPy working by installing Ubuntu server (latest, but NOT "core" -- use the Raspberry Pi Imager --> choose "Other General Pupose OS" in options --> Ubuntu Server/64-bit +update/upgrade) and then follow Rasperry Pi Guide on InstaPy page, SKIPPING "Install Geckodrivver" part (the part after install FIrefox) on the InstaPy install page...
> 
> Not ideal (IMPO - I personally think this should work with Raspbian OS), but it works for now to use RPi3B as an IG bot....

Follow THIS tutorial: https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi#1-overview

**Comment by mikestan** [comment]
...and if your Ubuntu install hangs randomly, create a swap partition 2x the installed RAM (mine was 1GB, so I made a 2GB swap partition on my 16GB SD card. Helped for me 🍺😷👍

**Comment by maury37** [comment]
Thanks @mikestan ! Solution works !

**Comment by Max-cmd-dot** [comment]
Hello,
I have a Raspberry pi 3b at the moment and have installed Ubuntu (with GNOME desktop) as described above. Unfortunately when I run quickstart.py I get the following error:
"""
Traceback (most recent call last):
  File "/home/ubuntu/quickstart.py", line 53, in <module>
    session = InstaPy(username=insta_username,
  File "/home/ubuntu/.local/lib/python3.9/site-packages/instapy/instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/instapy/browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 179, in __init__
    RemoteWebDriver.__init__(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)


"""
Does anyone have an idea how I can fix this?
Thanks for your help!
LG
