### ISSUE TITLE
Can not start instaPY

### ISSUE THREAD

**Issue by Fred0078** [InstaPy/InstaPy#6358]
Installed latest python3 on Windows 10, latest Firefox and Chrome.
Default quickstart.py with correct insta credentials

Here are the error messages I get:

What am I missing?

C:\Insta>quickstart.py
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/fred.DESKTOP-FIGUPVC/InstaPy"
Traceback (most recent call last):
  File "C:\Insta\quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\instapy\instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\instapy\browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 180, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by scott12123** [comment]
I received this same error and resolved it by installing Firefox. Try removing and re-installing firefox with a new installer from their website.

**Comment by Fred0078** [comment]
Thanks!

Re-installed firefox. No change.

However, this is confusing. The installer doesnt check for firefox, it does check for chrome. But not firefox. But then you start i get exceptions referring to firefox.  

BATCH SESSION SUCCESSFUL(PYTHON, PIP, CHROME, AND INSTAPY ALL VERIFIED AND INSTALLED) YOU MAY EXIT NOW

starting instapy with quickstart
================================
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/fred.DESKTOP-FIGUPVC/InstaPy"
Traceback (most recent call last):
  File "C:\Insta\quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\instapy\instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\instapy\browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 180, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line


> I received this same error and resolved it by installing Firefox. Try removing and re-installing firefox with a new installer from their website.

**Comment by elulcao** [comment]
> Installed latest python3 on Windows 10, latest Firefox and Chrome. Default quickstart.py with correct insta credentials
> 
> Here are the error messages I get:
> 
> What am I missing?
> 
> C:\Insta>quickstart.py InstaPy Version: 0.6.13 ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. Workspace in use: "C:/Users/fred.DESKTOP-FIGUPVC/InstaPy" Traceback (most recent call last): File "C:\Insta\quickstart.py", line 22, in session = InstaPy(username=insta_username, File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\instapy\instapy.py", line 325, in **init** self.browser, err_msg = set_selenium_local_session( File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\instapy\browser.py", line 123, in set_selenium_local_session browser = webdriver.Firefox( File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 180, in **init** RemoteWebDriver.**init**( File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in **init** self.start_session(capabilities, browser_profile) File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session response = self.execute(Command.NEW_SESSION, parameters) File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute self.error_handler.check_response(response) File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

Here the links for official documentation, for installing custom version of FF and geckodriver.

https://instapy.org
https://instapy.org/instance-settings#choose-the-browser-version
https://instapy.org/additional-information#custom-geckodriver

**Comment by elulcao** [comment]
> Thanks!
> 
> Set path in quickstart.py script to point to firefox.exe. Still getting a terminating exception. Path is correct and points to firefox.exe. Browser dont load - and windows start .bat script fails saying firefox.exe is not a correct binary.
> 
> (Path is correct, and firefox is latest version - loads up perfectly if exact same path is executed from the CMD terminal for example. So nothing wrong there.)
> 
> Tried to change to chrome.exe. It now loads the browser. But then nothing happens. Seems like the selenium is not talking to the browser because there is no authentication to instagram.com etc. Nothing happens in short.
> 
> Exactly which browser is required for selenium? The InstaPY Installer checks the required dependency for Chrome. Firefox is never mentioned. Very confusing.
> 
> (I dont really care which browser to use)
> 
> InstaPy Version: 0.6.13 ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. Workspace in use: "C:/Users/fred.DESKTOP-FIGUPVC/InstaPy" Traceback (most recent call last): File "C:\Insta\quickstart.py", line 24, in session = InstaPy(username=insta_username, File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\instapy\instapy.py", line 325, in **init** self.browser, err_msg = set_selenium_local_session( File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\instapy\browser.py", line 123, in set_selenium_local_session browser = webdriver.Firefox( File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 180, in **init** RemoteWebDriver.**init**( File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in **init** self.start_session(capabilities, browser_profile) File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session response = self.execute(Command.NEW_SESSION, parameters) File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute self.error_handler.check_response(response) File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable
> 
> QUESTION: Exactly which browser is the official requirement? It should be Chrome since that is tne only dependency being checked?
> 
> QUESTION: Which folders are of interest? So that I can delete everything and start a new fresh install. What Ive found is: $env:HOMEDRIVE\Users$env:USERNAME\InstaPy $env:HOMEDRIVE\Users$env:USERNAME\AppData* (nothing store in here? what about the SQLite .db file?)
> 
> > Here the links for official documentation, for installing custom version of FF and geckodriver.
> > https://instapy.org https://instapy.org/instance-settings#choose-the-browser-version https://instapy.org/additional-information#custom-geckodriver

Chrome is not supported, instead use Firefox ESR. FF latest release cannot be changed to hide the marionette actions or extensions like the one used by InstaPy.
Try with FF 77
HOME/Instapy is the workspace, used for logs and db file. the db file is used for persistent storage (interactions, etc)
there is also another set of files for persistent storage and PKL file (the cookie for accessing the IG acct). You shouldn't modify the WORKSPACE at least if you don't know how to handle it.

**Comment by Fred0078** [comment]
Thanks!

Could not find FF ESR 77 - closest available was 78.15 

However, no luck. Browser wont start as (selenium?) refuses to load FF?

_selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable_

However, nothing wrong with FF - it loads and works perfect if starting manually.

Very confusing. If chrome not recommended, then why does the installer check that dependency (firefox is not mentioned)?

**Versions:
Windows 10/Python 3
Firefox 78.15.0esr (64-bit)
geckodriver-v0.30.0-win32

general.log and general.log are both empty**

session = InstaPy(username=insta_username,
                  password=insta_password,
                  browser_executable_path="C:\Program Files\Mozilla Firefox\firefox.exe",
                  headless_browser=False)
				 
InstaPy Version: 0.6.13

_RESULT:
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/fred.DESKTOP-FIGUPVC/InstaPy"
Traceback (most recent call last):
  File "C:\Insta\quickstart.py", line 24, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\instapy\instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\instapy\browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 180, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\fred.DESKTOP-FIGUPVC\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable

Press any key to continue . . ._
