### ISSUE TITLE
webdriver exception on unfollow_util.py at get_users_through_dialog_with_graphql function (line 634) on try catch

### ISSUE THREAD

**Issue by Defdjamel** [InstaPy/InstaPy#6387]
**anyone get this webdriver  exception happen on unfollow_util.py at get_users_through_dialog_with_graphql function (line 634) on try catch**
## Expected Behavior
During handling of the above exception, another exception occurred:
```

Traceback (most recent call last):
  File "/Users/james/Projects/botInsta/main.py", line 25, in <module>
    session.follow_user_followers(users, amount=10, randomize=False, sleep_delay=600)
  File "/Users/james/Projects/botInsta/venv/lib/python3.9/site-packages/instapy/instapy.py", line 3675, in follow_user_followers
    person_list, simulated_list = get_given_user_followers(
  File "/Users/james/Projects/botInsta/venv/lib/python3.9/site-packages/instapy/unfollow_util.py", line 1005, in get_given_user_followers
    person_list, simulated_list = get_users_through_dialog_with_graphql(
  File "/Users/james/Projects/botInsta/venv/lib/python3.9/site-packages/instapy/unfollow_util.py", line 667, in get_users_through_dialog_with_graphql
    user_id = browser.execute_script(
  File "/Users/james/Projects/botInsta/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 872, in execute_script
    return self.execute(command, {
  File "/Users/james/Projects/botInsta/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "/Users/james/Projects/botInsta/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window._sharedData.entry_data.ProfilePage[0].graphql is undefined
Stacktrace:
@https://www.instagram.com/jlo/:2:7
@https://www.instagram.com/jlo/:3:8

```

```
geckolog : 
JavaScript error: https://www.instagram.com/, line 53: TypeError: window.__bufferedErrors is undefined
```

geckolog : 
JavaScript error: https://www.instagram.com/, line 53: TypeError: window.__bufferedErrors is undefined

## Possible Solution (optional)
maybe a javascript error .
## InstaPy configuration

Firefox 73.01
Mac OS M1 monterey
python 3.9.7
instapy  0.6.14 with modified login cookie handle

```
from os import close
from instapy import InstaPy
from instapy import smart_run

insta_username = ''
insta_password = ''

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
  users = ['jlo'] 
  session.follow_user_followers(users, amount=10, randomize=False, sleep_delay=600)
```

**Comment by Defdjamel** [comment]
after digging,problem comes from  the function to get user_id :

**Comment by Defdjamel** [comment]
problem come from the function to get the user_id :    
at unfollow_util.py line 634   at get_users_through_dialog_with_graphql function:
```
try :
user_id = browser.execute_script(
             "return window.__additionalData[Object.keys(window.__additionalData)[0]].data.graphql.user.id"
  except WebDriverException:
           user_id = browser.execute_script(
               "return window._sharedData.entry_data.ProfilePage[0].graphql.user.id"
           )
```


the javacript script try to get `window.__additionalData` but it doesn't exist anymore , instagram change it to 

> `__additionalDataLoaded("....")`

 the user_id is on parameter of this function : 
now:

> `window.__additionalDataLoaded('feed',{"user":{"id":"18250865","profile_pic_url":"https://scontent-cdt1-1.cdninstagram.com/v/t51.2885-19/s150x150/121422870_778991819589848_4638567315270601199_n.jpg?...."`

**if someone know how to extract parameters as String or Json as Python object..**.

_NB: `_sharedData.entry_data.ProfilePage is empty now._

**Comment by gabinfoulard** [comment]
@elulcao could you look at this ?

**Comment by Asdrubale2022** [comment]
@timgrossmann still same problem

**Comment by kleber011** [comment]
The same problem
