### ISSUE TITLE
this bot can`t open chrome

### ISSUE THREAD

**Issue by Vladios121** [InstaPy/InstaPy#6399]
Hello! I installed this simple bot, but at startup gives this error.
ERROR [2021-11-20 18:23:40] [anatoliytakoy]  Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90),platform=Windows NT 10.0.19044 x86_64)
Traceback (most recent call last):
  File "D:\Users\Влад\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instapy\browser.py", line 121, in set_selenium_local_session
    browser = webdriver.Chrome(chromedriver_location,
  File "D:\Users\Влад\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "D:\Users\Влад\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "D:\Users\Влад\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\Users\Влад\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Users\Влад\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "D:\Users\Влад\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90),platform=Windows NT 10.0.19044 x86_64)

Traceback (most recent call last):
  File "D:\Users\Влад\Desktop\instapy-quickstart-master\quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "D:\Users\Влад\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instapy\instapy.py", line 276, in __init__
    self.set_selenium_local_session()
  File "D:\Users\Влад\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instapy\instapy.py", line 328, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at D:\Users\Влад\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instapy_chromedriver\chromedriver_win32.exe
HELP ME PLEASE!!!!

**Comment by CodeMasterBond** [comment]
Make sure you have all the required files installed and in working condition (upgraded). To install all the files in the requirements.txt file, type ``pip** install -r requirements.txt`` in the shell. Also, make sure you pip install ``instapy`` and ``selenium`` as they are the foundations of the project.

**Comment by Vladios121** [comment]
After all updates and installation of selenium, when starting the bot, an error crashes and it immediately closes

**Comment by CodeMasterBond** [comment]
This may or may not determine whether the program runs, but what IDE are you using?

**Comment by Vladios121** [comment]
I use python and did everything according to the instructions

**Comment by CodeMasterBond** [comment]
Correct. Your supposed to use python for a python project and not javascript. What I was asking for however was whether you were using VSC, repl, pycharm...

**Comment by Vladios121** [comment]
Oh, sorry, didn't understand correctly. I use IDLE.
I'm a complete zero in this case.

**Comment by ezzcodeezzlife** [comment]
```
...
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
...
```

make sure you have chrome installed & chromedriver from https://chromedriver.chromium.org/downloads in the same directory. 

make sure you download the fitting version for you chrome (you can find your chrome version help>about google chrome)

**Comment by CodeMasterBond** [comment]
Yep. As @ezzcodeezzlife said above, ``make sure you have chrome installed & chromedriver... in the same directory.``

**Comment by Vladios121** [comment]
Nothing changed after I installed the chorme driver))

**Comment by elulcao** [comment]
@Vladios121 
Chrome has been deprecated since 0.6.0, 

```
## [0.6.0] - 2019-08-12

### Added

- Firefox Extension which hides Selenium
- Black code formatter
- Mobile user agent
- Mobile Mode to enable mobile features
- Screen shots (rotative screen shots are taken and saved in your InstaPy user folder)
- Connection State

### Breaking Changes

- removed chromedriver
- signature changes:
  - set_action_delays(random_range) -> (random_range_from, random_range_to)
  - set_delemit_liking(max, min) ->(max_likes, min_likes)
  - set_delemit_commenting(max, min) ->(max_comments, min_comments)
  - unfollow_users(customList, instapyfollowed) -> (custom_list_enabled, custom_list, custom_list_param, instapy_followed_enabled, instapy_followed_param)
  - set*quota_supervisor(peak*_) ->(peak\_\_\_hourly, peak_\*\_daily)

```

**Comment by adrielkirch** [comment]
@Vladios121 have you already solved this issue, it's happening to me with instapy?

**Comment by kristijorgji** [comment]
Why was Chrome deprecated, any reason?
