### ISSUE TITLE
it was okay but now it cannot work

### ISSUE THREAD

**Issue by akyab** [InstaPy/InstaPy#6400]
this is what i get whenever i try to run the code: please HELP 

Traceback (most recent call last):
  File "C:\insta\in.py", line 10, in <module>
    with smart_run(session):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\util.py", line 1962, in smart_run
    session.login()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 472, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\print_log_writer.py", line 21, in log_follower_num
    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\util.py", line 488, in getUserData
    data = shared_data["entry_data"]["ProfilePage"][0]
TypeError: 'NoneType' object is not subscriptable
PS C:\insta>

**Comment by elulcao** [comment]
@akyab 
Check the README for instructions 
https://github.com/InstaPy/InstaPy/blob/master/docs/home.md#installation

**Comment by gui-ducci** [comment]
It looks like you are getting a TypeError when trying to access an element of a list that is None. This error is occurring because the ProfilePage key in the entry_data dictionary is returning None, which means it is not a subscriptable object (i.e., you cannot use the square brackets [] to access elements of it).

There could be a number of reasons why this error is occurring. Here are a few things you might want to check:

Make sure that you are using the correct username. If you are using an incorrect username, you might be getting a different page than the profile page, which would not have the ProfilePage key in the entry_data dictionary.

Check the network connection. If you are not connected to the internet or if the Instagram website is experiencing issues, you might not be able to access the profile page.

Check for any other errors that might be occurring earlier in your code. If there are other errors occurring before this point, they might be causing the entry_data dictionary to be None, which would cause this error to be raised.

I hope this helps! Let me know if you have any other questions or if you need further assistance.

**Comment by official-antique** [comment]
@gui-ducci sharedData no longer exists, no matter what this or any user does it will not work.
