### ISSUE TITLE
like_util.py 878

### ISSUE THREAD

**Issue by jayjay992** [InstaPy/InstaPy#6411]
I keep getting an error with this file 
like_util.py Line 878

its saying its missing a comma possibly????

**Comment by elulcao** [comment]
@jayjay992 
could you share the output? remove the sensitive info.

**Comment by jayjay992** [comment]
i fixed this line now im getting


PS C:\Users\stayf\desktop> py instabot.py
InstaPy Version: 0.6.14
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/stayf/InstaPy"
Traceback (most recent call last):
  File "C:\Users\stayf\desktop\instabot.py", line 3, in <module>
    session = InstaPy(username="jay.bagchasin" , password="*")
  File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 327, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 179, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by elulcao** [comment]
> i fixed this line now im getting
> 
> PS C:\Users\stayf\desktop> py instabot.py InstaPy Version: 0.6.14 ._. ._. ._. ._. ._. ._. ._. ._. ._. Workspace in use: "C:/Users/stayf/InstaPy" Traceback (most recent call last): File "C:\Users\stayf\desktop\instabot.py", line 3, in session = InstaPy(username="jay.bagchasin" , password="*") File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 327, in **init** self.browser, err_msg = set_selenium_local_session( File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\browser.py", line 123, in set_selenium_local_session browser = webdriver.Firefox( File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 179, in **init** RemoteWebDriver.**init**( File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in **init** self.start_session(capabilities, browser_profile) File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session response = self.execute(Command.NEW_SESSION, parameters) File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute self.error_handler.check_response(response) File "C:\Users\stayf\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

Explain how did you solve the issue.
Then create another Ticket for the new issue,
