### ISSUE TITLE
WebDriverException occurs

### ISSUE THREAD

**Issue by its-ogawa** [InstaPy/InstaPy#6414]
## Expected Behavior
I want to know how to run grab_followers using geckodriver.

## Current Behavior
I have the latest version of Firefox (94.0.2) and the latest version of geckodriver (0.30.0), but when I run grab_followers I get a WebDriverException.

Looking at the output, it seems to be looking for a chromedriver, is it possible to pre-specify the webdriver that instapy uses?

Note that I have tried like_by_tag in the quick reference and it works fine.

I don't know why grab_followers doesn't work.

Any advice would be appreciated in advance.

```
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Custom workspace set: "./InstaPy" :]
InstaPy Version: 0.6.14
 ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "./InstaPy"
Traceback (most recent call last):
  File "like_by_followers.py", line 14, in <module>
    session = InstaPy(username=USERNAME,
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\instapy\instapy.py", line 327, in __init__       
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\instapy\browser.py", line 131, in set_selenium_local_session
    browser.install_addon(create_firefox_extension(), temporary=True)
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\firefox\webdriver.py", line 253, in install_addon
    return self.execute("INSTALL_ADDON", payload)["value"]
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 
247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Expected absolute path: [Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: chrome://remote/content/marionette/addon.js :: install :: line 70"  data: no]
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5
UnknownError@chrome://remote/content/shared/webdriver/Errors.jsm:488:5
install@chrome://remote/content/marionette/addon.js:72:13
GeckoDriver.prototype.installAddon@chrome://remote/content/marionette/driver.js:2655:16
despatch@chrome://remote/content/marionette/server.js:306:40
execute@chrome://remote/content/marionette/server.js:279:16
onPacket/<@chrome://remote/content/marionette/server.js:252:20
onPacket@chrome://remote/content/marionette/server.js:253:9
_onJSONObjectReady/<@chrome://remote/content/marionette/transport.js:500:20
```

## InstaPy configuration

```
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

work_dir = "./"
set_workspace(path=work_dir)

# get an InstaPy session!
session = InstaPy(username=USERNAME,
                password=PASSWORD,
                multi_logs=True
                )

with smart_run(session):
    followers = session.grab_followers(username=INFLUENCER, amount="full", live_match=True, store_locally=True)

print(followers)
```

**Comment by elulcao** [comment]
@its-ogawa 
could you check `addon.js` and deactivate that add-on 
it seems to be the problem based in the log provided

**Comment by its-ogawa** [comment]
Thank you for your comment.
I can't find addon.js.
Where is it originally created?

**Comment by elulcao** [comment]
@its-ogawa 
one step back, it seems that the error comes from selenium layer instead of InstaPy

since you are using Windows `File "C:\Users\ogawa\AppData` then paths must be using 
backslashes `\` instead of slashes `/`. 

```
work_dir = "./"
set_workspace(path=work_dir)
```

Then, I would like to recommend to verify the path string at your local.

**Comment by its-ogawa** [comment]
Thank you for your comment.

The `". /"` seems to work fine.
(I may need to use `r". /"`.)


```
import os

work_dir = "./"
print(os.path.abspath(work_dir))
```

I get the following results with this script

```
C:\Users\ogawa\Documents\Docker\instagramlike3\app
```

**Comment by elulcao** [comment]
In Windows, the `.` is for the current directory (for the filesystem), the `/` is for domain from user (the User Path).
In Unix-like the `.` is the current directory (for the filesystem), but the localhost is 
referenced with the `/`

Double check the syntax, you are not in Unix-like OS.

If you want to see the the real error at geckodriver layer use this `geckodriver_log_level="trace",` in the session constructor, and verify the log created.

```python
session = InstaPy(
    username="",
    password="",
    geckodriver_log_level="trace",
)
```

**Comment by its-ogawa** [comment]
Thanks for telling me about geckodriver_log_level.
Adding that worked fine! 

But what I don't understand is that now it works fine without it anymore...
