### ISSUE TITLE
`grab_followers` does not work!

### ISSUE THREAD

**Issue by its-ogawa** [InstaPy/InstaPy#6424]
### Current Behavior

I am getting the following exception.

`selenium.common.exceptions.JavascriptException: Message: TypeError: window.__additionalData[Object.keys(...)[0]] is undefined`

#### script

The script I ran is as follows.

```
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace
import os

work_dir = os.path.join(os.getcwd(), "InstaPy")
set_workspace(path=work_dir)

username = <username>
password = <password>
influencer = <target>

# get an InstaPy session!
session = InstaPy(username=username,
                password=password,
                headless_browser=True,  
                disable_image_load=True,
                multi_logs=True         
                )

with smart_run(session):
    followers = session.grab_followers(
        username=influencer, 
        amount="full", 
        live_match=True, 
        store_locally=True
        )
```

#### output

When I run the above script, I get the following message.

```
>python test.py
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Custom workspace set: "/InstaPy" :]
InstaPy Version: 0.6.14
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-12-06 15:21:54] [<username>]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-12-06 15:21:54] [<username>]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-12-06 15:21:54] [<username>]  - Internet Connection Status: ok
INFO [2021-12-06 15:21:54] [<username>]  - Current IP is "XXX.XXX.XXX.XXX" and it's from "Japan/JP"
INFO [2021-12-06 15:21:54] [<username>]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-12-06 15:21:54] [<username>]  - window.navigator.webdriver response: True
WARNING [2021-12-06 15:21:54] [<username>]  - Hide Selenium Extension: error
INFO [2021-12-06 15:21:57] [<username>]  - Cookie file not found, creating cookie...
INFO [2021-12-06 15:22:22] [<username>]  - Do not save Login Info by now...
................................................................
INFO [2021-12-06 15:22:34] [<username>]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2021-12-06 15:22:34] [<username>]  Saving account progress...
_______________________________________________________________________________
INFO [2021-12-06 15:22:38] [<username>]  Starting to get the `Followers` data..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2021-12-06 15:22:38] [<username>]  Retrieving live `Followers` data of <target> at "full" range

INFO [2021-12-06 15:22:43] [<username>]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 55.32 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-12-06 15:22:43] [<username>]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\instapy\relationship_tools.py", line 116, in get_followers
    user_data["id"] = browser.execute_script(
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 878, in execute_script
    return self.execute(command, {
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window.__additionalData[Object.keys(...)[0]] is undefined
Stacktrace:
@https://www.instagram.com/<target>/:2:45
@https://www.instagram.com/<target>/:3:8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 22, in <module>
    followers = session.grab_followers(
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\instapy\instapy.py", line 4537, in grab_followers
    grabbed_followers = get_followers(
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\instapy\relationship_tools.py", line 121, in get_followers
    user_data["id"] = browser.execute_script(
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 878, in execute_script
    return self.execute(command, {
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ogawa\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window._sharedData.entry_data.ProfilePage[0].graphql is undefined
Stacktrace:
@https://www.instagram.com/<target>/:2:7
@https://www.instagram.com/<target>/:3:8
```

**Comment by its-ogawa** [comment]
Very puzzling, but it works now.
Sorry for the inconvenience.

**Comment by gabinfoulard** [comment]
@ses-ogawa What did you do for making your script work ?

**Comment by its-ogawa** [comment]
Thank you @gabinfoulard for your question.
I know it sounds very puzzling, but I am not doing any special operations.
Just in case, I have listed the versions of my python and instapy related modules.
Could you please try to run it with the following configuration?

```
>python --version
Python 3.8.12

>conda list
... snip ...
geckodriver               0.30.0               hdb13177_0    conda-forge
... snip ...
instapy                   0.6.14                   pypi_0    pypi
... snip ...
selenium                  3.141.0         py38h294d835_1003    conda-forge
... snip ...
```

**Comment by gabinfoulard** [comment]
> Merci @gabinfoulard pour votre question. Je sais que cela semble très déroutant, mais je ne fais aucune opération spéciale. Juste au cas où, j'ai répertorié les versions de mes modules liés à python et instapy. Pourriez-vous s'il vous plaît essayer de l'exécuter avec la configuration suivante ?
> 
> ```
> >python --version
> Python 3.8.12
> 
> >conda list
> ... snip ...
> geckodriver               0.30.0               hdb13177_0    conda-forge
> ... snip ...
> instapy                   0.6.14                   pypi_0    pypi
> ... snip ...
> selenium                  3.141.0         py38h294d835_1003    conda-forge
> ... snip ...
> ```

I tried with your configuration and i already have the same error !

**Comment by its-ogawa** [comment]
@gabinfoulard 
Hmmm. I'm not sure what's causing this.
I'm attaching my requirements.txt file just in case.
Maybe it's not a problem with an environment.

[conda_requirements.txt](https://github.com/InstaPy/InstaPy/files/7893296/conda_requirements.txt)

**Comment by Asdrubale2022** [comment]
Still does not work @its-ogawa "get_given_user_followers" from unfollow_util.py is working since it uses xpath. "get_followers" from relationship_tools.py is not working since it uses graphql queries.

**Comment by ersom** [comment]
Does anyone have a solution to this yet? I cannot get this to work...
