### ISSUE TITLE
Accept cookie problem !!

### ISSUE THREAD

**Issue by gabinfoulard** [InstaPy/InstaPy#6426]
Hello,

I have a problem with **accepting cookies** and specifically the 'accept all' button. The script **click on 'manage data settings'** and go to this page : https://ibb.co/dL3WswM

### Here is the cmd report (script used: quickstart.py)

quickstart.py errorcode:

`OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-12-06 12:37:35] [ahmedtestbg]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2021-12-06 12:37:35] [ahmedtestbg]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-12-06 12:37:35] [ahmedtestbg]  - Internet Connection Status: ok
INFO [2021-12-06 12:37:35] [ahmedtestbg]  - Current IP is "xxxxxxxxxxxxx" and it's from "France/FR"
INFO [2021-12-06 12:37:35] [ahmedtestbg]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-12-06 12:37:35] [ahmedtestbg]  - window.navigator.webdriver response: True
WARNING [2021-12-06 12:37:35] [ahmedtestbg]  - Hide Selenium Extension: error
INFO [2021-12-06 12:37:37] [ahmedtestbg]  - Cookie file not found, creating cookie...
INFO [2021-12-06 12:38:22] [ahmedtestbg]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
C:\Users\user1\AppData\Local\Temp\20211206-123827.html
**********************************************************************

INFO [2021-12-06 12:38:27] [ahmedtestbg]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 59.21 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-12-06 12:38:27] [ahmedtestbg]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "C:\InstaPy_Bot\quickstart.py", line 27, in <module>
    with smart_run(session):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 121, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield
Appuyez sur une touche pour continuer...`

--------------------------------
I tried using the method from the following posts:

-#5837
-#5886
-#5834

But I always get the same error : 

 ` File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 121, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield`

I tried to change the instagram account (in case of softban)
Changing my IP (if it was banned)

Nothing works whereas yesterday everything was perfect !
If I accept manually cookies, the script is working... strange

### My other question is : 
By modifying the instapy scripts (like util.py, login_util.py, xpath\compile...) directly in the \ AppData \ Local \ Packages \ ... folder, will they be deleted in order to be replaced by a future update? 
Because if this is the case, if the modifications to be made are not present in the updates, it will be necessary to replace the files manually each time ??

I saw a lot of issues on the web about this porblem, so it's time to fix it once and for all.

I admit not knowing where to look anymore .. I have tried everything.
Thanks to those who will respond!

Gab

**Comment by GebbenPlayz** [comment]
I got it too....

**Comment by bschro99** [comment]
Same here
