### ISSUE TITLE
ImportError: No module named instapy

### ISSUE THREAD

**Issue by stymdxt** [InstaPy/InstaPy#6430]
## Expected Behavior

quick-start.py file should run

## Current Behavior
tarting InstaPy with quickstart
====================
Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
ImportError: No module named instapy
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by CodeMasterBond** [comment]
In the console before you run the program, type ``pip install instapy``

**Comment by noobNovato** [comment]
i have the same error.

**Comment by noobNovato** [comment]
use python3 instead of python

**Comment by stefanimitova** [comment]
Even after "pip install instapy"  all requirements are satisfied and there is:

Traceback (most recent call last):
  File "/Users/stefanimitova/Documents/Pyhton_bot/instapy-quickstart-master/quickstart.py", line 2, in <module>
    from instapy import InstaPy
ImportError: No module named instapy. 

Any recommendations?
(python --version Python 3.10.2)

**Comment by fudojahic** [comment]
Is this been fixed?  I have the same error and I believe my instapy is installed! ahh

**Comment by Shclick** [comment]
> Is this been fixed? I have the same error and I believe my instapy is installed! ahh

@fudojahic Yeah same

**Comment by erwinowak** [comment]
constantly having problems with this bot..

**Comment by muneef1994** [comment]
from instapy import instaPy
ModuleNotFoundError: No module named 'instapy

still getting same error

**Comment by tatoosa** [comment]
none solve it?

**Comment by iransales** [comment]
none solve it????

**Comment by damshly2** [comment]
I have the same error and I believe my instapy is installed
