### ISSUE TITLE
InstaPy won't run on my MacOS  username: str = None,

### ISSUE THREAD

**Issue by FethiAmari** [InstaPy/InstaPy#6439]
## Expected Behavior
I keep getting this error when I run 'python quickstart.py'.

## Current Behavior
python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/Users/fethi/Documents/Insta/InstaPy/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/Users/fethi/Documents/Insta/InstaPy/instapy/instapy.py", line 109
    username: str = None,
            ^
SyntaxError: invalid syntax

## InstaPy configuration

```python
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'abcd'
insta_password = '1234'

comments = ['Nice shot! @{}',
        'I love your profile! @{}',
        'Your feed is an inspiration :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Getting inspired by you @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:']

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
  """ Activity flow """		
  # general settings		
  session.set_dont_include(["friend1", "friend2", "friend3"])		
  
  # activity		
  session.like_by_tags(["natgeo"], amount=10)

  # Joining Engagement Pods
  session.set_do_comment(enabled=True, percentage=35)
  session.set_comments(comments)
  session.join_pods(topic='sports', engagement_mode='no_comments')
```

**Comment by CodeMasterBond** [comment]
In the terminal/console type “pip install instapy”

**Comment by Fethi89Dz** [comment]
> In the terminal/console type “pip install instapy”

The problem was with the Python3, thank you bro
