### ISSUE TITLE
cygrpc ImportError

### ISSUE THREAD

**Issue by ziqingc** [InstaPy/InstaPy#6445]
Hi,

I cloned the repository from https://github.com/InstaPy/instapy-quickstart.git and got error when running quickStart.py.
instapy-quickstart-master % python3 quickstart.py
Traceback (most recent call last):
  File "/Users/ziqing/Downloads/instapy-quickstart-master/quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/instapy.py", line 21, in <module>
    from .clarifai_util import check_image
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/clarifai/rest/__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/clarifai/rest/client.py", line 36, in <module>
    from clarifai.rest.grpc.proto.clarifai.api.endpoint_pb2_grpc import V2Stub
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/clarifai/rest/grpc/proto/clarifai/api/endpoint_pb2_grpc.py", line 2, in <module>
    import grpc
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/cygrpc.cpython-310-darwin.so' (no such file)

It said it is an incompatible architecture. I have a Mac with M1 chip.
Does anyone know how to fix it?

Cheers

**Comment by CodeMasterBond** [comment]
In your shell, type ``pip install instapy``

**Comment by elulcao** [comment]
> Hi,
> 
> I cloned the repository from https://github.com/InstaPy/instapy-quickstart.git and got error when running quickStart.py. instapy-quickstart-master % python3 quickstart.py Traceback (most recent call last): File "/Users/ziqing/Downloads/instapy-quickstart-master/quickstart.py", line 2, in from instapy import InstaPy File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/**init**.py", line 3, in from .instapy import InstaPy File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/instapy.py", line 21, in from .clarifai_util import check_image File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/clarifai_util.py", line 3, in from clarifai.rest import ClarifaiApp File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/clarifai/rest/**init**.py", line 3, in from clarifai.rest.client import ApiClient File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/clarifai/rest/client.py", line 36, in from clarifai.rest.grpc.proto.clarifai.api.endpoint_pb2_grpc import V2Stub File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/clarifai/rest/grpc/proto/clarifai/api/endpoint_pb2_grpc.py", line 2, in import grpc File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/**init**.py", line 22, in from grpc import _compression File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_compression.py", line 15, in from grpc._cython import cygrpc ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/cygrpc.cpython-310-darwin.so' (no such file)
> 
> It said it is an incompatible architecture. I have a Mac with M1 chip. Does anyone know how to fix it?
> 
> Cheers

Please check https://github.com/grpc/grpc/issues/25082

for details
