### ISSUE TITLE
Not able to run quickstart.py

### ISSUE THREAD

**Issue by classbproject** [InstaPy/InstaPy#6460]
I created a `quickstart.py` file and when I tried running it, it showed me the following error. InstaPy is installed on an Oracle VM with their ARM processors. 

```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
InstaPy Version: 0.6.15
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/ubuntu/InstaPy"
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    session = InstaPy(username='XXX', password='XXX', headless_browser=True)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/instapy/instapy.py", line 327, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/instapy/browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    self.service.start()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```
I had to install an older version of the [geckodriver](https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-arm7hf.tar.gz) meant for ARM processors and `/usr/local/bin/geckodriver` is indeed in `PATH`. I've obviously replaced my username and password with XXX. Stumped!

**Comment by elulcao** [comment]
This is not an InstaPy error but a pip dependency that is outdated, specifically for ARM arch. 
Did you try `pip install -U urllib3 requests`? for updating to a newer versions

**Comment by classbproject** [comment]
I just did and I still see the same error.

**Comment by elulcao** [comment]
> 

I reviewed the versions for urlib3, you are using the latest, 
then problem is about the PATH, `/usr/local/bin/geckodriver` doesn't exist based on logs provided. I suspect that WebDriver cannot found/download the geckodriver as per #6153, that package is little old and doesn't work for ARM archs. If this is the case download the geckodriver and explicitly define the location in the constructor session.

**Comment by classbproject** [comment]
> explicitly define the location in the constructor session

How do I do this? 

The latest `geckodriver` that works with ARM processors is 0.23 and that is what I installed.

**Comment by elulcao** [comment]
> geckodriver

Try this


https://github.com/InstaPy/InstaPy/blob/865b1309458b044b944a9b24a28c6c6300d8dee0/docs/additional-information.md#L511-L519

### Custom geckodriver
By default, InstaPy downloads the latest version of the geckodriver.
Unless you need a specific version of the geckodriver, you're ready to go.

You can manually download the geckodriver binary and put the path as an argument to the InstaPy constructor:

```python
session = InstaPy(..., geckodriver_path = '/path/to/binary', ...)
```

**Comment by classbproject** [comment]
Now it gives me this error:

`... PermissionError: [Errno 13] Permission denied: '/usr/local/bin'` and `... selenium.common.exceptions.WebDriverException: Message: 'bin' executable may have wrong permissions.`

This is what `geckodriver` permissions look like on my VM. 

`-rwxr-xr-x  1 root root 11222548 Jan 17 14:07 geckodriver`

**Comment by elulcao** [comment]
Check that `/usr/local/bin` is in the PATH
```bash
echo $PATH
```

if not add to the path, update this in your .bashrc or zshrc,
```bash
PATH=/usr/local/bin:$PATH
```

**Comment by classbproject** [comment]
It is in the `PATH` which is why this is so frustrating :(

**Comment by elulcao** [comment]
Can you share the output for listing the '/usr/local/bin/gecko*'?
and the `echo $PATH` output 

run both commands from user session that executes InstaPy

**Comment by classbproject** [comment]
> Can you share the output for listing the `ls -la /usr/local/bin/gecko*`?

```
-rwxr-xr-x 1 root root 11222548 Jan 17 14:07 /usr/local/bin/geckodriver
-rw-r--r-- 1 root root        0 Jan 19 04:39 /usr/local/bin/geckodriver.log
```

> and the `echo $PATH` output

`/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/bin/geckodriver`

**Comment by elulcao** [comment]
> > Can you share the output for listing the `ls -la /usr/local/bin/gecko*`?
> 
> ```
> -rwxr-xr-x 1 root root 11222548 Jan 17 14:07 /usr/local/bin/geckodriver
> -rw-r--r-- 1 root root        0 Jan 19 04:39 /usr/local/bin/geckodriver.log
> ```
> 
>  > and the `echo $PATH` output
> 
> `/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/bin/geckodriver`

`/usr/local/bin` is already in the PATH, you can remove `/usr/local/bin/geckodriver` from there. 
`/usr/local/bin/geckodriver.log` must not be there, this is file not a binary. Somehow previous executions saved the log there, like if wrong configuration. Now, Im interested about the session constructor and how did you defined the paths for FF and geckodriver.

**Comment by classbproject** [comment]
> Now, Im interested about the session constructor and how did you defined the paths for FF and geckodriver.

`session = InstaPy(username='XXX', password='XXX', headless_browser=True, geckodriver_path = '/usr/local/bin/geckodriver')`

Not sure what you mean by paths for FF.

**Comment by elulcao** [comment]
> > Now, Im interested about the session constructor and how did you defined the paths for FF and geckodriver.
> 
> `session = InstaPy(username='XXX', password='XXX', headless_browser=True, geckodriver_path = '/usr/local/bin/geckodriver')`
> 
> Not sure what you mean by paths for FF. I have not defined the path for Firefox explicitly in the session constructor. `which Firefox` shows me `/usr/bin/firefox`

Here in the Documentation
https://github.com/InstaPy/InstaPy/blob/cd189928a41a312777b46377a39e83f806915e5f/docs/instance-settings.md#L119

```python
session = InstaPy(username=insta_username,
                  password=insta_password,
                  browser_executable_path=r"D:\Program Files\Mozilla Firefox\firefox.exe")
```

**Comment by classbproject** [comment]
Still getting the `selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.` error. I'll try this on an Intel-powered VM. Is there a way to use `chromium` instead of `Firefox`?

**Comment by classbproject** [comment]
OK so I tried on a Ubuntu VM with an AMD processor and it works fine. I had to put `want_check_browser=False ` in the session constructor because of this [error](https://github.com/InstaPy/InstaPy/issues/6326#issuecomment-924386337). Also had some trouble with `urllib3` but I was able to fix that. I tried following the Raspberry Pi install guide for ARM processors but that did not work as well.
