### ISSUE TITLE
like_util.py line 618 problem

### ISSUE THREAD

**Issue by sergenkuzey** [InstaPy/InstaPy#6470]
I am using instapy-0.6.14

code:

from instapy import InstaPy

import random
from instapy import InstaPy
from instapy import smart_run

#login credentials
insta_username = '****'
insta_password = '****'

#login session
session = InstaPy(username=insta_username, password=insta_password)
session.login()

session.like_by_tags(["#carz"], amount=5)
getting below error

Traceback (most recent call last): File "E:\Study\Python_Automation\Insta_Commentor\quickstart.py", line 56, in session.like_by_tags(my_hashtags, amount=90, media=None) File "C:\Users\sonu3\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 1977, in like_by_tags inappropriate, user_name, is_video, reason, scope = check_link( File "C:\Users\sonu3\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\like_util.py", line 618, in check_link media = post_page[0]["shortcode_media"] KeyError: 0

I tried everything but I didn't solve this problem.

**Comment by fabianbeta** [comment]
same here

**Comment by ivan-ngchakming** [comment]
I think this error is caused by a change in from the Instagram web page.

Looks like the data obtained from `window.__additionalDataLoaded` in the html source (data stored in the `post_page` variable) is changed. 

Some information can be extracted using a slightly different way, 

```py
media = post_page["items"][0]
is_video = media["media_type"] == 2  # 1 for photos, 2 for videos
user_name = media["user"]["username"]
image_text = media["caption"]["text"]
```

but I can't seem to find comments in this data anymore.

**Comment by fabianbeta** [comment]
> I think this error is caused by a change in from the Instagram web page.
> 
> Looks like the data obtained from `window.__additionalDataLoaded` in the html source (data stored in the `post_page` variable) is changed.
> 
> Some information can be extracted using a slightly different way,
> 
> ```python
> media = post_page["items"][0]
> is_video = media["media_type"] == 2  # 1 for photos, 2 for videos
> user_name = media["user"]["username"]
> image_text = media["caption"]["text"]
> ```
> 
> but I can't seem to find comments in this data anymore.

Thanks Ian. I'll await an update for those with zero programming knowledge :)

**Comment by ivan-ngchakming** [comment]
Looks like there is already a PR working to fix this.
 #6467

**Comment by Schmaggi** [comment]
Same here

**Comment by hscanlan** [comment]
ditto

**Comment by ElBartu** [comment]
same here

**Comment by hscanlan** [comment]
Just a heads up, there is a pull request aval that fixes it. I just updated the 3 files and everything is fine again.

**Comment by astroramses** [comment]
> Just a heads up, there is a pull request aval that fixes it. I just updated the 3 files and everything is fine again.
> 
> #6467

I did change the 3 files, but still have unknown exception 0 when I try to use the function interact_by_users

**Comment by fabianbeta** [comment]
> > Just a heads up, there is a pull request aval that fixes it. I just updated the 3 files and everything is fine again.
> > #6467
> 
> I did change the 3 files, but still have unknown exception 0 when I try to use the function interact_by_users

I can confirm this.

**Comment by lovung** [comment]
@X0x1RG9f  I got this error after replacing
```bash
  File "/usr/local/lib/python3.9/site-packages/instapy/like_util.py", line 622, in check_link
    image_text = media["caption"]["text"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by X0x1RG9f** [comment]
Well, seems to means that the IG post has no text. Cannot try it as this is quite random but the modified code should fix it. Again, this is not official fix and just an ugly sticking plaster :) !

**Comment by impcretor** [comment]
> media = post_page['items'][0]
> is_video = media["is_unified_video"]
> user_name = media["user"]["username"]
> try : 
>     image_text = media["caption"]["text"]
> except Exception:
>     image_text = ""
> 
> owner_comments = None

It works for me! Thank you

**Comment by ErwinKoekoek** [comment]
ALL.
Just made a small fix that hopefully catches the last issues...
Look at this PR for more information. Please close this item if your problem is solved!
https://github.com/InstaPy/InstaPy/pull/6467

**Comment by fabianbeta** [comment]
> ALL. Just made a small fix that hopefully catches the last issues... Look at this PR for more information. Please close this item if your problem is solved! #6467

I just did a pip uninstall/install which I found to be easier. Working thank you - just struggling with the usuer_interact function where it's not liking those who I follow via instapy but I susepect that's my lack of experience? I am expecting the below to FOLLOW and then LIKE media of those followed (the "amount=2") defining the likes?) or does interact mean something else?

session.set_user_interact(amount=2,
                          percentage=70,
                          randomize=True,
                          media='Photo')

session.follow_likers(['user1' , 'user2'],
                      photos_grab_amount = 2,
                      follow_likers_per_photo = 3,
                      randomize=True,
                      sleep_delay=600,
                      interact=True)

**Comment by beeloved** [comment]
> ALL. Just made a small fix that hopefully catches the last issues... Look at this PR for more information. Please close this item if your problem is solved! #6467

Works for me.

**Comment by mrz8097** [comment]
This problem is due to the changes that Instagram has made in its source code.
Go to line "619" from the "like_util.py" file and change that part of the code to the code I gave you below (if you could not find this part of the code, the phrase media = post_page [0] ["shortcode_media "] Search the file" like_util.py ")

         media = post_page ['items'] [0]
         is_video = media ["is_unified_video"]
         user_name = media ["user"] ["username"]
         image_text = media ["caption"] ["text"]
         owner_comments = ""

> I am using instapy-0.6.14
> 
> code:
> 
> from instapy import InstaPy
> 
> import random from instapy import InstaPy from instapy import smart_run
> 
> #login credentials insta_username = '****' insta_password = '****'
> 
> #login session session = InstaPy(username=insta_username, password=insta_password) session.login()
> 
> session.like_by_tags(["#carz"], amount=5) getting below error
> 
> Traceback (most recent call last): File "E:\Study\Python_Automation\Insta_Commentor\quickstart.py", line 56, in session.like_by_tags(my_hashtags, amount=90, media=None) File "C:\Users\sonu3\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 1977, in like_by_tags inappropriate, user_name, is_video, reason, scope = check_link( File "C:\Users\sonu3\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\like_util.py", line 618, in check_link media = post_page[0]["shortcode_media"] KeyError: 0
> 
> I tried everything but I didn't solve this problem.
