### ISSUE TITLE
like_by_tags or like_by_feed dosen't work anymore

### ISSUE THREAD

**Issue by T1000MG** [InstaPy/InstaPy#6472]
Hi!
From one day to the next, the script no longer worked. No matter whether I used the method:
session.like_by_tags
or
session.like_by_feed 
the script logs in, opens the feed and then crashes with the error. I don't know if this is the correct error message. I am new to python. If you want me to look for the error message from another source, please feel free to let me know and I'll look there again.
To rule out an error or misconfiguration on my local machine, I installed python and instapy again on another machine, same problem there.
Windows 10
Python 3.10.0
I don't know how to get the Instapy version, but I have found it via 
py -m pip install instapy -U to update it

Traceback (most recent call last):
  File "D:\Instabot\instagram_bot.py", line 58, in <module>
    session.like_by_feed(amount=65, randomize=False, unfollow=False, interact=True)
  File "C:\Users\zunam\AppData\Roaming\Python\Python310\site-packages\instapy\instapy.py", line 4137, in like_by_feed
    for _ in self.like_by_feed_generator(amount, randomize, unfollow, interact):
  File "C:\Users\zunam\AppData\Roaming\Python\Python310\site-packages\instapy\instapy.py", line 4244, in like_by_feed_generator
    ) = check_link(
  File "C:\Users\zunam\AppData\Roaming\Python\Python310\site-packages\instapy\like_util.py", line 619, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

I take a look at other issues, but found no solution.

Thank you for your help
Best wishes from Germany

**Comment by Ticunas** [comment]
Please check #6467 
You can use solution from @ErwinKoekoek repository

**Comment by T1000MG** [comment]
> Please check #6467 You can use solution from @ErwinKoekoek repository

Hi, thanks for your answer.
I see that posting, but I don't know how to do this. I only use the instapy library with pip install instapy . Never build a project in python. My first steps are the phython script. I am a bit helpless right now

**Comment by ErwinKoekoek** [comment]
> > Please check #6467 You can use solution from @ErwinKoekoek repository
> 
> Hi, thanks for your answer. I see that posting, but I don't know how to do this. I only use the instapy library with pip install instapy . Never build a project in python. My first steps are the phython script. I am a bit helpless right now
Hi, 
Replace the files on your system with these updates ones 
Updates files:  comment_util.py, like_util.py, util.py.  

New files are on this repo:
https://github.com/ErwinKoekoek/InstaPy/tree/master/instapy

Best Erwin

**Comment by T1000MG** [comment]
> > > Please check #6467 You can use solution from @ErwinKoekoek repository
> > 
> > 
> > Hi, thanks for your answer. I see that posting, but I don't know how to do this. I only use the instapy library with pip install instapy . Never build a project in python. My first steps are the phython script. I am a bit helpless right now
> > Hi,
> > Replace the files on your system with these updates ones
> > Updates files:  comment_util.py, like_util.py, util.py.
> 
> New files are on this repo: https://github.com/ErwinKoekoek/InstaPy/tree/master/instapy
> 
> Best Erwin

Thank you Erwin, but I don't know how to build it and replace my old istapy libary. Im totaly new in this game. I only write c# web applications

**Comment by Ticunas** [comment]
> > Please check #6467 You can use solution from @ErwinKoekoek repository
> 
> Hi, thanks for your answer. I see that posting, but I don't know how to do this. I only use the instapy library with pip install instapy . Never build a project in python. My first steps are the phython script. I am a bit helpless right now

you can use
pip install git+https://github.com/ErwinKoekoek/InstaPy.git

**Comment by ErwinKoekoek** [comment]
ALL.
Just made a small fix that hopefully catches the last issues...
Look at this PR for more information. Please close this item if your problem is solved!
https://github.com/InstaPy/InstaPy/pull/6467

**Comment by T1000MG** [comment]
Befor your answers I make following steps that works.
First uninstall instapy
then 
pip install git+https://github.com/ErwinKoekoek/InstaPy.git@master



> ALL. Just made a small fix that hopefully catches the last issues... Look at this PR for more information. Please close this item if your problem is solved! #6467

Can I update my instapy or dit i uninstall it first, like I do the last time? Is it possible to update it?

**Comment by 2firstnames** [comment]
> This problem is due to the changes that Instagram has made in its source code. Go to line "619" from the "like_util.py" file and change that part of the code to the code I gave you below (if you could not find this part of the code, the phrase < media = post_page [0] ["shortcode_media "] > Search the file" like_util.py ")
> 
> ```
>      media = post_page ['items'] [0]
>      is_video = media ["is_unified_video"]
>      user_name = media ["user"] ["username"]
>      image_text = media ["caption"] ["text"]
>      owner_comments = ""
> ```
> 
> > Hi! From one day to the next, the script no longer worked. No matter whether I used the method: session.like_by_tags or session.like_by_feed the script logs in, opens the feed and then crashes with the error. I don't know if this is the correct error message. I am new to python. If you want me to look for the error message from another source, please feel free to let me know and I'll look there again. To rule out an error or misconfiguration on my local machine, I installed python and instapy again on another machine, same problem there. Windows 10 Python 3.10.0 I don't know how to get the Instapy version, but I have found it via py -m pip install instapy -U to update it
> > Traceback (most recent call last): File "D:\Instabot\instagram_bot.py", line 58, in session.like_by_feed(amount=65, randomize=False, unfollow=False, interact=True) File "C:\Users\zunam\AppData\Roaming\Python\Python310\site-packages\instapy\instapy.py", line 4137, in like_by_feed for _ in self.like_by_feed_generator(amount, randomize, unfollow, interact): File "C:\Users\zunam\AppData\Roaming\Python\Python310\site-packages\instapy\instapy.py", line 4244, in like_by_feed_generator ) = check_link( File "C:\Users\zunam\AppData\Roaming\Python\Python310\site-packages\instapy\like_util.py", line 619, in check_link media = post_page[0]["shortcode_media"] KeyError: 0
> > I take a look at other issues, but found no solution.
> > Thank you for your help Best wishes from Germany
> 
> This problem is due to the changes that Instagram has made in its source code. Go to line "619" from the "like_util.py" file and change that part of the code to the code I gave you below (if you could not find this part of the code, the phrase media = post_page [0] ["shortcode_media "] Search the file" like_util.py ")
> 
> ```
>      media = post_page ['items'] [0]
>      is_video = media ["is_unified_video"]
>      user_name = media ["user"] ["username"]
>      image_text = media ["caption"] ["text"]
>      owner_comments = ""
> ```

Thank you, I was having the same problem and you're code snippet fixed it.
