### ISSUE TITLE
Error when liking posts : media = post_page[0]["shortcode_media"] KeyError: 0

### ISSUE THREAD

**Issue by OnHai** [InstaPy/InstaPy#6480]
## Expected Behavior
simple quickstart.py file

## Current Behavior
```
Traceback (most recent call last):
  File "quickstart.py", line 31, in <module>
    session.like_by_tags(["natgeo"], amount=10)
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 1980, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "/usr/local/lib/python3.8/dist-packages/instapy/like_util.py", line 619, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0
```
## InstaPy configuration
Version 0.6.16
All deufaults

**Comment by eXtraMt** [comment]
same here

**Comment by beeloved** [comment]
See https://github.com/InstaPy/InstaPy/pull/6467

**Comment by Adrianahwjsgsj** [comment]
#6467 solved for me

**Comment by mikestan** [comment]
NICE WORK! Running headless Ubuntu 21.10 on RPi 3B (version 1.2). Upgraded to InstaPy 0.6.16 from .15 and then applied your copy/paste fix - bow we're back in business! 🍺😷👍
