### ISSUE TITLE
InstaPy dies after about 10 minutes

### ISSUE THREAD

**Issue by mikestan** [InstaPy/InstaPy#6482]
## Expected Behavior
Continues to complete liking/commenting per config

## Current Behavior
Get the following error after about 10 minutes:

Traceback (most recent call last):
  File "/home/ubuntu/quickstart.py", line 60, in <module>
    session.like_by_tags(my_hashtags, amount=92, media=None, interact=True)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/instapy/instapy.py", line 2009, in like_by_tags
    like_state, msg = like_image(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/instapy/like_util.py", line 799, in like_image
    if not verify_liked_image(browser, logger):
  File "/home/ubuntu/.local/lib/python3.9/site-packages/instapy/like_util.py", line 825, in verify_liked_image
    browser.refresh()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1061, in refresh
    self.execute(Command.REFRESH)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: TimedPromise timed out after 300000 ms
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
TimeoutError@chrome://remote/content/shared/webdriver/Errors.jsm:472:5
bail@chrome://remote/content/marionette/sync.js:231:19

## Possible Solution (optional)
Seems recent "patch" I applied to fix #6467 issues either does not work for all cases -OR- still needs help...

## InstaPy configuration
Running InstaPy 0.6.16 with bug fix #6467 fix - headless Ubuntu 21.10 on RPi 3B (version 1.2). Here's the config file:

# !/usr/bin/python3
import random
from instapy import InstaPy
from instapy import smart_run

# get a session!
session = InstaPy(username='username', password='password', headless_browser=True)

# let's go! :>
with smart_run(session):
    hashtags = ['jigsawpuzzle', 'puzzle', 'puzzles', 'jigsaw', 'puzzlelover', 'puzzletime', 'puzzleaddict', 'pieces', 'jigsawpuzzles', 'puzzlesofinstagram', 'puzzler', 'ilovepuzzles', 'puzzlegram', 'puzzlemania', 'piecepuzzle', 'puzzlepieces', 'puzzling', 'jigsaws', 'puzzlelove', 'instapuzzle', 'jigsawpuzzlesofinstagram', 'rompecabezas', 'puzzled', 'jigsawpuzzleaddict', 'jualpuzzle', 'puzzlefun', 'ravensburger', 'puzzlenerd', 'puzzlelife', 'bhfyp', 'puzzlefeed', 'puzzleart', 'puzzlepiece', 'jigsawpuzzlelover', 'fun', 'art', 'hobby', 'puzzlepic', 'puzzleindonesia', 'jualpuzzleimport', 'jualpuzzledisney', 'mainpuzzle', 'puzzleimport', 'tokopuzzle', 'puzzleshop', 'stayhome', 'a', 'jualanpuzzle', 'kolektorpuzzle', 'disney', 'jualpuzzletenyo', 'woodenpuzzle', 'gift', 'jualpuzzlejepang', 'jigzle', 'puzzel', 'games', 'quebracabe', 'pintoo', 'puzzleprogress']

    random.shuffle(hashtags)
    my_hashtags = hashtags[:10]

    # general settings
    session.set_dont_like(['sad', 'rain', 'depression', 'followback', 'followforfollow', 'likeforlike', 'likeforlikes', 'likeforfollow'])
    session.set_do_follow(enabled=True, percentage=10, times=2)
    session.set_do_comment(enabled=True, percentage=20)
    session.set_comments([
                             u'Nice work! :heart_eyes: ',
                             u'Wonderful!! :heart_eyes:',
                             u'This is awesome!! :heart_eyes:',
                             u'Nice!! :wink:',
                             u'Cool!. Ever try our '
                             u'Puzzles? :wink:',
                             u'Way cool!! :smiley:',
                             u'Wow!! :smiley: :thumbsup: What do '
                             u'you think of our puzzles?'],
                         media='Photo')
    session.set_do_like(True, percentage=60)
    session.set_delimit_liking(enabled=True, max_likes=920, min_likes=0)
    session.set_delimit_commenting(enabled=False, max_comments=30, min_comments=0)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=30000000,
                                    max_following=2000000,
                                    min_followers=20,
                                    min_following=5)

    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "follows"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes_hourly=200,
                                 peak_likes_daily=585,
                                 peak_comments_hourly=80,
                                 peak_comments_daily=182,
                                 peak_follows_hourly=48,
                                 peak_follows_daily=None,
                                 peak_unfollows_hourly=35,
                                 peak_unfollows_daily=402,
                                 peak_server_calls_hourly=None,
                                 peak_server_calls_daily=4700)

    session.set_user_interact(amount=10, randomize=True, percentage=80)

    # activity
    session.like_by_tags(my_hashtags, amount=92, media=None, interact=True)
    session.unfollow_users(amount=500, instapy_followed_enabled=True, instapy_followed_param="nonfollowers",
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=501)
    session.unfollow_users(amount=500, instapy_followed_enabled=True, instapy_followed_param="all",
                           style="FIFO", unfollow_after=24 * 60 * 60,
                           sleep_delay=501)

    """ Joining Engagement Pods...
    """
    session.join_pods(topic='sports', engagement_mode='no_comments')

**Comment by TheNighthawk99** [comment]
Same here.
When I use the `like_by_tag` or `like_by_feed`, the script crashes after some time.

**Comment by TheNighthawk99** [comment]
Hello, for troubleshooting, this is the message I get:

```
Traceback (most recent call last):
  File "quickstart.py", line 24, in <module>
    session.like_by_tags(["tag1", "tag2", "tag3"], amount=12)
  File "/home/username/git/InstaPy-erwin/instapy/instapy.py", line 2009, in like_by_tags
    like_state, msg = like_image(
  File "/home/username/git/InstaPy-erwin/instapy/like_util.py", line 814, in like_image
    if not verify_liked_image(browser, logger):
  File "/home/username/git/InstaPy-erwin/instapy/like_util.py", line 840, in verify_liked_image
    browser.refresh()
  File "/home/username/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1061, in refresh
    self.execute(Command.REFRESH)
  File "/home/username/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/username/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: TimedPromise timed out after 300000 ms
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
TimeoutError@chrome://remote/content/shared/webdriver/Errors.jsm:472:5
bail@chrome://remote/content/marionette/sync.js:231:19
```

Script was run with `headless_browser=True`.
