### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by alexpzpz** [InstaPy/InstaPy#6483]
hello, who faced such a problem
do not reach the end of the action, then performs 10%, then 75%. 

**code:**
```
session.set_do_like(enabled=True, 
                        percentage=100)
session.interact_user_likers(usernames=["user"],
                             posts_grab_amount=1,
                             interact_likers_per_post=550,
                             randomize=True)  
```

**log:**
```
Traceback (most recent call last):
  File "C:\Users\Серв\Desktop\Bot\like_unf_cat.py", line 70, in <module>
    session.interact_user_likers(usernames=["oriental_sema_cat"],
  File "C:\Users\Серв\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 3390, in interact_user_likers
    validation, details = self.validate_user_call(person)
  File "C:\Users\Серв\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 1353, in validate_user_call
    validation, details = validate_username(
  File "C:\Users\Серв\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\util.py", line 322, in validate_username
    number_of_posts = getUserData(
  File "C:\Users\Серв\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\util.py", line 482, in getUserData
    get_key = shared_data.get("entry_data").get("ProfilePage")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by camillevingere** [comment]
Hello, I am facing the same problem 👎 Anyone has a fix ?
