### ISSUE TITLE
Not working on Windows anymore

### ISSUE THREAD

**Issue by Ordovicium** [InstaPy/InstaPy#6490]
## Current Behavior
The fix from here https://github.com/InstaPy/InstaPy/pull/6467 starts running as expected with Ubuntu but I have instapy also running for specific tasks on Windows. On Windows I get still the same coding errors as before the fix.

Traceback (most recent call last):
  File ".\instagram.py", line 66, in <module>
    session.like_by_tags(my_hashtags, amount=90, media=None)
  File "C:\............\InstaBot\instapy\instapy.py", line 1980, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\............\InstaBot\instapy\like_util.py", line 619, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

**Comment by Ordovicium** [comment]
@mrz8097 no didn't work.

Got now

Traceback (most recent call last):
  File ".\instagram.py", line 66, in <module>
    session.like_by_tags(my_hashtags, amount=90, media=None)
  File "C:\.....\AppData\Roaming\Python\Python38\site-packages\instapy\instapy.py", line 1994, in like_by_tags
    self.liking_approved = verify_liking(
  File "C:\.....\AppData\Roaming\Python\Python38\site-packages\instapy\like_util.py", line 912, in verify_liking
    likes_count = post_page["graphql"]["shortcode_media"]["edge_media_preview_like"][
KeyError: 'graphql'
