### ISSUE TITLE
Raspberry 4B geckodriver unexpectedly exited. Status code was: 1

### ISSUE THREAD

**Issue by elouanbarbier** [InstaPy/InstaPy#6491]
## Expected Behavior

Start instapy

## Current Behavior

Hello, when i start quickstart.py i have this issues : 

selenium.common.exceptions.WebDriverException: Message: Service /home/pi/.local/bin/geckodriver unexpectedly exited. Status code was: 1

I don't know if it's because I'm using an Raspberry ...

Thanks 
## InstaPy configuration

I use RaspberryPi 4B. 
VERSION -> debian 10 (buster)

**Comment by erwinbierens** [comment]
i'm facing the same problem, already tried to install different version but with no success.

**Comment by oc8** [comment]
Same for me:
```
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/kali/InstaPy"
Traceback (most recent call last):
  File "/home/kali/Documents/main.py", line 10, in <module>
    session = InstaPy(
  File "/home/kali/.local/lib/python3.9/site-packages/instapy/instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/home/kali/.local/lib/python3.9/site-packages/instapy/browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/home/kali/.local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    self.service.start()
  File "/home/kali/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/kali/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/bin/geckodriver unexpectedly exited. Status code was: 1
```

**Comment by LPhil** [comment]
Is there a last know working configuration?

**Comment by gk6294** [comment]
https://stackoverflow.com/questions/64278632/python-selenium-geckodriver-executable-needs-to-be-in-path-how-to-install-on

This might help, download the arm64 geckodriver binary from https://launchpad.net/ubuntu/bionic/arm64/firefox-geckodriver/ and move it to the corresponding path folder, 

P.s. I got my RPI4 running geckodriver fine.

**Comment by Wolkex3** [comment]
Hi, I have the same issue. 

@oc8 I have installed FF 91.6.0esr (32-bit). Is this the correct version? If not, how can I install a specefic FF version? I already tried to download another version, but I dont know how.

@gk6294 I tried to find a executable geckodriver ont he link you posted. But I didnt find anything. Im new to the raspberry pi. Hope you can help me here? :)

Thanks a lot guys!

```
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "/home/pi/quickstart.py", line 12, in <module>
    session = InstaPy(username=insta_username,
  File "/home/pi/.local/lib/python3.9/site-packages/instapy/instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/home/pi/.local/lib/python3.9/site-packages/instapy/browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/bin/geckodriver unexpectedly exited. Status code was: 1

```

@oc8

**Comment by Wolkex3** [comment]
Geckodriver version:

```
pi@raspberrypi:~ $ geckodriver --version
geckodriver 0.23.0 ( 2018-10-04)

The source code of this program is available from
testing/geckodriver in https://hg.mozilla.org/mozilla-central.

This program is subject to the terms of the Mozilla Public License 2.0.
You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
```

**Comment by patrickschmelter** [comment]
I got the same problem, did anyone manage to find a solution?
