### ISSUE TITLE
No interact

### ISSUE THREAD

**Issue by alexpzpz** [InstaPy/InstaPy#6497]
Doesn't interact with users 

**Code:**
```
session.set_do_like(enabled=True, 
                        percentage=100)
    
    session.set_user_interact(amount=1, 
                                randomize=False, 
                                percentage=100)

    session.interact_user_likers(usernames=["_tomato_333_"],
                             posts_grab_amount=1,
                             interact_likers_per_post=20,
                             randomize=True)  
```

**Log:**
```
Traceback (most recent call last):
  File "C:\Users\Серв\Desktop\Bot\inst_like.py", line 32, in <module>
    session.interact_user_likers(usernames=["user"],
  File "C:\Users\Серв\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 3332, in interact_user_likers
    post_urls = get_photo_urls_from_profile(
  File "C:\Users\Серв\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\commenters_util.py", line 449, in get_photo_urls_from_profile
    photos_a_elems = browser.find_elements(
  File "C:\Users\Серв\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1279, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\Серв\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Серв\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: Cyclic object value
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
JavaScriptError@chrome://remote/content/shared/webdriver/Errors.jsm:362:5
evaluate.assertAcyclic@chrome://remote/content/marionette/evaluate.js:52:11
evaluate.toJSON@chrome://remote/content/marionette/evaluate.js:323:14
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:177:31
```

**Comment by Sergej99** [comment]
https://github.com/InstaPy/InstaPy/issues/6496 

Help me please

**Comment by ashardaniyal12** [comment]
Same Issue did you resolved it?
