### ISSUE TITLE
Status code was 1

### ISSUE THREAD

**Issue by oc8** [InstaPy/InstaPy#6500]
## Expected Behavior
Start InstaPy

## Current Behavior
Hello, 
When I start quickstart.py I have this issue:
```
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/kali/InstaPy"
Traceback (most recent call last):
  File "/home/kali/Documents/main.py", line 10, in <module>
    session = InstaPy(
  File "/home/kali/.local/lib/python3.9/site-packages/instapy/instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/home/kali/.local/lib/python3.9/site-packages/instapy/browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/home/kali/.local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    self.service.start()
  File "/home/kali/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/kali/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/bin/geckodriver unexpectedly exited. Status code was: 1
```
I tried these two ways of installation:
https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md
https://github.com/funkypenguin/InstaPy/blob/master/docs/How_to_Raspberry.md

Thanks for your help !

## InstaPy configuration
I use RaspberryPi 4B and all required pip packages are installed.
I tried with raspios and kali linux. 
I tried with geckodriver-v0.18.0-arm7hf and geckodriver-v0.23.0-arm7hf

**Comment by CodeMasterBond** [comment]
Do you have Firefox-esr installed? Also make sure the gecko driver is downgraded.

**Comment by Wolkex3** [comment]
I have the same problem. @oc8 do you solved this issue?

**Comment by oc8** [comment]
> I have the same problem. @oc8 do you solved this issue?

No, I still haven't found a solution ;(

**Comment by Wolkex3** [comment]
@oc8 I started a question in https://stackoverflow.com/questions/71252255/assert-process-still-running-and-webdriverexception-message-service-geckodri/

There is already one answer. Maybe we will solve it there together? :)

**Comment by Wolkex3** [comment]
I have now completly reinstalled raspbian and having the same issue. 
I cannot even start geckodriver. Does someone have a hint for me?

```
pi@raspberrypi:~ $ python3
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> browser = webdriver.Firefox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 173, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 1
```

**Comment by Wolkex3** [comment]
@oc8, have a look at this post. I think we need to switch to Ubunto on RPI. 
https://github.com/InstaPy/InstaPy/issues/6521#issuecomment-1053699644

**Comment by oc8** [comment]
> @oc8, have a look at this post. I think we need to switch to Ubunto on RPI. [#6521 (comment)](https://github.com/InstaPy/InstaPy/issues/6521#issuecomment-1053699644)

Great! I'm going to try this weekend. 
Let me know if it worked for you!

**Comment by Wolkex3** [comment]
> > @oc8, have a look at this post. I think we need to switch to Ubunto on RPI. [#6521 (comment)](https://github.com/InstaPy/InstaPy/issues/6521#issuecomment-1053699644)
> 
> 
> 
> Great! I'm going to try this weekend. 
> 
> Let me know if it worked for you!

Hi @oc8 fid it worked for you? I have the following issue: https://github.com/InstaPy/InstaPy/issues/6521#issuecomment-1062158851
