### ISSUE TITLE
Timeout after cookies - No Login

### ISSUE THREAD

**Issue by paoloallegretti** [InstaPy/InstaPy#6529]
Hello! I was having trouble with "cookies" and I figured out (with the help of a user) that the last line of `xpath_compile.py` needed to be updated in `xpath["accept_igcookie_dialogue"] = {
    "accept_button": "//button[text()='Accept All']"}` and it seems legit because IG changed the button in "Accept All".

BUT

now I'm stucked here

```
C:\Users\ \Desktop\instabot>py instabot.py
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/ /InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-03-02 01:43:45] [ ]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2022-03-02 01:43:45] [ ]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2022-03-02 01:43:45] [ ]  - Internet Connection Status: ok
INFO [2022-03-02 01:43:45] [ ]  - Current IP is " " and it's from " "
INFO [2022-03-02 01:43:45] [ ]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2022-03-02 01:43:45] [ ]  - window.navigator.webdriver response: True
WARNING [2022-03-02 01:43:45] [ ]  - Hide Selenium Extension: error
INFO [2022-03-02 01:43:49] [ ]  - Cookie file not found, creating cookie...
INFO [2022-03-02 01:43:49] [ ]  - Accepted IG cookies by default...
INFO [2022-03-02 01:44:29] [ ]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
C:\Users\ \AppData\Local\Temp\20220302-014434.html
**********************************************************************

INFO [2022-03-02 01:44:34] [ ]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 58.41 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-03-02 01:44:34] [ ]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "C:\Users\ \Desktop\instabot\instabot.py", line 16, in <module>
    with smart_run(session):
  File "C:\Users\ \AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 137, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield
```

this:
`INFO [2022-03-02 01:44:29] [ ]  Timed out with failure while explicitly waiting until visibility of element located!`

What element visibility he's looking for, since the accept cookie button was already checked?
`INFO [2022-03-02 01:43:49] [ ]  - Accepted IG cookies by default...`

Any solutions?
Thanks!

**Comment by RainbowTob** [comment]
Check this:

https://github.com/InstaPy/InstaPy/issues/6384#issuecomment-955745336

**Comment by paolinooh** [comment]
> Check this:
> 
> [#6384 (comment)](https://github.com/InstaPy/InstaPy/issues/6384#issuecomment-955745336)

Thank you, I've tried a few and now it's working, but I now have other bugs lol
