### ISSUE TITLE
Bot not working on any computer - why?

### ISSUE THREAD

**Issue by Rapid1898-code** [InstaPy/InstaPy#6532]
Hello - i have the following script which works fine on the one win10 client - but fails on another win10 client -

```
import os
from instapy import InstaPy
   session = InstaPy(username=INSTA_USER, 
                    password=INSTA_PW,
                    headless_browser= True)
  session.login()
  session.set_comments(listComments)
  session.like_by_tags(listTags, amount=likeCount)
  session.set_dont_like(listNotTags)
  session.set_do_follow(True, percentage=100)
  session.set_do_comment(True, percentage=100)  
  session.end()
```

On the one client it runs trough without problems and on the second one i get this error - directly at the login i would say

```
$ python instaBot.py
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/WRSPOL/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-03-02 20:56:30] [aunikat_wien]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2022-03-02 20:56:30] [aunikat_wien]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2022-03-02 20:56:30] [aunikat_wien]  - Internet Connection Status: ok
INFO [2022-03-02 20:56:30] [aunikat_wien]  - Current IP is "185.17.14.8" and it's from "Austria/AT"
INFO [2022-03-02 20:56:30] [aunikat_wien]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2022-03-02 20:56:31] [aunikat_wien]  - window.navigator.webdriver response: True
WARNING [2022-03-02 20:56:31] [aunikat_wien]  - Hide Selenium Extension: error
INFO [2022-03-02 20:56:34] [aunikat_wien]  - Cookie file not found, creating cookie...
INFO [2022-03-02 20:57:18] [aunikat_wien]  Timed out with failure while explicitly waiting until visibility of element located!

Traceback (most recent call last):
  File "C:\DEV\Fiverr\TRY\littlescreamer\instaBot.py", line 50, in <module>
  File "C:\DEV\.venv\instapy\lib\site-packages\instapy\login_util.py", line 385, in login_user   
    input_username = browser.find_element(By.XPATH, input_username_XP)
  File "C:\DEV\.venv\instapy\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1248, in find_element
    return self.execute(Command.FIND_ELEMENT, {
 in execute                                                                                      , in find_element    
    self.error_handler.check_response(response)
  File "C:\DEV\.venv\instapy\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 2 in execute47, in check_response
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //input[@na47, in check_responseme='username']
Stacktrace:
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5                     me='username']       
element.find/</<@chrome://remote/content/marionette/element.js:305:16
```

What could be the reason for this?
Must there be anything special installed (chrome, firefox, etc.)?

**Comment by Ilnur786** [comment]
firefox of course must be installed. Also can be needed geckodriver (if it firefox). For example, on Windows you should download geckodriver.exe and add path to PATH environ variables

**Comment by Rapid1898-code** [comment]
ok is see - so Chrome is not sufficient - so Firefox is mandatory?
And i also have to manual download the geckodriver and include the exe in PATH?
(there is no automatic way to do this - like webdriver_manager for chrome?

**Comment by Ilnur786** [comment]
Add firefox.exe at PATH variables wasn't need. Where from you get login and password?

**Comment by Rapid1898-code** [comment]
The login and password i read from an excel-sheet(
(this is the same on both clients - i also checked on the problematic client if the information is read from the excel and this works fine)

**Comment by Ilnur786** [comment]
https://stackoverflow.com/questions/57561286/selenium-common-exceptions-nosuchelementexception-message-unable-to-locate-ele

**Comment by Rapid1898-code** [comment]
ok thanks - i see - but what can i do now
Is there any setting in instaPy related to this?

**Comment by Remi13Git** [comment]
I had this issue first time I used instapy, it solving by accepting cookies by myself when the bot is working. Next times he accept cookies itself

**Comment by fasalco1** [comment]
im still facing this issue
