### ISSUE TITLE
cannot comment like_util Error on Line 619

### ISSUE THREAD

**Issue by shoushouleb** [InstaPy/InstaPy#6535]
## Expected Behavior
I am trying to comment on one user post, but the InstaPY is throwing an error as in the image below.
## Current Behavior
![Capture](https://user-images.githubusercontent.com/13929075/156789350-da84b9d7-fe84-4427-af86-784cc8cacb3b.PNG)

## InstaPy configuration
I am using the default configuration and below is my code.

from instapy import InstaPy
f = open("accounts.txt")
comments = open("comments.txt")
for x in f:
  print(x.strip())
  session = InstaPy(username=x.strip(),password="passwor",headless_browser=True)
  session.login()
  #Commenting
  session.interact_by_users(["username"], amount=4, randomize=True, media='Photo')
  session.set_do_comment(True, percentage=100)
  session.set_comments(comments)
  session.end()
  
f.close()

**Comment by vsevolod-mineev** [comment]
I have the same problem in the context of: `session.like_by_tags(my_hashtags, amount=90)`

Something needs to change on line 619 for session.like_by_tags to work.

**Comment by Jordybesselaar** [comment]
Same problem: 

Traceback (most recent call last):
  File "C:\Users\User\bot732022.py", line 32, in <module>
    session.like_by_tags(["tag"], amount=10)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 1980, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\like_util.py", line 619, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

**Comment by erwinowak** [comment]
Same problem 😢

**Comment by micahdc5** [comment]
Same problem
