### ISSUE TITLE
No module named instapy But insapy installed on mac 

### ISSUE THREAD

**Issue by fudojahic** [InstaPy/InstaPy#6544]
Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
ImportError: No module named instapy

**Comment by fudojahic** [comment]
> 

I did and this is the outcome:

Name: instapy
Version: 0.6.16
Summary: Tool for automated Instagram interactions
Home-page: https://github.com/timgrossmann/InstaPy
Author: Tim Großmann
Author-email: contact.timgrossmann@gmail.com
License: GPLv3
Location: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Requires: api-display-purposes, certifi, chardet, clarifai, configparser, EasyProcess, emoji, future, grpcio, idna, jsonschema, MeaningCloud-python, plyer, protobuf, python-telegram-bot, PyVirtualDisplay, PyYAML, regex, requests, selenium, setuptools-rust, six, urllib3, webdriverdownloader
Required-by: 

Im a missing something?

**Comment by Skin1980** [comment]
Try

> python --version

**Comment by Skin1980** [comment]
Then maybe you have 2 versions of python installed….

try to run your script with:

python3 yourfilename

**Comment by fudojahic** [comment]
> Then maybe you have 2 versions of python installed….
> 
> try to run your script with:
> 
> python3 yourfilename

I think i do have 2. how would I run the script with python3

**Comment by Skin1980** [comment]
Just write python3 instead of python

**Comment by Skin1980** [comment]
> > Then maybe you have 2 versions of python installed….
> > try to run your script with:
> > python3 yourfilename
> 
> I think i do have 2. how would I run the script with python3

Solved?

**Comment by fudojahic** [comment]
> > > Then maybe you have 2 versions of python installed….
> > > try to run your script with:
> > > python3 yourfilename
> > 
> > 
> > I think i do have 2. how would I run the script with python3
> 
> Solved?

No sorry! i just dont understand why is not functioning. Hm

**Comment by fudojahic** [comment]
session = InstaPy(username=insta_username,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 181, in __init__
    RemoteWebDriver.__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by fudojahic** [comment]
> > > Then maybe you have 2 versions of python installed….
> > > try to run your script with:
> > > python3 yourfilename
> > 
> > 
> > I think i do have 2. how would I run the script with python3
> 
> Solved?

Got it all figure it out! loggs into the account finds a tag, finds a photo but when it try's to like it I get this error out 

On session start was FOLLOWING 881 users & had 1547 FOLLOWERS
[Session lasted 1.12 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-03-11 08:08:30] [myusername]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "/Users/username/Desktop/instapy-quickstart-master/quickstart.py", line 32, in <module>
    session.like_by_tags(["natgeo"], amount=5)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/instapy.py", line 1980, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/like_util.py", line 619, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0


Any thoughts
