### ISSUE TITLE
Geckodriver / Firefox ESR issue @Ubuntu

### ISSUE THREAD

**Issue by Wolkex3** [InstaPy/InstaPy#6552]
Hi, 
I have installed Ubuntu on my RPi4. I was able to get instapy working but with an hide selenium error. So I assumed that the installed Firefox version is not correct. 

So I tried to install firefox-esr and now I m getting the following error message. Geckodriver is in /usr/local/bin. /usr/local/bin is in path as well. Did I made something wrong installing Firefox-esr? I installed the following version: 91.7.0esr (64-bit)

How to install an older esr version correctly?

Hope you can help me!

```
o@o-desktop:~/Schreibtisch/instapy-quickstart-master$ python3 quickstart.py
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/o/InstaPy"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/o/Schreibtisch/instapy-quickstart-master/quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "/usr/local/lib/python3.9/dist-packages/instapy/instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/usr/local/lib/python3.9/dist-packages/instapy/browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/firefox/webdriver.py", line 176, in __init__
    self.service.start()
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
```

**Comment by oc8** [comment]
Oh no, another new problem
We can't get instapy to work on rpi, can anyone who has succeeded help us?
Thanks in advance!
