### ISSUE TITLE
ERROR  - unknown error: Cannot read property 'entry_data' of undefined

### ISSUE THREAD

**Issue by datteba** [InstaPy/InstaPy#657]
Traceback (most recent call last):
  File "D:\Users\user\InstaPy-master\quickstart.py", line 83, in <module>
    .like_by_feed(amount=rnd_1, randomize=True) \
  File "D:\Users\user\InstaPy-master\instapy\instapy.py", line 1030, in like_by_feed
    self.like_by_followers_lower_limit)
  File "D:\Users\user\InstaPy-master\instapy\like_util.py", line 387, in check_link
    "return window._sharedData.entry_data.ProfilePage[0].user.followed_by.count")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 487, in execute_script
    'args': converted_args})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: chrome=60.0.3112.101)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 10.0.15063 x86_64)

**Comment by diveu** [comment]
I faced this problem and it was the sign that liking was limited for an account. Did you check the liking ability on your phone?
