### ISSUE TITLE
Hide Selenium Extension: error

### ISSUE THREAD

**Issue by giladstov** [InstaPy/InstaPy#6573]
I Ubuntu 20.04 (LTS) x64
With firefox 98.0.2 64bit
geckodriver-v0.30.0-linux64

I get warning Hide Selenium Extension: **error**

NFO [2022-04-02 01:31:32] [xxxxx]  Session started!
INFO [2022-04-02 01:31:45] [xxxxx]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2022-04-02 01:31:46] [xxxxx]  - Internet Connection Status: ok
INFO [2022-04-02 01:31:46] [xxxxx]  - Current IP is "2a00:c281:12cb:f500:7d94:99fc:e46a:c52d" and it's from "Germany/DE"
INFO [2022-04-02 01:31:46] [xxxxx]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2022-04-02 01:31:46] [xxxxx]  - window.navigator.webdriver response: True
WARNING [2022-04-02 01:31:46] [xxxxx]  - Hide Selenium Extension: error

I've seen Ubuntu server // Hide Selenium Extension: error #6452 which was closed but I can't get any help from there
I've searched about the issue maybe it has to do with the newer versions of firefox

I manage to login but doesn't it mean that automation is **not hidden**??

**Comment by rob3210** [comment]
i am showing this same error message. the script then crashes 

Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    session.like_by_tags(['sunset'], amount=100)
  File "C:\Users\xxxx\Documents\Coding\InstaPy-master\instapy\instapy.py", line 1990, in like_by_tags
    self.logger,
  File "C:\Users\xxxx\Documents\Coding\InstaPy-master\instapy\like_util.py", line 619, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0
