### ISSUE TITLE
error Instapy

### ISSUE THREAD

**Issue by okih1** [InstaPy/InstaPy#6578]
Can you help me pls for this error

'auto_load_more_enabled': False}
Traceback (most recent call last):
  File "C:\Users\Pss\Desktop\insta.py", line 12, in <module>
    session.like_by_tags(['music', 'mp3love'], amount=5)
  File "C:\Users\Pss\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 1980, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\Pss\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\like_util.py", line 619, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

**Comment by rob3210** [comment]
having same issue.
