### ISSUE TITLE
BadZipFile Error

### ISSUE THREAD

**Issue by sebsi1** [InstaPy/InstaPy#6580]
I get this error while logging in my account: 

InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/sebsi/InstaPy"
Traceback (most recent call last):
  File "\\HOMECLOUD\Leo\Documents\PyCharmProjects\Instagrambot\main.py", line 10, in <module>
    session = InstaPy(username=username, password=password, headless_browser=False)
  File "C:\Users\sebsi\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\sebsi\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\sebsi\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "C:\Users\sebsi\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 195, in download_and_install
    with zipfile.ZipFile(os.path.join(self.get_download_path(version), filename), mode="r") as driver_zipfile:
  File "C:\Users\sebsi\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "C:\Users\sebsi\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by AndreGrigorian** [comment]
same
