### ISSUE TITLE
don't comment 

### ISSUE THREAD

**Issue by AlirezaKarimiyan** [InstaPy/InstaPy#6600]
hi
When the robot enters the commenting process, I encounter this error:
INFO [2022-05-02 01:28:40] [mohsenkiami]  --> Image...
INFO [2022-05-02 01:28:40] [mohsenkiami]  --> Image liked!
Traceback (most recent call last):
  File "C:\Users\Ali\Desktop\tests\test2.py", line 75, in <module>
    session.like_by_tags(['crypto'], amount=2)
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 2067, in like_by_tags
    success = process_comments(
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\comment_util.py", line 445, in process_comments
    commented_image, message = verify_commented_image(browser, link, owner, logger)
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\comment_util.py", line 366, in verify_commented_image
    data = getMediaData("edge_media_to_parent_comment", browser)
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\util.py", line 523, in getMediaData
    data = additional_data["graphql"]["shortcode_media"]
KeyError: 'graphql'

Process finished with exit code 1

**Comment by EmanueleSeminara** [comment]
At the moment by downgrading to version 0.6.0 everything returns to work, here are the commands to do it:
`pip3 uninstall instapy
pip3 install --upgrade instapy==0.6.0`
I haven't tried with later versions.

**Comment by wolf2000-hub** [comment]
> At the moment by downgrading to version 0.6.0 everything returns to work, here are the commands to do it: `pip3 uninstall instapy pip3 install --upgrade instapy==0.6.0` I haven't tried with later versions.


I did it, but this way, I came across this:
Issue with cookie for user mohsen---. Creating new cookie...
Login A/B test detected! Trying another string...

**Comment by EmanueleSeminara** [comment]
Same problem as mine, I think I can't close the cookie screen ... I'm trying to solve it with no great success.

**Comment by asep171** [comment]
same error, you sould fix or not yet
