### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

### ISSUE THREAD

**Issue by PanQyB** [InstaPy/InstaPy#6611]
hi guys, i have problem when start file quickstart.py

what is it and how to fixed that problem?

```

InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/home/InstaPy"
Traceback (most recent call last):
  File "/home/home/Desktop/instapy-quickstart/quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "/home/home/.local/lib/python3.10/site-packages/instapy/instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/home/home/.local/lib/python3.10/site-packages/instapy/browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/home/home/.local/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 180, in __init__
    RemoteWebDriver.__init__(
  File "/home/home/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/home/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/home/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/home/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

```

**Comment by boytsovau** [comment]
I have the same problem. Can anyone help?

**Comment by abdulqadeerqureshi** [comment]
I am having same issue on mac
