### ISSUE TITLE
Got an issue 'attributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by xProSen** [InstaPy/InstaPy#6619]
here's the full code:
PS C:\Users\a\Desktop> py bot.py
InstaPy Version: 0.6.16
.. .. .. .. .. .. .. .. ._.
Workspace in use: "C:/Users/a/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-06-11 19:23:28] [itayabergell] Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2022-06-11 19:23:36] [i] - Cookie file for user '...' loaded...
..................................................................
INFO [2022-06-11 19:24:03] Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2022-06-11 19:24:03] [i] Saving account progress...
INFO [2022-06-11 19:24:56] [ Failed to get followers count of 'b'...'' ~empty list
INFO [2022-06-11 19:25:46] [] Failed to get following count of 'b'...'' ~empty list
WARNING [2022-06-11 19:25:46] [...] Unable to save account progress, skipping data update
b"'NoneType' object has no attribute 'get'"
Traceback (most recent call last):
File "C:\Users\Desktop\bot.py", line 9, in
session.login()
File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 475, in login
self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
File "C:\Usersי\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\print_log_writer.py", line 21, in log_follower_num
followed_by = getUserData("graphql.user.edge_followed_by.count", browser)
File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\util.py", line 501, in getUserData
get_key = shared_data.get("entry_data").get("ProfilePage")
AttributeError: 'NoneType' object has no attribute 'get'
PS C:\Users\a\Desktop>

**Comment by adrielkirch** [comment]
Same issue, haven't found a solution yet

**Comment by kelvin-tran** [comment]
Same issue as https://github.com/InstaPy/InstaPy/issues/6615

**Comment by s4gor** [comment]
same

**Comment by NomanBaigA** [comment]
Same issue

**Comment by Qapmarcelo** [comment]
> Mesmo problema, ainda não encontrei solução

advise a solution?

**Comment by GASTAOPOLYTECH** [comment]
it's 2024 do you guys found the solution ?

**Comment by wsdt** [comment]
bot completely broken
