### ISSUE TITLE
ERROR: Unable to locate element: {"method":"xpath","selector":"//li[2]/a/span"}

### ISSUE THREAD

**Issue by datteba** [InstaPy/InstaPy#662]
![image](https://user-images.githubusercontent.com/30053143/30472548-42c47486-99fd-11e7-9ca8-d2474579e802.png)

**Comment by timgrossmann** [comment]
@datteba Thank you, this has to be fixed pretty quickly!

**Comment by SamuelPinho** [comment]
The same here.

**Comment by tibor** [comment]
@timgrossmann I have a similar error in the unfollow process:

```
Logged in successfully!
Number of people followed automatically remaining: 408
Traceback (most recent call last):
  File "unfollow.py", line 15, in <module>
    .unfollow_users(amount=500)\
  File "/home/tibor/InstaPy/instapy/instapy.py", line 961, in unfollow_users
    onlyInstapyMethod, self.automatedFollowedPool)
  File "/home/tibor/InstaPy/instapy/unfollow_util.py", line 111, in unfollow
    dialog = browser.find_element_by_xpath('/html/body/div[4]/div/div[2]/div/div[2]/div/div[2]')
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[4]/div/div[2]/div/div[2]/div/div[2]"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 2.6.32-042stab120.6 x86_64)
```

**Comment by alexauvray** [comment]
I have the same problem @tibor

**Comment by alexauvray** [comment]
Found it : you need to replace the xpath (under # find dialog box) in unfollow_util.py by
/html/body/div[4]/div/div/div[2]/div

**Comment by alexsonnay** [comment]
However mine still unfollows friends I excluded...

**Comment by tibor** [comment]
@alexsonnay thanks, this way it works again. Are you doing a PR as well?

**Comment by converge** [comment]
#744 bug fix (merged)

**Comment by Foerdy** [comment]
I seem to have a similar problem:


python ./quickstart.py
INFO [2018-06-02 19:00:51] [foerdy]  Session started - 2018-06-02 19:00:51
Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20180602-190120.html
**********************************************************************
INFO [2018-06-02 19:01:20] [foerdy]  Session ended - 2018-06-02 19:01:20
INFO [2018-06-02 19:01:20] [foerdy]  --------------------


Traceback (most recent call last):
  File "./quickstart.py", line 25, in <module>
    session.login()
  File "/home/foerdy/InstaPy/instapy/instapy.py", line 322, in login
    self.bypass_suspicious_attempt):
  File "/home/foerdy/InstaPy/instapy/login_util.py", line 136, in login_user
    "//select[@class='_fsoey']/option[text()='English']").click()
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=67.0.3396.62)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.15.0-22-generic x86_64)
