### ISSUE TITLE
Did some major changes to try and fix data access due to instagram changes on jun/2022

### ISSUE THREAD

**Issue by victorccaldas** [InstaPy/InstaPy#6626]
It's available in my fork, but still very buggy.
To fix it completely and make it work we should recover an active community.

@timgrossmann is this project still active?

**Comment by dkyazzentwatwa** [comment]
Will give it a try. Tim has probably been silenced by Meta and can’t really update or help us at this point.

**Comment by metapodcod** [comment]
@victorccaldas i tried your fork but i am getting errors

```
Versão Instapy: 0.7
Traceback (most recent call last):
  File "C:\Users\metapodcod\InstaPy\quicstart.py", line 4, in <module>
    from instapy import InstaPy
  File "C:\Users\metapodcod\InstaPy\instapy\__init__.py", line 7, in <module>
    from .instapy import InstaPy
  File "C:\Users\metapodcod\InstaPy\instapy\instapy.py", line 35, in <module>
    from .browser import close_browser, set_selenium_local_session
  File "C:\Users\metapodcod\InstaPy\instapy\browser.py", line 15, in <module>
    from .util import interruption_handler
  File "C:\Users\metapodcod\InstaPy\instapy\util.py", line 51, in <module>
    from .minhas_funcoes import verificar_link
ImportError: cannot import name 'verificar_link' from 'instapy.minhas_funcoes' (C:\Users\metapodcod\InstaPy\instapy\minhas_funcoes.py)
```
