### ISSUE TITLE
Browser's "shared_data" is a NoneType now and has no attribute 'get' !

### ISSUE THREAD

**Issue by medhachoum** [InstaPy/InstaPy#6632]
Hi , Every time I use Instapy after successfully logging in my account  I encounter this problem, which makes using the library useless!

Traceback (most recent call last):
  File "C:\Users\med\OneDrive\python projects\InstaBot\DTF MA Handler\dtfbot\Start.py", line 19, in <module>
    with smart_run(session):
  File "C:\users\med\appdata\local\programs\python\python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "C:\Users\med\AppData\Local\pypoetry\Cache\virtualenvs\dtfbot-W9o4miMr-py3.9\lib\site-packages\instapy\util.py", line 1983, in smart_run
    session.login()
  File "C:\Users\med\AppData\Local\pypoetry\Cache\virtualenvs\dtfbot-W9o4miMr-py3.9\lib\site-packages\instapy\instapy.py", line 475, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\Users\med\AppData\Local\pypoetry\Cache\virtualenvs\dtfbot-W9o4miMr-py3.9\lib\site-packages\instapy\print_log_writer.py", line 21, in log_follower_num
    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)
  File "C:\Users\med\AppData\Local\pypoetry\Cache\virtualenvs\dtfbot-W9o4miMr-py3.9\lib\site-packages\instapy\util.py", line 501, in getUserData
    get_key = shared_data.get("entry_data").get("ProfilePage")
AttributeError: 'NoneType' object has no attribute 'get'

Did you find any solution to this problem? Is the library still active in developing?
any clue on how to fix it?

**Comment by fluttered** [comment]
Dublicate of #6615
