### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: geckodriver.exe

### ISSUE THREAD

**Issue by sourstripe** [InstaPy/InstaPy#6643]
## Expected Behavior
instapy runs

## Current Behavior
It does not run. I get the error
after running `python quickstart.py -u bob`

 ```
._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Custom workspace set: "C:/Users/bob/Desktop/Desktop/useful/InstaPy-master" :]
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/bob/Desktop/Desktop/useful/InstaPy-master"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-08-27 18:56:57] [bob]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
INFO [2022-08-27 18:56:57] [bob]  Workspace in use: "C:/Users/bob/Desktop/Desktop/useful/InstaPy-master"
Traceback (most recent call last):
  File "C:\Users\bob\Desktop\Desktop\useful\InstaPy-master\quickstart.py", line 50, in <module>
    session = InstaPy()
  File "C:\Users\bob\Desktop\Desktop\useful\InstaPy-master\instapy\instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\bob\Desktop\Desktop\useful\InstaPy-master\instapy\browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\bob\Desktop\Desktop\useful\InstaPy-master\instapy\browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "C:\Users\bob\AppData\Local\Programs\Python\Python310\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 225, in download_and_install
    shutil.copy2(src_file, dest_file)
  File "C:\Users\bob\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\bob\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\bob\\Desktop\\Desktop\\useful\\InstaPy-master\\assets\\geckodriver.exe'
```

This is after a restart of my computer to make sure no other instances are running.
using latest stable version of windows 11

**Comment by sourstripe** [comment]
fixed it. realized i was accidentally running two sessions
