### ISSUE TITLE
Issue when trying to run InstaPy

### ISSUE THREAD

**Issue by eastcoastboys** [InstaPy/InstaPy#6650]
Workspace in use: "C:/Users/Jordan Gri/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-10-27 16:03:58] [shotsbyjordangri]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2022-10-27 16:04:02] [shotsbyjordangri]  - Cookie file not found, creating cookie...
WARNING [2022-10-27 16:04:13] [shotsbyjordangri]  Login A/B test detected! Trying another string...
WARNING [2022-10-27 16:04:18] [shotsbyjordangri]  Could not pass the login A/B test. Trying last string...
ERROR [2022-10-27 16:04:23] [shotsbyjordangri]  Login A/B test failed!
        b"Message: Unable to locate element: //div[text()='Log In']\nStacktrace:\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:186:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:398:5\nelement.find/</<@chrome://remote/content/marionette/element.js:300:16\n"
Traceback (most recent call last):
  File "C:\Users\Jordan Gri\Desktop\Python Projects\InstaPy-master\instapy\login_util.py", line 337, in login_user
    login_elem = browser.find_element(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan Gri\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan Gri\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Jordan Gri\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[text()='Log In']
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:186:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:398:5
element.find/</<@chrome://remote/content/marionette/element.js:300:16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan Gri\Desktop\Python Projects\InstaPy-master\instapy\login_util.py", line 343, in login_user
    login_elem = browser.find_element(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan Gri\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan Gri\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Jordan Gri\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[text()='Log In']
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:186:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:398:5
element.find/</<@chrome://remote/content/marionette/element.js:300:16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan Gri\Desktop\Python Projects\InstaPy-master\instapy\login_util.py", line 350, in login_user
    login_elem = browser.find_element(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan Gri\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan Gri\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Jordan Gri\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[text()='Log In']
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:186:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:398:5
element.find/</<@chrome://remote/content/marionette/element.js:300:16

..............................................................................................................................
CRITICAL [2022-10-27 16:04:23] [shotsbyjordangri]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2022-10-27 16:04:23] [shotsbyjordangri]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2022-10-27 16:04:23] [shotsbyjordangri]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 31.08 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-10-27 16:04:23] [shotsbyjordangri]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by VladSemenik** [comment]
I have the same error

Has anybody solved this?

**Comment by official-antique** [comment]
@VladSemenik it wont be solved any time soon, it *may* be possible with a **LOT** of work but I don't see it happening.

**Comment by Jayybags** [comment]
> 

@official-antique  what kind of work?

**Comment by official-antique** [comment]
@Jayybags

1. `_sharedData` is no longer found in `window` which causes the "Saving account progress" issue.
2. `xpath` values for buttons, elements, etc. have changed which causes the "Failed to get followers" and many other issues.
3. `UNICODE_EMOJI` has been replaced by `EMOJI_DATA` in the `emoji` module (easy fix).

This list isn't exhaustive but those are the main ones. My previous fork before my rewrite fixed the `_sharedData` and `UNICODE_EMOJI` issues and touched the `xpath` issue.

**Comment by Jayybags** [comment]
@official-antique so this is a list of the issues i need to fix for me to finally run instapy? I mean, i've fixed the emoji issue.
its pip install emoji==1.7 right? yeah, so I've sorted that out. Mind talking me through the other steps? seems like alot of work like you said. Btw, im new to this board, what exactly is a fork?

**Comment by official-antique** [comment]
@Jayybags That's just some of the things that need fixing, after making my edit I remembered that recent posts are no longer available natively so that'd need changing too.

Unfortunately I can't give much more help with the project, from my point of view having spent the better part of 3 days working on it I've come to the conclusion that InstaPy cannot be fixed.

**Comment by eastcoastboys** [comment]
That's good that we know what we need to do to get the bot back up and running! 
I'm not super familiar with Python code to offer any help on coding so I am totally dependent on you all!

**Comment by Jayybags** [comment]
> That's good that we know what we need to do to get the bot back up and running! I'm not super familiar with Python code to offer any help on coding so I am totally dependent on you all!

@eastcoastboys  lemme know when you find a solution bro! I'm struggling with this too

**Comment by Jayybags** [comment]
> That's good that we know what we need to do to get the bot back up and running! I'm not super familiar with Python code to offer any help on coding so I am totally dependent on you all!
 @official-antique @eastcoastboys  find a solution guys?
