### ISSUE TITLE
Problem with Instapy

### ISSUE THREAD

**Issue by osco55** [InstaPy/InstaPy#6655]
Hello, when I execute the quickstart.py, I have an error message like this :
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Elève\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\Elève\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 34, in <module>
    from .browser import close_browser, set_selenium_local_session
  File "C:\Users\Elève\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\browser.py", line 14, in <module>
    from .util import interruption_handler
  File "C:\Users\Elève\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\util.py", line 27, in <module>
    from emoji.unicode_codes import UNICODE_EMOJI
ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji.unicode_codes' (C:\Users\Elève\AppData\Local\Programs\Python\Python310\lib\site-packages\emoji\unicode_codes\__init__.py)`

Do you know how i can resolve it ? 
thank you in advance

**Comment by official-antique** [comment]
@osco55 It's not working due to the change in emoji module, the UNICODE_EMOJI is now EMOJI_DATA, even with that change though it won't work due to the changes Instagram has made.

**Comment by osco55** [comment]
so Instapy is useless ?

**Comment by official-antique** [comment]
Simply put, yes. InstaPy will require a complete rewrite to function as it once did however, those changes would require the project to move away from Selenium for a majority of the functionality.

**Comment by osco55** [comment]
Okay,thanks for yours responses 
what is the current program that works?

**Comment by retsied** [comment]
> 

Is there any alternative right now? I've seen InstaPy2 around but haven't heard much about it. Thanks

**Comment by official-antique** [comment]
@retsied InstaPy2 is fully functional and contains all but the Stories functionality of InstaPy.

I'm looking to add more stuff but I've been focusing on my emulator for the Play Store. You could join the Discord (on the InstaPy2 repo to keep track of updates).

**Comment by retsied** [comment]
@official-antique , thanks for the quick response

Can you point me in the right direction to install and get going with InstaPy2? 
Is [this](https://github.com/jetiston/InstaPy2/blob/master/README.md#basic-installation) correct? The readme shows the original github for install (pip install git+https://github.com/timgrossmann/InstaPy.git) which doesn't exist

**Comment by robertiulianstoica** [comment]
Hi there! @official-antique good job in taking the initiative in rebuilding the project. I see that the documentation link is broken. Is the setup process similar to instapy as also ?

**Comment by robertiulianstoica** [comment]
Thank you very much for your fast response!
