### ISSUE TITLE
Invalid Like Element and other error

### ISSUE THREAD

**Issue by T1000MG** [InstaPy/InstaPy#6661]
## Expected Behavior
Simple Like
## Current Behavior
Not a single like becaus of " --> Invalid Like Element!" 
and also some times i get the error down there 
## InstaPy configuration

Error Message:

Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\util.py", line 1185, in get_relationship_counts
    followers_count = browser.execute_script(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 506, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window._sharedData.entry_data.ProfilePage is undefined
Stacktrace:
@https://www.instagram.com/superalmanaque/:2:7
@https://www.instagram.com/superalmanaque/:3:8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Instabot\bot.py", line 25, in <module>
    session.like_by_tags(["bluray"], amount=4, skip_top_posts= True)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\instapy.py", line 1997, in like_by_tags
    validation, details = self.validate_user_call(user_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\instapy.py", line 1350, in validate_user_call
    validation, details = validate_username(
                          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\util.py", line 238, in validate_username
    followers_count, following_count = get_relationship_counts(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\util.py", line 1192, in get_relationship_counts
    followers_count = format_number(
                      ^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\util.py", line 1139, in format_number
    return int(formatted_num)
           ^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '116K'

**Comment by 0xA0E** [comment]
Use lower case 'k', or just enter 116000

**Comment by T1000MG** [comment]
> Use lower case 'k', or just enter 116000

Where? I am a litte bit confused. Im not so into Python. :(

**Comment by T1000MG** [comment]
No solution? ;(

**Comment by T1000MG** [comment]
> Use lower case 'k', or just enter 116000

Can you tell me where i shoud change it? I can't finde the place.
