### ISSUE TITLE
Its not working 

### ISSUE THREAD

**Issue by juanrojasm** [InstaPy/InstaPy#6665]
PS C:\Users\JUAN ROJAS\xsx> python quickstart.py
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/JUAN ROJAS/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-12-15 19:50:00] [gouppers]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2022-12-15 19:50:00] [gouppers]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2022-12-15 19:50:00] [gouppers]  - Internet Connection Status: ok
INFO [2022-12-15 19:50:00] [gouppers]  - Current IP is "186.155.15.159" and it's from "Colombia/CO"
INFO [2022-12-15 19:50:00] [gouppers]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2022-12-15 19:50:00] [gouppers]  - window.navigator.webdriver response: True
WARNING [2022-12-15 19:50:00] [gouppers]  - Hide Selenium Extension: error
INFO [2022-12-15 19:50:03] [gouppers]  - Cookie file not found, creating cookie...
WARNING [2022-12-15 19:50:19] [gouppers]  Login A/B test detected! Trying another string...
WARNING [2022-12-15 19:50:24] [gouppers]  Could not pass the login A/B test. Trying last string...
ERROR [2022-12-15 19:50:30] [gouppers]  Login A/B test failed!
        b"Message: Unable to locate element: //div[text()='Log In']\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\nelement.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16\n"
Traceback (most recent call last):
  File "C:\Users\JUAN ROJAS\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\login_util.py", line 348, in login_user
    login_elem = browser.find_element(
  File "C:\Users\JUAN ROJAS\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\JUAN ROJAS\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\JUAN ROJAS\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[text()='Log In']
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JUAN ROJAS\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\login_util.py", line 354, in login_user
    login_elem = browser.find_element(
  File "C:\Users\JUAN ROJAS\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\JUAN ROJAS\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\JUAN ROJAS\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //a[text()='Log in']
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JUAN ROJAS\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\login_util.py", line 361, in login_user
    login_elem = browser.find_element(
  File "C:\Users\JUAN ROJAS\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\JUAN ROJAS\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\JUAN ROJAS\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[text()='Log In']
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16

......................................................................................................................
CRITICAL [2022-12-15 19:50:30] [gouppers]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2022-12-15 19:50:30] [gouppers]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2022-12-15 19:50:32] [gouppers]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 41.04 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-12-15 19:50:32] [gouppers]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by SerhatYildrm** [comment]
Try it.
https://github.com/InstaPy/InstaPy/issues/6669#issuecomment-1365229232
