### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by AwakexD** [InstaPy/InstaPy#6669]
## Current Behavior
 File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[text()='Log In']

**Comment by SerhatYildrm** [comment]
Try change //div[text()='Log In'  to //div[text()='Log in'  in xpath_compile.py file. (line number 176)

**Comment by AwakexD** [comment]
I've tried but it doesn't work

**Comment by SerhatYildrm** [comment]
Could you share the python error ?

**Comment by carmenintech** [comment]
Hi @SerhatYildrm, I downloaded the instapy quickstart repo and have that running, as well as the main instapy repo, on my machine. 

I found the `xpath_compile.py` file in `usr/local/lib/python3.10/site-packages/instapy` and edited the "in" as you suggested, but it's not being picked up by the quickstart.py script in my instapy quickstart folder. 

![Screen Shot 2022-12-29 at 3 18 25 pm](https://user-images.githubusercontent.com/103980536/209903167-0c1e71d8-ca6e-4888-ba13-0867c38541d7.png)

Sorry for the ignorance, but how do I either get the `xpath_compile.py` change reflected in my instapy quickstart setup - or alternatively, how do I get the quickstart.py file working in my general instapy package?

**Comment by vert0x9** [comment]
Same result, albeit xpath_compile.py has this exception handling here:

```
    "login_elem": "//button[text()='Log In']",
    "login_elem_no_such_exception": "//a[text()='Log in']",
    "login_elem_no_such_exception_2": "//div[text()='Log in']",
```

according to the log it tries other options, but the result is somewhat the same.  

```

`mndrmbp15-6:InstaPy mandrivko$ python /Users/mandrivko/Downloads/instapy-quickstart-master/simple_interaction_good_for_beginners.py 
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/mandrivko/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2023-01-17 14:13:58] [khlatrava]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2023-01-17 14:14:02] [khlatrava]  - Cookie file not found, creating cookie...
WARNING [2023-01-17 14:14:12] [khlatrava]  Login A/B test detected! Trying another string...
WARNING [2023-01-17 14:14:17] [khlatrava]  Could not pass the login A/B test. Trying last string...
ERROR [2023-01-17 14:14:22] [khlatrava]  Login A/B test failed!
	b"Message: Unable to locate element: //div[text()='Log In']\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\nelement.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16\n"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/login_util.py", line 338, in login_user
    By.XPATH, read_xpath(login_user.__name__, "login_elem")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1250, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[text()='Log In']
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/login_util.py", line 345, in login_user
    read_xpath(login_user.__name__, "login_elem_no_such_exception"),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1250, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //a[text()='Log in']
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/login_util.py", line 352, in login_user
    read_xpath(login_user.__name__, "login_elem_no_such_exception_2"),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1250, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[text()='Log In']
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16

.......................................................................................................................
CRITICAL [2023-01-17 14:14:22] [khlatrava]  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2023-01-17 14:14:22] [khlatrava]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2023-01-17 14:14:23] [khlatrava]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 28.21 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2023-01-17 14:14:23] [khlatrava]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo


`
```

**Comment by vert0x9** [comment]
I've updated to python3.11 and got a different output: 

```
mndrmbp15-6:InstaPy mandrivko$ python3 /Users/mandrivko/Downloads/instapy-quickstart-master/simple_interaction_good_for_beginners.py 
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/mandrivko/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2023-01-17 15:26:20] [khlatrava]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2023-01-17 15:26:23] [khlatrava]  - Cookie file not found, creating cookie...
WARNING [2023-01-17 15:26:33] [khlatrava]  Login A/B test detected! Trying another string...
WARNING [2023-01-17 15:26:38] [khlatrava]  Could not pass the login A/B test. Trying last string...
ERROR [2023-01-17 15:26:43] [khlatrava]  Login A/B test failed!
	b"Message: Unable to locate element: //div[text()='Log In']\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\nelement.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16\n"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy/login_util.py", line 337, in login_user
    login_elem = browser.find_element(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[text()='Log In']
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy/login_util.py", line 343, in login_user
    login_elem = browser.find_element(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //a[text()='Log in']
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy/login_util.py", line 350, in login_user
    login_elem = browser.find_element(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[text()='Log In']
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16

.......................................................................................................................
CRITICAL [2023-01-17 15:26:43] [khlatrava]  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2023-01-17 15:26:43] [khlatrava]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2023-01-17 15:26:44] [khlatrava]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 27.43 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2023-01-17 15:26:44] [khlatrava]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo


```

**Comment by official-antique** [comment]
@vert0x9 "unable to find element" is likely because of capitalisation of the text (its case-sensitive) or the xpath being incorrect.

**Comment by vert0x9** [comment]
> 

i've changed the capitalization in the file to no effect. But what could be wrong with xpath? Thanks

**Comment by henrique-cechinel** [comment]
Open xpath_compile.py.
Change ALL 'Log In' occurrences to 'Log in' (there should be two: "//div[text()='Log In']" and "//button[text()='Log In']".

I was facing the same error, and after changing these two lines, it worked for me!

**Comment by vert0x9** [comment]
Ah, yes. Did that to no effect

**Comment by slavianap** [comment]
Same issue here. Changing capitalisation doesn't help.

**Comment by frostynikov** [comment]
INFO [2023-02-09 23:51:47] [0xfrosterix]  -- Connection Checklist [1/2] (Internet Connection Status)
WARNING [2023-02-09 23:51:48] [0xfrosterix]  - Internet Connection Status: error
.........................................................................................................................
CRITICAL [2023-02-09 23:51:48] [0xfrosterix]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''

Now is doing this. I change the Log in's

**Comment by ajju2smart** [comment]
Modified the element but still not working. Facing the same error. Did someone found the resolution for that issue.    self.error_handler.check_response(response)
  File "C:\Users\i5-Sys\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[text()='Log In']

**Comment by abusyafii** [comment]
Change all "Log in" capitalisation

    "login_elem": "//button[text()='Log in']",
    "login_elem_no_such_exception": "//a[text()='Log in']",
    "login_elem_no_such_exception_2": "//div[text()='Log in']",

**Comment by creativejaymi** [comment]
where can i change them??

> For future readers... Change all "Log in" capitalisation solved this issue
> 
> ```
> "login_elem": "//button[text()='Log in']",
> "login_elem_no_such_exception": "//a[text()='Log in']",
> "login_elem_no_such_exception_2": "//div[text()='Log in']",
> ```

where can i change this?

**Comment by abdulrafayyamir** [comment]
I was changing the capitalization in `xpath_compile.py`, but it wasn't working. I would get the same error. Adding "contains" to the XML path resolved the issue.

The `contains` function finds elements that contain the specified text. This can be more flexible in case there are additional spaces or elements surrounding the "Log in" text.

Try the following:

```xml
"login_elem": "//button[contains(text(), 'Log in')]",
"login_elem_no_such_exception": "//a[contains(text(), 'Log in')]",
"login_elem_no_such_exception_2": "//div[contains(text(), 'Log in')]",

**Comment by viniciusdalve** [comment]
> I was changing the capitalization in `xpath_compile.py`, but it wasn't working. I would get the same error. Adding "contains" to the XML path resolved the issue.
> 
> The `contains` function finds elements that contain the specified text. This can be more flexible in case there are additional spaces or elements surrounding the "Log in" text.
> 
> Try the following:
> 
> ```
> "login_elem": "//button[contains(text(), 'Log in')]",
> "login_elem_no_such_exception": "//a[contains(text(), 'Log in')]",
> "login_elem_no_such_exception_2": "//div[contains(text(), 'Log in')]",
> ```

It worked for me, but it generated another error:

InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/admin/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2024-01-06 17:50:22] [grupo.mentes.milionarias]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2024-01-06 17:50:29] [grupo.mentes.milionarias]  - Cookie file for user 'grupo.mentes.milionarias' loaded...
WARNING [2024-01-06 17:50:45] [grupo.mentes.milionarias]  - Issue with cookie for user 'grupo.mentes.milionarias'. Creating new cookie...
INFO [2024-01-06 17:50:45] [grupo.mentes.milionarias]  - Deleting browser cookies...
WARNING [2024-01-06 17:50:54] [grupo.mentes.milionarias]  Login A/B test detected! Trying another string...
WARNING [2024-01-06 17:50:59] [grupo.mentes.milionarias]  Could not pass the login A/B test. Trying last string...
..............................................................................
INFO [2024-01-06 17:51:33] [grupo.mentes.milionarias]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2024-01-06 17:51:33] [grupo.mentes.milionarias]  Saving account progress...
WARNING [2024-01-06 17:51:36] [grupo.mentes.milionarias]  Unable to save account progress, skipping data update 
        b"invalid literal for int() with base 10: '627\\nfollowers'"
Traceback (most recent call last):
  File "/Users/admin/Documents/instapy/instabot.py", line 10, in <module>
    session.login()
  File "/opt/homebrew/lib/python3.11/site-packages/instapy/instapy.py", line 475, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/instapy/print_log_writer.py", line 21, in log_follower_num
    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/instapy/util.py", line 501, in getUserData
    get_key = shared_data.get("entry_data").get("ProfilePage")
              ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by abdulrafayyamir** [comment]
> > I was changing the capitalization in `xpath_compile.py`, but it wasn't working. I would get the same error. Adding "contains" to the XML path resolved the issue.
> > The `contains` function finds elements that contain the specified text. This can be more flexible in case there are additional spaces or elements surrounding the "Log in" text.
> > Try the following:
> > ```
> > "login_elem": "//button[contains(text(), 'Log in')]",
> > "login_elem_no_such_exception": "//a[contains(text(), 'Log in')]",
> > "login_elem_no_such_exception_2": "//div[contains(text(), 'Log in')]",
> > ```
> 
> It worked for me, but it generated another error:
> 
> InstaPy Version: 0.6.16 ._. ._. ._. ._. ._. ._. ._. ._. Workspace in use: "/Users/admin/InstaPy" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO INFO [2024-01-06 17:50:22] [grupo.mentes.milionarias] Session started! oooooooooooooooooooooooooooooooooooooooooooooooooooooo INFO [2024-01-06 17:50:29] [grupo.mentes.milionarias] - Cookie file for user 'grupo.mentes.milionarias' loaded... WARNING [2024-01-06 17:50:45] [grupo.mentes.milionarias] - Issue with cookie for user 'grupo.mentes.milionarias'. Creating new cookie... INFO [2024-01-06 17:50:45] [grupo.mentes.milionarias] - Deleting browser cookies... WARNING [2024-01-06 17:50:54] [grupo.mentes.milionarias] Login A/B test detected! Trying another string... WARNING [2024-01-06 17:50:59] [grupo.mentes.milionarias] Could not pass the login A/B test. Trying last string... .............................................................................. INFO [2024-01-06 17:51:33] [grupo.mentes.milionarias] Logged in successfully! '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' INFO [2024-01-06 17:51:33] [grupo.mentes.milionarias] Saving account progress... WARNING [2024-01-06 17:51:36] [grupo.mentes.milionarias] Unable to save account progress, skipping data update b"invalid literal for int() with base 10: '627\nfollowers'" Traceback (most recent call last): File "/Users/admin/Documents/instapy/instabot.py", line 10, in session.login() File "/opt/homebrew/lib/python3.11/site-packages/instapy/instapy.py", line 475, in login self.followed_by = log_follower_num(self.browser, self.username, self.logfolder) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/instapy/print_log_writer.py", line 21, in log_follower_num followed_by = getUserData("graphql.user.edge_followed_by.count", browser) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/instapy/util.py", line 501, in getUserData get_key = shared_data.get("entry_data").get("ProfilePage") ^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'get'

One bug after the other in this library, it's not well maintained. I would recommend you learn selenium & python and make your own bot for your purposes. I personally found that easier than debugging things in InstaPy.

**Comment by viniciusdalve** [comment]
> > > I was changing the capitalization in `xpath_compile.py`, but it wasn't working. I would get the same error. Adding "contains" to the XML path resolved the issue.
> > > The `contains` function finds elements that contain the specified text. This can be more flexible in case there are additional spaces or elements surrounding the "Log in" text.
> > > Try the following:
> > > ```
> > > "login_elem": "//button[contains(text(), 'Log in')]",
> > > "login_elem_no_such_exception": "//a[contains(text(), 'Log in')]",
> > > "login_elem_no_such_exception_2": "//div[contains(text(), 'Log in')]",
> > > ```
> > 
> > 
> > It worked for me, but it generated another error:
> > InstaPy Version: 0.6.16 ._. ._. ._. ._. ._. ._. ._. ._. Workspace in use: "/Users/admin/InstaPy" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO INFO [2024-01-06 17:50:22] [grupo.mentes.milionarias] Session started! oooooooooooooooooooooooooooooooooooooooooooooooooooooo INFO [2024-01-06 17:50:29] [grupo.mentes.milionarias] - Cookie file for user 'grupo.mentes.milionarias' loaded... WARNING [2024-01-06 17:50:45] [grupo.mentes.milionarias] - Issue with cookie for user 'grupo.mentes.milionarias'. Creating new cookie... INFO [2024-01-06 17:50:45] [grupo.mentes.milionarias] - Deleting browser cookies... WARNING [2024-01-06 17:50:54] [grupo.mentes.milionarias] Login A/B test detected! Trying another string... WARNING [2024-01-06 17:50:59] [grupo.mentes.milionarias] Could not pass the login A/B test. Trying last string... .............................................................................. INFO [2024-01-06 17:51:33] [grupo.mentes.milionarias] Logged in successfully! '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' INFO [2024-01-06 17:51:33] [grupo.mentes.milionarias] Saving account progress... WARNING [2024-01-06 17:51:36] [grupo.mentes.milionarias] Unable to save account progress, skipping data update b"invalid literal for int() with base 10: '627\nfollowers'" Traceback (most recent call last): File "/Users/admin/Documents/instapy/instabot.py", line 10, in session.login() File "/opt/homebrew/lib/python3.11/site-packages/instapy/instapy.py", line 475, in login self.followed_by = log_follower_num(self.browser, self.username, self.logfolder) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/instapy/print_log_writer.py", line 21, in log_follower_num followed_by = getUserData("graphql.user.edge_followed_by.count", browser) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/instapy/util.py", line 501, in getUserData get_key = shared_data.get("entry_data").get("ProfilePage") ^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'get'
> 
> One bug after the other in this library, it's not well maintained. I would recommend you learn selenium & python and make your own bot for your purposes. I personally found that easier than debugging things in InstaPy.

true, I'll do that, thanks man!

**Comment by dy11-laktosa** [comment]
._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/hady4/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2024-08-28 02:59:43] [hayyy1.1]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2024-08-28 02:59:43] [hayyy1.1]  -- Connection Checklist [1/2] (Internet Connection Status)
WARNING [2024-08-28 02:59:43] [hayyy1.1]  - Internet Connection Status: error
......................................................................................................................
CRITICAL [2024-08-28 02:59:43] [hayyy1.1]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2024-08-28 02:59:47] [hayyy1.1]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 16.77 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2024-08-28 02:59:47] [hayyy1.1]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by thor-slugger** [comment]
https://pythondev.space/questions/obtaining-div-attributes-with-python-selenium Acknowledge this note
