### ISSUE TITLE
Finding Login Element

### ISSUE THREAD

**Issue by KeaganKM** [InstaPy/InstaPy#6672]
## Current Behavior
 py bot.py
InstaPy Version: 0.6.14
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Keagan/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2023-01-06 10:07:47] [keagan_km]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2023-01-06 10:07:50] [keagan_km]  - Cookie file not found, creating cookie...
Traceback (most recent call last):
  File "C:\Users\Keagan\Dropbox\PC (4)\Desktop\bot.py", line 4, in <module>
    session.login()
  File "C:\Users\Keagan\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\instapy.py", line 428, in login
    if not login_user(
           ^^^^^^^^^^^
  File "C:\Users\Keagan\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\login_util.py", line 327, in login_user
    login_elem = browser.find_element_by_xpath(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WebDriver' object has no attribute 'find_element_by_xpath'
## InstaPy configuration

[geckodriver.log](https://github.com/InstaPy/InstaPy/files/10361242/geckodriver.log)

**Comment by ImanMo93** [comment]
edit login_util.py
line 327>
replace:
login_elem = browser.find_element_by_xpath(
with:
login_elem = browser.find_element(

**Comment by ajju2smart** [comment]
In the latest version this changes has been implemented but still getting the selenium error:
WARNING [2023-02-18 23:09:13] [be_positive_be_yourself_]  - Hide Selenium Extension: error        
INFO [2023-02-18 23:09:18] [be_positive_be_yourself_]  - Cookie file not found, creating cookie...
WARNING [2023-02-18 23:09:28] [be_positive_be_yourself_]  Login A/B test detected! Trying another string...
WARNING [2023-02-18 23:09:33] [be_positive_be_yourself_]  Could not pass the login A/B test. Trying last string...
ERROR [2023-02-18 23:09:38] [be_positive_be_yourself_]  Login A/B test failed!
        b"Message: Unable to locate element: //div[text()='Log In']\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5\nelement.find/</<@chrome://remote/content/marionette/element.sys.mjs:133:16\n"
Traceback (most recent call last):
  File "E:\Development\Instagram\InstaPy\instapy\login_util.py", line 340, in login_user
    login_elem = browser.find_element(

**Comment by daniloCaldeiraDWL** [comment]
Boa noite, também estou tendo o mesmo erro @ajju2smart 
Não consegui resolver o problema ainda!!!

**Comment by one-one-one-one** [comment]
wala wala

**Comment by obol2** [comment]
> edit login_util.py line 327> replace: login_elem = browser.find_element_by_xpath( with: login_elem = browser.find_element(

This is was already correct in login_util.py but I still get the login error. It seems that there are 3 buttons to find. My login is not working. Maybe that is the problem.

![Untitled](https://github.com/InstaPy/InstaPy/assets/10994379/b3d12cf6-cd3e-414a-912c-d6d5e18ffa80)


Log:

> INFO [2023-10-05 02:17:34] [XXXXX]  Session started!
INFO [2023-10-05 02:17:37] [XXXXX]  - Cookie file not found, creating cookie...
INFO [2023-10-05 02:17:37] [XXXXX]  - Accepted IG cookies by default...
WARNING [2023-10-05 02:17:43] [XXXXX]  Login A/B test detected! Trying another string...
WARNING [2023-10-05 02:17:48] [XXXXX]  Could not pass the login A/B test. Trying last string...
ERROR [2023-10-05 02:17:53] [XXXXX]  Login A/B test failed!
	b"Message: Unable to locate element: //div[text()='Log In']\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:507:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16\n"
Traceback (most recent call last):
  File "C:\Users\YYYYY\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\login_util.py", line 336, in login_user
    login_elem = browser.find_element(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YYYYY\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 831, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YYYYY\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\YYYYY\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[text()='Log In']


Any ideas how to fix this? Headless browser doesn't work.

**Comment by ahmed-alii** [comment]
Any updates in this issue?
