### ISSUE TITLE
Close quickstart immediately

### ISSUE THREAD

**Issue by rafffix** [InstaPy/InstaPy#668]
Hi there, sry for stupied questions but,
i followed the instructions and when i hit "RUN!" in the GUI or start quickstart it closes immediately.
I read and followed this post [https://github.com/Nemixalone/GUI-tool-for-InstaPy-script/issues/2](url) and everything works out fine, except `py get-pip.py`.
I just get this `PS C:\Users\Name> py get-pip.py
C:\Users\Name\AppData\Local\Programs\Python\Python36\python.exe: can't open file 'get-pip.py': [Errno 2] No such file
 or directory`
And like mentioned before, if i run InstaPy t closes immediately.
PS: my PC operates on windows 10.

Every help would be very nice :)

**Comment by GonzaloZiadi** [comment]
What the error message is saying is that you do not have the get-pip.py file in the folder from where you're running the command (`py get-pip.py`) from. 

You can get that file from here: https://packaging.python.org/tutorials/installing-packages/#install-pip-setuptools-and-wheel.

**Comment by rafffix** [comment]
Thank you very much! But where do i have to put it, that it works (tryed alot)?

**Comment by rafffix** [comment]
Thank you very much, but where do i have to put the file that it works ?

**Comment by GonzaloZiadi** [comment]
Put that file wherever you want. Then go wherever the file is through the command line and run  `python get-pip.py --prefix=/usr/local/`

**Comment by rafffix** [comment]
If i use this `C:\Users\Name\Downloads\Insta\InstaPy-master>py get-pip.py`, i get that `Requirement already up-to-date: pip in c:\users\name\appdata\local\programs\python\python36\lib\site-packages`.
Otherwise I (`C:\Users\Raphael\Downloads\Insta\InstaPy-master>py get-pip.py --prefix=/raphael/local/`) get that `Requirement already up-to-date: pip in c:\users\raphael\appdata\local\programs\python\python36\lib\site-packages
Exception:
Traceback (most recent call last):
  File "C:\Users\Raphael\AppData\Local\Temp\tmpj7vm5gbx\pip.zip\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Raphael\AppData\Local\Temp\tmpj7vm5gbx\pip.zip\pip\commands\install.py", line 350, in run
    isolated=options.isolated_mode,
  File "C:\Users\Raphael\AppData\Local\Temp\tmpj7vm5gbx\pip.zip\pip\commands\install.py", line 436, in get_lib_location_guesses
    scheme = distutils_scheme('', *args, **kwargs)
  File "C:\Users\Raphael\AppData\Local\Temp\tmpj7vm5gbx\pip.zip\pip\locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "C:\Users\Raphael\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "C:\Users\Raphael\AppData\Local\Programs\Python\Python36\lib\distutils\command\install.py", line 346, in finalize_options
    'userbase', 'usersite')
  File "C:\Users\Raphael\AppData\Local\Programs\Python\Python36\lib\distutils\command\install.py", line 487, in convert_paths
    setattr(self, attr, convert_path(getattr(self, attr)))
  File "C:\Users\Raphael\AppData\Local\Programs\Python\Python36\lib\distutils\util.py", line 125, in convert_path
    raise ValueError("path '%s' cannot be absolute" % pathname)
ValueError: path '/raphael/local//Lib/site-packages' cannot be absolute`

If i run instapy it still closes immediately.

PS: It's the right directory.

**Comment by converge** [comment]
hey @rafffix , did you managed to fix it ? how did you fix ?

**Comment by converge** [comment]
As there is no interaction for a long time, we are closing this issue. Please, reopen if you need help about this issue.
