### ISSUE TITLE
ModuleNotFoundError: No module named 'clarifai.rest'

### ISSUE THREAD

**Issue by FraTeG** [InstaPy/InstaPy#6680]
Traceback (most recent call last):
  File "C:\Users\franc\Downloads\InstaPy-master\quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "C:\Users\franc\Downloads\InstaPy-master\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\franc\Downloads\InstaPy-master\instapy\instapy.py", line 35, in <module>
    from .clarifai_util import check_image
  File "C:\Users\franc\Downloads\InstaPy-master\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Workflow
ModuleNotFoundError: No module named 'clarifai.rest'

**Comment by shredstick** [comment]
I have the exact same issue. Let me know if you found a solution :)

**Comment by leofloripa** [comment]
I have the exact same issue. Let me know if you found a solution :)

**Comment by leofloripa** [comment]
pip uninstall clarifai
pip install clarifai==2.6.2

**Comment by shredstick** [comment]
Thanks, this fixed it!

**Comment by filiperivelli** [comment]
Fixed, thanks.

**Comment by gamingnotice** [comment]
container@pterodactyl~ Server marked as running...
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: clarifai==2.6.2 in ./.local/lib/python3.11/site-packages (2.6.2)
Requirement already satisfied: future<2,>=0.15 in ./.local/lib/python3.11/site-packages (from clarifai==2.6.2) (0.18.3)
Requirement already satisfied: requests<3,>=2.13 in ./.local/lib/python3.11/site-packages (from clarifai==2.6.2) (2.28.2)
Requirement already satisfied: configparser<4,>=3.5 in ./.local/lib/python3.11/site-packages (from clarifai==2.6.2) (3.8.1)
Requirement already satisfied: jsonschema<3,>=2.5 in ./.local/lib/python3.11/site-packages (from clarifai==2.6.2) (2.6.0)
Requirement already satisfied: grpcio<2,>=1.13.0 in ./.local/lib/python3.11/site-packages (from clarifai==2.6.2) (1.51.3)
Requirement already satisfied: protobuf<4,>=3.6 in ./.local/lib/python3.11/site-packages (from clarifai==2.6.2) (3.20.3)
Requirement already satisfied: googleapis-common-protos<2,>=1.5.0 in ./.local/lib/python3.11/site-packages (from clarifai==2.6.2) (1.58.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.local/lib/python3.11/site-packages (from requests<3,>=2.13->clarifai==2.6.2) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in ./.local/lib/python3.11/site-packages (from requests<3,>=2.13->clarifai==2.6.2) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.local/lib/python3.11/site-packages (from requests<3,>=2.13->clarifai==2.6.2) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.11/site-packages (from requests<3,>=2.13->clarifai==2.6.2) (2022.12.7)
[notice] A new release of pip available: 22.3 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/home/container/main.py", line 3, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'

now I have this error

**Comment by igorJeus** [comment]
C:\Users\green>python botinstagram.py
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/green/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2023-04-07 17:18:54] [bruno.alves.02]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2023-04-07 17:18:54] [bruno.alves.02]  -- Connection Checklist [1/2] (Internet Connection Status)
WARNING [2023-04-07 17:18:55] [bruno.alves.02]  - Internet Connection Status: error
............................................................................................................................
CRITICAL [2023-04-07 17:18:56] [bruno.alves.02]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2023-04-07 17:18:56] [bruno.alves.02]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2023-04-07 17:18:58] [bruno.alves.02]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 18.09 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2023-04-07 17:18:58] [bruno.alves.02]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

help

**Comment by codewithdripzy** [comment]
Dude this package is full of errors, try fixing it

**Comment by houssamHADELAMOUS** [comment]
from clarifai.rest import ClarifaiApp, Workflow
ModuleNotFoundError: No module named 'clarifai'

help me please 
i want to login in my instagram account with use python but i can't do that with this error

**Comment by quitegreensky** [comment]
It's really such a shame to see how incompatible this package is with many things. 

> Dude this package is full of errors, try fixing it, Immediately i fix one error another one is appearing
