### ISSUE TITLE
I'm close but It doesn't run

### ISSUE THREAD

**Issue by channelblackri** [InstaPy/InstaPy#6684]
## Expected Behavior
it should run after the seperate Window pops up 

## Current Behavior
gwitter@MacBook instapy-quickstart-master % python3 quickstart.py
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/gwitter/InstaPy"
Traceback (most recent call last):
  File "/Users/gwitter/Desktop/instapy-quickstart-master/quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

gwitter@MacBook instapy-quickstart-master % 

## Possible Solution (optional)
...
## InstaPy configuration
standard, just added some hashtags and Login Data

**Comment by channelblackri** [comment]
**I kind of got a step further. i think it needed firefox. Installed it, but now it has somehow no Internet connection, can't log in and it says not enough comments (10) even tho I'm using 12!!**
______________________________________________________________________________

gwitter@MacBook-Air-von-G instapy-quickstart-master % python3 quickstart.py
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/gwitter/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2023-02-19 19:15:16] [no]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2023-02-19 19:15:16] [no]  -- Connection Checklist [1/2] (Internet Connection Status)
WARNING [2023-02-19 19:15:17] [no]  - Internet Connection Status: error
........................................................................................................................
CRITICAL [2023-02-19 19:15:17] [no]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2023-02-19 19:15:17] [no]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2023-02-19 19:15:18] [no]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 4.56 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2023-02-19 19:15:18] [no]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo



gwitter@MacBook-Air-von-G instapy-quickstart-master %
