### ISSUE TITLE
InstaPy Not Working

### ISSUE THREAD

**Issue by codewithdripzy** [InstaPy/InstaPy#6686]
Traceback (most recent call last):
  File "C:\Users\user\Documents\TTN\ttn_Instapy_bot\src\main.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\instapy.py", line 34, in <module>
    from .browser import close_browser, set_selenium_local_session
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\browser.py", line 14, in <module>
    from .util import interruption_handler
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\util.py", line 27, in <module>
    from emoji.unicode_codes import UNICODE_EMOJI
ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji.unicode_codes' (C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\emoji\unicode_codes\__init__.py)

**Comment by codewithdripzy** [comment]
Ok, thank you, is it possible for me to get a proper documentation because
i don't understand how it works

**Comment by gamingnotice** [comment]
is instapy discontinued?

**Comment by maxclax** [comment]
```
pip uninstall emoji
pip install emoji==1.7
```
