### ISSUE TITLE
InstaPy not running

### ISSUE THREAD

**Issue by codewithdripzy** [InstaPy/InstaPy#6690]
Traceback (most recent call last):
  File "C:\Users\user\Documents\TTN\ttn_Instapy_bot\src\main.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\instapy.py", line 35, in <module>
    from .clarifai_util import check_image
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Workflow
ModuleNotFoundError: No module named 'clarifai.rest'

**Comment by auveele** [comment]
#6680

**Comment by AhmadxAli** [comment]
same errors

**Comment by codewithdripzy** [comment]
Can the developer of this library check this errors?

**Comment by codewithdripzy** [comment]
well the answer to this error is at issue #6680 just click the link to to the issue https://github.com/InstaPy/InstaPy/issues/6680
