### ISSUE TITLE
During handling of the above exception, another exception occurred

### ISSUE THREAD

**Issue by becauseimnoob** [InstaPy/InstaPy#6702]
qs.py template https://github.com/InstaPy/instapy-quickstart/blob/master/quickstart_templates/good_commenting_strategy_and_new_qs_system.py

```
INFO [2023-04-13 18:41:43] [myhandsomenick]  Image link: b'https://www.instagram.com/p/Cq-pj6kpoNT/'
INFO [2023-04-13 18:41:43] [myhandsomenick]  Description: b'\xf0\x9f\x91\xa9\xe2\x80\x8d\xf0\x9f\x8f\xab Pode chegar que tem mais um Tech Drops \xf0\x9f\x92\xbb\xf0\x9f\x92\x8a!!!\n.\nHoje vamos trazer dicas relacionadas ao VSCode, que e\xcc\x81 um dos editores mais utilizados da atualidade! \xf0\x9f\xa4\xa9 Usar atalhos \xe2\x8c\xa8\xef\xb8\x8f ao codificar pode nos econimizar muitos cliques \xf0\x9f\x96\xb1 e otimizar muito nosso tempo \xe2\x8f\xb1! \n.\nSe voce\xcc\x82 utiliza outro editor ou IDE, e ainda na\xcc\x83o esta\xcc\x81 muito familiarizada com os atalhos dele, chegou a hora de pesquisar sobre e facilitar muitooo seu dia a dia!\n.\nCurtiu esse Tech Drop?! Deixa seu comenta\xcc\x81rio aqui \xf0\x9f\x91\x87 #tech #produtividade #devgirls #vscode  #womenintech #devgirlsporelas'

INFO [2023-04-13 18:41:51] [myhandsomenick]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 14 users & had 442 FOLLOWERS
[Session lasted 1.58 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2023-04-13 18:41:51] [myhandsomenick]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "C:\Users\becauseimnoob\InstaPy\instapy\util.py", line 1185, in get_relationship_counts
    followers_count = browser.execute_script(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\becauseimnoob\InstaPy\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 500, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\becauseimnoob\InstaPy\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\becauseimnoob\InstaPy\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window._sharedData.entry_data.ProfilePage is undefined
Stacktrace:
@https://www.instagram.com/devgirlsbr/:2:7
@https://www.instagram.com/devgirlsbr/:3:8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\becauseimnoob\InstaPy\qs.py", line 301, in <module>
    session.like_by_tags(my_hashtags, amount=1, media=None)
  File "C:\Users\becauseimnoob\InstaPy\instapy\instapy.py", line 1997, in like_by_tags
    validation, details = self.validate_user_call(user_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\becauseimnoob\InstaPy\instapy\instapy.py", line 1350, in validate_user_call
    validation, details = validate_username(
                          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\becauseimnoob\InstaPy\instapy\util.py", line 238, in validate_username
    followers_count, following_count = get_relationship_counts(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\becauseimnoob\InstaPy\instapy\util.py", line 1192, in get_relationship_counts
    followers_count = format_number(
                      ^^^^^^^^^^^^^^
  File "C:\Users\becauseimnoob\InstaPy\instapy\util.py", line 1139, in format_number
    return int(formatted_num)
           ^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '646\nfollowers'
```

**Comment by brunoaduarte** [comment]
Similar error here, have you found a solution @becauseimnoob ?

```
InstaPy Version: 0.6.16

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 

Workspace in use: "/home/vboxuser/InstaPy"

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

INFO [2023-04-27 17:03:07] [username]  Session started!

oooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2023-04-27 17:03:14] [username]  - Cookie file for user 'username' loaded...

..................................................................

INFO [2023-04-27 17:03:40] [username]  Logged in successfully!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2023-04-27 17:03:40] [username]  Saving account progress...

WARNING [2023-04-27 17:03:43] [username]  Unable to save account progress, skipping data update 

	b"invalid literal for int() with base 10: '7\\nfollowers'"



INFO [2023-04-27 17:03:43] [username]  Sessional Live Report:

	|> No any statistics to show





[Session lasted 39.51 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

INFO [2023-04-27 17:03:43] [username]  Session ended!

ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo







Traceback (most recent call last):

  File "/home/vboxuser/Downloads/instapy-quickstart/quickstart.py", line 27, in <module>

    with smart_run(session):

  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__

    return next(self.gen)

  File "/home/vboxuser/.local/lib/python3.10/site-packages/instapy/util.py", line 1983, in smart_run

    session.login()

  File "/home/vboxuser/.local/lib/python3.10/site-packages/instapy/instapy.py", line 475, in login

    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)

  File "/home/vboxuser/.local/lib/python3.10/site-packages/instapy/print_log_writer.py", line 21, in log_follower_num

    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)

  File "/home/vboxuser/.local/lib/python3.10/site-packages/instapy/util.py", line 501, in getUserData

    get_key = shared_data.get("entry_data").get("ProfilePage")

AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by sekoakb** [comment]
exactly same issue, any1 have progress?
