### ISSUE TITLE
Unable to save account progress, skipping data update: b"invalid literal for int() with base 10: '7\\nfollowers'"

### ISSUE THREAD

**Issue by FreedomLabsIO** [InstaPy/InstaPy#6704]
```
InstaPy Version: 0.6.16

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 

Workspace in use: "/home/vboxuser/InstaPy"

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

INFO [2023-04-27 17:03:07] [username]  Session started!

oooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2023-04-27 17:03:14] [username]  - Cookie file for user 'username' loaded...

..................................................................

INFO [2023-04-27 17:03:40] [username]  Logged in successfully!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2023-04-27 17:03:40] [username]  Saving account progress...

WARNING [2023-04-27 17:03:43] [username]  Unable to save account progress, skipping data update 

	b"invalid literal for int() with base 10: '7\\nfollowers'"



INFO [2023-04-27 17:03:43] [username]  Sessional Live Report:

	|> No any statistics to show





[Session lasted 39.51 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

INFO [2023-04-27 17:03:43] [username]  Session ended!

ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo







Traceback (most recent call last):

  File "/home/vboxuser/Downloads/instapy-quickstart/quickstart.py", line 27, in <module>

    with smart_run(session):

  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__

    return next(self.gen)

  File "/home/vboxuser/.local/lib/python3.10/site-packages/instapy/util.py", line 1983, in smart_run

    session.login()

  File "/home/vboxuser/.local/lib/python3.10/site-packages/instapy/instapy.py", line 475, in login

    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)

  File "/home/vboxuser/.local/lib/python3.10/site-packages/instapy/print_log_writer.py", line 21, in log_follower_num

    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)

  File "/home/vboxuser/.local/lib/python3.10/site-packages/instapy/util.py", line 501, in getUserData

    get_key = shared_data.get("entry_data").get("ProfilePage")

AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by TomiLikesToCode** [comment]
same

**Comment by TomiLikesToCode** [comment]
Maybe something to do with "7\\nfollowers" not being an integer

**Comment by systenconti** [comment]
I've got the same issue, but this problem was already discussed in here #6615. It seems that the project is just dead, because noone has answered how to fix it since 2022

**Comment by fincha** [comment]
```
followers_count = format_number(
                browser.find_element(
                    By.XPATH,
                    str(
                        read_xpath(get_relationship_counts.__name__, "followers_count")
                    ),
                ).text
            )
```

you need to add `.replace("\nfollowers", '')` after `.text` down the script also change this too

```
.replace("\nfollowing", '')
```

but... there are other issues :(
