### ISSUE TITLE
Index Error 

### ISSUE THREAD

**Issue by TBrannan** [InstaPy/InstaPy#671]
When trying to Follow users followers I get this index error

```
Traceback (most recent call last):

  File "example.py", line 18, in <module>

    session.follow_user_followers(['timanderic', 'SuperDeluxe'], amount=10, random=False, sleep_delay=0)

  File "/Users/Travis/Documents/GitHub/InstaPy/instapy/instapy.py", line 902, in follow_user_followers

    userFollowed += follow_given_user_followers(self.browser, user, amount, self.dont_include, self.username, self.follow_restrict, random, sleep_delay)

  File "/Users/Travis/Documents/GitHub/InstaPy/instapy/unfollow_util.py", line 435, in follow_given_user_followers

    personFollowed = follow_through_dialog(browser, user_name, amount, dont_include, login, follow_restrict, allfollowing, random, delay, callbacks=[])

  File "/Users/Travis/Documents/GitHub/InstaPy/instapy/unfollow_util.py", line 255, in follow_through_dialog

    .find_elements_by_tag_name("a")[1].text)

IndexError: list index out of range
```

**Comment by dominicwhyte** [comment]
Also having this issue

**Comment by dominicwhyte** [comment]
Is anyone working on this?

**Comment by Pormientras** [comment]
Same thing for me

**Comment by julianNNss** [comment]
I have the same problem

**Comment by timgrossmann** [comment]
Please Pull and try again.
