### ISSUE TITLE
MacOS can't find Python but it's installed

### ISSUE THREAD

**Issue by alexis3290** [InstaPy/InstaPy#6712]
Hello I'm facing an issue on the latest version of MacOs (Ventura 13.2.1).

When I run the install.command i have this error line 3: [: !=: unary operator expected
I've installe Python 3 package from the Python website.

If I do a $ python --version 
_zsh: command not found: python_

But if do a $ python3 --version 
Terminal said that python 3.11.3 is installed … 

I'm a little bit lost 😅

**Comment by alexis3290** [comment]
I by-pass the install by using python3 instead of python in the command files.
But now when I run the quickstart.py I have this error 

```python
myusername@Users-MacBook-Air instapy-quickstart-master % python3 quickstart.py
Traceback (most recent call last):
  File "/Users/myusername/Desktop/instapy-quickstart-master/quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/opt/homebrew/lib/python3.11/site-packages/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/opt/homebrew/lib/python3.11/site-packages/instapy/instapy.py", line 35, in <module>
    from .clarifai_util import check_image
  File "/opt/homebrew/lib/python3.11/site-packages/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Workflow
ModuleNotFoundError: No module named 'clarifai.rest'
myusername@Users-MacBook-Air instapy-quickstart-master % 
```
