### ISSUE TITLE
ValueError: Timeout value connect was <object object at 0x0000022FB2B146C0>

### ISSUE THREAD

**Issue by khansaad1275** [InstaPy/InstaPy#6728]
## Current Behavior
PS E:\Python Code\Automation\instapy-quickstart-master\instapy-quickstart-master\quickstart_templates> python .\like_by_tag_interact_unfollow.py
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/khans/InstaPy"
Traceback (most recent call last):
  File "E:\Python Code\Automation\instapy-quickstart-master\instapy-quickstart-master\quickstart_templates\like_by_tag_interact_unfollow.py", line 38, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\_request_methods.py", line 118, in request
    return self.request_encode_body(
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\_request_methods.py", line 217, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 432, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 328, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 351, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 265, in _new_pool
    return pool_cls(host, port, **request_context)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 196, in __init__
    timeout = Timeout.from_float(timeout)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\timeout.py", line 190, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\timeout.py", line 119, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "C:\Users\khans\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\timeout.py", line 156, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x0000022FB2B146C0>, but it must be an int, float or None.

**Comment by lukesikora** [comment]
In line 38, place your instagram username in `for session = InstaPy(username="insta_username"`

**Comment by drprolegend** [comment]
> In line 38, place your instagram username in `for session = InstaPy(username="insta_username"`

same problem. your solution doesn't work. The browser can't even open

**Comment by KoreaFritz** [comment]
same error

**Comment by soulduse** [comment]
same too

**Comment by xoco70** [comment]
same
