### ISSUE TITLE
Not able to run nogui=True

### ISSUE THREAD

**Issue by AlbertoGnz** [InstaPy/InstaPy#673]
Hi, I need help, when trying to run nogui=True i get an error.

Im testing in localhost because I would like to run it in AWS but i couldnt because of this error.

How can I solve it?

Traceback (most recent call last):
  File "C:\Users\Portatil Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\easyprocess\__init__.py", line 225, in start
    env=self.env,
  File "C:\Users\Portatil Casa\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Portatil Casa\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Portatil Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\easyprocess\__init__.py", line 178, in check_installed
    self.call()
  File "C:\Users\Portatil Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\easyprocess\__init__.py", line 194, in call
    self.start().wait(timeout=timeout)
  File "C:\Users\Portatil Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\easyprocess\__init__.py", line 230, in start
    raise EasyProcessError(self, 'start error')
easyprocess.EasyProcessError: start error <EasyProcess cmd_param=['Xvfb', '-help'] cmd=['Xvfb', '-help'] oserror=[WinError 2] El sistema no puede encontrar el archivo especificado return_code=None stdout="None" stderr="None" timeout_happened=False>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Portatil Casa\Desktop\automatizacion\tomahawk\example.py", line 5, in <module>
    session = InstaPy(username=----------', password='--------, nogui=True)
  File "C:\Users\Portatil Casa\Desktop\automatizacion\tomahawk\instapy\instapy.py", line 48, in __init__
    self.display = Display(visible=0, size=(800, 600))
  File "C:\Users\Portatil Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyvirtualdisplay\display.py", line 34, in __init__
    self._obj = self.display_class(
  File "C:\Users\Portatil Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyvirtualdisplay\display.py", line 52, in display_class
    cls.check_installed()
  File "C:\Users\Portatil Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyvirtualdisplay\xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "C:\Users\Portatil Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\easyprocess\__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[WinError 2] El sistema no puede encontrar el archivo especificado
Program install error! 
>>> 
![captura](https://user-images.githubusercontent.com/32103160/30600073-bffbc21a-9d5e-11e7-9729-0c46216cb07e.JPG)

**Comment by Unreal89** [comment]
Check which version of python you have installed, I don't remember if the 2.x or the 3.x  is somehow provoking this issue.

**Comment by AlbertoGnz** [comment]
![captura](https://user-images.githubusercontent.com/32103160/30691221-5c1650ca-9ec7-11e7-89ba-4a99742107e8.JPG)
Same error with 2.7 and 3.x

**Comment by AlbertoGnz** [comment]
Could someone, who got it working, tell me how does it run?

**Comment by staringispolite** [comment]
Getting this error too, on both Python 2 and 3.

I'll update if I get anywhere. This may be a clue: https://stackoverflow.com/questions/32173839/easyprocess-easyprocesscheckinstallederror-cmd-xvfb-help-oserror-errno

**Comment by staringispolite** [comment]
So, the root exception in this stack trace is the shell not finding Xvfb (X virtual frame buffer) for headless operation, because OS X doesn't use X anymore. Do a 
`> Xvfb` 
to see if your system has Xvfb. If you get `command not found` then you may have the same problem I did.

installing [XQuartz](https://www.xquartz.org/) (which comes with Xvfb) worked for me on OS X 10.11. 
If you already have Xvfb installed, it may just not be in your path

**Comment by converge** [comment]
hey @alberto11651 , did you solve this issue ?

**Comment by AlbertoGnz** [comment]
Unfortunately I gave up :(

**Comment by converge** [comment]
@alberto11651 you just need to setup ```nogui=False```

did it fix the issue ?

**Comment by staringispolite** [comment]
@converge No, check out the stack trace, he already used nogui=True, and it’s saying the code can’t find Xvfb. He had the same problem as I did. 

@alberto11651 I included instructions for a fix above, if you want to try again

**Comment by converge** [comment]
hi @staringispolite , nogui=True means the system will try to use a framebuffer to do it, as Windows doesn't have it, it will throw this error. As I said before ```nogui=False``` means: don't use xvfb

**Comment by staringispolite** [comment]
Oh you’re right, Xvfb doesn’t have a build for Windows! Did you try
anything like Docker or a virtual machine to get a Linux or Mac environment?

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
