### ISSUE TITLE
InstaPy Issue 

### ISSUE THREAD

**Issue by xsm99** [InstaPy/InstaPy#6749]
CODE:
 from instapy import InstaPy
from instapy import smart_run

my_username = 'myusername'
my_password = 'mypass.'

session = InstaPy(username = my_username,
                  password = my_password,
                  headless_browser = False)

with smart_run(session):
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_number=True,
                                    max_followers=500,
                                    min_followers=30,
                                    min_following=50)
    
    session.set_do_follow(True, percentage=100)
    session.set_dont_like(['nsfw', 'kia', 'ford'])

    session.like_by_tags(['bmw', 'mercedes'], amount=10)

ERROR WHEN RUN: 

Workspace in use: "C:/Users/gamin/InstaPy"
Traceback (most recent call last):
  File "C:\Users\gamin\OneDrive\Desktop\InstagramBot\instagram.py", line 7, in <module>
    session = InstaPy(username = my_username,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gamin\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gamin\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
              ^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got an unexpected keyword argument 'firefox_profile'
PS C:\Users\gamin\OneDrive\Desktop\InstagramBot>

How to fix this ?

**Comment by KoreaFritz** [comment]
TypeError: __init__() got an unexpected keyword argument 'firefox_profile'
PS C:\Users\XXX\Downloads\instapy-quickstart-master>

I have the same issue?

**Comment by mirimera** [comment]
My Data
