### ISSUE TITLE
selenium, firefox error

### ISSUE THREAD

**Issue by ThePilotDev** [InstaPy/InstaPy#6753]
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/ConpriDev/InstaPy"
Error, unable to find a download for os: win
Traceback (most recent call last):
  File "C:\Users\ConpriDev\Documents\insta_bot\instagram.py", line 11, in <module>
    session = InstaPy(username=insta_username,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ConpriDev\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ConpriDev\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
                                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\ConpriDev\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ConpriDev\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ConpriDev\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ConpriDev\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 318, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to find a download for os: win

I've been trying everything

**Comment by albertoleandrosanchez** [comment]
![Captura](https://github.com/InstaPy/InstaPy/assets/52971416/5d42b4a8-bc90-4c20-b9cd-36e6a7f357c9)
Hi @ConpricookDev you have to put the geckodriver.exe in the main folder and that problem dissapear

**Comment by natschoes** [comment]
> ![Captura](https://private-user-images.githubusercontent.com/52971416/273070332-5d42b4a8-bc90-4c20-b9cd-36e6a7f357c9.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTI5NDgsIm5iZiI6MTcwNDMxMjY0OCwicGF0aCI6Ii81Mjk3MTQxNi8yNzMwNzAzMzItNWQ0MmI0YTgtYmM5MC00YzIwLWI5Y2QtMzZlNmE3ZjM1N2M5LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDIwMTA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZmE4M2E4MjM3YzdiM2NjYzQyYjE4YTFkMTIwMTRkMjFhZTA5ODY2ODYyMWYyZmVhN2Q1YTI0Y2U2ZTEyYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GHmxuMtwZk76GICoLDtbCPzMSNaJSgDlVGFPysvtGlo) Hi @ConpricookDev you have to put the geckodriver.exe in the main folder and that problem dissapear

Hi this doesnt work for me.. I have a similar error. Do you have any other solution?

**Comment by tomcloud0** [comment]
pip install selenium==3.141.0 

still getting errors but downgrading selenium fixed that one at least...

**Comment by ikrambaloch** [comment]
How to hack Instagram
