### ISSUE TITLE
InstaPy not working help pls

### ISSUE THREAD

**Issue by xympyo** [InstaPy/InstaPy#6758]
Traceback (most recent call last):
  File "D:\PersonalStudy\Automation\HopefullyAdvancedInstaBot\bot.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\instapy.py", line 35, in <module>
    from .clarifai_util import check_image
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Workflow
ModuleNotFoundError: No module named 'clarifai.rest'

**Comment by ElenaPT** [comment]
It is apparently an issue with the version of the package. Uninstall and install a compatible version:
```
pip uninstall clarifai
pip install clarifai==2.6.2
```

**Comment by xympyo** [comment]
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/xynpy/InstaPy"
Traceback (most recent call last):
  File "D:\PersonalStudy\Automation\instapyAPI Bot\bot.py", line 7, in <module>
    session = InstaPy(username=my_username, password=my_password, headless_browser=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
              ^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got an unexpected keyword argument 'firefox_profile'

it gives this error now.., I already made FireFox into my Default Browser too

**Comment by ElenaPT** [comment]
I believe this is also an issue with version compatibility, only this time with the version of selenium. So it would be the same idea:
```
pip uninstall selenium
pip install selenium==3.141
```

**Comment by xympyo** [comment]
um now it gives a more long error

Traceback (most recent call last):
  File "D:\PersonalStudy\Automation\instapyAPI Bot\bot.py", line 7, in <module>
    session = InstaPy(username=my_username, password=my_password, headless_browser=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 118, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 217, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 432, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 328, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 351, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 265, in _new_pool
    return pool_cls(host, port, **request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 196, in __init__
    timeout = Timeout.from_float(timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\timeout.py", line 190, in from_float
    return Timeout(read=timeout, connect=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\timeout.py", line 119, in __init__
    self._connect = self._validate_timeout(connect, "connect")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xynpy\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\timeout.py", line 156, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x00000227C41044A0>, but it must be an int, float or None.

**Comment by ElenaPT** [comment]
It seems like this time the error is related to urllib3. However, I don't know how this one could be solved, I'm sorry.

Maybe you colud try the same thing as in the other cases, using a compatible version (1.24.1, according to [InstaPy's requirements](https://github.com/InstaPy/InstaPy/blob/master/requirements.txt)) But I don't know if it it will solve the problem in this instance.

**Comment by ealvesss** [comment]
This project still alive?
