### ISSUE TITLE
ModuleNotFound error while installing

### ISSUE THREAD

**Issue by esiruchek** [InstaPy/InstaPy#6774]
Per the title, upon installing instapy in the command module, the error below is presented:

```
Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    import instapy
  File "C:\Users\Esiru\AppData\Local\Programs\Python\Python310\lib\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\Esiru\AppData\Local\Programs\Python\Python310\lib\instapy\instapy.py", line 34, in <module>
    from .browser import close_browser, set_selenium_local_session
  File "C:\Users\Esiru\AppData\Local\Programs\Python\Python310\lib\instapy\browser.py", line 11, in <module>
    from webdriverdownloader import GeckoDriverDownloader
ModuleNotFoundError: No module named 'webdriverdownloader'
```

**Comment by capak07** [comment]
@esiruchek try manually downloading the modeule
`pip install webdriverdownloader`
