### ISSUE TITLE
Termux error "idk help pls"

### ISSUE THREAD

**Issue by TrustForFree** [InstaPy/InstaPy#6776]
pip3 install instapy
Collecting instapy
  Using cached instapy-0.6.16-py2.py3-none-any.whl (246 kB)
Requirement already satisfied: certifi>=2018.10.15 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from instapy) (2023.7.22)
Collecting chardet<4,>=3.0.4 (from instapy)
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting clarifai>=2.4.1 (from instapy)
  Using cached clarifai-9.10.0-py3-none-any.whl.metadata (11 kB)
Collecting configparser<4,>=3.5.0 (from instapy)
  Using cached configparser-3.8.1-py2.py3-none-any.whl (22 kB)
Collecting EasyProcess>=0.2.3 (from instapy)
  Using cached EasyProcess-1.1-py3-none-any.whl (8.7 kB)
Requirement already satisfied: emoji>=0.5.1 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from instapy) (1.6.1)
Collecting future>=0.17.1 (from instapy)
  Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py) ... done
Collecting grpcio>=1.16.1 (from instapy)
  Using cached grpcio-1.59.2.tar.gz (24.8 MB)
  Preparing metadata (setup.py) ... done
Collecting idna<3,>=2.7 (from instapy)
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting jsonschema<3,>=2.6.0 (from instapy)
  Using cached jsonschema-2.6.0-py2.py3-none-any.whl (39 kB)
Collecting MeaningCloud-python>=1.1.1 (from instapy)
  Using cached MeaningCloud_python-2.0.0-py2.py3-none-any.whl (21 kB)
Collecting plyer>=1.3.1 (from instapy)
  Using cached plyer-2.1.0-py2.py3-none-any.whl (142 kB)
Collecting protobuf<4,>=3.6.1 (from instapy)
  Using cached protobuf-3.20.3-py2.py3-none-any.whl (162 kB)
Requirement already satisfied: PyYAML>=3.13 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from instapy) (5.4.1)
Collecting regex>=2018.11.22 (from instapy)
  Using cached regex-2023.10.3.tar.gz (394 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests>=2.20.1 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from instapy) (2.27.1)
Collecting selenium>=3.141.0 (from instapy)
  Using cached selenium-4.15.2-py3-none-any.whl.metadata (6.9 kB)
Collecting setuptools-rust>=0.11.6 (from instapy)
  Using cached setuptools_rust-1.8.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: six>=1.11.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from instapy) (1.16.0)
Requirement already satisfied: urllib3>=1.24.1 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from instapy) (1.26.7)
Collecting webdriverdownloader>=1.1.0.3 (from instapy)
  Using cached webdriverdownloader-1.1.0.3-py2.py3-none-any.whl (10 kB)
Collecting api-display-purposes>=0.0.3 (from instapy)
  Using cached api_display_purposes-0.0.3-py3-none-any.whl (4.7 kB)
Collecting python-telegram-bot>=12.0.0 (from instapy)
  Using cached python_telegram_bot-20.6-py3-none-any.whl.metadata (15 kB)
Collecting PyVirtualDisplay>=0.2.1 (from instapy)
  Using cached PyVirtualDisplay-3.0-py3-none-any.whl (15 kB)
Collecting clarifai-grpc==9.10.0 (from clarifai>=2.4.1->instapy)
  Using cached clarifai_grpc-9.10.0-py3-none-any.whl.metadata (4.1 kB)
Collecting pandas==1.3.5 (from clarifai>=2.4.1->instapy)
  Using cached pandas-1.3.5.tar.gz (4.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [246 lines of output]
      Collecting setuptools>=51.0.0
        Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Using cached wheel-0.41.3-py3-none-any.whl.metadata (2.2 kB)
      Collecting Cython<3,>=0.29.24
        Using cached Cython-0.29.36-py2.py3-none-any.whl.metadata (3.1 kB)
      Collecting oldest-supported-numpy>=0.10
        Using cached oldest_supported_numpy-2023.10.25-py3-none-any.whl.metadata (9.8 kB)
      Collecting numpy==1.23.2 (from oldest-supported-numpy>=0.10)
        Using cached numpy-1.23.2.tar.gz (10.7 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
      Using cached wheel-0.41.3-py3-none-any.whl (65 kB)
      Using cached Cython-0.29.36-py2.py3-none-any.whl (988 kB)
      Using cached oldest_supported_numpy-2023.10.25-py3-none-any.whl (4.9 kB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (pyproject.toml): started
        Building wheel for numpy (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for numpy (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [212 lines of output]
            setup.py:71: RuntimeWarning: NumPy 1.23.2 may not yet support Python 3.11.
              warnings.warn(
            Running from numpy source directory.
            setup.py:86: DeprecationWarning:

              `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
              of the deprecation of `distutils` itself. It will be removed for
              Python >= 3.12. For older Python versions it will remain present.
              It is recommended to use `setuptools < 60.0` for those Python versions.
              For more details, see:
                https://numpy.org/devdocs/reference/distutils_status_migration.html

              import numpy.distutils.command.sdist
            Processing numpy/random/_bounded_integers.pxd.in
            Processing numpy/random/_bounded_integers.pyx.in
            Processing numpy/random/_common.pyx
            Processing numpy/random/_generator.pyx
            Processing numpy/random/_mt19937.pyx
            Processing numpy/random/_pcg64.pyx
            Processing numpy/random/_philox.pyx
            Processing numpy/random/_sfc64.pyx
            Processing numpy/random/bit_generator.pyx
            Processing numpy/random/mtrand.pyx
            Cythonizing sources
            INFO: blas_opt_info:
            INFO: blas_armpl_info:
            INFO: customize UnixCCompiler
            INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blas_mkl_info:
            INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blis_info:
            INFO:   libraries blis not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_info:
            INFO: C compiler: aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC

            creating /data/data/com.termux/files/usr/tmp/tmpp0rsv1ge/data
            creating /data/data/com.termux/files/usr/tmp/tmpp0rsv1ge/data/data
            creating /data/data/com.termux/files/usr/tmp/tmpp0rsv1ge/data/data/com.termux
            creating /data/data/com.termux/files/usr/tmp/tmpp0rsv1ge/data/data/com.termux/files
            creating /data/data/com.termux/files/usr/tmp/tmpp0rsv1ge/data/data/com.termux/files/usr
            creating /data/data/com.termux/files/usr/tmp/tmpp0rsv1ge/data/data/com.termux/files/usr/tmp
            creating /data/data/com.termux/files/usr/tmp/tmpp0rsv1ge/data/data/com.termux/files/usr/tmp/tmpp0rsv1ge
            INFO: compile options: '-c'
            INFO: aarch64-linux-android-clang: /data/data/com.termux/files/usr/tmp/tmpp0rsv1ge/source.c
            INFO: aarch64-linux-android-clang /data/data/com.termux/files/usr/tmp/tmpp0rsv1ge/data/data/com.termux/files/usr/tmp/tmpp0rsv1ge/source.o -L/data/data/com.termux/files/usr/lib -lopenblas -o /data/data/com.termux/files/usr/tmp/tmpp0rsv1ge/a.out
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            non-existing path in 'numpy/distutils': 'site.cfg'
            INFO: lapack_opt_info:
            INFO: lapack_armpl_info:
            INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: lapack_mkl_info:
            INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_lapack_info:
            INFO: C compiler: aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC

            creating /data/data/com.termux/files/usr/tmp/tmp1zbzdgnj/data
            creating /data/data/com.termux/files/usr/tmp/tmp1zbzdgnj/data/data
            creating /data/data/com.termux/files/usr/tmp/tmp1zbzdgnj/data/data/com.termux
            creating /data/data/com.termux/files/usr/tmp/tmp1zbzdgnj/data/data/com.termux/files
            creating /data/data/com.termux/files/usr/tmp/tmp1zbzdgnj/data/data/com.termux/files/usr
            creating /data/data/com.termux/files/usr/tmp/tmp1zbzdgnj/data/data/com.termux/files/usr/tmp
            creating /data/data/com.termux/files/usr/tmp/tmp1zbzdgnj/data/data/com.termux/files/usr/tmp/tmp1zbzdgnj
            INFO: compile options: '-c'
            INFO: aarch64-linux-android-clang: /data/data/com.termux/files/usr/tmp/tmp1zbzdgnj/source.c
            INFO: aarch64-linux-android-clang /data/data/com.termux/files/usr/tmp/tmp1zbzdgnj/data/data/com.termux/files/usr/tmp/tmp1zbzdgnj/source.o -L/data/data/com.termux/files/usr/lib -lopenblas -o /data/data/com.termux/files/usr/tmp/tmp1zbzdgnj/a.out
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            Warning: attempted relative import with no known parent package
            /data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running bdist_wheel
            running build
            running config_cc
            INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            INFO: build_src
            INFO: building py_modules sources
            creating build
            creating build/src.linux-aarch64-3.11
            creating build/src.linux-aarch64-3.11/numpy
            creating build/src.linux-aarch64-3.11/numpy/distutils
            INFO: building library "npymath" sources
            WARN: Could not locate executable armflang
            WARN: Could not locate executable gfortran
            WARN: Could not locate executable f95
            WARN: Could not locate executable ifort
            WARN: Could not locate executable ifc
            WARN: Could not locate executable lf95
            WARN: Could not locate executable pgfortran
            WARN: Could not locate executable nvfortran
            WARN: Could not locate executable f90
            WARN: Could not locate executable f77
            WARN: Could not locate executable fort
            WARN: Could not locate executable efort
            WARN: Could not locate executable efc
            WARN: Could not locate executable g77
            WARN: Could not locate executable g95
            WARN: Could not locate executable pathf95
            WARN: Could not locate executable nagfor
            WARN: Could not locate executable frt
            WARN: don't know how to compile Fortran code on platform 'posix'
            creating build/src.linux-aarch64-3.11/numpy/core
            creating build/src.linux-aarch64-3.11/numpy/core/src
            creating build/src.linux-aarch64-3.11/numpy/core/src/npymath
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_internal.h
            INFO:   adding 'build/src.linux-aarch64-3.11/numpy/core/src/npymath' to include_dirs.
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/ieee754.c
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_complex.c
            INFO: None - nothing done with h_files = ['build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_internal.h']
            INFO: building library "npyrandom" sources
            INFO: building extension "numpy.core._multiarray_tests" sources
            creating build/src.linux-aarch64-3.11/numpy/core/src/multiarray
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/multiarray/_multiarray_tests.c
            INFO: building extension "numpy.core._multiarray_umath" sources
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 230, in build_wheel
                return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
                self.run_setup()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 268, in run_setup
                self).run_setup(setup_script=setup_script)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 158, in run_setup
                exec(compile(code, __file__, 'exec'), locals())
              File "setup.py", line 493, in <module>
                setup_package()
              File "setup.py", line 485, in setup_package
                setup(**metadata)
              File "/data/data/com.termux/files/usr/tmp/pip-install-izl3ge9e/numpy_56d44ebac564424db15459b1a5fa4463/numpy/distutils/core.py", line 169, in setup
                return old_setup(**new_attr)
                       ^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 153, in setup
                return distutils.core.setup(**attrs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 148, in setup
                dist.run_commands()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
                self.run_command(cmd)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 299, in run
                self.run_command('build')
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-install-izl3ge9e/numpy_56d44ebac564424db15459b1a5fa4463/numpy/distutils/command/build.py", line 62, in run
                old_build.run(self)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
                self.run_command(cmd_name)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-oz23g464/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-install-izl3ge9e/numpy_56d44ebac564424db15459b1a5fa4463/numpy/distutils/command/build_src.py", line 144, in run
                self.build_sources()
              File "/data/data/com.termux/files/usr/tmp/pip-install-izl3ge9e/numpy_56d44ebac564424db15459b1a5fa4463/numpy/distutils/command/build_src.py", line 161, in build_sources
                self.build_extension_sources(ext)
              File "/data/data/com.termux/files/usr/tmp/pip-install-izl3ge9e/numpy_56d44ebac564424db15459b1a5fa4463/numpy/distutils/command/build_src.py", line 318, in build_extension_sources
                sources = self.generate_sources(sources, ext)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-install-izl3ge9e/numpy_56d44ebac564424db15459b1a5fa4463/numpy/distutils/command/build_src.py", line 378, in generate_sources
                source = func(extension, build_dir)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-install-izl3ge9e/numpy_56d44ebac564424db15459b1a5fa4463/numpy/core/setup.py", line 513, in generate_config_h
                check_math_capabilities(config_cmd, ext, moredefs, mathlibs)
              File "/data/data/com.termux/files/usr/tmp/pip-install-izl3ge9e/numpy_56d44ebac564424db15459b1a5fa4463/numpy/core/setup.py", line 176, in check_math_capabilities
                raise SystemError("One of the required function to build numpy is not"
            SystemError: One of the required function to build numpy is not available (the list is ['sin', 'cos', 'tan', 'sinh', 'cosh', 'tanh', 'fabs', 'floor', 'ceil', 'sqrt', 'log10', 'log', 'exp', 'asin', 'acos', 'atan', 'fmod', 'modf', 'frexp', 'ldexp']).
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by jinix6** [comment]
Same error Bro 😢
