### ISSUE TITLE
Problem with running instapy for the first time, please help

### ISSUE THREAD

**Issue by gnyolmen** [InstaPy/InstaPy#6777]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\InstaGrowth\main.py", line 3, in <module>
    from instapy import InstaPy
  File "C:\Users\User\PycharmProjects\InstaGrowth\venv\Lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\User\PycharmProjects\InstaGrowth\venv\Lib\site-packages\instapy\instapy.py", line 34, in <module>
    from .browser import close_browser, set_selenium_local_session
  File "C:\Users\User\PycharmProjects\InstaGrowth\venv\Lib\site-packages\instapy\browser.py", line 14, in <module>
    from .util import interruption_handler
  File "C:\Users\User\PycharmProjects\InstaGrowth\venv\Lib\site-packages\instapy\util.py", line 27, in <module>
    from emoji.unicode_codes import UNICODE_EMOJI
ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji.unicode_codes' (C:\Users\User\PycharmProjects\InstaGrowth\venv\Lib\site-packages\emoji\unicode_codes\__init__.py)

Everything is installed as in video guide, tried to install different versions of selenium and instapy itself. using python 3.12 help

**Comment by seyhak** [comment]
Yep its dead, requirements are broken

**Comment by seboliver16** [comment]
so instapy cant be used? or is there a work around?
