### ISSUE TITLE
    import imp ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by cloudglides** [InstaPy/InstaPy#6790]
from instapy import InstaPy 
  
session = InstaPy(username="user",password="pass") 
session.login()

this code provides with error

$ C:/Users/DELL/AppData/Local/Programs/Python/Python312/python.exe c:/Users/DELL/python/insta.py
Traceback (most recent call last):
  File "c:\Users\DELL\python\insta.py", line 1, in <module>
    from instapy import InstaPy
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\instapy\__init__.py", line 6, in <module>        
    from .instapy import InstaPy
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\instapy\instapy.py", line 21, in <module>        
    from .clarifai_util import check_image
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\instapy\clarifai_util.py", line 3, in <module>   
    from clarifai.rest import ClarifaiApp
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\clarifai\rest\__init__.py", line 3, in <module>  
    from clarifai.rest.client import ApiClient
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\clarifai\rest\client.py", line 22, in <module>   
    from future.moves.urllib.parse import urlparse
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\future\moves\__init__.py", line 5, in <module>   
    from future.standard_library import import_top_level_modules
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\future\standard_library\__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

im using Python 3.12.0

**Comment by CardiganQ** [comment]
我遇到了，直接把代码就完事儿了，
原因：估计你也搜到了，python我这里是3.12的版本，高版本已经不使用imp了，改成了importlib
解决方式：直接找到报错的位置(就是你现在报错的最后一行)，直接把源码改了，改成importlib

**Comment by Authtbh** [comment]
alright thanks
