### ISSUE TITLE
b"invalid literal for int() with base 10: '262\\nfollowers'"

### ISSUE THREAD

**Issue by thegreatref** [InstaPy/InstaPy#6803]
INFO [2024-04-11 19:58:16] [xposemediaza]  Saving account progress...
WARNING [2024-04-11 19:58:20] [xposemediaza]  Unable to save account progress, skipping data update 
        b"invalid literal for int() with base 10: '262\\nfollowers'"
Traceback (most recent call last):
  File "c:\Users\Refentse\Desktop\Work\Xpose\Python\instagage.py", line 4, in <module>
    session.login()
  File "C:\Users\Refentse\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\instapy\instapy.py", line 475, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by jglatts** [comment]
you can wrap the statement in a try\except block to keep your script running: 
```python
        try:
            session = InstaPy(username=username, password=password)
            session.login()
        except AttributeError as e:
            print(e)
```

**Comment by csr13** [comment]
This has to do with the text that it's being obtained, you need to modify source code ... stop using the function `format_number` with the same browser select element, check `utils.py`, you can fix this, but there is another bug later on .. which I am stuck on that is, there is no `window._sharedData` to pull extra profile data, on `getUserData` function, also on `utils.py`

**Comment by jglatts** [comment]
I've had luck with this library [instagrapi](https://github.com/subzeroid/instagrapi) for the common instagram functions. Login, Likes, and Comments are all working. Just be careful as instagram might flag the account.
