### ISSUE TITLE
Beginner needing help

### ISSUE THREAD

**Issue by guggze** [InstaPy/InstaPy#682]
I have tried my best to follow the instructions but cannot seem to complete it. Here is where I am at the moment.

Lukes-MacBook-Pro:Instapy Lukejeal$ python3 quickstart.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: './assets/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password)
  File "/Users/Lukejeal/InstaPy/instapy/instapy.py", line 100, in __init__
    self.set_selenium_local_session()
  File "/Users/Lukejeal/InstaPy/instapy/instapy.py", line 139, in set_selenium_local_session
    self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Lukes-MacBook-Pro:Instapy Lukejeal$

Can someone help me please

**Comment by westondeboer** [comment]
The error is saying that there is no chromedriver.

So you just need to go download the chrome driver at:
https://chromedriver.storage.googleapis.com/2.32/chromedriver_mac64.zip

and then unzip the file and put it into the ./assets/ folder. 

Hope that help!

**Comment by guggze** [comment]
I have put in chromedriver in the assets folder but I still get this response:
Lukes-MBP:InstaPy Lukejeal$ python3 quickstart.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: './assets/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password)
  File "/Users/Lukejeal/InstaPy/instapy/instapy.py", line 100, in __init__
    self.set_selenium_local_session()
  File "/Users/Lukejeal/InstaPy/instapy/instapy.py", line 139, in set_selenium_local_session
    self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Lukes-MBP:InstaPy Lukejeal$ 

![screen shot 2017-09-22 at 08 46 43](https://user-images.githubusercontent.com/32033043/30734803-a33c7896-9f74-11e7-9aad-3cabfc05c5a9.png)

**Comment by guggze** [comment]
So I have got the chromedriver added now thank you but this is what I am getting now when I run quick.py:

Lukes-MBP:InstaPy Lukejeal$ python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 9, in <module>
    session.login()
  File "/Users/Lukejeal/InstaPy/instapy/instapy.py", line 161, in login
    if not login_user(self.browser, self.username, self.password, self.switch_language):
  File "/Users/Lukejeal/InstaPy/instapy/login_util.py", line 28, in login_user
    action = ActionChains(browser).move_to_element(input_username[0]).click().send_keys(username).perform()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    action()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 343, in <lambda>
    Command.SEND_KEYS_TO_ACTIVE_ELEMENT, {'value': keys_to_typing(keys_to_send)}))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/utils.py", line 150, in keys_to_typing
    for i in range(len(val)):
TypeError: object of type 'NoneType' has no len()
Lukes-MBP:InstaPy Lukejeal$ 

Please can someone help

**Comment by tobyf93** [comment]
It can always be tricky installing a project like that.  It is very hard to guarantee that your development environment is going to be exactly the same as mine or someone elses.

If you are having heaps of trouble getting this bot off the ground (like i did) i recommend looking into using [Docker](https://www.docker.com/).  The docker client for Mac OSX is incredibly easy to install and from there you can package the project up in "containers" that ensures the development environment is setup the way it should be, no more, no less.  This is already pretty well described in the [README](https://github.com/timgrossmann/InstaPy#running-with-docker-microservices-manual) but i'm happy to give you further directions if you have trouble.

FYI:  The README recommends running `docker-compose up -d --build`.  This can be confusing for beginners because the `-d` flag detaches the container from the current shell i.e. you don't see any output.  I recommend running docker-compose without that flag if you want to see your bot in action.

**Comment by converge** [comment]
As there is no interaction for a long time, we are closing this issue. Please, reopen if you need help about this issue.
