### ISSUE TITLE
TypeError: must be str, not NoneType

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#71]
I sometimes get this error:

```
Link: https://www.instagram.com/p/BSvPTpGj7sh/?tagged=minimalism
Traceback (most recent call last):
  File "quickstart.py", line 11, in <module>
    .like_by_tags(['#minimalism', '#minimalistic', '#austria','#germany','#vlbg','#vorarlberg','#architecture','#urban','#bw', '#bw_photography'], amount=5000)\
  File "/Users/UserName/Desktop/InstaPy/InstaPy/instapy/instapy.py", line 224, in like_by_tags
    self.ignore_if_contains, self.username)
  File "/Users/UserName/Desktop/InstaPy/InstaPy/instapy/like_util.py", line 56, in check_link
    print('Description: ' + image_text)
TypeError: must be str, not NoneType
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x10305eeb8>>
Traceback (most recent call last):
  File "/Users/UserName/anaconda/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/service.py", line 163, in __del__
  File "/Users/UserName/anaconda/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/service.py", line 139, in stop
  File "/Users/Tibor/anaconda/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down
```

What would I need to change to keep InstaPy running?

Kind regards

Tibor

**Comment by pekapa** [comment]
Seems like you have an old version, the easiest way to to just update your InstaPy and you should be good to go.

If you want to just fix this one, add

```python
  if image_text is None:
    image_text = "No description"
```

right before line 56 of `InstaPy/instapy/like_util.py`

**Comment by tibor** [comment]
Okay, thanks!
