### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: Element i s not clickable at point (507, 1664)

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#710]
Windows 7 laptop, chrome.
Happens many times.

```
--> Total liked image reached it's amount given:  2

Username [2/18]
--> 'xxxxx'
Getting  xxxxx image list...
Interaction begin...

Traceback (most recent call last):
  File "C:\instapy\instaPy\InstaPyOffic\quickstart.py", line 24, in <module>
    session.interact_user_followers(userFollowlist, amount=20, random=True)
  File "C:\instapy\instaPy\InstaPyOffic\instapy\instapy.py", line 866, in intera
ct_user_followers
    self.like_by_users(userToInteract, self.user_interact_amount, self.user_inte
ract_random, self.user_interact_media)
  File "C:\instapy\instaPy\InstaPyOffic\instapy\instapy.py", line 585, in like_b
y_users
    links = get_links_for_username(self.browser, username, amount, random, media
)
  File "C:\instapy\instaPy\InstaPyOffic\instapy\like_util.py", line 253, in get_
links_for_username
    load_button.click()
  File "C:\Users\SionC\AppData\Local\Programs\Python\Python36-32\lib\site-packag
es\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\SionC\AppData\Local\Programs\Python\Python36-32\lib\site-packag
es\selenium\webdriver\remote\webelement.py", line 491, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\SionC\AppData\Local\Programs\Python\Python36-32\lib\site-packag
es\selenium\webdriver\remote\webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SionC\AppData\Local\Programs\Python\Python36-32\lib\site-packag
es\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element i
s not clickable at point (507, 1664)
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce
41),platform=Windows NT 6.1.7601 SP1 x86_64)
```

**Comment by sionking** [comment]
We need some mechanisem skipping over errors and continue the run.
There is almost no single run I did without finishing with error.

**Comment by converge** [comment]
you can avoid exceptions in this way. if you have multiple accounts, it's a good ideia.

@timgrossmann what do you think about catch this kind of exception inside bot functions ?

```
from selenium.common.exceptions import WebDriverException

try:
  InstaPy(username='login', password='passwd', nogui=True) \
    .login() \
    .end()
except WebDriverException:
  # do something or skip ->
  pass
```

**Comment by timgrossmann** [comment]
@converge Well, I use this structure to make sure that chrome and the xvfb instances are closed when running it on a server and persisting the errors to a logfile.

But I completely agree, we need some error catching inside the tool to make sure that exception pages simply get skipped and avoid the whole bot crashing.
However, someone else has to implement this because I definitely have no time at the moment to keep working on the bot. 
Maybe after the Internship once I'm back at university... 

That's why I'm extremely grateful that the community does so much for this tool, thank you!
