### ISSUE TITLE
Emoji Module

### ISSUE THREAD

**Issue by BuiltOnDevel** [InstaPy/InstaPy#715]
Hey guys, i has a problem with emoji, but i dontknow where stay this module... 

Traceback (most recent call last):
  File "C:\Program Files (x86)\pythonx64\Scripts\InstaPy-master\quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Program Files (x86)\pythonx64\Scripts\InstaPy-master\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\Program Files (x86)\pythonx64\Scripts\InstaPy-master\instapy\instapy.py", line 16, in <module>
    from .comment_util import comment_image
  File "C:\Program Files (x86)\pythonx64\Scripts\InstaPy-master\instapy\comment_util.py", line 10, in <module>
    import emoji
ModuleNotFoundError: No module named 'emoji'

**Comment by BuiltOnDevel** [comment]
i solved that with pip, you need install emoji like selenium.
pip emoji install
