### ISSUE TITLE
browser.find_element_by_xpath

### ISSUE THREAD

**Issue by jeffreylm** [InstaPy/InstaPy#717]
Hello Everyone,

The 

This error started on the 4th of September. I believe Instagram updated the adroid app also on that date.
The screen to unfollow comes up, then it spits out the text below after about 5-10 sec and then quits.
This is the unfollow text in quickstart.py: **session.unfollow_users(amount=1500, onlyInstapyFollowed = False)**

Logged in successfully!
Number of people followed automatically remaining: 11070
Traceback (most recent call last):
  File "quickstart.py", line 19, in <module>
    session.unfollow_users(amount=1500, onlyInstapyFollowed = False)
  File "C:\Users\jeffrey\InstaPy_03okt\instapy\instapy.py", line 961, in unfollow_users
    onlyInstapyMethod, self.automatedFollowedPool)
  File "C:\Users\jeffrey\InstaPy_03okt\instapy\unfollow_util.py", line 111, in unfollow
    dialog = browser.find_element_by_xpath('/html/body/div[4]/div/div[2]/div/div[2]/div/div[2]')
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 832, in find_element
    'value': value})['value']
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[4]/div/div[2]/div/div[2]/div/div[2]"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 10.0.15063 x86_64)

**Comment by randysinnott** [comment]
I can confirm I am experiencing the same thing starting on Sept 4th as well.  This issue seems to break the unfollow functionality -- so I have had to manually disable the follow and unfollow functions temporarily.

**Comment by converge** [comment]
can someone test my fix ? https://github.com/converge/InstaPy/commit/552bd6ea84f54d1e8611ddebeae081bc52f4af6e

**Comment by cagalindo** [comment]
**Fix Unfollow (Working October 8th)** @converge @randysinnott @jeffreylm 
Change line ~110 in "instapy > unfollow_util.py" to:

`# find dialog box
dialog = browser.find_element_by_xpath('/html/body/div[4]/div/div/div[2]/div/div[2]')`

Don't do git so someone else update this

**Comment by converge** [comment]
just made a pull request

**Comment by converge** [comment]
This problem should be fix with the latest version, if you still face this issue, pls reopen it.

**Comment by randysinnott** [comment]
Can verify this has been fixed in latest version.
