### ISSUE TITLE
Message: unknown error: session deleted because of page crash from unknown error: cannot determine loading status

### ISSUE THREAD

**Issue by remorses** [InstaPy/InstaPy#729]
**I am getting this error with every session, I tried on the readme example too.
I should have all ut to date.
My droplet has 1GB Ram.
Here there is the output:**
Logged in successfully!
Tag [1/2]
--> b'#dog'
Traceback (most recent call last):
  File "bot.py", line 14, in <module>
    session.like_by_tags(['#dog', 'cat'], amount=100)
  File "/root/InstaPy/instapy/instapy.py", line 482, in like_by_tags
    links = get_links_for_tag(self.browser, tag, amount, media)
  File "/root/InstaPy/instapy/like_util.py", line 155, in get_links_for_tag
    body_elem.send_keys(Keys.HOME)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=60.0.3112.101)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-87-generic x86_64)

**Comment by Toonix** [comment]
same problem in docker

**Comment by Toonix** [comment]
got it working..had to delete the files under /code/logs except the .json file.
