### ISSUE TITLE
InstaPy  not recognised

### ISSUE THREAD

**Issue by holumiede** [InstaPy/InstaPy#736]
hello

i get this issue when ever i run any of my scripts 

Traceback (most recent call last):
  File "example.py", line 5, in <module>
    session = InstaPy(username='xxx', password='xxx')
NameError: name 'InstaPy' is not defined

**Comment by converge** [comment]
@holumiede copy examples/exemple.py to ../ (home directory of InstaPy)

**Comment by bakerlang** [comment]
@converge thanks i did that but then i got this

Traceback (most recent call last):
  File "/home/bakertech/INSTA/InstaPy/example.py", line 2, in <module>
    from instapy import InstaPy
  File "/home/bakertech/INSTA/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/home/bakertech/INSTA/InstaPy/instapy/instapy.py", line 8, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'

**Comment by converge** [comment]
which python version ? (pip install pyvirtualdisplay or pip3 or pip3.x ...)

**Comment by holumiede** [comment]
After i copy examples/exemple.py to ../ (home directory of InstaPy) this is what i get ( i am running this on Kali by the way)

Traceback (most recent call last):
  File "example.py", line 5, in <module>
    session = InstaPy(username='xxx', password='xxx')
  File "/root/Downloads/InstaPy-master/instapy/instapy.py", line 93, in __init__
    self.set_selenium_local_session()
  File "/root/Downloads/InstaPy-master/instapy/instapy.py", line 132, in set_selenium_local_session
    self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by holumiede** [comment]
i installed chrome and then i got this... plus it opens a chrome tab not sure if its supposed to do so

Traceback (most recent call last):
  File "example.py", line 9, in <module>
    session.login()
  File "/root/Downloads/InstaPy-master/instapy/instapy.py", line 154, in login
    if not login_user(self.browser, self.username, self.password, self.switch_language):
  File "/root/Downloads/InstaPy-master/instapy/login_util.py", line 28, in login_user
    action = ActionChains(browser).move_to_element(input_username[0]).click().send_keys(username).perform()
IndexError: list index out of range

**Comment by converge** [comment]
Make sure to get the right chromedriver for your system [from here](https://sites.google.com/a/chromium.org/chromedriver/downloads). Just put it in /assets.

**Comment by emanuelepasin** [comment]
Hi guys since this morning I have the same error:

```
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 8, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay
```

I've created a new directory for instapy and I start over the installation process.
but I still have that issue.

**Comment by converge** [comment]
@emanuelepasin if you run the script in this way:

```python script_name.py```
do:
```python --version```
if it shows python 3.x:
```pip3 install pyvirtualdisplay```
if it shows python 2.x:
```pip install pyvirtualdisplay```
if pyvirtualdisplay is already installed, try to update it
```pip (or pip3) install -U pyvirtualdisplay```

**Comment by emanuelepasin** [comment]
@converge unfortunately I've already tried:
```

root@ubuntu-1gb-ams2-01:~/InstaPy# python --version
Python 2.7.12
root@ubuntu-1gb-ams2-01:~/InstaPy# pip install pyvirtualdisplay
Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python3.5/dist-packages/PyVirtualDisplay-0.2.1-py3.5.egg
Requirement already satisfied: EasyProcess in /usr/local/lib/python3.5/dist-packages/EasyProcess-0.2.3-py3.5.egg (from pyvirtualdisplay)
root@ubuntu-1gb-ams2-01:~/InstaPy# pip install -U pyvirtualdisplay
Requirement already up-to-date: pyvirtualdisplay in /usr/local/lib/python3.5/dist-packages/PyVirtualDisplay-0.2.1-py3.5.egg
Requirement already up-to-date: EasyProcess in /usr/local/lib/python3.5/dist-packages/EasyProcess-0.2.3-py3.5.egg (from pyvirtualdisplay)
root@ubuntu-1gb-ams2-01:~/InstaPy# python example.py
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 8, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay
```

**Comment by converge** [comment]
@emanuelepasin your pip is setup to use python 3 and your python setup is using python 2.7, you just need to install pyvirtualdisplay to python 2.7

```pip2.7 install pyvirtualdisplay```

**Comment by emanuelepasin** [comment]
@converge It didn't work, so I've created a new server and started over!

**Comment by converge** [comment]
@timgrossmann any idea ?

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.

**Comment by hacksmith-CA** [comment]
hi can anyone help me i am getting this error when i am trying to run this script after inserting my username and password 

`Error, unable to determine correct filename for 64bit linux
Traceback (most recent call last):
  File "/home/suyash/instapy-quickstart/quickstart_templates/basic_follow-unfollow_activity.py", line 30, in <module>
    session = InstaPy(username=insta_username,
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit linux`

can anyone help ?
