### ISSUE TITLE
Orange Pi Prime and Armbian Support 

### ISSUE THREAD

**Issue by phyesix** [InstaPy/InstaPy#756]
Hi all,
Is there orange pi models support? Only Raspberry 3?

**Comment by luisramirezdev** [comment]
Hi, I saw on this official website (http://www.orangepi.org/), that you can install "Android 4.4, Ubuntu, Debian, Raspbian", so you can install **Ubuntu**, **Debian** or **Raspbian**, and it should work, right?

**Comment by phyesix** [comment]
Yes, I use ARMbian (Ubuntu Base) from these operating systems on Orange Pi Prime.  

https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md

I think that the installation can be done through the directives in this address and I install Geckodriver v0.19.1. When i try start with: python3.5 firefoxExample.py, I get an error: 

`root@orangepiprime:~/InstaPy# sudo python3.5 firefoxExample.py
Traceback (most recent call last):
  File "firefoxExample.py", line 18, in <module>
    InstaPy(username='**********', password='**********', use_firefox=True, page_delay=25)\
  File "/root/InstaPy/instapy/instapy.py", line 109, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 134, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 99, in _wait_until_connectable
    "The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.
`

**Comment by Freddan-67** [comment]
I am no expert on armbian, but I think python 3.5 does not work currently on the armbian for orange pi prime. I run in to another but similar problem. I switched to python 2.7 with update-alternatives, following the guide at http://web.mit.edu/6.00/www/handouts/pybuntu.html (but reverse), after that my script worked.
