### ISSUE TITLE
Something broke up

### ISSUE THREAD

**Issue by sakowicz** [InstaPy/InstaPy#80]
Script worked well few days but then it stopped working. I reinstalled it but it didn't help.
Sorry if it's my fault but I will be grateful for help.

```
Traceback (most recent call last):
  File "example2.py", line 2, in <module>
    from instapy import InstaPy
  File "/home/giebeka/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/home/giebeka/InstaPy/instapy/instapy.py", line 11, in <module>
    from .clarifai_util import check_image
  File "/home/giebeka/InstaPy/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.client import ClarifaiApi
  File "build/bdist.linux-x86_64/egg/clarifai/client/__init__.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/clarifai/client/client.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/PIL/Image.py", line 63, in <module>
  File "build/bdist.linux-x86_64/egg/PIL/_imaging.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/PIL/_imaging.py", line 3, in __bootstrap__
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

```

**Comment by timgrossmann** [comment]
@giebeka Could you post your quickstart.py?

**Comment by sakowicz** [comment]
I didn't change quickstart.py. I have just edited login and password. When I do `python quickstart.py`
I've got:
`Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/home/giebeka/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/home/giebeka/InstaPy/instapy/instapy.py", line 11, in <module>
    from .clarifai_util import check_image
  File "/home/giebeka/InstaPy/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.client import ClarifaiApi
  File "build/bdist.linux-x86_64/egg/clarifai/client/__init__.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/clarifai/client/client.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/PIL/Image.py", line 63, in <module>
  File "build/bdist.linux-x86_64/egg/PIL/_imaging.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/PIL/_imaging.py", line 3, in __bootstrap__
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
`

**Comment by timgrossmann** [comment]
@giebeka that's weird...
Did you delete it and cloned it again from github?

**Comment by sakowicz** [comment]
I cloned it again to another location and same error. When I try to install it again this happen:
```
$ sudo curl https://bootstrap.pypa.io/get-pip.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1558k  100 1558k    0     0  9664k      0 --:--:-- --:--:-- --:--:-- 9677k
Traceback (most recent call last):
  File "<stdin>", line 20061, in <module>
  File "<stdin>", line 194, in main
  File "<stdin>", line 119, in bootstrap
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
```


and

```
$ sudo pip install .
Processing /home/giebeka/in/InstaPy
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 417, in run_egg_info
    self.setup_py, self.link,
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

```

It's Centos

I think that there is no issue with InstaPy but with some kind of python configuration, but it's not my cup of tea. Maybe somebody know how to help

**Comment by timgrossmann** [comment]
Did you follow the guide on CentOS?

**Comment by sakowicz** [comment]
Yes, you helped me few days ago. Script was working well since then, today something broke down

**Comment by pekapa** [comment]
Looks like pip/setuptools has broken.
Can you try to install another package and see if it works?

Try force upgrading pip with:

`python -m pip install --upgrade --force pip `

**Comment by sakowicz** [comment]
[This](http://stackoverflow.com/questions/42029545/pip-is-error-typeerror-call-takes-exactly-2-arguments-1-given) helped :)
