### ISSUE TITLE
interact_user_followers error

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#816]
Username [73/1016]
--> b'sxxxka'
Getting  'sxxxkaimage list...
This user is private...

```
Traceback (most recent call last):
  File "C:\instapy\instaPy\InstaPyOffic\quickstartUserFollow.py", line 27, in <m
odule>
    session.interact_user_followers(userFollowlist, amount=1000, random=False)
  File "C:\instapy\instaPy\InstaPyOffic\instapy\instapy.py", line 1082, in inter
act_user_followers
    self.user_interact_media)
  File "C:\instapy\instaPy\InstaPyOffic\instapy\instapy.py", line 744, in like_b
y_users
    self.username, username)
  File "C:\instapy\instaPy\InstaPyOffic\instapy\unfollow_util.py", line 201, in
follow_user
    if follow_button.is_displayed():
  File "C:\Users\SionC\AppData\Local\Programs\Python\Python36-32\lib\site-packag
es\selenium\webdriver\remote\webelement.py", line 358, in is_displayed
    return self._execute(Command.IS_ELEMENT_DISPLAYED)['value']
  File "C:\Users\SionC\AppData\Local\Programs\Python\Python36-32\lib\site-packag
es\selenium\webdriver\remote\webelement.py", line 491, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\SionC\AppData\Local\Programs\Python\Python36-32\lib\site-packag
es\selenium\webdriver\remote\webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SionC\AppData\Local\Programs\Python\Python36-32\lib\site-packag
es\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale elemen
t reference: element is not attached to the page document
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce
41),platform=Windows NT 6.1.7601 SP1 x86_64)

```

**Comment by converge** [comment]
I just sent the #824 PR to fix the #734 bug, and I think it will fix this bug too, can you test it ?
