### ISSUE TITLE
Crashing of script

### ISSUE THREAD

**Issue by wizarduk** [InstaPy/InstaPy#823]
It keeps crashing after 10min whats wrong with this bot ?

Image from: b'diet_memez'
Number of Followers: 337
Link: b'https://www.instagram.com/p/BatoIzWl1dw/?tagged=jokes'
Description: b'Satisfaction \xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2follow @diet_memez for more\n-\n\xe2\x80\xa2follow my main \n@meemester\n\xe2\x80\xa2#funny #lol #lmao #hilarious #humor #love #jokes #fun #nochill #laugh #follow #lmfao #meme #instagood #memes #followme #haha #funnyshit #like4like #music #bruh #niggasbelike #comedian #ctfu #tumblr #repost #movie #\xf0\x9f\x98\x82'
--> Image Liked!
Traceback (most recent call last):
  File "quickstart.py", line 19, in <module>
    session.like_by_tags(['jokes', 'funny', 'lmao', 'jokes', 'lol' ,'laugh' ,'crazy','joking','silly','laughing','epic','lmfao','haha','humor','wacky','hilarious'], amount=50)
  File "/root/InstaPy/instapy/instapy.py", line 614, in like_by_tags
    self.browser, comments)
  File "/root/InstaPy/instapy/comment_util.py", line 25, in comment_image
    comment_input[0].send_keys("\b")
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 320, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': keys_to_typing(value)})
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot focus element
  (Session info: chrome=62.0.3202.62)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 2.6.32-042stab125.3 x86_64)

**Comment by CharlesCCC** [comment]
Staring from yesterday, I'm getting exactly the same error from two different computer i'm using to run the script. (Mac and Windows)

**Comment by timgrossmann** [comment]
#817
