### ISSUE TITLE
Error stopping script

### ISSUE THREAD

**Issue by wizarduk** [InstaPy/InstaPy#832]
I keep getting this error when trying to run script i have done all the fixes and still happens.

arty #fun #pokerfest #casinofigueira #figueiradafoz #pokertime #pokertournament #showtime #pokerlife #pokerlive'
--> Image Liked!
Traceback (most recent call last):
  File "quickcasino.py", line 20, in <module>
    session.like_by_tags(['casino', 'gambling', 'freebets', 'poker', 'roulette' ,'footballbetting' ,'highstakes','lottery','casinoonline','wales','vale','betting','bets','bet','horseracing','gamble'], amount=50)
  File "/root/InstaPy/instapy/instapy.py", line 614, in like_by_tags
    self.browser, comments)
  File "/root/InstaPy/instapy/comment_util.py", line 30, in comment_image
    open_comment_section(browser)
  File "/root/InstaPy/instapy/comment_util.py", line 19, in open_comment_section
    comment_elem[0].click()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <a class="_p6oxf _6p9ga" href="#" role="button">...</a> is not clickable at point (485, 444). Other element would receive the click: <a class="_raoqe coreSpriteGooglePlayButton" href="https://play.google.com/store/apps/details?id=com.instagram.android&amp;referrer=utm_source%3Dinstagramweb%26utm_campaign%3DdesktopAppUpsell%26utm_medium%3DdesktopAppUpsell" target="_blank"></a>
  (Session info: chrome=62.0.3202.62)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 2.6.32-042stab125.3 x86_64)

**Comment by converge** [comment]
hello @wizarduk  , we fixed it today, please update InstaPy and try again. If the problem persists, please reopen this issue.

**Comment by wizarduk** [comment]
@converge thanks, i have done this and it works fine now tested yesterday and didn't get any errors one issue I am having is my cron job doesn't work I have tried this several times and it's not starting or working?
