### ISSUE TITLE
Not sure what's up here

### ISSUE THREAD

**Issue by xstalpha** [InstaPy/InstaPy#846]
python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password, use_firefox=True, nogui=True)
  File "/root/InstaPy/instapy/instapy.py", line 106, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 125, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory

**Comment by converge** [comment]
hey @xstalpha , how is your quickstart.py ?

**Comment by xstalpha** [comment]
it is the default one from the install page, but i added nogui and use_firefox since chromedriver wasnt working

from instapy import InstaPy

insta_username = 'USER'
insta_password = 'PASS'

# if you want to run this script on a server, 
# simply add nogui=True to the InstaPy() constructor
```
session = InstaPy(username=insta_username, password=insta_password, nogui=True, use_firefox=True)
session.login()

# set up all the settings
session.set_upper_follower_count(limit=2500)
session.set_do_comment(True, percentage=10)
session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
session.set_dont_include(['friend1', 'friend2', 'friend3'])
session.set_dont_like(['pizza', 'girl'])

# do the actual liking
session.like_by_tags(['natgeo', 'world'], amount=100)

# end the bot session
session.end()
```
