### ISSUE TITLE
TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'

### ISSUE THREAD

**Issue by adammenges** [InstaPy/InstaPy#847]
## Expected Behavior
Commenting with Emoji works

## Current Behavior
```
Traceback (most recent call last):
  File "bot.py", line 282, in <module>
    .like_by_tags(_tags, amount=amount)\
  File "InstaPy/instapy/instapy.py", line 536, in like_by_tags
    tags = list(map(str.strip, tags))
TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'
```

## InstaPy configuration
```
InstaPy(username='', password='')\
	.login()\
	.set_do_comment(True, percentage=random.randint(10,20))\
	.set_comments(_general_coments)\
	.set_dont_include(friend_list)\
	.set_ignore_if_contains(dont_like)\
	.like_by_tags(_tags, amount=amount)\
	.set_do_follow(enabled=True, percentage=random.randint(5,10), times=1)\
	.end()
```

where `_general_comments` has objects like: `u"👊🏻"`

**Comment by pilotdude** [comment]
@adammenges I think the error is coming from the like_by_tags method.  

Do you have emoji's or unicode objects in "_tags"?

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
