### ISSUE TITLE
Unicode Encode Error?

### ISSUE THREAD

**Issue by sankalpsingha** [InstaPy/InstaPy#87]
After running it successfully, I am getting a UnicodeEncodeError

```
Traceback (most recent call last):                                                                    │23093 root       20   0 1288M  304M  181M S  4.0 30.7  0:15.39 /opt/google/chrome/chrome --type=rende
  File "quickstart.py", line 17, in <module>                                                          │22382 root       20   0  865M 76204 47300 S  2.0  7.5  0:08.23 /opt/google/chrome/chrome --disable-ba
    .like_by_tags(['#dog', '#cat'], amount=100) \                                                     │22635 root       12  -8 1305M  318M  253M S  1.3 32.1  0:04.94 /opt/google/chrome/chrome --type=rende
  File "/root/InstaPy/instapy/instapy.py", line 224, in like_by_tags                                  │22844 root       20   0  788M 77100 48180 S  0.7  7.6  0:04.54 /opt/google/chrome/chrome --disable-ba
    self.ignore_if_contains, self.username)                                                           │22633 root       12  -8 1305M  318M  253M S  0.7 32.1  0:01.70 /opt/google/chrome/chrome --type=rende
  File "/root/InstaPy/instapy/like_util.py", line 67, in check_link                                   │22409 root       20   0  865M 76204 47300 S  0.7  7.5  0:02.12 /opt/google/chrome/chrome --disable-ba
    print('Description: ' + image_text)                                                               │23095 root       12  -8 1288M  304M  181M S  0.7 30.7  0:00.88 /opt/google/chrome/chrome --type=rende
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f60d' in position 482: ordinal not in │23097 root       12  -8 1288M  304M  181M S  0.0 30.7  0:01.58 /opt/google/chrome/chrome --type=rende
range(128)
```

**Comment by timgrossmann** [comment]
Copy of #45

**Comment by hojabbr** [comment]
Just add these lines to `quickstart.py` and `instapy.py`:

```
# -*- coding: UTF-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```
