### ISSUE TITLE
[Help Needed] Facing WindowsError: [Error 32] on all runs - Happens before signing in

### ISSUE THREAD

**Issue by arjunmurali1993** [InstaPy/InstaPy#882]
Hi, I pulled all the latest commits today morning and ever since, I've been facing this error. Looks like it might have something to do with logging or the new blacklist feature.

Traceback (most recent call last):
  File "E:/Documents/Python/InstaPy/arjun.py", line 9, in <module>
    session.login()
  File "E:\Documents\Python\InstaPy\instapy\instapy.py", line 186, in login
    self.switch_language):
  File "E:\Documents\Python\InstaPy\instapy\login_util.py", line 11, in login_user
    update_activity()
  File "E:\Documents\Python\InstaPy\instapy\util.py", line 85, in update_activity
    shutil.move(tmpfile.name, './logs/activity.csv')
  File "C:\Program Files (x86)\Python27\lib\shutil.py", line 317, in move
    os.unlink(src)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\arjun\\appdata\\local\\temp\\tmpeevqiq'

**Comment by converge** [comment]
#873
