### ISSUE TITLE
Instapy keeps crashing after latest update when using interact_user_followers

### ISSUE THREAD

**Issue by keivan85** [InstaPy/InstaPy#900]
I update the chromedriver but no changes.
This is the error and so far it happens when script reaches **private users** . I am using Ubuntu 14.04

This user is private...
Traceback (most recent call last):
  File "quickstart-nora.py", line 25, in <module>
    .interact_user_followers(['account1','account2', 'account3'], amount=27, random=True)\
  File "/home/MY-PC/Documents/InstaPy/instapy/instapy.py", line 1063, in interact_user_followers
    self.user_interact_media)
  File "/home/MY-PC/Documents/InstaPy/instapy/instapy.py", line 722, in like_by_users
    self.blacklist)
  File "/home/MY-PC/Documents/InstaPy/instapy/unfollow_util.py", line 210, in follow_user
    if follow_button.is_displayed():
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 325, in is_displayed
    return self._execute(Command.IS_ELEMENT_DISPLAYED)['value']
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=62.0.3202.89)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.4.0-98-generic x86_64)

And this is my running script

```python
from instapy import InstaPy

insta_username = 'MY USER'
insta_password = 'MY PASS'


InstaPy(username=insta_username, password=insta_password)\
  .login()\
  .set_user_interact(amount=3, random=True, percentage=100, media='Photo')\
  .set_do_like(enabled=True, percentage=100)\
  .set_do_comment(enabled=True, percentage=60)\
  .set_do_follow(enabled=True, percentage=70)\
  .set_comments(['Comment 1', 'comment2', 'comment3'])\
  .interact_user_followers(['account1','account2', 'account3'], amount=27, random=True)\
  .end()
```

**Comment by keivan85** [comment]
I also tried the same script with firefox esr. After 7-8 profiles when it reaches to a private account it throws this error 

This user is private...
Traceback (most recent call last):
  File "firefoxExample.py", line 26, in <module>
    .interact_user_followers(['sarahbtm','chelseaspursuit', 'camilla.law'], amount=27, random=True)\
  File "/home/MY-PC/Documents/InstaPy/instapy/instapy.py", line 1063, in interact_user_followers
    self.user_interact_media)
  File "/home/MY-PC/Documents/InstaPy/instapy/instapy.py", line 722, in like_by_users
    self.blacklist)
  File "/home/MY-PC/Documents/InstaPy/instapy/unfollow_util.py", line 210, in follow_user
    if follow_button.is_displayed():
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 325, in is_displayed
    return self._execute(Command.IS_ELEMENT_DISPLAYED)['value']
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: Element not found in the cache - perhaps the page has changed since it was looked up
Stacktrace:
    at fxdriver.cache.getElementAt (resource://fxdriver/modules/web-element-cache.js:9454)
    at Utils.getElementAt (file:///tmp/tmpxzzwtifn/extensions/fxdriver@googlecode.com/components/command-processor.js:9039)
    at WebElement.isElementDisplayed (file:///tmp/tmpxzzwtifn/extensions/fxdriver@googlecode.com/components/command-processor.js:12189)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmpxzzwtifn/extensions/fxdriver@googlecode.com/components/command-processor.js:12661)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmpxzzwtifn/extensions/fxdriver@googlecode.com/components/command-processor.js:625)

**Comment by datteba** [comment]
Same here

![image](https://user-images.githubusercontent.com/30053143/32720022-98936488-c862-11e7-923f-504d8132cb4f.png)

**Comment by sionking** [comment]
same, you can just ignore the error for now

**Comment by sionking** [comment]
errorSkip = False
		try:
		    follow_button.is_displayed()
		except:
		    errorSkip = True

        if not errorSkip and follow_button.is_displayed():
            follow_button.send_keys("\n")
            update_activity('follows')
        else:

**Comment by johnvfitness** [comment]
Hello
or add this command line please
