### ISSUE TITLE
Quickstart.py fails to start on server.

### ISSUE THREAD

**Issue by thatc0der** [InstaPy/InstaPy#912]
## Expected Behavior
I expect the program to run like it does locally 
## Current Behavior
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password)
  File "/root/InstaPy/instapy/instapy.py", line 109, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 161, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  'File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.4.0-98-generic x86_64)'

## InstaPy configuration
standard configuration just standard I suspect as thought the issue is with in the server. I set up  the 1 GB Memory / 30 GB Disk / NYC1 - Ubuntu 16.04.3 x64. For some reason it doesn't seem to work I have ssh and everything configured and I can enter in but not sure why the program won't run.

**Comment by converge** [comment]
hi @HaginCodes , check it:
1. is chromedriver in assets folder ?
2. chromedriver have +x (is executable) ?
3. seams like youre running it on DG (using terminal), make sure to set nogui=True https://github.com/timgrossmann/InstaPy#running-on-a-server
4. https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md

**Comment by thatc0der** [comment]
thanks for the help I just forgot about that parameter I didn't know it was a thing. Now it works! thank you so much for the help!!
