### ISSUE TITLE
problem running the program on mac

### ISSUE THREAD

**Issue by itsedomil** [InstaPy/InstaPy#918]
when i try to activate the program in terminal it sends me the next error message:
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/adam/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/Users/adam/InstaPy/instapy/instapy.py", line 8, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay
can someone help me understand what's wrong?

**Comment by converge** [comment]
hi @itsedomil , take a look https://github.com/timgrossmann/InstaPy/search?q=pyvirtualdisplay&type=Issues&utf8=%E2%9C%93
