### ISSUE TITLE
Problem while runing quickstart.py first time

### ISSUE THREAD

**Issue by oscaradams21** [InstaPy/InstaPy#944]
```
Traceback (most recent call last):
  File "C:\Users\Maor\Desktop\InstaPy-master\InstaPy-master\quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\Maor\Desktop\InstaPy-master\InstaPy-master\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\Users\Maor\Desktop\InstaPy-master\InstaPy-master\instapy\instapy.py", line 14, in <module>
    from .clarifai_util import check_image
  File "C:\Users\Maor\Desktop\InstaPy-master\InstaPy-master\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Image as ClImage
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\clarifai-2.0.31-py3.6.egg\clarifai\rest\__init__.py", line 3, in <module>
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\clarifai-2.0.31-py3.6.egg\clarifai\rest\client.py", line 21, in <module>
ModuleNotFoundError: No module named 'past'
[Finished in 0.4s with exit code 1]
[shell_cmd: python -u "C:\Users\Maor\Desktop\InstaPy-master\InstaPy-master\quickstart.py"]
[dir: C:\Users\Maor\Desktop\InstaPy-master\InstaPy-master]
[path: C:\Program Files (x86)\Python36-32\Scripts\;C:\Program Files (x86)\Python36-32\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\Lenovo\FusionEngine;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft OLE DB Provider for DB2\system;C:\Program Files\PuTTY\;C:\Python27;C:\Users\Maor\AppData\Local\Microsoft\WindowsApps;]
```

**Comment by converge** [comment]
hi @oscaradams21 , every time you see lines like this:
```ModuleNotFoundError: No module named 'past'```
all you have to do is:
```pip install past```
if it shows command not found, you need to install pip first

**Comment by RomeoJuliett** [comment]
@oscaradams21 Pip should be included in your Python package, but if not use this link to help your  [pip install](https://github.com/BurntSushi/nfldb/wiki/Python-&-pip-Windows-installation)
