### ISSUE TITLE
Message: unknown error: Cannot read property 'entry_data' of undefined

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#953]
Hey boys, 
Got an error few times (every time that I run my script), the script works well but crash after something like 1hour of running, 
Does anyone have a solution?
Cheers, 
Morgan

## Current Behavior

`Traceback (most recent call last):
  File "C:/Users/morga/PycharmProjects/Instagram/interactandlike.py", line 19, in <module>
    session.interact_user_followers(['removedtopost-username', 'removedtopost-username', 'removedtopost-username, 'removedtopost-username', 'removedtopost-username', 'removedtopost-username', 'removedtopost-username', 'removedtopost-username', 'removedtopost-username'], amount=5, random=True)
  File "C:\Users\morga\PycharmProjects\Instagram\instapy\instapy.py", line 1062, in interact_user_followers
    self.user_interact_media)
  File "C:\Users\morga\PycharmProjects\Instagram\instapy\instapy.py", line 755, in like_by_users
    self.like_by_followers_lower_limit)
  File "C:\Users\morga\PycharmProjects\Instagram\instapy\like_util.py", line 471, in check_link
    "return window._sharedData.entry_data."
  File "C:\Users\morga\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 532, in execute_script
    'args': converted_args})['value']
  File "C:\Users\morga\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "C:\Users\morga\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.15063 x86_64)`

**Comment by converge** [comment]
hi @MorganPelissier , this is a know issue, we will focus the conversation here #877
