### ISSUE TITLE
Schedule always crashes

### ISSUE THREAD

**Issue by ethandunford** [InstaPy/InstaPy#966]
## Expected Behavior
Run script at certain time
## Current Behavior
As soon as it's time to start a job chrome will crash

## InstaPy configuration
```python from instapy import InstaPy
import schedule
import random
import time

def run_bot():
    utils.ts('Starting bot')
    try:
        session = InstaPy(username='', password='', nogui=True)
        session.login()
    except Exception as e:
        print('Error --> {0}'.format(e))
        time.sleep(40)
        return

    session.follow_user_followers(['test'], amount=5, random=False, sleep_delay=random.randint(60, 120))
    return


schedule.every().day.at("10:30").do(run_bot)
schedule.every().day.at("12:05").do(run_bot)
schedule.every().day.at("16:23").do(run_bot)
schedule.every().day.at("19:30").do(run_bot)
schedule.every().day.at("21:40").do(run_bot)

while True:
    schedule.run_pending()
    time.sleep(1)
```

**Comment by ethandunford** [comment]
forgot to mention, I've followed the set up guide for digital ocean and the code works fine when inside a while loop. When I put the code inside a function it crashes

System: 1 GB Memory / 20 GB Disk / LON1 - Ubuntu 16.04.3 x64

**Comment by converge** [comment]
@ethandunford , what's the error ?

**Comment by ethandunford** [comment]
@converge  here is the full console output 

Traceback (most recent call last):
  File "test.py", line 54, in <module>
    schedule.run_pending()
  File "/home/ethan/insta_env/lib/python3.5/site-packages/schedule/__init__.py", line 452, in run_pending
    default_scheduler.run_pending()
  File "/home/ethan/insta_env/lib/python3.5/site-packages/schedule/__init__.py", line 75, in run_pending
    self._run_job(job)
  File "/home/ethan/insta_env/lib/python3.5/site-packages/schedule/__init__.py", line 129, in _run_job
    ret = job.run()
  File "/home/ethan/insta_env/lib/python3.5/site-packages/schedule/__init__.py", line 377, in run
    ret = self.job_func()
  File "test.py", line 42, in run_bot
    session.follow_user_followers(['test'], amount=5, random=False, sleep_delay=random.randint(60, 120))
  File "/home/ethan/InstaPy/instapy/instapy.py", line 1147, in follow_user_followers
    self.logger)
  File "/home/ethan/InstaPy/instapy/unfollow_util.py", line 603, in follow_given_user_followers
    callbacks=[])
  File "/home/ethan/InstaPy/instapy/unfollow_util.py", line 342, in follow_through_dialog
    .find_elements_by_tag_name("a")[1].text)
  File "/home/ethan/insta_env/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 68, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/home/ethan/insta_env/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/home/ethan/insta_env/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/ethan/insta_env/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.4.0-101-generic x86_64)

**Comment by sionking** [comment]
Will schedule execute the next job even if the previous did not finish ?

**Comment by ethandunford** [comment]
it doesn't get that far

**Comment by sionking** [comment]
I heard it has a threded way to do it
