### ISSUE TITLE
Is this a bug and how do I fix it?

### ISSUE THREAD

**Issue by clevebounce** [InstaPy/InstaPy#983]
#hkboy #hkgirl #hksalon #hkboys #hkiger #hkig #b5 #化妝 #染髮 #漂頭 #美髮 #扮靚 #負離子 #電髮 #曲髮 #直髮 #剪頭髮 #巴西焗油 #放榜 #畢業 #漂染 #旅行 #韓風 #香港好去處 #髮型屋 #梨花頭 #熱療 #直療 #paimore熱療 #paimore直療
INFO - --> Image Liked!
INFO - --> Not commented
INFO - --> Not following
INFO - [24/900]
INFO - https://www.instagram.com/p/Bbz0UYHFdzr/?tagged=hkig
INFO - Image from: hanabihairsalon
Traceback (most recent call last):
  File "quickstart.py", line 32, in <module>
    session.like_by_tags(['hkig', 'freedom', 'dream', 'happiness', 'lifestyle', 'successdriven'], amount=900)

  File "/Users/user/Downloads/InstaPy-master/instapy/instapy.py", line 640, in like_by_tags
    self.logger)
  File "/Users/user/Downloads/InstaPy-master/instapy/like_util.py", line 481, in check_link
    "return window._sharedData.entry_data."
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.1 x86_64)

C-MacBook-Air:InstaPy-master c$

**Comment by timgrossmann** [comment]
@clevebounce Do you have the latest version of InstaPy and the latest chrome driver for your system?

**Comment by clevebounce** [comment]
Yes I do, both downloaded less than a week ago

**Comment by timgrossmann** [comment]
@clevebounce Have you updated InstaPy in the last day?

**Comment by clevebounce** [comment]
You mean, the one you updated 6 hours ago?

**Comment by converge** [comment]
@clevebounce yes

**Comment by clevebounce** [comment]
Let me try and report back

**Comment by clevebounce** [comment]
This issue has be solved. Thank you.

**Comment by johnvfitness** [comment]
hi guys where is update please for fix bug 
because I have the same problem
