### ISSUE TITLE
WebDriverException: Message: unknown error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by tuxity** [InstaPy/InstaPy#985]
Hi there! I'm having issues to run the script directly with python. I'm using the latest version of the repo (7a6c9ff98e2db42881d1acff08342b6752796bed)

## Current Behavior
```
# python3 quickstart.py
INFO - Session started - 2017-11-23 23:15:51
INFO - Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session.login()
  File "/home/tuxity/InstaPy/instapy/instapy.py", line 216, in login
    log_follower_num(self.browser, self.username)
  File "/home/tuxity/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.9.0-3-amd64 x86_64)
```

## Possible Solution (optional)
I've checked directly into my browser [the javascript code](https://github.com/timgrossmann/InstaPy/blob/master/instapy/print_log_writer.py#L10#L12) to get the followers and it's working (at least with a `console.log`, not a `return`) Somehow it's not working within the code.

## InstaPy configuration
Exactly the same as quickstart.py inside the repository

**Comment by tuxity** [comment]
Okay, I was using my email as login instead of username. So obviously `https://www.instagram.com/EMAIL/ isn't an existing page ...
