### ISSUE TITLE
when i try launching quickstart.py i get this responce 

### ISSUE THREAD

**Issue by drcyber975** [InstaPy/InstaPy#999]
when i try launching quickstart.py i get this responce:
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/home/lubuntu/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/home/lubuntu/InstaPy/instapy/instapy.py", line 15, in <module>
    from .comment_util import comment_image
  File "/home/lubuntu/InstaPy/instapy/comment_util.py", line 8, in <module>
    import emoji
ImportError: No module named emoji

so i then tried installing emoji on ubuntu using the followng commands
sudo pip install emoji,
pip install emoji 
sudo apt-get install emoji
i have tried a few other commands to install it but none seems to work or if i do install a version of emoji i stillr ecieve the same message > ImportError: No module named emoji
its been a few days now i havent been able to figure it out please can someone help me?

**Comment by mjortberg521** [comment]
Try the steps described in issue #297
